<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- begin _includes/seo.html -->
  <title>SOLIDWORKS C# API - Edit Solidworks Feature Sketch - The CAD Coder</title>
  <meta name="description" content="Objective">



  <meta property="og:type" content="article">
  <meta property="og:locale" content="en_US">
  <meta property="og:site_name" content="The CAD Coder">
  <meta property="og:title" content="SOLIDWORKS C# API - Edit Solidworks Feature Sketch">
  <meta property="og:url" content="https://thecadcoder.com/solidworks-csharp/edit-solidworks-feature-sketch/">


  <meta property="og:description" content="Objective">







  <meta property="article:published_time" content="2024-10-29T13:58:17-04:00">






  <link rel="canonical" href="https://thecadcoder.com/solidworks-csharp/edit-solidworks-feature-sketch/">




  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": null,
      "url": "https://thecadcoder.com/"
    
  }
</script>







  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117501871-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-117501871-2', { 'anonymize_ip': true });
  </script>

  <!-- end _includes/seo.html -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">
  <link href="/feed.xml" type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/main.css">

  <meta name="google-site-verification" content="OeSBbUv_kXDkDxaeoLixjE1BYxlbQRINt58H1UGbSMY" />


</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
      <img src="/assets/logo.png" width="30" height="30" class="img-fluid" alt="">
      <span>The CAD Coder</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/vba/vba-Introduction/"><span>VBA</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/Solidworks-macro-guide/"><span>Solidworks VBA Macro</span></a>
        </li>


        <li class="nav-item">
          <a class="active nav-link" style="border-bottom: 1px solid #fff;"
            href="/Solidworks-csharp-api-tutorials/"><span>Solidworks C# API</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/Solidworks-cpp-api-tutorials/"><span>Solidworks C++ API</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/wpf-tutorials/syncfusion-account-signup/"><span>WPF Tutorials</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/knowledge-base/introduction/"><span>My Knowledge Base</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/resources/"><span>Resources</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/aboutMe/"><span>About</span></a>
        </li>

        <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li> -->
      </ul>
      <!-- <a class="btn btn-outline-success my-2 my-sm-0" href="/seach-document/" role="button">
            <i class="fas fa-search"></i>
        </a> -->
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-lg-2 col-sm-4">
        <div class="sidebar sticky" style="width: 100%;">











          <nav class="nav__list">

            <input id="ac-toc" name="accordion-toc" type="checkbox" />
            <label for="ac-toc">Toggle Menu</label>
            <ul class="nav__items">

              <li>

                <span class="nav__sub-title">Getting Started</span>



                <ul>

                  <li><a href="/Solidworks-csharp-api-tutorials/">Introduction</a></li>

                  <li><a href="/solidworks-csharp/Prerequisite/">Prerequisite</a></li>

                  <li><a href="/solidworks-csharp/open-solidworks/">Open Solidworks</a></li>

                  <li><a href="/solidworks-csharp/open-solidworks-document/">Open Solidworks Document</a></li>

                  <li><a href="/solidworks-csharp/browse-and-open-solidworks-file/">Browse/Open SOLIDWORKS Document</a>
                  </li>

                  <li><a href="/solidworks-csharp/unit-correction/">Fix Unit Issue</a></li>

                </ul>

              </li>

              <li>

                <span class="nav__sub-title">Sketch Segment</span>



                <ul>

                  <li><a href="/solidworks-csharp/insert-sketch/">Insert Solidworks Sketch</a></li>

                  <li><a href="/solidworks-csharp/edit-sketch/">Edit Solidworks Sketch</a></li>

                  <li><a href="/solidworks-csharp/edit-solidworks-feature-sketch/" class="active">Edit Solidworks
                      Feature Sketch</a></li>

                  <li><a href="/solidworks-csharp/change-sketch-name/">Change Sketch Name</a></li>

                  <li><a href="/solidworks-csharp/delete-selected-sketch/">Delete Selected Sketch</a></li>

                </ul>

              </li>

              <li>

                <span class="nav__sub-title">Sketch Lines</span>



                <ul>

                  <li><a href="/solidworks-csharp/create-line/">Create Line</a></li>

                </ul>

              </li>

              <li>

                <span class="nav__sub-title">Others</span>



                <ul>

                  <li><a href="/solidworks-csharp/update-dimension-state/">Update Dimension State</a></li>

                </ul>

              </li>

            </ul>
          </nav>



        </div>

      </div>
      <div class="col-md-9 col-lg-10 col-sm-8">
        <div>
          <div id="main" role="main">

            <article class="page" itemscope itemtype="https://schema.org/CreativeWork">

              <meta itemprop="headline" content="SOLIDWORKS C# API - Edit Solidworks Feature Sketch">

              <meta itemprop="description" content="Objective">


              <meta itemprop="datePublished" content="2024-10-29T13:58:17-04:00">


              <div class="page__inner-wrap">

                <header>
                  <h1 id="page-title" class="page__title" itemprop="headline">SOLIDWORKS C# API - Edit Solidworks
                    Feature Sketch
                  </h1>


                  <p class="page__meta">








                    <span class="page__meta-readtime">
                      <i class="far fa-clock" aria-hidden="true"></i>

                      1 minute read

                    </span>

                  </p>


                </header>


                <section class="page__content" itemprop="text">

                  <aside class="sidebar__right sticky">
                    <nav class="toc">
                      <header>
                        <h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4>
                      </header>
                      <ul class="toc__menu">
                        <li><a href="#objective">Objective</a></li>
                        <li><a href="#demo-video">Demo Video</a>
                          <ul>
                            <li><a href="#update-method---selectsketch">Update Method - SelectSketch</a></li>
                          </ul>
                        </li>
                        <li><a href="#final-result">FINAL RESULT</a></li>
                      </ul>

                      <br />
                      <script async
                        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
                        crossorigin="anonymous"></script>
                      <!-- Vertical Ads -->
                      <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002"
                        data-ad-slot="4311368222" data-ad-format="auto" data-full-width-responsive="true"></ins>
                      <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                      </script>
                    </nav>
                  </aside>

                  <div>
                    <script async
                      src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
                      crossorigin="anonymous"></script>
                    <!-- Horizontal Ads -->
                    <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002"
                      data-ad-slot="6007593278" data-ad-format="auto" data-full-width-responsive="true"></ins>
                    <script>
                      (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                    <h2 id="objective">Objective</h2>

                    <p>I want to:</p>

                    <ul>
                      <li>
                        <p><strong><em>Edit Feature Sketch into Solidworks Part Document using Solidworks C#
                              API</em></strong></p>
                      </li>
                      <li>
                        <p><strong><em>We will use same code from previous article üöÄ <a
                                href="/solidworks-csharp/edit-sketch/" target="_blank">Edit Solidworks
                                Sketch</a></em></strong>.</p>
                      </li>
                      <li>
                        <p><strong><em>Extend article by adding Solidworks C# API to previous code.</em></strong></p>
                      </li>
                    </ul>

                    <hr />

                    <h2 id="demo-video">Demo Video</h2>

                    <p>Please see below video on how to ‚Äú<strong>Edit Feature Sketch into Solidworks Part
                        Document</strong>‚Äù using <strong>Solidworks C# API</strong> from <strong>WPF
                        Application</strong>.</p>

                    <iframe src="https://www.youtube.com/embed/UJVSWyHRLwA" frameborder="0" allowfullscreen=""></iframe>
                    <p><br /></p>

                    <p class="notice--info">Please note that there are <strong>no explanation</strong> in the
                      video.<br />
                      <strong>Explanation</strong> of each step and why we write code this way is given in this post.
                    </p>

                    <hr />

                    <h3 id="update-method---selectsketch">Update Method - SelectSketch</h3>

                    <p>In this section, we update <em>SelectSketch method</em> for <strong>selecting Feature
                        Sketch</strong>.</p>

                    <p>Please see below üëáüèª image for sketch we want to edit.</p>

                    <p><a
                        href="/assets/solidworks-csharp-images/edit-solidworks-feature-sketch/feature-sketch-we-want-to-edit.png"><img
                          src="/assets/solidworks-csharp-images/edit-solidworks-feature-sketch/feature-sketch-we-want-to-edit.png"
                          alt="feature-sketch-we-want-to-edit" /></a></p>

                    <p>For editing we need to update below üëáüèª line.</p>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="kt">bool</span> <span class="n">isSelect</span> <span class="p">=</span> <span class="n">swDoc</span><span class="p">?.</span><span class="n">Extension</span><span class="p">.</span><span class="nf">SelectByID2</span><span class="p">(</span><span class="s">"Circle"</span><span class="p">,</span> <span class="s">"SKETCH"</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="k">false</span><span class="p">,</span> <span class="m">4</span><span class="p">,</span> <span class="k">null</span><span class="p">,</span> <span class="p">(</span><span class="kt">int</span><span class="p">)</span><span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span> <span class="p">??</span> <span class="k">false</span><span class="p">;</span>
</code></pre>
                      </div>
                    </div>

                    <p>In above code, we need to replace ‚Äú<strong><code
                          class="language-plaintext highlighter-rouge">Circle</code></strong>‚Äù with ‚Äú<strong><code
                          class="language-plaintext highlighter-rouge">Sketch2</code></strong>‚Äù value.</p>

                    <p>Please see below üëáüèª image for value we required.</p>

                    <p><a
                        href="/assets/solidworks-csharp-images/edit-solidworks-feature-sketch/value-to-select.png"><img
                          src="/assets/solidworks-csharp-images/edit-solidworks-feature-sketch/value-to-select.png"
                          alt="value-to-select" /></a></p>

                    <p>After updating <em>SelectSketch method</em> will look like below.</p>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">private</span> <span class="kt">bool</span> <span class="nf">SelectSketch</span><span class="p">()</span>
<span class="p">{</span>
    <span class="n">swDoc</span> <span class="p">=</span> <span class="k">null</span><span class="p">;</span>
    <span class="n">swDoc</span> <span class="p">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span><span class="p">;</span>

    <span class="kt">bool</span> <span class="n">isSelect</span> <span class="p">=</span> <span class="n">swDoc</span><span class="p">?.</span><span class="n">Extension</span><span class="p">.</span><span class="nf">SelectByID2</span><span class="p">(</span><span class="s">"Sketch2"</span><span class="p">,</span> <span class="s">"SKETCH"</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="k">false</span><span class="p">,</span> <span class="m">4</span><span class="p">,</span> <span class="k">null</span><span class="p">,</span> <span class="p">(</span><span class="kt">int</span><span class="p">)</span><span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span> <span class="p">??</span> <span class="k">false</span><span class="p">;</span>

    <span class="k">return</span> <span class="n">isSelect</span><span class="p">;</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <hr />

                    <h2 id="final-result">FINAL RESULT</h2>

                    <p>For Demo, we already had feature whose sketch we want to edit with our program.</p>

                    <p>Please see below üëáüèª image for reference.</p>

                    <p><a
                        href="/assets/solidworks-csharp-images/edit-solidworks-feature-sketch/feature-sketch-we-want-to-edit.png"><img
                          src="/assets/solidworks-csharp-images/edit-solidworks-feature-sketch/feature-sketch-we-want-to-edit.png"
                          alt="feature-sketch-we-want-to-edit" /></a></p>

                    <p>Now, we have done everything needed to <strong>Edit Solidwork Feature Sketch</strong> into
                      <em>Solidworks Document</em> through our application.</p>

                    <p>Please see below image for final result of our work.</p>

                    <ul>
                      <li>Edit Sketch with <strong><code
                            class="language-plaintext highlighter-rouge">ExecuteEditSketchMethod()</code></strong>
                        method</li>
                    </ul>

                    <p><a href="/assets/solidworks-csharp-images/edit-solidworks-feature-sketch/result-1.gif"><img
                          src="/assets/solidworks-csharp-images/edit-solidworks-feature-sketch/result-1.gif"
                          alt="result-1" /></a></p>

                    <ul>
                      <li>Edit Sketch with <strong><code
                            class="language-plaintext highlighter-rouge">ExecuteEditSketchOrSingleSketchFeatureMethod()</code></strong>
                        method</li>
                    </ul>

                    <p><a href="/assets/solidworks-csharp-images/edit-solidworks-feature-sketch/result-2.gif"><img
                          src="/assets/solidworks-csharp-images/edit-solidworks-feature-sketch/result-2.gif"
                          alt="result-2" /></a></p>

                    <hr />

                    <p><strong>This is it !!!</strong></p>

                    <p><em>I hope my efforts will helpful to someone!</em></p>

                    <p>If you found anything to <strong>add or update</strong>, please let me know on my
                      <em>e-mail</em>.</p>

                    <p>Hope this post helps you to <strong>Edit Solidworks Sketch</strong> from WPF PRISM Application.
                    </p>

                    <p><em>If you like the post then please share it with your friends also.</em></p>

                    <p><em>Do let me know by you like this post or not!</em></p>

                    <p><em>Till then, Happy learning!!!</em></p>


                  </div>

                  <div>
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Top and Bottom placed Ad -->
                    <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002"
                      data-ad-slot="6644001766" data-ad-format="auto" data-full-width-responsive="true"></ins>
                    <script>
                      (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                  </div>

                </section>

                <footer class="page__meta">






                  <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i>
                      Updated:</strong> <time datetime="2024-10-29T13:58:17-04:00">October 29, 2024</time></p>


                </footer>


                <nav aria-label="Page navigation example">
                  <ul class="pagination justify-content-center">

                    <li class="page-item mr-5">
                      <a class="btn btn-primary text-light" href="/solidworks-csharp/edit-sketch/" title="SOLIDWORKS C# API - Edit Solidworks Sketch
">‚ùÆ Previous</a>
                    </li>


                    <li class="page-item ml-5">
                      <a class="btn btn-primary text-light" href="/solidworks-csharp/change-sketch-name/" title="SOLIDWORKS C# API - Change Sketch Name
">Next ‚ùØ</a>
                    </li>

                  </ul>
                </nav>

              </div>
            </article>

          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="footer" class="page__footer">
    <footer>
      <!-- start custom footer snippets -->

      <!-- end custom footer snippets -->
      <footer class="bd-footer py-5 bg-light">
        <div class="container">
          <div class="row">
            <div class="col-6">
              <a class="d-inline-flex align-items-center mb-2 link-dark" href="/" aria-label="Bootstrap">
                <img src="/assets/logo.png" width="30" height="30" class="img-fluid mr-2" alt="">
                <span> The CAD Coder</span>
              </a>
              <ul class="list-unstyled small text-muted">
                <li class="mb-2">Programming Tutorials for SOLIDWORKS 3D CAD Software.</li>
                <li class="mb-2">Copyright ¬© 2022 The CAD Coder</li>
                <li class="mb-2">Built with <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a>.</li>






                <li class="list-inline-item"><a href="https://facebook.com/thecadcoder" target="_blank"
                    title="Facebook"><i class="fab fa-2x fa-facebook-f"></i></a></li>











                <li class="list-inline-item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg"
                    target="_blank" title="YouTube"><i class="fab fa-2x fa-youtube"></i></a></li>



                <li class="list-inline-item"><a href="mailto:thecadcoder@gmail.com" target="_blank" title="Email"><i
                      class="fa fa-envelope fa-2x"></i></a></li>



              </ul>
            </div>
            <div class="col-6">
              <h5>Links</h5>
              <ul class="list-unstyled">
                <!-- <li class="mb-2"><a href="/">Home</a></li> -->
                <li class="mb-2"><a href="/aboutMe/">About</a></li>
                <li class="mb-2"><a href="/resources/">Resources</a></li>
                <li class="mb-2"><a href="/Disclaimer/">Privacy Policy</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </footer>
  </div>


  <script src="/assets/js/main.min.js"></script>




  <script src="/assets/js/lunr/lunr.min.js"></script>
  <script src="/assets/js/lunr/lunr-store.js"></script>
  <script src="/assets/js/lunr/lunr-en.js"></script>







  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->


  <script src="/assets/js/main.min.js"></script>




  <script src="/assets/js/lunr/lunr.min.js"></script>
  <script src="/assets/js/lunr/lunr-store.js"></script>
  <script src="/assets/js/lunr/lunr-en.js"></script>






</body>

</html>