<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- begin _includes/seo.html --><title>SOLIDWORKS C# API - Fix Unit Issue - The CAD Coder</title>
<meta name="description" content="Objective">



<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="SOLIDWORKS C# API - Fix Unit Issue">
<meta property="og:url" content="https://thecadcoder.com/solidworks-csharp/unit-correction/">


  <meta property="og:description" content="Objective">







  <meta property="article:published_time" content="2025-07-22T00:18:05-04:00">






<link rel="canonical" href="https://thecadcoder.com/solidworks-csharp/unit-correction/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": null,
      "url": "https://thecadcoder.com/"
    
  }
</script>







<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-117501871-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-117501871-2', { 'anonymize_ip': true});
</script>

<!-- end _includes/seo.html -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">
  <link
    href="/feed.xml"
    type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/main.css">

  <meta name="google-site-verification" content="OeSBbUv_kXDkDxaeoLixjE1BYxlbQRINt58H1UGbSMY" />

  

  <!-- MailerLite Universal -->
  <script>
    (function (w, d, e, u, f, l, n) {
      w[f] = w[f] || function () {
        (w[f].q = w[f].q || [])
          .push(arguments);
      }, l = d.createElement(e), l.async = 1, l.src = u,
        n = d.getElementsByTagName(e)[0], n.parentNode.insertBefore(l, n);
    })
      (window, document, 'script', 'https://assets.mailerlite.com/js/universal.js', 'ml');
    ml('account', '1644816');
  </script>
  <!-- End MailerLite Universal -->
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        <img src="/assets/logo.png" width="30" height="30" class="img-fluid" alt="">
        <span>The CAD Coder</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a  class="nav-link"   href="/knowledge-base/introduction/"><span>Knowledge Base</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/vba/vba-Introduction/"><span>VBA</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-macro-guide/"><span>Solidworks VBA Macro</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="active nav-link" style="border-bottom: 1px solid #fff;"   href="/Solidworks-csharp-api-tutorials/"><span>Solidworks C# API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-cpp-api-tutorials/"><span>Solidworks C++ API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/wpf-tutorials/syncfusion-account-signup/"><span>WPF Tutorials</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/knowledge-base/wix4-introduction/"><span>Wix4 Tutorials</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/resources/"><span>Resources</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/aboutMe/"><span>About</span></a>
            </li>
            
            <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li> -->
        </ul>
        <!-- <a class="btn btn-outline-success my-2 my-sm-0" href="/seach-document/" role="button">
            <i class="fas fa-search"></i>
        </a> -->
    </div>
</nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-lg-2 col-sm-4">
  <div class="sidebar sticky" style="width: 100%;">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">Getting Started</span>
        

        
        <ul>
          
            <li><a href="/Solidworks-csharp-api-tutorials/">Introduction</a></li>
          
            <li><a href="/solidworks-csharp/Prerequisite/">Prerequisite</a></li>
          
            <li><a href="/solidworks-csharp/open-solidworks/">Open Solidworks</a></li>
          
            <li><a href="/solidworks-csharp/open-solidworks-document/">Open Solidworks Document</a></li>
          
            <li><a href="/solidworks-csharp/browse-and-open-solidworks-file/">Browse/Open SOLIDWORKS Document</a></li>
          
            <li><a href="/solidworks-csharp/unit-correction/" class="active">Fix Unit Issue</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch Segment</span>
        

        
        <ul>
          
            <li><a href="/solidworks-csharp/insert-sketch/">Insert Solidworks Sketch</a></li>
          
            <li><a href="/solidworks-csharp/edit-sketch/">Edit Solidworks Sketch</a></li>
          
            <li><a href="/solidworks-csharp/edit-solidworks-feature-sketch/">Edit Solidworks Feature Sketch</a></li>
          
            <li><a href="/solidworks-csharp/change-sketch-name/">Change Sketch Name</a></li>
          
            <li><a href="/solidworks-csharp/delete-selected-sketch/">Delete Selected Sketch</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch Lines</span>
        

        
        <ul>
          
            <li><a href="/solidworks-csharp/create-line/">Create Line</a></li>
          
            <li><a href="/solidworks-csharp/create-line-code-refactor/">Create Line Code Refactor</a></li>
          
            <li><a href="/solidworks-csharp/setup-test-project/">Setup Test Project</a></li>
          
            <li><a href="/solidworks-csharp/test-createLine-method/">Test Create Line Method</a></li>
          
            <li><a href="/solidworks-csharp/test-applyunitconversion-method/">Test ApplyUnitConversion Method</a></li>
          
            <li><a href="/solidworks-csharp/test-SelectSketchPlane-method/">Test SelectSketchPlane Method</a></li>
          
            <li><a href="/solidworks-csharp/test-CreatePartDocument-method/">Test CreatePartDocument Method</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Others</span>
        

        
        <ul>
          
            <li><a href="/solidworks-csharp/update-dimension-state/">Update Dimension State</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>

</div>
      <div class="col-md-9 col-lg-10 col-sm-8">
        <div>
          <div id="main" role="main">

  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    
    <meta itemprop="headline" content="SOLIDWORKS C# API - Fix Unit Issue">
    
    <meta itemprop="description" content="Objective">
    
    
    <meta itemprop="datePublished" content="2025-07-22T00:18:05-04:00">
    

    <div class="page__inner-wrap">
      
      <header>
        <h1 id="page-title" class="page__title" itemprop="headline">SOLIDWORKS C# API - Fix Unit Issue
</h1>
        

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          3 minute read
        
      </span>
    
  </p>


      </header>
      

      <section class="page__content" itemprop="text">
        
        <aside class="sidebar__right sticky">
          <nav class="toc">
            <header>
              <h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4>
            </header>
            <ul class="toc__menu"><li><a href="#objective">Objective</a></li><li><a href="#demo-video">Demo Video</a></li><li><a href="#add-unitconversionhelper-class">Add [UnitConversionHelper] class</a></li><li><a href="#add-public-properties">Add [Public Properties]</a></li><li><a href="#add-public-method">Add [Public Method]</a><ul><li><a href="#update-properties-value">Update Properties Value</a></li></ul></li><li><a href="#register-unitconversionhelper">Register [UnitConversionHelper]</a></li></ul>

            <br/>
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Vertical Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="4311368222"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          </nav>
        </aside>
        
        <div>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Horizontal Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="6007593278"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          <h2 id="objective">Objective</h2>

<p>I want to:</p>

<ul>
  <li><strong><em>Fix Unit issue for input values using Solidworks C# API.</em></strong></li>
</ul>

<p class="notice--warning">For more Details on why <strong>Fixing Unit issue</strong>, please visit üöÄ <strong><a href="/solidworks-macros/unit-correction/" target="_blank">Solidworks Macro - Fix Unit Issue</a></strong> article.</p>

<ul>
  <li><strong><em>We will continue from previous article üöÄ <a href="/wpf-tutorials/create-line-ui-part-2/" target="_blank">WPF Tutorials - Create Line UI - Part 2</a> article.</em></strong></li>
</ul>

<hr />

<h2 id="demo-video">Demo Video</h2>

<p>Below üé¨ video shows how to ‚Äú<strong>Fix Unit Issue</strong>‚Äù in Solidworks C# API.</p>

<iframe src="https://www.youtube.com/embed/RwCwaVSdpgI" frameborder="0" allowfullscreen=""></iframe>
<p><br /></p>

<p class="notice--warning">Please note that there are <strong>no explanation</strong> in the video.<br />
<strong>Explanation</strong> of each step and why we write code this way is given in this post.</p>

<hr />

<h2 id="add-unitconversionhelper-class">Add [UnitConversionHelper] class</h2>

<ul>
  <li>First we add <strong><code class="language-plaintext highlighter-rouge">Helper</code></strong> folder in our solution.</li>
  <li>Then we add <strong><code class="language-plaintext highlighter-rouge">UnitConversionHelper</code></strong> class inside ‚Äú<strong><code class="language-plaintext highlighter-rouge">Helper</code></strong>‚Äù folder.</li>
  <li>Please see below üëáüèª image for reference.</li>
</ul>

<p><a href="/assets/solidworks-csharp-images/unit-correction/add-unitconversion-helper.png"><img src="/assets/solidworks-csharp-images/unit-correction/add-unitconversion-helper.png" alt="add-unitconversion-helper" /></a></p>

<hr />

<h2 id="add-public-properties">Add [Public Properties]</h2>

<ul>
  <li>First we need to create a region.
    <ul>
      <li><strong>Region Name</strong>: <em>Public Properties</em></li>
    </ul>
  </li>
  <li>Inside this region, we we need <strong>2 properties</strong>.</li>
  <li>Please see below üëáüèª for code reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">#region Public Properties
</span><span class="k">public</span> <span class="kt">double</span> <span class="n">LengthConversionFactor</span> <span class="p">{</span> <span class="k">get</span><span class="p">;</span> <span class="k">set</span><span class="p">;</span> <span class="p">}</span>

<span class="k">public</span> <span class="kt">double</span> <span class="n">AngleConversionFactor</span> <span class="p">{</span> <span class="k">get</span><span class="p">;</span> <span class="k">set</span><span class="p">;</span> <span class="p">}</span>
<span class="cp">#endregion
</span></code></pre></div></div>

<ul>
  <li>In above code, we create 2 properties.
    <ul>
      <li><strong>Name of 1st property</strong>: <strong><code class="language-plaintext highlighter-rouge">LengthConversionFactor</code></strong></li>
      <li><strong>Name of 2nd property</strong>: <strong><code class="language-plaintext highlighter-rouge">AngleConversionFactor</code></strong></li>
      <li><strong>Type of both properties</strong>: <strong><code class="language-plaintext highlighter-rouge">double</code></strong></li>
    </ul>
  </li>
  <li>We expose them as <em>public members</em>, so that we can use them in other classes.</li>
</ul>

<hr />

<h2 id="add-public-method">Add [Public Method]</h2>

<ul>
  <li>
    <p>Now we need to add a method to <strong><code class="language-plaintext highlighter-rouge">UnitConversionHelper</code></strong> class.</p>
  </li>
  <li>First we need to create a region.
    <ul>
      <li><strong>Region Name</strong>: <em>Public Method</em></li>
    </ul>
  </li>
  <li>Inside this Public Method region, we need to create a method.</li>
  <li><strong>Method Name</strong>: <strong><code class="language-plaintext highlighter-rouge">UnitConversion</code></strong></li>
  <li><strong>Method Return Type</strong>: <strong><code class="language-plaintext highlighter-rouge">void</code></strong> [<em>means this method did not return anything</em>]</li>
  <li><strong>Method parameters</strong>:
    <ul>
      <li><strong>Name of parameter</strong>: <strong><code class="language-plaintext highlighter-rouge">swUnit</code></strong></li>
      <li><strong>Type of parameter</strong>: <strong><code class="language-plaintext highlighter-rouge">swLengthUnit_e</code></strong> <em>[Parameter for <code class="language-plaintext highlighter-rouge">Solidworks Length Unit</code> in current document.]</em></li>
    </ul>
  </li>
  <li>
    <p><strong>Method Purpose</strong>: Depending upon the <strong>value</strong> of <strong><code class="language-plaintext highlighter-rouge">swUnit</code></strong> parameter, we will <strong>modify</strong> the values of <strong><code class="language-plaintext highlighter-rouge">LengthConversionFactor</code></strong> and <strong><code class="language-plaintext highlighter-rouge">AngleConversionFactor</code></strong> properties.</p>
  </li>
  <li>Please see below üëáüèª for code reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">#region Public Method
</span><span class="k">public</span> <span class="k">void</span> <span class="nf">UnitConversion</span><span class="p">(</span><span class="n">swLengthUnit_e</span> <span class="n">swUnit</span><span class="p">)</span>
<span class="p">{</span>
    
<span class="p">}</span>
<span class="cp">#endregion
</span></code></pre></div></div>

<ul>
  <li>Please see below üëáüèª image for reference.</li>
</ul>

<p><a href="/assets/solidworks-csharp-images/unit-correction/add-method.png"><img src="/assets/solidworks-csharp-images/unit-correction/add-method.png" alt="add-method" /></a></p>

<h3 id="update-properties-value">Update Properties Value</h3>

<ul>
  <li>Now we need to update values of <strong><code class="language-plaintext highlighter-rouge">LengthConversionFactor</code></strong> and <strong><code class="language-plaintext highlighter-rouge">AngleConversionFactor</code></strong> properties.</li>
  <li>For this, we will use <strong><code class="language-plaintext highlighter-rouge">if-else if</code></strong> conditional statement.</li>
  <li>Please see below üëáüèª for code reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">#region Public Method
</span><span class="k">public</span> <span class="k">void</span> <span class="nf">UnitConversion</span><span class="p">(</span><span class="n">swLengthUnit_e</span> <span class="n">swUnit</span><span class="p">)</span>
<span class="p">{</span>
    <span class="k">if</span> <span class="p">(</span><span class="n">swUnit</span> <span class="p">==</span> <span class="n">swLengthUnit_e</span><span class="p">.</span><span class="n">swMETER</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">LengthConversionFactor</span> <span class="p">=</span> <span class="n">AngleConversionFactor</span> <span class="p">=</span> <span class="m">1</span><span class="p">;</span>
    <span class="p">}</span>
    <span class="k">else</span> <span class="k">if</span> <span class="p">(</span><span class="n">swUnit</span> <span class="p">==</span> <span class="n">swLengthUnit_e</span><span class="p">.</span><span class="n">swMM</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">LengthConversionFactor</span> <span class="p">=</span> <span class="m">1</span> <span class="p">/</span> <span class="m">1000</span><span class="p">;</span>
        <span class="n">AngleConversionFactor</span> <span class="p">=</span> <span class="m">1</span> <span class="p">*</span> <span class="m">0.01745329</span><span class="p">;</span>
    <span class="p">}</span>
    <span class="k">else</span> <span class="k">if</span> <span class="p">(</span><span class="n">swUnit</span> <span class="p">==</span> <span class="n">swLengthUnit_e</span><span class="p">.</span><span class="n">swCM</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">LengthConversionFactor</span> <span class="p">=</span> <span class="m">1</span> <span class="p">/</span> <span class="m">100</span><span class="p">;</span>
        <span class="n">AngleConversionFactor</span> <span class="p">=</span> <span class="m">1</span> <span class="p">*</span> <span class="m">0.01745329</span><span class="p">;</span>
    <span class="p">}</span>
    <span class="k">else</span> <span class="k">if</span> <span class="p">(</span><span class="n">swUnit</span> <span class="p">==</span> <span class="n">swLengthUnit_e</span><span class="p">.</span><span class="n">swINCHES</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">LengthConversionFactor</span> <span class="p">=</span> <span class="m">1</span> <span class="p">*</span> <span class="m">0.0254</span><span class="p">;</span>
        <span class="n">AngleConversionFactor</span> <span class="p">=</span> <span class="m">1</span> <span class="p">*</span> <span class="m">0.01745329</span><span class="p">;</span>
    <span class="p">}</span>
    <span class="k">else</span> <span class="k">if</span> <span class="p">(</span><span class="n">swUnit</span> <span class="p">==</span> <span class="n">swLengthUnit_e</span><span class="p">.</span><span class="n">swFEET</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">LengthConversionFactor</span> <span class="p">=</span> <span class="m">1</span> <span class="p">*</span> <span class="p">(</span><span class="m">0.0254</span> <span class="p">*</span> <span class="m">12</span><span class="p">);</span>
        <span class="n">AngleConversionFactor</span> <span class="p">=</span> <span class="m">1</span> <span class="p">*</span> <span class="m">0.01745329</span><span class="p">;</span>
    <span class="p">}</span>
    <span class="k">else</span> <span class="k">if</span> <span class="p">(</span><span class="n">swUnit</span> <span class="p">==</span> <span class="n">swLengthUnit_e</span><span class="p">.</span><span class="n">swFEETINCHES</span><span class="p">)</span>
    <span class="p">{</span>
        <span class="n">LengthConversionFactor</span> <span class="p">=</span> <span class="m">1</span> <span class="p">*</span> <span class="m">0.0254</span><span class="p">;</span>
        <span class="n">AngleConversionFactor</span> <span class="p">=</span> <span class="m">1</span> <span class="p">*</span> <span class="m">0.01745329</span><span class="p">;</span>
    <span class="p">}</span>
<span class="p">}</span>
<span class="cp">#endregion
</span></code></pre></div></div>

<ul>
  <li>In above code, we are checking value of <strong><code class="language-plaintext highlighter-rouge">swUnit</code></strong> parameter.</li>
  <li>Depending upon the value of <strong><code class="language-plaintext highlighter-rouge">swUnit</code></strong> parameter, we will update values of <strong><code class="language-plaintext highlighter-rouge">LengthConversionFactor</code></strong> and <strong><code class="language-plaintext highlighter-rouge">AngleConversionFactor</code></strong> properties accordingly.</li>
</ul>

<hr />

<h2 id="register-unitconversionhelper">Register [UnitConversionHelper]</h2>

<ul>
  <li>Now we need to register <strong><code class="language-plaintext highlighter-rouge">UnitConversionHelper</code></strong> class into <em>DI container</em>.</li>
  <li>After registering class, we can create instance of <strong><code class="language-plaintext highlighter-rouge">UnitConversionHelper</code></strong> class through DI container.</li>
  <li>For this, go to ‚Äú<strong><code class="language-plaintext highlighter-rouge">App.xaml.cs</code></strong>‚Äù class.</li>
  <li>In ‚Äú<strong><code class="language-plaintext highlighter-rouge">App.xaml.cs</code></strong>‚Äù class, inside <strong><code class="language-plaintext highlighter-rouge">RegisterTypes</code></strong> method, we register <strong><code class="language-plaintext highlighter-rouge">UnitConversionHelper</code></strong> method into <em>DI container</em>.</li>
  <li>Please see below üëáüèª for code reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">protected</span> <span class="k">override</span> <span class="k">void</span> <span class="nf">RegisterTypes</span><span class="p">(</span><span class="n">IContainerRegistry</span> <span class="n">containerRegistry</span><span class="p">)</span>
<span class="p">{</span>
    <span class="n">containerRegistry</span><span class="p">.</span><span class="n">Register</span><span class="p">&lt;</span><span class="n">PointViewModel</span><span class="p">&gt;();</span>
    <span class="n">containerRegistry</span><span class="p">.</span><span class="n">RegisterSingleton</span><span class="p">&lt;</span><span class="n">UnitConversionHelper</span><span class="p">&gt;();</span>
<span class="p">}</span>
</code></pre></div></div>

<ul>
  <li>Please see below üëáüèª image for reference.</li>
</ul>

<p><a href="/assets/solidworks-csharp-images/unit-correction/register-helper-class.png"><img src="/assets/solidworks-csharp-images/unit-correction/register-helper-class.png" alt="register-helper-class" /></a></p>

<ul>
  <li>In above code, we register <strong><code class="language-plaintext highlighter-rouge">UnitConversionHelper</code></strong> class as <strong><code class="language-plaintext highlighter-rouge">Singleton</code></strong>.</li>
  <li>By doing this, we only has <em>single instance</em> of <strong><code class="language-plaintext highlighter-rouge">UnitConversionHelper</code></strong> class in our application.</li>
</ul>

<hr />

<p><strong>This is it !!!</strong></p>

<p><em>I hope my efforts will helpful to someone!</em></p>

<p>If you found anything to <strong>add or update</strong>, please let me know on my <em>e-mail</em>.</p>

<p>Hope this post helps you to <strong>fix Unit issue</strong> in Solidworks application.</p>

<p><em>If you like the post then please share it with your friends also.</em></p>

<p><em>Do let me know by you like this post or not!</em></p>

<p><em>Till then, Happy learning!!!</em></p>


        </div>
        
        <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

      </section>

      <footer class="page__meta">
        
        


        

  <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i> Updated:</strong> <time datetime="2025-07-22T00:18:05-04:00">July 22, 2025</time></p>


      </footer>

      
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    
    <li class="page-item mr-5">
      <a class="btn btn-primary text-light" href="/solidworks-csharp/browse-and-open-solidworks-file/" title="SOLIDWORKS C# API - Browse/Open SOLIDWORKS Document
">‚ùÆ Previous</a>
    </li>
    
    
    <li class="page-item ml-5">
      <a class="btn btn-primary text-light" href="/solidworks-csharp/insert-sketch/" title="SOLIDWORKS C# API - Insert Solidworks Sketch
">Next ‚ùØ</a>
    </li>
    
  </ul>
</nav>

    </div>
  </article>

</div>

          <div class="ml-embedded" data-form="s7QtnY"></div>
        </div>
      </div>
    </div>
  </div>

  <div id="footer" class="page__footer">
    <footer>
      <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
      <footer class="bd-footer py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <a class="d-inline-flex align-items-center mb-2 link-dark" href="/" aria-label="Bootstrap">
          <img src="/assets/logo.png" width="30" height="30" class="img-fluid mr-2" alt="">
          <span> The CAD Coder</span>
        </a>
        <ul class="list-unstyled small text-muted">
          <li class="mb-2">Programming Tutorials for SOLIDWORKS 3D CAD Software.</li>
          <li class="mb-2">Copyright ¬© 2022 The CAD Coder</li>
          <li class="mb-2">Built with <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a>.</li>

          
          
          
          
          
          <li class="list-inline-item"><a href="https://facebook.com/thecadcoder" target="_blank" title="Facebook"><i
                class="fab fa-2x fa-facebook-f"></i></a></li>
          
          
          
          
          
          
          
          
          
          
          
          <li class="list-inline-item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" title="YouTube"><i
                class="fab fa-2x fa-youtube"></i></a></li>
          
          
          
          <li class="list-inline-item"><a href="mailto:thecadcoder@gmail.com" target="_blank" title="Email"><i
                class="fa fa-envelope fa-2x"></i></a></li>
          
          
          
        </ul>
      </div>
      <div class="col-6">
        <h5>Links</h5>
        <ul class="list-unstyled">
          <!-- <li class="mb-2"><a href="/">Home</a></li> -->
          <li class="mb-2"><a href="/aboutMe/">About</a></li>
          <li class="mb-2"><a href="/resources/">Resources</a></li>
          <li class="mb-2"><a href="/privacy-policy/">Privacy Policy</a></li>
          <li class="mb-2"><a href="/Disclaimer/">Disclaimer</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
    </footer>
  </div>

  
  <script src="/assets/js/main.min.js"></script>




<script src="/assets/js/lunr/lunr.min.js"></script>
<script src="/assets/js/lunr/lunr-store.js"></script>
<script src="/assets/js/lunr/lunr-en.js"></script>







  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->

  
  <script src="/assets/js/main.min.js"></script>




<script src="/assets/js/lunr/lunr.min.js"></script>
<script src="/assets/js/lunr/lunr-store.js"></script>
<script src="/assets/js/lunr/lunr-en.js"></script>






</body>

</html>