<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="generator" content="Docusaurus v2.0.0-alpha.66">
<link rel="preconnect" href="https://www.google-analytics.com">
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-117501871-2","auto"),ga("set","anonymizeIp",!0),ga("send","pageview")</script>
<script async src="https://www.google-analytics.com/analytics.js"></script><title data-react-helmet="true">Open new Assembly and Drawing document | The Cad Coder</title><meta data-react-helmet="true" name="twitter:card" content="summary_large_image"><meta data-react-helmet="true" name="docusaurus_language" content="en"><meta data-react-helmet="true" name="docusaurus_version" content="current"><meta data-react-helmet="true" name="docusaurus_tag" content="docs-default-current"><meta data-react-helmet="true" property="og:title" content="Open new Assembly and Drawing document | The Cad Coder"><meta data-react-helmet="true" name="description" content="In this post, we learn how can we Open new Assembly and Drawing document from a Visual Basic for Application&#x27;s Userform."><meta data-react-helmet="true" property="og:description" content="In this post, we learn how can we Open new Assembly and Drawing document from a Visual Basic for Application&#x27;s Userform."><meta data-react-helmet="true" property="og:url" content="https://prashantbaher.github.io//docs/vba-userform/vba-userforms-open--ass-doc"><link data-react-helmet="true" rel="shortcut icon" href="/img/logo.png"><link data-react-helmet="true" rel="canonical" href="https://prashantbaher.github.io//docs/vba-userform/vba-userforms-open--ass-doc"><link rel="stylesheet" href="/styles.f7ef45b3.css">
<link rel="preload" href="/styles.e684f388.js" as="script">
<link rel="preload" href="/runtime~main.10187eec.js" as="script">
<link rel="preload" href="/main.d90b1f90.js" as="script">
<link rel="preload" href="/1.1af7f77d.js" as="script">
<link rel="preload" href="/2.4f0019c3.js" as="script">
<link rel="preload" href="/94.4b40930d.js" as="script">
<link rel="preload" href="/95.2f44d2c3.js" as="script">
<link rel="preload" href="/f976f453.e3619938.js" as="script">
<link rel="preload" href="/17896441.361bff39.js" as="script">
<link rel="preload" href="/b368aa39.ccfd3589.js" as="script">
</head>
<body>
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><div aria-label="Navigation bar toggle" class="navbar__toggle" role="button" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></div><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a><div class="navbar__item dropdown dropdown--hoverable dropdown--left"><a class="navbar__item navbar__link">VBA</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li><a class="dropdown__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></div><a class="navbar__item navbar__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a><a class="navbar__item navbar__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></div><div class="navbar__items navbar__items--right"><div class="navbar__item dropdown dropdown--hoverable dropdown--right"><a class="navbar__item navbar__link">About</a><ul class="dropdown__menu"><li><a class="dropdown__link" position="right" href="/docs/about">About Me</a></li><li><a class="dropdown__link" position="right" href="/docs/resources">Resources</a></li><li><a class="dropdown__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></div><div class="react-toggle react-toggle--disabled displayOnlyInLargeViewport_2aTZ"><div class="react-toggle-track"><div class="react-toggle-track-check"><span class="toggle_BsTx">ðŸŒœ</span></div><div class="react-toggle-track-x"><span class="toggle_BsTx">ðŸŒž</span></div></div><div class="react-toggle-thumb"></div><input type="checkbox" disabled="" aria-label="Dark mode toggle" class="react-toggle-screenreader-only"></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div><div class="navbar-sidebar"><div class="navbar-sidebar__brand"><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a></div><div class="navbar-sidebar__items"><div class="menu"><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">VBA</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></li><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">About</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/about">About Me</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/resources">Resources</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></li></ul></div></div></div></nav><div class="main-wrapper"><div class="docPage_2gpo"><div class="docSidebarContainer_3_JD" role="complementary"><div class="sidebar_2urC"><div class="menu menu--responsive menu_5FrY"><button aria-label="Open Menu" aria-haspopup="true" class="button button--secondary button--sm menu__button" type="button"><svg aria-label="Menu" class="sidebarMenuIcon_Dm3K" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 32 32" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><ul class="menu__list"><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!">Introduction</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-userforms">VBA UserForms</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-userform/vba-userforms-open-part">Open new Part document</a></li><li class="menu__list-item"><a aria-current="page" class="menu__link menu__link--active active" tabindex="0" href="/docs/vba-userform/vba-userforms-open--ass-doc">Open new Assembly and Drawing document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-userform/vba-userforms-open-part-test">Testing Open new Assembly and Drawing document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-userform/vba-userforms-browse-files">Browse SOLIDWORKS file(s)</a></li></ul></li></ul></div></div></div><main class="docMainContainer_3EyW"><div class="container padding-vert--lg docItemWrapper_1EkI"><div class="row"><div class="col docItemCol_2ASc"><div class="docItemContainer_3QWW"><article><header><h1 class="docTitle_1Lrw">Open new Assembly and Drawing document</h1></header><div class="markdown"><p>In this post, we learn how can we <strong>Open new Assembly and Drawing document</strong> from a Visual Basic for Application&#x27;s <strong>Userform</strong>.</p><p>For this please we need to do following steps as described below.</p><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="video-of-code-on-youtube"></a>Video of Code on YouTube<a aria-hidden="true" tabindex="-1" class="hash-link" href="#video-of-code-on-youtube" title="Direct link to heading">#</a></h2><p>Please see below video how visually we <em>Open new Assembly and Drawing document</em> in <strong>Solidworks VBA macro Userform</strong>.</p><div class="youtube-responsive-container"><iframe src="https://www.youtube.com/embed/AQ3Fyw78ExI" frameborder="0"></iframe></div><p>Please note that there are <strong>no explanation</strong> in the video. </p><p><strong>Explanation</strong> of each line and why we write code this way is given in this post.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="create-a-new-macro"></a>Create a new macro<a aria-hidden="true" tabindex="-1" class="hash-link" href="#create-a-new-macro" title="Direct link to heading">#</a></h2><p>1st we need to create a <strong>new macro</strong> in <em>Solidworks 3D CAD Software</em>.</p><p>If you don&#x27;t know how to create a new macro in Solidworks, please go to <a href="/solidworks-macro/vba-in-solidworks">VBA in Solidworks</a> post for this.</p><p>This will open a new macro in Visual Basic Editor with some code as shown in below image.</p><p><img alt="open-new-macro" src="/assets/images/open-new-macro-b822f2e9b8c402eebf9f3386f8de3d09.png"> </p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="insert-userform-in-the-macro"></a>Insert userform in the macro<a aria-hidden="true" tabindex="-1" class="hash-link" href="#insert-userform-in-the-macro" title="Direct link to heading">#</a></h2><p>After this we need to insert <em>a userform</em> in our macro.</p><p>For this, select the button shown in below image.</p><p><img alt="insert-userform-into-macro" src="/assets/images/insert-userform-into-macro-4b981270c4f9349b4be7efaa800e712f.png"></p><p>This button is called <strong><em>insert userform</em></strong>. </p><p>As the name suggest, function of this button is <em>inserting a userform</em>.</p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>Please note that in a macro we can insert any number of userform as we like. But for this example we insert only 1 userform.</p></div></div><p>After clicking the <strong><em>insert userform</em></strong> button we get the userform window.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="adding-controls-into-userform"></a>Adding Controls into Userform<a aria-hidden="true" tabindex="-1" class="hash-link" href="#adding-controls-into-userform" title="Direct link to heading">#</a></h2><p>Now in our userform window, we add following controls:</p><ol><li><p><strong>A ComboBox</strong></p></li><li><p><strong>A CommandButton</strong></p></li></ol><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="adding-combobox"></a>Adding ComboBox<a aria-hidden="true" tabindex="-1" class="hash-link" href="#adding-combobox" title="Direct link to heading">#</a></h3><p>You can find <code>ComboBox</code> option, as highlighted in <em>Red Square</em> in below image.</p><p><img alt="insert-combox-into-userform" src="/assets/images/insert-combox-into-userform-cbfcbcc646555660439e14dc8c3b353a.png"></p><p>After adding ComboBox, we get window as shown in below image.</p><p><img alt="combobox-into-userform" src="/assets/images/combobox-into-userform-63ac1d4d4e8021a6b43868f651e6c7cb.png"></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="adding-commandbutton"></a>Adding CommandButton<a aria-hidden="true" tabindex="-1" class="hash-link" href="#adding-commandbutton" title="Direct link to heading">#</a></h3><p>You can find <code>CommandButton</code> option, as highlighted in <em>Red Square</em> in below image.</p><p><img alt="insert-command-button-into-userform" src="/assets/images/insert-command-button-into-userform-1eec72bde036662833f493102f51a14b.png"></p><p>After adding CommandButton, we get window as shown in below image.</p><p><img alt="command-button-into-userform" src="/assets/images/command-button-into-userform-b11cf60652222f0a250f9e952be4c2b0.png"></p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="updating-properties"></a>Updating Properties<a aria-hidden="true" tabindex="-1" class="hash-link" href="#updating-properties" title="Direct link to heading">#</a></h2><p>Now we update some properties of following:</p><ol><li><p><strong>UserForm</strong></p></li><li><p><strong>ComboBox</strong></p></li><li><p><strong>CommandButton</strong></p></li></ol><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="updating-properties-of-the-userform"></a>Updating Properties of the UserForm<a aria-hidden="true" tabindex="-1" class="hash-link" href="#updating-properties-of-the-userform" title="Direct link to heading">#</a></h3><p>We update following properties of the Userform:</p><ol><li><p>Name of Userform</p></li><li><p>Caption of Userform</p></li></ol><p>In below image, I have shown the properties of <code>Userform1</code> and update the properties:</p><p><img alt="update-userform-properties" src="/assets/images/update-userform-properties-59368ef851ec6debed291ae1f9f392d6.png"></p><p>Update the value of <em>Name</em> property from <code>UserForm1</code> to <code>OpenDocumentWindow</code>.</p><ul><li>From <em>Name</em> property, we access the Userform.</li></ul><p>Update the value of <em>Caption</em> property from <code>UserForm1</code> to <code>Open Document</code>.</p><ul><li>From <em>Caption</em> property, we update the text appears in the window of our Userform.</li></ul><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>Please note that it is <strong>not necessary</strong> to update properties but it is a good habit to update them for our purpose. </p></div></div><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="updating-properties-of-the-combobox"></a>Updating Properties of the ComboBox<a aria-hidden="true" tabindex="-1" class="hash-link" href="#updating-properties-of-the-combobox" title="Direct link to heading">#</a></h3><p>Now, we update following property of the ComboBox:</p><ol><li>Name of ComboBox</li></ol><p>In below image, I have shown the properties of <code>ComboBox1</code> and update the properties:</p><p><img alt="update-combobox-properties" src="/assets/images/update-combobox-properties-ef7ff04fbc4228169fe06ad4932f5755.png"></p><p>Update the value of <em>Name</em> property from <code>ComboBox1</code> to <code>DocumentTypeComboBox</code>.</p><ul><li>From <em>Name</em> property, we access the ComboBox.</li></ul><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="updating-properties-of-the-command-button"></a>Updating Properties of the Command Button<a aria-hidden="true" tabindex="-1" class="hash-link" href="#updating-properties-of-the-command-button" title="Direct link to heading">#</a></h3><p>Now, we update following property of the Command Button:</p><ol><li><p>Name of Command Button</p></li><li><p>Caption of Command Button</p></li></ol><p>In below image, I have shown the properties of <code>CommandButton1</code> and update the properties:</p><p><img alt="update-command-button-properties" src="/assets/images/update-command-button-properties-3632a93bb86f0e261f12da770d6737a1.png"></p><p>Update the value of <em>Name</em> property from <code>CommandButton1</code> to <code>OpenDocumentButton</code>.</p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>From <em>Name</em> property, we access the Command Button.</p></div></div><p>Update the value of <em>Caption</em> property from <code>CommandButton1</code> to <code>Open Selected Document</code>.</p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>From <em>Caption</em> property, we update the text appears in the Command Button of our Userform.</p></div></div><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="calling-userform-in-main-module"></a>Calling UserForm in Main Module<a aria-hidden="true" tabindex="-1" class="hash-link" href="#calling-userform-in-main-module" title="Direct link to heading">#</a></h2><p>Now, we need to call the our <em>Userform</em> inside main <strong><em>module</em></strong>.</p><p>For this goto main <code>Sub procedure</code> inside the <strong>main Module</strong>.</p><p>Code inside the main Module is as given below.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As Object</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>To call our <code>Userform</code>, replace above code with below code:</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Calling our window to show</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  OpenDocumentWindow.Show</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>Above function call our window to appears on screen.</p><p>When the window appears on screen, we <em>1st</em> select the document we want to <em>open</em> and <em>then</em> hit the button to open selected document.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="adding-document-list"></a>Adding Document list<a aria-hidden="true" tabindex="-1" class="hash-link" href="#adding-document-list" title="Direct link to heading">#</a></h2><p>Before anything we need to <em>add</em> a <em>list</em> of documents inside our combobox.</p><p>From this list, we select the document which we want to open.</p><p>In this post, we are listing only &quot;<strong>Assembly</strong>&quot; and &quot;<strong>Drawing</strong>&quot; documents.</p><p>For &quot;<strong>Part</strong>&quot; document, I will give you a simple exercise.</p><p>To add documents list inside our combobox, we 1st need to go in <strong>Code Window</strong> of userform.</p><p>For this, we need to <strong>right click</strong> on userform and select &quot;<strong>View Code</strong>&quot; option.</p><p>Please see below image for &quot;<em>how to open code window of userform</em>&quot;.</p><p><img alt="select-view-code-option" src="/assets/images/select-view-code-option-8c6dcbfce1db91dd5a445b011d8be298.png"></p><p>After selecting &quot;<strong>View Code</strong>&quot; a <em>Code window</em> appears, which is shown in below image.</p><p><img alt="behind-userform-code-window" src="/assets/images/behind-userform-code-window-53f7c7ccf79efeedfacece8d9f01c554.png"></p><p>Now <em>before</em> adding document list we need to understand <strong>one important thing</strong>!!!</p><p>We want to add document list, when we <strong>load</strong> our <code>Userform</code>.</p><p>For this we need to create an <code>Initialize Function</code>.</p><p>Below <code>Code</code> is that <code>Initialize Function</code> which load document lists in our combobox.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Call when user load</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Private Sub UserForm_Initialize()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Adding items in Combo Box and also set index to &#x27;0&#x27;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; &#x27;0&#x27; index means by default we can see &quot;Assembly Document&quot; as already filled</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  With DocumentTypeComboBox</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    .AddItem &quot;Assembly Document&quot;    &#x27; Adding Assembly Document in Combo Box</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    .AddItem &quot;Drawing Document&quot;     &#x27; Adding Drawing Document in Combo Box</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    .ListIndex = 0                  &#x27; Select list index for default value to show in combobox</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  End With</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>Now, above code is <strong><em>fully commented</em></strong> and <strong><em>self explanatory</em></strong> hence I will not explain it.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="first-test-of-macro"></a>First Test of Macro<a aria-hidden="true" tabindex="-1" class="hash-link" href="#first-test-of-macro" title="Direct link to heading">#</a></h2><p>After writing code sample in previous section, we will test if every thing is working correct?</p><p>By working correct means:</p><ol><li><p>When we <code>Run</code> macro, is <strong>Open Document</strong> window appears or not?</p></li><li><p>If window appears, then combobox has documents listed in it?</p></li><li><p>If both item listed, then &quot;<strong>Assembly document</strong>&quot; is showing as pre-filled value or not?</p></li><li><p>Since we have not given any functionality to &quot;<strong>Open Document</strong>&quot; button, hence it should not any done anything when clicking!!!</p></li></ol><p>For testing all the above points we need to <code>Run</code> the macro as shown in below image.</p><p><img alt="first-test-of-macro" src="/assets/images/first-test-of-macro-1993ba56e3541062dc3e75f4315bc669.png"></p><p>After running the window we got a window as shown in below image.</p><p><img alt="sample-userform-window" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATcAAADsCAYAAAARrOFqAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAA+VSURBVHhe7ZzbbtzGHYd5U7Qv5Bu9QFMETdOc0NwpBrKAFLtIAjcJ0qINakBNmwRVWwS9CQoD6VWVi6QFBCS2ZFkHWwdbJx9j2TAQv0DeYMr/kLM7HA53pRV3Q/73+wFflhzODMm158sMd73JkydPzKNHj8yDBw/M3bt3ze3bt83BwYHZ29szu7u75tatW+bmzZtmZ2fHbG9vd9na2gIAGBmbm5tdXJnvIHGS+Ek8Jc4Sd92/f988fPjQPH782CRObLOzswAArebw8NDcu3fPCi6R/8iMTQ4QQkhbIw6TWZzM4GTClsh/xHbIjRDS5ojDZKkqS1SZvSWyRt3f30duhJBWRxwmz+fk8wKZvSWyJJWpHHIjhLQ54rCNjQ37AaisRpM7d+7YTxyQGyGkzRGHra+v209SZTWayPRNTIfcCCFtjjhsdXXVLk1lNZrIwzd5CIfcCCFtjjhsZWXF3Lhxw65GE5m+yTQOuRFC2hxx2NWrV83169ftajSRTxbkm7/IjRDS5ojDlpaWus/dElmbyhoVuRFCxpkkSewMqyp29pXWOW6c3NbW1uyELZG1qaxRTyS3xY49qWNq/ig/MOosmo533vGemxBSZ0ReP/rxT6KC63esKuKwy5cvdz9UsHKTNeqx5WbFNmV6Tjky81PjkozIzT93LrvOYr7ftoT3Q8hkJSaxYcQmEYd988035tq1a3bCdkK5ZSIrueRo3kwlnXSojjoRGYzt3KMIciPEl9mwYpOIw77++mv7iak47WRyqxSJSM8N0nzALkrdyNLR9uGWla6vvM18b7kbnwnGZBAIt9B/KOKsbvFY2Ke/X74XaXM0P9XtY/h7k3JXN6X0fwxCJidOasOKTXJ6uU3Np4oI4wsmH7Sunh3wgSxcB+kStzDQ3QC3S9+YRIP2NuVzdz1ROHdWryzNsE9/P78udy/5s8ZuH4XrDPo51r2F5yZkMtMMuUWlI+LwhVAcsIudXDiFmU2OPRC2qRr0sXLv3JHrK577OML09wddl7c/1L2FxwiZvDixyau/fdKcTm6FWZKXgjjCAeu1GUowfiLlfp+R/scrt9P2T8hkJSazYQV3SrmlKS0ZZYD6y71gvzDow7ou4SCvGvSxer5sg/3CuauWpYGw7f1Vyafffnbuk91beIyQyUk/iQ0juNPLTWIF0Ft+9eQiyQZsp9N76F44boXTa3vyZanXNlan0H94vNi+KLS8vNPxzj3ouoL9Ie5NZpa9uoRMTuTvfT95yTGpc9zUI7e+CQczIYSMPiW5yT+/OvG/UOgb5EYIGX/EYYUv8SI3QoiGjEFuhBAy/iA3QojKIDdCiMogN0KIyiA3QojKIDdCiMogN0KIyiA3QojK9JXb999/DwDQSpAbAKgEuQGASpAbAKgEuQGASpAbAKgEuQGASpAbAKgEuQGASpAbAKgEuQGASpAbAKgEuQGASpAbAKgEuQGASpAbAKgEuQGASkpy29vbsxtvvPFGtAEAQBsQh12+fNmsrq6azc1N5AYAOkBuAKAS5AYAKkFuAKAS5AYAKkFuAKCSVsvt0qVLABBBEhszk0Tr5TYzMwMAHk+fPkVuKSrkRoiWiJhOA3LrgdwIaVCcmIaJGw/ILQO5kbElSZJ8i1TlNGJCbkWQGxlbkNvgILf6QG7jyNG8mZqaN0f5bjdV5UqD3AYHudXHBMrtyMxPJSYZp1TqkJvUTeUggnB0FvNjTU1wf8htcJBbfUye3OyA65jO1JSZH5fd6pKbX1f2my644JqR2+Agt/qYOLkdzU+ZqdRqi53EvrpIeXdWlA/IWJmTSlaeC9IOYhFmVt5ZzGeHdrt8vNhO+s3q90S1aDqujksgChu/TLa719VJe3CRvlx5eo75oB/Xh33tcw+ubrev4j3Mp+9n9xy2fq+9IO+1vJL+QW71MWFykwGXD8rFTiCsnhAWO+l2rMyKwhNHPrCtGNxgl3797fB4GivNrlDya5C6ziL+totftxt3PZnAXBPbv90JpZkm7Mft+9cYu4e+9+6do1s/TXAu5DY4yK0+JktuhcEmg9UJJ5NDfMYTDGhb5pMe9/uNbRfOm8b2E7Sz58vOJbPK0G3Fa3fJ2xyr/zyxurLvl8e25XXQvUuq+kkjbUj/ILf6mCi5FZaZOf7SdKDkwoHsUjWg3XbYTvYj/WVS60mukLAPyQn7t4nVDfuIbYftXMLyqn7SILfBQW71MVFyKy3R3BIqHYSdruTypetipOwoE13fWVVsOxjk3WVjUG73S8LNE9bNpZtdS/G6Bi5LPXlGl8jR7WPcuyRs650LuQ0OcquPiZJbYRDayIDtSas4m4uVpbEDtld+LDHE2oR1bbxngmHCPrxneDaF497ML2gncvJnsFOdTu8aY9cVbnt9le5dEuzLbNSeJ71YeSX9g9zqY6Lk1vj4D+MVBrkNDnKrD+TWoEQ/SFAU5DY4yK0+kBshDQpyqw/kRkiDEhOTfb5ZgV8PuRUpyW1/f99uIDdCxp8qMQ0Sm4DciojDrly5YtbW1szW1hZyI+SHTD8x9RObgNyKIDdCGpRBYqoSm4DciiA3QhqU04gJuRVBboQ0KMitPpAbIQ0KcqsP5EZIg4Lc6gO5EdKgILf6QG6ENCjIrT6QGyENCnKrD+RGSIOC3OoDuRHSoCC3+kBuhDQoyK0+kBshDQpyqw/kRkiDgtzqA7kR0qAgt/pAboQ0KMitPpAbIQ2KiEn+Xg8LcuuB3AhpUOTv82lBbhmtl5v8QQJAEeTWcrkRQqoTGzOTRKvlBgBQBXIDAJWU5PaHDy6a3/7u9+bZZ38ebQAA0AZef71j/vThX8zHn/zV/O3v/zDJhXfeM2++fcH89KfPRBsAALSBl195xczMnjfnf/2WdRpyAwAVPPPMz5AbAOhDHIbcAEAdyA0AVILcAEAlyA0AVILcAEAlyA0AVILcAEAlvtwuXpxDbgCgA19uCwtfIDcA0IGT27vvvW9/DCTZ2Ngwy8vLZnZ2NtoAAKANOLl99tm/zPb2dvaTR/LzIPzkEQC0GZHbufNvmqV0sobcAEANIrePPv7ErK+vIzcA0IPI7csvv0JuAKCLF1540f4SL3IDAFWcPXsWuQGAPsRhyA0A1IHcAEAlyA0AVILcAEAlyA0AVILcAEAlyA0AVILcAEAlyA0AVILcAEAlJbkdHBzYjXPnzkUbAAC0AXHY0tKSkR/g3dnZQW4AoAPkBgAqQW4AoBLkBgAqQW4AoJKS3OSrIMgNANpOSW6ff/5v5AYArackt3fefd+srKwgNwBoNSW5XXjnPfPpp/9EbgDQaqJyE/jnVwDQZqJye/PtC+a1185GGwAAtIFKub366qvRBgAAbaBSbi+++FK0AQBAG6iU23PP/SLaAACgDSA3AFBJq+VGCIlnZmYmOmYmiUq5Pf/8L6MNmoTk6dOnAOBx6dIl5JZSKbeXXno52qBJOLnFjgFMKsgto1Juv2rBV0GQG0AZ5JZRKbfp6elogyaB3ADKILeMqNzeevs3rXhzkBtAGeSWEZXbh3/+yB6INWgSyA2gDHLLiMrtPwtfIDeAloLcMkpy++CPF83m5iZyA2gpyC2jJLev/vu/1vwSL3IDKIPcMkpyOzw8tBvIDaCdILcMcdjy8jJymzh258yZM3NmN3asbsZ5LkBuOchthOzOnTFJknQ5M7cbrVcbIpHjnm9Y4QzTLtYmuFZhesE73kSGfc/GDHLLQG4jwoqtMBAWzPQg4ZwK6f+Mmdv19qcXvOMBTZCbXyb7TRfcsO/ZmEFuGchtJISiyXGDw75Om+kzkVlLPsiz8ryPvN3cdKR+FznntFkolOX06dMO1Nhx2zYTcu+cu2bOu2Yr6qq2hfKUUAr++WNlhfb+fQXXNBf04/qwr7332L/24d7ryL13r6lZILcM5DYK3AArHcsFZAeVJ4KF6XTAyAAOBOX6yQdhd1BK/Uj/C25AFmZsffq0fVQczwdzSaLd47Jf1VbKA4l02/Qp6/ZXbG9nwfaeItcU9uP25dW9x/b99ba713jC9zo8V0NBbhnIbRRUDoJ8QJWOS3k6+BaygeVmBxmR+oMGmR3MueSkbr8+Bx0P+/bLj9s21le0/4r3x56n4ppidWXfL49ty+tJrz081lCQWwZyGwm5rNzMzOEPrMIg8eQWGzz9BlwlVSLNqbyW4Hi/8uO2jdXrVxZrPwq5+e0cYXlVPw0GuWUgtxHR9wOFcJAUlkqDloKRfVfmL0e7dQb1WXG837JURGP3q9pKeU/u5fcipXQPfl/FfgcuS7vX453L7z+6XXHt4XWFbb1zNRXkloHcRogdaOkAcnQHkh0kwXLItQuPycDqN+C6FB94D3y47/cROx4pd9fvnu2VP1BIcW3d0ljqTU+XrzdsF850C8er3x+5Jv997p5L6vn3UbXt9XWc97pw765Ow0BuGcjthyAcQAA1gtwykNsPAXKDEYLcMpAbgDKQWwZyA1AGcstAbgDKQG4ZyA1AGcgtA7kBKAO5ZSA3AGUgtwzkBqAM5JaB3ACUgdwyWi83+YMEgCLIreVykz9AAIgTGzOTRKvlBgBQBXIDAJUgNwBQCXIDAJUgNwBQSUlut2/fNjdv3kRuANBqxGFXr141169ft05DbgCgAuQGACpBbgCgEuQGACpBbgCgEuQGACpBbgCgEuQGACpBbgCgEuQGACpBbgCgEuQGACpBbgCgEuQGACpBbgCgEuQGACpBbgCgEuQGACpBbgCgEuQGACpBbgCgEuQGACpBbgCgEuQGACpBbgCgkpLc7ty5Y27dumXOnz8fbQAA0AbEYSsrK+bGjRvWacgNAFSA3ABAJcgNAFSC3ABAJcgNAFSC3ABAJcgNAFSC3ABAJcgNAFSC3ABAJcgNAFSC3ABAJcgNAFQSlZv8PAhyA4A2Iw5zP3lk5eZ+zw25AUCb8eVW+LFK5AYAbQa5AYBKSnLjmRsAaMCXG5+WAoAaxGF8FQQA1OHktrm5aXZ3d5EbAOhAHHbt2jUrt729PZPcvXvXWg65AUCbEYetra2Z7e1ts7+/b5L79+/bDeQGAG1GHLa+vm52dnbMwcGBSR48eGAODw+RGwC0GnGY+6RUvuKWPHz40MhzN+QGAG1GHLa1tWWft8njtuTx48dGZm9yAACgzcisTVai9+7dM8mTJ0/M0dGRkWdvUigfLsiaVQwo3xfZ2Niw69jV1VX7SYR8SW55edksLS2ZK1euAACMBXGOuEccJC4SJ4mbZCkqvvLF9u2335rku+++M77gZIkqFWRqJ6KTf73gZCcfsUpHTngAAKNCPvl0uDJxjzhIXCROEjeJ1MRXvtgePXpk/g8oiLBoaCIxWAAAAABJRU5ErkJggg=="></p><p>Please <strong><em>do check</em></strong> if your macro is running perfectly till now or not!</p><p>If not, then I suggest you to read this article again.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="add-functionality-to-open-newpart-button"></a>Add Functionality to Open NewPart Button<a aria-hidden="true" tabindex="-1" class="hash-link" href="#add-functionality-to-open-newpart-button" title="Direct link to heading">#</a></h2><p>To add functionality in our <code>Open Selected Button</code>, just double click the <code>Open NewPart Button</code>.</p><p>This will add give some code behind the designer and opens the <strong>code window</strong> of Userform designer.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Private Sub OpenDocumentButton_Click()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>We need to update this code for opening new part after clicking the button.</p><p>For this replace all above code with below code.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Private function of Open New Part Button </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Private Sub OpenDocumentButton_Click()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Creating string type variable for storing default Assembly location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  If DocumentTypeComboBox.Value = &quot;Assembly Document&quot; Then</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting value of this string type variable to &quot;Default Assembly template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplateAssembly)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Else</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting value of this string type variable to &quot;Default drawing template&quot; without define paper size</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplateDrawing)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  End If</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Solidworks document to new Assembly document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Hiding the Window after opening the selected document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  OpenDocumentWindow.Hide</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Reset the Index of Combo Box to &quot;0&quot; again</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  DocumentTypeComboBox.ListIndex = 0</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>Now I have added codes in <strong>2 parts</strong>.</p><p>In <strong>1st part</strong> I added below code lines <em>at top</em> of the code window.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div></div></div></div></div><p>Please see below image for more reference.</p><p><img alt="add-code-at-top-of-userform-codewindow" src="/assets/images/add-code-at-top-of-userform-codewindow-bf23525039b13b3541a17582d33b3249.png"></p><p>In <strong>2nd part</strong> I added <code>OpenDocumentButton_Click</code> function in the code window as shown in below image.</p><p><img alt="code-when-button-clicked" src="/assets/images/code-when-button-clicked-9603ffb1fba2b3c7e42e697dec7db67b.png"></p><p>I have already explained code inside <code>OpenDocumentButton_Click</code> function in <a href="/solidworks-macro/open-assembly-and-drawing">Open Assembly and Drawing document</a>.</p><p>But here, I have added a condition which is shown in Red colored box in below image.</p><p><img alt="condition-that-control-opening-document" src="/assets/images/condition-that-control-opening-document-2ac32ef463a4d7ddfc1c0ef4236e74e2.png"></p><p>Basically, this condition stated that, if we select &quot;<em>Assembly Document</em>&quot; in combobox, then by clicking &quot;<em>Open Select Document</em>&quot; button our macro open &quot;<strong>Assembly</strong>&quot; document in <em>Solidworks</em>.</p><p>Otherwise, it will always open &quot;<strong>Drawing</strong>&quot; document in <em>Solidworks</em>.</p><p>The above code will <em>open New part document</em> when we click the button.</p><p><code>Run</code> the macro, and check wheather our macro is working correct document or not!!</p><p>If not, send your macro and I will guide you in doing it correctly! </p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="exercise-to-do"></a>Exercise to do<a aria-hidden="true" tabindex="-1" class="hash-link" href="#exercise-to-do" title="Direct link to heading">#</a></h2><p>For those who wants to do more I have an exercise!!</p><ol><li><p>Add &quot;<strong>Part Document</strong>&quot; in ComboBox list.</p></li><li><p>Make &quot;<strong>Part Document</strong>&quot; as <em>pre-filled</em> value in ComboBox.</p></li><li><p>Change the <strong>conditional statement</strong>, so that it can handle <strong>all 3 conditions</strong>!!</p></li></ol><p>Send me the Code of macro in my below <strong>e-mail</strong> and I will <strong><em>verify</em></strong> it. </p><p>That&#x27;s it for now.</p><p>Hope you learn some use of Userforms and by this post you can get the idea how they works.</p><p>I will provide more tutorials on using of Userform time to time.</p><p><strong><em>Till then do come to visit this blog and Happy learning!!!</em></strong></p></div></article><div class="margin-vert--lg"><nav class="pagination-nav" aria-label="Blog list page navigation"><div class="pagination-nav__item"><a class="pagination-nav__link" href="/docs/vba-userform/vba-userforms-open-part"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Â« Open new Part document</div></a></div><div class="pagination-nav__item pagination-nav__item--next"><a class="pagination-nav__link" href="/docs/vba-userform/vba-userforms-open-part-test"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Testing Open new Assembly and Drawing document Â»</div></a></div></nav></div></div></div><div class="col col--3"><div class="tableOfContents_3SO_"><ul class="table-of-contents table-of-contents__left-border"><li><a href="#video-of-code-on-youtube" class="table-of-contents__link">Video of Code on YouTube</a></li><li><a href="#create-a-new-macro" class="table-of-contents__link">Create a new macro</a></li><li><a href="#insert-userform-in-the-macro" class="table-of-contents__link">Insert userform in the macro</a></li><li><a href="#adding-controls-into-userform" class="table-of-contents__link">Adding Controls into Userform</a><ul><li><a href="#adding-combobox" class="table-of-contents__link">Adding ComboBox</a></li><li><a href="#adding-commandbutton" class="table-of-contents__link">Adding CommandButton</a></li></ul></li><li><a href="#updating-properties" class="table-of-contents__link">Updating Properties</a><ul><li><a href="#updating-properties-of-the-userform" class="table-of-contents__link">Updating Properties of the UserForm</a></li><li><a href="#updating-properties-of-the-combobox" class="table-of-contents__link">Updating Properties of the ComboBox</a></li><li><a href="#updating-properties-of-the-command-button" class="table-of-contents__link">Updating Properties of the Command Button</a></li></ul></li><li><a href="#calling-userform-in-main-module" class="table-of-contents__link">Calling UserForm in Main Module</a></li><li><a href="#adding-document-list" class="table-of-contents__link">Adding Document list</a></li><li><a href="#first-test-of-macro" class="table-of-contents__link">First Test of Macro</a></li><li><a href="#add-functionality-to-open-newpart-button" class="table-of-contents__link">Add Functionality to Open NewPart Button</a></li><li><a href="#exercise-to-do" class="table-of-contents__link">Exercise to do</a></li></ul></div></div></div></div></main></div></div><footer class="footer"><div class="container"><div class="row footer__links"><div class="col footer__col"><h4 class="footer__title">Tutorials</h4><ul class="footer__items"><li class="footer__item"><a class="footer__link-item" href="/docs/vba-Intro">VBA Introduction</a></li><li class="footer__item"><a class="footer__link-item" href="/docs/vba-in-sw">VBA in Solidworks</a></li><li class="footer__item">
                <div>
                  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                  
                  <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002" data-ad-slot="6644001766" data-ad-format="auto" data-full-width-responsive="true"></ins>
                  <script>(adsbygoogle=window.adsbygoogle||[]).push({})</script>
                </div>            
                </li></ul></div><div class="col footer__col"><h4 class="footer__title">Community</h4><ul class="footer__items"><li class="footer__item"><a href="https://www.facebook.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Facebook</a></li><li class="footer__item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" rel="noopener noreferrer" class="footer__link-item">YouTube</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">More</h4><ul class="footer__items"><li class="footer__item"><a href="mailto:thecadcoder@gmail.com" target="_blank" rel="noopener noreferrer" class="footer__link-item">E-Mail</a></li><li class="footer__item"><a href="https://www.buymeacoffee.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Buy Me a Coffee</a></li></ul></div></div><div class="text--center"><div>Copyright Â© 2020 The Cad Coder, Inc. Built with Docusaurus.</div></div></div></footer></div>
<script src="/styles.e684f388.js"></script>
<script src="/runtime~main.10187eec.js"></script>
<script src="/main.d90b1f90.js"></script>
<script src="/1.1af7f77d.js"></script>
<script src="/2.4f0019c3.js"></script>
<script src="/94.4b40930d.js"></script>
<script src="/95.2f44d2c3.js"></script>
<script src="/f976f453.e3619938.js"></script>
<script src="/17896441.361bff39.js"></script>
<script src="/b368aa39.ccfd3589.js"></script>
</body>
</html>