<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- begin _includes/seo.html --><title>SOLIDWORKS C# API - Browse/Open SOLIDWORKS Document - The CAD Coder</title>
<meta name="description" content="OBJECTIVE">



<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="SOLIDWORKS C# API - Browse/Open SOLIDWORKS Document">
<meta property="og:url" content="http://localhost:4000/solidworks-csharp/browse-and-open-solidworks-file/">


  <meta property="og:description" content="OBJECTIVE">







  <meta property="article:published_time" content="2025-07-29T07:06:23-04:00">






<link rel="canonical" href="http://localhost:4000/solidworks-csharp/browse-and-open-solidworks-file/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": null,
      "url": "http://localhost:4000/"
    
  }
</script>







<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-117501871-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-117501871-2', { 'anonymize_ip': true});
</script>

<!-- end _includes/seo.html -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">
  <link
    href="/feed.xml"
    type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/main.css">

  <meta name="google-site-verification" content="OeSBbUv_kXDkDxaeoLixjE1BYxlbQRINt58H1UGbSMY" />

  

  <!-- MailerLite Universal -->
  <script>
    (function (w, d, e, u, f, l, n) {
      w[f] = w[f] || function () {
        (w[f].q = w[f].q || [])
          .push(arguments);
      }, l = d.createElement(e), l.async = 1, l.src = u,
        n = d.getElementsByTagName(e)[0], n.parentNode.insertBefore(l, n);
    })
      (window, document, 'script', 'https://assets.mailerlite.com/js/universal.js', 'ml');
    ml('account', '1644816');
  </script>
  <!-- End MailerLite Universal -->
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        <img src="/assets/logo.png" width="30" height="30" class="img-fluid" alt="">
        <span>The CAD Coder</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a  class="nav-link"   href="/knowledge-base/introduction/"><span>Knowledge Base</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/vba/vba-Introduction/"><span>VBA</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-macro-guide/"><span>Solidworks VBA Macro</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="active nav-link" style="border-bottom: 1px solid #fff;"   href="/Solidworks-csharp-api-tutorials/"><span>Solidworks C# API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-cpp-api-tutorials/"><span>Solidworks C++ API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/wpf-tutorials/syncfusion-account-signup/"><span>WPF Tutorials</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/knowledge-base/wix4-introduction/"><span>Wix4 Tutorials</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/resources/"><span>Resources</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/aboutMe/"><span>About</span></a>
            </li>
            
            <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li> -->
        </ul>
        <!-- <a class="btn btn-outline-success my-2 my-sm-0" href="/seach-document/" role="button">
            <i class="fas fa-search"></i>
        </a> -->
    </div>
</nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-lg-2 col-sm-4">
  <div class="sidebar sticky" style="width: 100%;">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">Getting Started</span>
        

        
        <ul>
          
            <li><a href="/Solidworks-csharp-api-tutorials/">Introduction</a></li>
          
            <li><a href="/solidworks-csharp/Prerequisite/">Prerequisite</a></li>
          
            <li><a href="/solidworks-csharp/open-solidworks/">Open Solidworks</a></li>
          
            <li><a href="/solidworks-csharp/open-solidworks-document/">Open Solidworks Document</a></li>
          
            <li><a href="/solidworks-csharp/browse-and-open-solidworks-file/" class="active">Browse/Open SOLIDWORKS Document</a></li>
          
            <li><a href="/solidworks-csharp/unit-correction/">Fix Unit Issue</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch Segment</span>
        

        
        <ul>
          
            <li><a href="/solidworks-csharp/insert-sketch/">Insert Solidworks Sketch</a></li>
          
            <li><a href="/solidworks-csharp/edit-sketch/">Edit Solidworks Sketch</a></li>
          
            <li><a href="/solidworks-csharp/edit-solidworks-feature-sketch/">Edit Solidworks Feature Sketch</a></li>
          
            <li><a href="/solidworks-csharp/change-sketch-name/">Change Sketch Name</a></li>
          
            <li><a href="/solidworks-csharp/delete-selected-sketch/">Delete Selected Sketch</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch Lines</span>
        

        
        <ul>
          
            <li><a href="/solidworks-csharp/create-line/">Create Line</a></li>
          
            <li><a href="/solidworks-csharp/create-line-code-refactor/">Create Line Code Refactor</a></li>
          
            <li><a href="/solidworks-csharp/setup-test-project/">Setup Test Project</a></li>
          
            <li><a href="/solidworks-csharp/test-createLine-method/">Test Create Line Method</a></li>
          
            <li><a href="/solidworks-csharp/test-applyunitconversion-method/">Test ApplyUnitConversion Method</a></li>
          
            <li><a href="/solidworks-csharp/test-SelectSketchPlane-method/">Test SelectSketchPlane Method</a></li>
          
            <li><a href="/solidworks-csharp/test-CreatePartDocument-method/">Test CreatePartDocument Method</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Others</span>
        

        
        <ul>
          
            <li><a href="/solidworks-csharp/update-dimension-state/">Update Dimension State</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>

</div>
      <div class="col-md-9 col-lg-10 col-sm-8">
        <div>
          <div id="main" role="main">

  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    
    <meta itemprop="headline" content="SOLIDWORKS C# API - Browse/Open SOLIDWORKS Document">
    
    <meta itemprop="description" content="OBJECTIVE">
    
    
    <meta itemprop="datePublished" content="2025-07-29T07:06:23-04:00">
    

    <div class="page__inner-wrap">
      
      <header>
        <h1 id="page-title" class="page__title" itemprop="headline">SOLIDWORKS C# API - Browse/Open SOLIDWORKS Document
</h1>
        

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          4 minute read
        
      </span>
    
  </p>


      </header>
      

      <section class="page__content" itemprop="text">
        
        <aside class="sidebar__right sticky">
          <nav class="toc">
            <header>
              <h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4>
            </header>
            <ul class="toc__menu"><li><a href="#objective">OBJECTIVE</a></li><li><a href="#result-we-get">RESULT WE GET</a></li><li><a href="#demo-video">DEMO VIDEO</a></li><li><a href="#add-solidworks-references">ADD SOLIDWORKS REFERENCES</a></li><li><a href="#check-before-open-document">CHECK BEFORE OPEN DOCUMENT</a></li><li><a href="#open-solidworks-document">OPEN SOLIDWORKS DOCUMENT</a></li><li><a href="#final-result">FINAL RESULT</a></li></ul>

            <br/>
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Vertical Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="4311368222"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          </nav>
        </aside>
        
        <div>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Horizontal Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="6007593278"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          <h2 id="objective">OBJECTIVE</h2>

<p>I want to:</p>

<ul>
  <li>
    <p><strong><em>Open browsed SOLIDWORKS Document using Solidworks C# API</em></strong></p>
  </li>
  <li>
    <p><strong><em>We will continue from previous article 🚀 <a href="/wpf-tutorials/add-syncfusion-busy-indicator/">Browse Solidworks Document UI</a>.</em></strong></p>
  </li>
  <li>
    <p><strong><em>Extend article by adding Solidworks C# API to previous code.</em></strong></p>
  </li>
</ul>

<hr />

<h2 id="result-we-get">RESULT WE GET</h2>

<p>Below image shows the result we get.</p>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/final-result.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/final-result.gif" alt="browse-and-open-solidworks-file" /></a></p>

<p class="notice--warning">To get the correct result, please follow the steps correctly.</p>

<hr />

<h2 id="demo-video">DEMO VIDEO</h2>

<p>Please see below video on how to “Open browsed SOLIDWORKS Document” using <strong>SOLIDWORKS C# API</strong> from <strong>WPF Application</strong>.</p>

<iframe src="https://www.youtube.com/embed/pTB35G-Devg" frameborder="0" allowfullscreen=""></iframe>
<p><br /></p>

<p class="notice--info">Please note that there are <strong>no explanation</strong> in the video.<br />
<strong>Explanation</strong> of each step and why we write code this way is given in this post.</p>

<hr />

<h2 id="add-solidworks-references">ADD SOLIDWORKS REFERENCES</h2>

<ul>
  <li>
    <p>For opening <strong>SOLIDWORKS</strong> we need to add some <em>references</em> into our project.</p>
  </li>
  <li>
    <p>Please see below image for how to add <em>SOLIDWORKS</em> reference.</p>
  </li>
</ul>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/add-solidworks-references.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/add-solidworks-references.gif" alt="add-solidworks-references" /></a></p>

<h2 id="check-before-open-document">CHECK BEFORE OPEN DOCUMENT</h2>

<p>In this section we apply some checks.</p>

<ul>
  <li>
    <p>First, we check if we have a file path, which we browsed.</p>
  </li>
  <li>
    <p>Please see below 👇🏻 image for reference.</p>
  </li>
</ul>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/check-we-browsed-a-file.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/check-we-browsed-a-file.gif" alt="check-we-browsed-a-file" /></a></p>

<ul>
  <li>Please see below 👇🏻 code sample for reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">// Check if we browsed a file</span>
<span class="k">if</span> <span class="p">(</span><span class="kt">string</span><span class="p">.</span><span class="nf">IsNullOrEmpty</span><span class="p">(</span><span class="n">FilePath</span><span class="p">))</span>
    <span class="k">return</span><span class="p">;</span>
</code></pre></div></div>

<ul>
  <li>
    <p>In above code, we are checking, if we browsed a file.</p>
  </li>
  <li>
    <p><strong>Condition</strong>: <strong><code class="language-plaintext highlighter-rouge">string.IsNullOrEmpty(FilePath)</code></strong></p>

    <ul>
      <li>
        <p>Browsed file path is saved into <strong><code class="language-plaintext highlighter-rouge">FilePath</code></strong> variable.</p>
      </li>
      <li>
        <p>Please see previous article 🚀 <strong><a href="/wpf-tutorials/add-syncfusion-busy-indicator/">Browse Solidworks Document UI</a></strong> for more details.</p>
      </li>
      <li>
        <p>If we don’t browse any file, then <strong><code class="language-plaintext highlighter-rouge">FilePath</code></strong> variable did not have any value.</p>
      </li>
      <li>
        <p>We check if value of <strong><code class="language-plaintext highlighter-rouge">FilePath</code></strong> variable is <strong><code class="language-plaintext highlighter-rouge">null</code></strong> or <strong><code class="language-plaintext highlighter-rouge">empty</code></strong> by <strong><code class="language-plaintext highlighter-rouge">IsNullOrEmpty()</code></strong> method.</p>
      </li>
      <li>
        <p>When this condition is <strong><code class="language-plaintext highlighter-rouge">true</code></strong>, means we <strong>don’t</strong> have any file path, we <strong>exit</strong> the function from here.</p>
      </li>
    </ul>
  </li>
  <li>
    <p>Now we check if browsed file is exist in at said location.</p>
  </li>
  <li>
    <p>Please see below 👇🏻 image for reference.</p>
  </li>
</ul>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/check-file-exist.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/check-file-exist.gif" alt="check-file-exist" /></a></p>

<ul>
  <li>Please see below 👇🏻 code sample for reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">// Check if browsed file exist or not</span>
<span class="k">if</span> <span class="p">(</span><span class="n">File</span><span class="p">.</span><span class="nf">Exists</span><span class="p">(</span><span class="n">FilePath</span><span class="p">)</span> <span class="p">==</span> <span class="k">false</span><span class="p">)</span>
    <span class="k">return</span><span class="p">;</span>
</code></pre></div></div>

<ul>
  <li>
    <p><strong>Condition</strong>: <strong><code class="language-plaintext highlighter-rouge">File.Exists(FilePath) == false</code></strong></p>

    <ul>
      <li>
        <p>Browsed file path is saved into <strong><code class="language-plaintext highlighter-rouge">FilePath</code></strong> variable.</p>
      </li>
      <li>
        <p>Please see previous article 🚀 <strong><a href="/wpf-tutorials/add-syncfusion-busy-indicator/">Browse Solidworks Document UI</a></strong> for more details.</p>
      </li>
      <li>
        <p>We check if browsed file is exist or not.</p>
      </li>
      <li>
        <p>We do this by <strong><code class="language-plaintext highlighter-rouge">Exists</code></strong> method. This <strong><code class="language-plaintext highlighter-rouge">Exists</code></strong> method is part of <strong><code class="language-plaintext highlighter-rouge">File</code></strong> class.</p>
      </li>
      <li>
        <p>This <strong><code class="language-plaintext highlighter-rouge">Exists</code></strong> method take <em>path of file</em> as parameter.</p>
      </li>
      <li>
        <p>If file exist, then it returns <strong><code class="language-plaintext highlighter-rouge">true</code></strong>. If file does not exis, then return <strong><code class="language-plaintext highlighter-rouge">false</code></strong>.</p>
      </li>
      <li>
        <p>We are comparing that return value <strong><code class="language-plaintext highlighter-rouge">Exists</code></strong> method equals to <strong><code class="language-plaintext highlighter-rouge">false</code></strong>.</p>
      </li>
      <li>
        <p>When this condition is <strong><code class="language-plaintext highlighter-rouge">true</code></strong>, means we <strong>don’t</strong> have browsed file hence we <strong>exit</strong> the function from here.</p>
      </li>
    </ul>
  </li>
</ul>

<h2 id="open-solidworks-document">OPEN SOLIDWORKS DOCUMENT</h2>

<p>In this section, we open browsed Solidworks document.</p>

<ul>
  <li>
    <p>Create a new function <strong><code class="language-plaintext highlighter-rouge">OpenSolidworksDocument()</code></strong>.</p>
  </li>
  <li>
    <p>Please see below 👇🏻 image for reference.</p>
  </li>
</ul>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/add-opensolidworksdocument-function.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/add-opensolidworksdocument-function.gif" alt="add-opensolidworksdocument-function" /></a></p>

<ul>
  <li>Please see below 👇🏻 code sample for reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">private</span> <span class="k">void</span> <span class="nf">OpenSolidworksDocument</span><span class="p">()</span>
<span class="p">{</span>

<span class="p">}</span>
</code></pre></div></div>

<ul>
  <li>
    <p>Now we call this <strong><code class="language-plaintext highlighter-rouge">OpenSolidworksDocument()</code></strong> function in <strong><code class="language-plaintext highlighter-rouge">ExecuteClickCommand()</code></strong> method.</p>
  </li>
  <li>
    <p>Please see below 👇🏻 image for reference.</p>
  </li>
</ul>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/call-new-function.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/call-new-function.gif" alt="call-new-function" /></a></p>

<ul>
  <li>Please see below 👇🏻 code sample for reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">async</span> <span class="k">void</span> <span class="nf">ExecuteClickCommand</span><span class="p">()</span>
<span class="p">{</span>
    <span class="c1">// Show busy indicator</span>
    <span class="n">IsBusy</span> <span class="p">=</span> <span class="k">true</span><span class="p">;</span>

    <span class="k">await</span> <span class="n">Task</span><span class="p">.</span><span class="nf">Run</span><span class="p">(()</span> <span class="p">=&gt;</span>
    <span class="p">{</span>
        <span class="nf">OpenSolidworksDocument</span><span class="p">();</span>
    <span class="p">});</span>

    <span class="c1">// Hide busy indicator</span>
    <span class="n">IsBusy</span> <span class="p">=</span> <span class="k">false</span><span class="p">;</span>
<span class="p">}</span>
</code></pre></div></div>

<ul>
  <li>
    <p>Now, we get browsed file extension.</p>
  </li>
  <li>
    <p>Please see below 👇🏻 image for reference.</p>
  </li>
</ul>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/get-browsed-file-info.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/get-browsed-file-info.gif" alt="get-browsed-file-info" /></a></p>

<ul>
  <li>Please see below 👇🏻 code sample for reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">private</span> <span class="k">void</span> <span class="nf">OpenSolidworksDocument</span><span class="p">()</span>
<span class="p">{</span>
    <span class="n">FileInfo</span> <span class="n">fileInfo</span> <span class="p">=</span> <span class="k">new</span> <span class="nf">FileInfo</span><span class="p">(</span><span class="n">FilePath</span><span class="p">);</span>
<span class="p">}</span>
</code></pre></div></div>

<ul>
  <li>
    <p>In above line, we store <strong>file information</strong> in <strong><code class="language-plaintext highlighter-rouge">fileInfo</code></strong> variable.</p>
  </li>
  <li>
    <p>Type of <strong><code class="language-plaintext highlighter-rouge">fileInfo</code></strong> variable is <strong><code class="language-plaintext highlighter-rouge">FileInfo</code></strong>.</p>
  </li>
  <li>
    <p>When we create <strong><code class="language-plaintext highlighter-rouge">fileInfo</code></strong> variable, we pass browsed file path.</p>
  </li>
  <li>
    <p>We want to get information of this browsed file.</p>
  </li>
  <li>
    <p>Now we want to get the <strong>file extension</strong> from this <strong><code class="language-plaintext highlighter-rouge">fileInfo</code></strong> variable.</p>
  </li>
  <li>
    <p>Then we store this <strong>file extension</strong> in a <strong><code class="language-plaintext highlighter-rouge">string</code></strong> type variable.</p>
  </li>
  <li>
    <p>Please see below 👇🏻 image for reference.</p>
  </li>
</ul>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/get-file-extension.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/get-file-extension.gif" alt="get-file-extension" /></a></p>

<ul>
  <li>Please see below 👇🏻 code sample for reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">private</span> <span class="k">void</span> <span class="nf">OpenSolidworksDocument</span><span class="p">()</span>
<span class="p">{</span>
    <span class="n">FileInfo</span> <span class="n">fileInfo</span> <span class="p">=</span> <span class="k">new</span> <span class="nf">FileInfo</span><span class="p">(</span><span class="n">FilePath</span><span class="p">);</span>

    <span class="kt">string</span> <span class="n">fileExtension</span> <span class="p">=</span> <span class="n">fileInfo</span><span class="p">.</span><span class="n">Extension</span><span class="p">;</span>
<span class="p">}</span>
</code></pre></div></div>

<ul>
  <li>
    <p>Now we will get the document type of selected file.</p>
  </li>
  <li>
    <p>For this we will check the file extension, we get previously in <strong><code class="language-plaintext highlighter-rouge">fileExtension</code></strong> variable.</p>
  </li>
  <li>
    <p>For this, first we create a new variable <strong><code class="language-plaintext highlighter-rouge">docType</code></strong> of <strong><code class="language-plaintext highlighter-rouge">int</code></strong> data type.</p>
  </li>
  <li>
    <p>Please see below 👇🏻 image for reference.</p>
  </li>
</ul>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/add-data-type-variable.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/add-data-type-variable.gif" alt="add-data-type-variable" /></a></p>

<ul>
  <li>Please see below 👇🏻 code sample for reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">private</span> <span class="k">void</span> <span class="nf">OpenSolidworksDocument</span><span class="p">()</span>
<span class="p">{</span>
    <span class="n">FileInfo</span> <span class="n">fileInfo</span> <span class="p">=</span> <span class="k">new</span> <span class="nf">FileInfo</span><span class="p">(</span><span class="n">FilePath</span><span class="p">);</span>

    <span class="kt">string</span> <span class="n">fileExtension</span> <span class="p">=</span> <span class="n">fileInfo</span><span class="p">.</span><span class="n">Extension</span><span class="p">;</span>

    <span class="kt">int</span> <span class="n">docType</span> <span class="p">=</span> <span class="k">default</span><span class="p">(</span><span class="kt">int</span><span class="p">);</span>
<span class="p">}</span>
</code></pre></div></div>

<ul>
  <li>
    <p>We set the value of <strong><code class="language-plaintext highlighter-rouge">docType</code></strong> variable to Solidworks Document type we have browsed.</p>
  </li>
  <li>
    <p>Please see below 👇🏻 image for reference.</p>
  </li>
</ul>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/get-browsed-document-type.png"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/get-browsed-document-type.png" alt="get-browsed-document-type" /></a></p>

<ul>
  <li>Please see below 👇🏻 code sample for reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">if</span> <span class="p">(</span><span class="kt">string</span><span class="p">.</span><span class="nf">Compare</span><span class="p">(</span><span class="n">fileExtension</span><span class="p">,</span> <span class="s">".sldprt"</span><span class="p">,</span> <span class="k">true</span><span class="p">)</span> <span class="p">==</span> <span class="m">0</span><span class="p">)</span>
    <span class="n">docType</span> <span class="p">=</span> <span class="p">(</span><span class="kt">int</span><span class="p">)</span><span class="n">swDocumentTypes_e</span><span class="p">.</span><span class="n">swDocPART</span><span class="p">;</span>
<span class="k">else</span> <span class="k">if</span> <span class="p">(</span><span class="kt">string</span><span class="p">.</span><span class="nf">Compare</span><span class="p">(</span><span class="n">fileExtension</span><span class="p">,</span> <span class="s">".sldasm"</span><span class="p">,</span> <span class="k">true</span><span class="p">)</span> <span class="p">==</span> <span class="m">0</span><span class="p">)</span>
    <span class="n">docType</span> <span class="p">=</span> <span class="p">(</span><span class="kt">int</span><span class="p">)</span><span class="n">swDocumentTypes_e</span><span class="p">.</span><span class="n">swDocASSEMBLY</span><span class="p">;</span>
<span class="k">else</span>
    <span class="n">docType</span> <span class="p">=</span> <span class="p">(</span><span class="kt">int</span><span class="p">)</span><span class="n">swDocumentTypes_e</span><span class="p">.</span><span class="n">swDocDRAWING</span><span class="p">;</span>
</code></pre></div></div>

<ul>
  <li>
    <p>In above code sample, we check for 3 different conditions as follows.</p>

    <ol>
      <li>
        <p>First we check if fileExtension is <strong><code class="language-plaintext highlighter-rouge">.sldprt</code></strong>. If this condition is true, then we set the value of  <strong><code class="language-plaintext highlighter-rouge">docType</code></strong> variable to <strong><code class="language-plaintext highlighter-rouge">(int)swDocumentTypes_e.swDocPART</code></strong>.</p>
      </li>
      <li>
        <p>After that we check if fileExtension is <strong><code class="language-plaintext highlighter-rouge">.sldasm</code></strong>. If this condition is true, then we set the value of  <strong><code class="language-plaintext highlighter-rouge">docType</code></strong> variable to <strong><code class="language-plaintext highlighter-rouge">(int)swDocumentTypes_e.swDocASSEMBLY</code></strong>.</p>
      </li>
      <li>
        <p>Lastly if above any codition did not get <strong><code class="language-plaintext highlighter-rouge">true</code></strong>, then we set the value of  <strong><code class="language-plaintext highlighter-rouge">docType</code></strong> variable to <strong><code class="language-plaintext highlighter-rouge">(int)swDocumentTypes_e.swDocASSEMBLY</code></strong>.</p>
      </li>
    </ol>
  </li>
  <li>
    <p>Now we open browsed file in Solidworks.</p>
  </li>
  <li>
    <p>Please see below 👇🏻 image for reference.</p>
  </li>
</ul>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/open-solidworks-document.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/open-solidworks-document.gif" alt="open-solidworks-document" /></a></p>

<ul>
  <li>Please see below 👇🏻 code sample for reference.</li>
</ul>

<div class="language-cs highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span> <span class="n">swApp</span> <span class="p">=</span> <span class="k">new</span> <span class="n">SldWorks</span><span class="p">.</span><span class="nf">SldWorks</span><span class="p">();</span>

<span class="n">swApp</span><span class="p">.</span><span class="nf">OpenDoc</span><span class="p">(</span><span class="n">FilePath</span><span class="p">,</span> <span class="n">docType</span><span class="p">);</span>

<span class="n">swApp</span><span class="p">.</span><span class="n">Visible</span> <span class="p">=</span> <span class="k">true</span><span class="p">;</span>
</code></pre></div></div>

<ul>
  <li>
    <p>In above code, we create Solidworks application variable.</p>
  </li>
  <li>
    <p>Then, we open browsed document.</p>
  </li>
  <li>
    <p>After opening document, we make Solidworks visible.</p>
  </li>
</ul>

<h2 id="final-result">FINAL RESULT</h2>

<p>Now, we have done everything needed to <strong>Open</strong> <em>SOLIDWORKS Document</em> through our application.</p>

<p>Please see below image for final result of our work.</p>

<p><a href="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/final-result.gif"><img src="/assets/solidworks-csharp-images/browse-and-open-solidworks-file/final-result.gif" alt="final-result" /></a></p>

<hr />

<p><strong>This is it !!!</strong></p>

<p><em>I hope my efforts will helpful to someone!</em></p>

<p>If you found anything to <strong>add or update</strong>, please let me know on my <em>e-mail</em>.</p>

<p>Hope this post helps you to <strong>Open SOLIDWORKS Documents</strong> from WPF PRISM Application.</p>

<p><em>If you like the post then please share it with your friends also.</em></p>

<p><em>Do let me know by you like this post or not!</em></p>

<p><em>Till then, Happy learning!!!</em></p>

<ul>
  <li><a href="/download-solidworks-macros/">🎁 Download 5 Free SolidWorks Macros →</a></li>
</ul>

        </div>
        
        <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

      </section>

      <footer class="page__meta">
        
        


        

  <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i> Updated:</strong> <time datetime="2025-07-29T07:06:23-04:00">July 29, 2025</time></p>


      </footer>

      
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    
    <li class="page-item mr-5">
      <a class="btn btn-primary text-light" href="/solidworks-csharp/open-solidworks-document/" title="SOLIDWORKS C# API - Open SOLIDWORKS Document
">❮ Previous</a>
    </li>
    
    
    <li class="page-item ml-5">
      <a class="btn btn-primary text-light" href="/solidworks-csharp/unit-correction/" title="SOLIDWORKS C# API - Fix Unit Issue
">Next ❯</a>
    </li>
    
  </ul>
</nav>

    </div>
  </article>

</div>

          
        </div>
      </div>
    </div>
  </div>

  <div id="footer" class="page__footer">
    <footer>
      <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
      <footer class="bd-footer py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <a class="d-inline-flex align-items-center mb-2 link-dark" href="/" aria-label="Bootstrap">
          <img src="/assets/logo.png" width="30" height="30" class="img-fluid mr-2" alt="">
          <span> The CAD Coder</span>
        </a>
        <ul class="list-unstyled small text-muted">
          <li class="mb-2">Programming Tutorials for SOLIDWORKS 3D CAD Software.</li>
          <li class="mb-2">Copyright © 2022 The CAD Coder</li>
          <li class="mb-2">Built with <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a>.</li>

          
          
          
          
          
          <li class="list-inline-item"><a href="https://facebook.com/thecadcoder" target="_blank" title="Facebook"><i
                class="fab fa-2x fa-facebook-f"></i></a></li>
          
          
          
          
          
          
          
          
          
          
          
          <li class="list-inline-item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" title="YouTube"><i
                class="fab fa-2x fa-youtube"></i></a></li>
          
          
          
          <li class="list-inline-item"><a href="mailto:thecadcoder@gmail.com" target="_blank" title="Email"><i
                class="fa fa-envelope fa-2x"></i></a></li>
          
          
          
        </ul>
      </div>
      <div class="col-6">
        <h5>Links</h5>
        <ul class="list-unstyled">
          <!-- <li class="mb-2"><a href="/">Home</a></li> -->
          <li class="mb-2"><a href="/aboutMe/">About</a></li>
          <li class="mb-2"><a href="/resources/">Resources</a></li>
          <li class="mb-2"><a href="/privacy-policy/">Privacy Policy</a></li>
          <li class="mb-2"><a href="/Disclaimer/">Disclaimer</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
    </footer>
  </div>

  
  <script src="/assets/js/main.min.js"></script>




<script src="/assets/js/lunr/lunr.min.js"></script>
<script src="/assets/js/lunr/lunr-store.js"></script>
<script src="/assets/js/lunr/lunr-en.js"></script>







  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->

  
  <script src="/assets/js/main.min.js"></script>




<script src="/assets/js/lunr/lunr.min.js"></script>
<script src="/assets/js/lunr/lunr-store.js"></script>
<script src="/assets/js/lunr/lunr-en.js"></script>






</body>

</html>