"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[3032],{3905:function(e,t,n){n.d(t,{Zo:function(){return m},kt:function(){return u}});var o=n(67294);function a(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function r(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,o)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?r(Object(n),!0).forEach((function(t){a(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function l(e,t){if(null==e)return{};var n,o,a=function(e,t){if(null==e)return{};var n,o,a={},r=Object.keys(e);for(o=0;o<r.length;o++)n=r[o],t.indexOf(n)>=0||(a[n]=e[n]);return a}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(o=0;o<r.length;o++)n=r[o],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(a[n]=e[n])}return a}var s=o.createContext({}),p=function(e){var t=o.useContext(s),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},m=function(e){var t=p(e.components);return o.createElement(s.Provider,{value:t},e.children)},c={inlineCode:"code",wrapper:function(e){var t=e.children;return o.createElement(o.Fragment,{},t)}},d=o.forwardRef((function(e,t){var n=e.components,a=e.mdxType,r=e.originalType,s=e.parentName,m=l(e,["components","mdxType","originalType","parentName"]),d=p(n),u=a,k=d["".concat(s,".").concat(u)]||d[u]||c[u]||r;return n?o.createElement(k,i(i({ref:t},m),{},{components:n})):o.createElement(k,i({ref:t},m))}));function u(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var r=n.length,i=new Array(r);i[0]=d;var l={};for(var s in t)hasOwnProperty.call(t,s)&&(l[s]=t[s]);l.originalType=e,l.mdxType="string"==typeof e?e:a,i[1]=l;for(var p=2;p<r;p++)i[p]=n[p];return o.createElement.apply(null,i)}return o.createElement.apply(null,n)}d.displayName="MDXCreateElement"},32025:function(e,t,n){n.r(t),n.d(t,{assets:function(){return c},contentTitle:function(){return p},default:function(){return k},frontMatter:function(){return s},metadata:function(){return m},toc:function(){return d}});var o=n(87462),a=n(63366),r=(n(67294),n(3905)),i=n(74753),l=["components"],s={categories:"Solidworks-macro",title:"Solidworks Macro - Selection Methods",permalink:"/solidworks-macros/select-plane-from-tree/",tags:["Solidworks Macro"],id:"select-plane-from-tree"},p=void 0,m={unversionedId:"select-plane-from-tree",id:"select-plane-from-tree",title:"Solidworks Macro - Selection Methods",description:"",source:"@site/docs/solidworks-macros/001.4-select-plane-from-tree.md",sourceDirName:".",slug:"/select-plane-from-tree",permalink:"/solidworks-macros/select-plane-from-tree",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Selection Methods",permalink:"/solidworks-macros/select-plane-from-tree/",tags:["Solidworks Macro"],id:"select-plane-from-tree"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Open Assembly and Drawing document",permalink:"/solidworks-macros/open-assembly-and-drawing"},next:{title:"Solidworks Macro - Open Saved Documents",permalink:"/solidworks-macros/open-saved-document"}},c={},d=[{value:"By <strong>SelectByID</strong> method From <strong>ModelDoc2</strong> Interface",id:"by-selectbyid-method-from-modeldoc2-interface",level:2},{value:"Using SelectByID method in previous example",id:"using-selectbyid-method-in-previous-example",level:3},{value:"Using SelectByID method in an Open document",id:"using-selectbyid-method-in-an-open-document",level:3},{value:"By <strong>SelectByID2</strong> method From <strong>IModelDocExtension</strong> Interface",id:"by-selectbyid2-method-from-imodeldocextension-interface",level:2},{value:"Using SelectByID2 method in previous example",id:"using-selectbyid2-method-in-previous-example",level:3},{value:"Using SelectByID2 method in an Open document",id:"using-selectbyid2-method-in-an-open-document",level:3}],u={toc:d};function k(e){var t=e.components,n=(0,a.Z)(e,l);return(0,r.kt)("wrapper",(0,o.Z)({},u,n,{components:t,mdxType:"MDXLayout"}),(0,r.kt)(i.Z,{mdxType:"AdComponent"}),(0,r.kt)("p",null,"In this post, we select ",(0,r.kt)("strong",{parentName:"p"},"Default planes")," with following methods:"),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("em",{parentName:"li"},"By ",(0,r.kt)("inlineCode",{parentName:"em"},"SelectByID")," method From ",(0,r.kt)("inlineCode",{parentName:"em"},"ModelDoc2")," Interface")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("em",{parentName:"li"},"By ",(0,r.kt)("inlineCode",{parentName:"em"},"SelectByID2")," method From ",(0,r.kt)("inlineCode",{parentName:"em"},"IModelDocExtension")," Interface"))),(0,r.kt)("h2",{id:"by-selectbyid-method-from-modeldoc2-interface"},"By ",(0,r.kt)("strong",{parentName:"h2"},"SelectByID")," method From ",(0,r.kt)("strong",{parentName:"h2"},"ModelDoc2")," Interface"),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID")," method From ",(0,r.kt)("inlineCode",{parentName:"p"},"ModelDoc2")," Interface is the easiest method for selecting Default plane."),(0,r.kt)("p",null,"I will explain the use of this method in 2 different scenerio as follows:"),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},"Using this method in the previous example of creating a new document and then select a Plane."),(0,r.kt)("li",{parentName:"ol"},"Using this method in an open document.")),(0,r.kt)("h3",{id:"using-selectbyid-method-in-previous-example"},"Using SelectByID method in previous example"),(0,r.kt)("p",null,"In the previous 2 posts, we learned how to create ",(0,r.kt)("em",{parentName:"p"},"a new part document, an assembly document, and a drawing document"),"."),(0,r.kt)("p",null,"Now we use the same code and ",(0,r.kt)("em",{parentName:"p"},"extended")," it for using selecting planes."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Main function of our VBA program\nSub main()\n\n    ' Setting Solidworks variable to Solidworks application\n    Set swApp = Application.SldWorks\n    \n    ' Creating string type variable for storing default part location\n    Dim defaultTemplate As String\n    ' Setting value of this string type variable to \"Default part template\"\n    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n    ' Setting Solidworks document to new part document\n    Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n    ' Selecting Front Plane\n    BoolStatus = swDoc.SelectByID(\"Front Plane\", \"PLANE\", 0, 0, 0)\n\nEnd Sub\n")),(0,r.kt)("p",null,'Above code, 1st create a new part document and then select "',(0,r.kt)("strong",{parentName:"p"},"Front Plane"),'" in VBA macro.'),(0,r.kt)("p",null,"To select the plane, I have to add 2 lines. 1st I create a boolean varible above main function as shown in below code:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,r.kt)("p",null,"Then I use this ",(0,r.kt)("inlineCode",{parentName:"p"},"BoolStatus")," variable to selecting ",(0,r.kt)("em",{parentName:"p"},"Front Plane")," as shown in below code:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Selecting Front Plane\nBoolStatus = swDoc.SelectByID("Front Plane", "PLANE", 0, 0, 0)\n')),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID")," takes following parameters:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Name")," : ",(0,r.kt)("em",{parentName:"li"},"Name of the object or an empty string")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Type")," : ",(0,r.kt)("em",{parentName:"li"},"Type of object in uppercase or an empty string")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"X")," : ",(0,r.kt)("em",{parentName:"li"},"X selection location")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Y")," : ",(0,r.kt)("em",{parentName:"li"},"Y selection location")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Z")," : ",(0,r.kt)("em",{parentName:"li"},"Z selection Location"))),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Return Value")," - "),(0,r.kt)("p",null,"If the item is select then this method returns ",(0,r.kt)("inlineCode",{parentName:"p"},"True")," and otherwise ",(0,r.kt)("inlineCode",{parentName:"p"},"False"),"."),(0,r.kt)("p",null,"Since this method returns ",(0,r.kt)("inlineCode",{parentName:"p"},"True")," or ",(0,r.kt)("inlineCode",{parentName:"p"},"False"),", hence we use a ",(0,r.kt)("inlineCode",{parentName:"p"},"boolean")," variable to perfom this method."),(0,r.kt)("p",null,"If we want to select ",(0,r.kt)("strong",{parentName:"p"},"Right Plane")," then we just need to replace ",(0,r.kt)("inlineCode",{parentName:"p"},'"Front Plane"')," \u27a1 ",(0,r.kt)("inlineCode",{parentName:"p"},'"Right Plane"')," in previous code sample."),(0,r.kt)("p",null,"Similar for selecting ",(0,r.kt)("strong",{parentName:"p"},"Top Plane"),", we need to replace ",(0,r.kt)("inlineCode",{parentName:"p"},'"Front Plane"')," \u27a1 ",(0,r.kt)("inlineCode",{parentName:"p"},'"Top Plane"')," in previous code sample."),(0,r.kt)("h3",{id:"using-selectbyid-method-in-an-open-document"},"Using SelectByID method in an Open document"),(0,r.kt)("p",null,"For using ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID")," method in an open document we use differnet code sample."),(0,r.kt)("p",null,"The code sample is given below:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Main function of our VBA program\nSub main()\n\n    ' Setting Solidworks variable to Solidworks application\n    Set swApp = Application.SldWorks\n        \n    ' Setting Solidworks document to active open document\n    Set swDoc = swApp.ActiveDoc\n        \n    ' Selecting Front Plane\n    BoolStatus = swDoc.SelectByID(\"Front Plane\", \"PLANE\", 0, 0, 0)\n\nEnd Sub\n")),(0,r.kt)("p",null,"Most of the things in this code sample is already explained \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"previous post"))," and in previous section of this very post."),(0,r.kt)("p",null,"In this code I have set the ",(0,r.kt)("em",{parentName:"p"},"Solidworks document variable")," ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," to active open document."),(0,r.kt)("p",null,"And then we use similar method to select ",(0,r.kt)("strong",{parentName:"p"},'"Front Plane"'),"."),(0,r.kt)("p",null,"As explained in previous section we can select ",(0,r.kt)("strong",{parentName:"p"},"Right Plane")," and ",(0,r.kt)("strong",{parentName:"p"},"Top Plane"),"."),(0,r.kt)("hr",null),(0,r.kt)(i.Z,{mdxType:"AdComponent"}),(0,r.kt)("h2",{id:"by-selectbyid2-method-from-imodeldocextension-interface"},"By ",(0,r.kt)("strong",{parentName:"h2"},"SelectByID2")," method From ",(0,r.kt)("strong",{parentName:"h2"},"IModelDocExtension")," Interface"),(0,r.kt)("p",null,"This method is similar to ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID")," from previous section infact it is the ",(0,r.kt)("em",{parentName:"p"},"updated version")," of previous method."),(0,r.kt)("p",null,"Since it is ",(0,r.kt)("em",{parentName:"p"},"updated")," and has ",(0,r.kt)("em",{parentName:"p"},"additional functionality"),", I will explain it I ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"frequently"))," use this method. Previous method is easiest method, by far, for selecting objects."),(0,r.kt)("p",null,"Since ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID2")," is updated version of ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID")," it has similar syntax and usage."),(0,r.kt)("p",null,"I will explain the use of ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method in 2 different scenerio as done in previous method:"),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"Using this method in the previous example of creating a new document and then select a Plane.")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"Using this method in an open document."))),(0,r.kt)("h3",{id:"using-selectbyid2-method-in-previous-example"},"Using SelectByID2 method in previous example"),(0,r.kt)("p",null,"Now we use the same code and ",(0,r.kt)("em",{parentName:"p"},"extended")," it for using selecting planes by ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Main function of our VBA program\nSub main()\n\n    ' Setting Solidworks variable to Solidworks application\n    Set swApp = Application.SldWorks\n    \n    ' Creating string type variable for storing default part location\n    Dim defaultTemplate As String\n    ' Setting value of this string type variable to \"Default part template\"\n    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n    ' Setting Solidworks document to new part document\n    Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n    ' Selecting Front Plane\n    BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\nEnd Sub\n")),(0,r.kt)("p",null,"This method is doing the ",(0,r.kt)("em",{parentName:"p"},"same thing")," which I already explained in the previous method. "),(0,r.kt)("p",null,"The difference is in the ",(0,r.kt)("em",{parentName:"p"},"syntax")," and ",(0,r.kt)("em",{parentName:"p"},"input parameters"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Selecting Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,r.kt)("p",null,"As you can see from the above code sample, this method is a method of ",(0,r.kt)("inlineCode",{parentName:"p"},"Extension")," interface/object."),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"Extension")," interface/object is part of ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable. This variable is the type of ",(0,r.kt)("inlineCode",{parentName:"p"},"ModelDoc2")," interface/object."),(0,r.kt)("p",null,"Apart from that, we need to give additional input parameters also."),(0,r.kt)("p",null,"Below I have explained about the input parameters of ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Name")," : ",(0,r.kt)("em",{parentName:"li"},"Name of the object or an empty string")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Type")," : ",(0,r.kt)("em",{parentName:"li"},"Type of object in uppercase or an empty string")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"X")," : ",(0,r.kt)("em",{parentName:"li"},"X selection location")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Y")," : ",(0,r.kt)("em",{parentName:"li"},"Y selection location")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Z")," : ",(0,r.kt)("em",{parentName:"li"},"Z selection location")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Append")," : ",(0,r.kt)("em",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," or ",(0,r.kt)("inlineCode",{parentName:"em"},"False"),". It is used the adding the selection into selection list.")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Mark")," : ",(0,r.kt)("em",{parentName:"li"},"Value you want to use as a Mark; this value is used by other functions that require ordered selection.")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Callout")," : ",(0,r.kt)("em",{parentName:"li"},"Pointer to the ",(0,r.kt)("inlineCode",{parentName:"em"},"Callout")," interface/object. (Default value most of the time is ",(0,r.kt)("inlineCode",{parentName:"em"},"nothing"),"."),")"),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"SelectOption")," : ",(0,r.kt)("em",{parentName:"li"},"Selection option. You can use either ",(0,r.kt)("inlineCode",{parentName:"em"},"swSelectOptionDefault")," or ",(0,r.kt)("inlineCode",{parentName:"em"},"swSelectOptionExtensive")," value."))),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Return Value")," - "),(0,r.kt)("p",null,"If the item is select then this method returns ",(0,r.kt)("inlineCode",{parentName:"p"},"True")," and otherwise ",(0,r.kt)("inlineCode",{parentName:"p"},"False"),"."),(0,r.kt)("p",null,"There is ",(0,r.kt)("strong",{parentName:"p"},"a lot more")," about this method in the ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"Remark"))," section. For more information visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2017/english/api/sldworksapi/solidworks.interop.sldworks~solidworks.interop.sldworks.imodeldocextension~selectbyid2.html"},"here")),"."),(0,r.kt)("p",null,"Since this method returns ",(0,r.kt)("inlineCode",{parentName:"p"},"True")," or ",(0,r.kt)("inlineCode",{parentName:"p"},"False"),", here also we use a ",(0,r.kt)("inlineCode",{parentName:"p"},"boolean")," variable to perfom this method."),(0,r.kt)("p",null,"If we want to select ",(0,r.kt)("strong",{parentName:"p"},"Right Plane")," then we just need to replace ",(0,r.kt)("inlineCode",{parentName:"p"},'"Front Plane"')," \u27a1 ",(0,r.kt)("inlineCode",{parentName:"p"},'"Right Plane"')," in previous code sample."),(0,r.kt)("p",null,"Similar for selecting ",(0,r.kt)("strong",{parentName:"p"},"Top Plane"),", we need to replace ",(0,r.kt)("inlineCode",{parentName:"p"},'"Front Plane"')," \u27a1 ",(0,r.kt)("inlineCode",{parentName:"p"},'"Top Plane"')," in previous code sample."),(0,r.kt)("h3",{id:"using-selectbyid2-method-in-an-open-document"},"Using SelectByID2 method in an Open document"),(0,r.kt)("p",null,"For using ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method in an open document we use same code sample as used in previous method."),(0,r.kt)("p",null,"The code sample is given below:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Main function of our VBA program\nSub main()\n\n    ' Setting Solidworks variable to Solidworks application\n    Set swApp = Application.SldWorks\n        \n    ' Setting Solidworks document to active open document\n    Set swDoc = swApp.ActiveDoc\n        \n    ' Selecting Front Plane\n    BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\nEnd Sub\n")),(0,r.kt)("p",null,"Most of the things in this code sample is already explained \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"previous post"))," and in previous section of this very post."),(0,r.kt)("p",null,"In this code I have set the ",(0,r.kt)("em",{parentName:"p"},"Solidworks document variable")," ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," to active open document."),(0,r.kt)("p",null,"And then we use similar method to select ",(0,r.kt)("strong",{parentName:"p"},'"Front Plane"'),"."),(0,r.kt)("p",null,"As explained in previous section we can select ",(0,r.kt)("strong",{parentName:"p"},"Right Plane")," and ",(0,r.kt)("strong",{parentName:"p"},"Top Plane"),"."),(0,r.kt)("p",null,"This is all for now. This post is getting too long."),(0,r.kt)("p",null,"In next post we learn about ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"Open Saved Documents")),"."))}k.isMDXComponent=!0},74753:function(e,t,n){n.d(t,{Z:function(){return r}});var o=n(94578),a=n(67294),r=function(e){function t(){return e.apply(this,arguments)||this}(0,o.Z)(t,e);var n=t.prototype;return n.componentDidMount=function(){var e;(e=document.createElement("script")).src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild),(window.adsbygoogle=window.adsbygoogle||[]).push({})},n.render=function(){return a.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})},t}(a.Component)}}]);