"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[1319],{3905:(e,t,n)=>{n.d(t,{Zo:()=>m,kt:()=>u});var r=n(67294);function a(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);t&&(r=r.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,r)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(Object(n),!0).forEach((function(t){a(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function l(e,t){if(null==e)return{};var n,r,a=function(e,t){if(null==e)return{};var n,r,a={},o=Object.keys(e);for(r=0;r<o.length;r++)n=o[r],t.indexOf(n)>=0||(a[n]=e[n]);return a}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(r=0;r<o.length;r++)n=o[r],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(a[n]=e[n])}return a}var s=r.createContext({}),p=function(e){var t=r.useContext(s),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},m=function(e){var t=p(e.components);return r.createElement(s.Provider,{value:t},e.children)},c={inlineCode:"code",wrapper:function(e){var t=e.children;return r.createElement(r.Fragment,{},t)}},d=r.forwardRef((function(e,t){var n=e.components,a=e.mdxType,o=e.originalType,s=e.parentName,m=l(e,["components","mdxType","originalType","parentName"]),d=p(n),u=a,k=d["".concat(s,".").concat(u)]||d[u]||c[u]||o;return n?r.createElement(k,i(i({ref:t},m),{},{components:n})):r.createElement(k,i({ref:t},m))}));function u(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var o=n.length,i=new Array(o);i[0]=d;var l={};for(var s in t)hasOwnProperty.call(t,s)&&(l[s]=t[s]);l.originalType=e,l.mdxType="string"==typeof e?e:a,i[1]=l;for(var p=2;p<o;p++)i[p]=n[p];return r.createElement.apply(null,i)}return r.createElement.apply(null,n)}d.displayName="MDXCreateElement"},42085:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>p,contentTitle:()=>l,default:()=>d,frontMatter:()=>i,metadata:()=>s,toc:()=>m});var r=n(87462),a=(n(67294),n(3905)),o=n(74753);const i={categories:"Solidworks-macro",title:"Solidworks Macro - Create Perimeter Circle",permalink:"/solidworks-macros/create-perimeter-circle/",tags:["Solidworks Macro"],id:"create-perimeter-circle"},l=void 0,s={unversionedId:"create-perimeter-circle",id:"create-perimeter-circle",title:"Solidworks Macro - Create Perimeter Circle",description:"",source:"@site/docs/solidworks-macros/004.3-create-perimeter-circle.md",sourceDirName:".",slug:"/create-perimeter-circle",permalink:"/solidworks-macros/create-perimeter-circle",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Create Perimeter Circle",permalink:"/solidworks-macros/create-perimeter-circle/",tags:["Solidworks Macro"],id:"create-perimeter-circle"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Create Circle By Radius",permalink:"/solidworks-macros/create-circle-by-radius"},next:{title:"Solidworks Macro - Create Centerpoint Arc",permalink:"/solidworks-macros/create-centerpoint-arc"}},p={},m=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"Code Sample",id:"code-sample",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:2}],c={toc:m};function d(e){let{components:t,...n}=e;return(0,a.kt)("wrapper",(0,r.Z)({},c,n,{components:t,mdxType:"MDXLayout"}),(0,a.kt)(o.Z,{mdxType:"AdComponent"}),(0,a.kt)("p",null,"In this post, I tell you about ",(0,a.kt)("em",{parentName:"p"},"how to create Perimeter Circle through Solidworks VBA Macros")," in a sketch."),(0,a.kt)("p",null,"The process is identical with previous \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-circle"},"Solidworks Sketch Macros - Create Circle"))," post."),(0,a.kt)("p",null,"In this post, I tell you about ",(0,a.kt)("inlineCode",{parentName:"p"},"PerimeterCircle")," method from ",(0,a.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,a.kt)("inlineCode",{parentName:"p"},"SketchManager")," object."),(0,a.kt)("p",null,"This method is ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"most updated"))," method, I found in ",(0,a.kt)("em",{parentName:"p"},"Solidworks API Help"),". "),(0,a.kt)("p",null,"So ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"use this method"))," if you want to create a new ",(0,a.kt)("strong",{parentName:"p"},"Perimeter Circle"),"."),(0,a.kt)("hr",null),(0,a.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,a.kt)("p",null,"Please see below video \ud83c\udfac on ",(0,a.kt)("strong",{parentName:"p"},"how to create a Perimeter Circle")," from Solidworks VBA Macros."),(0,a.kt)("iframe",{src:"https://www.youtube.com/embed/D3AJ5kiD0kc",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,a.kt)("p",null,"Please note that there are ",(0,a.kt)("strong",{parentName:"p"},"no explaination")," in the video. "),(0,a.kt)("p",null,(0,a.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,a.kt)("hr",null),(0,a.kt)("h2",{id:"code-sample"},"Code Sample"),(0,a.kt)("p",null,"Below is the ",(0,a.kt)("inlineCode",{parentName:"p"},"code")," sample for creating ",(0,a.kt)("em",{parentName:"p"},"a Perimeter Circle"),"."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Boolean Variable\nDim BoolStatus As Boolean\n' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Main function of our VBA program\nSub main()\n\n    ' Setting Solidworks variable to Solidworks application\n    Set swApp = Application.SldWorks\n    \n    ' Creating string type variable for storing default part location\n    Dim defaultTemplate As String\n    ' Setting value of this string type variable to \"Default part template\"\n    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n    ' Setting Solidworks document to new part document\n    Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n    ' Selecting Front Plane\n    BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n    \n    ' Setting Sketch manager for our sketch\n    Set swSketchManager = swDoc.SketchManager\n\n    ' Inserting a sketch into selected plane\n    swSketchManager.InsertSketch True\n    \n    ' Creating object type Variable\n    Dim myPerimeterCircle As Object\n    \n    ' Creating a Perimeter circle\n    Set myPerimeterCircle = swSketchManager.PerimeterCircle(0, 0, 1, 0, 0, 1)\n    \n    ' De-select the circle after creation\n    swDoc.ClearSelection2 True\n    \n    ' Zoom to fit screen in Solidworks Window\n    swDoc.ViewZoomtofit\n\nEnd Sub\n")),(0,a.kt)("hr",null),(0,a.kt)(o.Z,{mdxType:"AdComponent"}),(0,a.kt)("h2",{id:"understanding-the-code"},"Understanding the Code"),(0,a.kt)("p",null,"Now let us walk through ",(0,a.kt)("em",{parentName:"p"},"each line")," in the above code, and ",(0,a.kt)("strong",{parentName:"p"},"understand")," the meaning of every line."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,a.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,a.kt)("admonition",{type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"For more information please visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,a.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,a.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,a.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,a.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,a.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,a.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,a.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,a.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,a.kt)("p",null,"Next is our ",(0,a.kt)("inlineCode",{parentName:"p"},"Sub")," procedure named ",(0,a.kt)("inlineCode",{parentName:"p"},"main"),". This procedure hold all the ",(0,a.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,a.kt)("p",null,"In this line, we are setting the value of our Solidworks variable which we define earlier to Solidworks application."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating string type variable for storing default part location\nDim defaultTemplate As String\n' Setting value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),(0,a.kt)("p",null,"In 1st statement of above example, we are defining a variable of ",(0,a.kt)("inlineCode",{parentName:"p"},"string")," type and named it as ",(0,a.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),(0,a.kt)("p",null,"This variable ",(0,a.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",(0,a.kt)("strong",{parentName:"p"},"Default Part Template"),"."),(0,a.kt)("p",null,"In 2nd line of above example. we assign value to our newly define ",(0,a.kt)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),(0,a.kt)("p",null,"We assign the value by using a ",(0,a.kt)("em",{parentName:"p"},"Method")," named ",(0,a.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". This method is a part of our main Solidworks variable ",(0,a.kt)("inlineCode",{parentName:"p"},"swApp"),"."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),(0,a.kt)("p",null,"In this line, we set the value of our ",(0,a.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),(0,a.kt)("admonition",{type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"For ",(0,a.kt)("strong",{parentName:"p"},"detailed information")," about these lines please visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Boolean Variable\nDim BoolStatus As Boolean\n\n\' Selecting Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,a.kt)("p",null,"In 1st line, we create a variable named ",(0,a.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,a.kt)("inlineCode",{parentName:"p"},"Boolean")," object."),(0,a.kt)("p",null,"In next line, we select the ",(0,a.kt)("em",{parentName:"p"},"front plane")," by using ",(0,a.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,a.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,a.kt)("admonition",{type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"For more information about selection method please visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post.")),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),(0,a.kt)("p",null,"In above line, we create variable ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchManager")," for ",(0,a.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,a.kt)("p",null,"As the name suggested, a Sketch Manager holds variours methods and properties to manage Sketches."),(0,a.kt)("p",null,"To see methods and properties related to SketchManager object, please visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this page of Solidworks API"))),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),(0,a.kt)("p",null,"In above line, we set the sketch manager variable to current document's sketch manager."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Inserting a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,a.kt)("p",null,"In above line, we use ",(0,a.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,a.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,a.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,a.kt)("p",null,"This method allows us to insert a sketch in selected plane."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating object type Variable\nDim myPerimeterCircle As Object\n    \n' Creating a Perimeter circle\nSet myPerimeterCircle = swSketchManager.PerimeterCircle(0, 0, 1, 0, 0, 1)\n")),(0,a.kt)("p",null,"In above sample code, we 1st create a variable named ",(0,a.kt)("inlineCode",{parentName:"p"},"myPerimeterCircle")," of type ",(0,a.kt)("inlineCode",{parentName:"p"},"Object"),"."),(0,a.kt)("p",null,"An ",(0,a.kt)("inlineCode",{parentName:"p"},"object")," can hold ",(0,a.kt)("strong",{parentName:"p"},"any")," type of ",(0,a.kt)("em",{parentName:"p"},"return value"),". In our example, it holds a ",(0,a.kt)("em",{parentName:"p"},"3 point Perimeter Arc")," as return value."),(0,a.kt)("p",null,"In 2nd line, we set the value of object variable ",(0,a.kt)("inlineCode",{parentName:"p"},"myPerimeterCircle"),"."),(0,a.kt)("p",null,"We get this value from ",(0,a.kt)("inlineCode",{parentName:"p"},"PerimeterCircle")," method which is inside the ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchManager")," variable."),(0,a.kt)("p",null,(0,a.kt)("inlineCode",{parentName:"p"},"swSketchManager")," variable is a type of SketchManager, hence we used ",(0,a.kt)("inlineCode",{parentName:"p"},"PerimeterCircle")," method from SketchManager."),(0,a.kt)("p",null,"This ",(0,a.kt)("inlineCode",{parentName:"p"},"PerimeterCircle")," method takes following parameters as explained:"),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"X1")," : X coordinate of the first point")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"Y1")," : Y coordinate of the first point")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"X2")," : X coordinate of the second point")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"Y2")," : Y coordinate of the second point")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"X3")," : X coordinate of the third point")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"Y3")," : Y coordinate of the third point"))),(0,a.kt)("p",null,"In the above code sample I have used (0, 0) for first point which is at origin."),(0,a.kt)("p",null,"For 2nd point on the circle I used (1, 0) which is 1 point distance in X-direction."),(0,a.kt)("p",null,"For 3rd point on the circle I used (0, 1) which is 1 point distance in Y-direction."),(0,a.kt)("p",null,"This ",(0,a.kt)("inlineCode",{parentName:"p"},"PerimeterCircle")," method returns ",(0,a.kt)("em",{parentName:"p"},"3 point Perimeter Arc")," object."),(0,a.kt)("admonition",{title:"NOTE",type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"It is ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",(0,a.kt)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Meter only")),"."),(0,a.kt)("p",{parentName:"admonition"},(0,a.kt)("em",{parentName:"p"},"Solidworks API")," does not care about your application's Unit systems."),(0,a.kt)("p",{parentName:"admonition"},'For example, I works in ANSI system means "inches" for distance. '),(0,a.kt)("p",{parentName:"admonition"},"But when I used Solidworks API through ",(0,a.kt)("em",{parentName:"p"},"VBA macros")," or ",(0,a.kt)("em",{parentName:"p"},"C#"),", I have to use ",(0,a.kt)("strong",{parentName:"p"},"converted")," numeric values."),(0,a.kt)("p",{parentName:"admonition"},"Because Solidworks API output the distance in ",(0,a.kt)("strong",{parentName:"p"},"Meter")," only; which is not my requirement.")),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the circle after creation\nswDoc.ClearSelection2 True\n")),(0,a.kt)("p",null,"In the this line of code, we de-select the created circle."),(0,a.kt)("p",null,"For de-selecting, we use ",(0,a.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document variable ",(0,a.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),(0,a.kt)("p",null,"In this last line we use ",(0,a.kt)("em",{parentName:"p"},"zoom to fit")," command."),(0,a.kt)("p",null,"For Zoom to fit, we use ",(0,a.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",(0,a.kt)("inlineCode",{parentName:"p"},"swDoc"),". "),(0,a.kt)("p",null,"Hope this post helps you to ",(0,a.kt)("em",{parentName:"p"},"create Circle")," in Sketches with Solidworks VB Macros."),(0,a.kt)("p",null,"For more such tutorials on ",(0,a.kt)("strong",{parentName:"p"},"Solidworks VBA Macros"),", do come to this blog after sometime."),(0,a.kt)("p",null,"Till then, Happy learning!!!"))}d.isMDXComponent=!0},74753:(e,t,n)=>{n.d(t,{Z:()=>a});var r=n(67294);class a extends r.Component{componentDidMount(){(()=>{const e=document.createElement("script");e.src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild)})(),(window.adsbygoogle=window.adsbygoogle||[]).push({})}render(){return r.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})}}}}]);