"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[8045],{3905:(e,t,n)=>{n.d(t,{Zo:()=>m,kt:()=>c});var o=n(67294);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function a(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,o)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?a(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):a(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function p(e,t){if(null==e)return{};var n,o,r=function(e,t){if(null==e)return{};var n,o,r={},a=Object.keys(e);for(o=0;o<a.length;o++)n=a[o],t.indexOf(n)>=0||(r[n]=e[n]);return r}(e,t);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);for(o=0;o<a.length;o++)n=a[o],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(r[n]=e[n])}return r}var l=o.createContext({}),s=function(e){var t=o.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},m=function(e){var t=s(e.components);return o.createElement(l.Provider,{value:t},e.children)},u={inlineCode:"code",wrapper:function(e){var t=e.children;return o.createElement(o.Fragment,{},t)}},d=o.forwardRef((function(e,t){var n=e.components,r=e.mdxType,a=e.originalType,l=e.parentName,m=p(e,["components","mdxType","originalType","parentName"]),d=s(n),c=r,w=d["".concat(l,".").concat(c)]||d[c]||u[c]||a;return n?o.createElement(w,i(i({ref:t},m),{},{components:n})):o.createElement(w,i({ref:t},m))}));function c(e,t){var n=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var a=n.length,i=new Array(a);i[0]=d;var p={};for(var l in t)hasOwnProperty.call(t,l)&&(p[l]=t[l]);p.originalType=e,p.mdxType="string"==typeof e?e:r,i[1]=p;for(var s=2;s<a;s++)i[s]=n[s];return o.createElement.apply(null,i)}return o.createElement.apply(null,n)}d.displayName="MDXCreateElement"},34432:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>l,contentTitle:()=>i,default:()=>u,frontMatter:()=>a,metadata:()=>p,toc:()=>s});var o=n(87462),r=(n(67294),n(3905));const a={title:"VBA Userforms - Open new Part document",tags:["VBA"],permalink:"/vba/open-part-from-userform/"},i=void 0,p={unversionedId:"open-part-from-userform",id:"open-part-from-userform",title:"VBA Userforms - Open new Part document",description:"In this post, we learn how can we open a part document from a Visual Basic for Application's Userform.",source:"@site/docs/vba/28-open-part-from-userform.md",sourceDirName:".",slug:"/open-part-from-userform",permalink:"/vba/open-part-from-userform",draft:!1,tags:[{label:"VBA",permalink:"/vba/tags/vba"}],version:"current",sidebarPosition:28,frontMatter:{title:"VBA Userforms - Open new Part document",tags:["VBA"],permalink:"/vba/open-part-from-userform/"},sidebar:"tutorialSidebar",previous:{title:"VBA UserForms",permalink:"/vba/vba-userform"},next:{title:"VBA Userforms - Open new Assembly and Drawing document",permalink:"/vba/open-assembly-and-drawing-from-userform"}},l={},s=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"Create a new macro",id:"create-a-new-macro",level:2},{value:"Insert userform in the macro",id:"insert-userform-in-the-macro",level:2},{value:"Adding a Button",id:"adding-a-button",level:2},{value:"Updating Properties of Command Button and Userform Windows",id:"updating-properties-of-command-button-and-userform-windows",level:2},{value:"Add Functionality to Open NewPart Button",id:"add-functionality-to-open-newpart-button",level:2}],m={toc:s};function u(e){let{components:t,...a}=e;return(0,r.kt)("wrapper",(0,o.Z)({},m,a,{components:t,mdxType:"MDXLayout"}),(0,r.kt)("p",null,"In this post, we learn how can we ",(0,r.kt)("em",{parentName:"p"},"open a part document")," from a Visual Basic for Application's ",(0,r.kt)("em",{parentName:"p"},"Userform"),"."),(0,r.kt)("p",null,"For this please we need to do following steps as described below."),(0,r.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,r.kt)("p",null,"Please see below video on ",(0,r.kt)("strong",{parentName:"p"},"Solidworks VBA Macro - Open new Part document")," in Solidwoks VBA Userforms."),(0,r.kt)("iframe",{src:"https://www.youtube.com/embed/pXMMSDeXEwo",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,r.kt)("p",null,"Please note that there are ",(0,r.kt)("strong",{parentName:"p"},"no explaination")," in the video. "),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,r.kt)("h2",{id:"create-a-new-macro"},"Create a new macro"),(0,r.kt)("p",null,"1st we need to create a ",(0,r.kt)("strong",{parentName:"p"},"new macro")," in ",(0,r.kt)("em",{parentName:"p"},"Solidworks 3D CAD Software"),"."),(0,r.kt)("p",null,"If you don't know how to create a new macro in Solidworks, please go to ",(0,r.kt)("a",{parentName:"p",href:"/solidworks-macros/vba-in-solidworks"},"VBA in Solidworks")," post for this."),(0,r.kt)("p",null,"This will open a new macro in Visual Basic Editor with some code as shown in below image."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"new_macro_window",src:n(97638).Z,width:"691",height:"545"})," "),(0,r.kt)("h2",{id:"insert-userform-in-the-macro"},"Insert userform in the macro"),(0,r.kt)("p",null,"After this we need to insert a userform in our macro."),(0,r.kt)("p",null,"For this, select the button shown in below image."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"insert-userform-button",src:n(1997).Z,width:"498",height:"242"})),(0,r.kt)("p",null,"This button is called ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"insert userform")),". "),(0,r.kt)("p",null,"As the name suggest, function of this button is ",(0,r.kt)("em",{parentName:"p"},"inserting a userform"),"."),(0,r.kt)("blockquote",null,(0,r.kt)("p",{parentName:"blockquote"},"Please note that in a macro we can insert any number of userform as we like. But for this example we insert only 1 userform.")),(0,r.kt)("p",null,"After clicking the ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"insert userform"))," button we get the userform window as shown in below image."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"userform-window",src:n(29900).Z,width:"1136",height:"578"})),(0,r.kt)("h2",{id:"adding-a-button"},"Adding a Button"),(0,r.kt)("p",null,"Now in our userform window, we add a ",(0,r.kt)("inlineCode",{parentName:"p"},"Command Button")," at center of window."),(0,r.kt)("p",null,"You can find ",(0,r.kt)("inlineCode",{parentName:"p"},"Command Button")," highlighted in red in below image."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"add-command-buton",src:n(4459).Z,width:"628",height:"404"})),(0,r.kt)("p",null,"You can place command button at your desire. I placed it at center of the userform window as shown in below image."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"userform-window-after-adding-command-button",src:n(21653).Z,width:"655",height:"455"})),(0,r.kt)("h2",{id:"updating-properties-of-command-button-and-userform-windows"},"Updating Properties of Command Button and Userform Windows"),(0,r.kt)("p",null,"Now we update some properties of Command Button and Userform Windows for our use."),(0,r.kt)("blockquote",null,(0,r.kt)("p",{parentName:"blockquote"},"It is not necessary to update properties but it is a good habit to update them for our purpose. ")),(0,r.kt)("p",null,"1st we update the properties of Userform."),(0,r.kt)("p",null,"In below image, I have shown the properties of ",(0,r.kt)("inlineCode",{parentName:"p"},"Userform1")," and update following properties:"),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"Name of Userform")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"Caption of Userform"))),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"properties-to-change-in-userform",src:n(29078).Z,width:"622",height:"738"})),(0,r.kt)("p",null,"Update the value of ",(0,r.kt)("em",{parentName:"p"},"Name")," property from ",(0,r.kt)("inlineCode",{parentName:"p"},"UserForm1")," to ",(0,r.kt)("inlineCode",{parentName:"p"},"OurWindow"),"."),(0,r.kt)("blockquote",null,(0,r.kt)("p",{parentName:"blockquote"},"From ",(0,r.kt)("em",{parentName:"p"},"Name")," property, we access the Userform.")),(0,r.kt)("p",null,"Update the value of ",(0,r.kt)("em",{parentName:"p"},"Caption")," property from ",(0,r.kt)("inlineCode",{parentName:"p"},"UserForm1")," to ",(0,r.kt)("inlineCode",{parentName:"p"},"Our Window"),"."),(0,r.kt)("blockquote",null,(0,r.kt)("p",{parentName:"blockquote"},"From ",(0,r.kt)("em",{parentName:"p"},"Caption")," property, we update the text appears in the window of our Userform.")),(0,r.kt)("p",null,"Now, we repeat the same process for Command Button."),(0,r.kt)("p",null,"1st we need to select the Command Button in the user form after that we update same properties of Command Button."),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"Name of Command Button")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"Caption of Command Button"))),(0,r.kt)("p",null,"Update the value of ",(0,r.kt)("em",{parentName:"p"},"Name")," property from ",(0,r.kt)("inlineCode",{parentName:"p"},"CommandButton1")," to ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenNewPartButton"),"."),(0,r.kt)("blockquote",null,(0,r.kt)("p",{parentName:"blockquote"},"From ",(0,r.kt)("em",{parentName:"p"},"Name")," property, we access the Command Button.")),(0,r.kt)("p",null,"Update the value of ",(0,r.kt)("em",{parentName:"p"},"Caption")," property from ",(0,r.kt)("inlineCode",{parentName:"p"},"CommandButton1")," to ",(0,r.kt)("inlineCode",{parentName:"p"},"Open NewPart Button"),"."),(0,r.kt)("blockquote",null,(0,r.kt)("p",{parentName:"blockquote"},"From ",(0,r.kt)("em",{parentName:"p"},"Caption")," property, we update the text appears in the Command Button of our Userform.")),(0,r.kt)("h2",{id:"add-functionality-to-open-newpart-button"},"Add Functionality to Open NewPart Button"),(0,r.kt)("p",null,"To add functionality in our ",(0,r.kt)("inlineCode",{parentName:"p"},"Open NewPart Button"),", just double click the ",(0,r.kt)("inlineCode",{parentName:"p"},"Open NewPart Button"),"."),(0,r.kt)("p",null,"This will add give some code behind the designer and opens the ",(0,r.kt)("strong",{parentName:"p"},"code window")," of Userform designer."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Private Sub OpenNewPartButton_Click()\n\nEnd Sub\n")),(0,r.kt)("p",null,"We need to update this code for opening new part after clicking the button."),(0,r.kt)("p",null,"For this replace all above code with below code."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Private function of Open New Part Button \nPrivate Sub OpenNewPartButton_Click()\n\n    ' Setting Solidworks variable to Solidworks application\n    Set swApp = Application.SldWorks\n    \n    ' Creating string type variable for storing default part location\n    Dim defaultTemplate As String\n    ' Setting value of this string type variable to \"Default part template\"\n    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n    ' Setting Solidworks document to new part document\n    Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\nEnd Sub\n")),(0,r.kt)("p",null,"The above code will ",(0,r.kt)("em",{parentName:"p"},"open New part document")," when we click the button."),(0,r.kt)("p",null,"But first, we need to call the our ",(0,r.kt)("em",{parentName:"p"},"Userform")," inside main ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"module")),"."),(0,r.kt)("p",null,"For this goto main ",(0,r.kt)("inlineCode",{parentName:"p"},"Sub procedure")," inside the ",(0,r.kt)("strong",{parentName:"p"},"main Module"),"."),(0,r.kt)("p",null,"Code inside the main Module is as given below."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Dim swApp As Object\nSub main()\n\nSet swApp = Application.SldWorks\nEnd Sub\n")),(0,r.kt)("p",null,"To call our Userform, replace above code with below code:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Main function of our VBA program\nSub main()\n    ' Calling our window to show\n    OurWindow.Show\nEnd Sub\n")),(0,r.kt)("p",null,"Above function call our window to appears on screen."),(0,r.kt)("p",null,"When the window appears on screen, we hit the button."),(0,r.kt)("p",null,"After hitting the button, the code behind the userform run, which opens a new Part document."),(0,r.kt)("p",null,"If you want to know more about how we open new part with macro please see ",(0,r.kt)("a",{parentName:"p",href:"/solidworks-macros/open-new-document/"},"Open new Part document"),"."),(0,r.kt)("p",null,"That's it for now."),(0,r.kt)("p",null,"Hope you learn some use of Userforms and by this post you can get the idea how they works."),(0,r.kt)("p",null,"I will provide more tutorials on using of Userform time to time."),(0,r.kt)("p",null,"Till then do come to visit this blog."),(0,r.kt)("p",null,"Till then, Happy learning!!!"))}u.isMDXComponent=!0},97638:(e,t,n)=>{n.d(t,{Z:()=>o});const o=n.p+"assets/images/1.new_macro_window-e509af3a79274952a24b6d2119d99e21.PNG"},1997:(e,t,n)=>{n.d(t,{Z:()=>o});const o=n.p+"assets/images/2.insert-userform-button-47db25e07f07365b98475369da9afeee.png"},29900:(e,t,n)=>{n.d(t,{Z:()=>o});const o=n.p+"assets/images/3.userform-window-03cf1994dcb9990c02e86a0fb1c6060a.PNG"},4459:(e,t,n)=>{n.d(t,{Z:()=>o});const o=n.p+"assets/images/4.add-command-button-576696f3adf8e3ed08b321a1fcbbe484.png"},21653:(e,t,n)=>{n.d(t,{Z:()=>o});const o=n.p+"assets/images/5.userform-window-after-adding-command-button-dd99e79f6a219247ac8fd27575b230dd.PNG"},29078:(e,t,n)=>{n.d(t,{Z:()=>o});const o=n.p+"assets/images/6.properties-to-change-in-userform-583a8eedc6262af7bffa6388390b782e.png"}}]);