"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[797],{3905:(e,t,n)=>{n.d(t,{Zo:()=>m,kt:()=>d});var a=n(67294);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function s(e,t){if(null==e)return{};var n,a,r=function(e,t){if(null==e)return{};var n,a,r={},o=Object.keys(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||(r[n]=e[n]);return r}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(r[n]=e[n])}return r}var l=a.createContext({}),p=function(e){var t=a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},m=function(e){var t=p(e.components);return a.createElement(l.Provider,{value:t},e.children)},c={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},k=a.forwardRef((function(e,t){var n=e.components,r=e.mdxType,o=e.originalType,l=e.parentName,m=s(e,["components","mdxType","originalType","parentName"]),k=p(n),d=r,u=k["".concat(l,".").concat(d)]||k[d]||c[d]||o;return n?a.createElement(u,i(i({ref:t},m),{},{components:n})):a.createElement(u,i({ref:t},m))}));function d(e,t){var n=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var o=n.length,i=new Array(o);i[0]=k;var s={};for(var l in t)hasOwnProperty.call(t,l)&&(s[l]=t[l]);s.originalType=e,s.mdxType="string"==typeof e?e:r,i[1]=s;for(var p=2;p<o;p++)i[p]=n[p];return a.createElement.apply(null,i)}return a.createElement.apply(null,n)}k.displayName="MDXCreateElement"},65997:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>p,contentTitle:()=>s,default:()=>k,frontMatter:()=>i,metadata:()=>l,toc:()=>m});var a=n(87462),r=(n(67294),n(3905)),o=n(74753);const i={categories:"Solidworks-macro",title:"Solidworks Macro - Create Tangent Arc",permalink:"/solidworks-macros/create-tangent-arc/",tags:["Solidworks Macro"],id:"create-tangent-arc"},s=void 0,l={unversionedId:"create-tangent-arc",id:"create-tangent-arc",title:"Solidworks Macro - Create Tangent Arc",description:"",source:"@site/docs/solidworks-macros/005.2-create-tangent-arc.md",sourceDirName:".",slug:"/create-tangent-arc",permalink:"/solidworks-macros/create-tangent-arc",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Create Tangent Arc",permalink:"/solidworks-macros/create-tangent-arc/",tags:["Solidworks Macro"],id:"create-tangent-arc"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Create Centerpoint Arc",permalink:"/solidworks-macros/create-centerpoint-arc"},next:{title:"Solidworks Macro - Create 3-Point Arc",permalink:"/solidworks-macros/create-3point-arc"}},p={},m=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"Code Sample",id:"code-sample",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:2}],c={toc:m};function k(e){let{components:t,...n}=e;return(0,r.kt)("wrapper",(0,a.Z)({},c,n,{components:t,mdxType:"MDXLayout"}),(0,r.kt)(o.Z,{mdxType:"AdComponent"}),(0,r.kt)("p",null,"In this post, I tell you about ",(0,r.kt)("em",{parentName:"p"},"how to create a Tangent Arc through Solidworks VBA Macros")," in a sketch."),(0,r.kt)("p",null,"The process is almost identical with previous \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/sketch-create-line"},"Solidworks Sketch Macros - Create Line"))," post."),(0,r.kt)("p",null,"In this post, I tell you about ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateTangentArc")," method from ",(0,r.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchManager")," object."),(0,r.kt)("p",null,"This method is ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"most updated"))," method, I found in ",(0,r.kt)("em",{parentName:"p"},"Solidworks API Help"),". "),(0,r.kt)("p",null,"So ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"use this method"))," if you want to create a new ",(0,r.kt)("strong",{parentName:"p"},"Tangent Arc"),"."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,r.kt)("p",null,"Please see below video \ud83c\udfac on ",(0,r.kt)("strong",{parentName:"p"},"how to create a Tangent Arc")," from Solidworks VBA Macros."),(0,r.kt)("iframe",{src:"https://www.youtube.com/embed/XK3uP6cETg8",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,r.kt)("p",null,"Please note that there are ",(0,r.kt)("strong",{parentName:"p"},"no explaination")," in the video. "),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"code-sample"},"Code Sample"),(0,r.kt)("p",null,"Below is the ",(0,r.kt)("inlineCode",{parentName:"p"},"code")," sample for creating ",(0,r.kt)("em",{parentName:"p"},"a Tangent Arc"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Boolean Variable\nDim BoolStatus As Boolean\n' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Main function of our VBA program\nSub main()\n\n  ' Setting Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Creating string type variable for storing default part location\n  Dim defaultTemplate As String\n  ' Setting value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Setting Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n  ' Selecting Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Setting Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n  \n  ' Inserting a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Creating Variable for Solidworks Sketch segment\n  Dim mySketchSegment As SketchSegment\n      \n  ' Creating an horizontal line\n  Set mySketchSegment = swSketchManager.CreateLine(0, 0, 0, 0, 1, 0)\n  \n  ' Creating a Tangent Arc\n  Set mySketchSegment = swSketchManager.CreateTangentArc(0, 1, 0, 2, 1, 0, swTangentArcTypes_e.swForward)\n  \n  ' De-select the Arc after creation\n  swDoc.ClearSelection2 True\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit\n\nEnd Sub\n")),(0,r.kt)("hr",null),(0,r.kt)(o.Z,{mdxType:"AdComponent"}),(0,r.kt)("h2",{id:"understanding-the-code"},"Understanding the Code"),(0,r.kt)("p",null,"Now let us walk through ",(0,r.kt)("em",{parentName:"p"},"each line")," in the above code, and ",(0,r.kt)("strong",{parentName:"p"},"understand")," the meaning of every line."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,r.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,r.kt)("admonition",{type:"tip"},(0,r.kt)("p",{parentName:"admonition"},"For more information please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,r.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,r.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,r.kt)("p",null,"Next is our ",(0,r.kt)("inlineCode",{parentName:"p"},"Sub")," procedure named as ",(0,r.kt)("inlineCode",{parentName:"p"},"main"),". This procedure hold all the ",(0,r.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,r.kt)("p",null,"In this line, we are setting the value of our Solidworks variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," which we defined earlier to Solidworks application."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating string type variable for storing default part location\nDim defaultTemplate As String\n' Setting value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),(0,r.kt)("p",null,"In 1st statement of above example, we are defining a variable of ",(0,r.kt)("inlineCode",{parentName:"p"},"string")," type and named it as ",(0,r.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),(0,r.kt)("p",null,"This variable ",(0,r.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),", holds the location the location of ",(0,r.kt)("strong",{parentName:"p"},"Default Part Template"),"."),(0,r.kt)("p",null,"In 2nd line of above example. we assign value to our newly define ",(0,r.kt)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),(0,r.kt)("p",null,"We assign the value by using a ",(0,r.kt)("em",{parentName:"p"},"Method")," named ",(0,r.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),(0,r.kt)("p",null,"This method is a part of our main Solidworks variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),(0,r.kt)("p",null,"In this line, we set the value of our ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),(0,r.kt)("admonition",{type:"tip"},(0,r.kt)("p",{parentName:"admonition"},"For ",(0,r.kt)("strong",{parentName:"p"},"more detailed information")," about above lines please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post. "),(0,r.kt)("p",{parentName:"admonition"},"I have discussed them ",(0,r.kt)("strong",{parentName:"p"},"thoroghly")," in \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post, so do checkout this post if you don't understand above code.")),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Boolean Variable\nDim BoolStatus As Boolean\n\n\' Selecting Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,r.kt)("p",null,"In 1st line, we create a variable named ",(0,r.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,r.kt)("inlineCode",{parentName:"p"},"Boolean")," object."),(0,r.kt)("p",null,"In next line, we select the ",(0,r.kt)("em",{parentName:"p"},"front plane")," by using ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,r.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,r.kt)("admonition",{type:"tip"},(0,r.kt)("p",{parentName:"admonition"},"For more information about selection method please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."),(0,r.kt)("p",{parentName:"admonition"},"I have discussed about different ",(0,r.kt)("em",{parentName:"p"},"Selection methods")," in details in \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Soldworks Macros - Selection Methods"))," post, so do visit this post for more ",(0,r.kt)("em",{parentName:"p"},"Selection methods"),".")),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),(0,r.kt)("p",null,"In above line, we create variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swSketchManager")," for ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,r.kt)("p",null,"As the name suggested, a ",(0,r.kt)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",(0,r.kt)("em",{parentName:"p"},"Sketches"),"."),(0,r.kt)("p",null,"To see methods and properties related to SketchManager object, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this page of Solidworks API Help"))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),(0,r.kt)("p",null,"In above line, we set the ",(0,r.kt)("strong",{parentName:"p"},"Sketch manager")," variable to current document's sketch manager."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Inserting a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,r.kt)("p",null,"In above line, we use ",(0,r.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,r.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,r.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,r.kt)("p",null,"This method allows us to insert a sketch in selected plane."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating Variable for Solidworks Sketch segment\nDim mySketchSegment As SketchSegment\n    \n' Creating an horizontal line\nSet mySketchSegment = swSketchManager.CreateLine(0, 0, 0, 0, 1, 0)\n\n' Creating a Tangent Arc\nSet mySketchSegment = swSketchManager.CreateTangentArc(0, 1, 0, 2, 1, 0, swTangentArcTypes_e.swForward)\n")),(0,r.kt)("p",null,"In above sample code, we 1st create a variable named ",(0,r.kt)("inlineCode",{parentName:"p"},"mySketchSegment")," of type ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchSegment"),"."),(0,r.kt)("p",null,"A ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchSegment")," represent ",(0,r.kt)("em",{parentName:"p"},"a line, ellipse, parabola or spline.")),(0,r.kt)("p",null,"A ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchSegment")," provides functions that are ",(0,r.kt)("strong",{parentName:"p"},"generic")," to every type of sketch segment."),(0,r.kt)("p",null,"For example, every sketch segment has ",(0,r.kt)("strong",{parentName:"p"},"an ID")," and can be selected programmatically."),(0,r.kt)("p",null,"Therefore, the ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchSegment")," interface provides functions to obtain the ID and to select the item."),(0,r.kt)("p",null,"For detailed information about the ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchSegment")," please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2017/english/api/sldworksapi/SOLIDWORKS.Interop.sldworks~SOLIDWORKS.Interop.sldworks.ISketchSegment.html"},"this page of Solidworks API Help"))),(0,r.kt)("p",null,"In 2nd line, we set the value of sketch segment variable ",(0,r.kt)("inlineCode",{parentName:"p"},"mySketchSegment"),"."),(0,r.kt)("p",null,"We get this value from ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateLine")," method which is inside the ",(0,r.kt)("inlineCode",{parentName:"p"},"swSketchManager")," variable."),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"swSketchManager")," variable is a type of ",(0,r.kt)("strong",{parentName:"p"},"SketchManager"),", hence we used ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateLine")," method from ",(0,r.kt)("strong",{parentName:"p"},"SketchManager"),"."),(0,r.kt)("admonition",{type:"tip"},(0,r.kt)("p",{parentName:"admonition"},"For detailed information on ",(0,r.kt)("em",{parentName:"p"},"Creating Sketch Line")," visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/sketch-create-line"},"Solidworks Sketch Macros - Create Line")))),(0,r.kt)("p",null,"In 3rd line, we again set the value of sketch segment variable ",(0,r.kt)("inlineCode",{parentName:"p"},"mySketchSegment"),"."),(0,r.kt)("p",null,"We get this value from ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateTangentArc")," method which is inside the ",(0,r.kt)("inlineCode",{parentName:"p"},"swSketchManager")," variable."),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"swSketchManager")," variable is a type of ",(0,r.kt)("strong",{parentName:"p"},"SketchManager"),", hence we used ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateTangentArc")," method from ",(0,r.kt)("strong",{parentName:"p"},"SketchManager"),"."),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateTangentArc")," method takes following parameters as explained:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"X1")," : X coordinate of the start point, of the arc")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"Y1")," : Y coordinate of the start point, of the arc")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"Z1")," : Z coordinate of the start point, of the arc")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"X2")," : X coordinate of the end point, of the arc")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"Y2")," : Y coordinate of the end point, of the arc")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"Z2")," : Z coordinate of the end point, of the arc")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"Arc Type")," : Types of Tangent Arcs as defined in ",(0,r.kt)("inlineCode",{parentName:"p"},"swTangentArcTypes_e")," enum list. "))),(0,r.kt)("p",null,"Below are the values inside ",(0,r.kt)("inlineCode",{parentName:"p"},"swTangentArcTypes_e")),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"swBack = 3")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"swForward = 1")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"swLeft = 2")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"swRight = 4"))),(0,r.kt)("p",null,"In the above code sample, first I create a ",(0,r.kt)("em",{parentName:"p"},"Sketch line")," and then at one end of the line I create a ",(0,r.kt)("em",{parentName:"p"},"Tangent arc"),"."),(0,r.kt)("p",null,"For creating a Sketch line, I have used (0, 0, 0) which is at origin as ",(0,r.kt)("em",{parentName:"p"},"starting point")," of the line."),(0,r.kt)("p",null,"For ",(0,r.kt)("em",{parentName:"p"},"End point")," of the line, I used (0, 1, 0) which is 1 point distance in Y-direction."),(0,r.kt)("p",null,"For creating a ",(0,r.kt)("em",{parentName:"p"},"Tangent arc"),", I used ",(0,r.kt)("em",{parentName:"p"},"End point")," of line i.e. (0, 1, 0) as the ",(0,r.kt)("em",{parentName:"p"},"Start point")," for ",(0,r.kt)("strong",{parentName:"p"},"Tangent Arc"),"."),(0,r.kt)("p",null,"For ",(0,r.kt)("em",{parentName:"p"},"End point")," of ",(0,r.kt)("em",{parentName:"p"},"Tangent arc"),", I used (2, 1, 0) which is 2 point distance in X-direction and 1 point distance in Y-direction."),(0,r.kt)("p",null,"Basically, I want to end the ",(0,r.kt)("em",{parentName:"p"},"Tangent arc")," at the same height of the ",(0,r.kt)("em",{parentName:"p"},"Sketch line"),"."),(0,r.kt)("p",null,"For Arc type, I have used ",(0,r.kt)("inlineCode",{parentName:"p"},"swForward")," as value."),(0,r.kt)("p",null,"This creates a ",(0,r.kt)("strong",{parentName:"p"},"forward clockwise")," ",(0,r.kt)("em",{parentName:"p"},"Tangent arc"),"."),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateTangentArc")," method returns ",(0,r.kt)("em",{parentName:"p"},"sketch segments")," which represent the sides created for this ",(0,r.kt)("em",{parentName:"p"},"Tangent arc"),"."),(0,r.kt)("p",null,"A ",(0,r.kt)("em",{parentName:"p"},"Sketch Segment")," can represent a sketch arc, line, ellipse, parabola or spline."),(0,r.kt)("p",null,"Sketch Segment has ",(0,r.kt)("inlineCode",{parentName:"p"},"ISketchSegment")," Interface, which provides functions that are generic to every type of sketch segment."),(0,r.kt)("p",null,"For example, every sketch segment has an ID and can be programmatically selected."),(0,r.kt)("p",null,"Therefore, the ",(0,r.kt)("inlineCode",{parentName:"p"},"ISketchSegment")," interface provides functions to obtain the ID and to select the item."),(0,r.kt)("admonition",{title:"NOTE",type:"tip"},(0,r.kt)("p",{parentName:"admonition"},"It is ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"Meter only")),"."),(0,r.kt)("p",{parentName:"admonition"},(0,r.kt)("em",{parentName:"p"},"Solidworks API")," does not care about your application's Unit systems."),(0,r.kt)("p",{parentName:"admonition"},'For example, I works in ANSI system means "inches" for distance. '),(0,r.kt)("p",{parentName:"admonition"},"But when I used Solidworks API through ",(0,r.kt)("em",{parentName:"p"},"VBA macros")," or ",(0,r.kt)("em",{parentName:"p"},"C#"),", I have to use ",(0,r.kt)("strong",{parentName:"p"},"converted")," numeric values."),(0,r.kt)("p",{parentName:"admonition"},"Because Solidworks API output the distance in ",(0,r.kt)("strong",{parentName:"p"},"Meter")," only; which is not my requirement.")),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Arc after creation\nswDoc.ClearSelection2 True\n")),(0,r.kt)("p",null,"In the this line of code, we de-select the created Tangent Arc."),(0,r.kt)("p",null,"For de-selecting, we use ",(0,r.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),(0,r.kt)("p",null,"In this last line we use ",(0,r.kt)("em",{parentName:"p"},"zoom to fit")," command."),(0,r.kt)("p",null,"For Zoom to fit, we use ",(0,r.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc"),". "),(0,r.kt)("p",null,"Hope this post helps you to ",(0,r.kt)("em",{parentName:"p"},"create Tangent Arc")," in Sketches with Solidworks VB Macros."),(0,r.kt)("p",null,"For more such tutorials on ",(0,r.kt)("strong",{parentName:"p"},"Solidworks VBA Macros"),", do come to this blog after sometime."),(0,r.kt)("p",null,"Till then, Happy learning!!!"))}k.isMDXComponent=!0},74753:(e,t,n)=>{n.d(t,{Z:()=>r});var a=n(67294);class r extends a.Component{componentDidMount(){(()=>{const e=document.createElement("script");e.src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild)})(),(window.adsbygoogle=window.adsbygoogle||[]).push({})}render(){return a.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})}}}}]);