"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[1846],{3905:function(e,t,n){n.d(t,{Zo:function(){return m},kt:function(){return d}});var a=n(67294);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function i(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function o(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?i(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):i(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function s(e,t){if(null==e)return{};var n,a,r=function(e,t){if(null==e)return{};var n,a,r={},i=Object.keys(e);for(a=0;a<i.length;a++)n=i[a],t.indexOf(n)>=0||(r[n]=e[n]);return r}(e,t);if(Object.getOwnPropertySymbols){var i=Object.getOwnPropertySymbols(e);for(a=0;a<i.length;a++)n=i[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(r[n]=e[n])}return r}var l=a.createContext({}),p=function(e){var t=a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):o(o({},t),e)),n},m=function(e){var t=p(e.components);return a.createElement(l.Provider,{value:t},e.children)},c={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},u=a.forwardRef((function(e,t){var n=e.components,r=e.mdxType,i=e.originalType,l=e.parentName,m=s(e,["components","mdxType","originalType","parentName"]),u=p(n),d=r,k=u["".concat(l,".").concat(d)]||u[d]||c[d]||i;return n?a.createElement(k,o(o({ref:t},m),{},{components:n})):a.createElement(k,o({ref:t},m))}));function d(e,t){var n=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var i=n.length,o=new Array(i);o[0]=u;var s={};for(var l in t)hasOwnProperty.call(t,l)&&(s[l]=t[l]);s.originalType=e,s.mdxType="string"==typeof e?e:r,o[1]=s;for(var p=2;p<i;p++)o[p]=n[p];return a.createElement.apply(null,o)}return a.createElement.apply(null,n)}u.displayName="MDXCreateElement"},19958:function(e,t,n){n.r(t),n.d(t,{assets:function(){return c},contentTitle:function(){return p},default:function(){return k},frontMatter:function(){return l},metadata:function(){return m},toc:function(){return u}});var a=n(87462),r=n(63366),i=(n(67294),n(3905)),o=n(74753),s=["components"],l={categories:"Solidworks-macro",title:"Solidworks Macro - Edit Circular Sketch Pattern",permalink:"/solidworks-macros/edit-circular-skech-pattern/",tags:["Solidworks Macro"],id:"edit-circular-skech-pattern"},p=void 0,m={unversionedId:"edit-circular-skech-pattern",id:"edit-circular-skech-pattern",title:"Solidworks Macro - Edit Circular Sketch Pattern",description:"",source:"@site/docs/solidworks-macros/011.4-edit-circular-skech-pattern.md",sourceDirName:".",slug:"/edit-circular-skech-pattern",permalink:"/solidworks-macros/edit-circular-skech-pattern",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Edit Circular Sketch Pattern",permalink:"/solidworks-macros/edit-circular-skech-pattern/",tags:["Solidworks Macro"],id:"edit-circular-skech-pattern"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Circular Sketch Pattern",permalink:"/solidworks-macros/circular-skech-pattern"},next:{title:"Solidworks Macro - Move/Copy Sketch Entities",permalink:"/solidworks-macros/move-copy-sketch-entities"}},c={},u=[{value:"Introduction",id:"introduction",level:2},{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"Code Sample",id:"code-sample",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:3},{value:"<strong>Cases</strong>",id:"cases",level:3},{value:"CASE 1 : Update Arc Radius",id:"case-1--update-arc-radius",level:4},{value:"CASE 2 : Update Arc Angle",id:"case-2--update-arc-angle",level:4},{value:"CASE 3 : Update Number of Instances",id:"case-3--update-number-of-instances",level:4},{value:"CASE 4 : Update Pattern Spacing",id:"case-4--update-pattern-spacing",level:4},{value:"CASE 5 : Update Display Rotation of Pattern",id:"case-5--update-display-rotation-of-pattern",level:4},{value:"CASE 6 : Update Number of Instances to Delete",id:"case-6--update-number-of-instances-to-delete",level:4},{value:"CASE 7 : Update Display Radius Dimension",id:"case-7--update-display-radius-dimension",level:4},{value:"CASE 8 : Update Display Angle Dimension",id:"case-8--update-display-angle-dimension",level:4},{value:"CASE 9 : Update Display Number of Instances",id:"case-9--update-display-number-of-instances",level:4}],d={toc:u};function k(e){var t=e.components,l=(0,r.Z)(e,s);return(0,i.kt)("wrapper",(0,a.Z)({},d,l,{components:t,mdxType:"MDXLayout"}),(0,i.kt)(o.Z,{mdxType:"AdComponent"}),(0,i.kt)("h2",{id:"introduction"},"Introduction"),(0,i.kt)("p",null,"In this post, I tell you about ",(0,i.kt)("strong",{parentName:"p"},"how to Edit Circular Sketch Pattern using Solidworks VBA Macros")," in a Sketch."),(0,i.kt)("p",null,"In this post, I explain about ",(0,i.kt)("inlineCode",{parentName:"p"},"EditCircularSketchStepAndRepeat")," method from ",(0,i.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,i.kt)("inlineCode",{parentName:"p"},"SketchManager")," object."),(0,i.kt)("p",null,"This method is ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"most updated"))," method, I found in ",(0,i.kt)("em",{parentName:"p"},"Solidworks API Help"),". "),(0,i.kt)("p",null,"So ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"use this method"))," if you want to ",(0,i.kt)("em",{parentName:"p"},"edit existing Circular Sketch Pattern"),"."),(0,i.kt)("p",null,"This post is a little different of previous \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/Circular-skech-pattern"},"Solidworks Macro - Circular Sketch Pattern"))," post."),(0,i.kt)("p",null,"There are 2 changes I have made, which I am going to use on future posts also."),(0,i.kt)("p",null,"These change are explain below:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},"In this post I used ",(0,i.kt)("inlineCode",{parentName:"p"},"code sample")," from \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/unit-correction"},"General - Fix Unit Issue"))," post to fix unit conversion issue and show how to use it.")),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},"In input parameter of ",(0,i.kt)("inlineCode",{parentName:"p"},"EditCircularSketchStepAndRepeat")," method, I passed variables not direct values. This helps us to maintain the code and modification of existing code is simple."))),(0,i.kt)("hr",null),(0,i.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,i.kt)("p",null,"Please see below video \ud83c\udfac on ",(0,i.kt)("strong",{parentName:"p"},"how to Edit Circular Sketch Pattern")," from Solidworks VBA Macros."),(0,i.kt)("iframe",{src:"https://www.youtube.com/embed/R7DnSLDytwg",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,i.kt)("p",null,"Please note that there are ",(0,i.kt)("strong",{parentName:"p"},"no explaination")," in the video. "),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,i.kt)("hr",null),(0,i.kt)("h2",{id:"code-sample"},"Code Sample"),(0,i.kt)("p",null,"Below is the ",(0,i.kt)("inlineCode",{parentName:"p"},"code")," sample to ",(0,i.kt)("em",{parentName:"p"},"edit Circular Sketch Pattern"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n  \n  '-----------------------UNIT CONVERSION----------------------------------------\n\n  ' Local variables used as Conversion Factors\n  Dim LengthConversionFactor As Double\n  Dim AngleConversionFactor As Double\n  \n  ' Use a Select Case, to get the length of active Unit and set the different factors\n  Select Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n    \n    Case swMETER    ' If length is in Meter\n      LengthConversionFactor = 1\n      AngleConversionFactor = 1\n    \n    Case swMM       ' If length is in MM\n      LengthConversionFactor = 1 / 1000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swCM       ' If length is in CM\n      LengthConversionFactor = 1 / 100\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swINCHES   ' If length is in INCHES\n      LengthConversionFactor = 1 * 0.0254\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEET     ' If length is in FEET\n      LengthConversionFactor = 1 * (0.0254 * 12)\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEETINCHES     ' If length is in FEET & INCHES\n      LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swANGSTROM        ' If length is in ANGSTROM\n      LengthConversionFactor = 1 / 10000000000#\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swNANOMETER       ' If length is in NANOMETER\n      LengthConversionFactor = 1 / 1000000000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swMICRON       ' If length is in MICRON\n      LengthConversionFactor = 1 / 1000000\n      AngleConversionFactor = 1 * 0.01745329\n  End Select\n\n  '----------------------------------------------------------------\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Circle Radius\n  Dim circleRadius As Double\n  circleRadius = 5 * LengthConversionFactor\n  \n  ' Set Sketch Segment value and Create a Circle\n  Set swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, circleRadius)\n  \n  ' De-select the lines after creation\n  swDoc.ClearSelection2 True\n\n  ' Select Circle we want to Pattern\n  BoolStatus = swDoc.Extension.SelectByID2(\"Arc1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Arc Radius\n  Dim arcRadius As Double\n  arcRadius = 10 * LengthConversionFactor\n  \n  ' Arc Angle\n  Dim arcAngle As Double\n  arcAngle = 0 * AngleConversionFactor\n  \n  ' Number of Instances\n  Dim numberOfInstance As Double\n  numberOfInstance = 3\n  \n  ' Pattern Spacing\n  Dim patternSpacing As Double\n  patternSpacing = 5 * AngleConversionFactor\n  \n  ' Create a Circular Sketch Pattern\n  BoolStatus = swSketchManager.CreateCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, True, \"\", True, True, True)\n  \n  ' De-select the Sketch Segment after Circular Sketch Pattern\n  swDoc.ClearSelection2 True\n  \n  ' Update Arc Radius\n  arcRadius = 20 * LengthConversionFactor\n\n  ' Edit a Circular Sketch Pattern\n  BoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, True, \"\", True, True, True, \"Arc1_\")\n\n  ' Show Front View after Circular Sketch Pattern\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n  \nEnd Sub\n")),(0,i.kt)("hr",null),(0,i.kt)(o.Z,{mdxType:"AdComponent"}),(0,i.kt)("h3",{id:"understanding-the-code"},"Understanding the Code"),(0,i.kt)("p",null,"Now let us walk through ",(0,i.kt)("strong",{parentName:"p"},"each line")," in the above code, and ",(0,i.kt)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),(0,i.kt)("p",null,"I also give some link so that you can go through them if there are anything I explained in ",(0,i.kt)("strong",{parentName:"p"},"previous posts"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,i.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,i.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"For more information please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,i.kt)("p",null,"In this line, we create a variable which we named as ",(0,i.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,i.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,i.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,i.kt)("p",null,"In this line, we create a variable which we named as ",(0,i.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,i.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,i.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,i.kt)("p",null,"In this line, we create a variable named ",(0,i.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,i.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),(0,i.kt)("p",null,"In above line, we create variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swSketchManager")," for ",(0,i.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,i.kt)("p",null,"As the name suggested, a ",(0,i.kt)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",(0,i.kt)("em",{parentName:"p"},"Sketches"),"."),(0,i.kt)("p",null,"To see methods and properties related to ",(0,i.kt)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this page of Solidworks API Help"))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n")),(0,i.kt)("p",null,"In this line, we Create a variable which we named as ",(0,i.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," and the type of this ",(0,i.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," variable is ",(0,i.kt)("inlineCode",{parentName:"p"},"SldWorks.SketchSegment"),"."),(0,i.kt)("p",null,"We create variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," for ",(0,i.kt)("strong",{parentName:"p"},"Solidworks Sketch Segments"),"."),(0,i.kt)("p",null,"To see methods and properties related to ",(0,i.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," object, please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"},"this page of Solidworks API Help"))),(0,i.kt)("p",null,"These all are our global variables."),(0,i.kt)("p",null,"As you can see in code sample, they are ",(0,i.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,i.kt)("p",null,"So basically I group all the ",(0,i.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,i.kt)("p",null,"I have also place ",(0,i.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",(0,i.kt)("em",{parentName:"p"},"need")," this variable frequently."),(0,i.kt)("p",null,"Thus, I have started placing it here."),(0,i.kt)("p",null,"Next is our ",(0,i.kt)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",(0,i.kt)("inlineCode",{parentName:"p"},"main"),". "),(0,i.kt)("p",null,"This procedure hold all the ",(0,i.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,i.kt)("p",null,"In this line, we set the value of our Solidworks variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create string type variable for storing default part location\nDim defaultTemplate As String\n' Set value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),(0,i.kt)("p",null,"In 1st statement of above example, we are defining a variable of ",(0,i.kt)("inlineCode",{parentName:"p"},"string")," type and named it as ",(0,i.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),(0,i.kt)("p",null,"This variable ",(0,i.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",(0,i.kt)("strong",{parentName:"p"},"Default Part Template"),"."),(0,i.kt)("p",null,"In 2nd line of above example. we assign value to our newly define ",(0,i.kt)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),(0,i.kt)("p",null,"We assign the value by using a ",(0,i.kt)("em",{parentName:"p"},"Method")," named ",(0,i.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),(0,i.kt)("p",null,"This ",(0,i.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," method is a part of our main Solidworks variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swApp"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),(0,i.kt)("p",null,"In this line, we set the value of our ",(0,i.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),(0,i.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"For ",(0,i.kt)("strong",{parentName:"p"},"detailed information")," about these lines please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."),(0,i.kt)("p",{parentName:"div"},"I have discussed them ",(0,i.kt)("strong",{parentName:"p"},"thoroghly")," in ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post, so do checkout that post if you want to understand above code in more detail."))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"'-----------------------UNIT CONVERSION----------------------------------------\n\n' Local variables used as Conversion Factors\nDim LengthConversionFactor As Double\nDim AngleConversionFactor As Double\n\n' Use a Select Case, to get the length of active Unit and set the different factors\nSelect Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n  \n  Case swMETER    ' If length is in Meter\n    LengthConversionFactor = 1\n    AngleConversionFactor = 1\n  \n  Case swMM       ' If length is in MM\n    LengthConversionFactor = 1 / 1000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swCM       ' If length is in CM\n    LengthConversionFactor = 1 / 100\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swINCHES   ' If length is in INCHES\n    LengthConversionFactor = 1 * 0.0254\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEET     ' If length is in FEET\n    LengthConversionFactor = 1 * (0.0254 * 12)\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEETINCHES     ' If length is in FEET & INCHES\n    LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swANGSTROM        ' If length is in ANGSTROM\n    LengthConversionFactor = 1 / 10000000000#\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swNANOMETER       ' If length is in NANOMETER\n    LengthConversionFactor = 1 / 1000000000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swMICRON       ' If length is in MICRON\n    LengthConversionFactor = 1 / 1000000\n    AngleConversionFactor = 1 * 0.01745329\nEnd Select\n\n'----------------------------------------------------------------\n")),(0,i.kt)("p",null,"Above code sample shows how to ",(0,i.kt)("strong",{parentName:"p"},"fix Solidworks API Unit issue"),". "),(0,i.kt)("p",null,"We ",(0,i.kt)("em",{parentName:"p"},"1st")," get the ",(0,i.kt)("em",{parentName:"p"},"current unit")," of the part and apply the ",(0,i.kt)("em",{parentName:"p"},"switch")," statements to update our ",(0,i.kt)("em",{parentName:"p"},"Length and Angle Conversion factors"),". "),(0,i.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"I have already explained in detail about ",(0,i.kt)("strong",{parentName:"p"},"Fixing Solidworks API Unit Issue")," in \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/unit-correction"},"General - Fix Unit Issue"))," blog post. "))),(0,i.kt)("p",null,"Do checkout above post for Fixing Solidworks API Issue."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,i.kt)("p",null,"In above line, we select the ",(0,i.kt)("em",{parentName:"p"},"front plane")," by using ",(0,i.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,i.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,i.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"For more information about selection method please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),(0,i.kt)("p",null,"In above line, we set the ",(0,i.kt)("em",{parentName:"p"},"Sketch manager")," variable to ",(0,i.kt)("em",{parentName:"p"},"current document's sketch manager"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Insert a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,i.kt)("p",null,"In above line, we use ",(0,i.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,i.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,i.kt)("p",null,"This method allows us to insert a sketch in selected plane."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Circle Radius\nDim circleRadius As Double\ncircleRadius = 5 * LengthConversionFactor\n")),(0,i.kt)("p",null,"In above code sample, we do following:"),(0,i.kt)("ol",null,(0,i.kt)("li",{parentName:"ol"},(0,i.kt)("p",{parentName:"li"},"Create a local variable named ",(0,i.kt)("inlineCode",{parentName:"p"},"circleRadius"),", which is ",(0,i.kt)("inlineCode",{parentName:"p"},"Double")," type.")),(0,i.kt)("li",{parentName:"ol"},(0,i.kt)("p",{parentName:"li"},"In 2nd line, we assign a value of ",(0,i.kt)("strong",{parentName:"p"},"5")," to our ",(0,i.kt)("inlineCode",{parentName:"p"},"circleRadius")," variable, also we multiple with our ",(0,i.kt)("inlineCode",{parentName:"p"},"LengthConversionFactor")," variable."))),(0,i.kt)("p",null,"Since I am using ",(0,i.kt)("em",{parentName:"p"},"IPS unit system"),", I want to create a circle of Radius ",(0,i.kt)("em",{parentName:"p"},"5 inch"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch Segment value and Create a Circle\nSet swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, circleRadius)\n")),(0,i.kt)("p",null,"In above line, we set the value of Solidworks Sketch Segment variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," by ",(0,i.kt)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method from ",(0,i.kt)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,i.kt)("p",null,"This ",(0,i.kt)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method creates ",(0,i.kt)("em",{parentName:"p"},"a Circle")," at given point with radius."),(0,i.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"For more information about ",(0,i.kt)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method, you can read my \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-circle-by-radius"},"Solidworks Macro - Create Circle By Radius"))," post."))),(0,i.kt)("p",null,"That post describe all the parameters we need for this ",(0,i.kt)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method in details."),(0,i.kt)("p",null,"In above line, we create a Circle with:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Circle Centerpoint")," : At origin i.e. ",(0,i.kt)("em",{parentName:"p"},"(0, 0, 0)"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Circle Radius")," : ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"circleRadius"))))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Sketch after creation\nswDoc.ClearSelection2 True\n")),(0,i.kt)("p",null,"In the above line of code, we deselect the ",(0,i.kt)("strong",{parentName:"p"},"Sketch")," after the ",(0,i.kt)("em",{parentName:"p"},"Circular Sketch Pattern")," operation."),(0,i.kt)("p",null,"For de-selecting, we use ",(0,i.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",(0,i.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Circle we want to Pattern\nBoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,i.kt)("p",null,"In above line of code, we select the Circle i.e. ",(0,i.kt)("strong",{parentName:"p"},"Arc 1")," and add it to selection list."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Arc Radius\nDim arcRadius As Double\narcRadius = 10 * LengthConversionFactor\n")),(0,i.kt)("p",null,"Above code sample creates a variable for ",(0,i.kt)("strong",{parentName:"p"},"Arc Radius")," and assign value."),(0,i.kt)("p",null,"While assigning the value we multiple with ",(0,i.kt)("inlineCode",{parentName:"p"},"LengthConversionFactor")," to get correct length."),(0,i.kt)("p",null,"Variable Name: ",(0,i.kt)("inlineCode",{parentName:"p"},"arcRadius")),(0,i.kt)("p",null,"Variable type: ",(0,i.kt)("inlineCode",{parentName:"p"},"Double")),(0,i.kt)("p",null,"Variable Value: 10 inch"),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"We want Arc Radius to 10 inch.")),(0,i.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"NOTE")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},(0,i.kt)("strong",{parentName:"p"},"By creating the variables we can handle the values more effciently.")))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Arc Angle\nDim arcAngle As Double\narcAngle = 0 * AngleConversionFactor\n")),(0,i.kt)("p",null,"Above code sample creates a variable for ",(0,i.kt)("strong",{parentName:"p"},"Arc Angle")," and assign value."),(0,i.kt)("p",null,"While assigning the value we multiple with ",(0,i.kt)("inlineCode",{parentName:"p"},"AngleConversionFactor")," to get correct angle."),(0,i.kt)("p",null,"Variable Name: ",(0,i.kt)("inlineCode",{parentName:"p"},"arcAngle")),(0,i.kt)("p",null,"Variable type: ",(0,i.kt)("inlineCode",{parentName:"p"},"Double")),(0,i.kt)("p",null,"Variable Value: 0"),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"We want Arc Angle to 0 degree.")),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Number of Instances\nDim numberOfInstance As Double\nnumberOfInstance = 3\n")),(0,i.kt)("p",null,"Above code sample creates a variable for ",(0,i.kt)("strong",{parentName:"p"},"Number of Instances")," and assign value."),(0,i.kt)("p",null,"Variable Name: ",(0,i.kt)("inlineCode",{parentName:"p"},"numberOfInstance")),(0,i.kt)("p",null,"Variable type: ",(0,i.kt)("inlineCode",{parentName:"p"},"Double")),(0,i.kt)("p",null,"Variable Value: 3"),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"We want 3 copies of the circle including the seed i.e. original circle.")),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Pattern Spacing\nDim patternSpacing As Double\npatternSpacing = 5 * AngleConversionFactor\n")),(0,i.kt)("p",null,"Above code sample creates a variable for ",(0,i.kt)("strong",{parentName:"p"},"Pattern Spacing")," and assign value."),(0,i.kt)("p",null,"While assigning the value we multiple with ",(0,i.kt)("inlineCode",{parentName:"p"},"AngleConversionFactor")," to get correct angle."),(0,i.kt)("p",null,"Variable Name: ",(0,i.kt)("inlineCode",{parentName:"p"},"patternSpacing")),(0,i.kt)("p",null,"Variable type: ",(0,i.kt)("inlineCode",{parentName:"p"},"Double")),(0,i.kt)("p",null,"Variable Value: 5"),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"We want 5 degree of spacing between each circle.")),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Create a Circular Sketch Pattern\nBoolStatus = swSketchManager.CreateCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, True, "", True, True, True)\n')),(0,i.kt)("p",null,"In above code sample we ",(0,i.kt)("em",{parentName:"p"},"Create a Circular Sketch Pattern")," of the selected circle by ",(0,i.kt)("inlineCode",{parentName:"p"},"CreateCircularSketchStepAndRepeat")," method from ",(0,i.kt)("em",{parentName:"p"},"Solidworks Sketch Manger")," variable."),(0,i.kt)("p",null,"As you can see we pass our ",(0,i.kt)("em",{parentName:"p"},"previously created variables")," ",(0,i.kt)("inlineCode",{parentName:"p"},"arcRadius"),", ",(0,i.kt)("inlineCode",{parentName:"p"},"arcAngle"),", ",(0,i.kt)("inlineCode",{parentName:"p"},"numberOfInstance")," and ",(0,i.kt)("inlineCode",{parentName:"p"},"patternSpacing")," in ",(0,i.kt)("inlineCode",{parentName:"p"},"CreateCircularSketchStepAndRepeat")," method as parameters."),(0,i.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"I have explained ",(0,i.kt)("inlineCode",{parentName:"p"},"CreateCircularSketchStepAndRepeat")," method in detail in \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/circular-skech-pattern"},"Sketch - Circular Sketch Pattern"))," post."))),(0,i.kt)("p",null,"Please see above post if you want to learn more about ",(0,i.kt)("inlineCode",{parentName:"p"},"CreateCircularSketchStepAndRepeat")," method and its parameters."),(0,i.kt)("p",null,"Below image shows Circular Sketch Pattern Parameter."),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"before-edit-circular-pattern",src:n(37316).Z,width:"1122",height:"554"})),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Sketch Segment after Circular Sketch Pattern\nswDoc.ClearSelection2 True\n")),(0,i.kt)("p",null,"In above line we ",(0,i.kt)("em",{parentName:"p"},"de-select")," the ",(0,i.kt)("em",{parentName:"p"},"Sketch Segment")," after creating ",(0,i.kt)("em",{parentName:"p"},"Circular Sketch Pattern"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Update Arc Radius\narcRadius = 20 * LengthConversionFactor\n")),(0,i.kt)("p",null,"In above line we ",(0,i.kt)("strong",{parentName:"p"},"Update Arc Radius")," to new value which we will use in ",(0,i.kt)("em",{parentName:"p"},"Editing previously created Circular Sketch pattern"),"."),(0,i.kt)("p",null,"Variable Name: ",(0,i.kt)("inlineCode",{parentName:"p"},"arcRadius")),(0,i.kt)("p",null,"Updated Value: 20 inch"),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Edit a Circular Sketch Pattern\nBoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, True, "", True, True, True, "Arc1_")\n')),(0,i.kt)("p",null,'For "',(0,i.kt)("strong",{parentName:"p"},"editing"),'" a Circular Sketch pattern, we need ',(0,i.kt)("inlineCode",{parentName:"p"},"EditCircularSketchStepAndRepeat")," method from ",(0,i.kt)("em",{parentName:"p"},"Solidworks Sketch Manager")," object/variable."),(0,i.kt)("p",null,"This ",(0,i.kt)("inlineCode",{parentName:"p"},"CreateCircularSketchStepAndRepeat")," method takes following parameters as explained:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"ArcRadius")," : ",(0,i.kt)("em",{parentName:"p"},"Radius for the circular sketch pattern. This value is in radian."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"ArcAngle")," : ",(0,i.kt)("em",{parentName:"p"},"Angle relative to the sketch entities being patterned. This value is in radian."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"PatternNum")," : ",(0,i.kt)("em",{parentName:"p"},"Total number of instances, including the seed geometry."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"PatternSpacing")," : ",(0,i.kt)("em",{parentName:"p"},"Spacing between pattern instances. This value is in radian."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"PatternRotate")," : ",(0,i.kt)("em",{parentName:"p"},"True to rotate the pattern, false to not."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"DeleteInstances")," : ",(0,i.kt)("em",{parentName:"p"},'Number of instances to delete, passed as a string in the format: "(a) (b) (c)".'))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"RadiusDim")," : ",(0,i.kt)("em",{parentName:"p"},"True to display the radius dimension in the graphics area, false to not."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"AngleDim")," : ",(0,i.kt)("em",{parentName:"p"},"True to display the angle dimension between axes in the graphics area, false to not."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"CreateNumOfInstancesDim")," : ",(0,i.kt)("em",{parentName:"p"},"True to display the number of instances dimension in the graphics area, false to not."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Seed"),": ",(0,i.kt)("em",{parentName:"p"},"List of the names of the entities, separated by the underscore character (",(0,i.kt)("em",{parentName:"em"},"), that comprise the seed pattern (e.g., Arc1")," as a seed pattern).")))),(0,i.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"NOTE")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"In ",(0,i.kt)("em",{parentName:"p"},"Seed"),", adding underscore(_) after selected entity is important, otherwise code will note work."))),(0,i.kt)("p",null,"After the function complete following are the results:"),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Return Value"),":"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"True"),": ",(0,i.kt)("em",{parentName:"p"},"If Edit Circular Sketch Pattern is "),"Success",(0,i.kt)("em",{parentName:"p"},"."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"False"),": ",(0,i.kt)("em",{parentName:"p"},"If Edit Circular Sketch Pattern is "),"Fail",(0,i.kt)("em",{parentName:"p"},".")))),(0,i.kt)("hr",null),(0,i.kt)(o.Z,{mdxType:"AdComponent"}),(0,i.kt)("h3",{id:"cases"},(0,i.kt)("strong",{parentName:"h3"},"Cases")),(0,i.kt)("p",null,"In this section, we will go through different cases by "),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("em",{parentName:"p"},"Modifying different parameters"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("em",{parentName:"p"},"See images, before and after parameter modification")))),(0,i.kt)("hr",null),(0,i.kt)("h4",{id:"case-1--update-arc-radius"},"CASE 1 : Update Arc Radius"),(0,i.kt)("p",null,"In our code, if we want to update Arc Radius, then we need to update ",(0,i.kt)("inlineCode",{parentName:"p"},"arcRadius")," variable only."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Update Arc Radius\narcRadius = 20 * LengthConversionFactor\n")),(0,i.kt)("p",null,"In above line we ",(0,i.kt)("strong",{parentName:"p"},"Update Arc Radius")," to new value. of 20 inch."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"Example Images:"))),(0,i.kt)("p",null,"Below image shows before and after we update ",(0,i.kt)("strong",{parentName:"p"},"Arc Radius"),"."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Before Update Arc Radius")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"before-edit-circular-pattern",src:n(37316).Z,width:"1122",height:"554"})),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"After Update Arc Radius")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-arc-radius",src:n(34999).Z,width:"1123",height:"555"})),(0,i.kt)("h4",{id:"case-2--update-arc-angle"},"CASE 2 : Update Arc Angle"),(0,i.kt)("p",null,"In our code, if we want to update Arc Angle, then we need to update ",(0,i.kt)("inlineCode",{parentName:"p"},"arcAngle")," variable only."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Update Arc Angle\narcAngle = 30 * AngleConversionFactor\n")),(0,i.kt)("p",null,"In above line we ",(0,i.kt)("strong",{parentName:"p"},"Update Arc Angle")," to new value of 30 inch."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"Example Images:"))),(0,i.kt)("p",null,"Below image shows before and after we update ",(0,i.kt)("strong",{parentName:"p"},"Arc Angle"),"."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Before Update Arc Angle")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-arc-radius",src:n(34999).Z,width:"1123",height:"555"})),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"After Update Arc Angle")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-arc-angle",src:n(3633).Z,width:"1122",height:"556"})),(0,i.kt)(o.Z,{mdxType:"AdComponent"}),(0,i.kt)("h4",{id:"case-3--update-number-of-instances"},"CASE 3 : Update Number of Instances"),(0,i.kt)("p",null,"In our code, if we want to update Number of Instances, then we need to update ",(0,i.kt)("inlineCode",{parentName:"p"},"numberOfInstance")," variable only."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Update Number of Instances\nnumberOfInstance = 5\n")),(0,i.kt)("p",null,"In above line we ",(0,i.kt)("strong",{parentName:"p"},"Update Number of Instances")," to new value of 5 number of instances."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"Example Images:"))),(0,i.kt)("p",null,"Below image shows before and after we update ",(0,i.kt)("strong",{parentName:"p"},"Number of Instances"),"."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Before Update Number of Instances")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-arc-angle",src:n(3633).Z,width:"1122",height:"556"})),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"After Update Number of Instances")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-number-of-instances",src:n(95730).Z,width:"1125",height:"556"})),(0,i.kt)("h4",{id:"case-4--update-pattern-spacing"},"CASE 4 : Update Pattern Spacing"),(0,i.kt)("p",null,"In our code, if we want to update Number of Instances, then we need to update ",(0,i.kt)("inlineCode",{parentName:"p"},"patternSpacing")," variable only."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Update Pattern Spacing\npatternSpacing = 10 * AngleConversionFactor\n")),(0,i.kt)("p",null,"In above line we ",(0,i.kt)("strong",{parentName:"p"},"Update Pattern Spacing")," to new value of 10 degree."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"Example Images:"))),(0,i.kt)("p",null,"Below image shows before and after we update ",(0,i.kt)("strong",{parentName:"p"},"Pattern Spacing"),"."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Before Update Pattern Spacing")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-number-of-instances",src:n(95730).Z,width:"1125",height:"556"})),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"After Update Pattern Spacing")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-pattern-spacing",src:n(70467).Z,width:"1122",height:"555"})),(0,i.kt)(o.Z,{mdxType:"AdComponent"}),(0,i.kt)("h4",{id:"case-5--update-display-rotation-of-pattern"},"CASE 5 : Update Display Rotation of Pattern"),(0,i.kt)("p",null,"If we want to update Display Rotation of Pattern, then we need to update value to either ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," or ",(0,i.kt)("inlineCode",{parentName:"p"},"False"),"."),(0,i.kt)("p",null,"In our code, we set this value to ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," which means we are displaying the rotation of pattern."),(0,i.kt)("p",null,"We update our code for not displaying the rotation of pattern as given in below code sample."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Edit a Circular Sketch Pattern\nBoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, False, "", True, True, True, "Arc1_")\n')),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"Example Images:"))),(0,i.kt)("p",null,"Below image shows before and after we update ",(0,i.kt)("strong",{parentName:"p"},"Display Rotation of Pattern"),"."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Before Update Display Rotation of Pattern")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-pattern-spacing",src:n(70467).Z,width:"1122",height:"555"})),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"After Update Display Rotation of Pattern")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-rotation-of-pattern",src:n(13631).Z,width:"1122",height:"555"})),(0,i.kt)("h4",{id:"case-6--update-number-of-instances-to-delete"},"CASE 6 : Update Number of Instances to Delete"),(0,i.kt)("p",null,"If we want to update Number of Instances to Delete, then we need to update value of ",(0,i.kt)("inlineCode",{parentName:"p"},'""')," as given in below code sample."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Edit a Circular Sketch Pattern\nBoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, False, "(3)", True, True, True, "Arc1_")\n')),(0,i.kt)("p",null,"In above code sample, we want to delete 3rd instance hence we pass the number ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"strong"},"3"))," inside ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"strong"},"()")),"."),(0,i.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"NOTE")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"For delete any instance we need to pass its position in paranthesis (). Otherwise it won't work."))),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"Example Images:"))),(0,i.kt)("p",null,"Below image shows before and after we update ",(0,i.kt)("strong",{parentName:"p"},"Number of Instances to Delete"),"."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Before Update Number of Instances to Delete")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-pattern-spacing",src:n(70467).Z,width:"1122",height:"555"})),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"After Update Number of Instances to Delete")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-number-of-instance-to-delete",src:n(81709).Z,width:"1125",height:"557"})),(0,i.kt)(o.Z,{mdxType:"AdComponent"}),(0,i.kt)("h4",{id:"case-7--update-display-radius-dimension"},"CASE 7 : Update Display Radius Dimension"),(0,i.kt)("p",null,"If we want to update Display Radius Dimension, then we need to update value to either ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," or ",(0,i.kt)("inlineCode",{parentName:"p"},"False"),"."),(0,i.kt)("p",null,"In our code, we set this value to ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," which means we are displaying the Display Radius Dimension."),(0,i.kt)("p",null,"We update our code for not displaying the Display Radius Dimension as given in below code sample."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Edit a Circular Sketch Pattern\nBoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, False, "(3)", False, True, True, "Arc1_")\n')),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"Example Images:"))),(0,i.kt)("p",null,"Below image shows before and after we update ",(0,i.kt)("strong",{parentName:"p"},"Display Radius Dimension"),"."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Before Update Display Radius Dimension")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-number-of-instance-to-delete",src:n(81709).Z,width:"1125",height:"557"})),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"After Update Display Radius Dimension")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-display-radius-dimension",src:n(61647).Z,width:"1124",height:"554"})),(0,i.kt)("h4",{id:"case-8--update-display-angle-dimension"},"CASE 8 : Update Display Angle Dimension"),(0,i.kt)("p",null,"If we want to update Display Angle Dimension, then we need to update value to either ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," or ",(0,i.kt)("inlineCode",{parentName:"p"},"False"),"."),(0,i.kt)("p",null,"In our code, we set this value to ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," which means we are displaying the Display Angle Dimension."),(0,i.kt)("p",null,"We update our code for not displaying the Display Angle Dimension as given in below code sample."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Edit a Circular Sketch Pattern\nBoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, False, "(3)", False, False, True, "Arc1_")\n')),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"Example Images:"))),(0,i.kt)("p",null,"Below image shows before and after we update ",(0,i.kt)("strong",{parentName:"p"},"Display Angle Dimension"),"."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Before Update Display Angle Dimension")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-number-of-instance-to-delete",src:n(81709).Z,width:"1125",height:"557"})),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"After Update Display Angle Dimension")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-display-angle-dimension",src:n(97067).Z,width:"1122",height:"554"})),(0,i.kt)("h4",{id:"case-9--update-display-number-of-instances"},"CASE 9 : Update Display Number of Instances"),(0,i.kt)("p",null,"If we want to update Display Number of Instances, then we need to update value to either ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," or ",(0,i.kt)("inlineCode",{parentName:"p"},"False"),"."),(0,i.kt)("p",null,"In our code, we set this value to ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," which means we are displaying the Display Number of Instances."),(0,i.kt)("p",null,"We update our code for not displaying the Display Number of Instances as given in below code sample."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Edit a Circular Sketch Pattern\nBoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, False, "(3)", False, False, False, "Arc1_")\n')),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"Example Images:"))),(0,i.kt)("p",null,"Below image shows before and after we update ",(0,i.kt)("strong",{parentName:"p"},"Display Number of Instances"),"."),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Before Update Display Number of Instances")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-number-of-instance-to-delete",src:n(81709).Z,width:"1125",height:"557"})),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"After Update Display Number of Instances")),(0,i.kt)("p",null,(0,i.kt)("img",{alt:"after-update-display-number-of-instance",src:n(90239).Z,width:"1122",height:"554"})),(0,i.kt)("hr",null),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"This is it !!!")),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"It is indeed a very LONG post. But I try to update the code and move into the direction where we were able to use these code samples in UserForms.")),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"I hope you like my effort!!!")),(0,i.kt)("p",null,"If you found anything to add or update, please let me know on my e-mail."),(0,i.kt)("p",null,"Hope this post helps you to ",(0,i.kt)("em",{parentName:"p"},"Edit a Circular Sketch Pattern")," with Solidworks VBA Macros."),(0,i.kt)("p",null,"For more such tutorials on ",(0,i.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"Do let me know by you like this post or not!")),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"Till then, Happy learning!!!")))}k.isMDXComponent=!0},74753:function(e,t,n){n.d(t,{Z:function(){return i}});var a=n(94578),r=n(67294),i=function(e){function t(){return e.apply(this,arguments)||this}(0,a.Z)(t,e);var n=t.prototype;return n.componentDidMount=function(){var e;(e=document.createElement("script")).src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild),(window.adsbygoogle=window.adsbygoogle||[]).push({})},n.render=function(){return r.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})},t}(r.Component)},3633:function(e,t,n){t.Z=n.p+"assets/images/after-update-arc-angle-e6e465fb88ffd4a8f6d2cfbe60753bdf.png"},34999:function(e,t,n){t.Z=n.p+"assets/images/after-update-arc-radius-3677d25642762b746e9ef6dcc6f32241.png"},97067:function(e,t,n){t.Z=n.p+"assets/images/after-update-display-angle-dimension-c5549bc4b01f68053a3a486453c020e8.png"},90239:function(e,t,n){t.Z=n.p+"assets/images/after-update-display-number-of-instance-530f548b755237d639db2499743c5f7d.png"},61647:function(e,t,n){t.Z=n.p+"assets/images/after-update-display-radius-dimension-0170696abf2326d18f1321de4348564b.png"},81709:function(e,t,n){t.Z=n.p+"assets/images/after-update-number-of-instance-to-delete-82c7f1c197a256a08bd621e106dea366.png"},95730:function(e,t,n){t.Z=n.p+"assets/images/after-update-number-of-instances-e8ad5a826c39937cc230b222c0f53557.png"},70467:function(e,t,n){t.Z=n.p+"assets/images/after-update-pattern-spacing-5af114e7a240763542004d930cfce8b9.png"},13631:function(e,t,n){t.Z=n.p+"assets/images/after-update-rotation-of-pattern-5af114e7a240763542004d930cfce8b9.png"},37316:function(e,t,n){t.Z=n.p+"assets/images/before-edit-circular-pattern-fe419f8b4250220bfc3613b83491a87d.png"}}]);