"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[4777],{3905:function(e,t,a){a.d(t,{Zo:function(){return m},kt:function(){return u}});var n=a(67294);function r(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}function i(e,t){var a=Object.keys(e);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);t&&(n=n.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),a.push.apply(a,n)}return a}function o(e){for(var t=1;t<arguments.length;t++){var a=null!=arguments[t]?arguments[t]:{};t%2?i(Object(a),!0).forEach((function(t){r(e,t,a[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(a)):i(Object(a)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(a,t))}))}return e}function s(e,t){if(null==e)return{};var a,n,r=function(e,t){if(null==e)return{};var a,n,r={},i=Object.keys(e);for(n=0;n<i.length;n++)a=i[n],t.indexOf(a)>=0||(r[a]=e[a]);return r}(e,t);if(Object.getOwnPropertySymbols){var i=Object.getOwnPropertySymbols(e);for(n=0;n<i.length;n++)a=i[n],t.indexOf(a)>=0||Object.prototype.propertyIsEnumerable.call(e,a)&&(r[a]=e[a])}return r}var l=n.createContext({}),p=function(e){var t=n.useContext(l),a=t;return e&&(a="function"==typeof e?e(t):o(o({},t),e)),a},m=function(e){var t=p(e.components);return n.createElement(l.Provider,{value:t},e.children)},d={inlineCode:"code",wrapper:function(e){var t=e.children;return n.createElement(n.Fragment,{},t)}},k=n.forwardRef((function(e,t){var a=e.components,r=e.mdxType,i=e.originalType,l=e.parentName,m=s(e,["components","mdxType","originalType","parentName"]),k=p(a),u=r,c=k["".concat(l,".").concat(u)]||k[u]||d[u]||i;return a?n.createElement(c,o(o({ref:t},m),{},{components:a})):n.createElement(c,o({ref:t},m))}));function u(e,t){var a=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var i=a.length,o=new Array(i);o[0]=k;var s={};for(var l in t)hasOwnProperty.call(t,l)&&(s[l]=t[l]);s.originalType=e,s.mdxType="string"==typeof e?e:r,o[1]=s;for(var p=2;p<i;p++)o[p]=a[p];return n.createElement.apply(null,o)}return n.createElement.apply(null,a)}k.displayName="MDXCreateElement"},69969:function(e,t,a){a.r(t),a.d(t,{assets:function(){return d},contentTitle:function(){return p},default:function(){return c},frontMatter:function(){return l},metadata:function(){return m},toc:function(){return k}});var n=a(87462),r=a(63366),i=(a(67294),a(3905)),o=a(74753),s=["components"],l={categories:"Solidworks-macro",title:"Solidworks Macro - Create Extrude/Boss",permalink:"/solidworks-macros/create-extrude-feature/",tags:["Solidworks Macro"],id:"feature-create-extrude-boss"},p=void 0,m={unversionedId:"feature-create-extrude-boss",id:"feature-create-extrude-boss",title:"Solidworks Macro - Create Extrude/Boss",description:"",source:"@site/docs/solidworks-macros/015.1-feature-create-extrude-boss.md",sourceDirName:".",slug:"/feature-create-extrude-boss",permalink:"/solidworks-macros/feature-create-extrude-boss",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Create Extrude/Boss",permalink:"/solidworks-macros/create-extrude-feature/",tags:["Solidworks Macro"],id:"feature-create-extrude-boss"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Add dimension to Sketch Entities",permalink:"/solidworks-macros/add-dimension-methods"},next:{title:"Solidworks Macro - Create Revolved Boss/Base",permalink:"/solidworks-macros/feature-create-revolve-boss"}},d={},k=[{value:"Code Sample",id:"code-sample",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:2},{value:"Method Parameters Details",id:"method-parameters-details",level:2}],u={toc:k};function c(e){var t=e.components,l=(0,r.Z)(e,s);return(0,i.kt)("wrapper",(0,n.Z)({},u,l,{components:t,mdxType:"MDXLayout"}),(0,i.kt)(o.Z,{mdxType:"AdComponent"}),(0,i.kt)("p",null,"In this post, I tell you about ",(0,i.kt)("em",{parentName:"p"},"how to create Extrude/Boss through Solidworks VBA Macros")," in a sketch."),(0,i.kt)("p",null,"In this post, I tell you about ",(0,i.kt)("inlineCode",{parentName:"p"},"FeatureExtrusion3")," method from ",(0,i.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,i.kt)("inlineCode",{parentName:"p"},"FeatureManager")," object."),(0,i.kt)("p",null,"This method is ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"most updated"))," method, I found in ",(0,i.kt)("em",{parentName:"p"},"Solidworks API Help"),". "),(0,i.kt)("p",null,"So ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"use this method"))," if you want to create a new ",(0,i.kt)("strong",{parentName:"p"},"Corner Extrude/Boss"),"."),(0,i.kt)("hr",null),(0,i.kt)("h2",{id:"code-sample"},"Code Sample"),(0,i.kt)("p",null,"Below is the ",(0,i.kt)("inlineCode",{parentName:"p"},"code")," sample for creating Corner Rectangle."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Boolean Variable\nDim BoolStatus As Boolean\n' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n' Creating variable for Solidworks Feature\nDim swFeature As SldWorks.Feature\n\n' Main function of our VBA program\nSub main()\n\n  ' Setting Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Creating string type variable for storing default part location\n  Dim defaultTemplate As String\n  ' Setting value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Setting Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n  ' Selecting Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Setting Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n  \n  ' Inserting a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Creating a \"Variant\" Variable which holds the values return by \"CreateCornerRectangle\" method\n  Dim vSketchLines As Variant\n  \n  ' Creating a Corner Rectangle\n  vSketchLines = swSketchManager.CreateCornerRectangle(0, 1, 0, 1, 0, 0)\n  \n  ' De-select the lines after creation\n  swDoc.ClearSelection2 True\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n  \n  ' Exit the Sketch\n  swSketchManager.InsertSketch True\n\n  ' Create Extrude Feature\n  Set swFeature = swDoc.FeatureManager.FeatureExtrusion3(True, False, False, swEndConditions_e.swEndCondBlind, swEndConditions_e.swEndCondBlind, 2, 0, False, False, False, True, 0, 0, False, False, False, False, True, False, True, swEndConditions_e.swEndCondBlind, 0, False)\n\nEnd Sub\n")),(0,i.kt)("hr",null),(0,i.kt)("h2",{id:"understanding-the-code"},"Understanding the Code"),(0,i.kt)("p",null,"Now let us walk through ",(0,i.kt)("strong",{parentName:"p"},"each line")," in the above code, and ",(0,i.kt)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),(0,i.kt)("p",null,"I also give some link so that you can go through them if there are anything I explained in previous posts."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,i.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,i.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"For more information please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,i.kt)("p",null,"In this line, we create a variable which we named as ",(0,i.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,i.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,i.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,i.kt)("p",null,"In this line, we create a variable which we named as ",(0,i.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,i.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,i.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,i.kt)("p",null,"In this line, we create a variable named ",(0,i.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,i.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),(0,i.kt)("p",null,"In above line, we create variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swSketchManager")," for ",(0,i.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,i.kt)("p",null,"As the name suggested, a ",(0,i.kt)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",(0,i.kt)("em",{parentName:"p"},"Sketches"),"."),(0,i.kt)("p",null,"To see methods and properties related to ",(0,i.kt)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this page of Solidworks API Help"))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Feature\nDim swFeature As SldWorks.Feature\n")),(0,i.kt)("p",null,"In this line, we Create a variable which we named as ",(0,i.kt)("inlineCode",{parentName:"p"},"swFeature")," and the type of this ",(0,i.kt)("inlineCode",{parentName:"p"},"swFeature")," variable is ",(0,i.kt)("inlineCode",{parentName:"p"},"SldWorks.Feature"),"."),(0,i.kt)("p",null,"We create variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swFeature")," for ",(0,i.kt)("strong",{parentName:"p"},"Solidworks Feature"),"."),(0,i.kt)("p",null,"To see methods and properties related to ",(0,i.kt)("inlineCode",{parentName:"p"},"Feature")," object, please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeature_members.html"},"this page of Solidworks API Help"))),(0,i.kt)("p",null,"These all are our global variables."),(0,i.kt)("p",null,"As you can see in code sample, they are ",(0,i.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,i.kt)("p",null,"So basically I group all the ",(0,i.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,i.kt)("p",null,"I have also place ",(0,i.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",(0,i.kt)("em",{parentName:"p"},"need")," this variable frequently."),(0,i.kt)("p",null,"Thus, I have started placing it here."),(0,i.kt)("p",null,"Next is our ",(0,i.kt)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",(0,i.kt)("inlineCode",{parentName:"p"},"main"),". "),(0,i.kt)("p",null,"This procedure hold all the ",(0,i.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,i.kt)("p",null,"In this line, we set the value of our Solidworks variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create string type variable for storing default part location\nDim defaultTemplate As String\n' Set value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),(0,i.kt)("p",null,"In 1st statement of above example, we are defining a variable of ",(0,i.kt)("inlineCode",{parentName:"p"},"string")," type and named it as ",(0,i.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),(0,i.kt)("p",null,"This variable ",(0,i.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",(0,i.kt)("strong",{parentName:"p"},"Default Part Template"),"."),(0,i.kt)("p",null,"In 2nd line of above example. we assign value to our newly define ",(0,i.kt)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),(0,i.kt)("p",null,"We assign the value by using a ",(0,i.kt)("em",{parentName:"p"},"Method")," named ",(0,i.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),(0,i.kt)("p",null,"This ",(0,i.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," method is a part of our main Solidworks variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swApp"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),(0,i.kt)("p",null,"In this line, we set the value of our ",(0,i.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),(0,i.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"For ",(0,i.kt)("strong",{parentName:"p"},"detailed information")," about these lines please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."),(0,i.kt)("p",{parentName:"div"},"I have discussed them ",(0,i.kt)("strong",{parentName:"p"},"thoroghly")," in \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post, so do checkout that post if you want to understand above code in more detail."))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,i.kt)("p",null,"In above line, we select the ",(0,i.kt)("em",{parentName:"p"},"front plane")," by using ",(0,i.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,i.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,i.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"For more information about selection method please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),(0,i.kt)("p",null,"In above line, we set the ",(0,i.kt)("em",{parentName:"p"},"Sketch manager")," variable to ",(0,i.kt)("em",{parentName:"p"},"current document's sketch manager"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Insert a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,i.kt)("p",null,"In above line, we use ",(0,i.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,i.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,i.kt)("p",null,"This method allows us to ",(0,i.kt)("strong",{parentName:"p"},"insert")," a sketch in selected plane."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Creating a "Variant" Variable which holds the values return by "CreateCornerRectangle" method\nDim vSketchLines As Variant\n    \n\' Creating a Corner Rectangle\nvSketchLines = swSketchManager.CreateCornerRectangle(0, 1, 0, 1, 0, 0)\n')),(0,i.kt)("p",null,"In above sample code, we 1st create a variable named ",(0,i.kt)("inlineCode",{parentName:"p"},"vSketchLines")," of type ",(0,i.kt)("inlineCode",{parentName:"p"},"Variant"),"."),(0,i.kt)("p",null,"A ",(0,i.kt)("inlineCode",{parentName:"p"},"Variant")," type variable can hold ",(0,i.kt)("strong",{parentName:"p"},"any")," type of value depends upon the use of variable."),(0,i.kt)("p",null,"In 2nd line, we set the value of variable ",(0,i.kt)("inlineCode",{parentName:"p"},"vSketchLines"),"."),(0,i.kt)("p",null,"In the above code sample I have used (0, 1, 0) Upper-left point in ",(0,i.kt)("em",{parentName:"p"},"Y-direction"),"."),(0,i.kt)("p",null,"For Lower-right point I used (1, 0, 0) which is 1 point distance in ",(0,i.kt)("em",{parentName:"p"},"X-direction"),"."),(0,i.kt)("p",null,"This ",(0,i.kt)("inlineCode",{parentName:"p"},"CreateCornerRectangle")," method returns ",(0,i.kt)("strong",{parentName:"p"},"an array")," of ",(0,i.kt)("em",{parentName:"p"},"sketch segments")," that represent the edges created for this corner rectangle."),(0,i.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"For more information about ",(0,i.kt)("strong",{parentName:"p"},"Create Corner Rectangle")," please visit \ud83d\ude80 ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-corner-rectangle"},"Solidworks Macros - Selection Methods"))," post."))),(0,i.kt)("div",{className:"admonition admonition-caution alert alert--warning"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"}))),"NOTE")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"It is ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",(0,i.kt)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("em",{parentName:"strong"},"Meter only")),".",(0,i.kt)("br",null),"\nSolidworks API does not care about your application's Unit systems.",(0,i.kt)("br",null),"\nFor example, I works in ANSI system means inches for distance.",(0,i.kt)("br",null)," But when I used Solidworks API through VBA macros or C#, I need to use converted numeric values.",(0,i.kt)("br",null),"\nBecause Solidworks API output the distance in ",(0,i.kt)("strong",{parentName:"p"},"Meter")," which is not my requirement."))),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the lines after creation\nswDoc.ClearSelection2 True\n")),(0,i.kt)("p",null,"In the this line of code, we deselect the Corner rectangle we have created."),(0,i.kt)("p",null,"For de-selecting, we use ",(0,i.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",(0,i.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit2\n")),(0,i.kt)("p",null,"In this last line we use ",(0,i.kt)("em",{parentName:"p"},"zoom to fit")," command."),(0,i.kt)("p",null,"For Zoom to fit, we use ",(0,i.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Exit the Sketch\nswSketchManager.InsertSketch True\n")),(0,i.kt)("p",null,"In above line, we use ",(0,i.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,i.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,i.kt)("p",null,"This method allows us to ",(0,i.kt)("strong",{parentName:"p"},"exit")," a sketch in selected plane."),(0,i.kt)("pre",null,(0,i.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create Extrude Feature\nSet swFeature = swDoc.FeatureManager.FeatureExtrusion3(True, False, False, swEndConditions_e.swEndCondBlind, swEndConditions_e.swEndCondBlind, 2, 0, False, False, False, True, 0, 0, False, False, False, False, True, True, True, swEndConditions_e.swEndCondBlind, 0, False)\n")),(0,i.kt)("p",null,"In above line of code we set the value of variable ",(0,i.kt)("inlineCode",{parentName:"p"},"swFeature")," by ",(0,i.kt)("inlineCode",{parentName:"p"},"FeatureExtrusion3")," method."),(0,i.kt)("p",null,(0,i.kt)("inlineCode",{parentName:"p"},"FeatureExtrusion3")," method is part of ",(0,i.kt)("inlineCode",{parentName:"p"},"FeatureManager")," object."),(0,i.kt)("p",null,"This ",(0,i.kt)("inlineCode",{parentName:"p"},"FeatureManager")," is again part of ",(0,i.kt)("inlineCode",{parentName:"p"},"swDoc")," variable i.e. ",(0,i.kt)("inlineCode",{parentName:"p"},"ModelDoc2")," object."),(0,i.kt)(o.Z,{mdxType:"AdComponent"}),(0,i.kt)("h2",{id:"method-parameters-details"},"Method Parameters Details"),(0,i.kt)("p",null,"This ",(0,i.kt)("inlineCode",{parentName:"p"},"FeatureExtrusion3")," method takes following parameters as explained:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Sd")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," for single ended, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," for double ended.")),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(39827).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(77290).Z,width:"405",height:"403"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Flip")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," to flip the side to cut")),(0,i.kt)("div",{parentName:"li",className:"admonition admonition-caution alert alert--warning"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"}))),"caution")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},'This option activate when we select feature "',(0,i.kt)("strong",{parentName:"p"},"Extruded Cut"),'".')))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Dir")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," to flip the direction of extrusion.")),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(5057).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(75465).Z,width:"405",height:"403"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"T1")," - ",(0,i.kt)("em",{parentName:"p"},"Termination type for first end of the extrusion as defined in ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e"),".")),(0,i.kt)("p",{parentName:"li"},"End Conditions has following enumeration values:"),(0,i.kt)("ul",{parentName:"li"},(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondBlind")," or ",(0,i.kt)("strong",{parentName:"p"},"0"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondMidPlane")," or ",(0,i.kt)("strong",{parentName:"p"},"6"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondOffsetFromSurface")," or ",(0,i.kt)("strong",{parentName:"p"},"5"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondThroughAll")," or ",(0,i.kt)("strong",{parentName:"p"},"1"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondThroughAllBoth")," or ",(0,i.kt)("strong",{parentName:"p"},"9"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondThroughNext")," or ",(0,i.kt)("strong",{parentName:"p"},"2"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondUpToBody")," or ",(0,i.kt)("strong",{parentName:"p"},"7"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondUpToNext")," or ",(0,i.kt)("strong",{parentName:"p"},"11"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondUpToSelection")," or ",(0,i.kt)("strong",{parentName:"p"},"10"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondUpToSurface")," or ",(0,i.kt)("strong",{parentName:"p"},"4")," = Do not use; superseded by ",(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondUpToSelection"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondUpToVertex")," or ",(0,i.kt)("strong",{parentName:"p"},"3")," = Do not use; superseded by ",(0,i.kt)("inlineCode",{parentName:"p"},"swEndCondUpToSelection")))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(22572).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(47898).Z,width:"405",height:"403"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"T2")," - ",(0,i.kt)("em",{parentName:"p"},"Termination type for second end of the extrusion as defined in ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e"),".")),(0,i.kt)("p",{parentName:"li"},"End Conditions has enumeration values as described in ",(0,i.kt)("strong",{parentName:"p"},"T1"),"."),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(59220).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(58681).Z,width:"405",height:"392"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"D1")," - ",(0,i.kt)("em",{parentName:"p"},"Depth of extrusion for first end in meters; offset, if ",(0,i.kt)("strong",{parentName:"em"},"T1")," is set to ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(56874).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(19654).Z,width:"404",height:"343"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"D2")," - ",(0,i.kt)("em",{parentName:"p"},"Depth of extrusion for second end in meters; offset, if ",(0,i.kt)("strong",{parentName:"em"},"T2")," is set to ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(71152).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(23210).Z,width:"381",height:"343"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Dchk1")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," to allow drafting in the first direction, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to not")),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(2929).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(36298).Z,width:"381",height:"343"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Dchk2")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," to allow drafting in the second direction, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to not")),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(21802).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(56995).Z,width:"381",height:"343"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Ddir1")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," for first draft angle to be inward, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to be outward; valid only if ",(0,i.kt)("strong",{parentName:"em"},"Dchk1")," is true")),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(15281).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(55191).Z,width:"381",height:"343"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Ddir2")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," for second draft angle to be inward, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to be outward; valid only if ",(0,i.kt)("strong",{parentName:"em"},"Dchk2")," is true")),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(44943).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(76183).Z,width:"381",height:"343"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Dang1")," - ",(0,i.kt)("em",{parentName:"p"},"Draft angle for first end; valid only if ",(0,i.kt)("strong",{parentName:"em"},"Dchk1")," is true")),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(62658).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(70841).Z,width:"411",height:"380"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Dang2")," - ",(0,i.kt)("em",{parentName:"p"},"Draft angle for second end; valid only if ",(0,i.kt)("strong",{parentName:"em"},"Dchk2")," is true")),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(64843).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(35752).Z,width:"411",height:"380"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"OffsetReverse1")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," to offset the first end from another face or plane in a direction away from the sketch, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to offset in a direction toward the sketch; valid only if ",(0,i.kt)("strong",{parentName:"em"},"T1")," is set to ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(45165).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(39951).Z,width:"411",height:"380"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"OffsetReverse2")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," to offset the second end from another face or plane in a direction away from the sketch, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to offset in a direction toward the sketch; valid only if ",(0,i.kt)("strong",{parentName:"em"},"T2")," is set to ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(97429).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(20160).Z,width:"411",height:"380"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"TranslateSurface1")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," if the first end of the extrusion is a translation of the reference surface, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," if it has a true offset; valid only if ",(0,i.kt)("strong",{parentName:"em"},"T1")," is set to ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(9874).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(96059).Z,width:"411",height:"380"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"TranslateSurface2")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," if the second end of the extrusion is a translation of the reference surface, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," if it has a true offset; valid only if ",(0,i.kt)("strong",{parentName:"em"},"T2")," is set to ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(65430).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(89630).Z,width:"411",height:"380"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Merge")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," to merge the results in a multibody part, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to not")),(0,i.kt)("div",{parentName:"li",className:"admonition admonition-caution alert alert--warning"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"}))),"caution")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"This option visible when we ",(0,i.kt)("strong",{parentName:"p"},"Extrude")," from existing ",(0,i.kt)("strong",{parentName:"p"},"feature/body"),"."))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(58736).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(79471).Z,width:"411",height:"368"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"UseFeatScope")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," if the feature only affects selected bodies, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," if the feature affects all bodies."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"UseAutoSelect")," - ",(0,i.kt)("em",{parentName:"p"},"True to automatically select all bodies and have the feature affect those bodies, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to select the bodies that the feature affects."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"T0")," - ",(0,i.kt)("em",{parentName:"p"},"Start condition as defined in ",(0,i.kt)("inlineCode",{parentName:"em"},"swStartConditions_e"))),(0,i.kt)("p",{parentName:"li"},"Start Conditions has following enumeration values:"),(0,i.kt)("ul",{parentName:"li"},(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swStartOffset")," or ",(0,i.kt)("strong",{parentName:"p"},"3"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swStartSketchPlane")," or ",(0,i.kt)("strong",{parentName:"p"},"0"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swStartSurface")," or ",(0,i.kt)("strong",{parentName:"p"},"1"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("inlineCode",{parentName:"p"},"swStartVertex")," or ",(0,i.kt)("strong",{parentName:"p"},"2")))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(33193).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(96010).Z,width:"411",height:"368"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"StartOffset")," - ",(0,i.kt)("em",{parentName:"p"},"Distance from the sketch plane to start the extrude; valid only if ",(0,i.kt)("strong",{parentName:"em"},"T0")," is set to ",(0,i.kt)("inlineCode",{parentName:"em"},"swStartConditions_e.swStartOffset"))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(73163).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(78472).Z,width:"411",height:"368"})))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"FlipStartOffset")," - ",(0,i.kt)("em",{parentName:"p"},(0,i.kt)("inlineCode",{parentName:"em"},"True")," to flip the direction of the start offset, ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to not; valid only if ",(0,i.kt)("strong",{parentName:"em"},"T0")," is set to ",(0,i.kt)("inlineCode",{parentName:"em"},"swStartConditions_e.swStartOffset"))),(0,i.kt)("p",{parentName:"li"},(0,i.kt)("a",{target:"_blank",href:a(37242).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(68975).Z,width:"411",height:"368"}))))),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"Return Value")," : This ",(0,i.kt)("inlineCode",{parentName:"p"},"FeatureExtrusion3")," method retun ",(0,i.kt)("inlineCode",{parentName:"p"},"Feature")," object."),(0,i.kt)("p",null,"To see methods and properties related to ",(0,i.kt)("inlineCode",{parentName:"p"},"Feature")," object, please visit ",(0,i.kt)("strong",{parentName:"p"},(0,i.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeature_members.html"},"this page of Solidworks API Help")),"."),(0,i.kt)("p",null,"In our code, I have used following values:"),(0,i.kt)("ul",null,(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Sd")," -  ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"True")," for single ended."))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Flip")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to flip the side to cut"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Dir")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to flip the direction of extrusion"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"T1")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondBlind")," of Termination type for first end of the extrusion "))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"T2")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondBlind")," of Termination type for second end of the extrusion "))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"D1")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"2")," as "),"Depth of extrusion",(0,i.kt)("em",{parentName:"p"}," for first end in meters"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"D2")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"0")," as "),"Depth of extrusion",(0,i.kt)("em",{parentName:"p"}," for second end in meters"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Dchk1")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to allow drafting in the first direction"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Dchk2")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to allow drafting in the second direction"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Ddir1")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," for first draft angle to be inward"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Ddir2")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"True")," for second draft angle to be inward")),(0,i.kt)("div",{parentName:"li",className:"admonition admonition-caution alert alert--warning"},(0,i.kt)("div",{parentName:"div",className:"admonition-heading"},(0,i.kt)("h5",{parentName:"div"},(0,i.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,i.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"},(0,i.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"}))),"caution")),(0,i.kt)("div",{parentName:"div",className:"admonition-content"},(0,i.kt)("p",{parentName:"div"},"Since ",(0,i.kt)("strong",{parentName:"p"},"Dchk2")," is ",(0,i.kt)("inlineCode",{parentName:"p"},"False"),", setting the value to ",(0,i.kt)("inlineCode",{parentName:"p"},"True")," is invalid.")))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Dang1")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"0")," for first end's draft angle"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Dang2")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"0")," for second end's draft angle"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"OffsetReverse1")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to offset the first end from another face or plane in a direction away from the sketch"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"OffsetReverse2")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to offset the second end from another face or plane in a direction away from the sketch"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"TranslateSurface1")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to the first end of the extrusion is a translation of the reference surface"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"TranslateSurface2")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to the second end of the extrusion is a translation of the reference surface"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"Merge")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"True")," to merge the results in a multibody part"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"UseFeatScope")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," so that this feature affects to all bodies"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"UseAutoSelect")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"True")," to automatically select all bodies and have the feature affect those bodies"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"T0")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondBlind")," as Start condition"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"StartOffset")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"0")," for distance from the sketch plane to start the extrude"))),(0,i.kt)("li",{parentName:"ul"},(0,i.kt)("p",{parentName:"li"},(0,i.kt)("strong",{parentName:"p"},"FlipStartOffset")," - ",(0,i.kt)("em",{parentName:"p"},"I use ",(0,i.kt)("inlineCode",{parentName:"em"},"False")," to flip the direction of the start offset")))),(0,i.kt)("p",null,"After running macro we get extrude as shown in below image."),(0,i.kt)("p",null,(0,i.kt)("a",{target:"_blank",href:a(3841).Z},(0,i.kt)("img",{alt:"feature-extrude-final",src:a(87540).Z,width:"384",height:"187"}))),(0,i.kt)("hr",null),(0,i.kt)("p",null,(0,i.kt)("strong",{parentName:"p"},"This is it !!!")),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"I hope my efforts will helpful to someone!")),(0,i.kt)("p",null,"If you found anything to ",(0,i.kt)("strong",{parentName:"p"},"add or update"),", please let me know on my ",(0,i.kt)("em",{parentName:"p"},"e-mail"),"."),(0,i.kt)("p",null,"Hope this post helps you to ",(0,i.kt)("strong",{parentName:"p"},"create Extrude/Boss")," with Solidworks VBA Macros."),(0,i.kt)("p",null,"For more such tutorials on ",(0,i.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"Do let me know by you like this post or not!")),(0,i.kt)("p",null,(0,i.kt)("em",{parentName:"p"},"Till then, Happy learning!!!")))}c.isMDXComponent=!0},74753:function(e,t,a){a.d(t,{Z:function(){return i}});var n=a(94578),r=a(67294),i=function(e){function t(){return e.apply(this,arguments)||this}(0,n.Z)(t,e);var a=t.prototype;return a.componentDidMount=function(){var e;(e=document.createElement("script")).src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild),(window.adsbygoogle=window.adsbygoogle||[]).push({})},a.render=function(){return r.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})},t}(r.Component)},39827:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-1-db894e6a3b9d20c78ad020df1ea43404.svg"},44943:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-10-3042e60ded5e9e89ac9109efa8b18c6a.svg"},62658:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-11-cc28826fbd05a22465d6f42406daf797.svg"},64843:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-12-9d7b909a2e1f074dc416d7146927edc0.svg"},45165:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-13-e83b35a29cd02ff7edf0df23295deb6d.svg"},97429:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-14-9bee816ac6a38ba0908778a20f01e37f.svg"},9874:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-15-335a019b6b1eee7405e4d5ac4bc482c5.svg"},65430:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-16-faaaf77956964b6d5eef7f63bdacf6cb.svg"},58736:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-17-332f7c532faae4562756640cdf7e35e0.svg"},33193:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-18-f7bbec957133fbdb2afea906465bc596.svg"},73163:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-19-0d7d3f12d12de7f881e204daa53cdad3.svg"},5057:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-2-a6ed5a181845609a5d1dc449b6703793.svg"},37242:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-20-78800cec813512d2cfe99df0431b54e2.svg"},22572:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-3-e7e3801800cad746f250ce27a160fb57.svg"},59220:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-4-55c5e842ed348bfdbe818f2cb45f3fe3.svg"},56874:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-5-bb92d8f70eb9b545aa0ca700b7348308.svg"},71152:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-6-bd79d975f9bdb5aea0ea5c0e2a066b5f.svg"},2929:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-7-755a0e6d75a3a97ad8166417b454d795.svg"},21802:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-8-ffab0f5713a985b03ab53674c796f9f8.svg"},15281:function(e,t,a){t.Z=a.p+"assets/files/Extrude-parameter-9-83c425e3d954c4b5b89f7b750ffbe6f0.svg"},3841:function(e,t,a){t.Z=a.p+"assets/files/extrude-part-23c64e3ce95700ec5f4ef30a31dc41e0.svg"},77290:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-1-db894e6a3b9d20c78ad020df1ea43404.svg"},76183:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-10-3042e60ded5e9e89ac9109efa8b18c6a.svg"},70841:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-11-cc28826fbd05a22465d6f42406daf797.svg"},35752:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-12-9d7b909a2e1f074dc416d7146927edc0.svg"},39951:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-13-e83b35a29cd02ff7edf0df23295deb6d.svg"},20160:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-14-9bee816ac6a38ba0908778a20f01e37f.svg"},96059:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-15-335a019b6b1eee7405e4d5ac4bc482c5.svg"},89630:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-16-faaaf77956964b6d5eef7f63bdacf6cb.svg"},79471:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-17-332f7c532faae4562756640cdf7e35e0.svg"},96010:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-18-f7bbec957133fbdb2afea906465bc596.svg"},78472:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-19-0d7d3f12d12de7f881e204daa53cdad3.svg"},75465:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-2-a6ed5a181845609a5d1dc449b6703793.svg"},68975:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-20-78800cec813512d2cfe99df0431b54e2.svg"},47898:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-3-e7e3801800cad746f250ce27a160fb57.svg"},58681:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-4-55c5e842ed348bfdbe818f2cb45f3fe3.svg"},19654:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-5-bb92d8f70eb9b545aa0ca700b7348308.svg"},23210:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-6-bd79d975f9bdb5aea0ea5c0e2a066b5f.svg"},36298:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-7-755a0e6d75a3a97ad8166417b454d795.svg"},56995:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-8-ffab0f5713a985b03ab53674c796f9f8.svg"},55191:function(e,t,a){t.Z=a.p+"assets/images/Extrude-parameter-9-83c425e3d954c4b5b89f7b750ffbe6f0.svg"},87540:function(e,t,a){t.Z=a.p+"assets/images/extrude-part-23c64e3ce95700ec5f4ef30a31dc41e0.svg"}}]);