"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[9425],{3905:(e,t,a)=>{a.d(t,{Zo:()=>m,kt:()=>d});var n=a(67294);function r(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}function o(e,t){var a=Object.keys(e);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);t&&(n=n.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),a.push.apply(a,n)}return a}function i(e){for(var t=1;t<arguments.length;t++){var a=null!=arguments[t]?arguments[t]:{};t%2?o(Object(a),!0).forEach((function(t){r(e,t,a[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(a)):o(Object(a)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(a,t))}))}return e}function s(e,t){if(null==e)return{};var a,n,r=function(e,t){if(null==e)return{};var a,n,r={},o=Object.keys(e);for(n=0;n<o.length;n++)a=o[n],t.indexOf(a)>=0||(r[a]=e[a]);return r}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(n=0;n<o.length;n++)a=o[n],t.indexOf(a)>=0||Object.prototype.propertyIsEnumerable.call(e,a)&&(r[a]=e[a])}return r}var l=n.createContext({}),p=function(e){var t=n.useContext(l),a=t;return e&&(a="function"==typeof e?e(t):i(i({},t),e)),a},m=function(e){var t=p(e.components);return n.createElement(l.Provider,{value:t},e.children)},u={inlineCode:"code",wrapper:function(e){var t=e.children;return n.createElement(n.Fragment,{},t)}},k=n.forwardRef((function(e,t){var a=e.components,r=e.mdxType,o=e.originalType,l=e.parentName,m=s(e,["components","mdxType","originalType","parentName"]),k=p(a),d=r,c=k["".concat(l,".").concat(d)]||k[d]||u[d]||o;return a?n.createElement(c,i(i({ref:t},m),{},{components:a})):n.createElement(c,i({ref:t},m))}));function d(e,t){var a=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var o=a.length,i=new Array(o);i[0]=k;var s={};for(var l in t)hasOwnProperty.call(t,l)&&(s[l]=t[l]);s.originalType=e,s.mdxType="string"==typeof e?e:r,i[1]=s;for(var p=2;p<o;p++)i[p]=a[p];return n.createElement.apply(null,i)}return n.createElement.apply(null,a)}k.displayName="MDXCreateElement"},62354:(e,t,a)=>{a.r(t),a.d(t,{assets:()=>p,contentTitle:()=>s,default:()=>k,frontMatter:()=>i,metadata:()=>l,toc:()=>m});var n=a(87462),r=(a(67294),a(3905)),o=a(74753);const i={categories:"Solidworks-macro",title:"Solidworks Macro - Create Sweep Base",permalink:"/solidworks-macros/create-sweep-feature/",tags:["Solidworks Macro"],id:"feature-create-sweep-boss"},s=void 0,l={unversionedId:"feature-create-sweep-boss",id:"feature-create-sweep-boss",title:"Solidworks Macro - Create Sweep Base",description:"",source:"@site/docs/solidworks-macros/015.3-feature-create-sweep-boss.md",sourceDirName:".",slug:"/feature-create-sweep-boss",permalink:"/solidworks-macros/feature-create-sweep-boss",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Create Sweep Base",permalink:"/solidworks-macros/create-sweep-feature/",tags:["Solidworks Macro"],id:"feature-create-sweep-boss"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Create Revolved Boss/Base",permalink:"/solidworks-macros/feature-create-revolve-boss"},next:{title:"Solidworks Macro - Create Lofted Base/Boss",permalink:"/solidworks-macros/feature-create-lofted-boss"}},p={},m=[{value:"Objective",id:"objective",level:2},{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"Code Sample",id:"code-sample",level:2},{value:"Prerequisite",id:"prerequisite",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:2},{value:"Feature Definition Method CreateDefinition Parameters Details",id:"feature-definition-method-createdefinition-parameters-details",level:2},{value:"Feature Creation Method CreateFeature Parameters Details",id:"feature-creation-method-createfeature-parameters-details",level:2}],u={toc:m};function k(e){let{components:t,...i}=e;return(0,r.kt)("wrapper",(0,n.Z)({},u,i,{components:t,mdxType:"MDXLayout"}),(0,r.kt)("h2",{id:"objective"},"Objective"),(0,r.kt)(o.Z,{mdxType:"AdComponent"}),(0,r.kt)("p",null,"In this post, I tell you about ",(0,r.kt)("em",{parentName:"p"},"how to create Sweep Base through Solidworks VBA Macros")," in a sketch."),(0,r.kt)("p",null,"From ",(0,r.kt)("em",{parentName:"p"},"Solidworks 2018"),", creating Sweep feature method is changed."),(0,r.kt)("p",null,"It is now done through creating ",(0,r.kt)("em",{parentName:"p"},"Feature Definition")," and create feature from this ",(0,r.kt)("em",{parentName:"p"},"Feature Definition"),"."),(0,r.kt)("p",null,"This method is ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"most updated"))," method, so ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"use this method"))," if you want to create a new ",(0,r.kt)("strong",{parentName:"p"},"Sweep Base"),"."),(0,r.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,r.kt)("p",null,"Please see below video \ud83c\udfac on ",(0,r.kt)("strong",{parentName:"p"},"how to create Sweep Base")," from Solidworks VBA Macros."),(0,r.kt)("iframe",{src:"https://www.youtube.com/embed/SQv1Mq1m6to",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,r.kt)("p",null,"Please note that there are ",(0,r.kt)("strong",{parentName:"p"},"no explaination")," in the video. "),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,r.kt)("h2",{id:"code-sample"},"Code Sample"),(0,r.kt)("p",null,"Below is the ",(0,r.kt)("inlineCode",{parentName:"p"},"code")," sample for creating ",(0,r.kt)("em",{parentName:"p"},"Sweep Base"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Creating variable for Solidworks Sweep Feature\nDim swFeature As SldWorks.Feature\n' Creating variable for Solidworks Sweep Feature data\nDim swSweep As SldWorks.SweepFeatureData\n' Boolean Variable\nDim boolStatus As Boolean\n\n' Sweep Base program\nSub main()\n\n  ' Setting Solidworks variable to current application\n  Set swApp = Application.SldWorks\n  \n  ' Check if Solidworks is opened or not\n  If swApp Is Nothing Then\n      MsgBox (\"Solidworks is not opened\")\n      Exit Sub\n  End If\n  \n  ' Setting Solidworks document variable to opened part document\n  Set swDoc = swApp.ActiveDoc\n  \n  ' Check if Solidworks document is opened or not\n  If swDoc Is Nothing Then\n      MsgBox (\"Solidworks document is not opened. Please open a document.\")\n      Exit Sub\n  End If\n   \n  ' Select Sketch 1 as profile and Sketch 2 as path in opened part document\n  boolStatus = swDoc.Extension.SelectByID2(\"Sketch1\", \"SKETCH\", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\n  boolStatus = swDoc.Extension.SelectByID2(\"Sketch2\", \"SKETCH\", 0, 0, 0, True, 4, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Create feature definition\n  Set swSweep = swDoc.FeatureManager.CreateDefinition(swFmSweep)\n  \n  ' Create sweep feature\n  Set swFeature = swDoc.FeatureManager.CreateFeature(swSweep)\n\n  ' Check if sweep Feature creates or not\n  If swFeature Is Nothing Then\n      MsgBox (\"Failed to create Sweep Feature.\")\n      Exit Sub\n  End If\n\n  ' Zoom to fit\n  swDoc.ViewZoomtofit2\n    \nEnd Sub\n")),(0,r.kt)(o.Z,{mdxType:"AdComponent"}),(0,r.kt)("h2",{id:"prerequisite"},"Prerequisite"),(0,r.kt)("p",null,"In this article there are some ",(0,r.kt)("em",{parentName:"p"},"prerequisite"),"."),(0,r.kt)("p",null,"We are ",(0,r.kt)("strong",{parentName:"p"},"not")," creating sketches from code but we use ",(0,r.kt)("strong",{parentName:"p"},"existing sketch")," to ",(0,r.kt)("em",{parentName:"p"},"create Sweep Base")," feature as shown in below picture."),(0,r.kt)("p",null,(0,r.kt)("a",{target:"_blank",href:a(70577).Z},(0,r.kt)("img",{alt:"sketches-to-use-for-sweep-feature",src:a(46644).Z,width:"1016",height:"533"}))),(0,r.kt)("p",null,"As shown in above image, there are 2 sketch in our part."),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"Sketch1")," : This is our ",(0,r.kt)("strong",{parentName:"p"},"profile")," for Sweep feture.")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"Sketch2")," : This is our ",(0,r.kt)("strong",{parentName:"p"},"path")," for Sweep feture."))),(0,r.kt)("p",null,"If you want to create these 2 sketch programatically then please refer to below articles."),(0,r.kt)("p",null,"For Circle \ud83d\ude80 read ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-circle"},"Solidworks Macros - Create Circle"))," article."),(0,r.kt)("p",null,"For Centerpoint Arc \ud83d\ude80 read ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-centerpoint-arc"},"Solidworks Macros - Create Centerpoint Arc"))," article."),(0,r.kt)("p",null,"Also, we will apply checks in this article, so that code we write should be error free most of the time."),(0,r.kt)("h2",{id:"understanding-the-code"},"Understanding the Code"),(0,r.kt)("p",null,"Now let us walk through ",(0,r.kt)("strong",{parentName:"p"},"each line")," in the above code, and ",(0,r.kt)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),(0,r.kt)("p",null,"I also give some link so that you can go through them if there are anything I explained in previous posts."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,r.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,r.kt)("admonition",{type:"tip"},(0,r.kt)("p",{parentName:"admonition"},"For more information please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,r.kt)("p",null,"In this line, we create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,r.kt)("p",null,"In this line, we create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Feature\nDim swFeature As SldWorks.Feature\n")),(0,r.kt)("p",null,"In this line, we Create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swFeature")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swFeature")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.Feature"),"."),(0,r.kt)("p",null,"We create variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swFeature")," for ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Feature"),"."),(0,r.kt)("p",null,"To see methods and properties related to ",(0,r.kt)("inlineCode",{parentName:"p"},"Feature")," object, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeature_members.html"},"this page of Solidworks API Help"))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Sweep Feature data\nDim swSweep As SldWorks.SweepFeatureData\n")),(0,r.kt)("p",null,"In this line, we Create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swSweep")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swSweep")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.SweepFeatureData"),"."),(0,r.kt)("p",null,"We create ",(0,r.kt)("inlineCode",{parentName:"p"},"swSweep")," variable for Solidworks Sweep feature data before we create Sweep feature using ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateFeature")," method from Solidworks Feature Manager."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,r.kt)("p",null,"In this line, we create a variable named ",(0,r.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,r.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,r.kt)("p",null,"These all are our global variables."),(0,r.kt)("p",null,"As you can see in code sample, they are ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,r.kt)("p",null,"So basically I group all the ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,r.kt)("p",null,"I have also place ",(0,r.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",(0,r.kt)("em",{parentName:"p"},"need")," this variable frequently."),(0,r.kt)("p",null,"Thus, I have started placing it here."),(0,r.kt)("p",null,"Next is our ",(0,r.kt)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",(0,r.kt)("inlineCode",{parentName:"p"},"main"),". "),(0,r.kt)("p",null,"This procedure hold all the ",(0,r.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,r.kt)("p",null,"In this line, we set the value of our Solidworks variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Solidworks is opened or not\nIf swApp Is Nothing Then\n    MsgBox ("Solidworks is not opened")\n    Exit Sub\nEnd If\n')),(0,r.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if Solidworks application variable is ",(0,r.kt)("em",{parentName:"p"},"successfully assigned")," to current Solidworks application."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks document variable to opened part document\nSet swDoc = swApp.ActiveDoc\n")),(0,r.kt)("p",null,"In above line of code, we set Solidwors document ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to currently open part document."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Solidworks document is opened or not\nIf swDoc Is Nothing Then\n    MsgBox ("Solidworks document is not opened. Please open a document.")\n    Exit Sub\nEnd If\n')),(0,r.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if Solidworks document ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," is opened."),(0,r.kt)("p",null,"If Solidworks document is not opened then code execute inside the code and inform the user by a \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,r.kt)("p",null,"After showing message our program ",(0,r.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Sketch 1 as profile and Sketch 2 as path in opened part document\nboolStatus = swDoc.Extension.SelectByID2("Sketch1", "SKETCH", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\nboolStatus = swDoc.Extension.SelectByID2("Sketch2", "SKETCH", 0, 0, 0, True, 4, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,r.kt)("p",null,"In above line, we select the ",(0,r.kt)("em",{parentName:"p"},"Sketch1")," and ",(0,r.kt)("em",{parentName:"p"},"Sketch2")," by using ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,r.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,r.kt)("admonition",{type:"tip"},(0,r.kt)("p",{parentName:"admonition"},"For more information about selection method please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post.")),(0,r.kt)("p",null,"\u2757 Please note that we need to define ",(0,r.kt)("em",{parentName:"p"},"profile")," and ",(0,r.kt)("em",{parentName:"p"},"path")," for ",(0,r.kt)("em",{parentName:"p"},"Sweep feature"),", hence while selecting sketches we need to define which sketch is profile and path as describe below."),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Profile")),(0,r.kt)("ul",{parentName:"li"},(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"If a ",(0,r.kt)("em",{parentName:"p"},"sketch profile"),", use ",(0,r.kt)("inlineCode",{parentName:"p"},"Mark = 1")," to select a ",(0,r.kt)("em",{parentName:"p"},"face, edge, or curve"),".\nFor a ",(0,r.kt)("em",{parentName:"p"},"swept-boss")," feature, the sketch profile must be ",(0,r.kt)("strong",{parentName:"p"},"closed")," \u2757. For a ",(0,r.kt)("em",{parentName:"p"},"swept-surface")," feature, the sketch profile is ",(0,r.kt)("strong",{parentName:"p"},"open or closed")," \u2757.")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"If a ",(0,r.kt)("em",{parentName:"p"},"circular profile"),", use ",(0,r.kt)("inlineCode",{parentName:"p"},"Mark = 4")," to select a ",(0,r.kt)("em",{parentName:"p"},"sketch line, edge or curve"),". The circular profile is ",(0,r.kt)("strong",{parentName:"p"},"open or closed")," \u2757.")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"If a ",(0,r.kt)("em",{parentName:"p"},"solid profile"),", use ",(0,r.kt)("inlineCode",{parentName:"p"},"Mark = 1")," to select the ",(0,r.kt)("em",{parentName:"p"},"tool body")," to use to make the cut and use ",(0,r.kt)("inlineCode",{parentName:"p"},"Mark = 2048")," to select the ",(0,r.kt)("em",{parentName:"p"},"solid body")," to ",(0,r.kt)("strong",{parentName:"p"},"cut")," \u2757. Solid profiles are used only in ",(0,r.kt)("inlineCode",{parentName:"p"},"swept-cut")," features.")))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Sweep path")," using ",(0,r.kt)("inlineCode",{parentName:"p"},"Mark = 4")))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create Sweep feature definition\nSet swSweep = swDoc.FeatureManager.CreateDefinition(swFmSweep)\n")),(0,r.kt)("p",null,"In above line of code we set the value of variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swSweep")," by ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateDefinition")," method."),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"CreateDefinition")," method is part of ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureManager")," object."),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureManager")," is again part of ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable i.e. ",(0,r.kt)("inlineCode",{parentName:"p"},"ModelDoc2")," object."),(0,r.kt)(o.Z,{mdxType:"AdComponent"}),(0,r.kt)("h2",{id:"feature-definition-method-createdefinition-parameters-details"},"Feature Definition Method CreateDefinition Parameters Details"),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateDefinition")," method takes following parameters as explained:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Type")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"Feature name ID")," as defined in ",(0,r.kt)("inlineCode",{parentName:"em"},"swFeatureNameID_e")),"."),(0,r.kt)("ul",{parentName:"li"},(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmBoundingBox")," ",(0,r.kt)("em",{parentName:"li"},"(bounding box)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmCirPattern")," ",(0,r.kt)("em",{parentName:"li"},"(circular pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmCurvePattern")," ",(0,r.kt)("em",{parentName:"li"},"(curve-driven pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmDerivedLPattern")," ",(0,r.kt)("em",{parentName:"li"},"(derived-driven pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmDimPattern")," ",(0,r.kt)("em",{parentName:"li"},"(variable/dimension pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmFillPattern")," ",(0,r.kt)("em",{parentName:"li"},"(fill pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmGroundPlane")," ",(0,r.kt)("em",{parentName:"li"},"(ground plane)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmLibraryFeature")," ",(0,r.kt)("em",{parentName:"li"},"(library)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmLocalChainPattern")," ",(0,r.kt)("em",{parentName:"li"},"(chain component pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmLocalCirPattern")," ",(0,r.kt)("em",{parentName:"li"},"(circular component pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmLocalCurvePattern")," ",(0,r.kt)("em",{parentName:"li"},"(curve-driven component pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmLocalLPattern")," ",(0,r.kt)("em",{parentName:"li"},"(linear component pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmLocalSketchPattern")," ",(0,r.kt)("em",{parentName:"li"},"(sketch-driven component pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmLPattern")," ",(0,r.kt)("em",{parentName:"li"},"(linear pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmNormalCut")," ",(0,r.kt)("em",{parentName:"li"},"(sheet metal normal cut)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmRefCurve")," ",(0,r.kt)("em",{parentName:"li"},"(projection curve)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmRefSurface")," ",(0,r.kt)("em",{parentName:"li"},"(surface sweep)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmSketchPattern")," ",(0,r.kt)("em",{parentName:"li"},"(sketch-driven pattern)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmSweep")," ",(0,r.kt)("em",{parentName:"li"},"(boss sweep)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmSweepCut")," ",(0,r.kt)("em",{parentName:"li"},"(cut sweep)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmSweepThread")," ",(0,r.kt)("em",{parentName:"li"},"(sweep thread)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmTabAndSlot")," ",(0,r.kt)("em",{parentName:"li"},"(tab and slot)")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("inlineCode",{parentName:"li"},"swFmTablePattern")," ",(0,r.kt)("em",{parentName:"li"},"(table pattern)"))))),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Return Value")," : This ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateDefinition")," method retun ",(0,r.kt)("strong",{parentName:"p"},"feature or pattern-specific")," feature data object."),(0,r.kt)("p",null,"To see methods and properties related to ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureManager")," object, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeatureManager_members.html"},"this page of Solidworks API Help")),"."),(0,r.kt)("p",null,"In our code, I have used following values:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"Type")," - ",(0,r.kt)("em",{parentName:"li"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"swFmSweep")," as ",(0,r.kt)("inlineCode",{parentName:"em"},"Feature name ID")),".")),(0,r.kt)("p",null,"If you want to know more information about Sweep Feature data then please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISweepFeatureData_members.html"},"this page of Solidworks API Help")),"."),(0,r.kt)("p",null,"This page will give you information about various properties and methods of ",(0,r.kt)("inlineCode",{parentName:"p"},"ISweepFeatureData")," Interface."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create sweep feature\nSet swFeature = swDoc.FeatureManager.CreateFeature(swSweep)\n")),(0,r.kt)("p",null,"In above line of code we set the value of variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swFeature")," by ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateFeature")," method."),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"CreateFeature")," method is part of ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureManager")," object."),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureManager")," is again part of ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable i.e. ",(0,r.kt)("inlineCode",{parentName:"p"},"ModelDoc2")," object."),(0,r.kt)("h2",{id:"feature-creation-method-createfeature-parameters-details"},"Feature Creation Method CreateFeature Parameters Details"),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateFeature")," method takes following parameters as explained:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"FeatureData")," - ",(0,r.kt)("em",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"em"},"Feature or pattern-specific")," feature data object"),".")),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Return Value")," : This ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateFeature")," method retun ",(0,r.kt)("strong",{parentName:"p"},"feature")," data object."),(0,r.kt)("p",null,"To see methods and properties related to ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureManager")," object, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeatureManager_members.html"},"this page of Solidworks API Help")),"."),(0,r.kt)("p",null,"In our code, I have used following values:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"FeatureData")," - ",(0,r.kt)("em",{parentName:"li"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"swFmSweep")," as feature data object which we defined prevously"),".")),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Sweep Feature creates or not\nIf swFeature Is Nothing Then\n    MsgBox ("Failed to create Sweep Feature.")\n    Exit Sub\nEnd If\n')),(0,r.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if we able to create Revolve Feature or not."),(0,r.kt)("p",null,"If we failed to select then inform the user by a \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,r.kt)("p",null,"After showing error message our program ",(0,r.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit\nswDoc.ViewZoomtofit2\n")),(0,r.kt)("p",null,"In above line of code, ",(0,r.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit2")," property to ",(0,r.kt)("em",{parentName:"p"},"Zoom to fit")," current view."),(0,r.kt)("p",null,"Now we run the macro and after running macro we get extrude as shown in below image."),(0,r.kt)("p",null,(0,r.kt)("a",{target:"_blank",href:a(8231).Z},(0,r.kt)("img",{alt:"sweep-feature-final-result",src:a(31231).Z,width:"1111",height:"530"}))),(0,r.kt)("hr",null),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"This is it !!!")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"I hope my efforts will helpful to someone!")),(0,r.kt)("p",null,"If you found anything to ",(0,r.kt)("strong",{parentName:"p"},"add or update"),", please let me know on my ",(0,r.kt)("em",{parentName:"p"},"e-mail"),"."),(0,r.kt)("p",null,"Hope this post helps you to ",(0,r.kt)("strong",{parentName:"p"},"create Sweep Base")," with Solidworks VBA Macros."),(0,r.kt)("p",null,"For more such tutorials on ",(0,r.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Do let me know by you like this post or not!")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Till then, Happy learning!!!")))}k.isMDXComponent=!0},74753:(e,t,a)=>{a.d(t,{Z:()=>r});var n=a(67294);class r extends n.Component{componentDidMount(){(()=>{const e=document.createElement("script");e.src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild)})(),(window.adsbygoogle=window.adsbygoogle||[]).push({})}render(){return n.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})}}},70577:(e,t,a)=>{a.d(t,{Z:()=>n});const n=a.p+"assets/files/sketches-to-use-for-sweep-feature-652f91a72f77aef77921cf81bcf16b67.png"},8231:(e,t,a)=>{a.d(t,{Z:()=>n});const n=a.p+"assets/files/sweep-feature-final-result-0b8adc1f2cab6868bce898252bbfb223.png"},46644:(e,t,a)=>{a.d(t,{Z:()=>n});const n=a.p+"assets/images/sketches-to-use-for-sweep-feature-652f91a72f77aef77921cf81bcf16b67.png"},31231:(e,t,a)=>{a.d(t,{Z:()=>n});const n=a.p+"assets/images/sweep-feature-final-result-0b8adc1f2cab6868bce898252bbfb223.png"}}]);