"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[3477],{3905:(e,t,n)=>{n.d(t,{Zo:()=>m,kt:()=>d});var o=n(67294);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function a(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,o)}return n}function s(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?a(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):a(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function i(e,t){if(null==e)return{};var n,o,r=function(e,t){if(null==e)return{};var n,o,r={},a=Object.keys(e);for(o=0;o<a.length;o++)n=a[o],t.indexOf(n)>=0||(r[n]=e[n]);return r}(e,t);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);for(o=0;o<a.length;o++)n=a[o],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(r[n]=e[n])}return r}var l=o.createContext({}),p=function(e){var t=o.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):s(s({},t),e)),n},m=function(e){var t=p(e.components);return o.createElement(l.Provider,{value:t},e.children)},c={inlineCode:"code",wrapper:function(e){var t=e.children;return o.createElement(o.Fragment,{},t)}},u=o.forwardRef((function(e,t){var n=e.components,r=e.mdxType,a=e.originalType,l=e.parentName,m=i(e,["components","mdxType","originalType","parentName"]),u=p(n),d=r,k=u["".concat(l,".").concat(d)]||u[d]||c[d]||a;return n?o.createElement(k,s(s({ref:t},m),{},{components:n})):o.createElement(k,s({ref:t},m))}));function d(e,t){var n=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var a=n.length,s=new Array(a);s[0]=u;var i={};for(var l in t)hasOwnProperty.call(t,l)&&(i[l]=t[l]);i.originalType=e,i.mdxType="string"==typeof e?e:r,s[1]=i;for(var p=2;p<a;p++)s[p]=n[p];return o.createElement.apply(null,s)}return o.createElement.apply(null,n)}u.displayName="MDXCreateElement"},89829:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>p,contentTitle:()=>i,default:()=>u,frontMatter:()=>s,metadata:()=>l,toc:()=>m});var o=n(87462),r=(n(67294),n(3905)),a=n(74753);const s={categories:"Solidworks-macro",title:"Solidworks Macro - Convert to Construction Sketch",permalink:"/solidworks-macros/convert-to-construction-sketch-segment/",tags:["Solidworks Macro"],id:"convert-to-construction-sketch-segment"},i=void 0,l={unversionedId:"convert-to-construction-sketch-segment",id:"convert-to-construction-sketch-segment",title:"Solidworks Macro - Convert to Construction Sketch",description:"",source:"@site/docs/solidworks-macros/099.1-convert-to-construction-sketch-segment.md",sourceDirName:".",slug:"/convert-to-construction-sketch-segment",permalink:"/solidworks-macros/convert-to-construction-sketch-segment",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Convert to Construction Sketch",permalink:"/solidworks-macros/convert-to-construction-sketch-segment/",tags:["Solidworks Macro"],id:"convert-to-construction-sketch-segment"},sidebar:"tutorialSidebar",previous:{title:"Solidworks VBA Macro - UnSuppress Component",permalink:"/solidworks-macros/assembly-unsuppress-component"},next:{title:"Solidworks Macro - Split Open/Closed Sketch Entities",permalink:"/solidworks-macros/split-sketch-segments"}},p={},m=[{value:"Code Sample",id:"code-sample",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:2}],c={toc:m};function u(e){let{components:t,...s}=e;return(0,r.kt)("wrapper",(0,o.Z)({},c,s,{components:t,mdxType:"MDXLayout"}),(0,r.kt)(a.Z,{mdxType:"AdComponent"}),(0,r.kt)("p",null,"In this post, I tell you about ",(0,r.kt)("strong",{parentName:"p"},"Convert to Construction Sketch")," in a Sketch."),(0,r.kt)("p",null,"In this post, I explain about ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateConstructionGeometry")," method from ",(0,r.kt)("strong",{parentName:"p"},"Solidworks"),"'s ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchManager")," object."),(0,r.kt)("p",null,"This method is ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"most updated"))," method, I found in ",(0,r.kt)("em",{parentName:"p"},"Solidworks API Help"),"."),(0,r.kt)("p",null,"This post will utilize the methods explained in earlier posts, hence knowledge to those is required but it is not mandatory."),(0,r.kt)("p",null,"An absolute beginner can follow what is written here."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"code-sample"},"Code Sample"),(0,r.kt)("p",null,"Below is the ",(0,r.kt)("inlineCode",{parentName:"p"},"code")," sample to ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"Convert Sketch Segment to Construction Sketch")),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Set Solidworks document to active part document\n  Set swDoc = swApp.ActiveDoc\n  \n  ' Select Circle\n  BoolStatus = swDoc.Extension.SelectByID2(\"Arc1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Convert to construction circle\n  swDoc.SketchManager.CreateConstructionGeometry\n  \n  ' De-select the Sketch Segment after Convert to construction\n  swDoc.ClearSelection2 True\n\n  ' Show Front View\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n\nEnd Sub\n")),(0,r.kt)("hr",null),(0,r.kt)(a.Z,{mdxType:"AdComponent"}),(0,r.kt)("h2",{id:"understanding-the-code"},"Understanding the Code"),(0,r.kt)("p",null,"Now let us walk through ",(0,r.kt)("strong",{parentName:"p"},"each line")," in the above code, and ",(0,r.kt)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),(0,r.kt)("p",null,"I also give some link so that you can go through them if there are anything I explained in previous posts."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,r.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,r.kt)("admonition",{type:"tip"},(0,r.kt)("p",{parentName:"admonition"},"For more information please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,r.kt)("p",null,"In this line, we create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,r.kt)("p",null,"In this line, we create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,r.kt)("p",null,"In this line, we create a variable named ",(0,r.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,r.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,r.kt)("p",null,"These all are our global variables."),(0,r.kt)("p",null,"As you can see in code sample, they are ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,r.kt)("p",null,"So basically I group all the ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,r.kt)("p",null,"I have also place ",(0,r.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",(0,r.kt)("em",{parentName:"p"},"need")," this variable frequently."),(0,r.kt)("p",null,"Thus, I have started placing it here."),(0,r.kt)("p",null,"Next is our ",(0,r.kt)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",(0,r.kt)("inlineCode",{parentName:"p"},"main"),". "),(0,r.kt)("p",null,"This procedure hold all the ",(0,r.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,r.kt)("p",null,"In this line, we set the value of our Solidworks variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks document to active part document\nSet swDoc = swApp.ActiveDoc\n")),(0,r.kt)("p",null,"In this line, we set the value of our Solidworks variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," to currently opened part document as shown below in our post."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Circle we want to Pattern\nBoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,r.kt)("p",null,"In above line of code, we select the Circle i.e. ",(0,r.kt)("strong",{parentName:"p"},"Arc 1")," and add it to selection list."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Convert to construction circle\nswDoc.SketchManager.CreateConstructionGeometry\n")),(0,r.kt)("p",null,"In above line, we convert the selected Solidworks Sketch Segment i.e. our circle ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateConstructionGeometry")," method from ",(0,r.kt)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,r.kt)("admonition",{type:"info"},(0,r.kt)("p",{parentName:"admonition"},"Please note that here we did not create another variable for Sketch Manger like I have done previously.")),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateConstructionGeometry")," method takes ",(0,r.kt)("strong",{parentName:"p"},"NO")," parameter and ",(0,r.kt)("strong",{parentName:"p"},"did not")," return any value."),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Before ",(0,r.kt)("em",{parentName:"strong"},"Convert")," Circle")),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"before-construction-sketch-segment",src:n(69943).Z,width:"1125",height:"552"})),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"After ",(0,r.kt)("em",{parentName:"strong"},"Convert")," Circle")),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"after-construction-sketch-segment",src:n(93235).Z,width:"1125",height:"557"})),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Sketch after creation\nswDoc.ClearSelection2 True\n")),(0,r.kt)("p",null,"In the above line of code, we deselect the ",(0,r.kt)("strong",{parentName:"p"},"Sketch")," after the ",(0,r.kt)("em",{parentName:"p"},"Circular Sketch Pattern")," operation."),(0,r.kt)("p",null,"For de-selecting, we use ",(0,r.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Show Front View\nswDoc.ShowNamedView2 "", swStandardViews_e.swFrontView\n')),(0,r.kt)("p",null,"In the above line of code, we update the ",(0,r.kt)("em",{parentName:"p"},"view orientation")," to ",(0,r.kt)("strong",{parentName:"p"},"Front View"),"."),(0,r.kt)("p",null,"In my machine, after inserting a sketch view orientation does not changed."),(0,r.kt)("p",null,"Because of this I have to update the view to ",(0,r.kt)("strong",{parentName:"p"},"Front view"),"."),(0,r.kt)("p",null,"For showing ",(0,r.kt)("strong",{parentName:"p"},"Front View")," we used ",(0,r.kt)("inlineCode",{parentName:"p"},"ShowNamedView2")," method from our Solidworks document name ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,r.kt)("p",null,"This method takes 2 parameter described as follows:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"VName")," : Name of the view to display or an empty string to use ViewId instead")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"ViewId")," : ID of the view to display as defined by ",(0,r.kt)("inlineCode",{parentName:"p"},"swStandardViews_e")," or -1 to use the ",(0,r.kt)("strong",{parentName:"p"},"VName")," argument instead."))),(0,r.kt)("admonition",{type:"info"},(0,r.kt)("p",{parentName:"admonition"},"If you specify both ",(0,r.kt)("strong",{parentName:"p"},"VName")," and ",(0,r.kt)("strong",{parentName:"p"},"ViewId"),", then ",(0,r.kt)("strong",{parentName:"p"},"ViewId")," takes precedence if the two arguments do not resolve to the same view.")),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"swStandardViews_e")," has following Standard View Types:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swBackView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swBottomView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swDimetricView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swFrontView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swIsometricView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swLeftView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swRightView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swTopView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swExtendetricView")))),(0,r.kt)("p",null,"In our code, we did not use ",(0,r.kt)("strong",{parentName:"p"},"VName")," instead I used ",(0,r.kt)("em",{parentName:"p"},"empty string")," in form of ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},'""'))," symbol."),(0,r.kt)("p",null,"I used ",(0,r.kt)("strong",{parentName:"p"},"ViewId")," value to specify view and used ",(0,r.kt)("inlineCode",{parentName:"p"},"swStandardViews_e.swFrontView")," value to use ",(0,r.kt)("em",{parentName:"p"},"Standard Front View"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),(0,r.kt)("p",null,"In this last line we use ",(0,r.kt)("em",{parentName:"p"},"zoom to fit")," command."),(0,r.kt)("p",null,"For Zoom to fit, we use ",(0,r.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,r.kt)("hr",null),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"This is it !!!")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"I hope my efforts will helpful to someone!")),(0,r.kt)("p",null,"If you found anything to ",(0,r.kt)("strong",{parentName:"p"},"add or update"),", please let me know on my ",(0,r.kt)("em",{parentName:"p"},"e-mail"),"."),(0,r.kt)("p",null,"Hope this post helps you to ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"Convert to Construction Sketch"))," with Solidworks VBA Macros."),(0,r.kt)("p",null,"For more such tutorials on ",(0,r.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Do let me know by you like this post or not!")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Till then, Happy learning!!!")))}u.isMDXComponent=!0},74753:(e,t,n)=>{n.d(t,{Z:()=>r});var o=n(67294);class r extends o.Component{componentDidMount(){(()=>{const e=document.createElement("script");e.src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild)})(),(window.adsbygoogle=window.adsbygoogle||[]).push({})}render(){return o.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})}}},93235:(e,t,n)=>{n.d(t,{Z:()=>o});const o=n.p+"assets/images/after-construction-sketch-segment-ae59e189ef53404c94bd8e0a6fcb8632.png"},69943:(e,t,n)=>{n.d(t,{Z:()=>o});const o=n.p+"assets/images/before-construction-sketch-segment-67918854b753621676e94fc37660e659.png"}}]);