"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[1570],{3905:function(e,t,n){n.d(t,{Zo:function(){return m},kt:function(){return k}});var a=n(67294);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function s(e,t){if(null==e)return{};var n,a,r=function(e,t){if(null==e)return{};var n,a,r={},o=Object.keys(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||(r[n]=e[n]);return r}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(r[n]=e[n])}return r}var l=a.createContext({}),p=function(e){var t=a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},m=function(e){var t=p(e.components);return a.createElement(l.Provider,{value:t},e.children)},d={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},u=a.forwardRef((function(e,t){var n=e.components,r=e.mdxType,o=e.originalType,l=e.parentName,m=s(e,["components","mdxType","originalType","parentName"]),u=p(n),k=r,c=u["".concat(l,".").concat(k)]||u[k]||d[k]||o;return n?a.createElement(c,i(i({ref:t},m),{},{components:n})):a.createElement(c,i({ref:t},m))}));function k(e,t){var n=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var o=n.length,i=new Array(o);i[0]=u;var s={};for(var l in t)hasOwnProperty.call(t,l)&&(s[l]=t[l]);s.originalType=e,s.mdxType="string"==typeof e?e:r,i[1]=s;for(var p=2;p<o;p++)i[p]=n[p];return a.createElement.apply(null,i)}return a.createElement.apply(null,n)}u.displayName="MDXCreateElement"},53761:function(e,t,n){n.r(t),n.d(t,{assets:function(){return d},contentTitle:function(){return p},default:function(){return c},frontMatter:function(){return l},metadata:function(){return m},toc:function(){return u}});var a=n(87462),r=n(63366),o=(n(67294),n(3905)),i=n(74753),s=["components"],l={categories:"Solidworks-macro",title:"Solidworks Macro - Create Lofted Base/Boss",permalink:"/solidworks-macros/create-lofted-boss-feature/",tags:["Solidworks Macro"],id:"feature-create-lofted-boss"},p=void 0,m={unversionedId:"feature-create-lofted-boss",id:"feature-create-lofted-boss",title:"Solidworks Macro - Create Lofted Base/Boss",description:"",source:"@site/docs/solidworks-macros/015.4-feature-create-lofted-boss.md",sourceDirName:".",slug:"/feature-create-lofted-boss",permalink:"/solidworks-macros/feature-create-lofted-boss",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Create Lofted Base/Boss",permalink:"/solidworks-macros/create-lofted-boss-feature/",tags:["Solidworks Macro"],id:"feature-create-lofted-boss"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Create Sweep Base",permalink:"/solidworks-macros/feature-create-sweep-boss"},next:{title:"SOLIDWORKS Macro - Create Extrude Cut",permalink:"/solidworks-macros/feature-create-extrude-cut"}},d={},u=[{value:"Objective",id:"objective",level:2},{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"Code Sample",id:"code-sample",level:2},{value:"Prerequisite",id:"prerequisite",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:2},{value:"InsertProtrusionBlend2 Method Parameters Details",id:"insertprotrusionblend2-method-parameters-details",level:2}],k={toc:u};function c(e){var t=e.components,l=(0,r.Z)(e,s);return(0,o.kt)("wrapper",(0,a.Z)({},k,l,{components:t,mdxType:"MDXLayout"}),(0,o.kt)("h2",{id:"objective"},"Objective"),(0,o.kt)(i.Z,{mdxType:"AdComponent"}),(0,o.kt)("p",null,"In this post, I tell you about ",(0,o.kt)("em",{parentName:"p"},"how to create Lofted Base/Boss through Solidworks VBA Macros")," in a sketch."),(0,o.kt)("p",null,"This method is ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"most updated"))," method, so ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"use this method"))," if you want to create a new ",(0,o.kt)("strong",{parentName:"p"},"Lofted Base/Boss"),"."),(0,o.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,o.kt)("p",null,"Please see below video \ud83c\udfac on ",(0,o.kt)("strong",{parentName:"p"},"how to create Lofted Base/Boss")," from Solidworks VBA Macros."),(0,o.kt)("iframe",{src:"https://www.youtube.com/embed/wg6_7sjZBnE",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,o.kt)("p",null,"Please note that there are ",(0,o.kt)("strong",{parentName:"p"},"no explanation")," in the video. "),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Explanation")," of each line and why we write code this way is given in this post."),(0,o.kt)("h2",{id:"code-sample"},"Code Sample"),(0,o.kt)("p",null,"Below is the ",(0,o.kt)("inlineCode",{parentName:"p"},"code")," sample for creating ",(0,o.kt)("em",{parentName:"p"},"Lofted Base/Boss"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\' Creating variable for Solidworks Feature\nDim swFeature As SldWorks.Feature\n\' Boolean Variable\nDim boolStatus As Boolean\n\n\' Lofted Boss/Extrude program\nSub main()\n\n  \' Setting Solidworks variable to current application\n  Set swApp = Application.SldWorks\n  \n  \' Check if Solidworks is opened or not\n  If swApp Is Nothing Then\n    MsgBox ("Solidworks is not opened")\n    Exit Sub\n  End If\n  \n  \' Setting Solidworks document variable to opened part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Check if Solidworks document is opened or not\n  If swDoc Is Nothing Then\n    MsgBox ("Solidworks document is not opened. Please open a document.")\n    Exit Sub\n  End If\n  \n  \' Select Sketch 3 in opened part document\n  boolStatus = swDoc.Extension.SelectByID2("Sketch3", "SKETCH", 0, 0, 0, False, 1, Nothing, 0)\n  \n  \' Check if select Sketch 3 selected or not\n  If boolStatus = False Then\n    MsgBox ("Fail to select Sketch 3 as profile for Loft.")\n    Exit Sub\n  End If\n  \n  \' Select Sketch 2 in opened part document\n  boolStatus = swDoc.Extension.SelectByID2("Sketch2", "SKETCH", 0, 0, 0, True, 1, Nothing, 0)\n  \n  \' Check if select Sketch 2 selected or not\n  If boolStatus = False Then\n    MsgBox ("Fail to select Sketch 2 as profile for Loft.")\n    Exit Sub\n  End If\n  \n  \' Select Sketch 1 in opened part document\n  boolStatus = swDoc.Extension.SelectByID2("Sketch1", "SKETCH", 0, 0, 0, True, 1, Nothing, 0)\n  \n  \' Check if select Sketch 1 selected or not\n  If boolStatus = False Then\n    MsgBox ("Fail to select Sketch 1 as profile for Loft.")\n    Exit Sub\n  End If\n  \n  \' Select 3DSketch1 in opened part document\n  boolStatus = swDoc.Extension.SelectByID2("3DSketch1", "SKETCH", 0, 0, 0, True, 2, Nothing, 0)\n  \n  \' Check if select 3DSketch1 selected or not\n  If boolStatus = False Then\n    MsgBox ("Fail to select 3DSketch1 as Guide curve for Loft.")\n    Exit Sub\n  End If\n  \n  \' Create Lofted Boss feature\n  Set swFeature = swDoc.FeatureManager.InsertProtrusionBlend2(False, True, True, 0, 0, 0, 0, 0, True, True, False, 0, 0, 0, True, True, True, swGuideCurveInfluence_e.swGuideCurveInfluenceNextGlobal)\n\n  \' Check if Loft boss feature is created or not\n  If swFeature Is Nothing Then\n    MsgBox ("Failed to create Lofted boss.")\n    Exit Sub\n  End If\n    \nEnd Sub\n')),(0,o.kt)(i.Z,{mdxType:"AdComponent"}),(0,o.kt)("h2",{id:"prerequisite"},"Prerequisite"),(0,o.kt)("p",null,"In this article there are some ",(0,o.kt)("em",{parentName:"p"},"prerequisite"),"."),(0,o.kt)("p",null,"We are ",(0,o.kt)("strong",{parentName:"p"},"not")," creating sketches from code but we use ",(0,o.kt)("strong",{parentName:"p"},"existing sketch")," to ",(0,o.kt)("em",{parentName:"p"},"create Lofted Base/Boss")," feature as shown in below picture."),(0,o.kt)("p",null,(0,o.kt)("a",{target:"_blank",href:n(15392).Z},(0,o.kt)("img",{alt:"sketch-to-use-for-lofted-bose-feature",src:n(89685).Z,width:"1365",height:"549"}))),(0,o.kt)("p",null,"As shown in above image, there are 2 sketch in our part."),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("inlineCode",{parentName:"p"},"Sketch1")," : This is our ",(0,o.kt)("strong",{parentName:"p"},"profile 1")," for Lofted feature.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("inlineCode",{parentName:"p"},"Sketch2")," : This is our ",(0,o.kt)("strong",{parentName:"p"},"profile 2")," for Lofted feature.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("inlineCode",{parentName:"p"},"Sketch3")," : This is our ",(0,o.kt)("strong",{parentName:"p"},"profile 3")," for Lofted feature.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("inlineCode",{parentName:"p"},"3DSketch1")," : This is our ",(0,o.kt)("strong",{parentName:"p"},"Guide Curve")," for Lofted feature."))),(0,o.kt)("p",null,"If you want to create these 2 sketch programmatically then please refer to below articles."),(0,o.kt)("p",null,"For Circle \ud83d\ude80 read ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-circle"},"Solidworks Macros - Create Circle"))," article."),(0,o.kt)("p",null,"For CenterPoint Arc \ud83d\ude80 read ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-center-rectangle"},"Solidworks Macros - Create Center Rectangle"))," article."),(0,o.kt)("p",null,"Also, we will apply checks in this article, so that code we write should be error free most of the time."),(0,o.kt)("h2",{id:"understanding-the-code"},"Understanding the Code"),(0,o.kt)("p",null,"Now let us walk through ",(0,o.kt)("strong",{parentName:"p"},"each line")," in the above code, and ",(0,o.kt)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),(0,o.kt)("p",null,"I also give some link so that you can go through them if there are anything I explained in previous posts."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,o.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,o.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"For more information please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,o.kt)("p",null,"In this line, we create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,o.kt)("p",null,"In this line, we create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Feature\nDim swFeature As SldWorks.Feature\n")),(0,o.kt)("p",null,"In this line, we Create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swFeature")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swFeature")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.Feature"),"."),(0,o.kt)("p",null,"We create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swFeature")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Feature"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"Feature")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeature_members.html"},"this page of Solidworks API Help"))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim boolStatus As Boolean\n")),(0,o.kt)("p",null,"In this line, we create a variable named ",(0,o.kt)("inlineCode",{parentName:"p"},"boolStatus")," as ",(0,o.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,o.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"info")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"These all are our global variables."))),(0,o.kt)("p",null,"They are ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,o.kt)("p",null,"So basically I group all the ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,o.kt)("p",null,"I have also place ",(0,o.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because we use this variable frequently."),(0,o.kt)("p",null,"Thus, I have started placing it here."),(0,o.kt)("p",null,"Next is our ",(0,o.kt)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",(0,o.kt)("inlineCode",{parentName:"p"},"main"),". "),(0,o.kt)("p",null,"This procedure hold all the ",(0,o.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,o.kt)("p",null,"In this line, we set the value of our Solidworks variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Solidworks is opened or not\nIf swApp Is Nothing Then\n  MsgBox ("Solidworks is not opened")\n  Exit Sub\nEnd If\n')),(0,o.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if Solidworks application variable is ",(0,o.kt)("em",{parentName:"p"},"successfully assigned")," to current Solidworks application."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks document variable to opened part document\nSet swDoc = swApp.ActiveDoc\n")),(0,o.kt)("p",null,"In above line of code, we set Solidwors document ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to currently open part document."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Solidworks document is opened or not\nIf swDoc Is Nothing Then\n  MsgBox ("Solidworks document is not opened. Please open a document.")\n  Exit Sub\nEnd If\n')),(0,o.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if Solidworks document ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," is opened."),(0,o.kt)("p",null,"If Solidworks document is not opened then code execute inside the code and inform the user by a \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,o.kt)("p",null,"After showing message our program ",(0,o.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Sketch 3 as profile in opened part document\nboolStatus = swDoc.Extension.SelectByID2("Sketch3", "SKETCH", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line, we select the ",(0,o.kt)("em",{parentName:"p"},"Sketch3")," by using ",(0,o.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,o.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,o.kt)("p",null,"Please note that for selecting profile we need to ",(0,o.kt)("inlineCode",{parentName:"p"},"Mark")," the selected entity as ",(0,o.kt)("inlineCode",{parentName:"p"},"1"),"."),(0,o.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"For more information about selection method please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Sketch 3 selected or not\nIf boolStatus = False Then\n  MsgBox ("Fail to select Sketch 3 as profile for Loft.")\n  Exit Sub\nEnd If\n')),(0,o.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if Solidworks document ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," is opened."),(0,o.kt)("p",null,"If ",(0,o.kt)("em",{parentName:"p"},"Sketch 3 selected or not")," then code execute inside the code and inform the user by a \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,o.kt)("p",null,"After showing message our program ",(0,o.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Sketch 2 as profile in opened part document\nboolStatus = swDoc.Extension.SelectByID2("Sketch2", "SKETCH", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line, we select the ",(0,o.kt)("em",{parentName:"p"},"Sketch2")," by using ",(0,o.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,o.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,o.kt)("p",null,"Please note that for selecting profile we need to ",(0,o.kt)("inlineCode",{parentName:"p"},"Mark")," the selected entity as ",(0,o.kt)("inlineCode",{parentName:"p"},"1"),"."),(0,o.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"For more information about selection method please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Sketch 2 selected or not\nIf boolStatus = False Then\n  MsgBox ("Fail to select Sketch 2 as profile for Loft.")\n  Exit Sub\nEnd If\n')),(0,o.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if Solidworks document ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," is opened."),(0,o.kt)("p",null,"If ",(0,o.kt)("em",{parentName:"p"},"Sketch 2 selected or not")," then code execute inside the code and inform the user by a \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,o.kt)("p",null,"After showing message our program ",(0,o.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Sketch 1 as profile in opened part document\nboolStatus = swDoc.Extension.SelectByID2("Sketch1", "SKETCH", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line, we select the ",(0,o.kt)("em",{parentName:"p"},"Sketch1")," by using ",(0,o.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,o.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,o.kt)("p",null,"Please note that for selecting profile we need to ",(0,o.kt)("inlineCode",{parentName:"p"},"Mark")," the selected entity as ",(0,o.kt)("inlineCode",{parentName:"p"},"1"),"."),(0,o.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"For more information about selection method please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Sketch 1 selected or not\nIf boolStatus = False Then\n  MsgBox ("Fail to select Sketch 1 as profile for Loft.")\n  Exit Sub\nEnd If\n')),(0,o.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if Solidworks document ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," is opened."),(0,o.kt)("p",null,"If ",(0,o.kt)("em",{parentName:"p"},"Sketch 1 selected or not")," then code execute inside the code and inform the user by a \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,o.kt)("p",null,"After showing message our program ",(0,o.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select 3DSketch1 as Guide curve in opened part document\nboolStatus = swDoc.Extension.SelectByID2("3DSketch1", "SKETCH", 0, 0, 0, True, 2, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line, we select the ",(0,o.kt)("em",{parentName:"p"},"3DSketch1")," by using ",(0,o.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,o.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,o.kt)("p",null,"Please note that for selecting profile we need to ",(0,o.kt)("inlineCode",{parentName:"p"},"Mark")," the selected entity as ",(0,o.kt)("inlineCode",{parentName:"p"},"2"),"."),(0,o.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"For more information about selection method please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if 3DSketch1 selected or not\nIf boolStatus = False Then\n  MsgBox ("Fail to select 3DSketch1 as Guide curve for Loft.")\n  Exit Sub\nEnd If\n')),(0,o.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if Solidworks document ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," is opened."),(0,o.kt)("p",null,"If ",(0,o.kt)("em",{parentName:"p"},"3DSketch1 selected or not")," then code execute inside the code and inform the user by a \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,o.kt)("p",null,"After showing message our program ",(0,o.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create Lofted feature\nSet swFeature = swDoc.FeatureManager.InsertProtrusionBlend2(False, True, True, 0, 0, 0, 0, 0, True, True, False, 0, 0, 0, True, True, True, swGuideCurveInfluence_e.swGuideCurveInfluenceNextGlobal)\n")),(0,o.kt)("p",null,"In above line of code we set the value of variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swFeature")," by ",(0,o.kt)("inlineCode",{parentName:"p"},"InsertProtrusionBlend2")," method."),(0,o.kt)("p",null,(0,o.kt)("inlineCode",{parentName:"p"},"InsertProtrusionBlend2")," method is part of ",(0,o.kt)("inlineCode",{parentName:"p"},"FeatureManager")," object."),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"FeatureManager")," is again part of ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable i.e. ",(0,o.kt)("inlineCode",{parentName:"p"},"ModelDoc2")," object."),(0,o.kt)(i.Z,{mdxType:"AdComponent"}),(0,o.kt)("h2",{id:"insertprotrusionblend2-method-parameters-details"},"InsertProtrusionBlend2 Method Parameters Details"),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"InsertProtrusionBlend2")," method takes following parameters as explained:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Closed")," - ",(0,o.kt)("em",{parentName:"p"},(0,o.kt)("inlineCode",{parentName:"em"},"True")," closes the loft, ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," leaves the loft open. If ",(0,o.kt)("inlineCode",{parentName:"em"},"True")," and less than three profiles are selected, then any selected guide curves ",(0,o.kt)("strong",{parentName:"em"},"must")," be closed curves"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"KeepTangency")," - ",(0,o.kt)("em",{parentName:"p"},(0,o.kt)("inlineCode",{parentName:"em"},"True")," maintains the tangency as seen in the section curves, ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," does not"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"ForceNonRational")," - ",(0,o.kt)("em",{parentName:"p"},(0,o.kt)("inlineCode",{parentName:"em"},"True")," obtains smoother surfaces, ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," does not"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"TessToleranceFactor")," - ",(0,o.kt)("em",{parentName:"p"},"Factor that controls the number of intermediate sections used for loft with centerline; the default value is 1.0; the greater the value, the more intermediate sections are created."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"StartMatchingType")," - ",(0,o.kt)("em",{parentName:"p"},"Tangency type at the start profile as follows:")),(0,o.kt)("ul",{parentName:"li"},(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"0")," = ",(0,o.kt)("em",{parentName:"li"},"none.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"1")," = ",(0,o.kt)("em",{parentName:"li"},"tangent to the normal of the profile.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"2")," = ",(0,o.kt)("em",{parentName:"li"},"tangent to a selected vector.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"3")," = ",(0,o.kt)("em",{parentName:"li"},"tangency to all the adjacent faces sharing an edge with the start profile.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"4")," = ",(0,o.kt)("em",{parentName:"li"},"tangent to some of the selected faces sharing an edge with the start profile (not available).")))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"EndMatchingType")," - ",(0,o.kt)("em",{parentName:"p"},"Tangency type at the end profile as follows:")),(0,o.kt)("ul",{parentName:"li"},(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"0")," = ",(0,o.kt)("em",{parentName:"li"},"none.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"1")," = ",(0,o.kt)("em",{parentName:"li"},"tangent to the normal of the profile.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"2")," = ",(0,o.kt)("em",{parentName:"li"},"tangent to a selected vector.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"3")," = ",(0,o.kt)("em",{parentName:"li"},"tangency to all the adjacent faces sharing an edge with the start profile.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"4")," = ",(0,o.kt)("em",{parentName:"li"},"tangent to some of the selected faces sharing an edge with the start profile (not available).")))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"StartTangentLength")," - ",(0,o.kt)("em",{parentName:"p"},"Start tangent length."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"EndTangentLength")," - ",(0,o.kt)("em",{parentName:"p"},"End tangent length."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"StartTangentDir")," - ",(0,o.kt)("em",{parentName:"p"},(0,o.kt)("inlineCode",{parentName:"em"},"True")," is one direction, ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," is the opposite."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"EndTangentDir")," - ",(0,o.kt)("em",{parentName:"p"},(0,o.kt)("inlineCode",{parentName:"em"},"True")," is one direction, ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," is the opposite."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"IsThinBody")," - ",(0,o.kt)("em",{parentName:"p"},(0,o.kt)("inlineCode",{parentName:"em"},"True")," if this feature is a thin body, ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," if it is not."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Thickness1")," - ",(0,o.kt)("em",{parentName:"p"},"Thickness value for the first direction."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Thickness2")," - ",(0,o.kt)("em",{parentName:"p"},"Thickness value for the second direction."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"ThinType")," - ",(0,o.kt)("em",{parentName:"p"},"Thin wall type :")),(0,o.kt)("ul",{parentName:"li"},(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"0")," = ",(0,o.kt)("em",{parentName:"li"},"One direction")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"1")," = ",(0,o.kt)("em",{parentName:"li"},"One direction reverse")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"2")," = ",(0,o.kt)("em",{parentName:"li"},"Mid-plane")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"3")," = ",(0,o.kt)("em",{parentName:"li"},"Two direction")))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Merge")," - ",(0,o.kt)("em",{parentName:"p"},(0,o.kt)("inlineCode",{parentName:"em"},"True")," merges the results in a multibody part, ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," does not."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"UseFeatScope")," - ",(0,o.kt)("em",{parentName:"p"},(0,o.kt)("inlineCode",{parentName:"em"},"True")," if the feature only affects selected bodies, ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," if the feature affects all bodies."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"UseAutoSelect")," - ",(0,o.kt)("em",{parentName:"p"},(0,o.kt)("inlineCode",{parentName:"em"},"True")," to automatically select all bodies and have the feature affect those bodies, ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," to select the bodies the feature affects."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"GuideCurveInfluence")," - ",(0,o.kt)("em",{parentName:"p"},"Guide curves influence as defined in ",(0,o.kt)("inlineCode",{parentName:"em"},"swGuideCurveInfluence_e"))),(0,o.kt)("ul",{parentName:"li"},(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"0")," = ",(0,o.kt)("inlineCode",{parentName:"li"},"swGuideCurveInfluenceNextGuide")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"1")," = ",(0,o.kt)("inlineCode",{parentName:"li"},"swGuideCurveInfluenceNextSharp")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"2")," = ",(0,o.kt)("inlineCode",{parentName:"li"},"swGuideCurveInfluenceNextEdge")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("inlineCode",{parentName:"li"},"3")," = ",(0,o.kt)("inlineCode",{parentName:"li"},"swGuideCurveInfluenceNextGlobal"))))),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Return Value")," : This ",(0,o.kt)("inlineCode",{parentName:"p"},"InsertProtrusionBlend2")," method return ",(0,o.kt)("strong",{parentName:"p"},"feature")," data object."),(0,o.kt)("p",null,"In our code, I have used following values:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Closed")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," to leave the loft open"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"KeepTangency")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"True")," to maintains the tangency"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"ForceNonRational")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"True")," to obtains smoother surfaces"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"TessToleranceFactor")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"0")," number of intermediate sections used for loft with centerline"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"StartMatchingType")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"0")," at the start profile."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"EndMatchingType")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"0")," at the start profile."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"StartTangentLength")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"0")," at the start tangent length."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"EndTangentLength")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"0")," at the end tangent length."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"StartTangentDir")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"True")," in one direction"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"EndTangentDir")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"True")," in one direction"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"IsThinBody")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"False")," for this feature is a thin body"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Thickness1")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"0")," for the first direction"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Thickness2")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"0")," for the second direction"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"ThinType")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"0")," for Thin wall type"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Merge")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"True")," for merges the results in a multibody part"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"UseFeatScope")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"True")," for the feature only affects selected bodies"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"UseAutoSelect")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"True")," for automatically select all bodies and have the feature affect those bodies"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"GuideCurveInfluence")," - ",(0,o.kt)("em",{parentName:"p"},"I use ",(0,o.kt)("inlineCode",{parentName:"em"},"swGuideCurveInfluence_e.swGuideCurveInfluenceNextGlobal")," for Guide curves influence"),"."))),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"FeatureManager")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeatureManager_members.html"},"this page of Solidworks API Help")),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Lofted boss creates or not\nIf swFeature Is Nothing Then\n  MsgBox ("Failed to create Lofted boss.")\n  Exit Sub\nEnd If\n')),(0,o.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if we able to create ",(0,o.kt)("em",{parentName:"p"},"Lofted Boss/Base")," Feature or not."),(0,o.kt)("p",null,"If we failed to select then inform the user by a \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,o.kt)("p",null,"After showing error message our program ",(0,o.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,o.kt)("p",null,"Now we run the macro and after running macro we get extrude as shown in below image."),(0,o.kt)("p",null,(0,o.kt)("a",{target:"_blank",href:n(7885).Z},(0,o.kt)("img",{alt:"loft-boss-feature-final-result",src:n(81638).Z,width:"1365",height:"549"}))),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"This is it !!!")),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"I hope my efforts will helpful to someone!")),(0,o.kt)("p",null,"If you found anything to ",(0,o.kt)("strong",{parentName:"p"},"add or update"),", please let me know on my ",(0,o.kt)("em",{parentName:"p"},"e-mail"),"."),(0,o.kt)("p",null,"Hope this post helps you to ",(0,o.kt)("strong",{parentName:"p"},"create Lofted Base/Boss")," with Solidworks VBA Macros."),(0,o.kt)("p",null,"For more such tutorials on ",(0,o.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Do let me know by you like this post or not!")),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Till then, Happy learning!!!")))}c.isMDXComponent=!0},74753:function(e,t,n){n.d(t,{Z:function(){return o}});var a=n(94578),r=n(67294),o=function(e){function t(){return e.apply(this,arguments)||this}(0,a.Z)(t,e);var n=t.prototype;return n.componentDidMount=function(){var e;(e=document.createElement("script")).src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild),(window.adsbygoogle=window.adsbygoogle||[]).push({})},n.render=function(){return r.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})},t}(r.Component)},7885:function(e,t,n){t.Z=n.p+"assets/files/loft-boss-feature-final-result-b7371ebe812256151bba377ad3f5f00b.png"},15392:function(e,t,n){t.Z=n.p+"assets/files/sketch-to-use-for-lofted-bose-feature-521923ae6370251d7a937633e2abb1d8.png"},81638:function(e,t,n){t.Z=n.p+"assets/images/loft-boss-feature-final-result-b7371ebe812256151bba377ad3f5f00b.png"},89685:function(e,t,n){t.Z=n.p+"assets/images/sketch-to-use-for-lofted-bose-feature-521923ae6370251d7a937633e2abb1d8.png"}}]);