"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[4715],{3905:(e,t,o)=>{o.d(t,{Zo:()=>u,kt:()=>k});var n=o(67294);function r(e,t,o){return t in e?Object.defineProperty(e,t,{value:o,enumerable:!0,configurable:!0,writable:!0}):e[t]=o,e}function l(e,t){var o=Object.keys(e);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);t&&(n=n.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),o.push.apply(o,n)}return o}function a(e){for(var t=1;t<arguments.length;t++){var o=null!=arguments[t]?arguments[t]:{};t%2?l(Object(o),!0).forEach((function(t){r(e,t,o[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(o)):l(Object(o)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(o,t))}))}return e}function s(e,t){if(null==e)return{};var o,n,r=function(e,t){if(null==e)return{};var o,n,r={},l=Object.keys(e);for(n=0;n<l.length;n++)o=l[n],t.indexOf(o)>=0||(r[o]=e[o]);return r}(e,t);if(Object.getOwnPropertySymbols){var l=Object.getOwnPropertySymbols(e);for(n=0;n<l.length;n++)o=l[n],t.indexOf(o)>=0||Object.prototype.propertyIsEnumerable.call(e,o)&&(r[o]=e[o])}return r}var i=n.createContext({}),p=function(e){var t=n.useContext(i),o=t;return e&&(o="function"==typeof e?e(t):a(a({},t),e)),o},u=function(e){var t=p(e.components);return n.createElement(i.Provider,{value:t},e.children)},d={inlineCode:"code",wrapper:function(e){var t=e.children;return n.createElement(n.Fragment,{},t)}},c=n.forwardRef((function(e,t){var o=e.components,r=e.mdxType,l=e.originalType,i=e.parentName,u=s(e,["components","mdxType","originalType","parentName"]),c=p(o),k=r,m=c["".concat(i,".").concat(k)]||c[k]||d[k]||l;return o?n.createElement(m,a(a({ref:t},u),{},{components:o})):n.createElement(m,a({ref:t},u))}));function k(e,t){var o=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var l=o.length,a=new Array(l);a[0]=c;var s={};for(var i in t)hasOwnProperty.call(t,i)&&(s[i]=t[i]);s.originalType=e,s.mdxType="string"==typeof e?e:r,a[1]=s;for(var p=2;p<l;p++)a[p]=o[p];return n.createElement.apply(null,a)}return n.createElement.apply(null,o)}c.displayName="MDXCreateElement"},30612:(e,t,o)=>{o.r(t),o.d(t,{assets:()=>i,contentTitle:()=>a,default:()=>d,frontMatter:()=>l,metadata:()=>s,toc:()=>p});var n=o(87462),r=(o(67294),o(3905));const l={categories:"Solidworks-C++-API",title:"Open Solidworks Part Document",tags:["Solidworks C++ API"],permalink:"/solidworks-cpp/open-part-document/",id:"open-part-document"},a=void 0,s={unversionedId:"open-part-document",id:"open-part-document",title:"Open Solidworks Part Document",description:"In this post, I tell you about how to Open Solidworks Part Document using Solidworks C++ API from Visual Studio.",source:"@site/docs/solidworks-cpp/001.4-open-part-document.md",sourceDirName:".",slug:"/open-part-document",permalink:"/solidworks-cpp/open-part-document",draft:!1,tags:[{label:"Solidworks C++ API",permalink:"/solidworks-cpp/tags/solidworks-c-api"}],version:"current",frontMatter:{categories:"Solidworks-C++-API",title:"Open Solidworks Part Document",tags:["Solidworks C++ API"],permalink:"/solidworks-cpp/open-part-document/",id:"open-part-document"},sidebar:"tutorialSidebar",previous:{title:"Open Solidworks & Hello World",permalink:"/solidworks-cpp/open-solidworks"},next:{title:"Browse and Open Solidworks Document",permalink:"/solidworks-cpp/browse-and-open-document"}},i={},p=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"Create a New project",id:"create-a-new-project",level:2},{value:"Add Source file",id:"add-source-file",level:2},{value:"Add References to Solidworks Type Library files",id:"add-references-to-solidworks-type-library-files",level:2},{value:"Add Code to Source file",id:"add-code-to-source-file",level:2},{value:"Final Result",id:"final-result",level:2},{value:"Issues and Solutions",id:"issues-and-solutions",level:2}],u={toc:p};function d(e){let{components:t,...l}=e;return(0,r.kt)("wrapper",(0,n.Z)({},u,l,{components:t,mdxType:"MDXLayout"}),(0,r.kt)("p",null,"In this post, I tell you about ",(0,r.kt)("strong",{parentName:"p"},"how to Open Solidworks Part Document using Solidworks C++ API")," from Visual Studio."),(0,r.kt)("p",null,"I hope you have setup Visual Studio community version."),(0,r.kt)("p",null,"If not then please go to \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-cpp/cpp-prerequisite/"},"Solidworks C++ API - Prerequisite"))," post and watch the suggested videos before proceeding further."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,r.kt)("p",null,"Please see below video on ",(0,r.kt)("strong",{parentName:"p"},"how to Open Solidworks Part Document using Solidworks C++ API")," from Visual Studio."),(0,r.kt)("iframe",{src:"https://www.youtube.com/embed/DBESb0ZGnGc",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,r.kt)("p",null,"Please note that there are ",(0,r.kt)("strong",{parentName:"p"},"no explaination")," in the video. "),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"create-a-new-project"},"Create a New project"),(0,r.kt)("p",null,"Fist, we will create a new project in Visual Studio."),(0,r.kt)("p",null,"As shown in below image I have created a new project named ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenPartDocument")," in Visual Studio."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"new-project-window",src:o(70900).Z,width:"785",height:"448"})),(0,r.kt)("p",null,"If you want to know more detail for Creating a New Project in Visual Studio, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-cpp/open-solidworks#create-a-new-project"},"Create a New project"))," section of \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-cpp/open-solidworks"},"Solidworks C++ API - Open Solidworks & Hello World"))," post."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"add-source-file"},"Add Source file"),(0,r.kt)("p",null,"After creating a new project, we need to Add Source file to our project."),(0,r.kt)("p",null,'I have already explain each steps taken to create/add a "',(0,r.kt)("strong",{parentName:"p"},"Source.cpp"),'" into our project in \ud83d\ude80 ',(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-cpp/open-solidworks#add-source-file"},"Add Source file"))," section of \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-cpp/open-solidworks"},"Solidworks C++ API - Open Solidworks & Hello World"))," post."),(0,r.kt)("p",null,'This will add "',(0,r.kt)("strong",{parentName:"p"},"Source.cpp"),'" file into our project.'),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"add-references-to-solidworks-type-library-files"},"Add References to Solidworks Type Library files"),(0,r.kt)("admonition",{type:"note"},(0,r.kt)("p",{parentName:"admonition"},"This section is copy/paste from \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-cpp/open-solidworks"},"Solidworks C++ API - Open Solidworks & Hello World"))," post.")),(0,r.kt)("p",null,"Now we need to ",(0,r.kt)("em",{parentName:"p"},"add References to Solidworks Type Library files.")),(0,r.kt)("p",null,"For this please follow below steps."),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"Select the ",(0,r.kt)("strong",{parentName:"p"},"OpenSolidworkTest")," project and and ",(0,r.kt)("em",{parentName:"p"},"Click Right Mouse Button (RMB)"),".")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"By doing this ",(0,r.kt)("em",{parentName:"p"},"a context menu")," is appear as shown in below image.")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"From this ",(0,r.kt)("em",{parentName:"p"},"context menu"),", select ",(0,r.kt)("strong",{parentName:"p"},'"Properties"')," option, which is the last one, as shown in below image."))),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"open-property-window",src:o(87243).Z,width:"634",height:"738"})),(0,r.kt)("p",null,"This will open a new window as shown in below image."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"project-property-window",src:o(95115).Z,width:"824",height:"560"})),(0,r.kt)("p",null,"Now following below steps:"),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"Select C/C++ option")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},'Add SOLIDWORKS folders path to 2nd Red colored box as shown in below image. Usually this path is "',(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"strong"},"C:\\Program Files\\ Solidworks Corp\\SOLIDWORKS")),'" if installed in default location.'))),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"add-solidowrks-reference",src:o(22603).Z,width:"825",height:"562"})),(0,r.kt)("p",null,'After adding the folder path, select "',(0,r.kt)("strong",{parentName:"p"},"Apply"),'" button.'),(0,r.kt)("p",null,"This complete the process of ",(0,r.kt)("em",{parentName:"p"},"adding References to Solidworks Type Library files.")),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"add-code-to-source-file"},"Add Code to Source file"),(0,r.kt)("p",null,"Now we need to add to ",(0,r.kt)("em",{parentName:"p"},"Source.cpp")," file."),(0,r.kt)("p",null,"Please copy the below code sample to your ",(0,r.kt)("em",{parentName:"p"},"Source.cpp")," file."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-cpp",metastring:"showLineNumbers",showLineNumbers:!0},'#include <atlbase.h>\n\n#import "sldworks.tlb" raw_interfaces_only, raw_native_types, no_namespace, named_guids  // SOLIDWORKS type library\n\n#import "swconst.tlb" raw_interfaces_only, raw_native_types, no_namespace, named_guids   // SOLIDWORKS constants type library\n\nint main()\n{\n    // Initialize COM\n    // Do this before using ATL smart pointers so COM is available.\n    CoInitialize(NULL);\n\n    // Use a block, so the smart pointers are destructed when the scope of this block is left\n    {\n        // COM Pointer of Soldiworks object\n        CComPtr<ISldWorks> swApp;\n\n        // COM Pointer of Soldiworks Model Document\n        CComPtr<IModelDoc2> swDoc;\n\n        // Variable to check if function is \n        HRESULT result = NOERROR;\n\n        // COM Style String for message to user\n        CComBSTR _messageToUser;\n\n        // long type variable to store the result value by user\n        long _lMessageResult;\n\n        // Create an instance of Solidworks application\n        // If it fails then return 0 and close program\n        if (swApp.CoCreateInstance(__uuidof(SldWorks), NULL, CLSCTX_LOCAL_SERVER) != S_OK) \n        {\n            // Stop COM \n            CoUninitialize();\n            return(0);\n        }\n\n        // COM Style String to store document type\n        CComBSTR _documentType;\n\n        // Get the Default Part document\n        swApp->GetUserPreferenceStringValue(swUserPreferenceStringValue_e::swDefaultTemplatePart, &_documentType);\n\n        // Create a new Part Document \n        result = swApp->INewDocument2(_documentType, 0, 0, 0, &swDoc);\n\n        // If there are no Default Part document assign then show a message to user\n        // and Stop COM, Visible the Solidworks and return the function\n        if (result != S_OK)\n        {\n            // COM Style String for message to user\n            _messageToUser = (L"Failed to open document.\\nPlease try again.");\n\n            // Send a message to user and store the return value in _lMessageResult by referencing it\n            swApp->SendMsgToUser2(_messageToUser, swMessageBoxIcon_e::swMbInformation, swMessageBoxBtn_e::swMbOk, &_lMessageResult);\n\n            // Visible the Solidworks\n            swApp->put_Visible(VARIANT_TRUE);\n\n            // Stop COM \n            CoUninitialize();\n            return(0);\n        }\n\n        // If created successfully, then visible the Solidworks\n        swApp->put_Visible(VARIANT_TRUE);\n    }\n\n    // Stop COM \n    CoUninitialize();\n}\n')),(0,r.kt)("p",null,"Now Build the Solution as shown in below image."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"build-solution",src:o(34062).Z,width:"648",height:"166"})),(0,r.kt)("p",null,"After Building Solution run the program by pressing ",(0,r.kt)("strong",{parentName:"p"},"F5"),"."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"final-result"},"Final Result"),(0,r.kt)("p",null,"After running the program wait for few minute."),(0,r.kt)("p",null,"You will get result as shown in below image!!!"),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"open-part-window",src:o(8762).Z,width:"1080",height:"584"})),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"issues-and-solutions"},"Issues and Solutions"),(0,r.kt)("p",null,"There are some issues I can think of which might be come to some people."),(0,r.kt)("p",null,"Those are as follows:"),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Issue 1:")),(0,r.kt)("p",null,"Program closed without open Solidworks!"),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Solution:")),(0,r.kt)("p",null,"I you face this issue, then open Solidworks Manually one time, close it and then run the program."),(0,r.kt)("p",null,"It will solve this issue."),(0,r.kt)("hr",null),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Issue 2:")),(0,r.kt)("p",null,"Program unable to create Part Document."),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Solution:")),(0,r.kt)("p",null,"This is a tricky one!!!"),(0,r.kt)("p",null,'If you face this issue, then you need to confirm in Solidworks that you have assigned the "default Part template".'),(0,r.kt)("p",null,"Please refer to below image for proper setting to fix this issue."),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"default-template-locations",src:o(92207).Z,width:"866",height:"614"})),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"I hope this will helpful!!!"))),(0,r.kt)("hr",null),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"This is it !!!"))),(0,r.kt)("p",null,"We have completed our ",(0,r.kt)("em",{parentName:"p"},"Open Part Document")," program in ",(0,r.kt)("em",{parentName:"p"},"Solidworks")," using ",(0,r.kt)("strong",{parentName:"p"},"Solidworks C++ APIs"),"."),(0,r.kt)("p",null,"Hope this post helps you to start with ",(0,r.kt)("em",{parentName:"p"},"Solidworks C++ API"),"."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Do let me know by you like this post or not! I will continue creating Solidworks C++ posts.")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Till then, Happy learning!!!")))}d.isMDXComponent=!0},92207:(e,t,o)=>{o.d(t,{Z:()=>n});const n=o.p+"assets/images/default-template-locations-abf74a769182507e4b234c14c5bc8c75.png"},70900:(e,t,o)=>{o.d(t,{Z:()=>n});const n=o.p+"assets/images/new-project-window-de59822283fe5ca841a16722957d5604.png"},8762:(e,t,o)=>{o.d(t,{Z:()=>n});const n=o.p+"assets/images/open-part-window-c644dafb267abcd0b776b8c1946e290c.png"},22603:(e,t,o)=>{o.d(t,{Z:()=>n});const n=o.p+"assets/images/add-solidowrks-reference-1a1ca5269a89c20dcf68687bed4f57f1.png"},34062:(e,t,o)=>{o.d(t,{Z:()=>n});const n=o.p+"assets/images/build-solution-588c7601214b803be92cd586a148bb2e.png"},87243:(e,t,o)=>{o.d(t,{Z:()=>n});const n=o.p+"assets/images/open-property-window-fbed5c07225a50d940c99768ebb68f86.png"},95115:(e,t,o)=>{o.d(t,{Z:()=>n});const n=o.p+"assets/images/project-property-window-71bcffa26b32a7297231b56e5ae5d052.png"}}]);