"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[956],{3905:function(e,t,n){n.d(t,{Zo:function(){return m},kt:function(){return c}});var o=n(67294);function a(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function r(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,o)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?r(Object(n),!0).forEach((function(t){a(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function p(e,t){if(null==e)return{};var n,o,a=function(e,t){if(null==e)return{};var n,o,a={},r=Object.keys(e);for(o=0;o<r.length;o++)n=r[o],t.indexOf(n)>=0||(a[n]=e[n]);return a}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(o=0;o<r.length;o++)n=r[o],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(a[n]=e[n])}return a}var l=o.createContext({}),s=function(e){var t=o.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},m=function(e){var t=s(e.components);return o.createElement(l.Provider,{value:t},e.children)},d={inlineCode:"code",wrapper:function(e){var t=e.children;return o.createElement(o.Fragment,{},t)}},u=o.forwardRef((function(e,t){var n=e.components,a=e.mdxType,r=e.originalType,l=e.parentName,m=p(e,["components","mdxType","originalType","parentName"]),u=s(n),c=a,k=u["".concat(l,".").concat(c)]||u[c]||d[c]||r;return n?o.createElement(k,i(i({ref:t},m),{},{components:n})):o.createElement(k,i({ref:t},m))}));function c(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var r=n.length,i=new Array(r);i[0]=u;var p={};for(var l in t)hasOwnProperty.call(t,l)&&(p[l]=t[l]);p.originalType=e,p.mdxType="string"==typeof e?e:a,i[1]=p;for(var s=2;s<r;s++)i[s]=n[s];return o.createElement.apply(null,i)}return o.createElement.apply(null,n)}u.displayName="MDXCreateElement"},30344:function(e,t,n){n.r(t),n.d(t,{assets:function(){return m},contentTitle:function(){return l},default:function(){return c},frontMatter:function(){return p},metadata:function(){return s},toc:function(){return d}});var o=n(87462),a=n(63366),r=(n(67294),n(3905)),i=["components"],p={categories:"Solidworks-macro",title:"Solidworks Macro - Open Saved Documents",permalink:"/solidworks-macros/open-saved-document/",tags:["Solidworks Macro"],id:"open-saved-document"},l=void 0,s={unversionedId:"open-saved-document",id:"open-saved-document",title:"Solidworks Macro - Open Saved Documents",description:"In this post, I tell you how to open a saved document in Solidworks using VBA Macro.",source:"@site/docs/solidworks-macros/001.5-open-saved-document.md",sourceDirName:".",slug:"/open-saved-document",permalink:"/solidworks-macros/open-saved-document",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Open Saved Documents",permalink:"/solidworks-macros/open-saved-document/",tags:["Solidworks Macro"],id:"open-saved-document"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Selection Methods",permalink:"/solidworks-macros/select-plane-from-tree"},next:{title:"Solidworks Macro - Fix Unit Issue",permalink:"/solidworks-macros/unit-correction"}},m={},d=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"By OpenDoc method",id:"by-opendoc-method",level:2},{value:"By OpenDoc6 method",id:"by-opendoc6-method",level:2}],u={toc:d};function c(e){var t=e.components,n=(0,a.Z)(e,i);return(0,r.kt)("wrapper",(0,o.Z)({},u,n,{components:t,mdxType:"MDXLayout"}),(0,r.kt)("p",null,"In this post, I tell you how to ",(0,r.kt)("em",{parentName:"p"},"open a saved document")," in Solidworks using ",(0,r.kt)("em",{parentName:"p"},"VBA Macro"),"."),(0,r.kt)("p",null,"We open document with 2 different methods."),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"By ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc")," method")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"By ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc6")," method"))),(0,r.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,r.kt)("p",null,"Please see below video \ud83c\udfac on ",(0,r.kt)("strong",{parentName:"p"},"how to Open Saved Documents")," from Visual Studio."),(0,r.kt)("iframe",{src:"https://www.youtube.com/embed/DeltLKXAIjY",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,r.kt)("p",null,"Please note that there are ",(0,r.kt)("strong",{parentName:"p"},"no explaination")," in the video. "),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,r.kt)("h2",{id:"by-opendoc-method"},"By OpenDoc method"),(0,r.kt)("p",null,"This is ",(0,r.kt)("strong",{parentName:"p"},"the simplest")," method to open a saved part from your computer."),(0,r.kt)("p",null,"In this method we just need two information."),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"Location of document to open")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"Type of document which we want to open"))),(0,r.kt)("p",null,"Below is the example code for opening a saved document using ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc")," method."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Boolean Variable\nDim BoolStatus As Boolean\n\n\n' Main function of our VBA program\nSub main()\n\n  ' Setting Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n      \n  ' Open a saved document\n  Set swDoc = swApp.OpenDoc(\"H:\\Solidworks studies\\API Studies\\Chapter 1 - The Basics\\1st example part.SLDPRT\", swDocumentTypes_e.swDocPART)\n      \n  ' Selecting Front Plane\n  BoolStatus = swDoc.SelectByID(\"Front Plane\", \"PLANE\", 0, 0, 0)\n\nEnd Sub\n")),(0,r.kt)("p",null,"I have already explained every line except ",(0,r.kt)("em",{parentName:"p"},"middle line")," in above code sample in previous posts."),(0,r.kt)("p",null,"To open a saved document we used following lline."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Open a saved document\nSet swDoc = swApp.OpenDoc("H:\\Solidworks studies\\API Studies\\Chapter 1 - The Basics\\1st example part.SLDPRT", swDocumentTypes_e.swDocPART)\n')),(0,r.kt)("p",null,"Here, we set the ",(0,r.kt)("inlineCode",{parentName:"p"},"ModelDoc2")," variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," to a value."),(0,r.kt)("p",null,"This value is ",(0,r.kt)("em",{parentName:"p"},"return")," or ",(0,r.kt)("em",{parentName:"p"},"provided")," by ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc")," method."),(0,r.kt)("p",null,"This method is part of ",(0,r.kt)("em",{parentName:"p"},"Solidworks document"),". "),(0,r.kt)("p",null,"Since we define ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," variable as Solidworks document hence we 1st call ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," and then using ",(0,r.kt)("inlineCode",{parentName:"p"},"Dot operator")," we access the ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc")," method."),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc")," method takes 2 ",(0,r.kt)("em",{parentName:"p"},"arguments")," or ",(0,r.kt)("em",{parentName:"p"},"parameter"),"."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"FileName")," : Document name or full path if not in current directory, including extension."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Type")," : Document type as define in ",(0,r.kt)("inlineCode",{parentName:"p"},"swDocumentTypes_e")," as follows."),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocASSEMBLY"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocDRAWING"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocLAYOUT"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocNONE"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocPART"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocSDM")))),(0,r.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"info")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"If you want to open a Library feature part then we use ",(0,r.kt)("inlineCode",{parentName:"p"},"swDocPART")," as document type."))),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Return Value")," - If the document opens then this method returns ",(0,r.kt)("inlineCode",{parentName:"p"},"True")," and otherwise ",(0,r.kt)("inlineCode",{parentName:"p"},"False"),"."),(0,r.kt)("p",null,"If you just want to open a saved document then this method is what you are looking for."),(0,r.kt)("p",null,"For most of the part, ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc")," method works well."),(0,r.kt)("p",null,"If you want more option while opening a document, then next method is for you."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"by-opendoc6-method"},"By OpenDoc6 method"),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc6")," method is extension to ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc")," with some additional parameters."),(0,r.kt)("p",null,"How ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc6")," works is shown in below code sample:"),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'Option Explicit\n\n\' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\' Boolean Variable\nDim BoolStatus As Boolean\n\n\n\' Main function of our VBA program\nSub main()\n\n  \' Setting Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n      \n  \' Open an saved document\n  Set swDoc = swApp.OpenDoc6("H:\\Solidworks studies\\API Studies\\Chapter 1 - The Basics\\1st example part.SLDPRT", swDocumentTypes_e.swDocPART, swOpenDocOptions_e.swOpenDocOptions_Silent, "", 0, 0)\n      \n  \' Selecting Front Plane\n  BoolStatus = swDoc.SelectByID("Front Plane", "PLANE", 0, 0, 0)\n\nEnd Sub\n')),(0,r.kt)("p",null,"This code sample is similar is to previous example code except for ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc6")," method takes extra 4 parameters."),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc6")," method takes 6 ",(0,r.kt)("em",{parentName:"p"},"arguments")," or ",(0,r.kt)("em",{parentName:"p"},"parameter"),"."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"FileName")," : Document name or full path if not in current directory, including extension."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Type")," : Document type as define in ",(0,r.kt)("inlineCode",{parentName:"p"},"swDocumentTypes_e")," as follows."),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocASSEMBLY"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocDRAWING"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocLAYOUT"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocNONE"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocPART"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swDocSDM")))),(0,r.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"info")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"f you want to open a Library feature part then we use ",(0,r.kt)("inlineCode",{parentName:"p"},"swDocPART")," as document type."))),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Options")," : Mode in which to open the document as defined in ",(0,r.kt)("inlineCode",{parentName:"p"},"swOpenDocOptions_e"),"."),(0,r.kt)("p",null,"For more details about ",(0,r.kt)("em",{parentName:"p"},"Options")," parameters, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swOpenDocOptions_e.html"},"this page of Solidworks API Help")),"."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Configuration")," : Configuration in which you want to open this document."),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"Applies to ",(0,r.kt)("em",{parentName:"p"},"Part")," and ",(0,r.kt)("em",{parentName:"p"},"Assemblies"),", not ",(0,r.kt)("em",{parentName:"p"},"drawings"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},"If this argument is ",(0,r.kt)("em",{parentName:"p"},"empty")," or the specified configuration is ",(0,r.kt)("em",{parentName:"p"},"not present")," in the model, the model is opened in the last-used configuration."))),(0,r.kt)("p",null,"I used an ",(0,r.kt)("inlineCode",{parentName:"p"},'""')," in the above code sample, because I want to open part file in last saved configuration."),(0,r.kt)("p",null,"If you don't know about ",(0,r.kt)("inlineCode",{parentName:"p"},'""'),", then this symbol represent an ",(0,r.kt)("strong",{parentName:"p"},"empty string"),"."),(0,r.kt)("p",null,"When we don't want to pass any value as ",(0,r.kt)("inlineCode",{parentName:"p"},"string"),", at that time I use ",(0,r.kt)("inlineCode",{parentName:"p"},'""'),"."),(0,r.kt)("p",null,"You can also use ",(0,r.kt)("inlineCode",{parentName:"p"},'""')," when you want to pass an empty string in VBA."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Errors")," : Load errors as defined in ",(0,r.kt)("inlineCode",{parentName:"p"},"swFileLoadError_e"),"."),(0,r.kt)("p",null,"For more details about ",(0,r.kt)("em",{parentName:"p"},"Errors")," parameters, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swFileLoadError_e.html"},"this page of Solidworks API Help")),"."),(0,r.kt)("p",null,"Since this parameter is ",(0,r.kt)("inlineCode",{parentName:"p"},"long")," type, and I don't want to enter any value from the provided list; I used ",(0,r.kt)("strong",{parentName:"p"},"0")," as value."),(0,r.kt)("p",null,"If you want to use options from option link then you can use values from there."),(0,r.kt)("p",null,"It is just I don't want to load any error information about the part."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Warnings")," : Warnings or extra information generated during the open operation as defined in ",(0,r.kt)("inlineCode",{parentName:"p"},"swFileLoadWarning_e"),"."),(0,r.kt)("p",null,"For more details about ",(0,r.kt)("em",{parentName:"p"},"Warnings")," parameters, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swFileLoadWarning_e.html"},"this page of Solidworks API Help"),".")),(0,r.kt)("p",null,"As in the previous parameter, I use ",(0,r.kt)("strong",{parentName:"p"},"0")," as value."),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Return Value")," - If the document opens then this method returns ",(0,r.kt)("inlineCode",{parentName:"p"},"True")," and otherwise ",(0,r.kt)("inlineCode",{parentName:"p"},"False"),"."),(0,r.kt)("p",null,"As you can see, in ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc6")," method, we need to defined the extra parameters compared to ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc")," method."),(0,r.kt)("p",null,"It is worth noted that, ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc6")," method is the most updated method for opening a saved document."),(0,r.kt)("p",null,"Hence if did not use any of the above method, I would recommend you to use ",(0,r.kt)("inlineCode",{parentName:"p"},"OpenDoc6")," method."),(0,r.kt)("p",null,"Hope this post helps you to understand opening methods with Solidworks VB Macros."),(0,r.kt)("p",null,"For more such tutorials on Solidworks VBA Macros, do come to this blog after sometime."),(0,r.kt)("p",null,"Till then, Happy learning!!!"))}c.isMDXComponent=!0}}]);