"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[961],{3905:(e,t,n)=>{n.d(t,{Zo:()=>m,kt:()=>d});var o=n(67294);function a(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function r(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,o)}return n}function l(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?r(Object(n),!0).forEach((function(t){a(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function i(e,t){if(null==e)return{};var n,o,a=function(e,t){if(null==e)return{};var n,o,a={},r=Object.keys(e);for(o=0;o<r.length;o++)n=r[o],t.indexOf(n)>=0||(a[n]=e[n]);return a}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(o=0;o<r.length;o++)n=r[o],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(a[n]=e[n])}return a}var s=o.createContext({}),p=function(e){var t=o.useContext(s),n=t;return e&&(n="function"==typeof e?e(t):l(l({},t),e)),n},m=function(e){var t=p(e.components);return o.createElement(s.Provider,{value:t},e.children)},k={inlineCode:"code",wrapper:function(e){var t=e.children;return o.createElement(o.Fragment,{},t)}},c=o.forwardRef((function(e,t){var n=e.components,a=e.mdxType,r=e.originalType,s=e.parentName,m=i(e,["components","mdxType","originalType","parentName"]),c=p(n),d=a,u=c["".concat(s,".").concat(d)]||c[d]||k[d]||r;return n?o.createElement(u,l(l({ref:t},m),{},{components:n})):o.createElement(u,l({ref:t},m))}));function d(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var r=n.length,l=new Array(r);l[0]=c;var i={};for(var s in t)hasOwnProperty.call(t,s)&&(i[s]=t[s]);i.originalType=e,i.mdxType="string"==typeof e?e:a,l[1]=i;for(var p=2;p<r;p++)l[p]=n[p];return o.createElement.apply(null,l)}return o.createElement.apply(null,n)}c.displayName="MDXCreateElement"},69517:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>p,contentTitle:()=>i,default:()=>c,frontMatter:()=>l,metadata:()=>s,toc:()=>m});var o=n(87462),a=(n(67294),n(3905)),r=n(74753);const l={categories:"Solidworks-macro",title:"Solidworks Macro - Create a Centerpoint Arc Slot",permalink:"/solidworks-macros/create-centerpoint-arc-slot/",tags:["Solidworks Macro"],id:"create-centerpoint-arc-slot"},i=void 0,s={unversionedId:"create-centerpoint-arc-slot",id:"create-centerpoint-arc-slot",title:"Solidworks Macro - Create a Centerpoint Arc Slot",description:"",source:"@site/docs/solidworks-macros/006.4-create-centerpoint-arc-slot.md",sourceDirName:".",slug:"/create-centerpoint-arc-slot",permalink:"/solidworks-macros/create-centerpoint-arc-slot",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Create a Centerpoint Arc Slot",permalink:"/solidworks-macros/create-centerpoint-arc-slot/",tags:["Solidworks Macro"],id:"create-centerpoint-arc-slot"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Create a 3-Point Arc Slot",permalink:"/solidworks-macros/create-3point-arc-slot"},next:{title:"Solidworks Macro - Create a Point",permalink:"/solidworks-macros/create-point"}},p={},m=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"For Experience Macro Developer",id:"for-experience-macro-developer",level:2},{value:"For Beginners Macro Developers",id:"for-beginners-macro-developers",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:3},{value:"VBA Language feature used in this post",id:"vba-language-feature-used-in-this-post",level:2},{value:"Solidworks API Objects",id:"solidworks-api-objects",level:2}],k={toc:m};function c(e){let{components:t,...l}=e;return(0,a.kt)("wrapper",(0,o.Z)({},k,l,{components:t,mdxType:"MDXLayout"}),(0,a.kt)(r.Z,{mdxType:"AdComponent"}),(0,a.kt)("p",null,"In this post, I tell you about ",(0,a.kt)("em",{parentName:"p"},"how to create a Centerpoint Arc Slot through Solidworks VBA Macros")," in a sketch."),(0,a.kt)("p",null,"The process is almost identical with previous \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-straight-slot"},"Sketch - Create Straight Slot"))," post. "),(0,a.kt)("hr",null),(0,a.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,a.kt)("p",null,"Please see below video \ud83c\udfac on ",(0,a.kt)("strong",{parentName:"p"},"how to create a Centerpoint Arc Slot")," from Solidworks VBA Macros."),(0,a.kt)("iframe",{src:"https://www.youtube.com/embed/9qZJ4fjo5kw",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,a.kt)("p",null,"Please note that there are ",(0,a.kt)("strong",{parentName:"p"},"no explaination")," in the video. "),(0,a.kt)("p",null,(0,a.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,a.kt)("hr",null),(0,a.kt)("h2",{id:"for-experience-macro-developer"},"For Experience Macro Developer"),(0,a.kt)("p",null,"If you are an experience ",(0,a.kt)("strong",{parentName:"p"},"Solidworks Macro developer"),", then you are looking for a specific code sample."),(0,a.kt)("p",null,"Below is the code for creating ",(0,a.kt)("strong",{parentName:"p"},"A Centerpoint Arc Slot")," from ",(0,a.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),"."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating Variable for Solidworks Slot\nDim mySketchSlot As SketchSlot\n    \n' Setting the value of a Centerpoint Arc slot\nSet mySketchSlot = swSketchManager.CreateSketchSlot(swSketchSlotCreationType_e.swSketchSlotCreationType_arc, swSketchSlotLengthType_e.swSketchSlotLengthType_CenterCenter, 0.5, 0, 0, 0, -1, 0, 0, 1, 0, 0, -1, False)\n")),(0,a.kt)("p",null,"First you need to ",(0,a.kt)("strong",{parentName:"p"},"Create")," a variable of ",(0,a.kt)("inlineCode",{parentName:"p"},"SketchSlot")," type."),(0,a.kt)("p",null,"After creating variable, you need to set the value of this variable."),(0,a.kt)("p",null,"For this you used ",(0,a.kt)("inlineCode",{parentName:"p"},"CreateSketchSlot")," method from ",(0,a.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,a.kt)("p",null,"This ",(0,a.kt)("inlineCode",{parentName:"p"},"CreateSketchSlot")," method set the value of ",(0,a.kt)("inlineCode",{parentName:"p"},"SketchSlot")," type variable."),(0,a.kt)("p",null,"The ",(0,a.kt)("inlineCode",{parentName:"p"},"CreateSketchSlot")," method takes following parameters:"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"SlotCreationType")," : ",(0,a.kt)("em",{parentName:"p"},"Type of sketch slot"),"."),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"SlotLengthType")," : ",(0,a.kt)("em",{parentName:"p"},"Type of length of sketch slot"),"."),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Width")," : Width of Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"X1")," : X coordinate of the point 1, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Y1")," : Y coordinate of the point 1, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Z1")," : Z coordinate of the point 1, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"X2")," : X coordinate of the point 2, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Y2")," : Y coordinate of the point 2, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Z2")," : Z coordinate of the point 2, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"X3")," : X coordinate of the point 3, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Y3")," : Y coordinate of the point 3, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Z3")," : Z coordinate of the point 3, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"CenterArcDirection")," : We need to set the direction eiter Clockwise or Anti-Clockwise/Counterclockwise "),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"AddDimension")," : ",(0,a.kt)("inlineCode",{parentName:"p"},"True")," to automatically add dimensions, ",(0,a.kt)("inlineCode",{parentName:"p"},"False")," to not."),(0,a.kt)("p",null,"If you want a more detail explaination then please read further otherwise this will help you to ",(0,a.kt)("strong",{parentName:"p"},"Create a Centerpoint Arc Slot From VBA Macro"),"."),(0,a.kt)("hr",null),(0,a.kt)(r.Z,{mdxType:"AdComponent"}),(0,a.kt)("h2",{id:"for-beginners-macro-developers"},"For Beginners Macro Developers"),(0,a.kt)("p",null,"In this post, I tell you about ",(0,a.kt)("inlineCode",{parentName:"p"},"CreateSketchSlot")," method from ",(0,a.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,a.kt)("inlineCode",{parentName:"p"},"SketchManager")," object."),(0,a.kt)("p",null,"This method is ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"most updated"))," method, I found in ",(0,a.kt)("em",{parentName:"p"},"Solidworks API Help"),". "),(0,a.kt)("p",null,"So ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"use this method"))," if you want to create a new ",(0,a.kt)("strong",{parentName:"p"},"Centerpoint Arc Slot"),"."),(0,a.kt)("p",null,"Below is the ",(0,a.kt)("inlineCode",{parentName:"p"},"code")," sample for creating ",(0,a.kt)("em",{parentName:"p"},"a Centerpoint Arc Slot"),"."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Boolean Variable\nDim BoolStatus As Boolean\n' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Main function of our VBA program\nSub main()\n\n  ' Setting Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Creating string type variable for storing default part location\n  Dim defaultTemplate As String\n  ' Setting value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Setting Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n  ' Selecting Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Setting Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n  \n  ' Inserting a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Creating Variable for Solidworks Slot\n  Dim mySketchSlot As SketchSlot\n      \n  ' Creating a Centerpoint Arc slot\n  Set mySketchSlot = swSketchManager.CreateSketchSlot(swSketchSlotCreationType_e.swSketchSlotCreationType_arc, swSketchSlotLengthType_e.swSketchSlotLengthType_CenterCenter, 0.5, 0, 0, 0, -1, 0, 0, 1, 0, 0, -1, False)\n\n  ' De-select the Slot after creation\n  swDoc.ClearSelection2 True\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit\n\nEnd Sub\n")),(0,a.kt)("hr",null),(0,a.kt)("h3",{id:"understanding-the-code"},"Understanding the Code"),(0,a.kt)("p",null,"Now let us walk through ",(0,a.kt)("em",{parentName:"p"},"each line")," in the above code, and ",(0,a.kt)("strong",{parentName:"p"},"understand")," the meaning of every line."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,a.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,a.kt)("admonition",{type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"For more information please visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,a.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,a.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,a.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,a.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,a.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,a.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,a.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,a.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,a.kt)("p",null,"Next is our ",(0,a.kt)("inlineCode",{parentName:"p"},"Sub")," procedure named as ",(0,a.kt)("inlineCode",{parentName:"p"},"main"),". This procedure hold all the ",(0,a.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,a.kt)("p",null,"In this line, we are setting the value of our Solidworks variable ",(0,a.kt)("inlineCode",{parentName:"p"},"swApp")," which we defined earlier to Solidworks application."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating string type variable for storing default part location\nDim defaultTemplate As String\n' Setting value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),(0,a.kt)("p",null,"In 1st statement of above example, we are defining a variable of ",(0,a.kt)("inlineCode",{parentName:"p"},"string")," type and named it as ",(0,a.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),(0,a.kt)("p",null,"This variable ",(0,a.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),", holds the location the location of ",(0,a.kt)("strong",{parentName:"p"},"Default Part Template"),"."),(0,a.kt)("p",null,"In 2nd line of above example. we assign value to our newly define ",(0,a.kt)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),(0,a.kt)("p",null,"We assign the value by using a ",(0,a.kt)("em",{parentName:"p"},"Method")," named ",(0,a.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),(0,a.kt)("p",null,"This method is a part of our main Solidworks variable ",(0,a.kt)("inlineCode",{parentName:"p"},"swApp"),"."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),(0,a.kt)("p",null,"In this line, we set the value of our ",(0,a.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),(0,a.kt)("admonition",{type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"For ",(0,a.kt)("strong",{parentName:"p"},"more detailed information")," about above lines please visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post. "),(0,a.kt)("p",{parentName:"admonition"},"I have discussed them ",(0,a.kt)("strong",{parentName:"p"},"thoroghly")," in \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post, so do checkout this post if you don't understand above code.")),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Boolean Variable\nDim BoolStatus As Boolean\n\n\' Selecting Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,a.kt)("p",null,"In 1st line, we create a variable named ",(0,a.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,a.kt)("inlineCode",{parentName:"p"},"Boolean")," object."),(0,a.kt)("p",null,"In next line, we select the ",(0,a.kt)("em",{parentName:"p"},"front plane")," by using ",(0,a.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,a.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,a.kt)("admonition",{type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"For more information about selection method please visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."),(0,a.kt)("p",{parentName:"admonition"},"I have discussed about different ",(0,a.kt)("em",{parentName:"p"},"Selection methods")," in details in \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Soldworks Macros - Selection Methods"))," post, so do visit this post for more ",(0,a.kt)("em",{parentName:"p"},"Selection methods"),".")),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),(0,a.kt)("p",null,"In above line, we create variable ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchManager")," for ",(0,a.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,a.kt)("p",null,"As the name suggested, a ",(0,a.kt)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",(0,a.kt)("em",{parentName:"p"},"Sketches"),"."),(0,a.kt)("p",null,"To see methods and properties related to SketchManager object, please visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this page of Solidworks API Help"))),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),(0,a.kt)("p",null,"In above line, we set the ",(0,a.kt)("strong",{parentName:"p"},"Sketch manager")," variable to current document's sketch manager."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Inserting a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,a.kt)("p",null,"In above line, we use ",(0,a.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,a.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,a.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,a.kt)("p",null,"This method allows us to insert a sketch in selected plane."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating Variable for Solidworks Slot\nDim mySketchSlot As SketchSlot\n      \n' Creating a Centerpoint Arc slot\nSet mySketchSlot = swSketchManager.CreateSketchSlot(swSketchSlotCreationType_e.swSketchSlotCreationType_arc, swSketchSlotLengthType_e.swSketchSlotLengthType_CenterCenter, 0.5, 0, 0, 0, -1, 0, 0, 1, 0, 0, -1, False\n")),(0,a.kt)("p",null,"In above sample code, we 1st create a variable named ",(0,a.kt)("inlineCode",{parentName:"p"},"mySketchSlot")," of type ",(0,a.kt)("inlineCode",{parentName:"p"},"SketchSlot"),"."),(0,a.kt)("p",null,"In 2nd line, we ",(0,a.kt)("strong",{parentName:"p"},"set")," the value of ",(0,a.kt)("em",{parentName:"p"},"SketchSlot")," variable ",(0,a.kt)("inlineCode",{parentName:"p"},"mySketchSlot"),"."),(0,a.kt)("p",null,"We get this value from ",(0,a.kt)("inlineCode",{parentName:"p"},"CreateSketchSlot")," method which is inside the ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchManager")," variable."),(0,a.kt)("p",null,(0,a.kt)("inlineCode",{parentName:"p"},"swSketchManager")," variable is a type of ",(0,a.kt)("strong",{parentName:"p"},"SketchManager"),", hence we used ",(0,a.kt)("inlineCode",{parentName:"p"},"CreateSketchSlot")," method from ",(0,a.kt)("strong",{parentName:"p"},"SketchManager"),"."),(0,a.kt)("p",null,"This ",(0,a.kt)("inlineCode",{parentName:"p"},"CreateSketchSlot")," method takes following parameters as explained:"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"SlotCreationType")," : ",(0,a.kt)("em",{parentName:"p"},"Type of sketch slot")," as defined in ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchSlotCreationType_e"),"."),(0,a.kt)("p",null,"  There are 4 Different types of Slots we can create."),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Straight Slot"))," : ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchSlotCreationType_e.swSketchSlotCreationType_line")," or ",(0,a.kt)("strong",{parentName:"p"},"0"))),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Centerpoint straight Slot"))," : ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchSlotCreationType_e.swSketchSlotCreationType_center_line")," or ",(0,a.kt)("strong",{parentName:"p"},"1"))),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Centerpoint arc Slot"))," : ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchSlotCreationType_e.swSketchSlotCreationType_arc")," or ",(0,a.kt)("strong",{parentName:"p"},"2"))),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"3-point arc Slot"))," : ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchSlotCreationType_e.swSketchSlotCreationType_3pointarc")," or ",(0,a.kt)("strong",{parentName:"p"},"4")))),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"SlotLengthType")," : ",(0,a.kt)("em",{parentName:"p"},"Type of length of sketch slot")," as defined in ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchSlotLengthType_e"),"."),(0,a.kt)("p",null,"  There are 2 different types of Sketch slot length we can create."),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Center to Center"))," : ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchSlotLengthType_e.swSketchSlotLengthType_CenterCenter")," or ",(0,a.kt)("strong",{parentName:"p"},"0"))),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Full Length"))," : ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchSlotLengthType_e.swSketchSlotLengthType_FullLength")," or ",(0,a.kt)("strong",{parentName:"p"},"1")))),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Width")," : Width of Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"X1")," : X coordinate of the point 1, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Y1")," : Y coordinate of the point 1, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Z1")," : Z coordinate of the point 1, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"X2")," : X coordinate of the point 2, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Y2")," : Y coordinate of the point 2, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Z2")," : Z coordinate of the point 2, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"X3")," : X coordinate of the point 3, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Y3")," : Y coordinate of the point 3, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"Z3")," : Z coordinate of the point 3, of the Slot"),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"CenterArcDirection")," : We need to set the direction eiter Clockwise or Anti-Clockwise/Counterclockwise as follows:"),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Clockwise (CW)"))," : -1")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Anti-Clockwise/Counterclockwise (CCW)"))," : 1"))),(0,a.kt)("p",null,(0,a.kt)("em",{parentName:"p"},"AddDimension")," : ",(0,a.kt)("inlineCode",{parentName:"p"},"True")," to automatically add dimensions, ",(0,a.kt)("inlineCode",{parentName:"p"},"False")," to not."),(0,a.kt)("p",null,"For ",(0,a.kt)("strong",{parentName:"p"},"more details")," about ",(0,a.kt)("em",{parentName:"p"},"Slot Parameter")," you can visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/english/api/sldworksapi/solidworks.interop.sldworks~solidworks.interop.sldworks.isketchmanager~createsketchslot.html"},"this page of Solidworks API Help"))),(0,a.kt)("p",null,"For creating a ",(0,a.kt)("em",{parentName:"p"},"Centerpoint Arc Slot"),", I used following parameter Values:"),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"SlotCreationType")," : ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchSlotCreationType_e.swSketchSlotCreationType_arc")),(0,a.kt)("p",{parentName:"li"},"Since we want to create a ",(0,a.kt)("em",{parentName:"p"},"Centerpoint Arc Slot")," hence I select above value.")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"SlotLengthType")," : ",(0,a.kt)("inlineCode",{parentName:"p"},"swSketchSlotLengthType_e.swSketchSlotLengthType_CenterCenter")),(0,a.kt)("p",{parentName:"li"},"I want length of this Slot from ",(0,a.kt)("em",{parentName:"p"},"Center to Center")," hence I select above value.")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"Width")," : ",(0,a.kt)("strong",{parentName:"p"},"0.5"))),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"X1, Y1, Z1")," : ",(0,a.kt)("inlineCode",{parentName:"p"},"0, 0, 0")),(0,a.kt)("p",{parentName:"li"},"For Point 1, I use (0, 0, 0) values, which is ",(0,a.kt)("em",{parentName:"p"},"origin")," of Sketch.")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"X2, Y2, Z2")," : ",(0,a.kt)("inlineCode",{parentName:"p"},"-1, 0, 0")),(0,a.kt)("p",{parentName:"li"},"For Point 2, I use (-1, 0, 0) values, which is which is -1 point distance in X-direction.")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"X3, Y3, Z3")," : ",(0,a.kt)("inlineCode",{parentName:"p"},"1, 0, 0")),(0,a.kt)("p",{parentName:"li"},"For Point 2, I use (1, 0, 0) values, which is which is 1 point distance in X-direction.")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"CenterArcDirection")," : ",(0,a.kt)("strong",{parentName:"p"},"-1")),(0,a.kt)("p",{parentName:"li"},"I want to create Clockwise Slot.")),(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("p",{parentName:"li"},(0,a.kt)("em",{parentName:"p"},"AddDimension")," : ",(0,a.kt)("inlineCode",{parentName:"p"},"False")))),(0,a.kt)("p",null,"Below Image described ",(0,a.kt)("strong",{parentName:"p"},"the Parameters for Centerpoint Arc Slot")," in more detail."),(0,a.kt)("p",null,(0,a.kt)("img",{alt:"centerpoint-arc-slot-parameters",src:n(24071).Z,width:"822",height:"489"})),(0,a.kt)("p",null,"This ",(0,a.kt)("inlineCode",{parentName:"p"},"CreateSketchSlot")," method returns ",(0,a.kt)("em",{parentName:"p"},"Sketch Slot")," interface i.e. ",(0,a.kt)("inlineCode",{parentName:"p"},"ISketchSlot")," interface. "),(0,a.kt)("p",null,"This ",(0,a.kt)("inlineCode",{parentName:"p"},"ISketchSlot")," interface has various ",(0,a.kt)("strong",{parentName:"p"},"methods and properties")," for ",(0,a.kt)("em",{parentName:"p"},"a Slot"),"."),(0,a.kt)("p",null,"For more detail about ",(0,a.kt)("strong",{parentName:"p"},"methods and properties")," of ",(0,a.kt)("inlineCode",{parentName:"p"},"ISketchSlot")," interface you can visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSlot_members.html"},"this page of Solidworks API Help"))),(0,a.kt)("hr",null),(0,a.kt)("admonition",{title:"NOTE",type:"tip"},(0,a.kt)("p",{parentName:"admonition"},"It is ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",(0,a.kt)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Meter only")),"."),(0,a.kt)("p",{parentName:"admonition"},(0,a.kt)("em",{parentName:"p"},"Solidworks API")," does not care about your application's Unit systems."),(0,a.kt)("p",{parentName:"admonition"},'For example, I works in ANSI system means "inches" for distance. '),(0,a.kt)("p",{parentName:"admonition"},"But when I used Solidworks API through ",(0,a.kt)("em",{parentName:"p"},"VBA macros")," or ",(0,a.kt)("em",{parentName:"p"},"C#"),", I have to use ",(0,a.kt)("strong",{parentName:"p"},"converted")," numeric values."),(0,a.kt)("p",{parentName:"admonition"},"Because Solidworks API output the distance in ",(0,a.kt)("strong",{parentName:"p"},"Meter")," only; which is not my requirement.")),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Slot after creation\nswDoc.ClearSelection2 True\n")),(0,a.kt)("p",null,"In the this line of code, we de-select the created Centerpointrc Slot."),(0,a.kt)("p",null,"For de-selecting, we use ",(0,a.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document variable ",(0,a.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,a.kt)("pre",null,(0,a.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),(0,a.kt)("p",null,"In this last line we use ",(0,a.kt)("em",{parentName:"p"},"zoom to fit")," command."),(0,a.kt)("p",null,"For Zoom to fit, we use ",(0,a.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",(0,a.kt)("inlineCode",{parentName:"p"},"swDoc"),". "),(0,a.kt)("p",null,"After this our Solidworks VBA Macro ends the ",(0,a.kt)("strong",{parentName:"p"},"Sub procedure")," and we create ",(0,a.kt)("strong",{parentName:"p"},"a Centerpoint Arc Slot"),"."),(0,a.kt)("hr",null),(0,a.kt)(r.Z,{mdxType:"AdComponent"}),(0,a.kt)("h2",{id:"vba-language-feature-used-in-this-post"},"VBA Language feature used in this post"),(0,a.kt)("p",null,"In this post used some features of ",(0,a.kt)("strong",{parentName:"p"},"VBA programming language"),"."),(0,a.kt)("p",null,"This section of post, has some brief information about the VBA programming language specific features."),(0,a.kt)("ol",null,(0,a.kt)("li",{parentName:"ol"},(0,a.kt)("p",{parentName:"li"},"We use ",(0,a.kt)("strong",{parentName:"p"},"Option Explicit")," for capturing un-declared variables. If you want to read more about ",(0,a.kt)("strong",{parentName:"p"},"Option Explicit")," then please visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/vba/vba-declaring-and-scoping-of-variables"},"Declaring and Scoping of Variables")),".")),(0,a.kt)("li",{parentName:"ol"},(0,a.kt)("p",{parentName:"li"},"Then we create ",(0,a.kt)("strong",{parentName:"p"},"variable")," for different data types. If you don't know about them, then please visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/vba/vba-variables"},"Variables"))," and \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/vba/vba-programming-concepts/#data-types-in-vba"},"Data-types"))," posts of this blog. These posts will help you to understand what ",(0,a.kt)("strong",{parentName:"p"},"Variables")," are and how to use them.")),(0,a.kt)("li",{parentName:"ol"},(0,a.kt)("p",{parentName:"li"},"Then we create ",(0,a.kt)("strong",{parentName:"p"},"main Sub procedure")," for our macro. If you don't know about the ",(0,a.kt)("strong",{parentName:"p"},"Sub procedure"),", then I suggest you to visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/vba/vba-sub-and-function-procedure"},"VBA Sub and Function Procedures"))," and \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/vba/vba-executing-procedures"},"Executing Sub and Function Procedures"))," posts of this blog. These posts will help you to understand what ",(0,a.kt)("strong",{parentName:"p"},"Procedures")," are and how to use them.")),(0,a.kt)("li",{parentName:"ol"},(0,a.kt)("p",{parentName:"li"},"In most part we create some variables and set their values. We set those values by using some ",(0,a.kt)("strong",{parentName:"p"},"functions")," provided from objects. If you don't know about the ",(0,a.kt)("strong",{parentName:"p"},"functions"),", then you should visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/vba/vba-functions"},"VBA Functions"))," and \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/vba/vba-more-function"},"VBA Functions that do more"))," posts of this blog. These posts will help you to understand what ",(0,a.kt)("strong",{parentName:"p"},"functions")," are and how to use them.")),(0,a.kt)("li",{parentName:"ol"},(0,a.kt)("p",{parentName:"li"},"For creating ",(0,a.kt)("strong",{parentName:"p"},"Centerpoint Arc Slot"),", we use ",(0,a.kt)("inlineCode",{parentName:"p"},"CreateSketchSlot")," function. This function take some input values in form of ",(0,a.kt)("strong",{parentName:"p"},"VBA Constants"),". If you don't know about the ",(0,a.kt)("strong",{parentName:"p"},"VBA Constants"),", then you should visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"/vba/vba-constant"},"VBA Constants"))," post of this blog. This posts will help you to understand what ",(0,a.kt)("strong",{parentName:"p"},"VBA Constants")," are and how to use them."))),(0,a.kt)("hr",null),(0,a.kt)("h2",{id:"solidworks-api-objects"},"Solidworks API Objects"),(0,a.kt)("p",null,"In this post, for creating ",(0,a.kt)("strong",{parentName:"p"},"Centerpoint Arc Slot"),", we use ",(0,a.kt)("em",{parentName:"p"},"Solidworks API objects and their methods"),"."),(0,a.kt)("p",null,"This section contains the list of all ",(0,a.kt)("strong",{parentName:"p"},"Solidworks Objects")," used in this post."),(0,a.kt)("p",null,"I have also attached links of these ",(0,a.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in ",(0,a.kt)("strong",{parentName:"p"},"API Help website"),"."),(0,a.kt)("p",null,"If you want to explore those objects, you can use these links."),(0,a.kt)("p",null,"These Solidworks API Objects are listed below:"),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("strong",{parentName:"li"},"Solidworks Application Object"))),(0,a.kt)("p",null,"If you want explore ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,a.kt)("strong",{parentName:"p"},"Solidworks Application Object")," object you can visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html"},"this link of Solidworks AP Help")),"."),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("strong",{parentName:"li"},"Solidworks Document Object"))),(0,a.kt)("p",null,"If you want explore ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,a.kt)("strong",{parentName:"p"},"Solidworks Document Object")," object you can visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html"},"this link of Solidworks AP Help")),"."),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("strong",{parentName:"li"},"Solidworks Sketch Manager Object"))),(0,a.kt)("p",null,"If you want explore ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of this ",(0,a.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")," you can visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this link of Solidworks AP Help")),"."),(0,a.kt)("ul",null,(0,a.kt)("li",{parentName:"ul"},(0,a.kt)("strong",{parentName:"li"},"Solidworks Sketch Slot Object"))),(0,a.kt)("p",null,"If you want explore ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of this ",(0,a.kt)("strong",{parentName:"p"},"Solidworks Sketch Slot Object")," you can visit \ud83d\ude80 ",(0,a.kt)("strong",{parentName:"p"},(0,a.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSlot_members.html"},"this link of Solidworks AP Help")),"."),(0,a.kt)("hr",null),(0,a.kt)("p",null,"Hope this post helps you to ",(0,a.kt)("em",{parentName:"p"},"create a Centerpoint Arc Slot")," in Sketches with ",(0,a.kt)("strong",{parentName:"p"},"Solidworks VBA Macros"),"."),(0,a.kt)("p",null,"For more such tutorials on ",(0,a.kt)("strong",{parentName:"p"},"Solidworks VBA Macros"),", do come to this blog."),(0,a.kt)("p",null,"Till then, Happy learning!!!"))}c.isMDXComponent=!0},74753:(e,t,n)=>{n.d(t,{Z:()=>a});var o=n(67294);class a extends o.Component{componentDidMount(){(()=>{const e=document.createElement("script");e.src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild)})(),(window.adsbygoogle=window.adsbygoogle||[]).push({})}render(){return o.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})}}},24071:(e,t,n)=>{n.d(t,{Z:()=>o});const o=n.p+"assets/images/centerpoint-arc-slot-parameters-a9ea02a21e1dc4b34c24f9037e1dc30e.png"}}]);