"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[2317],{3905:(e,t,n)=>{n.d(t,{Zo:()=>m,kt:()=>d});var a=n(67294);function o(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function r(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function s(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?r(Object(n),!0).forEach((function(t){o(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function i(e,t){if(null==e)return{};var n,a,o=function(e,t){if(null==e)return{};var n,a,o={},r=Object.keys(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var l=a.createContext({}),p=function(e){var t=a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):s(s({},t),e)),n},m=function(e){var t=p(e.components);return a.createElement(l.Provider,{value:t},e.children)},k={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},c=a.forwardRef((function(e,t){var n=e.components,o=e.mdxType,r=e.originalType,l=e.parentName,m=i(e,["components","mdxType","originalType","parentName"]),c=p(n),d=o,u=c["".concat(l,".").concat(d)]||c[d]||k[d]||r;return n?a.createElement(u,s(s({ref:t},m),{},{components:n})):a.createElement(u,s({ref:t},m))}));function d(e,t){var n=arguments,o=t&&t.mdxType;if("string"==typeof e||o){var r=n.length,s=new Array(r);s[0]=c;var i={};for(var l in t)hasOwnProperty.call(t,l)&&(i[l]=t[l]);i.originalType=e,i.mdxType="string"==typeof e?e:o,s[1]=i;for(var p=2;p<r;p++)s[p]=n[p];return a.createElement.apply(null,s)}return a.createElement.apply(null,n)}c.displayName="MDXCreateElement"},8958:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>p,contentTitle:()=>i,default:()=>c,frontMatter:()=>s,metadata:()=>l,toc:()=>m});var a=n(87462),o=(n(67294),n(3905)),r=n(74753);const s={categories:"Solidworks-macro",title:"Solidworks Macro - Split Open/Closed Sketch Entities",permalink:"/solidworks-macros/split-sketch-segments/",tags:["Solidworks Macro"],id:"split-sketch-segments"},i=void 0,l={unversionedId:"split-sketch-segments",id:"split-sketch-segments",title:"Solidworks Macro - Split Open/Closed Sketch Entities",description:"",source:"@site/docs/solidworks-macros/099.2-split-sketch-segments.md",sourceDirName:".",slug:"/split-sketch-segments",permalink:"/solidworks-macros/split-sketch-segments",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Split Open/Closed Sketch Entities",permalink:"/solidworks-macros/split-sketch-segments/",tags:["Solidworks Macro"],id:"split-sketch-segments"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Convert to Construction Sketch",permalink:"/solidworks-macros/convert-to-construction-sketch-segment"}},p={},m=[{value:"Introduction",id:"introduction",level:2},{value:"CASE 1 : Split Closed Sketch Entities",id:"case-1--split-closed-sketch-entities",level:2},{value:"Understanding Split Closed Sketch Segment the Code",id:"understanding-split-closed-sketch-segment-the-code",level:3},{value:"CASE 2 : Split Open Sketch Entities",id:"case-2--split-open-sketch-entities",level:2},{value:"Understanding Split Open Sketch Segment the Code",id:"understanding-split-open-sketch-segment-the-code",level:3}],k={toc:m};function c(e){let{components:t,...s}=e;return(0,o.kt)("wrapper",(0,a.Z)({},k,s,{components:t,mdxType:"MDXLayout"}),(0,o.kt)("h2",{id:"introduction"},"Introduction"),(0,o.kt)(r.Z,{mdxType:"AdComponent"}),(0,o.kt)("p",null,"In this post, I tell you about ",(0,o.kt)("strong",{parentName:"p"},"how to Split Open/Closed Sketch Entities using Solidworks VBA Macros")," in a Sketch."),(0,o.kt)("p",null,"In this post, I explain about ",(0,o.kt)("inlineCode",{parentName:"p"},"SplitOpenSegment")," and ",(0,o.kt)("inlineCode",{parentName:"p"},"SplitClosedSegment")," method from ",(0,o.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchManager")," object."),(0,o.kt)("p",null,"This method is ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"most updated"))," method, I found in ",(0,o.kt)("em",{parentName:"p"},"Solidworks API Help"),". "),(0,o.kt)("p",null,"So ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"use this method"))," if you want to ",(0,o.kt)("em",{parentName:"p"},"Split Open/Closed Sketch Entities"),"."),(0,o.kt)("hr",null),(0,o.kt)("h2",{id:"case-1--split-closed-sketch-entities"},"CASE 1 : Split Closed Sketch Entities"),(0,o.kt)("p",null,"Below is the ",(0,o.kt)("inlineCode",{parentName:"p"},"code")," sample to ",(0,o.kt)("em",{parentName:"p"},"Split Closed Sketch Entities"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n  \n  '-----------------------UNIT CONVERSION----------------------------------------\n\n  ' Local variables used as Conversion Factors\n  Dim LengthConversionFactor As Double\n  Dim AngleConversionFactor As Double\n  \n  ' Use a Select Case, to get the length of active Unit and set the different factors\n  Select Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n    \n    Case swMETER    ' If length is in Meter\n      LengthConversionFactor = 1\n      AngleConversionFactor = 1\n    \n    Case swMM       ' If length is in MM\n      LengthConversionFactor = 1 / 1000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swCM       ' If length is in CM\n      LengthConversionFactor = 1 / 100\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swINCHES   ' If length is in INCHES\n      LengthConversionFactor = 1 * 0.0254\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEET     ' If length is in FEET\n      LengthConversionFactor = 1 * (0.0254 * 12)\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEETINCHES     ' If length is in FEET & INCHES\n      LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swANGSTROM        ' If length is in ANGSTROM\n      LengthConversionFactor = 1 / 10000000000#\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swNANOMETER       ' If length is in NANOMETER\n      LengthConversionFactor = 1 / 1000000000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swMICRON       ' If length is in MICRON\n      LengthConversionFactor = 1 / 1000000\n      AngleConversionFactor = 1 * 0.01745329\n  End Select\n\n  '----------------------------------------------------------------\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Create a circle of diameter 10\n  Set swSketchSegment = swSketchManager.CreateCircle(0, 0, 0, 10 * LengthConversionFactor, 0, 0)\n  \n  ' Local variant type variable to hold return array of sketch segments\n  Dim swSketchSegmentArray As Variant\n  \n  ' Spliting the circle created and store the return array into local variable\n  swSketchSegmentArray = swSketchManager.SplitClosedSegment(-10 * LengthConversionFactor, 0, 0, 10 * LengthConversionFactor, 0, 0)\n  \n  ' De-select all after creation\n  swDoc.ClearSelection2 True\n  \n  ' Show Front View after Circular Sketch Pattern\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n  \nEnd Sub\n")),(0,o.kt)("hr",null),(0,o.kt)(r.Z,{mdxType:"AdComponent"}),(0,o.kt)("h3",{id:"understanding-split-closed-sketch-segment-the-code"},"Understanding Split Closed Sketch Segment the Code"),(0,o.kt)("p",null,"Now let us walk through ",(0,o.kt)("strong",{parentName:"p"},"each line")," in the above code, and ",(0,o.kt)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"I also give some link so that you can go through them if there are anything I explained in ",(0,o.kt)("strong",{parentName:"p"},"previous posts"),".")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,o.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For more information please visit ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,o.kt)("p",null,"In this line, we create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,o.kt)("p",null,"In this line, we create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,o.kt)("p",null,"In this line, we create a variable named ",(0,o.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,o.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),(0,o.kt)("p",null,"In above line, we create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchManager")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,o.kt)("p",null,"As the name suggested, a ",(0,o.kt)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",(0,o.kt)("em",{parentName:"p"},"Sketches"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2020/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this page of Solidworks API Help"))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n")),(0,o.kt)("p",null,"In this line, we Create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.SketchSegment"),"."),(0,o.kt)("p",null,"We create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Segments"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2020/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"},"this page of Solidworks API Help"))),(0,o.kt)("p",null,"These all are our global variables."),(0,o.kt)("p",null,"As you can see in code sample, they are ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,o.kt)("p",null,"So basically I group all the ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,o.kt)("p",null,"I have also place ",(0,o.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",(0,o.kt)("em",{parentName:"p"},"need")," this variable frequently."),(0,o.kt)("p",null,"Thus, I have started placing it here."),(0,o.kt)("p",null,"Next is our ",(0,o.kt)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",(0,o.kt)("inlineCode",{parentName:"p"},"main"),". "),(0,o.kt)("p",null,"This procedure hold all the ",(0,o.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,o.kt)("p",null,"In this line, we set the value of our Solidworks variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create string type variable for storing default part location\nDim defaultTemplate As String\n' Set value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),(0,o.kt)("p",null,"In 1st statement of above example, we are defining a variable of ",(0,o.kt)("inlineCode",{parentName:"p"},"string")," type and named it as ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),(0,o.kt)("p",null,"This variable ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",(0,o.kt)("strong",{parentName:"p"},"Default Part Template"),"."),(0,o.kt)("p",null,"In 2nd line of above example. we assign value to our newly define ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),(0,o.kt)("p",null,"We assign the value by using a ",(0,o.kt)("em",{parentName:"p"},"Method")," named ",(0,o.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," method is a part of our main Solidworks variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),(0,o.kt)("p",null,"In this line, we set the value of our ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For ",(0,o.kt)("strong",{parentName:"p"},"detailed information")," about these lines please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,o.kt)("p",null,"I have discussed them ",(0,o.kt)("strong",{parentName:"p"},"thoroghly")," in \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post, so do checkout that post if you want to understand above code in more detail."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"'-----------------------UNIT CONVERSION----------------------------------------\n\n' Local variables used as Conversion Factors\nDim LengthConversionFactor As Double\nDim AngleConversionFactor As Double\n\n' Use a Select Case, to get the length of active Unit and set the different factors\nSelect Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n  \n  Case swMETER    ' If length is in Meter\n    LengthConversionFactor = 1\n    AngleConversionFactor = 1\n  \n  Case swMM       ' If length is in MM\n    LengthConversionFactor = 1 / 1000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swCM       ' If length is in CM\n    LengthConversionFactor = 1 / 100\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swINCHES   ' If length is in INCHES\n    LengthConversionFactor = 1 * 0.0254\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEET     ' If length is in FEET\n    LengthConversionFactor = 1 * (0.0254 * 12)\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEETINCHES     ' If length is in FEET & INCHES\n    LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swANGSTROM        ' If length is in ANGSTROM\n    LengthConversionFactor = 1 / 10000000000#\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swNANOMETER       ' If length is in NANOMETER\n    LengthConversionFactor = 1 / 1000000000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swMICRON       ' If length is in MICRON\n    LengthConversionFactor = 1 / 1000000\n    AngleConversionFactor = 1 * 0.01745329\nEnd Select\n\n'----------------------------------------------------------------\n")),(0,o.kt)("p",null,"Above code sample shows how to ",(0,o.kt)("strong",{parentName:"p"},"fix Solidworks API Unit issue"),". "),(0,o.kt)("p",null,"We ",(0,o.kt)("em",{parentName:"p"},"1st")," get the ",(0,o.kt)("em",{parentName:"p"},"current unit")," of the part and apply the ",(0,o.kt)("em",{parentName:"p"},"switch")," statements to update our ",(0,o.kt)("em",{parentName:"p"},"Length and Angle Conversion factors"),". "),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"I have already explained in detail about ",(0,o.kt)("strong",{parentName:"p"},"Fixing Solidworks API Unit Issue")," in \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/unit-correction"},"General - Fix Unit Issue"))," blog post. ")),(0,o.kt)("p",null,"Do checkout above post for Fixing Solidworks API Issue."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line, we select the ",(0,o.kt)("em",{parentName:"p"},"front plane")," by using ",(0,o.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,o.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For more information about selection method please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),(0,o.kt)("p",null,"In above line, we set the ",(0,o.kt)("em",{parentName:"p"},"Sketch manager")," variable to ",(0,o.kt)("em",{parentName:"p"},"current document's sketch manager"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Insert a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,o.kt)("p",null,"In above line, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,o.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,o.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,o.kt)("p",null,"This method allows us to insert a sketch in selected plane."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create a circle of diameter 10\nSet swSketchSegment = swSketchManager.CreateCircle(0, 0, 0, 10 * LengthConversionFactor, 0, 0)\n")),(0,o.kt)("p",null,"In above line, we set the value of Solidworks Sketch Segment variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," by ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateCircle")," method from ",(0,o.kt)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateCircle")," method creates ",(0,o.kt)("em",{parentName:"p"},"a Circle"),' between "2 given point distance as diameter".'),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For more information about ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateCircle")," method, you can read my \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-circle"},"Solidworks Macro - Create Circle"))," post.")),(0,o.kt)("p",null,"That post describe all the parameters we need for this ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateCircle")," method in details."),(0,o.kt)("p",null,"In above line, we create a Circle with:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Circle Centerpoint")," : At origin i.e. ",(0,o.kt)("em",{parentName:"p"},"(0, 0, 0)"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Circle Diameter")," : ",(0,o.kt)("strong",{parentName:"p"},"10")," unit length"))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Local variant type variable to hold return array of sketch segments\nDim swSketchSegmentArray As Variant\n")),(0,o.kt)("p",null,"In above line of code, we create a ",(0,o.kt)("inlineCode",{parentName:"p"},"variant")," type variable to hold return array of ",(0,o.kt)("em",{parentName:"p"},"sketch segments"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Spliting the circle created and store the return array into local variable\nswSketchSegmentArray = swSketchManager.SplitClosedSegment(-10 * LengthConversionFactor, 0, 0, 10 * LengthConversionFactor, 0, 0)\n")),(0,o.kt)("p",null,'For "',(0,o.kt)("strong",{parentName:"p"},"Spliting"),'" an ',(0,o.kt)("em",{parentName:"p"},"closed")," sketch entity, we need ",(0,o.kt)("inlineCode",{parentName:"p"},"SplitClosedSegment")," method from ",(0,o.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchManager")," object."),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"SplitClosedSegment")," method takes following parameters as explained:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"X1")," : ",(0,o.kt)("em",{parentName:"p"},"X coordinate of first point."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Y1")," : ",(0,o.kt)("em",{parentName:"p"},"y coordinate of first point."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Z1")," : ",(0,o.kt)("em",{parentName:"p"},"z coordinate of first point."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"X2")," : ",(0,o.kt)("em",{parentName:"p"},"X coordinate of second point."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Y2")," : ",(0,o.kt)("em",{parentName:"p"},"Y coordinate of second point."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Z2")," : ",(0,o.kt)("em",{parentName:"p"},"Z coordinate of second point.")))),(0,o.kt)("p",null,"After the function complete following are the results:"),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Return Value"),":"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("strong",{parentName:"li"},"Array Sketch Segments"),": ",(0,o.kt)("em",{parentName:"li"},"Array of sketch segments of the now split formerly closed sketch skegment."))),(0,o.kt)("p",null,"In our code, I have used following values:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"X1")," : ",(0,o.kt)("em",{parentName:"p"},"X coordinate of first point = `-10 ")," LengthConversionFactor`.*")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Y1")," : ",(0,o.kt)("em",{parentName:"p"},"y coordinate of first point = ",(0,o.kt)("inlineCode",{parentName:"em"},"0"),"."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Z1")," : ",(0,o.kt)("em",{parentName:"p"},"z coordinate of first point = ",(0,o.kt)("inlineCode",{parentName:"em"},"0"),"."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"X2")," : ",(0,o.kt)("em",{parentName:"p"},"X coordinate of second point = `10 ")," LengthConversionFactor`.*")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Y2")," : ",(0,o.kt)("em",{parentName:"p"},"Y coordinate of second point = ",(0,o.kt)("inlineCode",{parentName:"em"},"0"),"."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Z2")," : ",(0,o.kt)("em",{parentName:"p"},"Z coordinate of second point = ",(0,o.kt)("inlineCode",{parentName:"em"},"0"),".")))),(0,o.kt)("p",null,"Below image shows before and after Circular Sketch Pattern."),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Before Circular Sketch Pattern")),(0,o.kt)("p",null,(0,o.kt)("img",{alt:"close-segment-before-split",src:n(56594).Z,width:"1126",height:"561"})),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"After Circular Sketch Pattern")),(0,o.kt)("p",null,(0,o.kt)("img",{alt:"close-segment-after-split",src:n(37363).Z,width:"1126",height:"559"})),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Sketch after creation\nswDoc.ClearSelection2 True\n")),(0,o.kt)("p",null,"In the above line of code, we deselect the ",(0,o.kt)("strong",{parentName:"p"},"Sketch")," after the ",(0,o.kt)("em",{parentName:"p"},"Linear Sketch Pattern")," operation."),(0,o.kt)("p",null,"For de-selecting, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Show Front View after Linear Sketch Pattern\nswDoc.ShowNamedView2 "", swStandardViews_e.swFrontView\n')),(0,o.kt)("p",null,"In the above line of code, we update the ",(0,o.kt)("em",{parentName:"p"},"view orientation")," to ",(0,o.kt)("strong",{parentName:"p"},"Front View"),"."),(0,o.kt)("p",null,"In my machine, after inserting a sketch view orientation does not changed."),(0,o.kt)("p",null,"Because of this I have to update the view to ",(0,o.kt)("strong",{parentName:"p"},"Front view"),"."),(0,o.kt)("p",null,"For showing ",(0,o.kt)("strong",{parentName:"p"},"Front View")," we used ",(0,o.kt)("inlineCode",{parentName:"p"},"ShowNamedView2")," method from our Solidworks document name ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("p",null,"This method takes 2 parameter described as follows:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"VName")," : Name of the view to display or an empty string to use ViewId instead")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"ViewId")," : ID of the view to display as defined by ",(0,o.kt)("inlineCode",{parentName:"p"},"swStandardViews_e")," or -1 to use the ",(0,o.kt)("strong",{parentName:"p"},"VName")," argument instead."))),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"NOTE:")," If you specify both ",(0,o.kt)("strong",{parentName:"p"},"VName")," and ",(0,o.kt)("strong",{parentName:"p"},"ViewId"),", then ",(0,o.kt)("strong",{parentName:"p"},"ViewId")," takes precedence if the two arguments do not resolve to the same view."),(0,o.kt)("p",null,(0,o.kt)("inlineCode",{parentName:"p"},"swStandardViews_e")," has following Standard View Types:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swBackView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swBottomView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swDimetricView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swFrontView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swIsometricView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swLeftView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swRightView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swTopView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swExtendetricView")))),(0,o.kt)("p",null,"In our code, we did not use ",(0,o.kt)("strong",{parentName:"p"},"VName")," instead I used ",(0,o.kt)("em",{parentName:"p"},"empty string")," in form of ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},'""'))," symbol."),(0,o.kt)("p",null,"I used ",(0,o.kt)("strong",{parentName:"p"},"ViewId")," value to specify view and used ",(0,o.kt)("inlineCode",{parentName:"p"},"swStandardViews_e.swFrontView")," value to use ",(0,o.kt)("em",{parentName:"p"},"Standard Front View"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),(0,o.kt)("p",null,"In this last line we use ",(0,o.kt)("em",{parentName:"p"},"zoom to fit")," command."),(0,o.kt)("p",null,"For Zoom to fit, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("hr",null),(0,o.kt)("h2",{id:"case-2--split-open-sketch-entities"},"CASE 2 : Split Open Sketch Entities"),(0,o.kt)("p",null,"Below is the ",(0,o.kt)("inlineCode",{parentName:"p"},"code")," sample to ",(0,o.kt)("em",{parentName:"p"},"Split Open Sketch Entities"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n  \n  '-----------------------UNIT CONVERSION----------------------------------------\n\n  ' Local variables used as Conversion Factors\n  Dim LengthConversionFactor As Double\n  Dim AngleConversionFactor As Double\n  \n  ' Use a Select Case, to get the length of active Unit and set the different factors\n  Select Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n    \n    Case swMETER    ' If length is in Meter\n      LengthConversionFactor = 1\n      AngleConversionFactor = 1\n    \n    Case swMM       ' If length is in MM\n      LengthConversionFactor = 1 / 1000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swCM       ' If length is in CM\n      LengthConversionFactor = 1 / 100\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swINCHES   ' If length is in INCHES\n      LengthConversionFactor = 1 * 0.0254\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEET     ' If length is in FEET\n      LengthConversionFactor = 1 * (0.0254 * 12)\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEETINCHES     ' If length is in FEET & INCHES\n      LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swANGSTROM        ' If length is in ANGSTROM\n      LengthConversionFactor = 1 / 10000000000#\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swNANOMETER       ' If length is in NANOMETER\n      LengthConversionFactor = 1 / 1000000000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swMICRON       ' If length is in MICRON\n      LengthConversionFactor = 1 / 1000000\n      AngleConversionFactor = 1 * 0.01745329\n  End Select\n\n  '----------------------------------------------------------------\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Create a line of distance 10\n  Set swSketchSegment = swSketchManager.CreateLine(0, 0, 0, 10 * LengthConversionFactor, 0, 0)\n  \n  ' Local variant type variable to hold return array of sketch segments\n  Dim swSketchSegmentArray As Variant\n  \n  ' Spliting the line at distance of 5 and store the return array into local variable\n  swSketchSegmentArray = swSketchManager.SplitOpenSegment(5 * LengthConversionFactor, 0, 0)\n  \n  ' De-select all after creation\n  swDoc.ClearSelection2 True\n  \n  ' Show Front View after Circular Sketch Pattern\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n  \nEnd Sub\n")),(0,o.kt)("hr",null),(0,o.kt)(r.Z,{mdxType:"AdComponent"}),(0,o.kt)("h3",{id:"understanding-split-open-sketch-segment-the-code"},"Understanding Split Open Sketch Segment the Code"),(0,o.kt)("p",null,"Now let us walk through ",(0,o.kt)("strong",{parentName:"p"},"each line")," in the above code, and ",(0,o.kt)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),(0,o.kt)("p",null,"I also give some link so that you can go through them if there are anything I explained in ",(0,o.kt)("strong",{parentName:"p"},"previous posts"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,o.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For more information please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,o.kt)("p",null,"In this line, we create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,o.kt)("p",null,"In this line, we create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,o.kt)("p",null,"In this line, we create a variable named ",(0,o.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,o.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),(0,o.kt)("p",null,"In above line, we create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchManager")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,o.kt)("p",null,"As the name suggested, a ",(0,o.kt)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",(0,o.kt)("em",{parentName:"p"},"Sketches"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2020/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this page of Solidworks API Help"))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n")),(0,o.kt)("p",null,"In this line, we Create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.SketchSegment"),"."),(0,o.kt)("p",null,"We create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Segments"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2020/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"},"this page of Solidworks API Help"))),(0,o.kt)("p",null,"These all are our global variables."),(0,o.kt)("p",null,"As you can see in code sample, they are ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,o.kt)("p",null,"So basically I group all the ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,o.kt)("p",null,"I have also place ",(0,o.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",(0,o.kt)("em",{parentName:"p"},"need")," this variable frequently."),(0,o.kt)("p",null,"Thus, I have started placing it here."),(0,o.kt)("p",null,"Next is our ",(0,o.kt)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",(0,o.kt)("inlineCode",{parentName:"p"},"main"),". "),(0,o.kt)("p",null,"This procedure hold all the ",(0,o.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,o.kt)("p",null,"In this line, we set the value of our Solidworks variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create string type variable for storing default part location\nDim defaultTemplate As String\n' Set value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),(0,o.kt)("p",null,"In 1st statement of above example, we are defining a variable of ",(0,o.kt)("inlineCode",{parentName:"p"},"string")," type and named it as ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),(0,o.kt)("p",null,"This variable ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",(0,o.kt)("strong",{parentName:"p"},"Default Part Template"),"."),(0,o.kt)("p",null,"In 2nd line of above example. we assign value to our newly define ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),(0,o.kt)("p",null,"We assign the value by using a ",(0,o.kt)("em",{parentName:"p"},"Method")," named ",(0,o.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," method is a part of our main Solidworks variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),(0,o.kt)("p",null,"In this line, we set the value of our ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For ",(0,o.kt)("strong",{parentName:"p"},"detailed information")," about these lines please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,o.kt)("p",null,"I have discussed them ",(0,o.kt)("strong",{parentName:"p"},"thoroghly")," in \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post, so do checkout that post if you want to understand above code in more detail."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"'-----------------------UNIT CONVERSION----------------------------------------\n\n' Local variables used as Conversion Factors\nDim LengthConversionFactor As Double\nDim AngleConversionFactor As Double\n\n' Use a Select Case, to get the length of active Unit and set the different factors\nSelect Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n  \n  Case swMETER    ' If length is in Meter\n    LengthConversionFactor = 1\n    AngleConversionFactor = 1\n  \n  Case swMM       ' If length is in MM\n    LengthConversionFactor = 1 / 1000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swCM       ' If length is in CM\n    LengthConversionFactor = 1 / 100\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swINCHES   ' If length is in INCHES\n    LengthConversionFactor = 1 * 0.0254\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEET     ' If length is in FEET\n    LengthConversionFactor = 1 * (0.0254 * 12)\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEETINCHES     ' If length is in FEET & INCHES\n    LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swANGSTROM        ' If length is in ANGSTROM\n    LengthConversionFactor = 1 / 10000000000#\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swNANOMETER       ' If length is in NANOMETER\n    LengthConversionFactor = 1 / 1000000000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swMICRON       ' If length is in MICRON\n    LengthConversionFactor = 1 / 1000000\n    AngleConversionFactor = 1 * 0.01745329\nEnd Select\n\n'----------------------------------------------------------------\n")),(0,o.kt)("p",null,"Above code sample shows how to ",(0,o.kt)("strong",{parentName:"p"},"fix Solidworks API Unit issue"),". "),(0,o.kt)("p",null,"We ",(0,o.kt)("em",{parentName:"p"},"1st")," get the ",(0,o.kt)("em",{parentName:"p"},"current unit")," of the part and apply the ",(0,o.kt)("em",{parentName:"p"},"switch")," statements to update our ",(0,o.kt)("em",{parentName:"p"},"Length and Angle Conversion factors"),". "),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"I have already explained in detail about ",(0,o.kt)("strong",{parentName:"p"},"Fixing Solidworks API Unit Issue")," in \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/unit-correction"},"General - Fix Unit Issue"))," blog post. ")),(0,o.kt)("p",null,"Do checkout above post for Fixing Solidworks API Issue."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line, we select the ",(0,o.kt)("em",{parentName:"p"},"front plane")," by using ",(0,o.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,o.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For more information about selection method please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),(0,o.kt)("p",null,"In above line, we set the ",(0,o.kt)("em",{parentName:"p"},"Sketch manager")," variable to ",(0,o.kt)("em",{parentName:"p"},"current document's sketch manager"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Insert a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,o.kt)("p",null,"In above line, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,o.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,o.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,o.kt)("p",null,"This method allows us to insert a sketch in selected plane."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create a line of distance 10\nSet swSketchSegment = swSketchManager.CreateLine(0, 0, 0, 10 * LengthConversionFactor, 0, 0)\n")),(0,o.kt)("p",null,"In above line, we set the value of Solidworks Sketch Segment variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," by ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateLine")," method from ",(0,o.kt)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateLine")," method creates ",(0,o.kt)("em",{parentName:"p"},"a line"),' between "2 given point".'),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For more information about ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateLine")," method, you can read my \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/sketch-create-line"},"Solidworks Sketch Macro - Create Line"))," post.")),(0,o.kt)("p",null,"That post describe all the parameters we need for this ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateLine")," method in details."),(0,o.kt)("p",null,"In above line, we create a line of 10 unit in X-direction."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Local variant type variable to hold return array of sketch segments\nDim swSketchSegmentArray As Variant\n")),(0,o.kt)("p",null,"In above line of code, we create a ",(0,o.kt)("inlineCode",{parentName:"p"},"variant")," type variable to hold return array of ",(0,o.kt)("em",{parentName:"p"},"sketch segments"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Spliting the line at distance of 5 and store the return array into local variable\nswSketchSegmentArray = swSketchManager.SplitOpenSegment(5 * LengthConversionFactor, 0, 0)\n")),(0,o.kt)("p",null,'For "',(0,o.kt)("strong",{parentName:"p"},"Spliting"),'" an ',(0,o.kt)("em",{parentName:"p"},"closed")," sketch entity, we need ",(0,o.kt)("inlineCode",{parentName:"p"},"SplitOpenSegment")," method from ",(0,o.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchManager")," object."),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"SplitOpenSegment")," method takes following parameters as explained:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"X")," : ",(0,o.kt)("em",{parentName:"p"},"X coordinate of the point that splits the sketch segment in two."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Y")," : ",(0,o.kt)("em",{parentName:"p"},"y coordinate of the point that splits the sketch segment in two."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Z")," : ",(0,o.kt)("em",{parentName:"p"},"z coordinate of the point that splits the sketch segment in two.")))),(0,o.kt)("p",null,"After the function complete following are the results:"),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Return Value"),":"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("strong",{parentName:"li"},"Array Sketch Segments"),": ",(0,o.kt)("em",{parentName:"li"},"Array of sketch segments of the now split formerly closed sketch skegment."))),(0,o.kt)("p",null,"In our code, I have used following values:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"X")," : ",(0,o.kt)("em",{parentName:"p"},"X coordinate of the point that splits the sketch segment in two = `5 ")," LengthConversionFactor`.*")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Y")," : ",(0,o.kt)("em",{parentName:"p"},"y coordinate of the point that splits the sketch segment in twot = ",(0,o.kt)("inlineCode",{parentName:"em"},"0"),"."))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Z")," : ",(0,o.kt)("em",{parentName:"p"},"z coordinate of the point that splits the sketch segment in two = ",(0,o.kt)("inlineCode",{parentName:"em"},"0"),".")))),(0,o.kt)("p",null,"Below image shows before and after Circular Sketch Pattern."),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Before Circular Sketch Pattern")),(0,o.kt)("p",null,(0,o.kt)("a",{target:"_blank",href:n(87435).Z},(0,o.kt)("img",{alt:"open-segment-before-split",src:n(9723).Z,width:"1124",height:"556"}))),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"After Circular Sketch Pattern")),(0,o.kt)("p",null,(0,o.kt)("a",{target:"_blank",href:n(99502).Z},(0,o.kt)("img",{alt:"open-segment-after-split",src:n(2863).Z,width:"1126",height:"557"}))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Sketch after creation\nswDoc.ClearSelection2 True\n")),(0,o.kt)("p",null,"In the above line of code, we deselect the ",(0,o.kt)("strong",{parentName:"p"},"Sketch")," after the ",(0,o.kt)("em",{parentName:"p"},"Linear Sketch Pattern")," operation."),(0,o.kt)("p",null,"For de-selecting, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Show Front View after Linear Sketch Pattern\nswDoc.ShowNamedView2 "", swStandardViews_e.swFrontView\n')),(0,o.kt)("p",null,"In the above line of code, we update the ",(0,o.kt)("em",{parentName:"p"},"view orientation")," to ",(0,o.kt)("strong",{parentName:"p"},"Front View"),"."),(0,o.kt)("p",null,"In my machine, after inserting a sketch view orientation does not changed."),(0,o.kt)("p",null,"Because of this I have to update the view to ",(0,o.kt)("strong",{parentName:"p"},"Front view"),"."),(0,o.kt)("p",null,"For showing ",(0,o.kt)("strong",{parentName:"p"},"Front View")," we used ",(0,o.kt)("inlineCode",{parentName:"p"},"ShowNamedView2")," method from our Solidworks document name ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("p",null,"This method takes 2 parameter described as follows:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"VName")," : Name of the view to display or an empty string to use ViewId instead")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"ViewId")," : ID of the view to display as defined by ",(0,o.kt)("inlineCode",{parentName:"p"},"swStandardViews_e")," or -1 to use the ",(0,o.kt)("strong",{parentName:"p"},"VName")," argument instead."))),(0,o.kt)("admonition",{type:"info"},(0,o.kt)("p",{parentName:"admonition"},"If you specify both ",(0,o.kt)("strong",{parentName:"p"},"VName")," and ",(0,o.kt)("strong",{parentName:"p"},"ViewId"),", then ",(0,o.kt)("strong",{parentName:"p"},"ViewId")," takes precedence if the two arguments do not resolve to the same view.")),(0,o.kt)("p",null,(0,o.kt)("inlineCode",{parentName:"p"},"swStandardViews_e")," has following Standard View Types:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swBackView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swBottomView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swDimetricView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swFrontView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swIsometricView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swLeftView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swRightView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swTopView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swExtendetricView")))),(0,o.kt)("p",null,"In our code, we did not use ",(0,o.kt)("strong",{parentName:"p"},"VName")," instead I used ",(0,o.kt)("em",{parentName:"p"},"empty string")," in form of ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},'""'))," symbol."),(0,o.kt)("p",null,"I used ",(0,o.kt)("strong",{parentName:"p"},"ViewId")," value to specify view and used ",(0,o.kt)("inlineCode",{parentName:"p"},"swStandardViews_e.swFrontView")," value to use ",(0,o.kt)("em",{parentName:"p"},"Standard Front View"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),(0,o.kt)("p",null,"In this last line we use ",(0,o.kt)("em",{parentName:"p"},"zoom to fit")," command."),(0,o.kt)("p",null,"For Zoom to fit, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("hr",null),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"This is it !!!")),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"I hope my efforts will helpful to someone!")),(0,o.kt)("p",null,"If you found anything to ",(0,o.kt)("strong",{parentName:"p"},"add or update"),", please let me know on my ",(0,o.kt)("em",{parentName:"p"},"e-mail"),"."),(0,o.kt)("p",null,"Hope this post helps you to ",(0,o.kt)("em",{parentName:"p"},"Split Open/Closed Sketch Entities")," with Solidworks VBA Macros."),(0,o.kt)("p",null,"For more such tutorials on ",(0,o.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Do let me know by you like this post or not!")),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Till then, Happy learning!!!")))}c.isMDXComponent=!0},74753:(e,t,n)=>{n.d(t,{Z:()=>o});var a=n(67294);class o extends a.Component{componentDidMount(){(()=>{const e=document.createElement("script");e.src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild)})(),(window.adsbygoogle=window.adsbygoogle||[]).push({})}render(){return a.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})}}},99502:(e,t,n)=>{n.d(t,{Z:()=>a});const a=n.p+"assets/files/open-segment-after-split-27334df3f16adfeacb3ce1246b423268.png"},87435:(e,t,n)=>{n.d(t,{Z:()=>a});const a=n.p+"assets/files/open-segment-before-split-40fa1fa0d6f1792584220492df7a4096.png"},37363:(e,t,n)=>{n.d(t,{Z:()=>a});const a=n.p+"assets/images/close-segment-after-split-37de0bbbb2a9f9e77703a239b5c24b01.png"},56594:(e,t,n)=>{n.d(t,{Z:()=>a});const a=n.p+"assets/images/close-segment-before-split-85174d6e41f8f69cb1459690aabfdba2.png"},2863:(e,t,n)=>{n.d(t,{Z:()=>a});const a=n.p+"assets/images/open-segment-after-split-27334df3f16adfeacb3ce1246b423268.png"},9723:(e,t,n)=>{n.d(t,{Z:()=>a});const a=n.p+"assets/images/open-segment-before-split-40fa1fa0d6f1792584220492df7a4096.png"}}]);