"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[5538],{3905:function(e,t,n){n.d(t,{Zo:function(){return m},kt:function(){return c}});var a=n(67294);function o(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function r(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function s(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?r(Object(n),!0).forEach((function(t){o(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function i(e,t){if(null==e)return{};var n,a,o=function(e,t){if(null==e)return{};var n,a,o={},r=Object.keys(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var l=a.createContext({}),p=function(e){var t=a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):s(s({},t),e)),n},m=function(e){var t=p(e.components);return a.createElement(l.Provider,{value:t},e.children)},k={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},d=a.forwardRef((function(e,t){var n=e.components,o=e.mdxType,r=e.originalType,l=e.parentName,m=i(e,["components","mdxType","originalType","parentName"]),d=p(n),c=o,u=d["".concat(l,".").concat(c)]||d[c]||k[c]||r;return n?a.createElement(u,s(s({ref:t},m),{},{components:n})):a.createElement(u,s({ref:t},m))}));function c(e,t){var n=arguments,o=t&&t.mdxType;if("string"==typeof e||o){var r=n.length,s=new Array(r);s[0]=d;var i={};for(var l in t)hasOwnProperty.call(t,l)&&(i[l]=t[l]);i.originalType=e,i.mdxType="string"==typeof e?e:o,s[1]=i;for(var p=2;p<r;p++)s[p]=n[p];return a.createElement.apply(null,s)}return a.createElement.apply(null,n)}d.displayName="MDXCreateElement"},96125:function(e,t,n){n.r(t),n.d(t,{assets:function(){return m},contentTitle:function(){return l},default:function(){return c},frontMatter:function(){return i},metadata:function(){return p},toc:function(){return k}});var a=n(87462),o=n(63366),r=(n(67294),n(3905)),s=["components"],i={categories:"Solidworks-macro",title:"Solidworks Macro - Extend Sketch Entities",permalink:"/solidworks-macros/extend-entities/",tags:["Solidworks Macro"],id:"extend-entities"},l=void 0,p={unversionedId:"extend-entities",id:"extend-entities",title:"Solidworks Macro - Extend Sketch Entities",description:"In this post, I tell you about how to Extend Sketch Entities using Solidworks VBA Macros in a Sketch.",source:"@site/docs/solidworks-macros/009.2-extend-entities.md",sourceDirName:".",slug:"/extend-entities",permalink:"/solidworks-macros/extend-entities",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Extend Sketch Entities",permalink:"/solidworks-macros/extend-entities/",tags:["Solidworks Macro"],id:"extend-entities"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Trim Sketch Entities",permalink:"/solidworks-macros/trim-entities"},next:{title:"Solidworks Macro - Offset Sketch Entities",permalink:"/solidworks-macros/offset-entities"}},m={},k=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"For Experience Macro Developer",id:"for-experience-macro-developer",level:2},{value:"For Beginners Macro Developers",id:"for-beginners-macro-developers",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:3},{value:"VBA Language feature used in this post",id:"vba-language-feature-used-in-this-post",level:2},{value:"Solidworks API Objects",id:"solidworks-api-objects",level:2}],d={toc:k};function c(e){var t=e.components,i=(0,o.Z)(e,s);return(0,r.kt)("wrapper",(0,a.Z)({},d,i,{components:t,mdxType:"MDXLayout"}),(0,r.kt)("p",null,"In this post, I tell you about ",(0,r.kt)("em",{parentName:"p"},"how to Extend Sketch Entities using Solidworks VBA Macros")," in a Sketch."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,r.kt)("p",null,"Please see below video \ud83c\udfac how visually we ",(0,r.kt)("em",{parentName:"p"},"Extend Sketch Entities")," in ",(0,r.kt)("strong",{parentName:"p"},"Solidworks VBA macro"),"."),(0,r.kt)("iframe",{src:"https://www.youtube.com/embed/tINYT057tFM",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,r.kt)("p",null,"Please note that there are ",(0,r.kt)("strong",{parentName:"p"},"no explaination")," given in the video. "),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"for-experience-macro-developer"},"For Experience Macro Developer"),(0,r.kt)("p",null,"If you are an experience ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Macro developer"),", then you are looking for a specific code sample."),(0,r.kt)("p",null,"Below is the code for ",(0,r.kt)("strong",{parentName:"p"},"Extend Sketch Entities")," from ",(0,r.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Boolean Variable\nDim BoolStatus As Boolean\n\n\' Select Line 1\nBoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n\' Extend Solidworks Sketch segment by "SketchExtend" method from Solidworks sketch manager\nBoolStatus = swSketchManager.SketchExtend(0, 0, 0)\n')),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Method Name"),": ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchExtend"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Description"),": Add lengths to the selected Sketch Entity till next sketch entity."))),(0,r.kt)("p",null,"For ",(0,r.kt)("strong",{parentName:"p"},"Extend")," Solidworks Sketch segment, first you need to ",(0,r.kt)("strong",{parentName:"p"},"Create")," a variable of ",(0,r.kt)("inlineCode",{parentName:"p"},"Boolean")," type."),(0,r.kt)("p",null,"After creating variable, you need to set the value of this ",(0,r.kt)("inlineCode",{parentName:"p"},"Boolean")," variable."),(0,r.kt)("p",null,"For this you used ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchExtend")," method from ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchExtend")," method set the value of ",(0,r.kt)("inlineCode",{parentName:"p"},"Boolean")," type variable."),(0,r.kt)("p",null,"If Extend is ",(0,r.kt)("strong",{parentName:"p"},"successful")," then ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchExtend")," method return ",(0,r.kt)("strong",{parentName:"p"},"True")," otherwise ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchExtend")," returns ",(0,r.kt)("strong",{parentName:"p"},"False"),"."),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchExtend")," method takes following parameters as explained:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"X")," : ",(0,r.kt)("em",{parentName:"p"},"Not used"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Y")," : ",(0,r.kt)("em",{parentName:"p"},"Not used"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Z")," : ",(0,r.kt)("em",{parentName:"p"},"Not used")))),(0,r.kt)("p",null,"If you want a more detail explaination then please read further otherwise this will help you to ",(0,r.kt)("strong",{parentName:"p"},"Extend Sketch Entities From VBA Macro"),"."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"for-beginners-macro-developers"},"For Beginners Macro Developers"),(0,r.kt)("p",null,"In this post, I tell you about ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchExtend")," method from ",(0,r.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchManager")," object."),(0,r.kt)("p",null,"This method is ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"most updated"))," method, I found in ",(0,r.kt)("em",{parentName:"p"},"Solidworks API Help"),". "),(0,r.kt)("p",null,"So ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"use this method"))," if you want to ",(0,r.kt)("em",{parentName:"p"},"Extend Sketces"),".."),(0,r.kt)("p",null,"Below is the ",(0,r.kt)("inlineCode",{parentName:"p"},"code")," sample for ",(0,r.kt)("em",{parentName:"p"},"Extend Sketces"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Set Sketch Segment value and Create Line 1\n  Set swSketchSegment = swSketchManager.CreateLine(-0.5, 0.75, 0, -0.25, -0.5, 0)\n  \n  ' Set Sketch Segment value and Create Line 2\n  Set swSketchSegment = swSketchManager.CreateLine(-0.75, -1.25, 0, 0.5, -1.25, 0)\n  \n  ' De-select the lines after creation\n  swDoc.ClearSelection2 True\n  \n  ' Select Line 1\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line1\", \"SKETCHSEGMENT\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Extend selected Sketch Segments by \"SketchExtend\" method from Solidworks sketch manager\n  BoolStatus = swSketchManager.SketchExtend(0.0, 0.0, 0.0)\n\n  ' De-select the Sketch Segment after Extend\n  swDoc.ClearSelection2 True\n  \n  ' Show Front View after Extend Sketch Segments\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n\nEnd Sub\n")),(0,r.kt)("hr",null),(0,r.kt)("h3",{id:"understanding-the-code"},"Understanding the Code"),(0,r.kt)("p",null,"Now let us walk through ",(0,r.kt)("em",{parentName:"p"},"each line")," in the above code, and ",(0,r.kt)("strong",{parentName:"p"},"understand")," the meaning of every line."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,r.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,r.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"For more information please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,r.kt)("p",null,"In this line, we create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,r.kt)("p",null,"In this line, we create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,r.kt)("p",null,"In this line, we create a variable named ",(0,r.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,r.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),(0,r.kt)("p",null,"In above line, we create variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swSketchManager")," for ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,r.kt)("p",null,"As the name suggested, a ",(0,r.kt)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",(0,r.kt)("em",{parentName:"p"},"Sketches"),"."),(0,r.kt)("p",null,"To see methods and properties related to ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this page of Solidworks API Help"))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n")),(0,r.kt)("p",null,"In this line, we Create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.SketchSegment"),"."),(0,r.kt)("p",null,"We create variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," for ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Sketch Segments"),"."),(0,r.kt)("p",null,"To see methods and properties related to ",(0,r.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," object, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"},"this page of Solidworks API Help"))),(0,r.kt)("p",null,"These all are our global variables."),(0,r.kt)("p",null,"As you can see in code sample, they are ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,r.kt)("p",null,"So basically I group all the ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,r.kt)("p",null,"I have also place ",(0,r.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",(0,r.kt)("em",{parentName:"p"},"need")," this variable frequently."),(0,r.kt)("p",null,"Thus, I have started placing it here."),(0,r.kt)("p",null,"Next is our ",(0,r.kt)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",(0,r.kt)("inlineCode",{parentName:"p"},"main"),". "),(0,r.kt)("p",null,"This procedure hold all the ",(0,r.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,r.kt)("p",null,"In this line, we are setting the value of our Solidworks variable which we define earlier to Solidworks application."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create string type variable for storing default part location\nDim defaultTemplate As String\n' Set value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),(0,r.kt)("p",null,"In 1st statement of above example, we are defining a variable of ",(0,r.kt)("inlineCode",{parentName:"p"},"string")," type and named it as ",(0,r.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),(0,r.kt)("p",null,"This variable ",(0,r.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",(0,r.kt)("strong",{parentName:"p"},"Default Part Template"),"."),(0,r.kt)("p",null,"In 2nd line of above example. we assign value to our newly define ",(0,r.kt)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),(0,r.kt)("p",null,"We assign the value by using a ",(0,r.kt)("em",{parentName:"p"},"Method")," named ",(0,r.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," method is a part of our main Solidworks variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),(0,r.kt)("p",null,"In this line, we set the value of our ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),(0,r.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"For ",(0,r.kt)("strong",{parentName:"p"},"detailed information")," about these lines please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."),(0,r.kt)("p",{parentName:"div"},"I have discussed them ",(0,r.kt)("strong",{parentName:"p"},"thoroghly")," in \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post, so do checkout this post if you don't understand above code."))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,r.kt)("p",null,"In above line, we select the ",(0,r.kt)("em",{parentName:"p"},"front plane")," by using ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,r.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,r.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"For more information about selection method please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),(0,r.kt)("p",null,"In above line, we set the sketch manager variable to current document's sketch manager."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Insert a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,r.kt)("p",null,"In above line, we use ",(0,r.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,r.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,r.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,r.kt)("p",null,"This method allows us to insert a sketch in selected plane."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch Segment value and Create Line 1\nSet swSketchSegment = swSketchManager.CreateLine(-0.5, 0.75, 0, -0.25, -0.5, 0)\n")),(0,r.kt)("p",null,"In above line, we set the value of Solidworks Sketch Segment variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," by ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateLine")," method from ",(0,r.kt)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateLine")," method creates Lines between 2 given points."),(0,r.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"For more information about ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateLine")," method, you can read my \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/sketch-create-line"},"Solidworks Sketch Macros - Create Line"))," post."))),(0,r.kt)("p",null,"This post describe all the parameters we need for this ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateLine")," method."),(0,r.kt)("p",null,"In above line, we create a Line between ",(0,r.kt)("strong",{parentName:"p"},"point (-0.5, 0.75, 0)")," and ",(0,r.kt)("strong",{parentName:"p"},"point (-0.25, -0.5, 0)"),"."),(0,r.kt)("p",null,"This line is ",(0,r.kt)("strong",{parentName:"p"},"not parallel")," to any axis."),(0,r.kt)("p",null,"This line is at an angle to ",(0,r.kt)("em",{parentName:"p"},"Vertical")," axis."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch Segment value and Create Line 2\nSet swSketchSegment = swSketchManager.CreateLine(-0.75, -1.25, 0, 0.5, -1.25, 0)\n")),(0,r.kt)("p",null,"In above line we create Line 2 by using same ",(0,r.kt)("inlineCode",{parentName:"p"},"CreateLine")," method from ",(0,r.kt)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,r.kt)("p",null,"In above code, we create our 2nd line between ",(0,r.kt)("strong",{parentName:"p"},"point (-0.75, -1.25, 0)")," and ",(0,r.kt)("strong",{parentName:"p"},"point (0.5, -1.25, 0)"),"."),(0,r.kt)("p",null,"This line is ",(0,r.kt)("strong",{parentName:"p"},"parallel")," to X-axis."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the lines after creation\nswDoc.ClearSelection2 True\n")),(0,r.kt)("p",null,"After creating both lines we de-select those lines."),(0,r.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"info")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"We ",(0,r.kt)("strong",{parentName:"p"},"don't need")," to de-select the lines for ",(0,r.kt)("strong",{parentName:"p"},"Extend operation")," as I will select those lines agains in next 2 lines. I just want to show you how to select a ",(0,r.kt)("strong",{parentName:"p"},"Sketch Segment")," with ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectById")," Menthod."))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Line 1\nBoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,r.kt)("p",null,"In above line of code, we select ",(0,r.kt)("strong",{parentName:"p"},"Line 1"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Extend selected Sketch Segments by "SketchExtend" method from Solidworks sketch manager\nBoolStatus = swSketchManager.SketchExtend(0.0, 0.0, 0.0)\n')),(0,r.kt)("p",null,"In above line, we ",(0,r.kt)("strong",{parentName:"p"},"Extend")," selected ",(0,r.kt)("em",{parentName:"p"},"Sketch Segments")," by ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchExtend")," method from ",(0,r.kt)("em",{parentName:"p"},"Solidworks sketch manager"),"."),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"SketchExtend")," method takes following parameters:"),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"X")," : ",(0,r.kt)("em",{parentName:"p"},"Not used")),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Y")," : ",(0,r.kt)("em",{parentName:"p"},"Not used")),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Z")," : ",(0,r.kt)("em",{parentName:"p"},"Not used")),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Return Value"),":"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"True"),": If Extend operation is ",(0,r.kt)("em",{parentName:"li"},"Success"),".")),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("strong",{parentName:"li"},"False"),": If Extend operation is ",(0,r.kt)("em",{parentName:"li"},"Fail"),".")),(0,r.kt)("p",null,"In our code, I have used following values:"),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"X")," : I have used 0.0 value for ",(0,r.kt)("em",{parentName:"p"},"X"),"."),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Y")," : I have used 0.0 value for ",(0,r.kt)("em",{parentName:"p"},"Y"),"."),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Z")," : I have used 0.0 value for ",(0,r.kt)("em",{parentName:"p"},"Z"),"."),(0,r.kt)("p",null,"Below image shows before and after Extend operation on the sketch."),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Before Extend Operation")),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"before_extend",src:n(91178).Z,width:"1036",height:"806"})),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"After Extend Operation")),(0,r.kt)("p",null,(0,r.kt)("img",{alt:"after_extend",src:n(623).Z,width:"1037",height:"811"})),(0,r.kt)("hr",null),(0,r.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"NOTE")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"It is ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"Meter only")),"."),(0,r.kt)("p",{parentName:"div"},"Solidworks API does not care about your application's Unit systems."),(0,r.kt)("p",{parentName:"div"},"For example, I works in ",(0,r.kt)("strong",{parentName:"p"},"ANSI")," system means inches for distance. But when I used ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API")," through ",(0,r.kt)("em",{parentName:"p"},"VBA macros or C#"),", I need to use converted numeric values."),(0,r.kt)("p",{parentName:"div"},"Because Solidworks API output the distance in ",(0,r.kt)("strong",{parentName:"p"},"Meter")," which is not my requirement."))),(0,r.kt)("hr",null),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Sketch after creation\nswDoc.ClearSelection2 True\n")),(0,r.kt)("p",null,"In the above line of code, we deselect the ",(0,r.kt)("strong",{parentName:"p"},"Sketch")," after the ",(0,r.kt)("em",{parentName:"p"},"Extend")," operation."),(0,r.kt)("p",null,"For de-selecting, we use ",(0,r.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Show Front View after Sketch Extend\nswDoc.ShowNamedView2 "", swStandardViews_e.swFrontView\n')),(0,r.kt)("p",null,"In the above line of code, we update the ",(0,r.kt)("em",{parentName:"p"},"view orientation")," to ",(0,r.kt)("strong",{parentName:"p"},"Front View"),"."),(0,r.kt)("p",null,"In my machine, after inserting a sketch view orientation does not changed."),(0,r.kt)("p",null,"Because of this I have to update the view to ",(0,r.kt)("strong",{parentName:"p"},"Front view"),"."),(0,r.kt)("p",null,"For showing ",(0,r.kt)("strong",{parentName:"p"},"Front View")," we used ",(0,r.kt)("inlineCode",{parentName:"p"},"ShowNamedView2")," method from our Solidworks document name ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,r.kt)("p",null,"This method takes 2 parameter described as follows:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"VName")," : Name of the view to display or an empty string to use ViewId instead")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"ViewId")," : ID of the view to display as defined by ",(0,r.kt)("inlineCode",{parentName:"p"},"swStandardViews_e")," or -1 to use the ",(0,r.kt)("strong",{parentName:"p"},"VName")," argument instead."))),(0,r.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"NOTE")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"If you specify both ",(0,r.kt)("strong",{parentName:"p"},"VName")," and ",(0,r.kt)("strong",{parentName:"p"},"ViewId"),", then ",(0,r.kt)("strong",{parentName:"p"},"ViewId")," takes precedence if the two arguments do not resolve to the same view."))),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"swStandardViews_e")," has following Standard View Types:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swBackView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swBottomView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swDimetricView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swFrontView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swIsometricView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swLeftView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swRightView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swTopView"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("em",{parentName:"p"},"swExtendetricView")))),(0,r.kt)("p",null,"In our code, we did not use ",(0,r.kt)("strong",{parentName:"p"},"VName")," instead I used ",(0,r.kt)("em",{parentName:"p"},"empty string")," in form of ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},'""'))," symbol."),(0,r.kt)("p",null,"I used ",(0,r.kt)("strong",{parentName:"p"},"ViewId")," value to specify view and used ",(0,r.kt)("inlineCode",{parentName:"p"},"swStandardViews_e.swFrontView")," value to use ",(0,r.kt)("em",{parentName:"p"},"Standard Front View"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),(0,r.kt)("p",null,"In this last line we use ",(0,r.kt)("em",{parentName:"p"},"zoom to fit")," command."),(0,r.kt)("p",null,"For Zoom to fit, we use ",(0,r.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,r.kt)("p",null,"This is it !!!"),(0,r.kt)("p",null,"If you found anything to add or update, please let me know on my e-mail."),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"vba-language-feature-used-in-this-post"},"VBA Language feature used in this post"),(0,r.kt)("p",null,"In this post used some features of ",(0,r.kt)("strong",{parentName:"p"},"VBA programming language"),"."),(0,r.kt)("p",null,"This section of post, has some brief information about the VBA programming language specific features."),(0,r.kt)("ol",null,(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"We use ",(0,r.kt)("strong",{parentName:"p"},"Option Explicit")," for capturing un-declared variables. If you want to read more about ",(0,r.kt)("strong",{parentName:"p"},"Option Explicit")," then please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-declaring-and-scoping-of-variables"},"Declaring and Scoping of Variables")),".")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"Then we create ",(0,r.kt)("strong",{parentName:"p"},"variable")," for different data types. If you don't know about them, then please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-variables"},"Variables"))," and \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-programming-concepts/#data-types-in-vba"},"Data-types"))," posts of this blog. These posts will help you to understand what ",(0,r.kt)("strong",{parentName:"p"},"Variables")," are and how to use them.")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"Then we create ",(0,r.kt)("strong",{parentName:"p"},"main Sub procedure")," for our macro. If you don't know about the ",(0,r.kt)("strong",{parentName:"p"},"Sub procedure"),", then I suggest you to visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-sub-and-function-procedure"},"VBA Sub and Function Procedures"))," and \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-executing-procedures"},"Executing Sub and Function Procedures"))," posts of this blog. These posts will help you to understand what ",(0,r.kt)("strong",{parentName:"p"},"Procedures")," are and how to use them.")),(0,r.kt)("li",{parentName:"ol"},(0,r.kt)("p",{parentName:"li"},"In most part we create some variables and set their values. We set those values by using some ",(0,r.kt)("strong",{parentName:"p"},"functions")," provided from objects. If you don't know about the ",(0,r.kt)("strong",{parentName:"p"},"functions"),", then you should visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-functions"},"VBA Functions"))," and \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-more-function"},"VBA Functions that do more"))," posts of this blog. These posts will help you to understand what ",(0,r.kt)("strong",{parentName:"p"},"functions")," are and how to use them."))),(0,r.kt)("hr",null),(0,r.kt)("h2",{id:"solidworks-api-objects"},"Solidworks API Objects"),(0,r.kt)("p",null,"In this post of ",(0,r.kt)("strong",{parentName:"p"},"Sketch Extend"),", we use ",(0,r.kt)("em",{parentName:"p"},"Solidworks API objects and their methods"),"."),(0,r.kt)("p",null,"This section contains the list of all ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Objects")," used in this post."),(0,r.kt)("p",null,"I have also attached links of these ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in ",(0,r.kt)("strong",{parentName:"p"},"API Help website"),"."),(0,r.kt)("p",null,"If you want to explore those objects, you can use these links."),(0,r.kt)("p",null,"These Solidworks API Objects are listed below:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Solidworks Application Object")),(0,r.kt)("p",{parentName:"li"},"If you want explore ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Application Object")," object you can visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html"},"this link")),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Solidworks Document Object")),(0,r.kt)("p",{parentName:"li"},"If you want explore ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Document Object")," object you can visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html"},"this link")),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")),(0,r.kt)("p",{parentName:"li"},"If you want explore ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")," you can visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this link")),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")),(0,r.kt)("p",{parentName:"li"},"If you want explore ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")," you can visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"},"this link")),"."))),(0,r.kt)("hr",null),(0,r.kt)("p",null,"Hope this post helps you to ",(0,r.kt)("em",{parentName:"p"},"Extend")," Sketch Entities with Solidworks VB Macros."),(0,r.kt)("p",null,"For more such tutorials on ",(0,r.kt)("strong",{parentName:"p"},"Solidworks VBA Macros"),", do come to this blog after sometime."),(0,r.kt)("p",null,"Till then, Happy learning!!!"))}c.isMDXComponent=!0},623:function(e,t,n){t.Z=n.p+"assets/images/after_extend-7266e4cdfebc4671a3302534d29dc639.png"},91178:function(e,t,n){t.Z=n.p+"assets/images/before_extend-165aa7bd29644b8a2a20efae9424e648.png"}}]);