"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[5935],{3905:(e,t,n)=>{n.d(t,{Zo:()=>m,kt:()=>u});var a=n(67294);function o(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function r(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?r(Object(n),!0).forEach((function(t){o(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function s(e,t){if(null==e)return{};var n,a,o=function(e,t){if(null==e)return{};var n,a,o={},r=Object.keys(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var l=a.createContext({}),p=function(e){var t=a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},m=function(e){var t=p(e.components);return a.createElement(l.Provider,{value:t},e.children)},k={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},c=a.forwardRef((function(e,t){var n=e.components,o=e.mdxType,r=e.originalType,l=e.parentName,m=s(e,["components","mdxType","originalType","parentName"]),c=p(n),u=o,d=c["".concat(l,".").concat(u)]||c[u]||k[u]||r;return n?a.createElement(d,i(i({ref:t},m),{},{components:n})):a.createElement(d,i({ref:t},m))}));function u(e,t){var n=arguments,o=t&&t.mdxType;if("string"==typeof e||o){var r=n.length,i=new Array(r);i[0]=c;var s={};for(var l in t)hasOwnProperty.call(t,l)&&(s[l]=t[l]);s.originalType=e,s.mdxType="string"==typeof e?e:o,i[1]=s;for(var p=2;p<r;p++)i[p]=n[p];return a.createElement.apply(null,i)}return a.createElement.apply(null,n)}c.displayName="MDXCreateElement"},81955:(e,t,n)=>{n.r(t),n.d(t,{assets:()=>p,contentTitle:()=>s,default:()=>c,frontMatter:()=>i,metadata:()=>l,toc:()=>m});var a=n(87462),o=(n(67294),n(3905)),r=n(74753);const i={categories:"Solidworks-macro",title:"Solidworks Macro - Create a Spline",permalink:"/solidworks-macros/create-spline/",tags:["Solidworks Macro"],id:"create-spline"},s=void 0,l={unversionedId:"create-spline",id:"create-spline",title:"Solidworks Macro - Create a Spline",description:"",source:"@site/docs/solidworks-macros/007.2-create-spline.md",sourceDirName:".",slug:"/create-spline",permalink:"/solidworks-macros/create-spline",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Create a Spline",permalink:"/solidworks-macros/create-spline/",tags:["Solidworks Macro"],id:"create-spline"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Create a Point",permalink:"/solidworks-macros/create-point"},next:{title:"Solidworks Macro - Create a Fillet",permalink:"/solidworks-macros/create-sketch-fillet"}},p={},m=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"For Experience Macro Developer",id:"for-experience-macro-developer",level:2},{value:"For Beginners Macro Developers",id:"for-beginners-macro-developers",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:3},{value:"Creating sequence of Points",id:"creating-sequence-of-points",level:4},{value:"Create a Collection of Points Co-ordinates",id:"create-a-collection-of-points-co-ordinates",level:4},{value:"Preparing Co-ordinates of Points",id:"preparing-co-ordinates-of-points",level:4},{value:"Create Spline",id:"create-spline",level:4},{value:"VBA Language feature used in this post",id:"vba-language-feature-used-in-this-post",level:2},{value:"Solidworks API Objects",id:"solidworks-api-objects",level:2}],k={toc:m};function c(e){let{components:t,...i}=e;return(0,o.kt)("wrapper",(0,a.Z)({},k,i,{components:t,mdxType:"MDXLayout"}),(0,o.kt)(r.Z,{mdxType:"AdComponent"}),(0,o.kt)("p",null,"In this post, I tell you about ",(0,o.kt)("em",{parentName:"p"},"how to create a Spline through Solidworks VBA Macros")," in a sketch."),(0,o.kt)("p",null,"This post take some functionality from previous \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-point"},"Sketch - Create Create a Point"))," post."),(0,o.kt)("p",null,"Hence if you have not read \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/create-point"},"Sketch - Create Create a Point"))," post, then it is ",(0,o.kt)("strong",{parentName:"p"},"recommended")," that please read it 1st."),(0,o.kt)("hr",null),(0,o.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,o.kt)("p",null,"Please see below video \ud83c\udfac how visually we can create ",(0,o.kt)("em",{parentName:"p"},"a Spline")," from ",(0,o.kt)("strong",{parentName:"p"},"Solidworks VBA macro"),"."),(0,o.kt)("iframe",{src:"https://www.youtube.com/embed/B_W-f3cqUPM",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,o.kt)("p",null,"Please note that there are no explaination given in the video. "),(0,o.kt)("p",null,"Explaination of each line and why we write code this way is explained here."),(0,o.kt)("hr",null),(0,o.kt)("h2",{id:"for-experience-macro-developer"},"For Experience Macro Developer"),(0,o.kt)("p",null,"If you are an experience ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Macro developer"),", then you are looking for a specific code sample."),(0,o.kt)("p",null,"Below is the code for creating ",(0,o.kt)("strong",{parentName:"p"},"A Spline")," from ",(0,o.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n      \n' Set the value of Solidworks Sketch segment by \"CreateSpline2\" method from Solidworks sketch manager\nSet swSketchSegment = swSketchManager.CreateSpline2((pointArray), True)\n")),(0,o.kt)("p",null,"For creating a ",(0,o.kt)("strong",{parentName:"p"},"Spline")," first you need to ",(0,o.kt)("strong",{parentName:"p"},"Create")," a variable of ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchSegment")," type."),(0,o.kt)("p",null,"After creating variable, you need to set the value of this variable."),(0,o.kt)("p",null,"For this you used ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateSpline2")," method from ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateSpline2")," method set the value of ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchSegment")," type variable."),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateSpline2")," method takes following parameters as explained:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"PointData")," : ",(0,o.kt)("em",{parentName:"p"},"Array of X,Y,Z point coordinates to use in creating the spline"),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"SimulateNaturalEnds")," : ",(0,o.kt)("em",{parentName:"p"},"True to simulate natural ends, false to not simulate natural ends"),"."))),(0,o.kt)("p",null,"If you want a more detail explaination then please read further otherwise this will help you to ",(0,o.kt)("strong",{parentName:"p"},"Create a Spline From VBA Macro"),"."),(0,o.kt)("hr",null),(0,o.kt)(r.Z,{mdxType:"AdComponent"}),(0,o.kt)("h2",{id:"for-beginners-macro-developers"},"For Beginners Macro Developers"),(0,o.kt)("p",null,"In this post, I tell you about ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateSpline2")," method from ",(0,o.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchManager")," object."),(0,o.kt)("p",null,"By this method we create ",(0,o.kt)("em",{parentName:"p"},"a simple Spline from a sequence of points"),"."),(0,o.kt)("p",null,"This method is ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"most updated"))," method, I found in ",(0,o.kt)("em",{parentName:"p"},"Solidworks API Help"),". "),(0,o.kt)("p",null,"So ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"use this method"))," if you want to create ",(0,o.kt)("strong",{parentName:"p"},"a new Spline"),"."),(0,o.kt)("p",null,"Below is the ",(0,o.kt)("inlineCode",{parentName:"p"},"code")," sample for creating ",(0,o.kt)("em",{parentName:"p"},"a Spline"),"."),(0,o.kt)("admonition",{type:"caution"},(0,o.kt)("p",{parentName:"admonition"},"Please don't get distracted by length of code, I  just want to do everything programatically. So that you have some sort of experience in developing logic.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Creating variable for Solidworks Sketch\nDim swSketch As SldWorks.Sketch\n\n' Creating variable for Solidworks Sketch Point\nDim swSketchPoint As SldWorks.SketchPoint\n\n' Creating variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks application variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Creating string type variable for storing default part location\n  Dim defaultTemplate As String\n  \n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n  \n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Create integer type local variable\n  Dim i As Integer\n  \n  ' Loop through 0 to 10\n  For i = 0 To 10\n    \n    ' Create integer type variables\n    Dim x, y, z, incrementFactor As Integer\n    \n    ' Set value of incrementFactor\n    incrementFactor = i * 0.5\n    \n    ' Set value of x co-ordinate\n    x = i\n    ' Set value of y co-ordinate\n    y = x + incrementFactor\n    ' Set value of z co-ordinate\n    z = 0\n\n    ' Create a Sketch Point using x, y & z variables\n    Set swSketchPoint = swSketchManager.CreatePoint(x, y, z)\n\n  Next i\n  \n  ' De-select the points after creation\n  swDoc.ClearSelection2 True\n  \n  ' Set Solidworks Sketch variable to active sketch\n  Set swSketch = swSketchManager.ActiveSketch\n  \n  ' Create variant type variable named \"sketchPointArray\"\n  Dim sketchPointArray As Variant\n  \n  ' Get all the points in this active sketch and store them into our variant type variable\n  sketchPointArray = swSketch.GetSketchPoints2()\n  \n  ' Creating a new Collection,\n  ' we use this collecction to store x,y,z co-ordinates of all sketch points\n  Dim pointCollection As New Collection\n  \n  ' Loop through all points in \"sketchPointArray\"\n  For i = 0 To UBound(sketchPointArray)\n    ' Set Solidworks sketch point variable to current point\n    Set swSketchPoint = sketchPointArray(i)\n    \n    ' Add X co-ordinate of current point into collection\n    pointCollection.Add (swSketchPoint.x)\n    \n    ' Add Y co-ordinate of current point into collection\n    pointCollection.Add (swSketchPoint.y)\n    \n    ' Add Z co-ordinate of current point into collection\n    pointCollection.Add (swSketchPoint.z)\n  Next i\n  \n  ' Create an array variable, this is Double type variable\n  Dim point() As Double\n  \n  ' Define the size of array Dynamically\n  ReDim point(0 To pointCollection.Count) As Double\n  \n  ' Loop through the collection we have\n  For i = 0 To (pointCollection.Count - 1)\n    ' Add each item of collection into our array variable\n    point(i) = pointCollection(i + 1)\n  Next i\n  \n  ' Create a local variable name \"pointArray\" of variant type\n  Dim pointArray As Variant\n  \n  ' Set the new created variable equal to point array variable\n  pointArray = point\n  \n  ' Exit the sketch\n  swSketchManager.InsertSketch True\n  \n  ' De-select the sketch\n  swDoc.ClearSelection2 True\n  \n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Insert a sketch into \"Front Plane\"\n  swSketchManager.InsertSketch True\n  \n  ' Set the value of Solidworks Sketch segment by \"CreateSpline2\" method from Solidworks sketch manager\n  Set swSketchSegment = swSketchManager.CreateSpline2((pointArray), True)\n\n  ' De-select the Spline after creation\n  swDoc.ClearSelection2 True\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n\n  ' Exit the sketch\n  swSketchManager.InsertSketch True\n\n  ' Force Re-build the model\n  swDoc.Rebuild (swRebuildOptions_e.swForceRebuildAll)\n\nEnd Sub\n")),(0,o.kt)("hr",null),(0,o.kt)("h3",{id:"understanding-the-code"},"Understanding the Code"),(0,o.kt)("p",null,"Now let us walk through ",(0,o.kt)("em",{parentName:"p"},"each line")," in the above code, and ",(0,o.kt)("strong",{parentName:"p"},"understand")," the meaning of every line."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,o.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For more information please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,o.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,o.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,o.kt)("p",null,"In this line, we create a variable named ",(0,o.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,o.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),(0,o.kt)("p",null,"In above line, we create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchManager")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,o.kt)("p",null,"As the name suggested, a ",(0,o.kt)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",(0,o.kt)("em",{parentName:"p"},"Sketches"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this page of Solidworks API Help"))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Sketch\nDim swSketch As SldWorks.Sketch\n")),(0,o.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketch")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketch")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.Sketch"),"."),(0,o.kt)("p",null,"We create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketch")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketches"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"Sketch")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketch_members.html?verRedirect=1"},"this page of Solidworks API Help"))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Sketch Point\nDim swSketchPoint As SldWorks.SketchPoint\n")),(0,o.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchPoint")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchPoint")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.SketchPoint"),"."),(0,o.kt)("p",null,"We create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchPoint")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Points"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchPoint")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchPoint_members.html"},"this page of Solidworks API Help"))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n")),(0,o.kt)("p",null,"In this line, we are creating a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.SketchSegment"),"."),(0,o.kt)("p",null,"We create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Segments"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"},"this page of Solidworks API Help"))),(0,o.kt)("p",null,"These all are our global variables."),(0,o.kt)("p",null,"As you can see in code sample, they are ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,o.kt)("p",null,"So basically I group all the ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,o.kt)("p",null,"I have also place ",(0,o.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",(0,o.kt)("em",{parentName:"p"},"need")," this variable frequently."),(0,o.kt)("p",null,"Thus, I have started placing it here."),(0,o.kt)("p",null,"Next is our ",(0,o.kt)("inlineCode",{parentName:"p"},"Sub")," procedure named as ",(0,o.kt)("inlineCode",{parentName:"p"},"main"),". This procedure hold all the ",(0,o.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,o.kt)("p",null,"In this line, we are setting the value of our Solidworks variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," which we defined earlier to Solidworks application."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating string type variable for storing default part location\nDim defaultTemplate As String\n\n' Setting value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),(0,o.kt)("p",null,"In 1st statement of above example, we are defining a variable of ",(0,o.kt)("inlineCode",{parentName:"p"},"string")," type and named it as ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),(0,o.kt)("p",null,"This variable ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),", holds the location the location of ",(0,o.kt)("strong",{parentName:"p"},"Default Part Template"),"."),(0,o.kt)("p",null,"In 2nd line of above example. we assign value to our newly define ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),(0,o.kt)("p",null,"We assign the value by using a ",(0,o.kt)("em",{parentName:"p"},"Method")," named ",(0,o.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),(0,o.kt)("p",null,"This method is a part of our main Solidworks variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),(0,o.kt)("p",null,"In this line, we set the value of our ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For ",(0,o.kt)("strong",{parentName:"p"},"more detailed information")," about above lines please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post. "),(0,o.kt)("p",{parentName:"admonition"},"I have discussed them ",(0,o.kt)("strong",{parentName:"p"},"thoroghly")," in \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post, so do checkout this post if you don't understand above code.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Selecting Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line, we select the ",(0,o.kt)("em",{parentName:"p"},"front plane")," by using ",(0,o.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,o.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For more information about selection method please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."),(0,o.kt)("p",{parentName:"admonition"},"I have discussed about different ",(0,o.kt)("em",{parentName:"p"},"Selection methods")," in details in \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Soldworks Macros - Selection Methods"))," post, so do visit this post for more ",(0,o.kt)("em",{parentName:"p"},"Selection methods"),".")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),(0,o.kt)("p",null,"In above line, we set the ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch manager")," variable to current document's sketch manager."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Inserting a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,o.kt)("p",null,"In above line, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,o.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,o.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,o.kt)("p",null,"This method allows us to insert/exit ",(0,o.kt)("strong",{parentName:"p"},"a sketch")," in selected plane."),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Now I have created a sequence of Points for our Spline.")),(0,o.kt)("p",null,"Because if you already have co-ordinates of points in your machine somewhere you can use the approach I shown here to create a Spline."),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"I like to save co-ordinates in MS Excel file and then use it.")),(0,o.kt)("hr",null),(0,o.kt)(r.Z,{mdxType:"AdComponent"}),(0,o.kt)("h4",{id:"creating-sequence-of-points"},"Creating sequence of Points"),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Below code shows how to create Sequence of Points.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create integer type local variable\nDim i As Integer\n\n' Loop through 0 to 10\nFor i = 0 To 10\n  \n  ' Create integer type variables\n  Dim x, y, z, incrementFactor As Integer\n  \n  ' Set value of incrementFactor\n  incrementFactor = i * 0.5\n  \n  ' Set value of x co-ordinate\n  x = i\n  ' Set value of y co-ordinate\n  y = x + incrementFactor\n  ' Set value of z co-ordinate\n  z = 0\n\n  ' Create a Sketch Point using x, y & z variables\n  Set swSketchPoint = swSketchManager.CreatePoint(x, y, z)\n\nNext i\n\n' De-select the points after creation\nswDoc.ClearSelection2 True\n")),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Let us understand each line of code and how above Lines of code creates a number of points.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create integer type local variable\nDim i As Integer\n")),(0,o.kt)("p",null,"In above line, we create a local variable named ",(0,o.kt)("inlineCode",{parentName:"p"},"i")," of ",(0,o.kt)("strong",{parentName:"p"},"integer")," type."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Looping through 1 to 10\nFor i = 0 To 10\n  \nNext\n")),(0,o.kt)("p",null,"In above lines, we create a ",(0,o.kt)("inlineCode",{parentName:"p"},"For")," loop."),(0,o.kt)("p",null,"This loop iterate the value of ",(0,o.kt)("inlineCode",{parentName:"p"},"i")," variable from ",(0,o.kt)("strong",{parentName:"p"},"0 -> 10"),"."),(0,o.kt)("p",null,"I use max value of ",(0,o.kt)("strong",{parentName:"p"},"10"),", because I want to create 10 points."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create integer type variables\nDim x, y, z, incrementFactor As Integer\n\n' Set value of incrementFactor\nincrementFactor = i * 0.5\n\n' Setting values of x, y and z\nx = i\ny = x + incrementFactor\nz = 0\n")),(0,o.kt)("p",null,"In above lines, we 1st declare 4 variable ",(0,o.kt)("em",{parentName:"p"},"x, y, z and incrementFactor")," of ",(0,o.kt)("strong",{parentName:"p"},"integer")," type."),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"x, y and z")," are co-ordinates of a single point in ",(0,o.kt)("em",{parentName:"p"},"X, Y")," and ",(0,o.kt)("em",{parentName:"p"},"Z")," direction."),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"incrementFactor")," is the factor by which I want to increase the value of ",(0,o.kt)("em",{parentName:"p"},"Y co-ordinate")," of a single point."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set value of incrementFactor\nincrementFactor = i * 0.5\n")),(0,o.kt)("p",null,"In above line, I set the value of ",(0,o.kt)("em",{parentName:"p"},"incrementFactor"),"."),(0,o.kt)("p",null,"This value is ",(0,o.kt)("strong",{parentName:"p"},"0.5")," times of value of ",(0,o.kt)("inlineCode",{parentName:"p"},"i")," variable."),(0,o.kt)("p",null,"Example: ",(0,o.kt)("inlineCode",{parentName:"p"},"i = 3")," then ",(0,o.kt)("em",{parentName:"p"},"incrementFactor = 3 ")," 0.5 => incrementFactor = 1.5*"),(0,o.kt)("p",null,"In next 3 lines, we set the values of ",(0,o.kt)("em",{parentName:"p"},"x, y and z"),"."),(0,o.kt)("p",null,"For all points, we set the value of ",(0,o.kt)("em",{parentName:"p"},"z")," to ",(0,o.kt)("strong",{parentName:"p"},"0")," because we want to place our points in ",(0,o.kt)("strong",{parentName:"p"},"X-Y plane"),"."),(0,o.kt)("p",null,"If the value of ",(0,o.kt)("inlineCode",{parentName:"p"},"i = 0"),", then we set the value of ",(0,o.kt)("em",{parentName:"p"},"x")," equal to ",(0,o.kt)("em",{parentName:"p"},"i"),"."),(0,o.kt)("p",null,"This makes ",(0,o.kt)("inlineCode",{parentName:"p"},"x = 0")," also."),(0,o.kt)("p",null,"Now, we set the value of ",(0,o.kt)("em",{parentName:"p"},"y")," which is equal to ",(0,o.kt)("strong",{parentName:"p"},"SUM")," of ",(0,o.kt)("em",{parentName:"p"},"x")," and ",(0,o.kt)("em",{parentName:"p"},"incrementFactor"),"."),(0,o.kt)("p",null,"Hence for ",(0,o.kt)("em",{parentName:"p"},"i = 0"),", ",(0,o.kt)("em",{parentName:"p"},"x = 0"),", ",(0,o.kt)("em",{parentName:"p"},"y = 0")," and ",(0,o.kt)("em",{parentName:"p"},"incrementFactor = 0"),"."),(0,o.kt)("p",null,"For ",(0,o.kt)("em",{parentName:"p"},"i = 1"),", ",(0,o.kt)("em",{parentName:"p"},"x = 1"),", ",(0,o.kt)("em",{parentName:"p"},"y = 1.5")," and ",(0,o.kt)("em",{parentName:"p"},"incrementFactor = 0.5"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create a Sketch Point using x, y & z variables\nSet swSketchPoint = swSketchManager.CreatePoint(x, y, z)\n")),(0,o.kt)("p",null,"In above line, we create a Point using ",(0,o.kt)("inlineCode",{parentName:"p"},"CreatePoint")," function of ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchManager")," variable with the values of ",(0,o.kt)("em",{parentName:"p"},"x, y and z"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Points after creation\nswDoc.ClearSelection2 True\n")),(0,o.kt)("p",null,"In the this line of code, we de-select the created ",(0,o.kt)("em",{parentName:"p"},"Points"),"."),(0,o.kt)("p",null,"For de-selecting, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("hr",null),(0,o.kt)("h4",{id:"create-a-collection-of-points-co-ordinates"},"Create a Collection of Points Co-ordinates"),(0,o.kt)("p",null,"After creating points, I want to do following things:"),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"Get all points in this sketch")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"Add co-ordinates of each point into a collection"))),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Why I want to do this when I already know co-ordinates of all points in previous section?"))),(0,o.kt)("p",null,"It is because I create points from this macro hence I know their co-ordinates."),(0,o.kt)("p",null,"I can add them to collection there BUT I want to take this opportunity to show following things:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},"How you get points of an Sketch.")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},"How to create a Collection and Add values in it."))),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Below code shows how to do all those things.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks Sketch variable to active sketch\nSet swSketch = swSketchManager.ActiveSketch\n\n' Create variant type variable named \"sketchPointArray\"\nDim sketchPointArray As Variant\n\n' Get all the points in this active sketch and store them into our variant type variable\nsketchPointArray = swSketch.GetSketchPoints2()\n\n' Creating a new Collection,\n' we use this collecction to store x,y,z co-ordinates of all sketch points\nDim pointCollection As New Collection\n\n' Loop through all points in \"sketchPointArray\"\nFor i = 0 To UBound(sketchPointArray)\n  ' Set Solidworks sketch point variable to current point\n  Set swSketchPoint = sketchPointArray(i)\n  \n  ' Add X co-ordinate of current point into collection\n  pointCollection.Add (swSketchPoint.x)\n  \n  ' Add Y co-ordinate of current point into collection\n  pointCollection.Add (swSketchPoint.y)\n  \n  ' Add Z co-ordinate of current point into collection\n  pointCollection.Add (swSketchPoint.z)\nNext i\n")),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Let us understand each line of code.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks Sketch variable to active sketch\nSet swSketch = swSketchManager.ActiveSketch\n")),(0,o.kt)("p",null,"In the above line, I set the value of ",(0,o.kt)("em",{parentName:"p"},"Solidworks Sketch")," variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketch")," to active sketch."),(0,o.kt)("p",null,"For this we use ",(0,o.kt)("inlineCode",{parentName:"p"},"ActiveSketch")," method of ",(0,o.kt)("em",{parentName:"p"},"Solidworks Sketch Manager")," variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchManager"),"."),(0,o.kt)("p",null,"This method give us a ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.Sketch")," type return value which we store into ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketch")," variable."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variant type variable named \"sketchPointArray\"\nDim sketchPointArray As Variant\n\n' Get all the points in this active sketch and store them into our variant type variable\nsketchPointArray = swSketch.GetSketchPoints2()\n")),(0,o.kt)("p",null,"In 1st line of above code, I create a variable ",(0,o.kt)("inlineCode",{parentName:"p"},"sketchPointArray"),"."),(0,o.kt)("p",null,"This variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"Variant")," type variable."),(0,o.kt)("p",null,"In 2nd line of above code, I set the value of variable ",(0,o.kt)("inlineCode",{parentName:"p"},"sketchPointArray")," using ",(0,o.kt)("inlineCode",{parentName:"p"},"GetSketchPoints2()")," method."),(0,o.kt)("p",null,"We use ",(0,o.kt)("inlineCode",{parentName:"p"},"GetSketchPoints2()")," method from our ",(0,o.kt)("em",{parentName:"p"},"Solidworks Sketch")," type variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketch"),"."),(0,o.kt)("p",null,(0,o.kt)("inlineCode",{parentName:"p"},"GetSketchPoints2()")," method gives us all points in this sketch and we store those points into ",(0,o.kt)("inlineCode",{parentName:"p"},"sketchPointArray")," variable."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating a new Collection,\n' we use this collecction to store x,y,z co-ordinates of all sketch points\nDim pointCollection As New Collection\n")),(0,o.kt)("p",null,"In the above line, I create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"pointCollection")," of ",(0,o.kt)("strong",{parentName:"p"},"Collection")," type."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Loop through all points in "sketchPointArray"\nFor i = 0 To UBound(sketchPointArray)\n\nNext i\n')),(0,o.kt)("p",null,"In above lines, we create a ",(0,o.kt)("inlineCode",{parentName:"p"},"For")," loop."),(0,o.kt)("p",null,"This loop iterate the value of ",(0,o.kt)("inlineCode",{parentName:"p"},"i")," variable from ",(0,o.kt)("strong",{parentName:"p"},"0 -> UBound(sketchPointArray)"),"."),(0,o.kt)("p",null,"I use max value of ",(0,o.kt)("strong",{parentName:"p"},"UBound(sketchPointArray)"),", because I want to iterate through Maximum number of points we get from the ",(0,o.kt)("inlineCode",{parentName:"p"},"GetSketchPoints2()")," method."),(0,o.kt)("p",null,"If number of points are other than ",(0,o.kt)("em",{parentName:"p"},"10"),", then ",(0,o.kt)("inlineCode",{parentName:"p"},"UBound(sketchPointArray)")," method return only that number of points."),(0,o.kt)("p",null,"Hence it is ",(0,o.kt)("strong",{parentName:"p"},"useful")," to know for future use."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks sketch point variable to current point\nSet swSketchPoint = sketchPointArray(i)\n")),(0,o.kt)("p",null,"Now inside, this loop in 1st line we set ",(0,o.kt)("em",{parentName:"p"},"Solidworks sketch point")," variable to ",(0,o.kt)("strong",{parentName:"p"},"current")," point of ",(0,o.kt)("inlineCode",{parentName:"p"},"sketchPointArray"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Add X co-ordinate of current point into collection\npointCollection.Add (swSketchPoint.x)\n\n' Add Y co-ordinate of current point into collection\npointCollection.Add (swSketchPoint.y)\n\n' Add Z co-ordinate of current point into collection\npointCollection.Add (swSketchPoint.z)\n")),(0,o.kt)("p",null,"In above 3 lines, we add ",(0,o.kt)("em",{parentName:"p"},"X, Y and Z")," co-ordinates of current point into our collection."),(0,o.kt)("h4",{id:"preparing-co-ordinates-of-points"},"Preparing Co-ordinates of Points"),(0,o.kt)("p",null,"You know from \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"#for-experience-macro-developer"},"For Experience Macro Developers"))," section, we need an ",(0,o.kt)("em",{parentName:"p"},"Array")," of ",(0,o.kt)("strong",{parentName:"p"},"PointData"),"."),(0,o.kt)("p",null,"This array contains ",(0,o.kt)("em",{parentName:"p"},"X, Y and Z")," co-ordinates for Spline Points."),(0,o.kt)("p",null,"Now I tried to add ",(0,o.kt)("em",{parentName:"p"},"X, Y and Z")," co-ordinates directly into an Array and then use this array to create Spline."),(0,o.kt)("p",null,"But it did not work, hence I had to store all ",(0,o.kt)("em",{parentName:"p"},"X, Y and Z")," co-ordinates 1st into ",(0,o.kt)("strong",{parentName:"p"},"Collection"),"."),(0,o.kt)("p",null,"Now I have all co-ordinates in my ",(0,o.kt)("strong",{parentName:"p"},"Collection")," and I have to create an ",(0,o.kt)("inlineCode",{parentName:"p"},"Array")," for Spline from this ",(0,o.kt)("strong",{parentName:"p"},"Collection"),"."),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Below code sample show how to prepare Co-ordinate points for Spline"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create an array variable, this is Double type variable\nDim point() As Double\n\n' Define the size of array Dynamically\nReDim point(0 To pointCollection.Count) As Double\n\n' Loop through the collection we have\nFor i = 0 To (pointCollection.Count - 1)\n  ' Add each item of collection into our array variable\n  point(i) = pointCollection(i + 1)\nNext i\n\n' Create a local variable name \"pointArray\" of variant type\nDim pointArray As Variant\n\n' Set the new created variable equal to point array variable\npointArray = point\n\n' Exit the sketch\nswSketchManager.InsertSketch True\n\n' De-select the sketch\nswDoc.ClearSelection2 True\n")),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Let us understand each line of above code sample.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create an array variable, this is Double type variable\nDim point() As Double\n\n' Define the size of array Dynamically\nReDim point(0 To pointCollection.Count) As Double\n")),(0,o.kt)("p",null,"In above code, 1st line creates an ",(0,o.kt)("inlineCode",{parentName:"p"},"Array")," variable. This is ",(0,o.kt)("inlineCode",{parentName:"p"},"double")," type variable."),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"If you don't know what an array is, then please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-arrays"},"VBA Arrays"))," post.")),(0,o.kt)("p",null,"In 2nd line, we define the size of array. This size is ",(0,o.kt)("em",{parentName:"p"},"dynamic")," means it ",(0,o.kt)("strong",{parentName:"p"},"automatic")," in nature."),(0,o.kt)("p",null,"We don't have to give exact value every time, this code adjust the values if there is any change in our ",(0,o.kt)("em",{parentName:"p"},"Collection"),"."),(0,o.kt)("p",null,"This size of this array is ",(0,o.kt)("em",{parentName:"p"},"from")," 0 to Number of Co-ordinates in the collection."),(0,o.kt)("p",null,"In our case size of array is ",(0,o.kt)("strong",{parentName:"p"},"0 -> 30"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Loop through the collection we have\nFor i = 0 To (pointCollection.Count - 1)\n  ' Add each item of collection into our array variable\n  point(i) = pointCollection(i + 1)\nNext i\n")),(0,o.kt)("p",null,"In above code we 1st create a ",(0,o.kt)("em",{parentName:"p"},"Loop"),"."),(0,o.kt)("p",null,"This ",(0,o.kt)("em",{parentName:"p"},"Loop")," iterate ",(0,o.kt)("em",{parentName:"p"},"from 0")," to ",(0,o.kt)("em",{parentName:"p"},"pointCollection.Count - 1"),"."),(0,o.kt)("p",null,"Why ",(0,o.kt)("em",{parentName:"p"},"pointCollection.Count - 1")," ? It is because ",(0,o.kt)("em",{parentName:"p"},"pointCollection.Count")," starts from ",(0,o.kt)("em",{parentName:"p"},"1")," and our loop start with ",(0,o.kt)("em",{parentName:"p"},"0"),"."),(0,o.kt)("p",null,"Because of additional 1 count in ",(0,o.kt)("em",{parentName:"p"},"pointCollection"),", we need to remove 1 from the count."),(0,o.kt)("p",null,"Inside this loop, we add every item of ",(0,o.kt)("em",{parentName:"p"},"pointCollection")," into our ",(0,o.kt)("strong",{parentName:"p"},"point() array"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create a local variable name \"pointArray\" of variant type\nDim pointArray As Variant\n\n' Set the new created variable equal to point array variable\npointArray = point\n")),(0,o.kt)("p",null,'In 1st line of above code, we create local variable "pointArray". This variable is ',(0,o.kt)("inlineCode",{parentName:"p"},"Variant")," type."),(0,o.kt)("p",null,'In 2nd line of above code, we set the value of variable "pointArray" to value of variable "point".'),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Exit the sketch\nswSketchManager.InsertSketch True\n\n' De-select the sketch\nswDoc.ClearSelection2 True\n")),(0,o.kt)("p",null,"In 1st line of above code, we Exit the sketch."),(0,o.kt)("p",null,"In 2nd line of above code, we De-select the sketch."),(0,o.kt)(r.Z,{mdxType:"AdComponent"}),(0,o.kt)("h4",{id:"create-spline"},"Create Spline"),(0,o.kt)("p",null,"Now we have all information available for creating ",(0,o.kt)("strong",{parentName:"p"},"a Spline"),"."),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Below code sample shows how to create a Spline.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n\' Insert a sketch into "Front Plane"\nswSketchManager.InsertSketch True\n\n\' Set the value of Solidworks Sketch segment by "CreateSpline2" method from Solidworks sketch manager\nSet swSketchSegment = swSketchManager.CreateSpline2((pointArray), True)\n\n\' De-select the Spline after creation\nswDoc.ClearSelection2 True\n\n\' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit2\n\n\' Exit the sketch\nswSketchManager.InsertSketch True\n\n\' Force Re-build the model\nswDoc.Rebuild (swRebuildOptions_e.swForceRebuildAll)\n')),(0,o.kt)("p",null,(0,o.kt)("em",{parentName:"p"},"Let us understand each line of above code sample.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Selecting Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line, we select the ",(0,o.kt)("em",{parentName:"p"},"front plane")," by using ",(0,o.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,o.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,o.kt)("admonition",{type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"For more information about selection method please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."),(0,o.kt)("p",{parentName:"admonition"},"I have discussed about different ",(0,o.kt)("em",{parentName:"p"},"Selection methods")," in details in \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Soldworks Macros - Selection Methods"))," post, so do visit this post for more ",(0,o.kt)("em",{parentName:"p"},"Selection methods"),".")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Inserting a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,o.kt)("p",null,"In above line, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,o.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,o.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,o.kt)("p",null,"This method allows us to insert/exit ",(0,o.kt)("strong",{parentName:"p"},"a sketch")," in selected plane."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Set the value of Solidworks Sketch segment by "CreateSpline2" method from Solidworks sketch manager\nSet swSketchSegment = swSketchManager.CreateSpline2((pointArray), True)\n')),(0,o.kt)("p",null,"In above line we set the value of ",(0,o.kt)("em",{parentName:"p"},"Solidworks Sketch segment variable")," ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment"),"."),(0,o.kt)("p",null,"For this we use, ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateSpline2")," method from ",(0,o.kt)("em",{parentName:"p"},"Solidworks sketch manager variable")," ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchManager"),"."),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateSpline2")," method takes following parameters as explained:"),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"PointData")," : ",(0,o.kt)("em",{parentName:"p"},"Array of X,Y,Z point coordinates to use in creating the spline"),"."),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"SimulateNaturalEnds")," : ",(0,o.kt)("em",{parentName:"p"},"True to simulate natural ends, false to not simulate natural ends"),"."),(0,o.kt)("p",null,"Below Image described ",(0,o.kt)("strong",{parentName:"p"},"the Parameters for a Spline"),"."),(0,o.kt)("p",null,(0,o.kt)("img",{alt:"spline_parameters",src:n(70019).Z,width:"345",height:"331"})),(0,o.kt)("p",null,"In this ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateSpline2")," method, we pass our ",(0,o.kt)("inlineCode",{parentName:"p"},"pointArray")," variable as ",(0,o.kt)("strong",{parentName:"p"},"PointData"),"."),(0,o.kt)("p",null,"We want our spline to simulate natural ends. Hence we ",(0,o.kt)("inlineCode",{parentName:"p"},"True")," as second parameter."),(0,o.kt)("hr",null),(0,o.kt)("admonition",{title:"NOTE",type:"tip"},(0,o.kt)("p",{parentName:"admonition"},"It is ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Meter only")),"."),(0,o.kt)("p",{parentName:"admonition"},(0,o.kt)("em",{parentName:"p"},"Solidworks API")," does not care about your application's Unit systems."),(0,o.kt)("p",{parentName:"admonition"},"For example, I works in ",(0,o.kt)("strong",{parentName:"p"},"ANSI"),' system means "inches" for distance. '),(0,o.kt)("p",{parentName:"admonition"},"But when I used Solidworks API through ",(0,o.kt)("em",{parentName:"p"},"VBA macros")," or ",(0,o.kt)("em",{parentName:"p"},"C#"),", I have to use ",(0,o.kt)("strong",{parentName:"p"},"converted")," numeric values."),(0,o.kt)("p",{parentName:"admonition"},"Because Solidworks API output the distance in ",(0,o.kt)("strong",{parentName:"p"},"Meter")," only; which is not my requirement.")),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Spline after creation\nswDoc.ClearSelection2 True\n")),(0,o.kt)("p",null,"In above line, we de-select the created ",(0,o.kt)("em",{parentName:"p"},"Spline"),"."),(0,o.kt)("p",null,"For de-selecting, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),(0,o.kt)("p",null,"In above line we use ",(0,o.kt)("em",{parentName:"p"},"zoom to fit")," command."),(0,o.kt)("p",null,"For Zoom to fit, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Exit the sketch\nswSketchManager.InsertSketch True\n")),(0,o.kt)("p",null,"In above line, we exit the sketch."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Force Re-build the model\nswDoc.Rebuild (swRebuildOptions_e.swForceRebuildAll)\n")),(0,o.kt)("p",null,"In above line, we Force Re-build the model the model."),(0,o.kt)("p",null,'For "Force Re-build" we use ',(0,o.kt)("strong",{parentName:"p"},"Rebuild")," method from ",(0,o.kt)("em",{parentName:"p"},"Solidworks Document variable")," ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("p",null,"In this ",(0,o.kt)("strong",{parentName:"p"},"Rebuild")," method, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"swRebuildOptions_e.swForceRebuildAll")," option for re-build all."),(0,o.kt)("p",null,"This is it !!!"),(0,o.kt)("p",null,"It is a BIG post but I tried to explain all."),(0,o.kt)("p",null,"If you found anything to add or update, please let me know on my e-mail."),(0,o.kt)("hr",null),(0,o.kt)(r.Z,{mdxType:"AdComponent"}),(0,o.kt)("h2",{id:"vba-language-feature-used-in-this-post"},"VBA Language feature used in this post"),(0,o.kt)("p",null,"In this post used some features of ",(0,o.kt)("strong",{parentName:"p"},"VBA programming language"),"."),(0,o.kt)("p",null,"This section of post, has some brief information about the VBA programming language specific features."),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"We use ",(0,o.kt)("strong",{parentName:"p"},"Option Explicit")," for capturing un-declared variables. If you want to read more about ",(0,o.kt)("strong",{parentName:"p"},"Option Explicit")," then please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-declaring-and-scoping-of-variables"},"Declaring and Scoping of Variables")),".")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"Then we create ",(0,o.kt)("strong",{parentName:"p"},"variable")," for different data types. If you don't know about them, then please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-variables"},"Variables"))," and \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-programming-concepts/#data-types-in-vba"},"Data-types"))," posts of this blog. These posts will help you to understand what ",(0,o.kt)("strong",{parentName:"p"},"Variables")," are and how to use them.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"Then we create ",(0,o.kt)("strong",{parentName:"p"},"main Sub procedure")," for our macro. If you don't know about the ",(0,o.kt)("strong",{parentName:"p"},"Sub procedure"),", then I suggest you to visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-sub-and-function-procedure"},"VBA Sub and Function Procedures"))," and \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-executing-procedures"},"Executing Sub and Function Procedures"))," posts of this blog. These posts will help you to understand what ",(0,o.kt)("strong",{parentName:"p"},"Procedures")," are and how to use them.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"In most part we create some variables and set their values. We set those values by using some ",(0,o.kt)("strong",{parentName:"p"},"functions")," provided from objects. If you don't know about the ",(0,o.kt)("strong",{parentName:"p"},"functions"),", then you should visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-functions"},"VBA Functions"))," and \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-more-function"},"VBA Functions that do more"))," posts of this blog. These posts will help you to understand what ",(0,o.kt)("strong",{parentName:"p"},"functions")," are and how to use them.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"For creating a sequence of points and data for Spline, we use a ",(0,o.kt)("strong",{parentName:"p"},"For-Next loop"),". We use a loop to set values of x, y and z co-ordinates of each points. If you don't know about the ",(0,o.kt)("strong",{parentName:"p"},"For-Next loop"),", then you should visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-looping"},"VBA Looping"))," post of this blog. This posts will help you to understand what ",(0,o.kt)("strong",{parentName:"p"},"For-Next loop")," are and how to use them.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"For storing co-ordinates of points we use ",(0,o.kt)("strong",{parentName:"p"},"Collection"),". In an ",(0,o.kt)("strong",{parentName:"p"},"Collection"),", we store objects or data. This is very helpful and important language feature. If you don't know about the ",(0,o.kt)("strong",{parentName:"p"},"Collection"),", then you should visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/collections"},"Collections (Visual Basic)"))," from ",(0,o.kt)("strong",{parentName:"p"},"Microsoft Official Document Website"),". This will help you to understand what ",(0,o.kt)("strong",{parentName:"p"},"Collection")," are and how to use them.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"For creating Spline we use an ",(0,o.kt)("strong",{parentName:"p"},"Array"),". An ",(0,o.kt)("strong",{parentName:"p"},"Array")," is similar to ",(0,o.kt)("strong",{parentName:"p"},"Collection"),", in which we store objects or data. But Array is more basic version actually Array is a basic programming feature and used frequently ",(0,o.kt)("em",{parentName:"p"},"C and C++ programming languages"),". This is also very helpful and important language feature. If you don't know about the ",(0,o.kt)("strong",{parentName:"p"},"Array"),", then you should visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/arrays/index"},"Arrays in Visual Basic"))," from ",(0,o.kt)("strong",{parentName:"p"},"Microsoft Official Document Website"),". This will help you to understand what ",(0,o.kt)("strong",{parentName:"p"},"Array")," are and how to use them."))),(0,o.kt)("hr",null),(0,o.kt)("h2",{id:"solidworks-api-objects"},"Solidworks API Objects"),(0,o.kt)("p",null,"In this post, for creating a ",(0,o.kt)("strong",{parentName:"p"},"Point"),", we use ",(0,o.kt)("em",{parentName:"p"},"Solidworks API objects and their methods"),"."),(0,o.kt)("p",null,"This section contains the list of all ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Objects")," used in this post."),(0,o.kt)("p",null,"I have also attached links of these ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in ",(0,o.kt)("strong",{parentName:"p"},"API Help website"),"."),(0,o.kt)("p",null,"If you want to explore those objects, you can use these links."),(0,o.kt)("p",null,"These Solidworks API Objects are listed below:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("strong",{parentName:"li"},"Solidworks Application Object"))),(0,o.kt)("p",null,"If you want explore ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Application Object")," object you can visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html"},"this link")),"."),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("strong",{parentName:"li"},"Solidworks Document Object"))),(0,o.kt)("p",null,"If you want explore ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Document Object")," object you can visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html"},"this link")),"."),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("strong",{parentName:"li"},"Solidworks Sketch Manager Object"))),(0,o.kt)("p",null,"If you want explore ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")," you can visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this link")),"."),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("strong",{parentName:"li"},"Solidworks Sketches Object"))),(0,o.kt)("p",null,"If you want explore ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketches Object")," you can visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketch_members.html?verRedirect=1"},"this link")),"."),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("strong",{parentName:"li"},"Solidworks Sketch Point Object"))),(0,o.kt)("p",null,"If you want explore ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Point Object")," you can visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchPoint_members.html"},"this link")),"."),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("strong",{parentName:"li"},"Solidworks Sketch Segment Object"))),(0,o.kt)("p",null,"If you want explore ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")," you can visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"},"this link")),"."),(0,o.kt)("hr",null),(0,o.kt)("p",null,"Hope this post helps you to ",(0,o.kt)("em",{parentName:"p"},"create a Spline")," in Sketches with Solidworks VB Macros."),(0,o.kt)("p",null,"For more such tutorials on ",(0,o.kt)("strong",{parentName:"p"},"Solidworks VBA Macros"),", do come to this blog after sometime."),(0,o.kt)("p",null,"Till then, Happy learning!!!"))}c.isMDXComponent=!0},74753:(e,t,n)=>{n.d(t,{Z:()=>o});var a=n(67294);class o extends a.Component{componentDidMount(){(()=>{const e=document.createElement("script");e.src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild)})(),(window.adsbygoogle=window.adsbygoogle||[]).push({})}render(){return a.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})}}},70019:(e,t,n)=>{n.d(t,{Z:()=>a});const a=n.p+"assets/images/spline_parameters-32e91cd90eb4dc7e4ac1b5fa79a2d1b0.png"}}]);