"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[7675],{3905:function(e,t,n){n.d(t,{Zo:function(){return m},kt:function(){return u}});var a=n(67294);function o(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function r(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?r(Object(n),!0).forEach((function(t){o(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):r(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function s(e,t){if(null==e)return{};var n,a,o=function(e,t){if(null==e)return{};var n,a,o={},r=Object.keys(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var l=a.createContext({}),p=function(e){var t=a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},m=function(e){var t=p(e.components);return a.createElement(l.Provider,{value:t},e.children)},d={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},k=a.forwardRef((function(e,t){var n=e.components,o=e.mdxType,r=e.originalType,l=e.parentName,m=s(e,["components","mdxType","originalType","parentName"]),k=p(n),u=o,c=k["".concat(l,".").concat(u)]||k[u]||d[u]||r;return n?a.createElement(c,i(i({ref:t},m),{},{components:n})):a.createElement(c,i({ref:t},m))}));function u(e,t){var n=arguments,o=t&&t.mdxType;if("string"==typeof e||o){var r=n.length,i=new Array(r);i[0]=k;var s={};for(var l in t)hasOwnProperty.call(t,l)&&(s[l]=t[l]);s.originalType=e,s.mdxType="string"==typeof e?e:o,i[1]=s;for(var p=2;p<r;p++)i[p]=n[p];return a.createElement.apply(null,i)}return a.createElement.apply(null,n)}k.displayName="MDXCreateElement"},74425:function(e,t,n){n.r(t),n.d(t,{assets:function(){return d},contentTitle:function(){return p},default:function(){return c},frontMatter:function(){return l},metadata:function(){return m},toc:function(){return k}});var a=n(87462),o=n(63366),r=(n(67294),n(3905)),i=n(74753),s=["components"],l={categories:"Solidworks-macro",title:"Solidworks Macro - Create Revolved Boss/Base",permalink:"/solidworks-macros/create-revolved-feature/",tags:["Solidworks Macro"],id:"feature-create-revolve-boss"},p=void 0,m={unversionedId:"feature-create-revolve-boss",id:"feature-create-revolve-boss",title:"Solidworks Macro - Create Revolved Boss/Base",description:"",source:"@site/docs/solidworks-macros/015.2-feature-create-revolve-boss.md",sourceDirName:".",slug:"/feature-create-revolve-boss",permalink:"/solidworks-macros/feature-create-revolve-boss",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Create Revolved Boss/Base",permalink:"/solidworks-macros/create-revolved-feature/",tags:["Solidworks Macro"],id:"feature-create-revolve-boss"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Create Extrude/Boss",permalink:"/solidworks-macros/feature-create-extrude-boss"},next:{title:"Solidworks Macro - Create Sweep Base",permalink:"/solidworks-macros/feature-create-sweep-boss"}},d={},k=[{value:"Objective",id:"objective",level:2},{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"Code Sample",id:"code-sample",level:2},{value:"Prerequisite",id:"prerequisite",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:2},{value:"Method Parameters Details",id:"method-parameters-details",level:2}],u={toc:k};function c(e){var t=e.components,l=(0,o.Z)(e,s);return(0,r.kt)("wrapper",(0,a.Z)({},u,l,{components:t,mdxType:"MDXLayout"}),(0,r.kt)("h2",{id:"objective"},"Objective"),(0,r.kt)(i.Z,{mdxType:"AdComponent"}),(0,r.kt)("p",null,"In this post, I tell you about ",(0,r.kt)("em",{parentName:"p"},"how to create Revolved Boss/Base through Solidworks VBA Macros")," in a sketch."),(0,r.kt)("p",null,"In this post, I tell you about ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureRevolve2")," method from ",(0,r.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureManager")," object."),(0,r.kt)("p",null,"This method is ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"most updated"))," method, I found in ",(0,r.kt)("em",{parentName:"p"},"Solidworks API Help"),". "),(0,r.kt)("p",null,"So ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("em",{parentName:"strong"},"use this method"))," if you want to create a new ",(0,r.kt)("strong",{parentName:"p"},"Revolved Boss/Base"),"."),(0,r.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,r.kt)("p",null,"Please see below video \ud83c\udfac on ",(0,r.kt)("strong",{parentName:"p"},"how to create Revolved Boss/Base")," from Solidworks VBA Macros."),(0,r.kt)("iframe",{src:"https://www.youtube.com/embed/oOsEvLge_0s",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,r.kt)("p",null,"Please note that there are ",(0,r.kt)("strong",{parentName:"p"},"no explaination")," in the video. "),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,r.kt)("h2",{id:"code-sample"},"Code Sample"),(0,r.kt)("p",null,"Below is the ",(0,r.kt)("inlineCode",{parentName:"p"},"code")," sample for creating ",(0,r.kt)("em",{parentName:"p"},"Revolved Boss/Base"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Creating variable for Solidworks Feature\nDim swFeature As SldWorks.Feature\n' Boolean Variable\nDim boolStatus As Boolean\n\n' Revolve Boss/Extrude program\nSub main()\n\n  ' Setting Solidworks variable to current application\n  Set swApp = Application.SldWorks\n  \n  ' Check if Solidworks is opened or not\n  If swApp Is Nothing Then\n      MsgBox (\"Solidworks is not opened\")\n      Exit Sub\n  End If\n  \n  ' Setting Solidworks document variable to opened part document\n  Set swDoc = swApp.ActiveDoc\n  \n  ' Check if Solidworks document is opened or not\n  If swDoc Is Nothing Then\n      MsgBox (\"Solidworks document is not opened. Please open a document.\")\n      Exit Sub\n  End If\n  \n  '-----------------------BELOW IS THE SOLUTION----------------------------------------\n\n  ' Local variables used as Conversion Factors\n  Dim LengthConversionFactor As Double\n  Dim AngleConversionFactor As Double\n\n  ' Use a Select Case, to get the length of active Unit and set the different factors\n  Select Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n    \n    Case swMETER    ' If length is in Meter\n      LengthConversionFactor = 1\n      AngleConversionFactor = 1\n    \n    Case swMM       ' If length is in MM\n      LengthConversionFactor = 1 / 1000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swCM       ' If length is in CM\n      LengthConversionFactor = 1 / 100\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swINCHES   ' If length is in INCHES\n      LengthConversionFactor = 1 * 0.0254\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEET     ' If length is in FEET\n      LengthConversionFactor = 1 * (0.0254 * 12)\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEETINCHES     ' If length is in FEET & INCHES\n      LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swANGSTROM        ' If length is in ANGSTROM\n      LengthConversionFactor = 1 / 10000000000#\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swNANOMETER       ' If length is in NANOMETER\n      LengthConversionFactor = 1 / 1000000000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swMICRON       ' If length is in MICRON\n      LengthConversionFactor = 1 / 1000000\n      AngleConversionFactor = 1 * 0.01745329\n  End Select\n  \n  '----------------------------------------------------------------\n  \n  ' Select Sketch 1 in opened part document\n  boolStatus = swDoc.Extension.SelectByID2(\"Sketch1\", \"SKETCH\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Check if failed to select sketch 1\n  If boolStatus = False Then\n      MsgBox (\"Failed to select sketch 1.\")\n      Exit Sub\n  End If    \n  \n  ' Create Revolve Feature\n  Set swFeature = swDoc.FeatureManager.FeatureRevolve2(True, True, False, False, False, True, swEndConditions_e.swEndCondBlind, swEndConditions_e.swEndCondBlind, AngleConversionFactor * 360, 0, False, False, 0, 0, swThinWallType_e.swThinWallOneDirection, 0, 0, True, False, True)\n  \n  ' Check if Revolve Feature creates or not\n  If swFeature Is Nothing Then\n      MsgBox (\"Failed to create Revolve Feature.\")\n      Exit Sub\n  End If\n    \nEnd Sub\n")),(0,r.kt)("h2",{id:"prerequisite"},"Prerequisite"),(0,r.kt)("p",null,"In this article there are some ",(0,r.kt)("em",{parentName:"p"},"prerequisite"),"."),(0,r.kt)("p",null,"We are ",(0,r.kt)("strong",{parentName:"p"},"not")," creating sketches from code but we use ",(0,r.kt)("strong",{parentName:"p"},"existing sketch")," to ",(0,r.kt)("em",{parentName:"p"},"create Revolve feature"),"."),(0,r.kt)("p",null,"Also, we will apply checks in this article, so that code we write should be error free."),(0,r.kt)(i.Z,{mdxType:"AdComponent"}),(0,r.kt)("h2",{id:"understanding-the-code"},"Understanding the Code"),(0,r.kt)("p",null,"Now let us walk through ",(0,r.kt)("strong",{parentName:"p"},"each line")," in the above code, and ",(0,r.kt)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),(0,r.kt)("p",null,"I also give some link so that you can go through them if there are anything I explained in previous posts."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,r.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,r.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"For more information please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,r.kt)("p",null,"In this line, we create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,r.kt)("p",null,"In this line, we create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Creating variable for Solidworks Feature\nDim swFeature As SldWorks.Feature\n")),(0,r.kt)("p",null,"In this line, we Create a variable which we named as ",(0,r.kt)("inlineCode",{parentName:"p"},"swFeature")," and the type of this ",(0,r.kt)("inlineCode",{parentName:"p"},"swFeature")," variable is ",(0,r.kt)("inlineCode",{parentName:"p"},"SldWorks.Feature"),"."),(0,r.kt)("p",null,"We create variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swFeature")," for ",(0,r.kt)("strong",{parentName:"p"},"Solidworks Feature"),"."),(0,r.kt)("p",null,"To see methods and properties related to ",(0,r.kt)("inlineCode",{parentName:"p"},"Feature")," object, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeature_members.html"},"this page of Solidworks API Help"))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,r.kt)("p",null,"In this line, we create a variable named ",(0,r.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,r.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,r.kt)("p",null,"These all are our global variables."),(0,r.kt)("p",null,"As you can see in code sample, they are ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,r.kt)("p",null,"So basically I group all the ",(0,r.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,r.kt)("p",null,"I have also place ",(0,r.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",(0,r.kt)("em",{parentName:"p"},"need")," this variable frequently."),(0,r.kt)("p",null,"Thus, I have started placing it here."),(0,r.kt)("p",null,"Next is our ",(0,r.kt)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",(0,r.kt)("inlineCode",{parentName:"p"},"main"),". "),(0,r.kt)("p",null,"This procedure hold all the ",(0,r.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,r.kt)("p",null,"In this line, we set the value of our Solidworks variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Solidworks is opened or not\nIf swApp Is Nothing Then\n  MsgBox ("Solidworks is not opened")\n  Exit Sub\nEnd If\n')),(0,r.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if Solidworks application variable is ",(0,r.kt)("em",{parentName:"p"},"successfully assigned")," to current Solidworks application."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Setting Solidworks document variable to opened part document\nSet swDoc = swApp.ActiveDoc\n")),(0,r.kt)("p",null,"In above line of code, we set Solidwors document ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to currently open part document."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Solidworks document is opened or not\nIf swDoc Is Nothing Then\n  MsgBox ("Solidworks document is not opened. Please open a document.")\n  Exit Sub\nEnd If\n')),(0,r.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if Solidworks document ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," is opened."),(0,r.kt)("p",null,"If Solidworks document is not opened then code execute inside the code and inform the user by a \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,r.kt)("p",null,"After showing message our program ",(0,r.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"'-----------------------BELOW IS THE SOLUTION----------------------------------------\n\n' Local variables used as Conversion Factors\nDim LengthConversionFactor As Double\nDim AngleConversionFactor As Double\n\n' Use a Select Case, to get the length of active Unit and set the different factors\nSelect Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n  \n  Case swMETER    ' If length is in Meter\n    LengthConversionFactor = 1\n    AngleConversionFactor = 1\n  \n  Case swMM       ' If length is in MM\n    LengthConversionFactor = 1 / 1000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swCM       ' If length is in CM\n    LengthConversionFactor = 1 / 100\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swINCHES   ' If length is in INCHES\n    LengthConversionFactor = 1 * 0.0254\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEET     ' If length is in FEET\n    LengthConversionFactor = 1 * (0.0254 * 12)\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEETINCHES     ' If length is in FEET & INCHES\n    LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swANGSTROM        ' If length is in ANGSTROM\n    LengthConversionFactor = 1 / 10000000000#\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swNANOMETER       ' If length is in NANOMETER\n    LengthConversionFactor = 1 / 1000000000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swMICRON       ' If length is in MICRON\n    LengthConversionFactor = 1 / 1000000\n    AngleConversionFactor = 1 * 0.01745329\nEnd Select\n\n'----------------------------------------------------------------\n")),(0,r.kt)("p",null,"In above line of code, we get and update unit conversion variable as per document unit."),(0,r.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"For more detail about why we are using this code sample, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/unit-correction/"},"Solidworks Macro - Fix Unit Issue"))," article."))),(0,r.kt)("p",null,"In this line, we set the value of our variable to new document."),(0,r.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"For ",(0,r.kt)("strong",{parentName:"p"},"detailed information")," about these lines please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Sketch 1 in opened part document\nboolStatus = swDoc.Extension.SelectByID2("Sketch1", "SKETCH", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,r.kt)("p",null,"In above line, we select the ",(0,r.kt)("em",{parentName:"p"},"Sketch1")," by using ",(0,r.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,r.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,r.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"For more information about selection method please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if failed to select sketch 1\nIf boolStatus = False Then\n    MsgBox ("Failed to select sketch 1.")\n    Exit Sub\nEnd If \n')),(0,r.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if we able to select the ",(0,r.kt)("inlineCode",{parentName:"p"},"Sketch1")," or not."),(0,r.kt)("p",null,"If we failed to select then inform the user by a \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,r.kt)("p",null,"After showing error message our program ",(0,r.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create Revolve Feature\nSet swFeature = swDoc.FeatureManager.FeatureRevolve2(True, True, False, False, False, True, swEndConditions_e.swEndCondBlind, swEndConditions_e.swEndCondBlind, AngleConversionFactor * 360, 0, False, False, 0, 0, swThinWallType_e.swThinWallOneDirection, 0, 0, True, False, True)\n")),(0,r.kt)("p",null,"In above line of code we set the value of variable ",(0,r.kt)("inlineCode",{parentName:"p"},"swFeature")," by ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureRevolve2")," method."),(0,r.kt)("p",null,(0,r.kt)("inlineCode",{parentName:"p"},"FeatureRevolve2")," method is part of ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureManager")," object."),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureManager")," is again part of ",(0,r.kt)("inlineCode",{parentName:"p"},"swDoc")," variable i.e. ",(0,r.kt)("inlineCode",{parentName:"p"},"ModelDoc2")," object."),(0,r.kt)(i.Z,{mdxType:"AdComponent"}),(0,r.kt)("h2",{id:"method-parameters-details"},"Method Parameters Details"),(0,r.kt)("p",null,"This ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureRevolve2")," method takes following parameters as explained:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"SingleDir")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," if the revolve is in one direction, ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," if in both directions"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"IsSolid")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," if this is a ",(0,r.kt)("strong",{parentName:"em"},"Solid")," revolve feature, ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," if not.")," ")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"IsThin")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," if this is a ",(0,r.kt)("strong",{parentName:"em"},"Thin")," revolve feature, ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," if not.")," ")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"IsCut")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," if this is a ",(0,r.kt)("strong",{parentName:"em"},"Cut")," revolve feature, ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," if not.")," ")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"ReverseDir")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," reverses the angle of the revolution, ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," does not; only applies if ",(0,r.kt)("inlineCode",{parentName:"em"},"Dir1Type")," is not ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondMidPlane"),".")," ")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"BothDirectionUpToSameEntity")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," if the revolve is up to the same entity in both directions, ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," if not; only applies if ",(0,r.kt)("inlineCode",{parentName:"em"},"SingleDir")," is ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," and ",(0,r.kt)("inlineCode",{parentName:"em"},"Dir1Type")," and ",(0,r.kt)("inlineCode",{parentName:"em"},"Dir2Type")," are ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondUpToVertex"),", ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondUpToSurface"),", or ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"),")."))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Dir1Type")," - ",(0,r.kt)("em",{parentName:"p"},"Revolve end condition in ",(0,r.kt)("strong",{parentName:"em"},"direction 1")," as defined in ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e"),".")," "),(0,r.kt)("p",{parentName:"li"},"End Conditions has following enumeration values:"),(0,r.kt)("ul",{parentName:"li"},(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondBlind")," or ",(0,r.kt)("strong",{parentName:"p"},"0"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondMidPlane")," or ",(0,r.kt)("strong",{parentName:"p"},"6"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondOffsetFromSurface")," or ",(0,r.kt)("strong",{parentName:"p"},"5"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondThroughAll")," or ",(0,r.kt)("strong",{parentName:"p"},"1"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondThroughAllBoth")," or ",(0,r.kt)("strong",{parentName:"p"},"9"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondThroughNext")," or ",(0,r.kt)("strong",{parentName:"p"},"2"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondUpToBody")," or ",(0,r.kt)("strong",{parentName:"p"},"7"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondUpToNext")," or ",(0,r.kt)("strong",{parentName:"p"},"11"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondUpToSelection")," or ",(0,r.kt)("strong",{parentName:"p"},"10"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondUpToSurface")," or ",(0,r.kt)("strong",{parentName:"p"},"4")," = Do not use; superseded by ",(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondUpToSelection"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondUpToVertex")," or ",(0,r.kt)("strong",{parentName:"p"},"3")," = Do not use; superseded by ",(0,r.kt)("inlineCode",{parentName:"p"},"swEndCondUpToSelection"))))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Dir2Type")," - ",(0,r.kt)("em",{parentName:"p"},"Revolve end condition in ",(0,r.kt)("strong",{parentName:"em"},"direction 2"),"; as defined in ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e")," and only applies if ",(0,r.kt)("inlineCode",{parentName:"em"},"Dir1Type")," is not ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondMidPlane"),".")," ")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Dir1Angle")," - ",(0,r.kt)("em",{parentName:"p"},"Angle in radians of revolution in ",(0,r.kt)("strong",{parentName:"em"},"direction 1"),"; only applies if ",(0,r.kt)("inlineCode",{parentName:"em"},"Dir1Type")," is ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondBlind"),"."))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Dir2Angle")," - ",(0,r.kt)("em",{parentName:"p"},"Angle in radians of revolution in ",(0,r.kt)("strong",{parentName:"em"},"direction 2"),"; only applies if ",(0,r.kt)("inlineCode",{parentName:"em"},"Dir2Type")," is ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondBlind"),"."))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"OffsetReverse1")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," to reverse the offset direction in ",(0,r.kt)("strong",{parentName:"em"},"direction 1"),", ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," to not; only applies if ",(0,r.kt)("inlineCode",{parentName:"em"},"Dir1Type")," is ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"),"."))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"OffsetReverse2")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," to reverse the offset direction in ",(0,r.kt)("strong",{parentName:"em"},"direction 2"),", ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," to not; only applies if ",(0,r.kt)("inlineCode",{parentName:"em"},"Dir2Type")," is ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"),"."))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"OffsetDistance1")," - ",(0,r.kt)("em",{parentName:"p"},"Offset distance in ",(0,r.kt)("strong",{parentName:"em"},"direction 1"),"; only applies if ",(0,r.kt)("inlineCode",{parentName:"em"},"Dir1Type")," is ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"),"."))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"OffsetDistance2")," - ",(0,r.kt)("em",{parentName:"p"},"Offset distance in ",(0,r.kt)("strong",{parentName:"em"},"direction 2"),"; only applies if ",(0,r.kt)("inlineCode",{parentName:"em"},"Dir2Type")," is ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondOffsetFromSurface"),"."),"  ")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"ThinType")," - ",(0,r.kt)("em",{parentName:"p"},"Type and direction as defined in ",(0,r.kt)("inlineCode",{parentName:"em"},"swThinWallType_e"),"."),"  "),(0,r.kt)("p",{parentName:"li"},"Thin wall types has following enumeration values:"),(0,r.kt)("ul",{parentName:"li"},(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swThinWallMidPlane")," or ",(0,r.kt)("strong",{parentName:"p"},"2"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swThinWallOneDirection")," or ",(0,r.kt)("strong",{parentName:"p"},"0"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swThinWallOppDirection")," or ",(0,r.kt)("strong",{parentName:"p"},"1"))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("inlineCode",{parentName:"p"},"swThinWallTwoDirection")," or ",(0,r.kt)("strong",{parentName:"p"},"3"))))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"ThinThickness1")," - ",(0,r.kt)("em",{parentName:"p"},"Wall thickness in ",(0,r.kt)("strong",{parentName:"em"},"direction 1")," (if ThinType is ",(0,r.kt)("inlineCode",{parentName:"em"},"swThinWallType_e.swThinWallMidPlane"),", (ThinThickness1)/2 is used for each direction)."))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"ThinThickness2")," - ",(0,r.kt)("em",{parentName:"p"},"Wall thickness in ",(0,r.kt)("strong",{parentName:"em"},"direction 2")," (only applies if ThinType is ",(0,r.kt)("inlineCode",{parentName:"em"},"swThinWallType_e.swThinWallTwoDirection"),").")," ")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Merge")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," to merge the results into a multi-body part, ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," to not.")," ")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"UseFeatScope")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," if the feature only affects selected bodies, ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," if the feature affects all bodies.")," ")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"UseAutoSelect")," - ",(0,r.kt)("em",{parentName:"p"},(0,r.kt)("inlineCode",{parentName:"em"},"True")," to automatically select all bodies and have the feature affect those bodies, ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," to select the bodies or components that the feature affects.")," "))),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"Return Value")," : This ",(0,r.kt)("inlineCode",{parentName:"p"},"FeatureRevolve2")," method retun ",(0,r.kt)("inlineCode",{parentName:"p"},"Feature")," object."),(0,r.kt)("p",null,"To see methods and properties related to ",(0,r.kt)("inlineCode",{parentName:"p"},"Feature")," object, please visit \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeature_members.html"},"this page of Solidworks API Help")),"."),(0,r.kt)("p",null,"In our code, I have used following values:"),(0,r.kt)("ul",null,(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"SingleDir")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"True")," for revolve is in one direction"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"IsSolid")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"True")," for ",(0,r.kt)("strong",{parentName:"em"},"Solid")," revolve feature"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"IsThin")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," for ",(0,r.kt)("strong",{parentName:"em"},"Thin")," revolve feature"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"IsCut")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," for ",(0,r.kt)("strong",{parentName:"em"},"Cut")," revolve feature"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"ReverseDir")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," for reverses the angle of the revolution"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"BothDirectionUpToSameEntity")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"True")," for revolve is up to the same entity in both directions"),"."),(0,r.kt)("div",{parentName:"li",className:"admonition admonition-tip alert alert--success"},(0,r.kt)("div",{parentName:"div",className:"admonition-heading"},(0,r.kt)("h5",{parentName:"div"},(0,r.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,r.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,r.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,r.kt)("div",{parentName:"div",className:"admonition-content"},(0,r.kt)("p",{parentName:"div"},"Since ",(0,r.kt)("strong",{parentName:"p"},"SingleDir")," is ",(0,r.kt)("inlineCode",{parentName:"p"},"True"),", setting the value to ",(0,r.kt)("inlineCode",{parentName:"p"},"True")," is invalid.")))),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Dir1Type")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondBlind")," for Revolve end condition in direction 1"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Dir2Type")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"swEndConditions_e.swEndCondBlind")," for Revolve end condition in direction 2"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Dir1Angle")," - ",(0,r.kt)("em",{parentName:"p"},"I use `AngleConversionFactor ")," 360` for Angle in radians of revolution in direction 1*.")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Dir2Angle")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"0")," for Angle in radians of revolution in direction 2"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"OffsetReverse1")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," for reverse the offset direction in direction 1"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"OffsetReverse2")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," for reverse the offset direction in direction 2"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"OffsetDistance1")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"0")," for Offset distance in direction 1"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"OffsetDistance2")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"0")," for Offset distance in direction 2"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"ThinType")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"swThinWallType_e.swThinWallOneDirection")," for Type and direction"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"ThinThickness1")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"0")," for Wall thickness in direction 1"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"ThinThickness2")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"0")," for Wall thickness in direction 2"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"Merge")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"True")," for merge the results into a multi-body part"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"UseFeatScope")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"False")," for the feature affects all bodies"),".")),(0,r.kt)("li",{parentName:"ul"},(0,r.kt)("p",{parentName:"li"},(0,r.kt)("strong",{parentName:"p"},"UseAutoSelect")," - ",(0,r.kt)("em",{parentName:"p"},"I use ",(0,r.kt)("inlineCode",{parentName:"em"},"True")," for automatically select all bodies and have the feature affect those bodies"),"."))),(0,r.kt)("pre",null,(0,r.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Check if Revolve Feature creates or not\nIf swFeature Is Nothing Then\n    MsgBox ("Failed to create Revolve Feature.")\n    Exit Sub\nEnd If\n')),(0,r.kt)("p",null,"In above line of code, we use an \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-if-then-structure-select-case/"},"IF statement"))," to check if we able to create Revolve Feature or not."),(0,r.kt)("p",null,"If we failed to select then inform the user by a \ud83d\ude80 ",(0,r.kt)("strong",{parentName:"p"},(0,r.kt)("a",{parentName:"strong",href:"/vba/vba-msgBox-function/"},"Message Window")),"."),(0,r.kt)("p",null,"After showing error message our program ",(0,r.kt)("strong",{parentName:"p"},"exit")," from here itself."),(0,r.kt)("p",null,"Now we run the macro and after running macro we get extrude as shown in below image."),(0,r.kt)("p",null,(0,r.kt)("a",{target:"_blank",href:n(7779).Z},(0,r.kt)("img",{alt:"final_Image",src:n(36343).Z,width:"1127",height:"557"}))),(0,r.kt)("hr",null),(0,r.kt)("p",null,(0,r.kt)("strong",{parentName:"p"},"This is it !!!")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"I hope my efforts will helpful to someone!")),(0,r.kt)("p",null,"If you found anything to ",(0,r.kt)("strong",{parentName:"p"},"add or update"),", please let me know on my ",(0,r.kt)("em",{parentName:"p"},"e-mail"),"."),(0,r.kt)("p",null,"Hope this post helps you to ",(0,r.kt)("strong",{parentName:"p"},"create Revolve Boss")," with Solidworks VBA Macros."),(0,r.kt)("p",null,"For more such tutorials on ",(0,r.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Do let me know by you like this post or not!")),(0,r.kt)("p",null,(0,r.kt)("em",{parentName:"p"},"Till then, Happy learning!!!")))}c.isMDXComponent=!0},74753:function(e,t,n){n.d(t,{Z:function(){return r}});var a=n(94578),o=n(67294),r=function(e){function t(){return e.apply(this,arguments)||this}(0,a.Z)(t,e);var n=t.prototype;return n.componentDidMount=function(){var e;(e=document.createElement("script")).src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild),(window.adsbygoogle=window.adsbygoogle||[]).push({})},n.render=function(){return o.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})},t}(o.Component)},7779:function(e,t,n){t.Z=n.p+"assets/files/final_Image-0a28fe7981f9b16587388d8c37563bfc.svg"},36343:function(e,t,n){t.Z=n.p+"assets/images/final_Image-0a28fe7981f9b16587388d8c37563bfc.svg"}}]);