"use strict";(self.webpackChunkdocs_website=self.webpackChunkdocs_website||[]).push([[828],{3905:function(e,t,n){n.d(t,{Zo:function(){return m},kt:function(){return c}});var a=n(67294);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function o(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?o(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):o(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function s(e,t){if(null==e)return{};var n,a,r=function(e,t){if(null==e)return{};var n,a,r={},o=Object.keys(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||(r[n]=e[n]);return r}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(r[n]=e[n])}return r}var l=a.createContext({}),p=function(e){var t=a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},m=function(e){var t=p(e.components);return a.createElement(l.Provider,{value:t},e.children)},k={inlineCode:"code",wrapper:function(e){var t=e.children;return a.createElement(a.Fragment,{},t)}},d=a.forwardRef((function(e,t){var n=e.components,r=e.mdxType,o=e.originalType,l=e.parentName,m=s(e,["components","mdxType","originalType","parentName"]),d=p(n),c=r,u=d["".concat(l,".").concat(c)]||d[c]||k[c]||o;return n?a.createElement(u,i(i({ref:t},m),{},{components:n})):a.createElement(u,i({ref:t},m))}));function c(e,t){var n=arguments,r=t&&t.mdxType;if("string"==typeof e||r){var o=n.length,i=new Array(o);i[0]=d;var s={};for(var l in t)hasOwnProperty.call(t,l)&&(s[l]=t[l]);s.originalType=e,s.mdxType="string"==typeof e?e:r,i[1]=s;for(var p=2;p<o;p++)i[p]=n[p];return a.createElement.apply(null,i)}return a.createElement.apply(null,n)}d.displayName="MDXCreateElement"},19920:function(e,t,n){n.r(t),n.d(t,{assets:function(){return k},contentTitle:function(){return p},default:function(){return u},frontMatter:function(){return l},metadata:function(){return m},toc:function(){return d}});var a=n(87462),r=n(63366),o=(n(67294),n(3905)),i=n(74753),s=["components"],l={categories:"Solidworks-macro",title:"Solidworks Macro - Mirror Sketch Entities",permalink:"/solidworks-macros/mirror-entities/",tags:["Solidworks Macro"],id:"mirror-entities"},p=void 0,m={unversionedId:"mirror-entities",id:"mirror-entities",title:"Solidworks Macro - Mirror Sketch Entities",description:"",source:"@site/docs/solidworks-macros/010.2-mirror-entities.md",sourceDirName:".",slug:"/mirror-entities",permalink:"/solidworks-macros/mirror-entities",draft:!1,tags:[{label:"Solidworks Macro",permalink:"/solidworks-macros/tags/solidworks-macro"}],version:"current",frontMatter:{categories:"Solidworks-macro",title:"Solidworks Macro - Mirror Sketch Entities",permalink:"/solidworks-macros/mirror-entities/",tags:["Solidworks Macro"],id:"mirror-entities"},sidebar:"tutorialSidebar",previous:{title:"Solidworks Macro - Offset Sketch Entities",permalink:"/solidworks-macros/offset-entities"},next:{title:"Solidworks Macro - Linear Sketch Pattern",permalink:"/solidworks-macros/linear-skech-pattern"}},k={},d=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",level:2},{value:"For Experience Macro Developer",id:"for-experience-macro-developer",level:2},{value:"For Beginners Macro Developers",id:"for-beginners-macro-developers",level:2},{value:"Understanding the Code",id:"understanding-the-code",level:3},{value:"VBA Language feature used in this post",id:"vba-language-feature-used-in-this-post",level:2},{value:"Solidworks API Objects",id:"solidworks-api-objects",level:2}],c={toc:d};function u(e){var t=e.components,l=(0,r.Z)(e,s);return(0,o.kt)("wrapper",(0,a.Z)({},c,l,{components:t,mdxType:"MDXLayout"}),(0,o.kt)(i.Z,{mdxType:"AdComponent"}),(0,o.kt)("p",null,"In this post, I tell you about ",(0,o.kt)("em",{parentName:"p"},"how to Mirror Sketch Entities using Solidworks VBA Macros")," in a Sketch."),(0,o.kt)("hr",null),(0,o.kt)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),(0,o.kt)("p",null,"Please see below video \ud83c\udfac how visually we ",(0,o.kt)("em",{parentName:"p"},"Mirror Sketch Entities")," in ",(0,o.kt)("strong",{parentName:"p"},"Solidworks VBA macro"),"."),(0,o.kt)("iframe",{src:"https://www.youtube.com/embed/iVCCMKYgxcA",frameborder:"0",allowfullscreen:!0,width:"100%",height:"500"}),(0,o.kt)("p",null,"Please note that there are ",(0,o.kt)("strong",{parentName:"p"},"no explaination")," given in the video. "),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),(0,o.kt)("hr",null),(0,o.kt)("h2",{id:"for-experience-macro-developer"},"For Experience Macro Developer"),(0,o.kt)("p",null,"If you are an experience ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Macro developer"),", then you are looking for a specific code sample."),(0,o.kt)("p",null,"Below is the code for ",(0,o.kt)("strong",{parentName:"p"},"Mirror Sketch Entities")," from ",(0,o.kt)("strong",{parentName:"p"},"Solidworks VBA Macro"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Boolean Variable\nDim BoolStatus As Boolean\n\n\' Select Center Line for Mirror\nBoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, False, 2, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n\' Select Circle we want to Mirror\nBoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n\' Mirror Selected Sketch entities\nswDoc.SketchMirror\n')),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Method Name"),": ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchMirror")),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Description"),": ",(0,o.kt)("em",{parentName:"p"},"Mirrors")," the selected sketch entities with reference from a Centerline."),(0,o.kt)("p",null,"For ",(0,o.kt)("strong",{parentName:"p"},"Mirror")," Solidworks Sketch entities, first we need following things:"),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"Sketch Entity/Entities to ",(0,o.kt)("em",{parentName:"p"},"Mirror"))),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"A Centerline"),", from which we ",(0,o.kt)("em",{parentName:"p"},"Mirror")," the sketch entities"))),(0,o.kt)("p",null,"If you want more detailed explaination then please read further otherwise this will help you to ",(0,o.kt)("strong",{parentName:"p"},"Mirror Sketch Entities From VBA Macro"),"."),(0,o.kt)("hr",null),(0,o.kt)(i.Z,{mdxType:"AdComponent"}),(0,o.kt)("h2",{id:"for-beginners-macro-developers"},"For Beginners Macro Developers"),(0,o.kt)("p",null,"In this post, I tell you about ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchMirror")," method from ",(0,o.kt)("strong",{parentName:"p"},"Solidworks")," ",(0,o.kt)("inlineCode",{parentName:"p"},"ModelDoc2")," object."),(0,o.kt)("p",null,"This method is ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"easiest"))," method, I found in ",(0,o.kt)("em",{parentName:"p"},"Solidworks API Help"),". "),(0,o.kt)("p",null,"So ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"use this method"))," if you want to ",(0,o.kt)("em",{parentName:"p"},"Mirror Sketches"),"."),(0,o.kt)("p",null,"Below is the ",(0,o.kt)("inlineCode",{parentName:"p"},"code")," sample for ",(0,o.kt)("em",{parentName:"p"},"Mirror Sketches"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Set Sketch Segment value and Create a Center Line\n  Set swSketchSegment = swSketchManager.CreateCenterLine(0, 0, 0, 0, 1, 0)\n  \n  ' Set Sketch Segment value and Create a Circle\n  Set swSketchSegment = swSketchManager.CreateCircleByRadius(-0.75, 0, 0, 0.2)\n  \n  ' De-select the lines after creation\n  swDoc.ClearSelection2 True\n  \n  ' Select Center Line for Mirror\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line1\", \"SKETCHSEGMENT\", 0, 0, 0, False, 2, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Select Circle we want to Mirror\n  BoolStatus = swDoc.Extension.SelectByID2(\"Arc1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Mirror Selected Sketch entities\n  swDoc.SketchMirror\n\n  ' De-select the Sketch Segment after Mirror\n  swDoc.ClearSelection2 True\n  \n  ' Show Front View after Mirror Sketch Segments\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n\nEnd Sub\n")),(0,o.kt)("hr",null),(0,o.kt)("h3",{id:"understanding-the-code"},"Understanding the Code"),(0,o.kt)("p",null,"Now let us walk through ",(0,o.kt)("strong",{parentName:"p"},"each line")," in the above code, and ",(0,o.kt)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),(0,o.kt)("p",null,"I also give some link so that you can go through them if there are anything I explained in previous posts."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"Option Explicit\n")),(0,o.kt)("p",null,"This line forces us to define every variable we are going to use. "),(0,o.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"For more information please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),(0,o.kt)("p",null,"In this line, we create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),(0,o.kt)("p",null,"In this line, we create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Boolean Variable\nDim BoolStatus As Boolean\n")),(0,o.kt)("p",null,"In this line, we create a variable named ",(0,o.kt)("inlineCode",{parentName:"p"},"BoolStatus")," as ",(0,o.kt)("inlineCode",{parentName:"p"},"Boolean")," object type."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),(0,o.kt)("p",null,"In above line, we create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchManager")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,o.kt)("p",null,"As the name suggested, a ",(0,o.kt)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",(0,o.kt)("em",{parentName:"p"},"Sketches"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this page of Solidworks API Help"))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n")),(0,o.kt)("p",null,"In this line, we Create a variable which we named as ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," and the type of this ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," variable is ",(0,o.kt)("inlineCode",{parentName:"p"},"SldWorks.SketchSegment"),"."),(0,o.kt)("p",null,"We create variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," for ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Segments"),"."),(0,o.kt)("p",null,"To see methods and properties related to ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," object, please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"},"this page of Solidworks API Help"))),(0,o.kt)("p",null,"These all are our global variables."),(0,o.kt)("p",null,"As you can see in code sample, they are ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects"),"."),(0,o.kt)("p",null,"So basically I group all the ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),(0,o.kt)("p",null,"I have also place ",(0,o.kt)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",(0,o.kt)("em",{parentName:"p"},"need")," this variable frequently."),(0,o.kt)("p",null,"Thus, I have started placing it here."),(0,o.kt)("p",null,"Next is our ",(0,o.kt)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",(0,o.kt)("inlineCode",{parentName:"p"},"main"),". "),(0,o.kt)("p",null,"This procedure hold all the ",(0,o.kt)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),(0,o.kt)("p",null,"In this line, we set the value of our Solidworks variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Create string type variable for storing default part location\nDim defaultTemplate As String\n' Set value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),(0,o.kt)("p",null,"In 1st statement of above example, we are defining a variable of ",(0,o.kt)("inlineCode",{parentName:"p"},"string")," type and named it as ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),(0,o.kt)("p",null,"This variable ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",(0,o.kt)("strong",{parentName:"p"},"Default Part Template"),"."),(0,o.kt)("p",null,"In 2nd line of above example. we assign value to our newly define ",(0,o.kt)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),(0,o.kt)("p",null,"We assign the value by using a ",(0,o.kt)("em",{parentName:"p"},"Method")," named ",(0,o.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," method is a part of our main Solidworks variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swApp"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),(0,o.kt)("p",null,"In this line, we set the value of our ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),(0,o.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"For ",(0,o.kt)("strong",{parentName:"p"},"detailed information")," about these lines please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post."),(0,o.kt)("p",{parentName:"div"},"I have discussed them ",(0,o.kt)("strong",{parentName:"p"},"thoroghly")," in \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/open-new-document"},"Solidworks Macros - Open new Part document"))," post, so do checkout that post if you want to understand above code in more detail."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line, we select the ",(0,o.kt)("em",{parentName:"p"},"front plane")," by using ",(0,o.kt)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",(0,o.kt)("inlineCode",{parentName:"p"},"Extension")," object."),(0,o.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"For more information about selection method please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/select-plane-from-tree"},"Solidworks Macros - Selection Methods"))," post."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),(0,o.kt)("p",null,"In above line, we set the ",(0,o.kt)("em",{parentName:"p"},"Sketch manager")," variable to ",(0,o.kt)("em",{parentName:"p"},"current document's sketch manager"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Insert a sketch into selected plane\nswSketchManager.InsertSketch True\n")),(0,o.kt)("p",null,"In above line, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",(0,o.kt)("em",{parentName:"p"},"SketchManager")," and give ",(0,o.kt)("inlineCode",{parentName:"p"},"True")," value."),(0,o.kt)("p",null,"This method allows us to insert a sketch in selected plane."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch Segment value and Create a Center Line\nSet swSketchSegment = swSketchManager.CreateCenterLine(0, 0, 0, 0, 1, 0)\n")),(0,o.kt)("p",null,"In above line, we set the value of Solidworks Sketch Segment variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swSketchSegment")," by ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateCenterLine")," method from ",(0,o.kt)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateCenterLine")," method creates a Center Line between 2 given points."),(0,o.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"tip")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"For more information about ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateCenterLine")," method, you can read my \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/solidworks-macros/sketch-create-centerline"},"Solidworks Sketch Macros - Create CenterLines"))," post."))),(0,o.kt)("p",null,"That post describe all the parameters we need for this ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateCenterLine")," method in details."),(0,o.kt)("p",null,"In above line, we create a Line between ",(0,o.kt)("strong",{parentName:"p"},"point (0, 0, 0)")," and ",(0,o.kt)("strong",{parentName:"p"},"point (0, 1, 0)"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Set Sketch Segment value and Create a Circle\nSet swSketchSegment = swSketchManager.CreateCircleByRadius(-0.75, 0, 0, 0.2)\n")),(0,o.kt)("p",null,"In above line we create ",(0,o.kt)("em",{parentName:"p"},"a Circle")," by using same ",(0,o.kt)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method from ",(0,o.kt)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),(0,o.kt)("p",null,"In above code, we create ",(0,o.kt)("em",{parentName:"p"},"a Circle")," at ",(0,o.kt)("strong",{parentName:"p"},"point (0, 0, 0)")," with a radius of ",(0,o.kt)("strong",{parentName:"p"},"0.2"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the lines after creation\nswDoc.ClearSelection2 True\n")),(0,o.kt)("p",null,"After creating both entities we ",(0,o.kt)("em",{parentName:"p"},"de-select")," them."),(0,o.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"info")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"We need to ",(0,o.kt)("strong",{parentName:"p"},"de-select")," both the entities because we have to ",(0,o.kt)("strong",{parentName:"p"},"mark")," them with options when we select them individually."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Center Line for Mirror\nBoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, False, 2, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line of code, we select the ",(0,o.kt)("em",{parentName:"p"},"Center Line")," i.e. ",(0,o.kt)("strong",{parentName:"p"},"Line 1")," for our Mirror option."),(0,o.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"NOTE")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"To differentiate a ",(0,o.kt)("em",{parentName:"p"},"Center Line")," between selected entities, we use ",(0,o.kt)("strong",{parentName:"p"},"Mark")," option of ",(0,o.kt)("inlineCode",{parentName:"p"},"2")," while selecting the Center Line. This is IMPORTANT for defining the Centerline in ",(0,o.kt)("strong",{parentName:"p"},"Mirror")," operation."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Select Circle we want to Mirror\nBoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),(0,o.kt)("p",null,"In above line of code, we select the Circle i.e. ",(0,o.kt)("strong",{parentName:"p"},"Arc 1")," and add it to selection list."),(0,o.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"NOTE")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"While selecting entities to Mirror, we use ",(0,o.kt)("strong",{parentName:"p"},"Mark")," option of ",(0,o.kt)("inlineCode",{parentName:"p"},"1")," while selecting the Center Line. This is IMPORTANT for while selecting sketch entities in ",(0,o.kt)("strong",{parentName:"p"},"Mirror")," operation. If any selected entity is ",(0,o.kt)("strong",{parentName:"p"},"NOT")," marked with ",(0,o.kt)("inlineCode",{parentName:"p"},"1")," then it will not mirror."))),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Mirror Selected Sketch entities\nswDoc.SketchMirror\n")),(0,o.kt)("p",null,"In above line, we ",(0,o.kt)("strong",{parentName:"p"},"Mirror")," selected ",(0,o.kt)("em",{parentName:"p"},"Circle")," by ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchMirror")," method from ",(0,o.kt)("em",{parentName:"p"},"Solidworks Document")," variable."),(0,o.kt)("p",null,"This ",(0,o.kt)("inlineCode",{parentName:"p"},"SketchMirror")," method does not take any parameters."),(0,o.kt)("p",null,"Below image shows before and after Mirror operation on the sketch."),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"Before Mirror Operation")),(0,o.kt)("p",null,(0,o.kt)("img",{alt:"before-Mirror",src:n(77833).Z,width:"1130",height:"589"})),(0,o.kt)("p",null,(0,o.kt)("strong",{parentName:"p"},"After Mirror Operation")),(0,o.kt)("p",null,(0,o.kt)("img",{alt:"after-Mirror",src:n(93368).Z,width:"1131",height:"593"})),(0,o.kt)("hr",null),(0,o.kt)("div",{className:"admonition admonition-tip alert alert--success"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"}))),"NOTE")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"It is ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Meter only")),"."),(0,o.kt)("p",{parentName:"div"},"Solidworks API does not care about your application's Unit systems."),(0,o.kt)("p",{parentName:"div"},"For example, I works in ",(0,o.kt)("strong",{parentName:"p"},"ANSI")," system means ",(0,o.kt)("em",{parentName:"p"},"inches")," for distance. But when I used ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API")," through ",(0,o.kt)("em",{parentName:"p"},"VBA macros or C#"),", I need to converted numeric values."),(0,o.kt)("p",{parentName:"div"},"Because Solidworks API output the distance in ",(0,o.kt)("strong",{parentName:"p"},"Meter")," which is not my requirement."))),(0,o.kt)("hr",null),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' De-select the Sketch after creation\nswDoc.ClearSelection2 True\n")),(0,o.kt)("p",null,"In the above line of code, we deselect the ",(0,o.kt)("strong",{parentName:"p"},"Sketch")," after the ",(0,o.kt)("em",{parentName:"p"},"Mirror")," operation."),(0,o.kt)("p",null,"For de-selecting, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},'\' Show Front View after Sketch Mirror\nswDoc.ShowNamedView2 "", swStandardViews_e.swFrontView\n')),(0,o.kt)("p",null,"In the above line of code, we update the ",(0,o.kt)("em",{parentName:"p"},"view orientation")," to ",(0,o.kt)("strong",{parentName:"p"},"Front View"),"."),(0,o.kt)("p",null,"In my machine, after inserting a sketch view orientation does not changed."),(0,o.kt)("p",null,"Because of this I have to update the view to ",(0,o.kt)("strong",{parentName:"p"},"Front view"),"."),(0,o.kt)("p",null,"For showing ",(0,o.kt)("strong",{parentName:"p"},"Front View")," we used ",(0,o.kt)("inlineCode",{parentName:"p"},"ShowNamedView2")," method from our Solidworks document name ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("p",null,"This method takes 2 parameter described as follows:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"VName")," : Name of the view to display or an empty string to use ViewId instead")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"ViewId")," : ID of the view to display as defined by ",(0,o.kt)("inlineCode",{parentName:"p"},"swStandardViews_e")," or -1 to use the ",(0,o.kt)("strong",{parentName:"p"},"VName")," argument instead."))),(0,o.kt)("div",{className:"admonition admonition-info alert alert--info"},(0,o.kt)("div",{parentName:"div",className:"admonition-heading"},(0,o.kt)("h5",{parentName:"div"},(0,o.kt)("span",{parentName:"h5",className:"admonition-icon"},(0,o.kt)("svg",{parentName:"span",xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"},(0,o.kt)("path",{parentName:"svg",fillRule:"evenodd",d:"M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"}))),"NOTE")),(0,o.kt)("div",{parentName:"div",className:"admonition-content"},(0,o.kt)("p",{parentName:"div"},"If you specify both ",(0,o.kt)("strong",{parentName:"p"},"VName")," and ",(0,o.kt)("strong",{parentName:"p"},"ViewId"),", then ",(0,o.kt)("strong",{parentName:"p"},"ViewId")," takes precedence if the two arguments do not resolve to the same view."))),(0,o.kt)("p",null,(0,o.kt)("inlineCode",{parentName:"p"},"swStandardViews_e")," has following Standard View Types:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swBackView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swBottomView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swDimetricView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swFrontView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swIsometricView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swLeftView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swRightView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swTopView"))),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("em",{parentName:"p"},"swExtendetricView")))),(0,o.kt)("p",null,"In our code, we did not use ",(0,o.kt)("strong",{parentName:"p"},"VName")," instead I used ",(0,o.kt)("em",{parentName:"p"},"empty string")," in form of ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},'""'))," symbol."),(0,o.kt)("p",null,"I used ",(0,o.kt)("strong",{parentName:"p"},"ViewId")," value to specify view and used ",(0,o.kt)("inlineCode",{parentName:"p"},"swStandardViews_e.swFrontView")," value to use ",(0,o.kt)("em",{parentName:"p"},"Standard Front View"),"."),(0,o.kt)("pre",null,(0,o.kt)("code",{parentName:"pre",className:"language-vb",metastring:"showlinenumbers showLineNumbers",showlinenumbers:!0,showLineNumbers:!0},"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),(0,o.kt)("p",null,"In this last line we use ",(0,o.kt)("em",{parentName:"p"},"zoom to fit")," command."),(0,o.kt)("p",null,"For Zoom to fit, we use ",(0,o.kt)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",(0,o.kt)("inlineCode",{parentName:"p"},"swDoc"),"."),(0,o.kt)("p",null,"This is it !!!"),(0,o.kt)("p",null,"If you found anything to add or update, please let me know on my e-mail."),(0,o.kt)("hr",null),(0,o.kt)(i.Z,{mdxType:"AdComponent"}),(0,o.kt)("h2",{id:"vba-language-feature-used-in-this-post"},"VBA Language feature used in this post"),(0,o.kt)("p",null,"In this post used some features of ",(0,o.kt)("strong",{parentName:"p"},"VBA programming language"),"."),(0,o.kt)("p",null,"This section of post, has some brief information about the VBA programming language specific features."),(0,o.kt)("ol",null,(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"We use ",(0,o.kt)("strong",{parentName:"p"},"Option Explicit")," for capturing un-declared variables. If you want to read more about ",(0,o.kt)("strong",{parentName:"p"},"Option Explicit")," then please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-declaring-and-scoping-of-variables"},"Declaring and Scoping of Variables")),".")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"Then we create ",(0,o.kt)("strong",{parentName:"p"},"variable")," for different data types. If you know in detail about the ",(0,o.kt)("strong",{parentName:"p"},"Variables"),", then please visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-variables"},"Variables"))," and \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-programming-concepts/#data-types-in-vba"},"Data-types"))," posts of this blog. It will help you to understand what ",(0,o.kt)("strong",{parentName:"p"},"Variables")," are and how to use them.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"Then we create ",(0,o.kt)("strong",{parentName:"p"},"main Sub procedure")," for our macro. If you know in detail about the ",(0,o.kt)("strong",{parentName:"p"},"Sub procedure"),", then I suggest you to visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-sub-and-function-procedure"},"VBA Sub and Function Procedures"))," and \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-executing-procedures"},"Executing Sub and Function Procedures"))," posts of this blog. It will help you to understand what ",(0,o.kt)("strong",{parentName:"p"},"Procedures")," are and how to use them.")),(0,o.kt)("li",{parentName:"ol"},(0,o.kt)("p",{parentName:"li"},"In most part we create some variables and set their values. We set those values by using some ",(0,o.kt)("strong",{parentName:"p"},"functions")," provided from objects. If you don't know about the ",(0,o.kt)("strong",{parentName:"p"},"functions"),", then you should visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-functions"},"VBA Functions"))," and \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"/vba/vba-more-function"},"VBA Functions that do more"))," posts of this blog. It will help you to understand what ",(0,o.kt)("strong",{parentName:"p"},"functions")," are and how to use them."))),(0,o.kt)("hr",null),(0,o.kt)("h2",{id:"solidworks-api-objects"},"Solidworks API Objects"),(0,o.kt)("p",null,"In this post of ",(0,o.kt)("strong",{parentName:"p"},"Sketch Mirror"),", we use ",(0,o.kt)("em",{parentName:"p"},"Solidworks API objects and their methods"),"."),(0,o.kt)("p",null,"This section contains the list of all ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Objects")," used in this post."),(0,o.kt)("p",null,"I have also attached links of these ",(0,o.kt)("strong",{parentName:"p"},"Solidworks API Objects")," in ",(0,o.kt)("strong",{parentName:"p"},"API Help website"),"."),(0,o.kt)("p",null,"If you want to explore those objects, you can use these links."),(0,o.kt)("p",null,"These Solidworks API Objects are listed below:"),(0,o.kt)("ul",null,(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Solidworks Application Object")),(0,o.kt)("p",{parentName:"li"},"If you want explore ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Application Object")," object you can visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html"},"this link")),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Solidworks Document Object")),(0,o.kt)("p",{parentName:"li"},"If you want explore ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Document Object")," object you can visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html"},"this link")),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")),(0,o.kt)("p",{parentName:"li"},"If you want explore ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")," you can visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"},"this link")),".")),(0,o.kt)("li",{parentName:"ul"},(0,o.kt)("p",{parentName:"li"},(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")),(0,o.kt)("p",{parentName:"li"},"If you want explore ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",(0,o.kt)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")," you can visit \ud83d\ude80 ",(0,o.kt)("strong",{parentName:"p"},(0,o.kt)("a",{parentName:"strong",href:"https://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"},"this link")),"."))),(0,o.kt)("hr",null),(0,o.kt)("p",null,"Hope this post helps you to ",(0,o.kt)("em",{parentName:"p"},"Mirror")," Sketch Entities with Solidworks VBA Macros."),(0,o.kt)("p",null,"For more such tutorials on ",(0,o.kt)("strong",{parentName:"p"},"Solidworks VBA Macros"),", do come to this blog after sometime."),(0,o.kt)("p",null,"Till then, Happy learning!!!"))}u.isMDXComponent=!0},74753:function(e,t,n){n.d(t,{Z:function(){return o}});var a=n(94578),r=n(67294),o=function(e){function t(){return e.apply(this,arguments)||this}(0,a.Z)(t,e);var n=t.prototype;return n.componentDidMount=function(){var e;(e=document.createElement("script")).src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js",e.async=!0,e.defer=!0,document.body.insertBefore(e,document.body.firstChild),(window.adsbygoogle=window.adsbygoogle||[]).push({})},n.render=function(){return r.createElement("ins",{className:"adsbygoogle",style:{display:"block"},"data-ad-client":"ca-pub-8158659264340002","data-ad-slot":"6644001766","data-ad-format":"auto","data-full-width-responsive":"true"})},t}(r.Component)},93368:function(e,t,n){t.Z=n.p+"assets/images/after-Mirror-dab5e63919e9f9a52bc27f9887ead2cb.png"},77833:function(e,t,n){t.Z=n.p+"assets/images/before-Mirror-c38151b18efcbdfa536c69ea10857010.png"}}]);