<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="generator" content="Docusaurus v2.0.0-alpha.66">
<link rel="preconnect" href="https://www.google-analytics.com">
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-117501871-2","auto"),ga("set","anonymizeIp",!0),ga("send","pageview")</script>
<script async src="https://www.google-analytics.com/analytics.js"></script>
<script data-ad-client="ca-pub-8158659264340002" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><title data-react-helmet="true">Fix Unit Issue | The Cad Coder</title><meta data-react-helmet="true" name="twitter:card" content="summary_large_image"><meta data-react-helmet="true" name="docusaurus_language" content="en"><meta data-react-helmet="true" name="docusaurus_version" content="current"><meta data-react-helmet="true" name="docusaurus_tag" content="docs-default-current"><meta data-react-helmet="true" property="og:title" content="Fix Unit Issue | The Cad Coder"><meta data-react-helmet="true" name="description" content="In this post, I tell you about how to Fix *Unit Issue* in Solidworks API from VBA Macros in a Sketch."><meta data-react-helmet="true" property="og:description" content="In this post, I tell you about how to Fix *Unit Issue* in Solidworks API from VBA Macros in a Sketch."><meta data-react-helmet="true" property="og:url" content="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-fix-unit-issue"><link data-react-helmet="true" rel="shortcut icon" href="/img/logo.png"><link data-react-helmet="true" rel="canonical" href="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-fix-unit-issue"><link rel="stylesheet" href="/styles.f7ef45b3.css">
<link rel="preload" href="/styles.c3633769.js" as="script">
<link rel="preload" href="/runtime~main.4d18c882.js" as="script">
<link rel="preload" href="/main.08717c6b.js" as="script">
<link rel="preload" href="/1.4d0f5633.js" as="script">
<link rel="preload" href="/2.9b374bfd.js" as="script">
<link rel="preload" href="/94.e6f15855.js" as="script">
<link rel="preload" href="/95.291d156d.js" as="script">
<link rel="preload" href="/f976f453.2a96abdd.js" as="script">
<link rel="preload" href="/17896441.b813b81e.js" as="script">
<link rel="preload" href="/395cf440.a4817bab.js" as="script">
</head>
<body>
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><div aria-label="Navigation bar toggle" class="navbar__toggle" role="button" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></div><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a><div class="navbar__item dropdown dropdown--hoverable dropdown--left"><a class="navbar__item navbar__link">VBA</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li><a class="dropdown__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></div><a class="navbar__item navbar__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a><a class="navbar__item navbar__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></div><div class="navbar__items navbar__items--right"><div class="navbar__item dropdown dropdown--hoverable dropdown--right"><a class="navbar__item navbar__link">About</a><ul class="dropdown__menu"><li><a class="dropdown__link" position="right" href="/docs/about">About Me</a></li><li><a class="dropdown__link" position="right" href="/docs/resources">Resources</a></li><li><a class="dropdown__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></div><div class="react-toggle react-toggle--disabled displayOnlyInLargeViewport_2aTZ"><div class="react-toggle-track"><div class="react-toggle-track-check"><span class="toggle_BsTx">ðŸŒœ</span></div><div class="react-toggle-track-x"><span class="toggle_BsTx">ðŸŒž</span></div></div><div class="react-toggle-thumb"></div><input type="checkbox" disabled="" aria-label="Dark mode toggle" class="react-toggle-screenreader-only"></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div><div class="navbar-sidebar"><div class="navbar-sidebar__brand"><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a></div><div class="navbar-sidebar__items"><div class="menu"><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">VBA</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></li><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">About</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/about">About Me</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/resources">Resources</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></li></ul></div></div></div></nav><div class="main-wrapper"><div class="docPage_2gpo"><div class="docSidebarContainer_3_JD" role="complementary"><div class="sidebar_2urC"><div class="menu menu--responsive menu_5FrY"><button aria-label="Open Menu" aria-haspopup="true" class="button button--secondary button--sm menu__button" type="button"><svg aria-label="Menu" class="sidebarMenuIcon_Dm3K" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 32 32" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><ul class="menu__list"><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!">General Functions</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-in-sw">VBA in Solidworks</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-macro-open-part">Open new Part document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-macro-open-asm-and-dwg">Open Assembly and Drawing document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-macro-selection-methods">Selection Methods</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-macro-open-saved-documents">Open Saved Documents</a></li><li class="menu__list-item"><a aria-current="page" class="menu__link menu__link--active active" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue">Fix Unit Issue</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">Sketch</a><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Lines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-line">Create Line</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerline">Create CenterLine</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Rectangles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-corner-rec">Create Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-center-rec">Create Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-corner-rec">Create 3-Point Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-center-rec">Create 3-Point Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-parallelogram">Create A Parallelogram</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Circles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle">Create Circle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle-by-radius">Create Circle By Radius</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-perimeter-circle">Create Perimeter Circle</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Arcs</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc">Create Centerpoint Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-tangent-arc">Create Tangent Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc">Create 3-Point Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-polygon">Create Polygon</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Slots</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-straight-slot">Create a Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-straight-slot">Create a Centerpoint Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc-slot">Create a 3-Point Arc Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc-slot">Create a Centerpoint Arc Slot</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Splines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-point">Create a Point</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-spline">Create a Spline</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Fillet &amp; Chamfer</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-fillet">Create a Fillet</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-chamfer">Create a Chamfer</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Trim and Extend</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-trim-entities">Trim Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-extend-entities">Extend Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Offset and Mirror</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-offset-entities">Offset Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-mirror-sketch-entities">Mirror Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Sketch Patterns</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-linear-sketch-patterm">Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm">Edit Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm">Circular Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern">Edit Circular Sketch Pattern</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Sketch Transformation</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities">Move/Copy Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities">Rotate/Copy Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Sketch Relations</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-toggle-sketch-relation">Toggle (Hide/Show) Sketch Relations</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-sketch-relation">Add Sketch Relations (Constraints)</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Others</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-convert-to-construction-sketch">Convert to Construction Sketch</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-split-sketch-entities">Split Open/Closed Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Sketch Dimensioning</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-dimension-sketch-entities">Add dimension to Sketch Entities</a></li></ul></li></ul></li></ul></div></div></div><main class="docMainContainer_3EyW"><div class="container padding-vert--lg docItemWrapper_1EkI"><div class="row"><div class="col docItemCol_2ASc"><div class="docItemContainer_3QWW"><article><header><h1 class="docTitle_1Lrw">Fix Unit Issue</h1></header><div class="markdown"><p>In this post, I tell you about <strong>how to Fix <em>Unit Issue</em> in Solidworks API from VBA Macros</strong> in a Sketch.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="what-is-the-issue"></a>What is the Issue?<a aria-hidden="true" tabindex="-1" class="hash-link" href="#what-is-the-issue" title="Direct link to heading">#</a></h2><p>Before going to solution let us see what is the issue we are trying to address.</p><p>In my all previous posts, you can see a <strong>NOTE</strong> (shown below) about Solidworks API.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="note"></a>NOTE<a aria-hidden="true" tabindex="-1" class="hash-link" href="#note" title="Direct link to heading">#</a></h2><p>  It is <strong><em>very important</em></strong> to remember that, when you give distance or any other numeric value in <strong>Solidworks API</strong>, Solidworks takes that numeric value in <strong><em>Meter only</em></strong>.</p><p>  Please see below for detail:</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-undefined codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">- Length: **Meter**</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">- Angle: **Radian**</span></div></div></div></div></div><p>  Solidworks API does not care about your application&#x27;s Unit systems.</p><p>  For example, I works in <strong>ANSI</strong> system means <em>inches</em> for distance. But when I used <strong>Solidworks API</strong> through <em>VBA macros or C#</em>, I need to converted numeric values.</p><p>  Because Solidworks API output the distance in <strong>Meter</strong> which is not my requirement.</p><hr><p><strong>So in this post we address this issue and use this solution in future posts.</strong></p><p>For this we take following steps:</p><ul><li><p><em>Get <strong>Unit currently in use</strong> in Solidworks.</em></p></li><li><p><em>Apply <strong>Select Case</strong> on the length of active unit.</em></p></li><li><p><em>We define values of <strong>factors</strong> i.e. <code>LengthConversionFactor</code> and <code>AngleConversionFactor</code>, these values depends upon the selected Length unit.</em></p></li><li><p><em>After assigning the values, we use them when we need to define any <strong>length or angle value</strong>.</em></p></li></ul><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="code-sample"></a>Code Sample<a aria-hidden="true" tabindex="-1" class="hash-link" href="#code-sample" title="Direct link to heading">#</a></h2><p>In below sample VBA macro program, we fix the issue.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create Variable for Solidworks Sketch Segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchSegment As SldWorks.SketchSegment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Create string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27;-----------------------BELOW IS THE SOLUTION----------------------------------------</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Local variables used as Conversion Factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim LengthConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim AngleConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Use a Select Case, to get the length of active Unit and set the different factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Select Case swDoc.GetUnits(0)       &#x27; GetUnits function gives us, active unit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swMETER    &#x27; If length is in Meter</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swMM       &#x27; If length is in MM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 1000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swCM       &#x27; If length is in CM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 100</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swINCHES   &#x27; If length is in INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 * 0.0254</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swFEET     &#x27; If length is in FEET</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 * (0.0254 * 12)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swFEETINCHES     &#x27; If length is in FEET &amp; INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 * 0.0254  &#x27; For length we use sama as Inch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swANGSTROM        &#x27; If length is in ANGSTROM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 10000000000#</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swNANOMETER       &#x27; If length is in NANOMETER</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 1000000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swMICRON       &#x27; If length is in MICRON</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 1000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  End Select</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27;----------------------------------------------------------------</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Select Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swSketchManager = swDoc.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Insert a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swSketchManager.InsertSketch True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Sketch Segment value and Create a Circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, 0.2 * LengthConversionFactor)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; De-select the Sketch Segment after Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ClearSelection2 True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Show Front View after Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ShowNamedView2 &quot;&quot;, swStandardViews_e.swFrontView</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Zoom to fit screen in Solidworks Window</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ViewZoomtofit2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="understanding-the-code"></a>Understanding the Code<a aria-hidden="true" tabindex="-1" class="hash-link" href="#understanding-the-code" title="Direct link to heading">#</a></h3><p>Now let us walk through <strong>each line</strong> in the above code, and <strong>understand</strong> the meaning and purpose of every line.</p><p>I also give some link so that you can go through them if there are anything I explained in previous posts.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div></div></div></div></div><p>This line forces us to define every variable we are going to use. </p><p>For more information please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div></div></div></div></div><p>In this line, we create a variable which we named as <code>swApp</code> and the type of this <code>swApp</code> variable is <code>SldWorks.SldWorks</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div></div></div></div></div><p>In this line, we create a variable which we named as <code>swDoc</code> and the type of this <code>swDoc</code> variable is <code>SldWorks.ModelDoc2</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div></div></div></div></div><p>In this line, we create a variable named <code>BoolStatus</code> as <code>Boolean</code> object type.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div></div></div></div></div><p>In above line, we create variable <code>swSketchManager</code> for <strong>Solidworks Sketch Manager</strong>.</p><p>As the name suggested, a <strong>Sketch Manager</strong> holds variours methods and properties to manage <em>Sketches</em>.</p><p>To see methods and properties related to <code>SketchManager</code> object, please visit <strong><a href="/docs/solidworks-macros/help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this page</a></strong></p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks Sketch Segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchSegment As SldWorks.SketchSegment</span></div></div></div></div></div><p>In this line, we Create a variable which we named as <code>swSketchSegment</code> and the type of this <code>swSketchSegment</code> variable is <code>SldWorks.SketchSegment</code>.</p><p>We create variable <code>swSketchSegment</code> for <strong>Solidworks Sketch Segments</strong>.</p><p>To see methods and properties related to <code>swSketchSegment</code> object, please visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html" target="_blank" rel="noopener noreferrer">this page</a></strong></p><p>These all are our global variables.</p><p>As you can see in code sample, they are <strong>Solidworks API Objects</strong>.</p><p>So basically I group all the <strong>Solidworks API Objects</strong> in one place.</p><p>I have also place <code>boolean</code> type object at top also, because after certain point we will <em>need</em> this variable frequently.</p><p>Thus, I have started placing it here.</p><p>Next is our <code>Sub</code> procedure which has name of <code>main</code>. </p><p>This procedure hold all the <em>statements (instructions)</em> we give to computer.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swApp = Application.SldWorks</span></div></div></div></div></div><p>In this line, we set the value of our Solidworks variable <code>swApp</code>; which we define earlier; to Solidworks application.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div></div></div></div></div><p>In 1st statement of above example, we are defining a variable of <code>string</code> type and named it as <code>defaultTemplate</code>.</p><p>This variable <code>defaultTemplate</code>, hold the location the location of <strong>Default Part Template</strong>.</p><p>In 2nd line of above example. we assign value to our newly define <code>defaultTemplate</code> variable.</p><p>We assign the value by using a <em>Method</em> named <code>GetUserPreferenceStringValue()</code>. </p><p>This <code>GetUserPreferenceStringValue()</code> method is a part of our main Solidworks variable <code>swApp</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div></div></div></div></div><p>In this line, we set the value of our <code>swDoc</code> variable to new document.</p><p>For <strong>detailed information</strong> about these lines please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post.</p><p>I have discussed them <strong>thoroghly</strong> in <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post, so do checkout that post if you want to understand above code in more detail.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Local variables used as Conversion Factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim LengthConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim AngleConversionFactor As Double</span></div></div></div></div></div><p>In above line we define our <em>local variable</em> we use as <em>Conversion Factors</em>.</p><p>Since this <em>VBA program</em> is <strong>small</strong>, we declare them in our <code>Sub</code> function.</p><p>If we have multiple functions, then we will create them with other <strong>Global variables</strong>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Use a Select Case, to get the length of active Unit and set the different factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Select Case swDoc.GetUnits(0)       &#x27; GetUnits function gives us, active unit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swMETER    &#x27; If length is in Meter</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swMM       &#x27; If length is in MM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 1000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swCM       &#x27; If length is in CM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 100</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swINCHES   &#x27; If length is in INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 * 0.0254</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swFEET     &#x27; If length is in FEET</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 * (0.0254 * 12)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swFEETINCHES     &#x27; If length is in FEET &amp; INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 * 0.0254  &#x27; For length we use sama as Inch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swANGSTROM        &#x27; If length is in ANGSTROM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 10000000000#</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swNANOMETER       &#x27; If length is in NANOMETER</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 1000000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swMICRON       &#x27; If length is in MICRON</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 1000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Select</span></div></div></div></div></div><p>Above we use a <code>Select Case</code> statement and apply <code>GetUnits(0)</code> method on <code>swDoc</code> variable to get the <em>active unit</em> of <em>current document</em>.</p><div class="admonition admonition-tip alert alert--success"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" viewBox="0 0 12 16"><path fill-rule="evenodd" d="M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"></path></svg></span>tip</h5></div><div class="admonition-content"><p>If you want to know more about <code>Select Case</code> statment then please visit <a href="/docs/vba/vba-if-else">If-Then and Select Case structure</a> post.</p></div></div><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Case swMETER    &#x27; If length is in Meter</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  LengthConversionFactor = 1 </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  AngleConversionFactor = 1</span></div></div></div></div></div><p>As shown in above code, when the is <code>swMETER</code> then we define the value of these factors.</p><p>In this case, it is:</p><ul><li>LengthConversionFactor = 1 </li><li>AngleConversionFactor = 1</li></ul><p>Since, I use <strong>IPS</strong>, I got the below case.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Case swINCHES   &#x27; If length is in INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  LengthConversionFactor = 1 * 0.0254</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  AngleConversionFactor = 1 * 0.01745329</span></div></div></div></div></div><p>In this case, it is:</p><ul><li><p>LengthConversionFactor = 0.0254 </p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>I write the value in <code>(1 * 0.0254)</code> format to show a relation of values with &quot;METER&quot;.</p></div></div></li><li><p>AngleConversionFactor = 0.01745329</p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>I write the value in <code>(1 * 0.01745329)</code> format to show a relation of values with &quot;RADIAN&quot;.</p></div></div></li></ul><p><strong><em>Similar is for all other CASES.</em></strong></p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Select Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div></div></div></div></div><p>In above line, we select the <em>front plane</em> by using <code>SelectByID2</code> method from <code>Extension</code> object.</p><p>For more information about selection method please visit <strong><a href="/docs/solidworks-macros/sw-macro-selection-methods">Solidworks Macros - Selection Methods</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchManager = swDoc.SketchManager</span></div></div></div></div></div><p>In above line, we set the <em>Sketch manager</em> variable to <em>current document&#x27;s sketch manager</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Insert a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swSketchManager.InsertSketch True</span></div></div></div></div></div><p>In above line, we use <code>InsertSketch</code> method of <em>SketchManager</em> and give <code>True</code> value.</p><p>This method allows us to insert a sketch in selected plane.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Sketch Segment value and Create a Circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, 0.2 * LengthConversionFactor)</span></div></div></div></div></div><p>In above line, we set the value of Solidworks Sketch Segment variable <code>swSketchSegment</code> by <code>CreateCircleByRadius</code> method from <em>Solidworks Sketch Manager</em>.</p><p>This <code>CreateCircleByRadius</code> method creates <em>a Circle</em> at given point with radius.</p><p>For more information about <code>CreateCircleByRadius</code> method, you can read my <strong><a href="/docs/solidworks-macros/sw-sketch-macro-create-circle-by-radius">Solidworks Macro - Create Circle By Radius From VBA Macro</a></strong> post.</p><p>That post describe all the parameters we need for this <code>CreateCircleByRadius</code> method in details.</p><p>In above line, we create a Circle with:</p><ul><li><p><strong>Circle Centerpoint</strong> : At origin i.e. <em>(0, 0, 0)</em></p></li><li><p><strong>Circle Radius</strong> : <em>`0.2 </em> LengthConversionFactor`*</p></li></ul><p>As you can notice, I have multiple the <code>LengthConversionFactor</code> in <code>0.2</code>.</p><p>This will make sure that I get a circle of <strong>0.4 Inch diameter</strong>. not a converted diameter in <strong>Meter</strong>.</p><p><strong><em>Image of created circle is shown below with diameter dimension.</em></strong></p><p><img alt="correct-unit-values" src="/assets/images/correct-unit-values-31ee433568755e796f23480fd59def95.png"></p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; De-select the Sketch after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ClearSelection2 True</span></div></div></div></div></div><p>In the above line of code, we deselect the <strong>Sketch</strong> after the <em>Circular Sketch Pattern</em> operation.</p><p>For de-selecting, we use <code>ClearSelection2</code> method from our Solidworks document name <code>swDoc</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Show Front View after Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ShowNamedView2 &quot;&quot;, swStandardViews_e.swFrontView</span></div></div></div></div></div><p>In the above line of code, we update the <em>view orientation</em> to <strong>Front View</strong>.</p><p>In my machine, after inserting a sketch view orientation does not changed.</p><p>Because of this I have to update the view to <strong>Front view</strong>.</p><p>For showing <strong>Front View</strong> we used <code>ShowNamedView2</code> method from our Solidworks document name <code>swDoc</code>.</p><p>This method takes 2 parameter described as follows:</p><ul><li><p><strong>VName</strong> : Name of the view to display or an empty string to use ViewId instead</p></li><li><p><strong>ViewId</strong> : ID of the view to display as defined by <code>swStandardViews_e</code> or -1 to use the <strong>VName</strong> argument instead.</p></li></ul><p><em>NOTE:</em> If you specify both <strong>VName</strong> and <strong>ViewId</strong>, then <strong>ViewId</strong> takes precedence if the two arguments do not resolve to the same view.</p><p><code>swStandardViews_e</code> has following Standard View Types:</p><ul><li><p><em>swBackView</em></p></li><li><p><em>swBottomView</em></p></li><li><p><em>swDimetricView</em></p></li><li><p><em>swFrontView</em></p></li><li><p><em>swIsometricView</em></p></li><li><p><em>swLeftView</em></p></li><li><p><em>swRightView</em></p></li><li><p><em>swTopView</em></p></li><li><p><em>swExtendetricView</em></p></li></ul><p>In our code, we did not use <strong>VName</strong> instead I used <em>empty string</em> in form of <strong><em>&quot;&quot;</em></strong> symbol.</p><p>I used <strong>ViewId</strong> value to specify view and used <code>swStandardViews_e.swFrontView</code> value to use <em>Standard Front View</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Zoom to fit screen in Solidworks Window</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ViewZoomtofit</span></div></div></div></div></div><p>In this last line we use <em>zoom to fit</em> command.</p><p>For Zoom to fit, we use <code>ViewZoomtofit</code> method from our Solidworks document variable <code>swDoc</code>.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="vba-language-feature-used-in-this-post"></a>VBA Language feature used in this post<a aria-hidden="true" tabindex="-1" class="hash-link" href="#vba-language-feature-used-in-this-post" title="Direct link to heading">#</a></h2><p>In this post used some features of <strong>VBA programming language</strong>.</p><p>This section of post, has some brief information about the VBA programming language specific features.</p><ol><li>We use <strong>Option Explicit</strong> for capturing un-declared variables.</li></ol><p>If you want to read more about <strong>Option Explicit</strong> then please visit <strong><a href="/docs/vba/vba-variables-decl">Declaring and Scoping of Variables</a></strong>.</p><ol start="2"><li>Then we create <strong>variable</strong> for different data types.</li></ol><p>If you know in detail about the <strong>Variables</strong>, then please visit <strong><a href="/docs/vba/vba-variables">Variables</a></strong> and <strong><a href="/docs/vba/vba-prog-concept#data-types-in-vba">Data-types</a></strong> posts of this blog.</p><p>It will help you to understand what <strong>Variables</strong> are and how to use them.</p><ol start="3"><li>Then we create <strong>main Sub procedure</strong> for our macro.</li></ol><p>If you know in detail about the <strong>Sub procedure</strong>, then I suggest you to visit <strong><a href="/docs/vba/vba-procedures">VBA Sub and Function Procedures</a></strong> and <strong><a href="/docs/vba/vba-procedures-exec">Executing Sub and Function Procedures</a></strong> posts of this blog.</p><p>It will help you to understand what <strong>Procedures</strong> are and how to use them.</p><ol start="4"><li>In most part we create some variables and set their values. We set those values by using some <strong>functions</strong> provided from objects.</li></ol><p>If you don&#x27;t know about the <strong>functions</strong>, then you should visit <strong><a href="/docs/vba/vba-functions">VBA Functions</a></strong> and <strong><a href="/docs/vba/vba-functions-adv">VBA Functions that do more</a></strong> posts of this blog.</p><p>It will help you to understand what <strong>functions</strong> are and how to use them.</p><ol start="5"><li>We use <strong>Select Case</strong> for checking <em>Length</em> of active unit.</li></ol><p>If you want to read more about <strong>Select Case</strong> then please visit <strong><a href="/docs/vba/vba-if-else#select-case-structure">If-Then and Select Case structure</a></strong>.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="solidworks-api-objects"></a>Solidworks API Objects<a aria-hidden="true" tabindex="-1" class="hash-link" href="#solidworks-api-objects" title="Direct link to heading">#</a></h2><p>In this post of <strong>Circular Sketch Pattern</strong>, we use <em>Solidworks API objects and their methods</em>.</p><p>This section contains the list of all <strong>Solidworks Objects</strong> used in this post.</p><p>I have also attached links of these <strong>Solidworks API Objects</strong> in <strong>API Help website</strong>.</p><p>If you want to explore those objects, you can use these links.</p><p>These Solidworks API Objects are listed below:</p><ul><li><p><strong>Solidworks Application Object</strong></p><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Application Object</strong> object you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html" target="_blank" rel="noopener noreferrer">this link</a></strong>.</p></li><li><p><strong>Solidworks Document Object</strong></p><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Document Object</strong> object you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html" target="_blank" rel="noopener noreferrer">this link</a></strong>.</p></li><li><p><strong>Solidworks Sketch Manager Object</strong></p><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Sketch Manager Object</strong> you can visit <strong><a href="/docs/solidworks-macros/help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this link</a></strong>.</p></li><li><p><strong>Solidworks Sketch Segment Object</strong></p><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Sketch Segment Object</strong> you can visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html" target="_blank" rel="noopener noreferrer">this link</a></strong>.</p></li></ul><hr><p><strong>This is it !!!</strong></p><p>If you found anything to add or update, please let me know on my e-mail.</p><p>Hope this post helps you to <em>Fix Unit Issue</em> in Solidworks API from VBA Macros.</p><p>For more such tutorials on <strong>Solidworks VBA Macro</strong>, do come to this blog after sometime.</p><p><em>If you like the post then please share it with your friends also.</em></p><p><em>Do let me know by you like this post or not!</em></p><p><em>Till then, Happy learning!!!</em></p></div></article><div class="margin-vert--lg"><nav class="pagination-nav" aria-label="Blog list page navigation"><div class="pagination-nav__item"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-macro-open-saved-documents"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Â« Open Saved Documents</div></a></div><div class="pagination-nav__item pagination-nav__item--next"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-create-line"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Create Line Â»</div></a></div></nav></div></div></div><div class="col col--3"><div class="tableOfContents_3SO_"><ul class="table-of-contents table-of-contents__left-border"><li><a href="#what-is-the-issue" class="table-of-contents__link">What is the Issue?</a></li><li><a href="#note" class="table-of-contents__link">NOTE</a></li><li><a href="#code-sample" class="table-of-contents__link">Code Sample</a><ul><li><a href="#understanding-the-code" class="table-of-contents__link">Understanding the Code</a></li></ul></li><li><a href="#vba-language-feature-used-in-this-post" class="table-of-contents__link">VBA Language feature used in this post</a></li><li><a href="#solidworks-api-objects" class="table-of-contents__link">Solidworks API Objects</a></li></ul></div></div></div></div></main></div></div><footer class="footer"><div class="container"><div class="row footer__links"><div class="col footer__col"><h4 class="footer__title">Tutorials</h4><ul class="footer__items"><li class="footer__item"><a class="footer__link-item" href="/docs/vba-Intro">VBA Introduction</a></li><li class="footer__item"><a class="footer__link-item" href="/docs/vba-in-sw">VBA in Solidworks</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">Community</h4><ul class="footer__items"><li class="footer__item"><a href="https://www.facebook.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Facebook</a></li><li class="footer__item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" rel="noopener noreferrer" class="footer__link-item">YouTube</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">More</h4><ul class="footer__items"><li class="footer__item"><a href="mailto:thecadcoder@gmail.com" target="_blank" rel="noopener noreferrer" class="footer__link-item">E-Mail</a></li><li class="footer__item"><a href="https://www.buymeacoffee.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Buy Me a Coffee</a></li></ul></div></div><div class="text--center"><div>Copyright Â© 2020 The Cad Coder, Inc. Built with Docusaurus.</div></div></div></footer></div>
<script src="/styles.c3633769.js"></script>
<script src="/runtime~main.4d18c882.js"></script>
<script src="/main.08717c6b.js"></script>
<script src="/1.4d0f5633.js"></script>
<script src="/2.9b374bfd.js"></script>
<script src="/94.e6f15855.js"></script>
<script src="/95.291d156d.js"></script>
<script src="/f976f453.2a96abdd.js"></script>
<script src="/17896441.b813b81e.js"></script>
<script src="/395cf440.a4817bab.js"></script>
</body>
</html>