I"`ò<p>In this post, I tell you about <strong>how to Add Sketch Relations (Constraints) using Solidworks VBA Macros</strong> in a Sketch.</p>

<p>In this post, I explain about <code class="language-plaintext highlighter-rouge">SketchAddConstraints</code> method from <strong>Solidworks</strong>â€™s <code class="language-plaintext highlighter-rouge">ModelDoc2</code> object.</p>

<p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>.</p>

<p>This post will utilize the methods explained in earlier posts, hence knowledge to those is required but it is not mandatory.</p>

<p>An absolute beginner can follow what is written here.</p>

<hr />

<h2 id="add-sketch-relations-constraints-method">Add Sketch Relations (Constraints) method</h2>

<p>For adding relations to a sketch segment, we use <code class="language-plaintext highlighter-rouge">SketchAddConstraints</code> method from <strong>Solidworks</strong>â€™s <code class="language-plaintext highlighter-rouge">ModelDoc2</code> object.</p>

<p>This <code class="language-plaintext highlighter-rouge">SketchAddConstraints</code> method takes following parameters as explained:</p>

<ul>
  <li><strong>Constraint</strong> : <em>ID of constraint as given on <strong><a href="http://help.solidworks.com/2020/english/api/sldworksapi/SOLIDWORKS.Interop.sldworks~SOLIDWORKS.Interop.sldworks.IModelDoc2~SketchAddConstraints.html?verRedirect=1">this page of Solidworks API Help</a></strong>.</em></li>
</ul>

<p><strong>Return Value</strong>: There are no return value for this method.</p>

<p>In following sections we add different sketch constraints to sketch segments.</p>

<hr />

<h2 id="add-fix-sketch-relation-to-a-sketch-segment">Add â€˜Fixâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Fixed</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use a <code class="language-plaintext highlighter-rouge">circle</code> as shown in below image:</p>

<p><strong>Before Add <em>Fix</em> Sketch Relation to Circle</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/circle-before-fixed-relation.png" alt="circle-before-fixed-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Fix</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to active part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Circle</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Arc1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Fix sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgFIXED"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Fix</em> Sketch Relation to Circle</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/circle-after-fixed-relation.png" alt="circle-after-fixed-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-coincident-sketch-relation-to-a-sketch-segment">Add â€˜Coincidentâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Coincident</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use a <code class="language-plaintext highlighter-rouge">circle</code> as shown in below image:</p>

<p><strong>Before Add <em>Coincident</em> Sketch Relation to Circle</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/circle-before-coincident-relation.png" alt="circle-before-coincident-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Coincident</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Circle center point</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Point2"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Select Origin</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Point1@Origin"</span><span class="p">,</span> <span class="s">"EXTSKETCHPOINT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Coincident sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgCOINCIDENT"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Coincident</em> Sketch Relation to Circle</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/circle-after-coincident-relation.png" alt="circle-after-coincident-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-horizontal-sketch-relation-to-a-sketch-segment">Add â€˜Horizontalâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Horizontal</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use a <code class="language-plaintext highlighter-rouge">Line</code> as shown in below image:</p>

<p><strong>Before Add <em>Horizontal</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/line-before-horizontal-or-vertical-relation.png" alt="line-before-horizontal-or-vertical-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Horizontal</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Horizontal sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgHORIZONTAL2D"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Horizontal</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/line-after-horizontal-relation.png" alt="line-after-horizontal-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-vertical-sketch-relation-to-a-sketch-segment">Add â€˜Verticalâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Vertical</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use a <code class="language-plaintext highlighter-rouge">Line</code> as shown in below image:</p>

<p><strong>Before Add <em>Vertical</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/line-before-horizontal-or-vertical-relation.png" alt="line-before-horizontal-or-vertical-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Vertical</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Vertical sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgVERTICAL2D"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Vertical</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/line-after-vertical-relation.png" alt="line-after-vertical-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-midpoint-sketch-relation-to-a-sketch-segment">Add â€˜Midpointâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Midpoint</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use a <code class="language-plaintext highlighter-rouge">Line</code> as shown in below image:</p>

<p><strong>Before Add <em>Midpoint</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/line-before-horizontal-or-vertical-relation.png" alt="line-before-horizontal-or-vertical-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Midpoint</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Select Origin</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Point1@Origin"</span><span class="p">,</span> <span class="s">"EXTSKETCHPOINT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Midpoint sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgATMIDDLE"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Midpoint</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/line-after-midpoint-relation.png" alt="line-after-midpoint-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-co-linear-sketch-relation-to-a-sketch-segment">Add â€˜Co-Linearâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Co-Linear</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use two <code class="language-plaintext highlighter-rouge">Lines</code> as shown in below image:</p>

<p><strong>Before Add <em>Co-Linear</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/lines-before-addng-colinear-relation.png" alt="lines-before-addng-colinear-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Co-Linear</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line 1</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Select Line 2</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line2"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Co-Linear sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgCOLINEAR"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Co-Linear</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/lines-after-colinear-relation.png" alt="lines-after-colinear-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-perpendicular-sketch-relation-to-a-sketch-segment">Add â€˜Perpendicularâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Perpendicular</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use two <code class="language-plaintext highlighter-rouge">Lines</code> as shown in below image:</p>

<p><strong>Before Add <em>Perpendicular</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/lines-before-addng-perpendicular-relation.png" alt="lines-before-addng-perpendicular-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Perpendicular</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line 1</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Select Line 2</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line2"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Perpendicular sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgPERPENDICULAR"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Perpendicular</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/lines-after-adding-perpendicular-relation.png" alt="lines-after-adding-perpendicular-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-parallel-sketch-relation-to-a-sketch-segment">Add â€˜Parallelâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Parallel</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use two <code class="language-plaintext highlighter-rouge">Lines</code> as shown in below image:</p>

<p><strong>Before Add <em>Parallel</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/lines-before-addng-parallel-relation.png" alt="lines-before-addng-parallel-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Parallel</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line 1</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Select Line 2</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line2"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Parallel sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgPARALLEL"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Parallel</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/lines-after-adding-parallel-relation.png" alt="lines-after-adding-parallel-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-equal-length-sketch-relation-to-a-sketch-segment">Add â€˜Equal Lengthâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Equal Length</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use two <code class="language-plaintext highlighter-rouge">Lines</code> as shown in below image:</p>

<p><strong>Before Add <em>Equal Length</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/lines-before-addng-equal-relation.png" alt="lines-before-addng-equal-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Equal Length</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line 1</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Select Line 2</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line2"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Equal Length sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgSAMELENGTH"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Equal Length</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/lines-after-adding-equal-relation.png" alt="lines-after-adding-equal-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-tangent-sketch-relation-to-a-sketch-segment">Add â€˜Tangentâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Tangent</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use a <code class="language-plaintext highlighter-rouge">Line</code> and a <code class="language-plaintext highlighter-rouge">Circle</code> as shown in below image:</p>

<p><strong>Before Add <em>Tangent</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/line-circle-before-adding-tangent-relation.png" alt="line-circle-before-adding-tangent-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Tangent</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line 1</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Select Line 2</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Arc1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Tangent sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgTANGENT"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Tangent</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/line-circle-after-adding-tangent-relation.png" alt="line-circle-after-adding-tangent-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-same-curve-length-sketch-relation-to-a-sketch-segment">Add â€˜Same Curve Lengthâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Same Curve Length</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use a <code class="language-plaintext highlighter-rouge">Line</code> and a <code class="language-plaintext highlighter-rouge">Circle</code> as shown in below image:</p>

<p><strong>Before Add <em>Same Curve Length</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/line-circle-before-adding-equal-curve-length-relation.png" alt="line-circle-before-adding-equal-curve-length-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Same Curve Length</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line 1</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Select Line 2</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Arc1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Same Curve Length sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgSAMECURVELENGTH"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Same Curve Length</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/line-circle-after-adding-equal-curve-length-relation.png" alt="line-circle-after-adding-equal-curve-length-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-coincident-sketch-relation-to-a-sketch-segment-1">Add â€˜Coincidentâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Coincident</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use <strong>two</strong> <code class="language-plaintext highlighter-rouge">Circles</code> as shown in below image:</p>

<p><strong>Before Add <em>Coincident</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/circles-before-adding-concentric-relation.png" alt="circles-before-adding-concentric-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Coincident</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line 1</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Arc1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Select Line 2</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Arc2"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Coincident sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgCONCENTRIC"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Coincident</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/circles-after-adding-concentric-relation.png" alt="circles-after-adding-concentric-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<h2 id="add-coradial-sketch-relation-to-a-sketch-segment">Add â€˜Coradialâ€™ Sketch Relation to a sketch segment</h2>

<p>Here we learn how to add <code class="language-plaintext highlighter-rouge">Coradial</code> <em>sketch relation</em> to a sketch segment through <strong>VBA</strong>.</p>

<p>We need <em>an unconstraint sketch segment</em>.</p>

<p>In this post, I use <strong>two</strong> <code class="language-plaintext highlighter-rouge">Circles</code> as shown in below image:</p>

<p><strong>Before Add <em>Coradial</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/circles-before-adding-coradial-relation.png" alt="circles-before-adding-coradial-relation" /></p>

<p><strong>Code to add <code class="language-plaintext highlighter-rouge">Coradial</code> sketch relation</strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
  
  <span class="c1">' Select Line 1</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Arc1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Select Line 2</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Arc2"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Add Coradial sketch relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchAddConstraints</span> <span class="p">(</span><span class="s">"sgCORADIAL"</span><span class="p">)</span>
  
  <span class="c1">' Clear selection after adding relation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p><strong>After Add <em>Coradial</em> Sketch Relation to Line</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/circles-after-adding-coradial-relation.png" alt="circles-after-adding-coradial-relation" /></p>

<p>I have added comments to each line <code class="language-plaintext highlighter-rouge">code sample</code>, hence it is easy to understand.</p>

<hr />

<p><strong>This is it !!!</strong></p>

<p><em>I hope my efforts will helpful to someone!</em></p>

<p>If you found anything to <strong>add or update</strong>, please let me know on my <em>e-mail</em>.</p>

<p>Hope this post helps you to <strong><em>Add Sketch Relations (Constraints)</em></strong> with Solidworks VBA Macros.</p>

<p>For more such tutorials on <strong>Solidworks VBA Macro</strong>, do come to this blog after sometime.</p>

<p><strong><em>If you like the post then please share it with your friends also.</em></strong></p>

<p><strong><em>Do let me know by you like this post or not!</em></strong></p>

<p><strong><em>Till then, Happy learning!!!</em></strong></p>
:ET