I"X<p>In this post, we select <strong>Default planes</strong> with following methods:</p>

<ol>
  <li>
    <p>By <code class="language-plaintext highlighter-rouge">SelectByID</code> method From <code class="language-plaintext highlighter-rouge">ModelDoc2</code> Interface</p>
  </li>
  <li>
    <p>By <code class="language-plaintext highlighter-rouge">SelectByID2</code> method From <code class="language-plaintext highlighter-rouge">IModelDocExtension</code> Interface</p>
  </li>
</ol>

<h2 id="by-selectbyid-method-from-modeldoc2-interface">By <strong>SelectByID</strong> method From <strong>ModelDoc2</strong> Interface</h2>

<p><code class="language-plaintext highlighter-rouge">SelectByID</code> method From <code class="language-plaintext highlighter-rouge">ModelDoc2</code> Interface is the easiest method for selecting Default plane.</p>

<p>I will explain the use of this method in 2 different scenerio as follows:</p>

<ol>
  <li>
    <p>Using this method in the previous example of creating a new document and then select a Plane.</p>
  </li>
  <li>
    <p>Using this method in an open document.</p>
  </li>
</ol>

<h3 id="using-selectbyid-method-in-previous-example">Using SelectByID method in previous example</h3>

<p>In the previous 2 posts, we learned how to create <em>a new part document, an assembly document, and a drawing document</em>.</p>

<p>Now we use the same code and <em>extended</em> it for using selecting planes.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

    <span class="c1">' Setting Solidworks variable to Solidworks application</span>
    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
    
    <span class="c1">' Creating string type variable for storing default part location</span>
    <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
    <span class="c1">' Setting value of this string type variable to "Default part template"</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>

    <span class="c1">' Setting Solidworks document to new part document</span>
    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

    <span class="c1">' Selecting Front Plane</span>
    <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SelectByID</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>Above code, 1st create a new part document and then select “<strong>Front Plane</strong>” in VBA macro.</p>

<p>To select the plane, I have to add 2 lines. 1st I create a boolean varible above main function as shown in below code:</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>
</code></pre></div></div>

<p>Then I use this <code class="language-plaintext highlighter-rouge">BoolStatus</code> variable to selecting <em>Front Plane</em> as shown in below code:</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Selecting Front Plane</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SelectByID</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
</code></pre></div></div>

<p><code class="language-plaintext highlighter-rouge">SelectByID</code> takes following parameters:</p>

<ul>
  <li>
    <p><em>Name</em> : Name of the object or an empty string</p>
  </li>
  <li>
    <p><em>Type</em> : Type of object in uppercase or an empty string</p>
  </li>
  <li>
    <p><em>X</em> : X selection location</p>
  </li>
  <li>
    <p><em>Y</em> : Y selection location</p>
  </li>
  <li>
    <p><em>Z</em> : Z selection location</p>
  </li>
</ul>

<p><strong>Return Value</strong> -</p>

<p>If the item is select then this method returns <code class="language-plaintext highlighter-rouge">True</code> and otherwise <code class="language-plaintext highlighter-rouge">False</code>.</p>

<p>Since this method returns <code class="language-plaintext highlighter-rouge">True</code> or <code class="language-plaintext highlighter-rouge">False</code>, hence we use a <code class="language-plaintext highlighter-rouge">boolean</code> variable to perfom this method.</p>

<p>If we want to select <strong>Right Plane</strong> then we just need to replace <code class="language-plaintext highlighter-rouge">"Front Plane"</code> -&gt; <code class="language-plaintext highlighter-rouge">"Right Plane"</code> in previous code sample.</p>

<p>Similar for selecting <strong>Top Plane</strong>, we need to replace <code class="language-plaintext highlighter-rouge">"Front Plane"</code> -&gt; <code class="language-plaintext highlighter-rouge">"Top Plane"</code> in previous code sample.</p>

<h3 id="using-selectbyid-method-in-an-open-document">Using SelectByID method in an Open document</h3>

<p>For using <code class="language-plaintext highlighter-rouge">SelectByID</code> method in an open document we use differnet code sample.</p>

<p>The code sample is given below:</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

    <span class="c1">' Setting Solidworks variable to Solidworks application</span>
    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
        
    <span class="c1">' Setting Solidworks document to active open document</span>
    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
        
    <span class="c1">' Selecting Front Plane</span>
    <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SelectByID</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>Most of the things in this code sample is already explained <strong><a href="/solidworks-macros/open-new-document">previous post</a></strong> and in previous section of this very post.</p>

<p>In this code I have set the <em>Solidworks document variable</em> <code class="language-plaintext highlighter-rouge">swDoc</code> to active open document.</p>

<p>And then we use similar method to select <strong>“Front Plane”</strong>.</p>

<p>As explained in previous section we can select <strong>Right Plane</strong> and <strong>Top Plane</strong>.</p>

<hr />

<h2 id="by-selectbyid2-method-from-imodeldocextension-interface">By <strong>SelectByID2</strong> method From <strong>IModelDocExtension</strong> Interface</h2>

<p>This method is similar to <code class="language-plaintext highlighter-rouge">SelectByID</code> from previous section infact it is the <em>updated version</em> of previous method.</p>

<p>Since it is <em>updated</em> and has <em>additional functionality</em>, I will explain it I <strong><em>frequently</em></strong> use this method. Previous method is easiest method, by far, for selecting objects.</p>

<p>Since <code class="language-plaintext highlighter-rouge">SelectByID2</code> is updated version of <code class="language-plaintext highlighter-rouge">SelectByID</code> it has similar syntax and usage.</p>

<p>I will explain the use of <code class="language-plaintext highlighter-rouge">SelectByID2</code> method in 2 different scenerio as done in previous method:</p>

<ol>
  <li>
    <p>Using this method in the previous example of creating a new document and then select a Plane.</p>
  </li>
  <li>
    <p>Using this method in an open document.</p>
  </li>
</ol>

<h3 id="using-selectbyid2-method-in-previous-example">Using SelectByID2 method in previous example</h3>

<p>Now we use the same code and <em>extended</em> it for using selecting planes by <code class="language-plaintext highlighter-rouge">SelectByID2</code> method.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

    <span class="c1">' Setting Solidworks variable to Solidworks application</span>
    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
    
    <span class="c1">' Creating string type variable for storing default part location</span>
    <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
    <span class="c1">' Setting value of this string type variable to "Default part template"</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>

    <span class="c1">' Setting Solidworks document to new part document</span>
    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

    <span class="c1">' Selecting Front Plane</span>
    <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>This method is doing the <em>same thing</em> which I already explained in the previous method.</p>

<p>The difference is in the <em>syntax</em> and <em>input parameters</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Selecting Front Plane</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
</code></pre></div></div>

<p>As you can see from the above code sample, this method is a method of <code class="language-plaintext highlighter-rouge">Extension</code> interface/object.</p>

<p>This <code class="language-plaintext highlighter-rouge">Extension</code> interface/object is part of <code class="language-plaintext highlighter-rouge">swDoc</code> variable. This variable is the type of <code class="language-plaintext highlighter-rouge">ModelDoc2</code> interface/object.</p>

<p>Apart from that, we need to give additional input parameters also.</p>

<p>Below I have explained about the input parameters of <code class="language-plaintext highlighter-rouge">SelectByID2</code> method:</p>

<ul>
  <li>
    <p><em>Name</em> : Name of the object or an empty string</p>
  </li>
  <li>
    <p><em>Type</em> : Type of object in uppercase or an empty string</p>
  </li>
  <li>
    <p><em>X</em> : X selection location</p>
  </li>
  <li>
    <p><em>Y</em> : Y selection location</p>
  </li>
  <li>
    <p><em>Z</em> : Z selection location</p>
  </li>
  <li>
    <p><em>Append</em> : <code class="language-plaintext highlighter-rouge">True</code> or <code class="language-plaintext highlighter-rouge">False</code>. It is used the adding the selection into selection list.</p>
  </li>
  <li>
    <p><em>Mark</em> : Value you want to use as a Mark; this value is used by other functions that require ordered selection.</p>
  </li>
  <li>
    <p><em>Callout</em> : Pointer to the <code class="language-plaintext highlighter-rouge">Callout</code> interface/object. (Default value most of the time is <code class="language-plaintext highlighter-rouge">nothing</code>.)</p>
  </li>
  <li>
    <p><em>SelectOption</em> : Selection option. You can use either <code class="language-plaintext highlighter-rouge">swSelectOptionDefault</code> or <code class="language-plaintext highlighter-rouge">swSelectOptionExtensive</code> value.</p>
  </li>
</ul>

<p><strong>Return Value</strong> -</p>

<p>If the item is select then this method returns <code class="language-plaintext highlighter-rouge">True</code> and otherwise <code class="language-plaintext highlighter-rouge">False</code>.</p>

<p>There is <strong>a lot more</strong> about this method in the <strong><em>Remark</em></strong> section. For more information visit <a href="http://help.solidworks.com/2017/english/api/sldworksapi/solidworks.interop.sldworks~solidworks.interop.sldworks.imodeldocextension~selectbyid2.html">here</a>.</p>

<p>Since this method returns <code class="language-plaintext highlighter-rouge">True</code> or <code class="language-plaintext highlighter-rouge">False</code>, here also we use a <code class="language-plaintext highlighter-rouge">boolean</code> variable to perfom this method.</p>

<p>If we want to select <strong>Right Plane</strong> then we just need to replace <code class="language-plaintext highlighter-rouge">"Front Plane"</code> -&gt; <code class="language-plaintext highlighter-rouge">"Right Plane"</code> in previous code sample.</p>

<p>Similar for selecting <strong>Top Plane</strong>, we need to replace <code class="language-plaintext highlighter-rouge">"Front Plane"</code> -&gt; <code class="language-plaintext highlighter-rouge">"Top Plane"</code> in previous code sample.</p>

<h3 id="using-selectbyid2-method-in-an-open-document">Using SelectByID2 method in an Open document</h3>

<p>For using <code class="language-plaintext highlighter-rouge">SelectByID2</code> method in an open document we use same code sample as used in previous method.</p>

<p>The code sample is given below:</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

    <span class="c1">' Setting Solidworks variable to Solidworks application</span>
    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
        
    <span class="c1">' Setting Solidworks document to active open document</span>
    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">ActiveDoc</span>
        
    <span class="c1">' Selecting Front Plane</span>
    <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>Most of the things in this code sample is already explained <strong><a href="/solidworks-macros/open-new-document">previous post</a></strong> and in previous section of this very post.</p>

<p>In this code I have set the <em>Solidworks document variable</em> <code class="language-plaintext highlighter-rouge">swDoc</code> to active open document.</p>

<p>And then we use similar method to select <strong>“Front Plane”</strong>.</p>

<p>As explained in previous section we can select <strong>Right Plane</strong> and <strong>Top Plane</strong>.</p>

<p>This is all for now. This post is getting too long.</p>

<p>In next post we learn about <strong><em>Open Saved Documents</em></strong>.</p>

:ET