<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- begin _includes/seo.html --><title>VBA Userforms - Browse SOLIDWORKS file(s) - The CAD Coder</title>
<meta name="description" content="Introduction">



<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="VBA Userforms - Browse SOLIDWORKS file(s)">
<meta property="og:url" content="https://thecadcoder.com//vba/browse-solidworks-file/">


  <meta property="og:description" content="Introduction">







  <meta property="article:published_time" content="2022-04-21T07:33:08-04:00">






<link rel="canonical" href="https://thecadcoder.com//vba/browse-solidworks-file/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": null,
      "url": "https://thecadcoder.com//"
    
  }
</script>







<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-117501871-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-117501871-2', { 'anonymize_ip': true});
</script>

<!-- end _includes/seo.html -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">
  <link
    href="/feed.xml"
    type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/main.css">

  <meta name="google-site-verification" content="OeSBbUv_kXDkDxaeoLixjE1BYxlbQRINt58H1UGbSMY" />

  
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        <img src="/assets/logo.png" width="30" height="30" class="img-fluid" alt="">
        <span>The CAD Coder</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a  class="active nav-link" style="border-bottom: 1px solid #fff;"   href="/vba/vba-Introduction/"><span>VBA</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-macro-guide/"><span>Solidworks VBA Macro</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-csharp-api-tutorials/"><span>Solidworks C# API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-cpp-api-tutorials/"><span>Solidworks C++ API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/resources/"><span>Resources</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/aboutMe/"><span>About</span></a>
            </li>
            
            <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li> -->
        </ul>
        <!-- <a class="btn btn-outline-success my-2 my-sm-0" href="/seach-document/" role="button">
            <i class="fas fa-search"></i>
        </a> -->
    </div>
</nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-sm-4">
  <div class="sidebar sticky">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">Getting Started</span>
        

        
        <ul>
          
            <li><a href="/vba/vba-Introduction/">VBA Introduction</a></li>
          
            <li><a href="/vba/vba-vbe-editor/">VBA Visual Basic Editor</a></li>
          
            <li><a href="/vba/vba-windows/">VBE Windows</a></li>
          
            <li><a href="/vba/sub-and-function-procedure/">VBA Sub and Function Procedures</a></li>
          
            <li><a href="/vba/executing-procedures/">VBA Executing Sub and Function Procedures</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Programming Concepts</span>
        

        
        <ul>
          
            <li><a href="/vba/programming-concepts/">VBA Programming Concepts, Comments and Data-types</a></li>
          
            <li><a href="/vba/variables/">VBA Variables</a></li>
          
            <li><a href="/vba/declaring-and-scoping-of-variables/">VBA Declaring and Scoping of Variables</a></li>
          
            <li><a href="/vba/variable-scope/">VBA Variable Scope</a></li>
          
            <li><a href="/vba/publc-static-variable-life/">VBA Public, Static and Variable's Life</a></li>
          
            <li><a href="/vba/constant/">VBA Constants</a></li>
          
            <li><a href="/vba/string-basic/">VBA String Basics</a></li>
          
            <li><a href="/vba/assignment-statement-and-operator/">VBA Assignment Statements And Operators</a></li>
          
            <li><a href="/vba/arrays/">VBA Arrays</a></li>
          
            <li><a href="/vba/functions/">VBA Functions</a></li>
          
            <li><a href="/vba/more-functions/">VBA Functions that do more</a></li>
          
            <li><a href="/vba/controlling-flow-making-desicions/">VBA Controlling Program Flow and Making Decisions</a></li>
          
            <li><a href="/vba/if-then-structure-select-case/">VBA If-Then-Else and Select Case structure</a></li>
          
            <li><a href="/vba/looping/">VBA Looping</a></li>
          
            <li><a href="/vba/bug-finding/">VBA Bug Finding</a></li>
          
            <li><a href="/vba/debugger/">VBA Debugger</a></li>
          
            <li><a href="/vba/bug-reduction-tips/">VBA Bug Reduction Tips</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Dialog Boxes</span>
        

        
        <ul>
          
            <li><a href="/vba/dialog-boxes/">VBA Dialog Boxes</a></li>
          
            <li><a href="/vba/msgBox-function/">VBA MsgBox Function</a></li>
          
            <li><a href="/vba/inputbox-function/">VBA InputBox Function</a></li>
          
            <li><a href="/vba/other-dialogs/">VBA GetOpenFilename, GetSaveAsFilename and Getting a Folder Name</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">UserForms</span>
        

        
        <ul>
          
            <li><a href="/vba/userform/">VBA UserForms</a></li>
          
            <li><a href="/vba/open-part-from-userform/">VBA Userforms - Open new Part document</a></li>
          
            <li><a href="/vba/open-assembly-and-drawing-from-userform/">VBA Userforms - Open new Assembly and Drawing document</a></li>
          
            <li><a href="/vba/testing-open-assembly-and-drawing-document-macro/">VBA Userforms - Testing Open new Assembly and Drawing document</a></li>
          
            <li><a href="/vba/browse-solidworks-file/" class="active">VBA Userforms - Browse SOLIDWORKS file(s)</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>

</div>
      <div class="col-md-9 col-sm-8">
        <div id="main" role="main">

  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    
    <meta itemprop="headline" content="VBA Userforms - Browse SOLIDWORKS file(s)">
    
    <meta itemprop="description" content="Introduction">
    
    
    <meta itemprop="datePublished" content="2022-04-21T07:33:08-04:00">
    

    <div class="page__inner-wrap">
      
      <header>
        <h1 id="page-title" class="page__title" itemprop="headline">VBA Userforms - Browse SOLIDWORKS file(s)
</h1>
        

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          9 minute read
        
      </span>
    
  </p>


      </header>
      

      <section class="page__content" itemprop="text">
        
        <aside class="sidebar__right sticky">
          <nav class="toc">
            <header>
              <h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4>
            </header>
            <ul class="toc__menu"><li><a href="#introduction">Introduction</a></li><li><a href="#creating-userform">Creating Userform</a></li><li><a href="#adding-controls-into-userform">Adding Controls into Userform</a><ul><li><a href="#adding-combobox">Adding ComboBox</a></li><li><a href="#adding-commandbutton">Adding CommandButton</a></li></ul></li><li><a href="#updating-properties">Updating Properties</a><ul><li><a href="#update-userform-properties">Update Userform Properties</a></li><li><a href="#update-textbox-properties">Update TextBox Properties</a></li><li><a href="#update-commandbutton-properties">Update CommandButton Properties</a></li></ul></li><li><a href="#call-userform-in-main-module">Call UserForm in Main Module</a></li><li><a href="#add-functionality-to-button">Add Functionality to Button</a></li><li><a href="#method-1---from-sldworks-object-directly">Method 1 - From SldWorks object directly</a><ul><li><a href="#understanding-method-1">Understanding Method 1</a></li></ul></li><li><a href="#method-2---from-microsoft-excel-externally">Method 2 - From Microsoft Excel externally</a><ul><li><a href="#understanding-method-2">Understanding Method 2</a></li></ul></li><li><a href="#final-words">Final words</a></li></ul>

            <br/>
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Vertical Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="4311368222"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          </nav>
        </aside>
        
        <div>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Horizontal Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="6007593278"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          <h2 id="introduction">Introduction</h2>

<p>In this article, we learn <strong>how to browse SOLIDWORKS file(s)</strong> from a <strong>SOLIDWORKS VBA Userform</strong>.</p>

<p>In this article, I explain about <strong><em>2 different methods</em></strong> which are listed below.</p>

<ol>
  <li>
    <p>From <code class="language-plaintext highlighter-rouge">SldWorks</code> object directly.</p>
  </li>
  <li>
    <p>From <strong>Microsoft Excel</strong> externally.</p>
  </li>
</ol>

<p>Methods from these objects are <strong><em>updated</em></strong> methods, hence <strong><em>use any one of them</em></strong> for browsing SOLIDWORKS file(s).</p>

<hr />
<!--
## Video of Code on YouTube

Please see below video how visually we *browse SOLIDWORKS file(s)* in **SOLIDWORKS VBA Userform**.

<iframe src="https://www.youtube.com/embed/AQ3Fyw78ExI" frameborder="0" allowfullscreen></iframe>
<br>

Please note that there are **no explanation** in the video. 

**Explanation** of each line and why we write code this way is given in this post.

---
-->

<h2 id="creating-userform">Creating Userform</h2>

<p>1st we need to create a <strong>new macro</strong> in <em>SOLIDWORKS</em>.</p>

<p>If you don’t know how to create a new macro in Solidworks, please go to <strong><a href="/solidworks-macros/vba-in-solidworks">VBA in Solidworks</a></strong> post for this.</p>

<p>This opens a <strong>Visual Basic Editor</strong> with some code as shown in below image.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/solidworks-vba-window.png" alt="solidworks-vba-window" /></p>

<p>After this we need to insert <em>a userform</em> in our macro.</p>

<p>For this, select the button shown in below image.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/insert-userform-button.png" alt="insert-userform-button" /></p>

<p>This button is called <strong><em>insert userform</em></strong>.</p>

<p>As the name suggest, function of this button is <em>inserting a userform</em>.</p>

<blockquote>
  <p>Please note that in a macro we can insert any number of userform as we like. But for this example we insert only 1 userform.</p>
</blockquote>

<p>After clicking the <strong><em>insert userform</em></strong> button we get the userform window as shown in above image.</p>

<hr />

<h2 id="adding-controls-into-userform">Adding Controls into Userform</h2>

<p>Now in our userform window, we add following controls:</p>

<ol>
  <li>
    <p><strong>A TextBox</strong></p>
  </li>
  <li>
    <p><strong>A CommandButton</strong></p>
  </li>
</ol>

<h3 id="adding-combobox">Adding ComboBox</h3>

<p>You can find <code class="language-plaintext highlighter-rouge">TextBox</code> option, as highlighted in <em>Red Square</em> in below image.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/textbox-in-userform.png" alt="textbox-in-userform" /></p>

<p>After adding ComboBox, we get window as shown in below image.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/textbox-inside-userform.png" alt="textbox-inside-userform" /></p>

<h3 id="adding-commandbutton">Adding CommandButton</h3>

<p>You can find <code class="language-plaintext highlighter-rouge">CommandButton</code> option, as highlighted in <em>Red Square</em> in below image.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/insert-command-button-into-userform.png" alt="insert-command-button-into-userform" /></p>

<p>After adding CommandButton, we get window as shown in below image.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/command-button-into-userform.png" alt="command-button-into-userform" /></p>

<hr />

<h2 id="updating-properties">Updating Properties</h2>

<p>Now we update some properties of following:</p>

<ol>
  <li>
    <p><strong>Userform</strong></p>
  </li>
  <li>
    <p><strong>TextBox</strong></p>
  </li>
  <li>
    <p><strong>CommandButton</strong></p>
  </li>
</ol>

<h3 id="update-userform-properties">Update Userform Properties</h3>

<p>We update following properties of the Userform:</p>

<ol>
  <li>
    <p>Name of Userform</p>
  </li>
  <li>
    <p>Caption of Userform</p>
  </li>
</ol>

<p>In below image, I have shown the properties of <code class="language-plaintext highlighter-rouge">Userform1</code> and update the properties:</p>

<p><img src="/assets/vba-images/browse-solidworks-files/update-userform-properties.png" alt="update-userform-properties" /></p>

<p>Update the value of <em>Name</em> property from <code class="language-plaintext highlighter-rouge">UserForm1</code> to <code class="language-plaintext highlighter-rouge">BrowseDocumentWindow</code>.</p>

<ul>
  <li>From <em>Name</em> property, we access the Userform.</li>
</ul>

<p>Update the value of <em>Caption</em> property from <code class="language-plaintext highlighter-rouge">UserForm1</code> to <code class="language-plaintext highlighter-rouge">Browse Document</code>.</p>

<ul>
  <li>From <em>Caption</em> property, we update the text appears in the window of our Userform.</li>
</ul>

<blockquote>
  <p>Please note that it is <strong>not necessary</strong> to update properties but it is a good habit to update them for our purpose.</p>
</blockquote>

<h3 id="update-textbox-properties">Update TextBox Properties</h3>

<p>We update following property of the TextBox:</p>

<ol>
  <li>Name of TextBox</li>
</ol>

<p>In below image, I have shown the properties of <code class="language-plaintext highlighter-rouge">TextBox</code> and update the properties:</p>

<p><img src="/assets/vba-images/browse-solidworks-files/update-textbox-properties.png" alt="update-textbox-properties" /></p>

<p>Update the value of <em>Name</em> property from <code class="language-plaintext highlighter-rouge">TextBox</code> to <code class="language-plaintext highlighter-rouge">SelectedFileTextBox</code>.</p>

<ul>
  <li>From <em>Name</em> property, we access the TextBox <em>properties</em> like <strong>Text</strong> we want to show.</li>
</ul>

<h3 id="update-commandbutton-properties">Update CommandButton Properties</h3>

<p>We update following properties of the Command Button:</p>

<ol>
  <li>
    <p>Name of Command Button</p>
  </li>
  <li>
    <p>Caption of Command Button</p>
  </li>
</ol>

<p>In below image, I have shown the properties of <code class="language-plaintext highlighter-rouge">CommandButton1</code> and update the properties:</p>

<p><img src="/assets/vba-images/browse-solidworks-files/update-command-button-properties.png" alt="update-command-button-properties" /></p>

<p>Update the value of <em>Name</em> property from <code class="language-plaintext highlighter-rouge">CommandButton1</code> to <code class="language-plaintext highlighter-rouge">BrowseDocumentButton</code>.</p>

<blockquote>
  <p>From <em>Name</em> property, we access the Command Button.</p>
</blockquote>

<p>Update the value of <em>Caption</em> property from <code class="language-plaintext highlighter-rouge">CommandButton1</code> to <code class="language-plaintext highlighter-rouge">Browse SOLIDOWRKS File(s)</code>.</p>

<blockquote>
  <p>From <em>Caption</em> property, we update the text appears in the Command Button of our Userform.</p>
</blockquote>

<hr />

<h2 id="call-userform-in-main-module">Call UserForm in Main Module</h2>

<p>Now, we need to call the our <em>Userform</em> inside main <strong><em>module</em></strong>.</p>

<p>For this goto main <code class="language-plaintext highlighter-rouge">Sub procedure</code> inside the <strong>main Module</strong>.</p>

<p>Code inside the main Module is as given below.</p>

<figure class="highlight"><pre><code class="language-vb" data-lang="vb"><span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="kt">Object</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

<span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="k">End</span> <span class="k">Sub</span></code></pre></figure>

<p>To call our <code class="language-plaintext highlighter-rouge">Userform</code>, replace above code with below code:</p>

<figure class="highlight"><pre><code class="language-vb" data-lang="vb"><span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>
  <span class="c1">' Calling our window to show</span>
  <span class="n">BrowseDocumentWindow</span><span class="p">.</span><span class="n">Show</span>
<span class="k">End</span> <span class="k">Sub</span></code></pre></figure>

<p>Above function call our window to appears on screen.</p>

<p>When the window appears on screen, we hit the <em>Browse button</em> to browse SOLIDWORKS File(s).</p>

<hr />

<h2 id="add-functionality-to-button">Add Functionality to Button</h2>

<p>To add functionality in our <code class="language-plaintext highlighter-rouge">BrowseDocumentButton</code>, just double click the <em>button</em>.</p>

<p>This will add some code behind the designer.</p>

<p>Now open the <strong>code window</strong> of Userform designer.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Private</span> <span class="k">Sub</span> <span class="nf">CommandButton1_Click</span><span class="p">()</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>We need to update this code for opening new part after clicking the button.</p>

<h2 id="method-1---from-sldworks-object-directly">Method 1 - From <code class="language-plaintext highlighter-rouge">SldWorks</code> object directly</h2>

<p>For this replace all above code with below code.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Private function of Open New Part Button</span>
<span class="k">Private</span> <span class="k">Sub</span> <span class="nf">BrowseDocumentButton_Click</span><span class="p">()</span>

  <span class="c1">' Setting Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Solidworks file filter string</span>
  <span class="k">Dim</span> <span class="nv">swFilter</span> <span class="ow">As</span> <span class="kt">String</span>
  
  <span class="c1">' Method parameters</span>
  <span class="k">Dim</span> <span class="nv">fileName</span> <span class="ow">As</span> <span class="kt">String</span>
  <span class="k">Dim</span> <span class="nv">fileConfig</span> <span class="ow">As</span> <span class="kt">String</span>
  <span class="k">Dim</span> <span class="nv">fileDispName</span> <span class="ow">As</span> <span class="kt">String</span>
  <span class="k">Dim</span> <span class="nv">fileOptions</span> <span class="ow">As</span> <span class="kt">Long</span>

  <span class="c1">' Set filters for different Solidworks files.</span>
  <span class="n">swFilter</span> <span class="o">=</span> <span class="s">"SOLIDWORKS Files (*.sldprt; *.sldasm; *.slddrw)|*.sldprt;*.sldasm;*.slddrw"</span>
  
  <span class="c1">' Browse and get the Selected file name</span>
  <span class="n">fileName</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetOpenFileName</span><span class="p">(</span><span class="s">"Browse Document"</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="n">swFilter</span><span class="p">,</span> <span class="n">fileOptions</span><span class="p">,</span> <span class="n">fileConfig</span><span class="p">,</span> <span class="n">fileDispName</span><span class="p">)</span>

  <span class="c1">' Show the selected file's full path in text box</span>
  <span class="n">SelectedFileTextBox</span><span class="p">.</span><span class="n">Text</span> <span class="o">=</span> <span class="n">fileName</span>
    
<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<hr />

<h3 id="understanding-method-1">Understanding Method 1</h3>

<p>Now let us walk through <strong>each line</strong> in the above code, and <strong>understand</strong> the meaning and purpose of every line.</p>

<p>I also give some link so that you can go through them if there are anything I explained in <strong>previous posts</strong>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>
</code></pre></div></div>

<p>This line forces us to define every variable we are going to use.</p>

<p>For more information please visit <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
</code></pre></div></div>

<p>In this line, we create a variable which we named as <code class="language-plaintext highlighter-rouge">swApp</code> and the type of this <code class="language-plaintext highlighter-rouge">swApp</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.SldWorks</code>.</p>

<p>Next is our button click event <code class="language-plaintext highlighter-rouge">BrowseDocumentButton_Click</code> procedure.</p>

<p>This procedure hold all the <em>statements (instructions)</em> we give to computer.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Solidworks variable to Solidworks application</span>
<span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
</code></pre></div></div>

<p>In this line, we set the value of our Solidworks variable <code class="language-plaintext highlighter-rouge">swApp</code>; which we define earlier; to Solidworks application.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Solidworks file filter string</span>
<span class="k">Dim</span> <span class="nv">swFilter</span> <span class="ow">As</span> <span class="kt">String</span>

<span class="c1">' Method parameters</span>
<span class="k">Dim</span> <span class="nv">fileName</span> <span class="ow">As</span> <span class="kt">String</span>
<span class="k">Dim</span> <span class="nv">fileConfig</span> <span class="ow">As</span> <span class="kt">String</span>
<span class="k">Dim</span> <span class="nv">fileDispName</span> <span class="ow">As</span> <span class="kt">String</span>
<span class="k">Dim</span> <span class="nv">fileOptions</span> <span class="ow">As</span> <span class="kt">Long</span>
</code></pre></div></div>

<p>In above lines of code, we create SOLIDWORKS <em>files filter</em> string and <em>Method parameters</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set filters for different Solidworks files.</span>
<span class="n">Filter</span> <span class="o">=</span> <span class="s">"SOLIDWORKS Files (*.sldprt; *.sldasm; *.slddrw)|*.sldprt;*.sldasm;*.slddrw"</span>
</code></pre></div></div>

<p>In above line of code, we set filters for different SOLIDWORKS files.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Browse and get the Selected file name</span>
<span class="n">fileName</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetOpenFileName</span><span class="p">(</span><span class="s">"Browse Document"</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="n">swFilter</span><span class="p">,</span> <span class="n">fileOptions</span><span class="p">,</span> <span class="n">fileConfig</span><span class="p">,</span> <span class="n">fileDispName</span><span class="p">)</span>
</code></pre></div></div>

<p>For “<strong>Browse and get the Selected file name</strong>”, we use <code class="language-plaintext highlighter-rouge">GetOpenFileName</code> method from <strong>Solidworks</strong> <code class="language-plaintext highlighter-rouge">SldWorks</code> object.</p>

<p>This <code class="language-plaintext highlighter-rouge">GetOpenFileName</code> method takes following parameters as explained:</p>

<ul>
  <li>
    <p><strong>DialogTitle</strong> : <em>Title of the dialog.</em></p>
  </li>
  <li>
    <p><strong>InitialFileName</strong> : <em>Path and file name of the file to open.</em></p>
  </li>
  <li>
    <p><strong>FileFilter</strong> : <em>File name extension of the file to open.</em></p>
  </li>
  <li>
    <p><strong>OpenOptions</strong> : <em>Not used.</em></p>
  </li>
  <li>
    <p><strong>ConfigName</strong> : <em>Name of the configuration.</em></p>
  </li>
  <li>
    <p><strong>DisplayName</strong> : <em>Recommended file name to use.</em></p>
  </li>
</ul>

<p>After the function complete following are the results:</p>

<p><strong>Return Value</strong>:</p>

<ul>
  <li><em>Path and file name of the file to open.</em></li>
</ul>

<p>Below image shows our <strong>form</strong> in SOLIDWORKS.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/userform-in-solidworks.png" alt="userform-in-solidworks" title="Our userform in Solidworks" /></p>

<p>Below image shows the opened window.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/browse-window.png" alt="browse-window" title="Browsing window" /></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Show the selected file's full path in text box</span>
<span class="n">SelectedFileTextBox</span><span class="p">.</span><span class="n">Text</span> <span class="o">=</span> <span class="n">fileName</span>
</code></pre></div></div>

<p>Now we set the value of text box to <strong>browsed</strong> file name.</p>

<p>Final window of method 1 is shown below/.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/final-window-of-method-first.png" alt="final-window-of-method-first" title="Final window from Method 1" /></p>

<hr />

<h2 id="method-2---from-microsoft-excel-externally">Method 2 - From <strong>Microsoft Excel</strong> externally</h2>

<p><strong>Prerequisite</strong>:</p>

<ol>
  <li>
    <p><strong>Office 365</strong></p>
  </li>
  <li>
    <p><strong>Following below steps carefully</strong></p>
  </li>
</ol>

<p>For this method we need to use <strong>Microsoft Excel</strong> from SOLIDWORKS.</p>

<p>For using <strong>Microsoft Excel</strong>, we need to add reference files.</p>

<p>Please see following steps for adding reference files:</p>

<ol>
  <li>Select reference option as shown in below image.</li>
</ol>

<p><img src="/assets/vba-images/browse-solidworks-files/select-reference-option.png" alt="select-reference-option" title="Select reference option from Tools options" /></p>

<ol>
  <li>This open Reference window as shown in below image.</li>
</ol>

<p><img src="/assets/vba-images/browse-solidworks-files/reference-window.png" alt="reference-window" title="Reference window" /></p>

<ol>
  <li>Now select option given in below images and Press OK after selecting files..</li>
</ol>

<p><img src="/assets/vba-images/browse-solidworks-files/add-excel-reference.png" alt="add-excel-reference" title="Select reference file highlighted in red box" /></p>

<p>Now, replace code in <em><a href="#add-functionality-to-button">Add Functionality to Button</a></em> with below code sample.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Private function of Open New Part Button</span>
<span class="k">Private</span> <span class="k">Sub</span> <span class="nf">BrowseDocumentButton_Click</span><span class="p">()</span>
    
  <span class="c1">' Excel object</span>
  <span class="k">Dim</span> <span class="nv">xlObj</span> <span class="ow">As</span> <span class="kt">Object</span>
  
  <span class="c1">' File dialog object</span>
  <span class="k">Dim</span> <span class="nv">fDialog</span> <span class="ow">As</span> <span class="kt">Object</span>
  
  <span class="c1">' File name sting</span>
  <span class="k">Dim</span> <span class="nv">strFile</span> <span class="ow">As</span> <span class="kt">String</span>
  
  <span class="c1">' Create Excel object</span>
  <span class="k">Set</span> <span class="n">xlObj</span> <span class="o">=</span> <span class="n">CreateObject</span><span class="p">(</span><span class="s">"Excel.Application"</span><span class="p">)</span>
  
  <span class="c1">' Create File dialog object by setting option 3</span>
  <span class="k">Set</span> <span class="n">fDialog</span> <span class="o">=</span> <span class="n">xlObj</span><span class="p">.</span><span class="n">FileDialog</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
  
  <span class="c1">' Setting different properties of file dialog</span>
  <span class="k">With</span> <span class="n">fDialog</span>
    <span class="p">.</span><span class="n">Title</span> <span class="o">=</span> <span class="s">"Browse Document"</span>  <span class="c1">' Title of window</span>
    <span class="p">.</span><span class="n">AllowMultiSelect</span> <span class="o">=</span> <span class="k">True</span>    <span class="c1">' Allowing multiple select</span>
    <span class="p">.</span><span class="n">Filters</span><span class="p">.</span><span class="n">Clear</span>              <span class="c1">' Clear the filters</span>
    <span class="p">.</span><span class="n">Filters</span><span class="p">.</span><span class="n">Add</span> <span class="s">"SOLIDWORKS Files"</span><span class="p">,</span> <span class="s">"*.sldprt; *.sldasm; *.slddrw"</span>       <span class="c1">' Add filters for Solidworks files</span>
      <span class="k">If</span> <span class="p">.</span><span class="n">Show</span> <span class="k">Then</span>
        <span class="n">strFile</span> <span class="o">=</span> <span class="p">.</span><span class="n">SelectedItems</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
      <span class="k">Else</span>
        <span class="n">strFile</span> <span class="o">=</span> <span class="n">vbNullString</span>
      <span class="k">End</span> <span class="k">If</span>
  <span class="k">End</span> <span class="k">With</span>
    
  <span class="c1">' Show the selected file's full path in text box</span>
  <span class="n">SelectedFileTextBox</span><span class="p">.</span><span class="n">Text</span> <span class="o">=</span> <span class="n">strFile</span>
    
<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<hr />

<h3 id="understanding-method-2">Understanding Method 2</h3>

<p>Now let us walk through <strong>each line</strong> in the above code, and <strong>understand</strong> the meaning and purpose of every line.</p>

<p>I also give some link so that you can go through them if there are anything I explained in <strong>previous posts</strong>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>
</code></pre></div></div>

<p>This line forces us to define every variable we are going to use.</p>

<p>For more information please visit <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post.</p>

<p>Next is our button click event <code class="language-plaintext highlighter-rouge">BrowseDocumentButton_Click</code> procedure.</p>

<p>This procedure hold all the <em>statements (instructions)</em> we give to computer.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Excel object</span>
<span class="k">Dim</span> <span class="nv">xlObj</span> <span class="ow">As</span> <span class="kt">Object</span>
</code></pre></div></div>

<p>In this line, we create object for <strong>Microsoft Excel Application</strong>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' File dialog object</span>
<span class="k">Dim</span> <span class="nv">fDialog</span> <span class="ow">As</span> <span class="kt">Object</span>

<span class="c1">' File name sting</span>
<span class="k">Dim</span> <span class="nv">strFile</span> <span class="ow">As</span> <span class="kt">String</span>
</code></pre></div></div>

<p>In above lines of code, we create <code class="language-plaintext highlighter-rouge">objects</code> for <strong>File Dialog</strong> and <code class="language-plaintext highlighter-rouge">string</code> for file name.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create Excel object</span>
<span class="k">Set</span> <span class="n">xlObj</span> <span class="o">=</span> <span class="n">CreateObject</span><span class="p">(</span><span class="s">"Excel.Application"</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line of code, we create <strong>Microsoft Excel Application</strong> and set the value of excel object.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create File dialog object by setting option 3</span>
<span class="k">Set</span> <span class="n">fDialog</span> <span class="o">=</span> <span class="n">xlObj</span><span class="p">.</span><span class="n">FileDialog</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line of code, we create <strong>File dialog</strong> and set the value of file dialog by <code class="language-plaintext highlighter-rouge">FileDialog</code> method.</p>

<p><code class="language-plaintext highlighter-rouge">FileDialog</code> method take 1 parameter <code class="language-plaintext highlighter-rouge">enum</code>. Please see below links for more details about <code class="language-plaintext highlighter-rouge">FileDialog</code></p>

<p><strong><a href="https://docs.microsoft.com/en-us/office/vba/api/excel.application.filedialog">Application.FileDialog property (Excel)</a></strong></p>

<p><strong><a href="https://docs.microsoft.com/en-us/office/vba/api/office.msofiledialogtype">MsoFileDialogType enumeration (Office)</a></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Setting different properties of file dialog</span>
<span class="k">With</span> <span class="n">fDialog</span>
  <span class="p">.</span><span class="n">Title</span> <span class="o">=</span> <span class="s">"Browse Document"</span>  <span class="c1">' Title of window</span>
  <span class="p">.</span><span class="n">AllowMultiSelect</span> <span class="o">=</span> <span class="k">True</span>    <span class="c1">' Allowing multiple select</span>
  <span class="p">.</span><span class="n">Filters</span><span class="p">.</span><span class="n">Clear</span>              <span class="c1">' Clear the filters</span>
  <span class="p">.</span><span class="n">Filters</span><span class="p">.</span><span class="n">Add</span> <span class="s">"SOLIDWORKS Files"</span><span class="p">,</span> <span class="s">"*.sldprt; *.sldasm; *.slddrw"</span>       <span class="c1">' Add filters for Solidworks files</span>
    <span class="k">If</span> <span class="p">.</span><span class="n">Show</span> <span class="k">Then</span>
      <span class="n">strFile</span> <span class="o">=</span> <span class="p">.</span><span class="n">SelectedItems</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>     <span class="c1">' Select 3rd item from list</span>
    <span class="k">Else</span>
      <span class="n">strFile</span> <span class="o">=</span> <span class="n">vbNullString</span>
    <span class="k">End</span> <span class="k">If</span>
<span class="k">End</span> <span class="k">With</span>
</code></pre></div></div>

<p>In above code we set different properties of File dialog object.</p>

<ul>
  <li>
    <p><strong>Title</strong> : <em>Title of the dialog.</em></p>
  </li>
  <li>
    <p><strong>AllowMultiSelect</strong> : <em>Allowing multi select of files.</em></p>
  </li>
  <li>
    <p><strong>FileFilter</strong> : <em>File name extension of the file to open.</em></p>
  </li>
</ul>

<p><code class="language-plaintext highlighter-rouge">If</code> statement shows that, if <em>file dialog</em> is shown then assign the <em>first value</em> to <strong>file name</strong> string object.</p>

<p>After the function complete following are the results:</p>

<p><strong>Return Value</strong>:</p>

<ul>
  <li><em>Path and file name of the selected file(s).</em></li>
</ul>

<p>Below image shows our <strong>form</strong> in SOLIDWORKS.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/userform-in-solidworks.png" alt="userform-in-solidworks" title="Our userform in Solidworks" /></p>

<p>Below image shows the opened window.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/excel-browse-window.png" alt="excel-browse-window" title="Browsing window using MS Excel" /></p>

<p>Below image shows the <strong>multi-selection</strong> in opened window.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/multiple-select-window.png" alt="multiple-select-window" title="Multilpe file selection in Browsing window using MS Excel" /></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Show the selected file's full path in text box</span>
<span class="n">SelectedFileTextBox</span><span class="p">.</span><span class="n">Text</span> <span class="o">=</span> <span class="n">fileName</span>
</code></pre></div></div>

<p>Now we set the value of text box to <strong>browsed</strong> file name.</p>

<p>Final window of method 1 is shown below/.</p>

<p><img src="/assets/vba-images/browse-solidworks-files/final-window-of-method-first.png" alt="final-window-of-method-second" title="Final window from Method 2" /></p>

<p><em>Final window of both method is same.</em></p>

<hr />

<h2 id="final-words">Final words</h2>

<p><strong>This is it !!!</strong></p>

<p><em>I hope my efforts will helpful to someone!</em></p>

<p>If you found anything to <strong>add or update</strong>, please let me know on my <em>e-mail</em>.</p>

<p>Hope this post helps you in <em>Browsing SOLIDWORKS file(s)</em> with Solidworks VBA Macros.</p>

<p>For more such tutorials on <strong>Solidworks VBA Macro</strong>, do come to this blog after sometime.</p>

<p><em>If you like the post then please share it with your friends also.</em></p>

<p><em>Do let me know by you like this post or not!</em></p>

<p><em>Till then, Happy learning!!!</em></p>

        </div>
        
        <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

      </section>

      <footer class="page__meta">
        
        


        

  <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i> Updated:</strong> <time datetime="2022-04-21T07:33:08-04:00">April 21, 2022</time></p>


      </footer>

      
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    
    <li class="page-item mr-5">
      <a class="btn btn-primary text-light" href="/vba/testing-open-assembly-and-drawing-document-macro/" title="VBA Userforms - Testing Open new Assembly and Drawing document
">❮ Previous</a>
    </li>
    
    
    <li class="page-item ml-5">
      <a class="btn btn-primary disabled text-light" href="#">Next ❯</a>
    </li>
    
  </ul>
</nav>

    </div>
  </article>

</div>
      </div>
    </div>
  </div>

  <div id="footer" class="page__footer">
    <footer>
      <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
      <footer class="bd-footer py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <a class="d-inline-flex align-items-center mb-2 link-dark" href="/" aria-label="Bootstrap">
          <img src="/assets/logo.png" width="30" height="30" class="img-fluid mr-2" alt="">
          <span> The CAD Coder</span>
        </a>
        <ul class="list-unstyled small text-muted">
          <li class="mb-2">Programming Tutorials for SOLIDWORKS 3D CAD Software.</li>
          <li class="mb-2">Copyright © 2022 The CAD Coder</li>
          <li class="mb-2">Built with <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a>.</li>

          
            
              
            
              
              <li class="list-inline-item"><a href="https://facebook.com/thecadcoder" target="_blank" title="Facebook"><i
                class="fab fa-2x fa-facebook-f"></i></a></li>
              
            
              
            
              
            
              
            
              
            
              
              <li class="list-inline-item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" title="YouTube"><i
                class="fab fa-2x fa-youtube"></i></a></li>
              
            
              
              <li class="list-inline-item"><a href="mailto:thecadcoder@gmail.com" target="_blank" title="Email"><i
                class="fa fa-envelope fa-2x"></i></a></li>
              
            
          
        </ul>
      </div>
      <div class="col-6">
        <h5>Links</h5>
        <ul class="list-unstyled">
          <!-- <li class="mb-2"><a href="/">Home</a></li> -->
          <li class="mb-2"><a href="/aboutMe/">About</a></li>
          <li class="mb-2"><a href="/resources/">Resources</a></li>
          <li class="mb-2"><a href="/Disclaimer/">Privacy Policy</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
    </footer>
  </div>

  
  <script src="/assets/js/main.min.js"></script>


<script>
  (function () {
    var cx = '4b2b9cb8c831ee0fb';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();

  function googleCustomSearchExecute() {
    var input = document.getElementById('cse-search-input-box-id');
    var element = google.search.cse.element.getElement('searchresults-only0');
    if (input.value == '') {
      element.clearAllResults();
    } else {
      element.execute(input.value);
    }
    return false;
  }

  
    $(document).ready(function () {
      $('input#cse-search-input-box-id').on('keyup', function () {
        googleCustomSearchExecute();
      });
    });
  
</script>







  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->

  
  <script src="/assets/js/main.min.js"></script>


<script>
  (function () {
    var cx = '4b2b9cb8c831ee0fb';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();

  function googleCustomSearchExecute() {
    var input = document.getElementById('cse-search-input-box-id');
    var element = google.search.cse.element.getElement('searchresults-only0');
    if (input.value == '') {
      element.clearAllResults();
    } else {
      element.execute(input.value);
    }
    return false;
  }

  
    $(document).ready(function () {
      $('input#cse-search-input-box-id').on('keyup', function () {
        googleCustomSearchExecute();
      });
    });
  
</script>






</body>

</html>