(window.webpackJsonp=window.webpackJsonp||[]).push([[5],{152:function(e,t,n){"use strict";n.d(t,"a",(function(){return s})),n.d(t,"b",(function(){return u}));var a=n(0),o=n.n(a);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function c(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function l(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?c(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):c(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function i(e,t){if(null==e)return{};var n,a,o=function(e,t){if(null==e)return{};var n,a,o={},r=Object.keys(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var b=o.a.createContext({}),p=function(e){var t=o.a.useContext(b),n=t;return e&&(n="function"==typeof e?e(t):l(l({},t),e)),n},s=function(e){var t=p(e.components);return o.a.createElement(b.Provider,{value:t},e.children)},m={inlineCode:"code",wrapper:function(e){var t=e.children;return o.a.createElement(o.a.Fragment,{},t)}},d=o.a.forwardRef((function(e,t){var n=e.components,a=e.mdxType,r=e.originalType,c=e.parentName,b=i(e,["components","mdxType","originalType","parentName"]),s=p(n),d=a,u=s["".concat(c,".").concat(d)]||s[d]||m[d]||r;return n?o.a.createElement(u,l(l({ref:t},b),{},{components:n})):o.a.createElement(u,l({ref:t},b))}));function u(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var r=n.length,c=new Array(r);c[0]=d;var l={};for(var i in t)hasOwnProperty.call(t,i)&&(l[i]=t[i]);l.originalType=e,l.mdxType="string"==typeof e?e:a,c[1]=l;for(var b=2;b<r;b++)c[b]=n[b];return o.a.createElement.apply(null,c)}return o.a.createElement.apply(null,n)}d.displayName="MDXCreateElement"},220:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/polygon-inscribed-circle-true-c828918ce8ae6a7df0d90e0de57e5c61.png"},221:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/polygon-inscribed-circle-false-26eb249ca10be579c4345a2afb3fd418.png"},55:function(e,t,n){"use strict";n.r(t),n.d(t,"frontMatter",(function(){return c})),n.d(t,"metadata",(function(){return l})),n.d(t,"rightToc",(function(){return i})),n.d(t,"default",(function(){return p}));var a=n(2),o=n(6),r=(n(0),n(152)),c={id:"sw-sketch-macro-create-polygon",title:"Create Polygon"},l={unversionedId:"solidworks-macros/sw-sketch-macro-create-polygon",id:"solidworks-macros/sw-sketch-macro-create-polygon",isDocsHomePage:!1,title:"Create Polygon",description:"In this post, I tell you about how to create a Polygon through Solidworks VBA Macros in a sketch.",source:"@site/docs\\solidworks-macros\\2019-06-15-create-polygon.md",slug:"/solidworks-macros/sw-sketch-macro-create-polygon",permalink:"/docs/solidworks-macros/sw-sketch-macro-create-polygon",version:"current",sidebar:"swvba",previous:{title:"Create 3-Point Arc",permalink:"/docs/solidworks-macros/sw-sketch-macro-create-3point-arc"},next:{title:"Create a Straight Slot",permalink:"/docs/solidworks-macros/sw-sketch-macro-create-straight-slot"}},i=[{value:"Understanding the Code",id:"understanding-the-code",children:[{value:"NOTE",id:"note",children:[]}]}],b={rightToc:i};function p(e){var t=e.components,c=Object(o.a)(e,["components"]);return Object(r.b)("wrapper",Object(a.a)({},b,c,{components:t,mdxType:"MDXLayout"}),Object(r.b)("p",null,"In this post, I tell you about ",Object(r.b)("em",{parentName:"p"},"how to create a Polygon through Solidworks VBA Macros")," in a sketch."),Object(r.b)("p",null,"The process is almost identical with previous ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-sketch-macro-create-tangent-arc"}),"Sketch - Create Tangent Arc"))," post."),Object(r.b)("p",null,"In this post, I tell you about ",Object(r.b)("inlineCode",{parentName:"p"},"CreatePolygon")," method from ",Object(r.b)("strong",{parentName:"p"},"Solidworks")," ",Object(r.b)("inlineCode",{parentName:"p"},"SketchManager")," object."),Object(r.b)("p",null,"This method is ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"most updated"))," method, I found in ",Object(r.b)("em",{parentName:"p"},"Solidworks API Help"),". "),Object(r.b)("p",null,"So ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"use this method"))," if you want to create a new ",Object(r.b)("strong",{parentName:"p"},"Polygon"),"."),Object(r.b)("p",null,"Below is the ",Object(r.b)("inlineCode",{parentName:"p"},"code")," sample for creating ",Object(r.b)("em",{parentName:"p"},"a Polygon"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n' Boolean Variable\nDim BoolStatus As Boolean\n' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Main function of our VBA program\nSub main()\n\n  ' Setting Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Creating string type variable for storing default part location\n  Dim defaultTemplate As String\n  ' Setting value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Setting Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n  ' Selecting Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Setting Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n  \n  ' Inserting a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Creating Varient for Polygon\n  Dim myPolygon As Variant\n  \n  ' Creating a Polygon\n  myPolygon = swSketchManager.CreatePolygon(0, 0, 0, 1, 0, 0, 6, True)\n  \n  ' De-select the Polygon after creation\n  swDoc.ClearSelection2 True\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit\n\nEnd Sub\n")),Object(r.b)("hr",null),Object(r.b)("h2",{id:"understanding-the-code"},"Understanding the Code"),Object(r.b)("p",null,"Now let us walk through ",Object(r.b)("em",{parentName:"p"},"each line")," in the above code, and ",Object(r.b)("strong",{parentName:"p"},"understand")," the meaning of every line."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n")),Object(r.b)("p",null,"This line forces us to define every variable we are going to use. "),Object(r.b)("p",null,"For more information please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),Object(r.b)("p",null,"In this line, we are creating a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),Object(r.b)("p",null,"In this line, we are creating a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),Object(r.b)("p",null,"Next is our ",Object(r.b)("inlineCode",{parentName:"p"},"Sub")," procedure named as ",Object(r.b)("inlineCode",{parentName:"p"},"main"),". This procedure hold all the ",Object(r.b)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Setting Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),Object(r.b)("p",null,"In this line, we are setting the value of our Solidworks variable ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," which we defined earlier to Solidworks application."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Creating string type variable for storing default part location\nDim defaultTemplate As String\n' Setting value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),Object(r.b)("p",null,"In 1st statement of above example, we are defining a variable of ",Object(r.b)("inlineCode",{parentName:"p"},"string")," type and named it as ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),Object(r.b)("p",null,"This variable ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate"),", holds the location the location of ",Object(r.b)("strong",{parentName:"p"},"Default Part Template"),"."),Object(r.b)("p",null,"In 2nd line of above example. we assign value to our newly define ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),Object(r.b)("p",null,"We assign the value by using a ",Object(r.b)("em",{parentName:"p"},"Method")," named ",Object(r.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),Object(r.b)("p",null,"This method is a part of our main Solidworks variable ",Object(r.b)("inlineCode",{parentName:"p"},"swApp"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Setting Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),Object(r.b)("p",null,"In this line, we set the value of our ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),Object(r.b)("p",null,"For ",Object(r.b)("strong",{parentName:"p"},"more detailed information")," about above lines please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post. "),Object(r.b)("p",null,"I have discussed them ",Object(r.b)("strong",{parentName:"p"},"thoroghly")," in ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post, so do checkout this post if you don't understand above code."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Boolean Variable\nDim BoolStatus As Boolean\n\n\' Selecting Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),Object(r.b)("p",null,"In 1st line, we create a variable named ",Object(r.b)("inlineCode",{parentName:"p"},"BoolStatus")," as ",Object(r.b)("inlineCode",{parentName:"p"},"Boolean")," object."),Object(r.b)("p",null,"In next line, we select the ",Object(r.b)("em",{parentName:"p"},"front plane")," by using ",Object(r.b)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",Object(r.b)("inlineCode",{parentName:"p"},"Extension")," object."),Object(r.b)("p",null,"For more information about selection method please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-selection-methods"}),"Solidworks Macros - Selection Methods"))," post."),Object(r.b)("p",null,"I have discussed about different ",Object(r.b)("em",{parentName:"p"},"Selection methods")," in details in ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-selection-methods"}),"Soldworks Macros - Selection Methods"))," post, so do visit this post for more ",Object(r.b)("em",{parentName:"p"},"Selection methods"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Creating variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),Object(r.b)("p",null,"In above line, we create variable ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchManager")," for ",Object(r.b)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(r.b)("p",null,"As the name suggested, a ",Object(r.b)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",Object(r.b)("em",{parentName:"p"},"Sketches"),"."),Object(r.b)("p",null,"To see methods and properties related to SketchManager object, please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"}),"this page")),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Setting Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),Object(r.b)("p",null,"In above line, we set the ",Object(r.b)("strong",{parentName:"p"},"Sketch manager")," variable to current document's sketch manager."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Inserting a sketch into selected plane\nswSketchManager.InsertSketch True\n")),Object(r.b)("p",null,"In above line, we use ",Object(r.b)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",Object(r.b)("em",{parentName:"p"},"SketchManager")," and give ",Object(r.b)("inlineCode",{parentName:"p"},"True")," value."),Object(r.b)("p",null,"This method allows us to insert a sketch in selected plane."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Creating Varient for Polygon\nDim myPolygon As Variant\n\n' Creating a Polygon\nmyPolygon = swSketchManager.CreatePolygon(0, 0, 0, 1, 0, 0, 6, True)\n")),Object(r.b)("p",null,"In above sample code, we 1st create a variable named ",Object(r.b)("inlineCode",{parentName:"p"},"myPolygon")," of type ",Object(r.b)("inlineCode",{parentName:"p"},"Variant"),"."),Object(r.b)("p",null,"In 2nd line, we ",Object(r.b)("strong",{parentName:"p"},"get")," the value of ",Object(r.b)("em",{parentName:"p"},"Variant")," variable ",Object(r.b)("inlineCode",{parentName:"p"},"myPolygon"),"."),Object(r.b)("p",null,"We get this value from ",Object(r.b)("inlineCode",{parentName:"p"},"CreatePolygon")," method which is inside the ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchManager")," variable."),Object(r.b)("p",null,Object(r.b)("inlineCode",{parentName:"p"},"swSketchManager")," variable is a type of ",Object(r.b)("strong",{parentName:"p"},"SketchManager"),", hence we used ",Object(r.b)("inlineCode",{parentName:"p"},"CreatePolygon")," method from ",Object(r.b)("strong",{parentName:"p"},"SketchManager"),"."),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"CreatePolygon")," method takes following parameters as explained:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"XC")," : X coordinate of the center point, of the polygon")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"YC")," : Y coordinate of the center point, of the polygon")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"ZC")," : Z coordinate of the center point, of the polygon")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"Xp")," : X coordinate of the vertex point, of the polygon")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"Yp")," : Y coordinate of the vertex point, of the polygon")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"Zp")," : Z coordinate of the vertex point, of the polygon")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"Sides")," : Number of sides in the polygon")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"Inscribed")," : ",Object(r.b)("inlineCode",{parentName:"p"},"True")," to show an inscribed construction circle, ",Object(r.b)("inlineCode",{parentName:"p"},"False")," to show a circumscribed construction circle"))),Object(r.b)("p",null,"For creating a ",Object(r.b)("em",{parentName:"p"},"Polygon"),", I used (0, 0, 0) as the ",Object(r.b)("em",{parentName:"p"},"Center point"),", which is ",Object(r.b)("em",{parentName:"p"},"origin point")," of our Sketch."),Object(r.b)("p",null,"For ",Object(r.b)("em",{parentName:"p"},"Vertex point")," of ",Object(r.b)("em",{parentName:"p"},"Polygon"),", I used (1, 0, 0) which is 1 point distance in X-direction."),Object(r.b)("p",null,"For ",Object(r.b)("em",{parentName:"p"},"Number of sides")," in the ",Object(r.b)("em",{parentName:"p"},"Polygon"),", I used ",Object(r.b)("em",{parentName:"p"},"6")," which represent ",Object(r.b)("strong",{parentName:"p"},"a Hexagon"),"."),Object(r.b)("p",null,"Below Image show when ",Object(r.b)("em",{parentName:"p"},"Inscribed")," option is ",Object(r.b)("inlineCode",{parentName:"p"},"True")," and show an ",Object(r.b)("em",{parentName:"p"},"inscribed construction circle"),"."),Object(r.b)("p",null,Object(r.b)("img",{alt:"polygon-inscribed-circle-true",src:n(220).default})),Object(r.b)("p",null,"Below Image show when ",Object(r.b)("em",{parentName:"p"},"Inscribed")," option is ",Object(r.b)("inlineCode",{parentName:"p"},"False"),"and show a ",Object(r.b)("em",{parentName:"p"},"circumscribed construction circle"),"."),Object(r.b)("p",null,Object(r.b)("img",{alt:"polygon-inscribed-circle-false",src:n(221).default})),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"CreatePolygon")," method returns ",Object(r.b)("strong",{parentName:"p"},"an array")," of ",Object(r.b)("em",{parentName:"p"},"sketch segments")," that represent the sides created for this ",Object(r.b)("em",{parentName:"p"},"Polygon"),"."),Object(r.b)("p",null,"A ",Object(r.b)("em",{parentName:"p"},"Sketch Segment")," can represent a sketch arc, line, ellipse, parabola or spline."),Object(r.b)("p",null,"Sketch Segment has ",Object(r.b)("inlineCode",{parentName:"p"},"ISketchSegment")," Interface, which provides functions that are generic to every type of sketch segment."),Object(r.b)("p",null,"For example, every sketch segment has an ID and can be programmatically selected."),Object(r.b)("p",null,"Therefore, the ",Object(r.b)("inlineCode",{parentName:"p"},"ISketchSegment")," interface provides functions to obtain the ID and to select the item."),Object(r.b)("hr",null),Object(r.b)("h3",{id:"note"},"NOTE"),Object(r.b)("p",null,"It is ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",Object(r.b)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Meter only")),"."),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"Solidworks API")," does not care about your application's Unit systems."),Object(r.b)("p",null,'For example, I works in ANSI system means "inches" for distance. '),Object(r.b)("p",null,"But when I used Solidworks API through ",Object(r.b)("em",{parentName:"p"},"VBA macros")," or ",Object(r.b)("em",{parentName:"p"},"C#"),", I have to use ",Object(r.b)("strong",{parentName:"p"},"converted")," numeric values."),Object(r.b)("p",null,"Because Solidworks API output the distance in ",Object(r.b)("strong",{parentName:"p"},"Meter")," only; which is not my requirement."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' De-select the Polygon after creation\nswDoc.ClearSelection2 True\n")),Object(r.b)("p",null,"In the this line of code, we de-select the created Polygon."),Object(r.b)("p",null,"For de-selecting, we use ",Object(r.b)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document variable ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),Object(r.b)("p",null,"In this last line we use ",Object(r.b)("em",{parentName:"p"},"zoom to fit")," command."),Object(r.b)("p",null,"For Zoom to fit, we use ",Object(r.b)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc"),". "),Object(r.b)("p",null,"Hope this post helps you to ",Object(r.b)("em",{parentName:"p"},"create a Polygon")," in Sketches with Solidworks VB Macros."),Object(r.b)("p",null,"For more such tutorials on ",Object(r.b)("strong",{parentName:"p"},"Solidworks VBA Macros"),", do come to this blog after sometime."),Object(r.b)("p",null,"Till then, Happy learning!!!"))}p.isMDXComponent=!0}}]);