(window.webpackJsonp=window.webpackJsonp||[]).push([[21],{152:function(e,t,n){"use strict";n.d(t,"a",(function(){return p})),n.d(t,"b",(function(){return O}));var a=n(0),r=n.n(a);function o(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function s(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function b(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?s(Object(n),!0).forEach((function(t){o(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):s(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function c(e,t){if(null==e)return{};var n,a,r=function(e,t){if(null==e)return{};var n,a,r={},o=Object.keys(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||(r[n]=e[n]);return r}(e,t);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);for(a=0;a<o.length;a++)n=o[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(r[n]=e[n])}return r}var i=r.a.createContext({}),l=function(e){var t=r.a.useContext(i),n=t;return e&&(n="function"==typeof e?e(t):b(b({},t),e)),n},p=function(e){var t=l(e.components);return r.a.createElement(i.Provider,{value:t},e.children)},m={inlineCode:"code",wrapper:function(e){var t=e.children;return r.a.createElement(r.a.Fragment,{},t)}},u=r.a.forwardRef((function(e,t){var n=e.components,a=e.mdxType,o=e.originalType,s=e.parentName,i=c(e,["components","mdxType","originalType","parentName"]),p=l(n),u=a,O=p["".concat(s,".").concat(u)]||p[u]||m[u]||o;return n?r.a.createElement(O,b(b({ref:t},i),{},{components:n})):r.a.createElement(O,b({ref:t},i))}));function O(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var o=n.length,s=new Array(o);s[0]=u;var b={};for(var c in t)hasOwnProperty.call(t,c)&&(b[c]=t[c]);b.originalType=e,b.mdxType="string"==typeof e?e:a,s[1]=b;for(var i=2;i<o;i++)s[i]=n[i];return r.a.createElement.apply(null,s)}return r.a.createElement.apply(null,n)}u.displayName="MDXCreateElement"},238:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/correct-unit-values-31ee433568755e796f23480fd59def95.png"},78:function(e,t,n){"use strict";n.r(t),n.d(t,"frontMatter",(function(){return s})),n.d(t,"metadata",(function(){return b})),n.d(t,"rightToc",(function(){return c})),n.d(t,"default",(function(){return l}));var a=n(2),r=n(6),o=(n(0),n(152)),s={id:"sw-sketch-macro-fix-unit-issue",title:"Fix Unit Issue"},b={unversionedId:"solidworks-macros/sw-sketch-macro-fix-unit-issue",id:"solidworks-macros/sw-sketch-macro-fix-unit-issue",isDocsHomePage:!1,title:"Fix Unit Issue",description:"In this post, I tell you about how to Fix *Unit Issue* in Solidworks API from VBA Macros in a Sketch.",source:"@site/docs\\solidworks-macros\\2020-03-10-unit-correction.md",slug:"/solidworks-macros/sw-sketch-macro-fix-unit-issue",permalink:"/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue",version:"current",sidebar:"swvba",previous:{title:"Open Saved Documents",permalink:"/docs/solidworks-macros/sw-macro-open-saved-documents"},next:{title:"Create Line",permalink:"/docs/solidworks-macros/sw-sketch-macro-create-line"}},c=[{value:"What is the Issue?",id:"what-is-the-issue",children:[]},{value:"NOTE",id:"note",children:[]},{value:"Code Sample",id:"code-sample",children:[{value:"Understanding the Code",id:"understanding-the-code",children:[]}]},{value:"VBA Language feature used in this post",id:"vba-language-feature-used-in-this-post",children:[]},{value:"Solidworks API Objects",id:"solidworks-api-objects",children:[]}],i={rightToc:c};function l(e){var t=e.components,s=Object(r.a)(e,["components"]);return Object(o.b)("wrapper",Object(a.a)({},i,s,{components:t,mdxType:"MDXLayout"}),Object(o.b)("p",null,"In this post, I tell you about ",Object(o.b)("strong",{parentName:"p"},"how to Fix ",Object(o.b)("em",{parentName:"strong"},"Unit Issue")," in Solidworks API from VBA Macros")," in a Sketch."),Object(o.b)("hr",null),Object(o.b)("h2",{id:"what-is-the-issue"},"What is the Issue?"),Object(o.b)("p",null,"Before going to solution let us see what is the issue we are trying to address."),Object(o.b)("p",null,"In my all previous posts, you can see a ",Object(o.b)("strong",{parentName:"p"},"NOTE")," (shown below) about Solidworks API."),Object(o.b)("hr",null),Object(o.b)("h2",{id:"note"},"NOTE"),Object(o.b)("p",null,"  It is ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",Object(o.b)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("em",{parentName:"strong"},"Meter only")),"."),Object(o.b)("p",null,"  Please see below for detail:"),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{}),"- Length: **Meter**\n\n- Angle: **Radian**\n")),Object(o.b)("p",null,"  Solidworks API does not care about your application's Unit systems."),Object(o.b)("p",null,"  For example, I works in ",Object(o.b)("strong",{parentName:"p"},"ANSI")," system means ",Object(o.b)("em",{parentName:"p"},"inches")," for distance. But when I used ",Object(o.b)("strong",{parentName:"p"},"Solidworks API")," through ",Object(o.b)("em",{parentName:"p"},"VBA macros or C#"),", I need to converted numeric values."),Object(o.b)("p",null,"  Because Solidworks API output the distance in ",Object(o.b)("strong",{parentName:"p"},"Meter")," which is not my requirement."),Object(o.b)("hr",null),Object(o.b)("p",null,Object(o.b)("strong",{parentName:"p"},"So in this post we address this issue and use this solution in future posts.")),Object(o.b)("p",null,"For this we take following steps:"),Object(o.b)("ul",null,Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"Get ",Object(o.b)("strong",{parentName:"em"},"Unit currently in use")," in Solidworks."))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"Apply ",Object(o.b)("strong",{parentName:"em"},"Select Case")," on the length of active unit."))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"We define values of ",Object(o.b)("strong",{parentName:"em"},"factors")," i.e. ",Object(o.b)("inlineCode",{parentName:"em"},"LengthConversionFactor")," and ",Object(o.b)("inlineCode",{parentName:"em"},"AngleConversionFactor"),", these values depends upon the selected Length unit."))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"After assigning the values, we use them when we need to define any ",Object(o.b)("strong",{parentName:"em"},"length or angle value"),".")))),Object(o.b)("hr",null),Object(o.b)("h2",{id:"code-sample"},"Code Sample"),Object(o.b)("p",null,"In below sample VBA macro program, we fix the issue."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n  \n  '-----------------------BELOW IS THE SOLUTION----------------------------------------\n\n  ' Local variables used as Conversion Factors\n  Dim LengthConversionFactor As Double\n  Dim AngleConversionFactor As Double\n  \n  ' Use a Select Case, to get the length of active Unit and set the different factors\n  Select Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n    \n    Case swMETER    ' If length is in Meter\n      LengthConversionFactor = 1 \n      AngleConversionFactor = 1\n    \n    Case swMM       ' If length is in MM\n      LengthConversionFactor = 1 / 1000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swCM       ' If length is in CM\n      LengthConversionFactor = 1 / 100\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swINCHES   ' If length is in INCHES\n      LengthConversionFactor = 1 * 0.0254\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEET     ' If length is in FEET\n      LengthConversionFactor = 1 * (0.0254 * 12)\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEETINCHES     ' If length is in FEET & INCHES\n      LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swANGSTROM        ' If length is in ANGSTROM\n      LengthConversionFactor = 1 / 10000000000#\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swNANOMETER       ' If length is in NANOMETER\n      LengthConversionFactor = 1 / 1000000000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swMICRON       ' If length is in MICRON\n      LengthConversionFactor = 1 / 1000000\n      AngleConversionFactor = 1 * 0.01745329\n  End Select\n\n  '----------------------------------------------------------------\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Set Sketch Segment value and Create a Circle\n  Set swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, 0.2 * LengthConversionFactor)\n\n  ' De-select the Sketch Segment after Circular Sketch Pattern\n  swDoc.ClearSelection2 True\n\n  ' Show Front View after Circular Sketch Pattern\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n\nEnd Sub\n")),Object(o.b)("hr",null),Object(o.b)("h3",{id:"understanding-the-code"},"Understanding the Code"),Object(o.b)("p",null,"Now let us walk through ",Object(o.b)("strong",{parentName:"p"},"each line")," in the above code, and ",Object(o.b)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),Object(o.b)("p",null,"I also give some link so that you can go through them if there are anything I explained in previous posts."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n")),Object(o.b)("p",null,"This line forces us to define every variable we are going to use. "),Object(o.b)("p",null,"For more information please visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),Object(o.b)("p",null,"In this line, we create a variable which we named as ",Object(o.b)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",Object(o.b)("inlineCode",{parentName:"p"},"swApp")," variable is ",Object(o.b)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),Object(o.b)("p",null,"In this line, we create a variable which we named as ",Object(o.b)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",Object(o.b)("inlineCode",{parentName:"p"},"swDoc")," variable is ",Object(o.b)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Boolean Variable\nDim BoolStatus As Boolean\n")),Object(o.b)("p",null,"In this line, we create a variable named ",Object(o.b)("inlineCode",{parentName:"p"},"BoolStatus")," as ",Object(o.b)("inlineCode",{parentName:"p"},"Boolean")," object type."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),Object(o.b)("p",null,"In above line, we create variable ",Object(o.b)("inlineCode",{parentName:"p"},"swSketchManager")," for ",Object(o.b)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(o.b)("p",null,"As the name suggested, a ",Object(o.b)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",Object(o.b)("em",{parentName:"p"},"Sketches"),"."),Object(o.b)("p",null,"To see methods and properties related to ",Object(o.b)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"}),"this page"))),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n")),Object(o.b)("p",null,"In this line, we Create a variable which we named as ",Object(o.b)("inlineCode",{parentName:"p"},"swSketchSegment")," and the type of this ",Object(o.b)("inlineCode",{parentName:"p"},"swSketchSegment")," variable is ",Object(o.b)("inlineCode",{parentName:"p"},"SldWorks.SketchSegment"),"."),Object(o.b)("p",null,"We create variable ",Object(o.b)("inlineCode",{parentName:"p"},"swSketchSegment")," for ",Object(o.b)("strong",{parentName:"p"},"Solidworks Sketch Segments"),"."),Object(o.b)("p",null,"To see methods and properties related to ",Object(o.b)("inlineCode",{parentName:"p"},"swSketchSegment")," object, please visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"}),"this page"))),Object(o.b)("p",null,"These all are our global variables."),Object(o.b)("p",null,"As you can see in code sample, they are ",Object(o.b)("strong",{parentName:"p"},"Solidworks API Objects"),"."),Object(o.b)("p",null,"So basically I group all the ",Object(o.b)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),Object(o.b)("p",null,"I have also place ",Object(o.b)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",Object(o.b)("em",{parentName:"p"},"need")," this variable frequently."),Object(o.b)("p",null,"Thus, I have started placing it here."),Object(o.b)("p",null,"Next is our ",Object(o.b)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",Object(o.b)("inlineCode",{parentName:"p"},"main"),". "),Object(o.b)("p",null,"This procedure hold all the ",Object(o.b)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),Object(o.b)("p",null,"In this line, we set the value of our Solidworks variable ",Object(o.b)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create string type variable for storing default part location\nDim defaultTemplate As String\n' Set value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),Object(o.b)("p",null,"In 1st statement of above example, we are defining a variable of ",Object(o.b)("inlineCode",{parentName:"p"},"string")," type and named it as ",Object(o.b)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),Object(o.b)("p",null,"This variable ",Object(o.b)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",Object(o.b)("strong",{parentName:"p"},"Default Part Template"),"."),Object(o.b)("p",null,"In 2nd line of above example. we assign value to our newly define ",Object(o.b)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),Object(o.b)("p",null,"We assign the value by using a ",Object(o.b)("em",{parentName:"p"},"Method")," named ",Object(o.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),Object(o.b)("p",null,"This ",Object(o.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," method is a part of our main Solidworks variable ",Object(o.b)("inlineCode",{parentName:"p"},"swApp"),"."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),Object(o.b)("p",null,"In this line, we set the value of our ",Object(o.b)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),Object(o.b)("p",null,"For ",Object(o.b)("strong",{parentName:"p"},"detailed information")," about these lines please visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post."),Object(o.b)("p",null,"I have discussed them ",Object(o.b)("strong",{parentName:"p"},"thoroghly")," in ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post, so do checkout that post if you want to understand above code in more detail."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Local variables used as Conversion Factors\nDim LengthConversionFactor As Double\nDim AngleConversionFactor As Double\n")),Object(o.b)("p",null,"In above line we define our ",Object(o.b)("em",{parentName:"p"},"local variable")," we use as ",Object(o.b)("em",{parentName:"p"},"Conversion Factors"),"."),Object(o.b)("p",null,"Since this ",Object(o.b)("em",{parentName:"p"},"VBA program")," is ",Object(o.b)("strong",{parentName:"p"},"small"),", we declare them in our ",Object(o.b)("inlineCode",{parentName:"p"},"Sub")," function."),Object(o.b)("p",null,"If we have multiple functions, then we will create them with other ",Object(o.b)("strong",{parentName:"p"},"Global variables"),"."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Use a Select Case, to get the length of active Unit and set the different factors\nSelect Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n  \n  Case swMETER    ' If length is in Meter\n    LengthConversionFactor = 1 \n    AngleConversionFactor = 1\n  \n  Case swMM       ' If length is in MM\n    LengthConversionFactor = 1 / 1000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swCM       ' If length is in CM\n    LengthConversionFactor = 1 / 100\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swINCHES   ' If length is in INCHES\n    LengthConversionFactor = 1 * 0.0254\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEET     ' If length is in FEET\n    LengthConversionFactor = 1 * (0.0254 * 12)\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEETINCHES     ' If length is in FEET & INCHES\n    LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swANGSTROM        ' If length is in ANGSTROM\n    LengthConversionFactor = 1 / 10000000000#\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swNANOMETER       ' If length is in NANOMETER\n    LengthConversionFactor = 1 / 1000000000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swMICRON       ' If length is in MICRON\n    LengthConversionFactor = 1 / 1000000\n    AngleConversionFactor = 1 * 0.01745329\nEnd Select\n")),Object(o.b)("p",null,"Above we use a ",Object(o.b)("inlineCode",{parentName:"p"},"Select Case")," statement and apply ",Object(o.b)("inlineCode",{parentName:"p"},"GetUnits(0)")," method on ",Object(o.b)("inlineCode",{parentName:"p"},"swDoc")," variable to get the ",Object(o.b)("em",{parentName:"p"},"active unit")," of ",Object(o.b)("em",{parentName:"p"},"current document"),"."),Object(o.b)("div",{className:"admonition admonition-tip alert alert--success"},Object(o.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"}),Object(o.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"})))),"tip")),Object(o.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"If you want to know more about ",Object(o.b)("inlineCode",{parentName:"p"},"Select Case")," statment then please visit ",Object(o.b)("a",Object(a.a)({parentName:"p"},{href:"../vba/vba-if-else"}),"If-Then and Select Case structure")," post."))),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Case swMETER    ' If length is in Meter\n  LengthConversionFactor = 1 \n  AngleConversionFactor = 1\n")),Object(o.b)("p",null,"As shown in above code, when the is ",Object(o.b)("inlineCode",{parentName:"p"},"swMETER")," then we define the value of these factors."),Object(o.b)("p",null,"In this case, it is:"),Object(o.b)("ul",null,Object(o.b)("li",{parentName:"ul"},"LengthConversionFactor = 1 "),Object(o.b)("li",{parentName:"ul"},"AngleConversionFactor = 1")),Object(o.b)("p",null,"Since, I use ",Object(o.b)("strong",{parentName:"p"},"IPS"),", I got the below case."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Case swINCHES   ' If length is in INCHES\n  LengthConversionFactor = 1 * 0.0254\n  AngleConversionFactor = 1 * 0.01745329\n")),Object(o.b)("p",null,"In this case, it is:"),Object(o.b)("ul",null,Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},"LengthConversionFactor = 0.0254 "),Object(o.b)("div",Object(a.a)({parentName:"li"},{className:"admonition admonition-note alert alert--secondary"}),Object(o.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(o.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(o.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"I write the value in ",Object(o.b)("inlineCode",{parentName:"p"},"(1 * 0.0254)"),' format to show a relation of values with "METER".')))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},"AngleConversionFactor = 0.01745329"),Object(o.b)("div",Object(a.a)({parentName:"li"},{className:"admonition admonition-note alert alert--secondary"}),Object(o.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(o.b)("h5",{parentName:"div"},Object(o.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(o.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(o.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(o.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(o.b)("p",{parentName:"div"},"I write the value in ",Object(o.b)("inlineCode",{parentName:"p"},"(1 * 0.01745329)"),' format to show a relation of values with "RADIAN".'))))),Object(o.b)("p",null,Object(o.b)("strong",{parentName:"p"},Object(o.b)("em",{parentName:"strong"},"Similar is for all other CASES."))),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),Object(o.b)("p",null,"In above line, we select the ",Object(o.b)("em",{parentName:"p"},"front plane")," by using ",Object(o.b)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",Object(o.b)("inlineCode",{parentName:"p"},"Extension")," object."),Object(o.b)("p",null,"For more information about selection method please visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-selection-methods"}),"Solidworks Macros - Selection Methods"))," post."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),Object(o.b)("p",null,"In above line, we set the ",Object(o.b)("em",{parentName:"p"},"Sketch manager")," variable to ",Object(o.b)("em",{parentName:"p"},"current document's sketch manager"),"."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Insert a sketch into selected plane\nswSketchManager.InsertSketch True\n")),Object(o.b)("p",null,"In above line, we use ",Object(o.b)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",Object(o.b)("em",{parentName:"p"},"SketchManager")," and give ",Object(o.b)("inlineCode",{parentName:"p"},"True")," value."),Object(o.b)("p",null,"This method allows us to insert a sketch in selected plane."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Sketch Segment value and Create a Circle\nSet swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, 0.2 * LengthConversionFactor)\n")),Object(o.b)("p",null,"In above line, we set the value of Solidworks Sketch Segment variable ",Object(o.b)("inlineCode",{parentName:"p"},"swSketchSegment")," by ",Object(o.b)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method from ",Object(o.b)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(o.b)("p",null,"This ",Object(o.b)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method creates ",Object(o.b)("em",{parentName:"p"},"a Circle")," at given point with radius."),Object(o.b)("p",null,"For more information about ",Object(o.b)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method, you can read my ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-sketch-macro-create-circle-by-radius"}),"Solidworks Macro - Create Circle By Radius From VBA Macro"))," post."),Object(o.b)("p",null,"That post describe all the parameters we need for this ",Object(o.b)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method in details."),Object(o.b)("p",null,"In above line, we create a Circle with:"),Object(o.b)("ul",null,Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("strong",{parentName:"p"},"Circle Centerpoint")," : At origin i.e. ",Object(o.b)("em",{parentName:"p"},"(0, 0, 0)"))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("strong",{parentName:"p"},"Circle Radius")," : ",Object(o.b)("em",{parentName:"p"},"`0.2 ")," LengthConversionFactor`*"))),Object(o.b)("p",null,"As you can notice, I have multiple the ",Object(o.b)("inlineCode",{parentName:"p"},"LengthConversionFactor")," in ",Object(o.b)("inlineCode",{parentName:"p"},"0.2"),"."),Object(o.b)("p",null,"This will make sure that I get a circle of ",Object(o.b)("strong",{parentName:"p"},"0.4 Inch diameter"),". not a converted diameter in ",Object(o.b)("strong",{parentName:"p"},"Meter"),"."),Object(o.b)("p",null,Object(o.b)("strong",{parentName:"p"},Object(o.b)("em",{parentName:"strong"},"Image of created circle is shown below with diameter dimension."))),Object(o.b)("p",null,Object(o.b)("img",{alt:"correct-unit-values",src:n(238).default})),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' De-select the Sketch after creation\nswDoc.ClearSelection2 True\n")),Object(o.b)("p",null,"In the above line of code, we deselect the ",Object(o.b)("strong",{parentName:"p"},"Sketch")," after the ",Object(o.b)("em",{parentName:"p"},"Circular Sketch Pattern")," operation."),Object(o.b)("p",null,"For de-selecting, we use ",Object(o.b)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",Object(o.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Show Front View after Circular Sketch Pattern\nswDoc.ShowNamedView2 "", swStandardViews_e.swFrontView\n')),Object(o.b)("p",null,"In the above line of code, we update the ",Object(o.b)("em",{parentName:"p"},"view orientation")," to ",Object(o.b)("strong",{parentName:"p"},"Front View"),"."),Object(o.b)("p",null,"In my machine, after inserting a sketch view orientation does not changed."),Object(o.b)("p",null,"Because of this I have to update the view to ",Object(o.b)("strong",{parentName:"p"},"Front view"),"."),Object(o.b)("p",null,"For showing ",Object(o.b)("strong",{parentName:"p"},"Front View")," we used ",Object(o.b)("inlineCode",{parentName:"p"},"ShowNamedView2")," method from our Solidworks document name ",Object(o.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(o.b)("p",null,"This method takes 2 parameter described as follows:"),Object(o.b)("ul",null,Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("strong",{parentName:"p"},"VName")," : Name of the view to display or an empty string to use ViewId instead")),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("strong",{parentName:"p"},"ViewId")," : ID of the view to display as defined by ",Object(o.b)("inlineCode",{parentName:"p"},"swStandardViews_e")," or -1 to use the ",Object(o.b)("strong",{parentName:"p"},"VName")," argument instead."))),Object(o.b)("p",null,Object(o.b)("em",{parentName:"p"},"NOTE:")," If you specify both ",Object(o.b)("strong",{parentName:"p"},"VName")," and ",Object(o.b)("strong",{parentName:"p"},"ViewId"),", then ",Object(o.b)("strong",{parentName:"p"},"ViewId")," takes precedence if the two arguments do not resolve to the same view."),Object(o.b)("p",null,Object(o.b)("inlineCode",{parentName:"p"},"swStandardViews_e")," has following Standard View Types:"),Object(o.b)("ul",null,Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"swBackView"))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"swBottomView"))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"swDimetricView"))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"swFrontView"))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"swIsometricView"))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"swLeftView"))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"swRightView"))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"swTopView"))),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("em",{parentName:"p"},"swExtendetricView")))),Object(o.b)("p",null,"In our code, we did not use ",Object(o.b)("strong",{parentName:"p"},"VName")," instead I used ",Object(o.b)("em",{parentName:"p"},"empty string")," in form of ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("em",{parentName:"strong"},'""'))," symbol."),Object(o.b)("p",null,"I used ",Object(o.b)("strong",{parentName:"p"},"ViewId")," value to specify view and used ",Object(o.b)("inlineCode",{parentName:"p"},"swStandardViews_e.swFrontView")," value to use ",Object(o.b)("em",{parentName:"p"},"Standard Front View"),"."),Object(o.b)("pre",null,Object(o.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),Object(o.b)("p",null,"In this last line we use ",Object(o.b)("em",{parentName:"p"},"zoom to fit")," command."),Object(o.b)("p",null,"For Zoom to fit, we use ",Object(o.b)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",Object(o.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(o.b)("hr",null),Object(o.b)("h2",{id:"vba-language-feature-used-in-this-post"},"VBA Language feature used in this post"),Object(o.b)("p",null,"In this post used some features of ",Object(o.b)("strong",{parentName:"p"},"VBA programming language"),"."),Object(o.b)("p",null,"This section of post, has some brief information about the VBA programming language specific features."),Object(o.b)("ol",null,Object(o.b)("li",{parentName:"ol"},"We use ",Object(o.b)("strong",{parentName:"li"},"Option Explicit")," for capturing un-declared variables.")),Object(o.b)("p",null,"If you want to read more about ",Object(o.b)("strong",{parentName:"p"},"Option Explicit")," then please visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-variables-decl"}),"Declaring and Scoping of Variables")),"."),Object(o.b)("ol",{start:2},Object(o.b)("li",{parentName:"ol"},"Then we create ",Object(o.b)("strong",{parentName:"li"},"variable")," for different data types.")),Object(o.b)("p",null,"If you know in detail about the ",Object(o.b)("strong",{parentName:"p"},"Variables"),", then please visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-variables"}),"Variables"))," and ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-prog-concept#data-types-in-vba"}),"Data-types"))," posts of this blog."),Object(o.b)("p",null,"It will help you to understand what ",Object(o.b)("strong",{parentName:"p"},"Variables")," are and how to use them."),Object(o.b)("ol",{start:3},Object(o.b)("li",{parentName:"ol"},"Then we create ",Object(o.b)("strong",{parentName:"li"},"main Sub procedure")," for our macro.")),Object(o.b)("p",null,"If you know in detail about the ",Object(o.b)("strong",{parentName:"p"},"Sub procedure"),", then I suggest you to visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-procedures"}),"VBA Sub and Function Procedures"))," and ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-procedures-exec"}),"Executing Sub and Function Procedures"))," posts of this blog."),Object(o.b)("p",null,"It will help you to understand what ",Object(o.b)("strong",{parentName:"p"},"Procedures")," are and how to use them."),Object(o.b)("ol",{start:4},Object(o.b)("li",{parentName:"ol"},"In most part we create some variables and set their values. We set those values by using some ",Object(o.b)("strong",{parentName:"li"},"functions")," provided from objects.")),Object(o.b)("p",null,"If you don't know about the ",Object(o.b)("strong",{parentName:"p"},"functions"),", then you should visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-functions"}),"VBA Functions"))," and ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-functions-adv"}),"VBA Functions that do more"))," posts of this blog."),Object(o.b)("p",null,"It will help you to understand what ",Object(o.b)("strong",{parentName:"p"},"functions")," are and how to use them."),Object(o.b)("ol",{start:5},Object(o.b)("li",{parentName:"ol"},"We use ",Object(o.b)("strong",{parentName:"li"},"Select Case")," for checking ",Object(o.b)("em",{parentName:"li"},"Length")," of active unit.")),Object(o.b)("p",null,"If you want to read more about ",Object(o.b)("strong",{parentName:"p"},"Select Case")," then please visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-if-else#select-case-structure"}),"If-Then and Select Case structure")),"."),Object(o.b)("hr",null),Object(o.b)("h2",{id:"solidworks-api-objects"},"Solidworks API Objects"),Object(o.b)("p",null,"In this post of ",Object(o.b)("strong",{parentName:"p"},"Circular Sketch Pattern"),", we use ",Object(o.b)("em",{parentName:"p"},"Solidworks API objects and their methods"),"."),Object(o.b)("p",null,"This section contains the list of all ",Object(o.b)("strong",{parentName:"p"},"Solidworks Objects")," used in this post."),Object(o.b)("p",null,"I have also attached links of these ",Object(o.b)("strong",{parentName:"p"},"Solidworks API Objects")," in ",Object(o.b)("strong",{parentName:"p"},"API Help website"),"."),Object(o.b)("p",null,"If you want to explore those objects, you can use these links."),Object(o.b)("p",null,"These Solidworks API Objects are listed below:"),Object(o.b)("ul",null,Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("strong",{parentName:"p"},"Solidworks Application Object")),Object(o.b)("p",{parentName:"li"},"If you want explore ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(o.b)("strong",{parentName:"p"},"Solidworks Application Object")," object you can visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html"}),"this link")),".")),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("strong",{parentName:"p"},"Solidworks Document Object")),Object(o.b)("p",{parentName:"li"},"If you want explore ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(o.b)("strong",{parentName:"p"},"Solidworks Document Object")," object you can visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html"}),"this link")),".")),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")),Object(o.b)("p",{parentName:"li"},"If you want explore ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(o.b)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")," you can visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"}),"this link")),".")),Object(o.b)("li",{parentName:"ul"},Object(o.b)("p",{parentName:"li"},Object(o.b)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")),Object(o.b)("p",{parentName:"li"},"If you want explore ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(o.b)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")," you can visit ",Object(o.b)("strong",{parentName:"p"},Object(o.b)("a",Object(a.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"}),"this link")),"."))),Object(o.b)("hr",null),Object(o.b)("p",null,Object(o.b)("strong",{parentName:"p"},"This is it !!!")),Object(o.b)("p",null,"If you found anything to add or update, please let me know on my e-mail."),Object(o.b)("p",null,"Hope this post helps you to ",Object(o.b)("em",{parentName:"p"},"Fix Unit Issue")," in Solidworks API from VBA Macros."),Object(o.b)("p",null,"For more such tutorials on ",Object(o.b)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),Object(o.b)("p",null,Object(o.b)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),Object(o.b)("p",null,Object(o.b)("em",{parentName:"p"},"Do let me know by you like this post or not!")),Object(o.b)("p",null,Object(o.b)("em",{parentName:"p"},"Till then, Happy learning!!!")))}l.isMDXComponent=!0}}]);