(window.webpackJsonp=window.webpackJsonp||[]).push([[36],{152:function(e,t,n){"use strict";n.d(t,"a",(function(){return p})),n.d(t,"b",(function(){return u}));var o=n(0),a=n.n(o);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function s(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,o)}return n}function c(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?s(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):s(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function l(e,t){if(null==e)return{};var n,o,a=function(e,t){if(null==e)return{};var n,o,a={},r=Object.keys(e);for(o=0;o<r.length;o++)n=r[o],t.indexOf(n)>=0||(a[n]=e[n]);return a}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(o=0;o<r.length;o++)n=r[o],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(a[n]=e[n])}return a}var i=a.a.createContext({}),b=function(e){var t=a.a.useContext(i),n=t;return e&&(n="function"==typeof e?e(t):c(c({},t),e)),n},p=function(e){var t=b(e.components);return a.a.createElement(i.Provider,{value:t},e.children)},g={inlineCode:"code",wrapper:function(e){var t=e.children;return a.a.createElement(a.a.Fragment,{},t)}},m=a.a.forwardRef((function(e,t){var n=e.components,o=e.mdxType,r=e.originalType,s=e.parentName,i=l(e,["components","mdxType","originalType","parentName"]),p=b(n),m=o,u=p["".concat(s,".").concat(m)]||p[m]||g[m]||r;return n?a.a.createElement(u,c(c({ref:t},i),{},{components:n})):a.a.createElement(u,c({ref:t},i))}));function u(e,t){var n=arguments,o=t&&t.mdxType;if("string"==typeof e||o){var r=n.length,s=new Array(r);s[0]=m;var c={};for(var l in t)hasOwnProperty.call(t,l)&&(c[l]=t[l]);c.originalType=e,c.mdxType="string"==typeof e?e:o,s[1]=c;for(var i=2;i<r;i++)s[i]=n[i];return a.a.createElement.apply(null,s)}return a.a.createElement.apply(null,n)}m.displayName="MDXCreateElement"},252:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/before-toggle-sketch-relation-5d4937bee3806c8ebe4cc343a8157914.png"},253:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/after-toggle-sketch-relation-48ecae9fb1999c23432f426296ceb1f4.png"},93:function(e,t,n){"use strict";n.r(t),n.d(t,"frontMatter",(function(){return s})),n.d(t,"metadata",(function(){return c})),n.d(t,"rightToc",(function(){return l})),n.d(t,"default",(function(){return b}));var o=n(2),a=n(6),r=(n(0),n(152)),s={id:"sw-sketch-macro-toggle-sketch-relation",title:"Toggle (Hide/Show) Sketch Relations"},c={unversionedId:"solidworks-macros/sw-sketch-macro-toggle-sketch-relation",id:"solidworks-macros/sw-sketch-macro-toggle-sketch-relation",isDocsHomePage:!1,title:"Toggle (Hide/Show) Sketch Relations",description:"In this post, I tell you about how to Toggle (Hide/Show) Sketch Relations using Solidworks VBA Macros in a Sketch.",source:"@site/docs\\solidworks-macros\\2020-06-28-toggle-display-sketch-relation.md",slug:"/solidworks-macros/sw-sketch-macro-toggle-sketch-relation",permalink:"/docs/solidworks-macros/sw-sketch-macro-toggle-sketch-relation",version:"current",sidebar:"swvba",previous:{title:"Rotate/Copy Sketch Entities",permalink:"/docs/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities"},next:{title:"Add Sketch Relations (Constraints)",permalink:"/docs/solidworks-macros/sw-sketch-macro-add-sketch-relation"}},l=[{value:"Code Sample",id:"code-sample",children:[]},{value:"Understanding the Code",id:"understanding-the-code",children:[]}],i={rightToc:l};function b(e){var t=e.components,s=Object(a.a)(e,["components"]);return Object(r.b)("wrapper",Object(o.a)({},i,s,{components:t,mdxType:"MDXLayout"}),Object(r.b)("p",null,"In this post, I tell you about ",Object(r.b)("strong",{parentName:"p"},"how to Toggle (Hide/Show) Sketch Relations using Solidworks VBA Macros")," in a Sketch."),Object(r.b)("p",null,"This post is extension to ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},Object(r.b)("a",Object(o.a)({parentName:"em"},{href:"sw-sketch-macro-rotate-or-copy-sketch-entities"}),"Sketch Transformation - Rotate/Copy Sketch Entities")))," post."),Object(r.b)("p",null,"Hence I will explained only ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Toggle (Hide/Show) Sketch Relations"))," related code."),Object(r.b)("p",null,"In this post, I explain about ",Object(r.b)("inlineCode",{parentName:"p"},"SetUserPreferenceToggle")," method from ",Object(r.b)("strong",{parentName:"p"},"Solidworks"),"'s ",Object(r.b)("inlineCode",{parentName:"p"},"ModelDoc2")," object."),Object(r.b)("p",null,"This method is ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"NOT updated"))," method, but it is easiest way to ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Toggle (Hide/Show) Sketch Relations")),"."),Object(r.b)("hr",null),Object(r.b)("h2",{id:"code-sample"},"Code Sample"),Object(r.b)("p",null,"Below is the ",Object(r.b)("inlineCode",{parentName:"p"},"code")," sample to ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Toggle (Hide/Show) Sketch Relations")),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(o.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n  \n  '-----------------------UNIT CONVERSION----------------------------------------\n\n  ' Local variables used as Conversion Factors\n  Dim LengthConversionFactor As Double\n  Dim AngleConversionFactor As Double\n  \n  ' Use a Select Case, to get the length of active Unit and set the different factors\n  Select Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n    \n    Case swMETER    ' If length is in Meter\n      LengthConversionFactor = 1\n      AngleConversionFactor = 1\n    \n    Case swMM       ' If length is in MM\n      LengthConversionFactor = 1 / 1000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swCM       ' If length is in CM\n      LengthConversionFactor = 1 / 100\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swINCHES   ' If length is in INCHES\n      LengthConversionFactor = 1 * 0.0254\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEET     ' If length is in FEET\n      LengthConversionFactor = 1 * (0.0254 * 12)\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEETINCHES     ' If length is in FEET & INCHES\n      LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swANGSTROM        ' If length is in ANGSTROM\n      LengthConversionFactor = 1 / 10000000000#\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swNANOMETER       ' If length is in NANOMETER\n      LengthConversionFactor = 1 / 1000000000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swMICRON       ' If length is in MICRON\n      LengthConversionFactor = 1 / 1000000\n      AngleConversionFactor = 1 * 0.01745329\n  End Select\n\n  '----------------------------------------------------------------\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Create a local variable for CenterPoint ractangle\n  Dim vSketch As Variant\n  \n  ' Create CenterPoint ractangle\n  vSketch = swSketchManager.CreateCenterRectangle(0, 0, 0, 1 * LengthConversionFactor, 1 * LengthConversionFactor, 0)\n    \n  ' De-select the lines after creation\n  swDoc.ClearSelection2 True\n  \n  ' Select all lines of CenterPoint Ractangle\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line2\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line3\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line4\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Rotate CenterPoint Ractangle by 45 degree only\n  swDoc.Extension.RotateOrCopy True, 2, True, 0, 0, 0, 0, 0, 1, 45 * AngleConversionFactor\n  \n  ' Toggle (Hide/Show) Sketch Relations\n  BoolStatus = swDoc.SetUserPreferenceToggle(swUserPreferenceToggle_e.swViewSketchRelations, True)\n  \n  ' De-select all after creation\n  swDoc.ClearSelection2 True\n  \n  ' Show Front View after Circular Sketch Pattern\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n  \nEnd Sub\n")),Object(r.b)("hr",null),Object(r.b)("h2",{id:"understanding-the-code"},"Understanding the Code"),Object(r.b)("p",null,"I have already discuss above code in previous ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},Object(r.b)("a",Object(o.a)({parentName:"em"},{href:"sw-sketch-macro-rotate-or-copy-sketch-entities"}),"Sketch Transformation - Rotate/Copy Sketch Entities")))," post except below line of code."),Object(r.b)("pre",null,Object(r.b)("code",Object(o.a)({parentName:"pre"},{className:"language-vb"}),"' Toggle (Hide/Show) Sketch Relations\nBoolStatus = swDoc.SetUserPreferenceToggle(swUserPreferenceToggle_e.swViewSketchRelations, True)\n")),Object(r.b)("p",null,'For "',Object(r.b)("strong",{parentName:"p"},"Toggle (Hide/Show)"),'"  Sketch Relations, we need ',Object(r.b)("inlineCode",{parentName:"p"},"SetUserPreferenceToggle")," method from ",Object(r.b)("strong",{parentName:"p"},"Solidworks"),"'s ",Object(r.b)("inlineCode",{parentName:"p"},"ModelDoc2")," object."),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"SetUserPreferenceToggle")," method takes following parameters as explained:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("strong",{parentName:"li"},"UserPreferenceValue")," : ",Object(r.b)("em",{parentName:"li"},"Use Preference Values to toggle as defined in ",Object(r.b)("inlineCode",{parentName:"em"},"swUserPreferenceToggle_e"),"."))),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(o.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(o.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(o.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(o.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(o.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},Object(r.b)("inlineCode",{parentName:"p"},"swUserPreferenceToggle_e")," has many values!!!  Hence it is not possible to list all of them here. If you want to check full list, please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(o.a)({parentName:"strong"},{href:"https://help.solidworks.com/2020/English/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swUserPreferenceToggle_e.html"}),"this page")),"."))),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("strong",{parentName:"li"},"OnFlag")," : ",Object(r.b)("em",{parentName:"li"},"True to toggle the value on, false to toggle the value off."))),Object(r.b)("p",null,"In our code, we used following values:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"UserPreferenceValue")," : ",Object(r.b)("em",{parentName:"p"},Object(r.b)("inlineCode",{parentName:"em"},"swUserPreferenceToggle_e.swViewSketchRelations")))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"OnFlag")," : ",Object(r.b)("em",{parentName:"p"},Object(r.b)("inlineCode",{parentName:"em"},"True"))))),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Return Value"),":"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"True"),": ",Object(r.b)("em",{parentName:"p"},"If Toggle (Hide/Show) of Sketch Relations is ",Object(r.b)("strong",{parentName:"em"},"Success"),"."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"False"),": ",Object(r.b)("em",{parentName:"p"},"If Toggle (Hide/Show) of Sketch Relations is ",Object(r.b)("strong",{parentName:"em"},"Fail"),".")))),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Before Toggle (Hide/Show) of Sketch Relations")),Object(r.b)("p",null,Object(r.b)("img",{alt:"before-toggle-sketch-relation",src:n(252).default})),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"After Toggle (Hide/Show) of Sketch Relations")),Object(r.b)("p",null,Object(r.b)("img",{alt:"after-toggle-sketch-relation",src:n(253).default})),Object(r.b)("hr",null),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"This is it !!!")),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"I hope my efforts will helpful to someone!")),Object(r.b)("p",null,"If you found anything to ",Object(r.b)("strong",{parentName:"p"},"add or update"),", please let me know on my ",Object(r.b)("em",{parentName:"p"},"e-mail"),"."),Object(r.b)("p",null,"Hope this post helps you to ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Toggle (Hide/Show) of Sketch Relations"))," with Solidworks VBA Macros."),Object(r.b)("p",null,"For more such tutorials on ",Object(r.b)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"Do let me know by you like this post or not!")),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"Till then, Happy learning!!!")))}b.isMDXComponent=!0}}]);