(window.webpackJsonp=window.webpackJsonp||[]).push([[62],{119:function(e,t,n){"use strict";n.r(t),n.d(t,"frontMatter",(function(){return l})),n.d(t,"metadata",(function(){return i})),n.d(t,"rightToc",(function(){return p})),n.d(t,"default",(function(){return b}));var o=n(2),r=n(6),a=(n(0),n(152)),l={id:"sw-cpp-open",title:"Open Solidworks & Hello World"},i={unversionedId:"solidworks-Cpp-tutorials/sw-cpp-open",id:"solidworks-Cpp-tutorials/sw-cpp-open",isDocsHomePage:!1,title:"Open Solidworks & Hello World",description:"In this post, I tell you about how to Open Solidworks using Solidworks C++ API from Visual Studio.",source:"@site/docs\\solidworks-Cpp-tutorials\\2.open-solidworks.md",slug:"/solidworks-Cpp-tutorials/sw-cpp-open",permalink:"/docs/solidworks-Cpp-tutorials/sw-cpp-open",version:"current",sidebar:"swcpp",previous:{title:"Prerequisite",permalink:"/docs/solidworks-Cpp-tutorials/sw-cpp-pre"},next:{title:"Open Solidworks Part Document",permalink:"/docs/solidworks-Cpp-tutorials/sw-cpp-part-doc"}},p=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",children:[]},{value:"Create a New project",id:"create-a-new-project",children:[]},{value:"Add Source file",id:"add-source-file",children:[]},{value:"Add References to Solidworks files",id:"add-references-to-solidworks-files",children:[]},{value:"Add Code to Source.cpp file",id:"add-code-to-sourcecpp-file",children:[]},{value:"Final Result",id:"final-result",children:[]}],c={rightToc:p};function b(e){var t=e.components,l=Object(r.a)(e,["components"]);return Object(a.b)("wrapper",Object(o.a)({},c,l,{components:t,mdxType:"MDXLayout"}),Object(a.b)("p",null,"In this post, I tell you about ",Object(a.b)("strong",{parentName:"p"},"how to Open Solidworks using Solidworks C++ API")," from Visual Studio."),Object(a.b)("p",null,"I hope you have setup Visual Studio community version."),Object(a.b)("p",null,"If not then please go to ",Object(a.b)("strong",{parentName:"p"},Object(a.b)("a",Object(o.a)({parentName:"strong"},{href:"sw-cpp-pre"}),"Solidworks C++ API - Prerequisite"))," post and watch the suggested videos before proceeding further."),Object(a.b)("hr",null),Object(a.b)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),Object(a.b)("p",null,"Please see below video on ",Object(a.b)("strong",{parentName:"p"},"how to Open Solidworks using Solidworks C++ API")," from Visual Studio."),Object(a.b)("div",{class:"youtube-responsive-container"},Object(a.b)("iframe",{src:"https://www.youtube.com/embed/oL9kJoRoYcQ",frameborder:"0",allowfullscreen:!0})),Object(a.b)("p",null,"Please note that there are ",Object(a.b)("strong",{parentName:"p"},"no explaination")," in the video. "),Object(a.b)("p",null,Object(a.b)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),Object(a.b)("hr",null),Object(a.b)("h2",{id:"create-a-new-project"},"Create a New project"),Object(a.b)("p",null,"Fist, we will create a new project in Visual Studio."),Object(a.b)("p",null,"There are 3 different ways for creating a new project."),Object(a.b)("ol",null,Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"From ",Object(a.b)("strong",{parentName:"p"},"File")," -> ",Object(a.b)("strong",{parentName:"p"},"New")," -> ",Object(a.b)("strong",{parentName:"p"},"Project"))),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"From ",Object(a.b)("strong",{parentName:"p"},"New Prject")," icon.")),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"Keyboard Short-cut i.e. ",Object(a.b)("inlineCode",{parentName:"p"},"Ctrl+Shift+N"),"."))),Object(a.b)("p",null,"Below image show how to create a ",Object(a.b)("em",{parentName:"p"},"New Project")," from ",Object(a.b)("strong",{parentName:"p"},"File")," option:"),Object(a.b)("p",null,Object(a.b)("img",{alt:"new-project-file-option",src:n(273).default})),Object(a.b)("p",null,"In above image, see Red color box."),Object(a.b)("p",null,"Below image show how to create a ",Object(a.b)("em",{parentName:"p"},"New Project")," from ",Object(a.b)("strong",{parentName:"p"},"New Project Icon")," option:"),Object(a.b)("p",null,Object(a.b)("img",{alt:"new-project-from-icon",src:n(274).default})),Object(a.b)("p",null,"In above image, see Red color box."),Object(a.b)("p",null,"When we select one of the above option we get a new window which is shown in below."),Object(a.b)("p",null,Object(a.b)("img",{alt:"create-project",src:n(275).default})),Object(a.b)("p",null,"In above image I have numbered the Red colored box."),Object(a.b)("p",null,"These numbers are explained below:"),Object(a.b)("ol",null,Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},Object(a.b)("em",{parentName:"p"},"The programming language")," you want to use for ",Object(a.b)("strong",{parentName:"p"},"New Project"),'. For our purpose, we use "',Object(a.b)("em",{parentName:"p"},"Visual C++"),'".')),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"It is, ",Object(a.b)("strong",{parentName:"p"},"which type")," of project you want to create. There are ",Object(a.b)("em",{parentName:"p"},"3 different type")," of projects we can create. In above image, we will create ",Object(a.b)("em",{parentName:"p"},"an empty project"),".")),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"It is ",Object(a.b)("em",{parentName:"p"},"the name of project")," we want to create. We named our project as ",Object(a.b)("strong",{parentName:"p"},"OpenSolidworkTest"),".")),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"The location of project we want. We use default location provided in above image.")),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"It is option ",Object(a.b)("em",{parentName:"p"},"if we want to create a Solution file for this project or not"),". In our case, we want to create a ",Object(a.b)("em",{parentName:"p"},"Solution file"),".")),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"Hit ",Object(a.b)("strong",{parentName:"p"},"Ok")," button after completing all fields."))),Object(a.b)("hr",null),Object(a.b)("h2",{id:"add-source-file"},"Add Source file"),Object(a.b)("p",null,"After creating a new project, we get a screen as shown in below image."),Object(a.b)("p",null,Object(a.b)("img",{alt:"after-new-project",src:n(276).default})),Object(a.b)("p",null,"This project has no file to write."),Object(a.b)("p",null,"Now we add a cpp file into ",Object(a.b)("em",{parentName:"p"},"Source Files filter folder"),"."),Object(a.b)("p",null,"For this please follow given steps:"),Object(a.b)("ol",null,Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"For this select ",Object(a.b)("em",{parentName:"p"},"Source Files filter folder")," and ",Object(a.b)("em",{parentName:"p"},"Click Right Mouse Button (RMB)"),".")),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"By doing this ",Object(a.b)("em",{parentName:"p"},"a context menu")," is appear as shown in below image.")),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"From this ",Object(a.b)("em",{parentName:"p"},"context menu"),", select ",Object(a.b)("strong",{parentName:"p"},'"Add"')," --\x3e ",Object(a.b)("strong",{parentName:"p"},'"New Item"'),", as shown in below image."))),Object(a.b)("p",null,Object(a.b)("img",{alt:"add-new-cpp-file",src:n(277).default})),Object(a.b)("p",null,"This will open a new window as shown in below image."),Object(a.b)("p",null,Object(a.b)("img",{alt:"add-new-cpp-file-window",src:n(278).default})),Object(a.b)("p",null,'Just select "',Object(a.b)("strong",{parentName:"p"},"Add"),'" option as shown in above image.'),Object(a.b)("p",null,'This will add "',Object(a.b)("strong",{parentName:"p"},"Source.cpp"),'" file into our project.'),Object(a.b)("hr",null),Object(a.b)("h2",{id:"add-references-to-solidworks-files"},"Add References to Solidworks files"),Object(a.b)("p",null,"Now we need to ",Object(a.b)("em",{parentName:"p"},"add References to Solidworks Type Library files.")),Object(a.b)("p",null,"For this please follow below steps."),Object(a.b)("ol",null,Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"Select the ",Object(a.b)("strong",{parentName:"p"},"OpenSolidworkTest")," project and and ",Object(a.b)("em",{parentName:"p"},"Click Right Mouse Button (RMB)"),".")),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"By doing this ",Object(a.b)("em",{parentName:"p"},"a context menu")," is appear as shown in below image.")),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"From this ",Object(a.b)("em",{parentName:"p"},"context menu"),", select ",Object(a.b)("strong",{parentName:"p"},'"Properties"')," option, which is the last one, as shown in below image."))),Object(a.b)("p",null,Object(a.b)("img",{alt:"open-property-window",src:n(168).default})),Object(a.b)("p",null,"This will open a new window as shown in below image."),Object(a.b)("p",null,Object(a.b)("img",{alt:"project-property-window",src:n(169).default})),Object(a.b)("p",null,"Now following below steps:"),Object(a.b)("ol",null,Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},"Select C/C++ option")),Object(a.b)("li",{parentName:"ol"},Object(a.b)("p",{parentName:"li"},'Add SOLIDWORKS folders path to 2nd Red colored box as shown in below image. Usually this path is "',Object(a.b)("inlineCode",{parentName:"p"},"C:\\Program Files\\ Solidworks Corp\\SOLIDWORKS"),'" if installed in default location.'))),Object(a.b)("p",null,Object(a.b)("img",{alt:"add-solidowrks-reference",src:n(170).default})),Object(a.b)("p",null,'After adding the folder path, select "',Object(a.b)("strong",{parentName:"p"},"Apply"),'" button.'),Object(a.b)("p",null,"This complete the process of ",Object(a.b)("em",{parentName:"p"},"adding References to Solidworks Type Library files.")),Object(a.b)("hr",null),Object(a.b)("h2",{id:"add-code-to-sourcecpp-file"},"Add Code to Source.cpp file"),Object(a.b)("p",null,"Now we need to add to ",Object(a.b)("em",{parentName:"p"},"Source.cpp")," file."),Object(a.b)("p",null,"Please copy the below code sample to your ",Object(a.b)("em",{parentName:"p"},"Source.cpp")," file."),Object(a.b)("pre",null,Object(a.b)("code",Object(o.a)({parentName:"pre"},{className:"language-cpp"}),'#include <atlbase.h>\n\n#import "sldworks.tlb" raw_interfaces_only, raw_native_types, no_namespace, named_guids  // SOLIDWORKS type library\n\n#import "swconst.tlb" raw_interfaces_only, raw_native_types, no_namespace, named_guids   // SOLIDWORKS constants type library\n\nint main()\n{\n    // Initialize COM\n    // Do this before using ATL smart pointers so COM is available.\n    CoInitialize(NULL);\n\n    // Use a block, so the smart pointers are destructed when the scope of this block is left\n    {\n        // COM Pointer of Soldiworks object\n        CComPtr<ISldWorks> swApp;\n\n        // Create an instance of Solidworks application\n        // If it fails then return 0 and close program\n        if (swApp.CoCreateInstance(__uuidof(SldWorks), NULL, CLSCTX_LOCAL_SERVER) != S_OK) \n        {\n            // Stop COM \n            CoUninitialize();\n            return(0);\n        }\n\n        // If created successfully, then visible the Solidworks\n        swApp->put_Visible(VARIANT_TRUE);\n\n        // COM Style String for message to user\n        CComBSTR _messageToUser(L"Hello World!!! I am from Solidworks C++ API.");\n\n        // long type variable to store the result value by user\n        long _lMessageResult;\n\n        // Send a message to user and store the return value in _lMessageResult by referencing it\n        swApp->SendMsgToUser2(_messageToUser, swMessageBoxIcon_e::swMbInformation, swMessageBoxBtn_e::swMbOk, &_lMessageResult);\n    }\n\n    // Stop COM \n    CoUninitialize();\n}\n')),Object(a.b)("p",null,"Now Build the Solution as shown in below image."),Object(a.b)("p",null,Object(a.b)("img",{alt:"build-solution",src:n(171).default})),Object(a.b)("p",null,"After Building Solution run the program by pressing ",Object(a.b)("strong",{parentName:"p"},"F5"),"."),Object(a.b)("hr",null),Object(a.b)("h2",{id:"final-result"},"Final Result"),Object(a.b)("p",null,"After running the program wait for few minute."),Object(a.b)("p",null,"You will get result as shown in below image!!!"),Object(a.b)("p",null,Object(a.b)("img",{alt:"hello-world-message.png",src:n(279).default})),Object(a.b)("hr",null),Object(a.b)("p",null,Object(a.b)("strong",{parentName:"p"},"This is it !!!")),Object(a.b)("p",null,"We have completed our ",Object(a.b)("em",{parentName:"p"},"Hello World")," program in ",Object(a.b)("em",{parentName:"p"},"Solidworks")," using ",Object(a.b)("strong",{parentName:"p"},"Solidworks C++ APIs"),"."),Object(a.b)("p",null,"Hope this post helps you to start with ",Object(a.b)("em",{parentName:"p"},"Solidworks C++ API"),"."),Object(a.b)("p",null,Object(a.b)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),Object(a.b)("p",null,Object(a.b)("em",{parentName:"p"},"Do let me know by you like this post or not! I will continue creating Solidworks C++ posts.")),Object(a.b)("p",null,Object(a.b)("em",{parentName:"p"},"Till then, Happy learning!!!")))}b.isMDXComponent=!0},152:function(e,t,n){"use strict";n.d(t,"a",(function(){return s})),n.d(t,"b",(function(){return m}));var o=n(0),r=n.n(o);function a(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function l(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var o=Object.getOwnPropertySymbols(e);t&&(o=o.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,o)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?l(Object(n),!0).forEach((function(t){a(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):l(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function p(e,t){if(null==e)return{};var n,o,r=function(e,t){if(null==e)return{};var n,o,r={},a=Object.keys(e);for(o=0;o<a.length;o++)n=a[o],t.indexOf(n)>=0||(r[n]=e[n]);return r}(e,t);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);for(o=0;o<a.length;o++)n=a[o],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(r[n]=e[n])}return r}var c=r.a.createContext({}),b=function(e){var t=r.a.useContext(c),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},s=function(e){var t=b(e.components);return r.a.createElement(c.Provider,{value:t},e.children)},u={inlineCode:"code",wrapper:function(e){var t=e.children;return r.a.createElement(r.a.Fragment,{},t)}},d=r.a.forwardRef((function(e,t){var n=e.components,o=e.mdxType,a=e.originalType,l=e.parentName,c=p(e,["components","mdxType","originalType","parentName"]),s=b(n),d=o,m=s["".concat(l,".").concat(d)]||s[d]||u[d]||a;return n?r.a.createElement(m,i(i({ref:t},c),{},{components:n})):r.a.createElement(m,i({ref:t},c))}));function m(e,t){var n=arguments,o=t&&t.mdxType;if("string"==typeof e||o){var a=n.length,l=new Array(a);l[0]=d;var i={};for(var p in t)hasOwnProperty.call(t,p)&&(i[p]=t[p]);i.originalType=e,i.mdxType="string"==typeof e?e:o,l[1]=i;for(var c=2;c<a;c++)l[c]=n[c];return r.a.createElement.apply(null,l)}return r.a.createElement.apply(null,n)}d.displayName="MDXCreateElement"},168:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/open-property-window-fbed5c07225a50d940c99768ebb68f86.png"},169:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/project-property-window-71bcffa26b32a7297231b56e5ae5d052.png"},170:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/add-solidowrks-reference-1a1ca5269a89c20dcf68687bed4f57f1.png"},171:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/build-solution-588c7601214b803be92cd586a148bb2e.png"},273:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/new-project-1-183e52449b810d1d939bd1f19581eed9.png"},274:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/new-project-2-c2128bf2aea6c97b2b58abd8c8607618.png"},275:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/create-project-94a23117f2a7ba3c241cb6ed4d1d2810.png"},276:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/after-new-project-50c7ebbac93b95a3e78a043b3aae04ee.png"},277:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/add-new-cpp-file-e6daf7554eb4075270cf943bfb03780c.png"},278:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/add-new-cpp-file-window-0c8908b909b3b72299caecfc65f37477.png"},279:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/hello-world-message-121ebb35b5936cf28ab810f9556a4992.png"}}]);