(window.webpackJsonp=window.webpackJsonp||[]).push([[67],{124:function(e,t,a){"use strict";a.r(t),a.d(t,"frontMatter",(function(){return o})),a.d(t,"metadata",(function(){return c})),a.d(t,"rightToc",(function(){return i})),a.d(t,"default",(function(){return l}));var n=a(2),r=a(6),b=(a(0),a(152)),o={id:"sw-sketch-macro-linear-sketch-patterm",title:"Linear Sketch Pattern"},c={unversionedId:"solidworks-macros/sw-sketch-macro-linear-sketch-patterm",id:"solidworks-macros/sw-sketch-macro-linear-sketch-patterm",isDocsHomePage:!1,title:"Linear Sketch Pattern",description:"In this post, I tell you about how to Linear Sketch Pattern using Solidworks VBA Macros in a Sketch.",source:"@site/docs\\solidworks-macros\\2020-01-20-linear-skech-pattern.md",slug:"/solidworks-macros/sw-sketch-macro-linear-sketch-patterm",permalink:"/docs/solidworks-macros/sw-sketch-macro-linear-sketch-patterm",version:"current",sidebar:"swvba",previous:{title:"Mirror Sketch Entities",permalink:"/docs/solidworks-macros/sw-sketch-macro-mirror-sketch-entities"},next:{title:"Edit Linear Sketch Pattern",permalink:"/docs/solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm"}},i=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",children:[]},{value:"For Experience Macro Developer",id:"for-experience-macro-developer",children:[]},{value:"For Beginners Macro Developers",id:"for-beginners-macro-developers",children:[{value:"Understanding the Code",id:"understanding-the-code",children:[]},{value:"NOTE",id:"note",children:[]}]},{value:"VBA Language feature used in this post",id:"vba-language-feature-used-in-this-post",children:[]},{value:"Solidworks API Objects",id:"solidworks-api-objects",children:[]}],p={rightToc:i};function l(e){var t=e.components,o=Object(r.a)(e,["components"]);return Object(b.b)("wrapper",Object(n.a)({},p,o,{components:t,mdxType:"MDXLayout"}),Object(b.b)("p",null,"In this post, I tell you about ",Object(b.b)("strong",{parentName:"p"},"how to Linear Sketch Pattern using Solidworks VBA Macros")," in a Sketch."),Object(b.b)("hr",null),Object(b.b)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),Object(b.b)("p",null,"Please see below video how visually we ",Object(b.b)("em",{parentName:"p"},"Linear Sketch Pattern")," in ",Object(b.b)("strong",{parentName:"p"},"Solidworks VBA macro"),"."),Object(b.b)("div",{class:"youtube-responsive-container"},Object(b.b)("iframe",{src:"https://www.youtube.com/embed/kvkj2qWPoQM",frameborder:"0",allowfullscreen:!0})),Object(b.b)("p",null,"Please note that there are ",Object(b.b)("strong",{parentName:"p"},"no explaination")," in the video. "),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),Object(b.b)("hr",null),Object(b.b)("h2",{id:"for-experience-macro-developer"},"For Experience Macro Developer"),Object(b.b)("p",null,"If you are an experience ",Object(b.b)("strong",{parentName:"p"},"Solidworks Macro developer"),", then you are looking for a specific code sample."),Object(b.b)("p",null,"Below is the code for ",Object(b.b)("strong",{parentName:"p"},"Linear Sketch Pattern")," from ",Object(b.b)("strong",{parentName:"p"},"Solidworks VBA Macro"),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Boolean Variable\nDim BoolStatus As Boolean\n\n\' Select Circle we want to Pattern\nBoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n\' Create a Linear Sketch Pattern\nBoolStatus = swSketchManager.CreateLinearSketchStepAndRepeat(1, 3, 1, 1, 0, 1.57, "", False, True, True, False, True)\n')),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Method Name"),": ",Object(b.b)("inlineCode",{parentName:"p"},"CreateLinearSketchStepAndRepeat")),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Description"),": Create ",Object(b.b)("em",{parentName:"p"},"Linear Sketch Pattern")," of the selected sketch entity or entities."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Prerequisites"),": To create a ",Object(b.b)("strong",{parentName:"p"},"Linear Sketch Pattern")," a Solidworks Sketch entity or entities, first we need following things:"),Object(b.b)("ol",null,Object(b.b)("li",{parentName:"ol"},Object(b.b)("p",{parentName:"li"},"Sketch Entity/Entities to ",Object(b.b)("em",{parentName:"p"},"Pattern"))),Object(b.b)("li",{parentName:"ol"},Object(b.b)("p",{parentName:"li"},"That Entity/Entities is selected before pattern"))),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"How it works"),":"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"For ",Object(b.b)("strong",{parentName:"p"},"Linear Sketch Pattern"),", first you need to ",Object(b.b)("strong",{parentName:"p"},"Create")," a variable of ",Object(b.b)("inlineCode",{parentName:"p"},"Boolean")," type.")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"After creating variable, you need to set the value of this ",Object(b.b)("inlineCode",{parentName:"p"},"Boolean")," variable.")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"For this you used ",Object(b.b)("inlineCode",{parentName:"p"},"CreateLinearSketchStepAndRepeat")," method from ",Object(b.b)("strong",{parentName:"p"},"Solidworks Sketch Manager"),".")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"This ",Object(b.b)("inlineCode",{parentName:"p"},"CreateLinearSketchStepAndRepeat")," method set the value of ",Object(b.b)("inlineCode",{parentName:"p"},"Boolean")," type variable.")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"If the ",Object(b.b)("em",{parentName:"p"},"Linear Sketch Pattern")," is ",Object(b.b)("strong",{parentName:"p"},"successful")," then ",Object(b.b)("inlineCode",{parentName:"p"},"CreateLinearSketchStepAndRepeat")," method return ",Object(b.b)("strong",{parentName:"p"},"True")," value otherwise ",Object(b.b)("inlineCode",{parentName:"p"},"CreateLinearSketchStepAndRepeat")," returns ",Object(b.b)("strong",{parentName:"p"},"False")," value."))),Object(b.b)("p",null,"This ",Object(b.b)("inlineCode",{parentName:"p"},"CreateLinearSketchStepAndRepeat")," method takes following parameters as explained:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumX")," : ",Object(b.b)("em",{parentName:"p"},"Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis, including the seed i.e. original entity/entities."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumY")," : ",Object(b.b)("em",{parentName:"p"},"Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis, including the seed i.e. original entity/entities."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingX")," : ",Object(b.b)("em",{parentName:"p"},"Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingY")," : ",Object(b.b)("em",{parentName:"p"},"Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleX")," : ",Object(b.b)("em",{parentName:"p"},"Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleY")," : ",Object(b.b)("em",{parentName:"p"},"Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"DeleteInstances")," : ",Object(b.b)("em",{parentName:"p"},'Number of instances to delete, passed as a string in the format: "(a) (b) (c)".'))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"XSpacingDim")," : ",Object(b.b)("em",{parentName:"p"},"True to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis in the graphics area, false to not"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"YSpacingDim")," : ",Object(b.b)("em",{parentName:"p"},"True to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis in the graphics area, false to not"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleDim")," : ",Object(b.b)("em",{parentName:"p"},"True to display the angle dimension between axes in the graphics area, false to not."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInXDir")," : ",Object(b.b)("em",{parentName:"p"},"True to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"x")," direction dimension in the graphics area, false to not."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInYDir")," : ",Object(b.b)("em",{parentName:"p"},"True to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"y")," direction dimension in the graphics area, false to not.")))),Object(b.b)("p",null,"If you want more detailed explaination then please read further otherwise this will help you to create a ",Object(b.b)("strong",{parentName:"p"},"Linear Sketch Pattern From VBA Macro"),"."),Object(b.b)("hr",null),Object(b.b)("h2",{id:"for-beginners-macro-developers"},"For Beginners Macro Developers"),Object(b.b)("p",null,"In this post, I tell you about ",Object(b.b)("inlineCode",{parentName:"p"},"CreateLinearSketchStepAndRepeat")," method from ",Object(b.b)("strong",{parentName:"p"},"Solidworks")," ",Object(b.b)("inlineCode",{parentName:"p"},"SketchManager")," object."),Object(b.b)("p",null,"This method is ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"most updated"))," method, I found in ",Object(b.b)("em",{parentName:"p"},"Solidworks API Help"),". "),Object(b.b)("p",null,"So ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"use this method"))," if you want to create ",Object(b.b)("em",{parentName:"p"},"Linear Sketch Pattern"),"."),Object(b.b)("p",null,"Below is the ",Object(b.b)("inlineCode",{parentName:"p"},"code")," sample to create ",Object(b.b)("em",{parentName:"p"},"Linear Sketch Pattern"),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Set Sketch Segment value and Create a Circle\n  Set swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, 0.2)\n  \n  ' De-select the lines after creation\n  swDoc.ClearSelection2 True\n\n  ' Select Circle we want to Pattern\n  BoolStatus = swDoc.Extension.SelectByID2(\"Arc1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Create a Linear Sketch Pattern\n  BoolStatus = swSketchManager.CreateLinearSketchStepAndRepeat(3, 1, 1, 0, 0, 0, \"\", True, False, True, True, False)\n  \n  ' De-select the Sketch Segment after Linear Sketch Pattern\n  swDoc.ClearSelection2 True\n  \n  ' Show Front View after Linear Sketch Pattern\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n\nEnd Sub\n")),Object(b.b)("hr",null),Object(b.b)("h3",{id:"understanding-the-code"},"Understanding the Code"),Object(b.b)("p",null,"Now let us walk through ",Object(b.b)("strong",{parentName:"p"},"each line")," in the above code, and ",Object(b.b)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),Object(b.b)("p",null,"I also give some link so that you can go through them if there are anything I explained in previous posts."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n")),Object(b.b)("p",null,"This line forces us to define every variable we are going to use. "),Object(b.b)("p",null,"For more information please visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),Object(b.b)("p",null,"In this line, we create a variable which we named as ",Object(b.b)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",Object(b.b)("inlineCode",{parentName:"p"},"swApp")," variable is ",Object(b.b)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),Object(b.b)("p",null,"In this line, we create a variable which we named as ",Object(b.b)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",Object(b.b)("inlineCode",{parentName:"p"},"swDoc")," variable is ",Object(b.b)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Boolean Variable\nDim BoolStatus As Boolean\n")),Object(b.b)("p",null,"In this line, we create a variable named ",Object(b.b)("inlineCode",{parentName:"p"},"BoolStatus")," as ",Object(b.b)("inlineCode",{parentName:"p"},"Boolean")," object type."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),Object(b.b)("p",null,"In above line, we create variable ",Object(b.b)("inlineCode",{parentName:"p"},"swSketchManager")," for ",Object(b.b)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(b.b)("p",null,"As the name suggested, a ",Object(b.b)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",Object(b.b)("em",{parentName:"p"},"Sketches"),"."),Object(b.b)("p",null,"To see methods and properties related to ",Object(b.b)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"}),"this page")),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n")),Object(b.b)("p",null,"In this line, we Create a variable which we named as ",Object(b.b)("inlineCode",{parentName:"p"},"swSketchSegment")," and the type of this ",Object(b.b)("inlineCode",{parentName:"p"},"swSketchSegment")," variable is ",Object(b.b)("inlineCode",{parentName:"p"},"SldWorks.SketchSegment"),"."),Object(b.b)("p",null,"We create variable ",Object(b.b)("inlineCode",{parentName:"p"},"swSketchSegment")," for ",Object(b.b)("strong",{parentName:"p"},"Solidworks Sketch Segments"),"."),Object(b.b)("p",null,"To see methods and properties related to ",Object(b.b)("inlineCode",{parentName:"p"},"swSketchSegment")," object, please visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"}),"this page")),"."),Object(b.b)("p",null,"These all are our global variables."),Object(b.b)("p",null,"As you can see in code sample, they are ",Object(b.b)("strong",{parentName:"p"},"Solidworks API Objects"),"."),Object(b.b)("p",null,"So basically I group all the ",Object(b.b)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),Object(b.b)("p",null,"I have also place ",Object(b.b)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",Object(b.b)("em",{parentName:"p"},"need")," this variable frequently."),Object(b.b)("p",null,"Thus, I have started placing it here."),Object(b.b)("p",null,"Next is our ",Object(b.b)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",Object(b.b)("inlineCode",{parentName:"p"},"main"),". "),Object(b.b)("p",null,"This procedure hold all the ",Object(b.b)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),Object(b.b)("p",null,"In this line, we set the value of our Solidworks variable ",Object(b.b)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Create string type variable for storing default part location\nDim defaultTemplate As String\n' Set value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),Object(b.b)("p",null,"In 1st statement of above example, we are defining a variable of ",Object(b.b)("inlineCode",{parentName:"p"},"string")," type and named it as ",Object(b.b)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),Object(b.b)("p",null,"This variable ",Object(b.b)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",Object(b.b)("strong",{parentName:"p"},"Default Part Template"),"."),Object(b.b)("p",null,"In 2nd line of above example. we assign value to our newly define ",Object(b.b)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),Object(b.b)("p",null,"We assign the value by using a ",Object(b.b)("em",{parentName:"p"},"Method")," named ",Object(b.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),Object(b.b)("p",null,"This ",Object(b.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," method is a part of our main Solidworks variable ",Object(b.b)("inlineCode",{parentName:"p"},"swApp"),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Set Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),Object(b.b)("p",null,"In this line, we set the value of our ",Object(b.b)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),Object(b.b)("p",null,"For ",Object(b.b)("strong",{parentName:"p"},"detailed information")," about these lines please visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post."),Object(b.b)("p",null,"I have discussed them ",Object(b.b)("strong",{parentName:"p"},"thoroghly")," in ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post, so do checkout that post if you want to understand above code in more detail."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),Object(b.b)("p",null,"In above line, we select the ",Object(b.b)("em",{parentName:"p"},"front plane")," by using ",Object(b.b)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",Object(b.b)("inlineCode",{parentName:"p"},"Extension")," object."),Object(b.b)("p",null,"For more information about selection method please visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"sw-macro-selection-methods"}),"Solidworks Macros - Selection Methods"))," post."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Set Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),Object(b.b)("p",null,"In above line, we set the ",Object(b.b)("em",{parentName:"p"},"Sketch manager")," variable to ",Object(b.b)("em",{parentName:"p"},"current document's sketch manager"),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Insert a sketch into selected plane\nswSketchManager.InsertSketch True\n")),Object(b.b)("p",null,"In above line, we use ",Object(b.b)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",Object(b.b)("em",{parentName:"p"},"SketchManager")," and give ",Object(b.b)("inlineCode",{parentName:"p"},"True")," value."),Object(b.b)("p",null,"This method allows us to insert a sketch in selected plane."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Set Sketch Segment value and Create a Circle\nSet swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, 0.2)\n")),Object(b.b)("p",null,"In above line, we set the value of Solidworks Sketch Segment variable ",Object(b.b)("inlineCode",{parentName:"p"},"swSketchSegment")," by ",Object(b.b)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method from ",Object(b.b)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(b.b)("p",null,"This ",Object(b.b)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method creates ",Object(b.b)("em",{parentName:"p"},"a Circle")," at given point with radius."),Object(b.b)("p",null,"For more information about ",Object(b.b)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method, you can read my ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"sw-sketch-macro-create-circle-by-radius"}),"Solidworks Macro - Create Circle By Radius From VBA Macro"))," post."),Object(b.b)("p",null,"That post describe all the parameters we need for this ",Object(b.b)("inlineCode",{parentName:"p"},"CreateCircleByRadius")," method in details."),Object(b.b)("p",null,"In above line, we create a Circle with:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"Circle Centerpoint")," : At origin i.e. ",Object(b.b)("em",{parentName:"p"},"(0, 0, 0)"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"Circle Radius")," : ",Object(b.b)("em",{parentName:"p"},"0.2")))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' De-select the lines after creation\nswDoc.ClearSelection2 True\n")),Object(b.b)("p",null,"After creating the circle we ",Object(b.b)("em",{parentName:"p"},"de-select")," it."),Object(b.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(b.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-heading"}),Object(b.b)("h5",{parentName:"div"},Object(b.b)("span",Object(n.a)({parentName:"h5"},{className:"admonition-icon"}),Object(b.b)("svg",Object(n.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(b.b)("path",Object(n.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(b.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-content"}),Object(b.b)("p",{parentName:"div"},"We ",Object(b.b)("strong",{parentName:"p"},"don't need")," to de-select the circle for ",Object(b.b)("strong",{parentName:"p"},"Pattern")," as we will select the circle agains in next line. I just want to show you how to select a ",Object(b.b)("strong",{parentName:"p"},"Sketch Segment")," with ",Object(b.b)("inlineCode",{parentName:"p"},"SelectById")," Menthod in next line of code."))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Select Circle we want to Pattern\nBoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),Object(b.b)("p",null,"In above line of code, we select the Circle i.e. ",Object(b.b)("strong",{parentName:"p"},"Arc 1")," and add it to selection list."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Create a Linear Sketch Pattern\nBoolStatus = swSketchManager.CreateLinearSketchStepAndRepeat(3, 1, 1, 0, 0, 0, "", True, False, True, True, False)\n')),Object(b.b)("p",null,"In above line, we ",Object(b.b)("strong",{parentName:"p"},"Pattern")," selected ",Object(b.b)("em",{parentName:"p"},"Circle")," by ",Object(b.b)("inlineCode",{parentName:"p"},"CreateLinearSketchStepAndRepeat")," method from ",Object(b.b)("em",{parentName:"p"},"Solidworks Sketch Manger")," variable."),Object(b.b)("p",null,"This ",Object(b.b)("inlineCode",{parentName:"p"},"CreateLinearSketchStepAndRepeat")," method takes following parameters as explained:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumX")," : ",Object(b.b)("em",{parentName:"p"},"Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis, including the seed i.e. original entity/entities."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumY")," : ",Object(b.b)("em",{parentName:"p"},"Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis, including the seed i.e. original entity/entities."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingX")," : ",Object(b.b)("em",{parentName:"p"},"Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingY")," : ",Object(b.b)("em",{parentName:"p"},"Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleX")," : ",Object(b.b)("em",{parentName:"p"},"Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleY")," : ",Object(b.b)("em",{parentName:"p"},"Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"DeleteInstances")," : ",Object(b.b)("em",{parentName:"p"},'Number of instances to delete, passed as a string in the format: "(a) (b) (c)".'))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"XSpacingDim")," : ",Object(b.b)("em",{parentName:"p"},"True to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis in the graphics area, false to not"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"YSpacingDim")," : ",Object(b.b)("em",{parentName:"p"},"True to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis in the graphics area, false to not"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleDim")," : ",Object(b.b)("em",{parentName:"p"},"True to display the angle dimension between axes in the graphics area, false to not."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInXDir")," : ",Object(b.b)("em",{parentName:"p"},"True to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"x")," direction dimension in the graphics area, false to not."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInYDir")," : ",Object(b.b)("em",{parentName:"p"},"True to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"y")," direction dimension in the graphics area, false to not.")))),Object(b.b)("p",null,"After the function complete following are the results:"),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Return Value"),":"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"True"),": ",Object(b.b)("em",{parentName:"p"},"If Linear Sketch Pattern is "),"Success",Object(b.b)("em",{parentName:"p"},"."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"False"),": ",Object(b.b)("em",{parentName:"p"},"If Linear Sketch Pattern is "),"Fail",Object(b.b)("em",{parentName:"p"},".")))),Object(b.b)("p",null,"In our code, I have used following values:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumX")," : ",Object(b.b)("em",{parentName:"p"},"I have used ",Object(b.b)("strong",{parentName:"em"},"3")," as Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis including original circle."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumY")," : ",Object(b.b)("em",{parentName:"p"},"I have used ",Object(b.b)("strong",{parentName:"em"},"1")," as Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis which includes original circle only.")),Object(b.b)("div",Object(n.a)({parentName:"li"},{className:"admonition admonition-note alert alert--secondary"}),Object(b.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-heading"}),Object(b.b)("h5",{parentName:"div"},Object(b.b)("span",Object(n.a)({parentName:"h5"},{className:"admonition-icon"}),Object(b.b)("svg",Object(n.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(b.b)("path",Object(n.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(b.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-content"}),Object(b.b)("p",{parentName:"div"},Object(b.b)("em",{parentName:"p"},"Even uf you don't want to pattern in ",Object(b.b)("strong",{parentName:"em"},"Y")," direction, you have to give atleast 1 as a value. Same goes for ",Object(b.b)("strong",{parentName:"em"},"X")," direction."))))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingX")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"1")," as Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingY")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"0")," Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleX")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"0")," Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleY")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"0")," Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"DeleteInstances")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},'""')," as Number of instances to delete, because I don't want to delete any instances."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"XSpacingDim")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"True")," to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis in the graphics area."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"YSpacingDim")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"False")," to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis in the graphics area."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleDim")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"True")," to display the angle dimension between axes in the graphics area."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInXDir")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"True")," to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"x")," direction dimension in the graphics area."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInYDir")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"False")," to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"y")," direction dimension in the graphics area.")))),Object(b.b)("p",null,"Below image shows before and after Linear Sketch Pattern."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Before Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"before-linear-pattern",src:a(302).default})),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"After Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"after-linear-pattern",src:a(172).default})),Object(b.b)("hr",null),Object(b.b)("h3",{id:"note"},"NOTE"),Object(b.b)("p",null,"It is ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",Object(b.b)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Meter only")),"."),Object(b.b)("p",null,"Please see below for detail:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"Length: ",Object(b.b)("strong",{parentName:"p"},"Meter"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"Angle: ",Object(b.b)("strong",{parentName:"p"},"Radian")))),Object(b.b)("p",null,"Solidworks API does not care about your application's Unit systems."),Object(b.b)("p",null,"For example, I works in ",Object(b.b)("strong",{parentName:"p"},"ANSI")," system means ",Object(b.b)("em",{parentName:"p"},"inches")," for distance. But when I used ",Object(b.b)("strong",{parentName:"p"},"Solidworks API")," through ",Object(b.b)("em",{parentName:"p"},"VBA macros or C#"),", I need to converted numeric values."),Object(b.b)("p",null,"Because Solidworks API output the distance in ",Object(b.b)("strong",{parentName:"p"},"Meter")," which is not my requirement."),Object(b.b)("hr",null),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' De-select the Sketch after creation\nswDoc.ClearSelection2 True\n")),Object(b.b)("p",null,"In the above line of code, we deselect the ",Object(b.b)("strong",{parentName:"p"},"Sketch")," after the ",Object(b.b)("em",{parentName:"p"},"Linear Sketch Pattern")," operation."),Object(b.b)("p",null,"For de-selecting, we use ",Object(b.b)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",Object(b.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Show Front View after Linear Sketch Pattern\nswDoc.ShowNamedView2 "", swStandardViews_e.swFrontView\n')),Object(b.b)("p",null,"In the above line of code, we update the ",Object(b.b)("em",{parentName:"p"},"view orientation")," to ",Object(b.b)("strong",{parentName:"p"},"Front View"),"."),Object(b.b)("p",null,"In my machine, after inserting a sketch view orientation does not changed."),Object(b.b)("p",null,"Because of this I have to update the view to ",Object(b.b)("strong",{parentName:"p"},"Front view"),"."),Object(b.b)("p",null,"For showing ",Object(b.b)("strong",{parentName:"p"},"Front View")," we used ",Object(b.b)("inlineCode",{parentName:"p"},"ShowNamedView2")," method from our Solidworks document name ",Object(b.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(b.b)("p",null,"This method takes 2 parameter described as follows:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"VName")," : Name of the view to display or an empty string to use ViewId instead")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"ViewId")," : ID of the view to display as defined by ",Object(b.b)("inlineCode",{parentName:"p"},"swStandardViews_e")," or -1 to use the ",Object(b.b)("strong",{parentName:"p"},"VName")," argument instead."))),Object(b.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(b.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-heading"}),Object(b.b)("h5",{parentName:"div"},Object(b.b)("span",Object(n.a)({parentName:"h5"},{className:"admonition-icon"}),Object(b.b)("svg",Object(n.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(b.b)("path",Object(n.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(b.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-content"}),Object(b.b)("p",{parentName:"div"},"If you specify both ",Object(b.b)("strong",{parentName:"p"},"VName")," and ",Object(b.b)("strong",{parentName:"p"},"ViewId"),", then ",Object(b.b)("strong",{parentName:"p"},"ViewId")," takes precedence if the two arguments do not resolve to the same view."))),Object(b.b)("p",null,Object(b.b)("inlineCode",{parentName:"p"},"swStandardViews_e")," has following Standard View Types:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"swBackView"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"swBottomView"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"swDimetricView"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"swFrontView"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"swIsometricView"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"swLeftView"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"swRightView"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"swTopView"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"swExtendetricView")))),Object(b.b)("p",null,"In our code, we did not use ",Object(b.b)("strong",{parentName:"p"},"VName")," instead I used ",Object(b.b)("em",{parentName:"p"},"empty string")," in form of ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},'""'))," symbol."),Object(b.b)("p",null,"I used ",Object(b.b)("strong",{parentName:"p"},"ViewId")," value to specify view and used ",Object(b.b)("inlineCode",{parentName:"p"},"swStandardViews_e.swFrontView")," value to use ",Object(b.b)("em",{parentName:"p"},"Standard Front View"),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),Object(b.b)("p",null,"In this last line we use ",Object(b.b)("em",{parentName:"p"},"zoom to fit")," command."),Object(b.b)("p",null,"For Zoom to fit, we use ",Object(b.b)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",Object(b.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(b.b)("p",null,"This is it !!!"),Object(b.b)("p",null,"If you found anything to add or update, please let me know on my e-mail."),Object(b.b)("hr",null),Object(b.b)("h2",{id:"vba-language-feature-used-in-this-post"},"VBA Language feature used in this post"),Object(b.b)("p",null,"In this post used some features of ",Object(b.b)("strong",{parentName:"p"},"VBA programming language"),"."),Object(b.b)("p",null,"This section of post, has some brief information about the VBA programming language specific features."),Object(b.b)("ol",null,Object(b.b)("li",{parentName:"ol"},"We use ",Object(b.b)("strong",{parentName:"li"},"Option Explicit")," for capturing un-declared variables.")),Object(b.b)("p",null,"If you want to read more about ",Object(b.b)("strong",{parentName:"p"},"Option Explicit")," then please visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"../vba/vba-variables-decl"}),"Declaring and Scoping of Variables")),"."),Object(b.b)("ol",{start:2},Object(b.b)("li",{parentName:"ol"},"Then we create ",Object(b.b)("strong",{parentName:"li"},"variable")," for different data types.")),Object(b.b)("p",null,"If you know in detail about the ",Object(b.b)("strong",{parentName:"p"},"Variables"),", then please visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"../vba/vba-variables"}),"Variables"))," and ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"../vba/vba-prog-concept#data-types-in-vba"}),"Data-types"))," posts of this blog."),Object(b.b)("p",null,"It will help you to understand what ",Object(b.b)("strong",{parentName:"p"},"Variables")," are and how to use them."),Object(b.b)("ol",{start:3},Object(b.b)("li",{parentName:"ol"},"Then we create ",Object(b.b)("strong",{parentName:"li"},"main Sub procedure")," for our macro.")),Object(b.b)("p",null,"If you know in detail about the ",Object(b.b)("strong",{parentName:"p"},"Sub procedure"),", then I suggest you to visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"../vba/vba-procedures"}),"VBA Sub and Function Procedures"))," and ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"../vba/vba-procedures-exec"}),"Executing Sub and Function Procedures"))," posts of this blog."),Object(b.b)("p",null,"It will help you to understand what ",Object(b.b)("strong",{parentName:"p"},"Procedures")," are and how to use them."),Object(b.b)("ol",{start:4},Object(b.b)("li",{parentName:"ol"},"In most part we create some variables and set their values. We set those values by using some ",Object(b.b)("strong",{parentName:"li"},"functions")," provided from objects.")),Object(b.b)("p",null,"If you don't know about the ",Object(b.b)("strong",{parentName:"p"},"functions"),", then you should visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"../vba/vba-functions"}),"VBA Functions"))," and ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"../vba/vba-functions-adv"}),"VBA Functions that do more"))," posts of this blog."),Object(b.b)("p",null,"It will help you to understand what ",Object(b.b)("strong",{parentName:"p"},"functions")," are and how to use them."),Object(b.b)("hr",null),Object(b.b)("h2",{id:"solidworks-api-objects"},"Solidworks API Objects"),Object(b.b)("p",null,"In this post of ",Object(b.b)("strong",{parentName:"p"},"Linear Sketch Pattern"),", we use ",Object(b.b)("em",{parentName:"p"},"Solidworks API objects and their methods"),"."),Object(b.b)("p",null,"This section contains the list of all ",Object(b.b)("strong",{parentName:"p"},"Solidworks Objects")," used in this post."),Object(b.b)("p",null,"I have also attached links of these ",Object(b.b)("strong",{parentName:"p"},"Solidworks API Objects")," in ",Object(b.b)("strong",{parentName:"p"},"API Help website"),"."),Object(b.b)("p",null,"If you want to explore those objects, you can use these links."),Object(b.b)("p",null,"These Solidworks API Objects are listed below:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"Solidworks Application Object")),Object(b.b)("p",{parentName:"li"},"If you want explore ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(b.b)("strong",{parentName:"p"},"Solidworks Application Object")," object you can visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html"}),"this link")),".")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"Solidworks Document Object")),Object(b.b)("p",{parentName:"li"},"If you want explore ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(b.b)("strong",{parentName:"p"},"Solidworks Document Object")," object you can visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html"}),"this link")),".")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")),Object(b.b)("p",{parentName:"li"},"If you want explore ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(b.b)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")," you can visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"}),"this link")),".")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")),Object(b.b)("p",{parentName:"li"},"If you want explore ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(b.b)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")," you can visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"}),"this link")),"."))),Object(b.b)("hr",null),Object(b.b)("p",null,"Hope this post helps you to ",Object(b.b)("em",{parentName:"p"},"Create Linear Sketch Pattern")," with Solidworks VBA Macros."),Object(b.b)("p",null,"For more such tutorials on ",Object(b.b)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),Object(b.b)("p",null,"If you like the post then please share it with your friends also."),Object(b.b)("p",null,"Do let me know by you like this post or not!"),Object(b.b)("p",null,"Till then, Happy learning!"))}l.isMDXComponent=!0},152:function(e,t,a){"use strict";a.d(t,"a",(function(){return s})),a.d(t,"b",(function(){return j}));var n=a(0),r=a.n(n);function b(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}function o(e,t){var a=Object.keys(e);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);t&&(n=n.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),a.push.apply(a,n)}return a}function c(e){for(var t=1;t<arguments.length;t++){var a=null!=arguments[t]?arguments[t]:{};t%2?o(Object(a),!0).forEach((function(t){b(e,t,a[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(a)):o(Object(a)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(a,t))}))}return e}function i(e,t){if(null==e)return{};var a,n,r=function(e,t){if(null==e)return{};var a,n,r={},b=Object.keys(e);for(n=0;n<b.length;n++)a=b[n],t.indexOf(a)>=0||(r[a]=e[a]);return r}(e,t);if(Object.getOwnPropertySymbols){var b=Object.getOwnPropertySymbols(e);for(n=0;n<b.length;n++)a=b[n],t.indexOf(a)>=0||Object.prototype.propertyIsEnumerable.call(e,a)&&(r[a]=e[a])}return r}var p=r.a.createContext({}),l=function(e){var t=r.a.useContext(p),a=t;return e&&(a="function"==typeof e?e(t):c(c({},t),e)),a},s=function(e){var t=l(e.components);return r.a.createElement(p.Provider,{value:t},e.children)},m={inlineCode:"code",wrapper:function(e){var t=e.children;return r.a.createElement(r.a.Fragment,{},t)}},O=r.a.forwardRef((function(e,t){var a=e.components,n=e.mdxType,b=e.originalType,o=e.parentName,p=i(e,["components","mdxType","originalType","parentName"]),s=l(a),O=n,j=s["".concat(o,".").concat(O)]||s[O]||m[O]||b;return a?r.a.createElement(j,c(c({ref:t},p),{},{components:a})):r.a.createElement(j,c({ref:t},p))}));function j(e,t){var a=arguments,n=t&&t.mdxType;if("string"==typeof e||n){var b=a.length,o=new Array(b);o[0]=O;var c={};for(var i in t)hasOwnProperty.call(t,i)&&(c[i]=t[i]);c.originalType=e,c.mdxType="string"==typeof e?e:n,o[1]=c;for(var p=2;p<b;p++)o[p]=a[p];return r.a.createElement.apply(null,o)}return r.a.createElement.apply(null,a)}O.displayName="MDXCreateElement"},172:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/after-linear-pattern-b545e8f2dbb930bd1376406b6e2ad911.png"},302:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/before-linear-pattern-251cc164685e46a45de3320aca3bf51a.png"}}]);