(window.webpackJsonp=window.webpackJsonp||[]).push([[88],{146:function(e,t,n){"use strict";n.r(t),n.d(t,"frontMatter",(function(){return b})),n.d(t,"metadata",(function(){return s})),n.d(t,"rightToc",(function(){return c})),n.d(t,"default",(function(){return l}));var a=n(2),o=n(6),r=(n(0),n(152)),b={id:"sw-sketch-macro-offset-entities",title:"Offset Sketch Entities"},s={unversionedId:"solidworks-macros/sw-sketch-macro-offset-entities",id:"solidworks-macros/sw-sketch-macro-offset-entities",isDocsHomePage:!1,title:"Offset Sketch Entities",description:"In this post, I tell you about how to Offset Sketch Entities using Solidworks VBA Macros in a Sketch.",source:"@site/docs\\solidworks-macros\\2020-01-02-offset-entities.md",slug:"/solidworks-macros/sw-sketch-macro-offset-entities",permalink:"/docs/solidworks-macros/sw-sketch-macro-offset-entities",version:"current",sidebar:"swvba",previous:{title:"Extend Sketch Entities",permalink:"/docs/solidworks-macros/sw-sketch-macro-extend-entities"},next:{title:"Mirror Sketch Entities",permalink:"/docs/solidworks-macros/sw-sketch-macro-mirror-sketch-entities"}},c=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",children:[]},{value:"For Experience Macro Developer",id:"for-experience-macro-developer",children:[]},{value:"For Beginners Macro Developers",id:"for-beginners-macro-developers",children:[{value:"Understanding the Code",id:"understanding-the-code",children:[]},{value:"NOTE",id:"note",children:[]}]},{value:"VBA Language feature used in this post",id:"vba-language-feature-used-in-this-post",children:[]},{value:"Solidworks API Objects",id:"solidworks-api-objects",children:[]}],i={rightToc:c};function l(e){var t=e.components,b=Object(o.a)(e,["components"]);return Object(r.b)("wrapper",Object(a.a)({},i,b,{components:t,mdxType:"MDXLayout"}),Object(r.b)("p",null,"In this post, I tell you about ",Object(r.b)("em",{parentName:"p"},"how to Offset Sketch Entities using Solidworks VBA Macros")," in a Sketch."),Object(r.b)("hr",null),Object(r.b)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),Object(r.b)("p",null,"Please see below video how visually we ",Object(r.b)("em",{parentName:"p"},"Offset Sketch Entities")," in ",Object(r.b)("strong",{parentName:"p"},"Solidworks VBA macro"),"."),Object(r.b)("div",{class:"youtube-responsive-container"},Object(r.b)("iframe",{src:"https://www.youtube.com/embed/jkVph-Rfgs0",frameborder:"0",allowfullscreen:!0})),Object(r.b)("p",null,"Please note that there are ",Object(r.b)("strong",{parentName:"p"},"no explaination")," given in the video. "),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Explaination")," of each line and why we write code this way is given in this post."),Object(r.b)("hr",null),Object(r.b)("h2",{id:"for-experience-macro-developer"},"For Experience Macro Developer"),Object(r.b)("p",null,"If you are an experience ",Object(r.b)("strong",{parentName:"p"},"Solidworks Macro developer"),", then you are looking for a specific code sample."),Object(r.b)("p",null,"Below is the code for ",Object(r.b)("strong",{parentName:"p"},"Offset Sketch Entities")," from ",Object(r.b)("strong",{parentName:"p"},"Solidworks VBA Macro"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Boolean Variable\nDim BoolStatus As Boolean\n\n\' Select Line 1\nBoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n\' Select Line 2\nBoolStatus = swDoc.Extension.SelectByID2("Line2", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n\' Offset Solidworks Sketch segment by "SketchOffset2" method from Solidworks sketch manager\nBoolStatus = swSketchManager.SketchOffset2(0.5, False, False, swSkOffsetCapEndType_e.swSkOffsetNoCaps, swSkOffsetMakeConstructionType_e.swSkOffsetDontMakeConstruction, True)\n')),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Method Name"),": ",Object(r.b)("inlineCode",{parentName:"p"},"SketchOffset2")),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Description"),": ",Object(r.b)("em",{parentName:"p"},"Offsets")," the selected sketch entities."),Object(r.b)("p",null,"For ",Object(r.b)("strong",{parentName:"p"},"Offset")," Solidworks Sketch entities, first you need to ",Object(r.b)("strong",{parentName:"p"},"Create")," a variable of ",Object(r.b)("inlineCode",{parentName:"p"},"Boolean")," type."),Object(r.b)("p",null,"After creating variable, you need to set the value of this ",Object(r.b)("inlineCode",{parentName:"p"},"Boolean")," variable."),Object(r.b)("p",null,"For this you used ",Object(r.b)("inlineCode",{parentName:"p"},"SketchOffset2")," method from ",Object(r.b)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"SketchOffset2")," method set the value of ",Object(r.b)("inlineCode",{parentName:"p"},"Boolean")," type variable."),Object(r.b)("p",null,"If ",Object(r.b)("em",{parentName:"p"},"Offset")," is ",Object(r.b)("strong",{parentName:"p"},"successful")," then ",Object(r.b)("inlineCode",{parentName:"p"},"SketchOffset2")," method return ",Object(r.b)("strong",{parentName:"p"},"True")," value otherwise ",Object(r.b)("inlineCode",{parentName:"p"},"SketchOffset2")," returns ",Object(r.b)("strong",{parentName:"p"},"False")," value."),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"SketchOffset2")," method takes following parameters as explained:"),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Offset")," : ",Object(r.b)("em",{parentName:"p"},"Offset value; negative value offsets the sketch entities in the opposite direction")),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"BothDirections")," : ",Object(r.b)("em",{parentName:"p"},"True to offset the sketch entities in both directions, false to offset the sketch entities in one direction")),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Chain")," : ",Object(r.b)("em",{parentName:"p"},"True to offset the chain of sketch entities, false to offset only the selected sketch entities")),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"CapEnds")," : ",Object(r.b)("em",{parentName:"p"},"Cap the ends as defined by ",Object(r.b)("inlineCode",{parentName:"em"},"swSkOffsetCapEndType_e"))),Object(r.b)("p",null,"  ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetCapEndType_e")," enum defines following different ",Object(r.b)("strong",{parentName:"p"},"End cap types")," ",Object(r.b)("a",Object(a.a)({parentName:"p"},{href:"../vba/vba-constants"}),"constants"),":"),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{}),"* swSkOffsetArcCaps\n\n* swSkOffsetLineCaps\n\n* swSkOffsetNoCaps\n")),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"MakeConstruction")," : ",Object(r.b)("em",{parentName:"p"},"Convert original and offset sketch entities to construction sketch entities as defined by ",Object(r.b)("inlineCode",{parentName:"em"},"swSkOffsetMakeConstructionType_e"))),Object(r.b)("p",null,"  ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetMakeConstructionType_e")," enum defines following different ",Object(r.b)("strong",{parentName:"p"},"Construction Types")," ",Object(r.b)("a",Object(a.a)({parentName:"p"},{href:"../vba/vba-constants"}),"constants"),":"),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{}),"* swSkOffsetDontMakeConstruction\n\n* swSkOffsetMakeBothConstruction\n\n* swSkOffsetMakeOffsConstruction\n\n* swSkOffsetMakeOrigConstruction\n")),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"AddDimensions")," : ",Object(r.b)("strong",{parentName:"p"},"True")," to add the dimension to the offset, false if not want to add the dimension to the offset."),Object(r.b)("p",null,"If you want more detailed explaination then please read further otherwise this will help you to ",Object(r.b)("strong",{parentName:"p"},"Offset Sketch Entities From VBA Macro"),"."),Object(r.b)("hr",null),Object(r.b)("h2",{id:"for-beginners-macro-developers"},"For Beginners Macro Developers"),Object(r.b)("p",null,"In this post, I tell you about ",Object(r.b)("inlineCode",{parentName:"p"},"SketchOffset2")," method from ",Object(r.b)("strong",{parentName:"p"},"Solidworks")," ",Object(r.b)("inlineCode",{parentName:"p"},"SketchManager")," object."),Object(r.b)("p",null,"This method is ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"most updated"))," method, I found in ",Object(r.b)("em",{parentName:"p"},"Solidworks API Help"),". "),Object(r.b)("p",null,"So ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"use this method"))," if you want to ",Object(r.b)("em",{parentName:"p"},"Offset Sketches"),"."),Object(r.b)("p",null,"Below is the ",Object(r.b)("inlineCode",{parentName:"p"},"code")," sample for ",Object(r.b)("em",{parentName:"p"},"Offset Sketches"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Set Sketch Segment value and Create Line 1\n  Set swSketchSegment = swSketchManager.CreateLine(-0.5, 0.75, 0, -0.25, -0.5, 0)\n  \n  ' Set Sketch Segment value and Create Line 2\n  Set swSketchSegment = swSketchManager.CreateLine(-0.75, -1.25, 0, 0.5, -1.25, 0)\n  \n  ' De-select the lines after creation\n  swDoc.ClearSelection2 True\n  \n  ' Select Line 1\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line1\", \"SKETCHSEGMENT\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Select Line 2\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line2\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Offset selected Sketch Segments by \"SketchOffset2\" method from Solidworks sketch manager\n  BoolStatus = swSketchManager.SketchOffset2(0.5, False, False, swSkOffsetCapEndType_e.swSkOffsetNoCaps, swSkOffsetMakeConstructionType_e.swSkOffsetDontMakeConstruction, True)\n\n  ' De-select the Sketch Segment after Offset\n  swDoc.ClearSelection2 True\n  \n  ' Show Front View after Offset Sketch Segments\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n\nEnd Sub\n")),Object(r.b)("hr",null),Object(r.b)("h3",{id:"understanding-the-code"},"Understanding the Code"),Object(r.b)("p",null,"Now let us walk through ",Object(r.b)("strong",{parentName:"p"},"each line")," in the above code, and ",Object(r.b)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),Object(r.b)("p",null,"I also give some link so that you can go through them if there are anything I explained in previous posts."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n")),Object(r.b)("p",null,"This line forces us to define every variable we are going to use. "),Object(r.b)("p",null,"For more information please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),Object(r.b)("p",null,"In this line, we create a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),Object(r.b)("p",null,"In this line, we create a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Boolean Variable\nDim BoolStatus As Boolean\n")),Object(r.b)("p",null,"In this line, we create a variable named ",Object(r.b)("inlineCode",{parentName:"p"},"BoolStatus")," as ",Object(r.b)("inlineCode",{parentName:"p"},"Boolean")," object type."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),Object(r.b)("p",null,"In above line, we create variable ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchManager")," for ",Object(r.b)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(r.b)("p",null,"As the name suggested, a ",Object(r.b)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",Object(r.b)("em",{parentName:"p"},"Sketches"),"."),Object(r.b)("p",null,"To see methods and properties related to ",Object(r.b)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"}),"this page")),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n")),Object(r.b)("p",null,"In this line, we Create a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchSegment")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchSegment")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.SketchSegment"),"."),Object(r.b)("p",null,"We create variable ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchSegment")," for ",Object(r.b)("strong",{parentName:"p"},"Solidworks Sketch Segments"),"."),Object(r.b)("p",null,"To see methods and properties related to ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchSegment")," object, please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"}),"this page")),"."),Object(r.b)("p",null,"These all are our global variables."),Object(r.b)("p",null,"As you can see in code sample, they are ",Object(r.b)("strong",{parentName:"p"},"Solidworks API Objects"),"."),Object(r.b)("p",null,"So basically I group all the ",Object(r.b)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),Object(r.b)("p",null,"I have also place ",Object(r.b)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",Object(r.b)("em",{parentName:"p"},"need")," this variable frequently."),Object(r.b)("p",null,"Thus, I have started placing it here."),Object(r.b)("p",null,"Next is our ",Object(r.b)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",Object(r.b)("inlineCode",{parentName:"p"},"main"),". "),Object(r.b)("p",null,"This procedure hold all the ",Object(r.b)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),Object(r.b)("p",null,"In this line, we set the value of our Solidworks variable ",Object(r.b)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create string type variable for storing default part location\nDim defaultTemplate As String\n' Set value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),Object(r.b)("p",null,"In 1st statement of above example, we are defining a variable of ",Object(r.b)("inlineCode",{parentName:"p"},"string")," type and named it as ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),Object(r.b)("p",null,"This variable ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",Object(r.b)("strong",{parentName:"p"},"Default Part Template"),"."),Object(r.b)("p",null,"In 2nd line of above example. we assign value to our newly define ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),Object(r.b)("p",null,"We assign the value by using a ",Object(r.b)("em",{parentName:"p"},"Method")," named ",Object(r.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," method is a part of our main Solidworks variable ",Object(r.b)("inlineCode",{parentName:"p"},"swApp"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),Object(r.b)("p",null,"In this line, we set the value of our ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),Object(r.b)("p",null,"For ",Object(r.b)("strong",{parentName:"p"},"detailed information")," about these lines please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post."),Object(r.b)("p",null,"I have discussed them ",Object(r.b)("strong",{parentName:"p"},"thoroghly")," in ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post, so do checkout that post if you want to understand above code in more detail."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),Object(r.b)("p",null,"In above line, we select the ",Object(r.b)("em",{parentName:"p"},"front plane")," by using ",Object(r.b)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",Object(r.b)("inlineCode",{parentName:"p"},"Extension")," object."),Object(r.b)("p",null,"For more information about selection method please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-selection-methods"}),"Solidworks Macros - Selection Methods"))," post."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),Object(r.b)("p",null,"In above line, we set the ",Object(r.b)("em",{parentName:"p"},"Sketch manager")," variable to ",Object(r.b)("em",{parentName:"p"},"current document's sketch manager"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Insert a sketch into selected plane\nswSketchManager.InsertSketch True\n")),Object(r.b)("p",null,"In above line, we use ",Object(r.b)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",Object(r.b)("em",{parentName:"p"},"SketchManager")," and give ",Object(r.b)("inlineCode",{parentName:"p"},"True")," value."),Object(r.b)("p",null,"This method allows us to insert a sketch in selected plane."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Sketch Segment value and Create Line 1\nSet swSketchSegment = swSketchManager.CreateLine(-0.5, 0.75, 0, -0.25, -0.5, 0)\n")),Object(r.b)("p",null,"In above line, we set the value of Solidworks Sketch Segment variable ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchSegment")," by ",Object(r.b)("inlineCode",{parentName:"p"},"CreateLine")," method from ",Object(r.b)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"CreateLine")," method creates Lines between 2 given points."),Object(r.b)("p",null,"For more information about ",Object(r.b)("inlineCode",{parentName:"p"},"CreateLine")," method, you can read my ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-sketch-macro-create-line"}),"Solidworks Sketch Macros - Create Line"))," post."),Object(r.b)("p",null,"That post describe all the parameters we need for this ",Object(r.b)("inlineCode",{parentName:"p"},"CreateLine")," method in details."),Object(r.b)("p",null,"In above line, we create a Line between ",Object(r.b)("strong",{parentName:"p"},"point (-0.5, 0.75, 0)")," and ",Object(r.b)("strong",{parentName:"p"},"point (-0.25, -0.5, 0)"),"."),Object(r.b)("p",null,"This line is ",Object(r.b)("strong",{parentName:"p"},"not parallel")," to any axis."),Object(r.b)("p",null,"This line is at an angle to ",Object(r.b)("em",{parentName:"p"},"Vertical")," axis."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Sketch Segment value and Create Line 2\nSet swSketchSegment = swSketchManager.CreateLine(-0.75, -1.25, 0, 0.5, -1.25, 0)\n")),Object(r.b)("p",null,"In above line we create Line 2 by using same ",Object(r.b)("inlineCode",{parentName:"p"},"CreateLine")," method from ",Object(r.b)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(r.b)("p",null,"In above code, we create our 2nd line between ",Object(r.b)("strong",{parentName:"p"},"point (-0.75, -1.25, 0)")," and ",Object(r.b)("strong",{parentName:"p"},"point (0.5, -1.25, 0)"),"."),Object(r.b)("p",null,"This line is ",Object(r.b)("strong",{parentName:"p"},"parallel")," to X-axis."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' De-select the lines after creation\nswDoc.ClearSelection2 True\n")),Object(r.b)("p",null,"After creating both lines we de-select those lines."),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"We ",Object(r.b)("strong",{parentName:"p"},"don't need")," to de-select the lines for ",Object(r.b)("strong",{parentName:"p"},"Offset operation")," as we will select those lines agains in next 2 lines. I just want to show you how to select a ",Object(r.b)("strong",{parentName:"p"},"Sketch Segment")," with ",Object(r.b)("inlineCode",{parentName:"p"},"SelectById")," Menthod in next line of code."))),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Select Line 1\nBoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),Object(r.b)("p",null,"In above line of code, we select ",Object(r.b)("strong",{parentName:"p"},"Line 1"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Select Line 2\nBoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),Object(r.b)("p",null,"In above line of code, we select ",Object(r.b)("strong",{parentName:"p"},"Line 2")," and add Line 2 to selection list."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Offset selected Sketch Segments by "SketchOffset2" method from Solidworks sketch manager\nBoolStatus = swSketchManager.SketchOffset2(0.5, False, False, swSkOffsetCapEndType_e.swSkOffsetNoCaps, swSkOffsetMakeConstructionType_e.swSkOffsetDontMakeConstruction, True)\n')),Object(r.b)("p",null,"In above line, we ",Object(r.b)("strong",{parentName:"p"},"Offset")," selected ",Object(r.b)("em",{parentName:"p"},"Lines")," by ",Object(r.b)("inlineCode",{parentName:"p"},"SketchOffset2")," method from ",Object(r.b)("em",{parentName:"p"},"Solidworks sketch manager"),"."),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"SketchOffset2")," method takes following parameters as explained:"),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Offset")," : ",Object(r.b)("em",{parentName:"p"},"Offset value; negative value offsets the sketch entities in the opposite direction")),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"BothDirections")," : ",Object(r.b)("em",{parentName:"p"},"True to offset the sketch entities in both directions, false to offset the sketch entities in one direction")),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Chain")," : ",Object(r.b)("em",{parentName:"p"},"True to offset the chain of sketch entities, false to offset only the selected sketch entities")),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"CapEnds")," : ",Object(r.b)("em",{parentName:"p"},"Cap the ends as defined by ",Object(r.b)("inlineCode",{parentName:"em"},"swSkOffsetCapEndType_e"))),Object(r.b)("p",null,"  ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetCapEndType_e")," enum defines following different ",Object(r.b)("strong",{parentName:"p"},"End cap types")," ",Object(r.b)("a",Object(a.a)({parentName:"p"},{href:"../vba/vba-constants"}),"constants"),":"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetArcCaps"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetLineCaps"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetNoCaps")))),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"MakeConstruction")," : ",Object(r.b)("em",{parentName:"p"},"Convert original and offset sketch entities to construction sketch entities as defined by ",Object(r.b)("inlineCode",{parentName:"em"},"swSkOffsetMakeConstructionType_e"))),Object(r.b)("p",null,"  ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetMakeConstructionType_e")," enum defines following different ",Object(r.b)("strong",{parentName:"p"},"Construction Types")," ",Object(r.b)("a",Object(a.a)({parentName:"p"},{href:"../vba/vba-constants"}),"constants"),":"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetDontMakeConstruction"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetMakeBothConstruction"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetMakeOffsConstruction"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetMakeOrigConstruction")))),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"AddDimensions")," : ",Object(r.b)("strong",{parentName:"p"},"True")," to add the dimension to the offset, false if not want to add the dimension to the offset."),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Return Value"),":"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"True"),": If Extend operation is ",Object(r.b)("em",{parentName:"p"},"Success"),".")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"False"),": If Extend operation is ",Object(r.b)("em",{parentName:"p"},"Fail"),"."))),Object(r.b)("p",null,"In our code, I have used following values:"),Object(r.b)("p",null,"  ",Object(r.b)("strong",{parentName:"p"},"Offset")," : I have used 0.5 value for ",Object(r.b)("em",{parentName:"p"},"Offset"),"."),Object(r.b)("p",null,"  ",Object(r.b)("strong",{parentName:"p"},"BothDirections")," : I have used ",Object(r.b)("inlineCode",{parentName:"p"},"False")," value for ",Object(r.b)("em",{parentName:"p"},"BothDirections"),"."),Object(r.b)("p",null,"  ",Object(r.b)("strong",{parentName:"p"},"Chain")," : I have used ",Object(r.b)("inlineCode",{parentName:"p"},"False")," value for ",Object(r.b)("em",{parentName:"p"},"Chain"),"."),Object(r.b)("p",null,"  ",Object(r.b)("strong",{parentName:"p"},"CapEnds")," : I have used ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetCapEndType_e.swSkOffsetNoCaps")," value for ",Object(r.b)("em",{parentName:"p"},"CapEnds"),"."),Object(r.b)("p",null,"  ",Object(r.b)("strong",{parentName:"p"},"MakeConstruction")," : I have used ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetMakeConstructionType_e.swSkOffsetDontMakeConstruction")," value for ",Object(r.b)("em",{parentName:"p"},"MakeConstruction"),"."),Object(r.b)("p",null,"  ",Object(r.b)("strong",{parentName:"p"},"AddDimensions")," : I have used ",Object(r.b)("inlineCode",{parentName:"p"},"True")," value for ",Object(r.b)("em",{parentName:"p"},"AddDimensions"),"."),Object(r.b)("p",null,"Below image shows before and after Offset operation on the sketch."),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Before Offset Operation")),Object(r.b)("p",null,Object(r.b)("img",{alt:"before-offset",src:n(349).default})),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"After Offset Operation")),Object(r.b)("p",null,Object(r.b)("img",{alt:"after-offset",src:n(350).default})),Object(r.b)("p",null,"Now let us modify some values and look for the changes:"),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"BothDirections")," : Let us change the value to ",Object(r.b)("inlineCode",{parentName:"p"},"True")," value for ",Object(r.b)("em",{parentName:"p"},"BothDirections")," and see the result:"),Object(r.b)("p",null,Object(r.b)("img",{alt:"offset-both-side",src:n(351).default})),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"CapEnds")," : Now we change the value of ",Object(r.b)("em",{parentName:"p"},"End cap"),". "),Object(r.b)("p",null,"Please see below for both ",Object(r.b)("strong",{parentName:"p"},"Line")," and ",Object(r.b)("strong",{parentName:"p"},"Arc")," option for ",Object(r.b)("em",{parentName:"p"},"End cap"),":"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},"If we change ",Object(r.b)("strong",{parentName:"p"},"CapEnds")," value to ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetLineCaps")," and then the result would be:"),Object(r.b)("p",{parentName:"li"},Object(r.b)("img",{alt:"end-cap-is-line-type",src:n(352).default}))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},"If we change ",Object(r.b)("strong",{parentName:"p"},"CapEnds")," value to ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetArcCaps")," and then the result would be:"),Object(r.b)("p",{parentName:"li"},Object(r.b)("img",{alt:"end-cap-is-arc-type",src:n(353).default})))),Object(r.b)("p",null,"These 2 covers all option available in ",Object(r.b)("strong",{parentName:"p"},"Cap End"),"."),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"MakeConstruction")," : Now we change the value of MakeConstruction. "),Object(r.b)("p",null,"Please see below for ",Object(r.b)("strong",{parentName:"p"},"all")," ",Object(r.b)("em",{parentName:"p"},"MakeConstruction")," options:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},"If we change ",Object(r.b)("strong",{parentName:"p"},"MakeConstruction")," value to ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetMakeOrigConstruction")," and then the result would be:"),Object(r.b)("p",{parentName:"li"},Object(r.b)("img",{alt:"make-original-entities-construction",src:n(354).default}))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},"If we change ",Object(r.b)("strong",{parentName:"p"},"MakeConstruction")," value to ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetMakeOffsConstruction")," and then the result would be:"),Object(r.b)("p",{parentName:"li"},Object(r.b)("img",{alt:"make-offset-entities-construction",src:n(355).default}))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},"If we change ",Object(r.b)("strong",{parentName:"p"},"MakeConstruction")," value to ",Object(r.b)("inlineCode",{parentName:"p"},"swSkOffsetMakeBothConstruction")," and then the result would be:"),Object(r.b)("p",{parentName:"li"},Object(r.b)("img",{alt:"original-and-offset-entities-are-construction",src:n(356).default})))),Object(r.b)("p",null,"This covers all options in ",Object(r.b)("inlineCode",{parentName:"p"},"SketchOffset2")," method."),Object(r.b)("hr",null),Object(r.b)("h3",{id:"note"},"NOTE"),Object(r.b)("p",null,"It is ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",Object(r.b)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Meter only")),"."),Object(r.b)("p",null,"Solidworks API does not care about your application's Unit systems."),Object(r.b)("p",null,"For example, I works in ",Object(r.b)("strong",{parentName:"p"},"ANSI")," system means inches for distance. But when I used ",Object(r.b)("strong",{parentName:"p"},"Solidworks API")," through ",Object(r.b)("em",{parentName:"p"},"VBA macros or C#"),", I need to use converted numeric values."),Object(r.b)("p",null,"Because Solidworks API output the distance in ",Object(r.b)("strong",{parentName:"p"},"Meter")," which is not my requirement."),Object(r.b)("hr",null),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' De-select the Sketch after creation\nswDoc.ClearSelection2 True\n")),Object(r.b)("p",null,"In the above line of code, we deselect the ",Object(r.b)("strong",{parentName:"p"},"Sketch")," after the ",Object(r.b)("em",{parentName:"p"},"Offset")," operation."),Object(r.b)("p",null,"For de-selecting, we use ",Object(r.b)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Show Front View after Sketch Offset\nswDoc.ShowNamedView2 "", swStandardViews_e.swFrontView\n')),Object(r.b)("p",null,"In the above line of code, we update the ",Object(r.b)("em",{parentName:"p"},"view orientation")," to ",Object(r.b)("strong",{parentName:"p"},"Front View"),"."),Object(r.b)("p",null,"In my machine, after inserting a sketch view orientation does not changed."),Object(r.b)("p",null,"Because of this I have to update the view to ",Object(r.b)("strong",{parentName:"p"},"Front view"),"."),Object(r.b)("p",null,"For showing ",Object(r.b)("strong",{parentName:"p"},"Front View")," we used ",Object(r.b)("inlineCode",{parentName:"p"},"ShowNamedView2")," method from our Solidworks document name ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(r.b)("p",null,"This method takes 2 parameter described as follows:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"VName")," : Name of the view to display or an empty string to use ViewId instead")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"ViewId")," : ID of the view to display as defined by ",Object(r.b)("inlineCode",{parentName:"p"},"swStandardViews_e")," or -1 to use the ",Object(r.b)("strong",{parentName:"p"},"VName")," argument instead."))),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"If you specify both ",Object(r.b)("strong",{parentName:"p"},"VName")," and ",Object(r.b)("strong",{parentName:"p"},"ViewId"),", then ",Object(r.b)("strong",{parentName:"p"},"ViewId")," takes precedence if the two arguments do not resolve to the same view."))),Object(r.b)("p",null,Object(r.b)("inlineCode",{parentName:"p"},"swStandardViews_e")," has following Standard View Types:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swBackView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swBottomView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swDimetricView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swFrontView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swIsometricView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swLeftView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swRightView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swTopView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swExtendetricView")))),Object(r.b)("p",null,"In our code, we did not use ",Object(r.b)("strong",{parentName:"p"},"VName")," instead I used ",Object(r.b)("em",{parentName:"p"},"empty string")," in form of ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},'""'))," symbol."),Object(r.b)("p",null,"I used ",Object(r.b)("strong",{parentName:"p"},"ViewId")," value to specify view and used ",Object(r.b)("inlineCode",{parentName:"p"},"swStandardViews_e.swFrontView")," value to use ",Object(r.b)("em",{parentName:"p"},"Standard Front View"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),Object(r.b)("p",null,"In this last line we use ",Object(r.b)("em",{parentName:"p"},"zoom to fit")," command."),Object(r.b)("p",null,"For Zoom to fit, we use ",Object(r.b)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(r.b)("p",null,"This is it !!!"),Object(r.b)("p",null,"If you found anything to add or update, please let me know on my e-mail."),Object(r.b)("hr",null),Object(r.b)("h2",{id:"vba-language-feature-used-in-this-post"},"VBA Language feature used in this post"),Object(r.b)("p",null,"In this post used some features of ",Object(r.b)("strong",{parentName:"p"},"VBA programming language"),"."),Object(r.b)("p",null,"This section of post, has some brief information about the VBA programming language specific features."),Object(r.b)("ol",null,Object(r.b)("li",{parentName:"ol"},"We use ",Object(r.b)("strong",{parentName:"li"},"Option Explicit")," for capturing un-declared variables.")),Object(r.b)("p",null,"If you want to read more about ",Object(r.b)("strong",{parentName:"p"},"Option Explicit")," then please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-variables-decl"}),"Declaring and Scoping of Variables")),"."),Object(r.b)("ol",{start:2},Object(r.b)("li",{parentName:"ol"},"Then we create ",Object(r.b)("strong",{parentName:"li"},"variable")," for different data types.")),Object(r.b)("p",null,"If you know in detail about the ",Object(r.b)("strong",{parentName:"p"},"Variables"),", then please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-variables"}),"Variables"))," and ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-prog-concept#data-types-in-vba"}),"Data-types"))," posts of this blog."),Object(r.b)("p",null,"It will help you to understand what ",Object(r.b)("strong",{parentName:"p"},"Variables")," are and how to use them."),Object(r.b)("ol",{start:3},Object(r.b)("li",{parentName:"ol"},"Then we create ",Object(r.b)("strong",{parentName:"li"},"main Sub procedure")," for our macro.")),Object(r.b)("p",null,"If you know in detail about the ",Object(r.b)("strong",{parentName:"p"},"Sub procedure"),", then I suggest you to visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-procedures"}),"VBA Sub and Function Procedures"))," and ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-procedures-exec"}),"Executing Sub and Function Procedures"))," posts of this blog."),Object(r.b)("p",null,"It will help you to understand what ",Object(r.b)("strong",{parentName:"p"},"Procedures")," are and how to use them."),Object(r.b)("ol",{start:4},Object(r.b)("li",{parentName:"ol"},"In most part we create some variables and set their values. We set those values by using some ",Object(r.b)("strong",{parentName:"li"},"functions")," provided from objects.")),Object(r.b)("p",null,"If you don't know about the ",Object(r.b)("strong",{parentName:"p"},"functions"),", then you should visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-functions"}),"VBA Functions"))," and ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"../vba/vba-functions-adv"}),"VBA Functions that do more"))," posts of this blog."),Object(r.b)("p",null,"It will help you to understand what ",Object(r.b)("strong",{parentName:"p"},"functions")," are and how to use them."),Object(r.b)("hr",null),Object(r.b)("h2",{id:"solidworks-api-objects"},"Solidworks API Objects"),Object(r.b)("p",null,"In this post of ",Object(r.b)("strong",{parentName:"p"},"Sketch Offset"),", we use ",Object(r.b)("em",{parentName:"p"},"Solidworks API objects and their methods"),"."),Object(r.b)("p",null,"This section contains the list of all ",Object(r.b)("strong",{parentName:"p"},"Solidworks Objects")," used in this post."),Object(r.b)("p",null,"I have also attached links of these ",Object(r.b)("strong",{parentName:"p"},"Solidworks API Objects")," in ",Object(r.b)("strong",{parentName:"p"},"API Help website"),"."),Object(r.b)("p",null,"If you want to explore those objects, you can use these links."),Object(r.b)("p",null,"These Solidworks API Objects are listed below:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Solidworks Application Object")),Object(r.b)("p",{parentName:"li"},"If you want explore ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(r.b)("strong",{parentName:"p"},"Solidworks Application Object")," object you can visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html"}),"this link")),".")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Solidworks Document Object")),Object(r.b)("p",{parentName:"li"},"If you want explore ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(r.b)("strong",{parentName:"p"},"Solidworks Document Object")," object you can visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html"}),"this link")),".")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")),Object(r.b)("p",{parentName:"li"},"If you want explore ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(r.b)("strong",{parentName:"p"},"Solidworks Sketch Manager Object")," you can visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"}),"this link")),".")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")),Object(r.b)("p",{parentName:"li"},"If you want explore ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Properties and Methods/Functions"))," of ",Object(r.b)("strong",{parentName:"p"},"Solidworks Sketch Segment Object")," you can visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"}),"this link")),"."))),Object(r.b)("hr",null),Object(r.b)("p",null,"Hope this post helps you to ",Object(r.b)("em",{parentName:"p"},"Offset")," Sketch Entities with Solidworks VBA Macros."),Object(r.b)("p",null,"For more such tutorials on ",Object(r.b)("strong",{parentName:"p"},"Solidworks VBA Macros"),", do come to this blog after sometime."),Object(r.b)("p",null,"Till then, Happy learning!!!"))}l.isMDXComponent=!0},152:function(e,t,n){"use strict";n.d(t,"a",(function(){return p})),n.d(t,"b",(function(){return d}));var a=n(0),o=n.n(a);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function b(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function s(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?b(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):b(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function c(e,t){if(null==e)return{};var n,a,o=function(e,t){if(null==e)return{};var n,a,o={},r=Object.keys(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var i=o.a.createContext({}),l=function(e){var t=o.a.useContext(i),n=t;return e&&(n="function"==typeof e?e(t):s(s({},t),e)),n},p=function(e){var t=l(e.components);return o.a.createElement(i.Provider,{value:t},e.children)},m={inlineCode:"code",wrapper:function(e){var t=e.children;return o.a.createElement(o.a.Fragment,{},t)}},O=o.a.forwardRef((function(e,t){var n=e.components,a=e.mdxType,r=e.originalType,b=e.parentName,i=c(e,["components","mdxType","originalType","parentName"]),p=l(n),O=a,d=p["".concat(b,".").concat(O)]||p[O]||m[O]||r;return n?o.a.createElement(d,s(s({ref:t},i),{},{components:n})):o.a.createElement(d,s({ref:t},i))}));function d(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var r=n.length,b=new Array(r);b[0]=O;var s={};for(var c in t)hasOwnProperty.call(t,c)&&(s[c]=t[c]);s.originalType=e,s.mdxType="string"==typeof e?e:a,b[1]=s;for(var i=2;i<r;i++)b[i]=n[i];return o.a.createElement.apply(null,b)}return o.a.createElement.apply(null,n)}O.displayName="MDXCreateElement"},349:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/before-offset-c65b523dd78c4a250e41dc5bcb9b0e9e.png"},350:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/after-offset-392f651605c44d4ec4ac2bba92788093.png"},351:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/offset-both-side-840d616de53bb83ed91a9f5b4a23d733.png"},352:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/end-cap-is-line-type-8b4bd91a8dd6de3f12b7024b9759e580.png"},353:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/end-cap-is-arc-type-e712b668ea84378a0a5c43e25d3ebf14.png"},354:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/make-original-entities-construction-0dd5c4a8dbcbadee7fee2d1fe25180cb.png"},355:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/make-offset-entities-construction-30d5884f1d34f5f43bc78bab230a2a89.png"},356:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/original-and-offset-entities-are-construction-fab470d31b0abe5fc14bfbdbd24a630e.png"}}]);