(window.webpackJsonp=window.webpackJsonp||[]).push([[89],{147:function(e,t,n){"use strict";n.r(t),n.d(t,"frontMatter",(function(){return c})),n.d(t,"metadata",(function(){return i})),n.d(t,"rightToc",(function(){return b})),n.d(t,"default",(function(){return s}));var a=n(2),o=n(6),r=(n(0),n(152)),c={id:"sw-sketch-macro-convert-to-construction-sketch",title:"Convert to Construction Sketch"},i={unversionedId:"solidworks-macros/sw-sketch-macro-convert-to-construction-sketch",id:"solidworks-macros/sw-sketch-macro-convert-to-construction-sketch",isDocsHomePage:!1,title:"Convert to Construction Sketch",description:"In this post, I tell you about Convert to Construction Sketch From VBA Macro in a Sketch.",source:"@site/docs\\solidworks-macros\\2020-09-10-convert-to-construction-sketch-segment.md",slug:"/solidworks-macros/sw-sketch-macro-convert-to-construction-sketch",permalink:"/docs/solidworks-macros/sw-sketch-macro-convert-to-construction-sketch",version:"current",sidebar:"swvba",previous:{title:"Add Sketch Relations (Constraints)",permalink:"/docs/solidworks-macros/sw-sketch-macro-add-sketch-relation"},next:{title:"Split Open/Closed Sketch Entities",permalink:"/docs/solidworks-macros/sw-sketch-macro-split-sketch-entities"}},b=[{value:"Code Sample",id:"code-sample",children:[]},{value:"Understanding the Code",id:"understanding-the-code",children:[]}],l={rightToc:b};function s(e){var t=e.components,c=Object(o.a)(e,["components"]);return Object(r.b)("wrapper",Object(a.a)({},l,c,{components:t,mdxType:"MDXLayout"}),Object(r.b)("p",null,"In this post, I tell you about ",Object(r.b)("strong",{parentName:"p"},"Convert to Construction Sketch From VBA Macro")," in a Sketch."),Object(r.b)("p",null,"In this post, I explain about ",Object(r.b)("inlineCode",{parentName:"p"},"CreateConstructionGeometry")," method from ",Object(r.b)("strong",{parentName:"p"},"Solidworks"),"'s ",Object(r.b)("inlineCode",{parentName:"p"},"SketchManager")," object."),Object(r.b)("p",null,"This method is ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"most updated"))," method, I found in ",Object(r.b)("em",{parentName:"p"},"Solidworks API Help"),"."),Object(r.b)("p",null,"This post will utilize the methods explained in earlier posts, hence knowledge to those is required but it is not mandatory."),Object(r.b)("p",null,"An absolute beginner can follow what is written here."),Object(r.b)("hr",null),Object(r.b)("h2",{id:"code-sample"},"Code Sample"),Object(r.b)("p",null,"Below is the ",Object(r.b)("inlineCode",{parentName:"p"},"code")," sample to ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Convert Sketch Segment to Construction Sketch")),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Set Solidworks document to active part document\n  Set swDoc = swApp.ActiveDoc\n  \n  ' Select Circle\n  BoolStatus = swDoc.Extension.SelectByID2(\"Arc1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Convert to construction circle\n  swDoc.SketchManager.CreateConstructionGeometry\n  \n  ' De-select the Sketch Segment after Convert to construction\n  swDoc.ClearSelection2 True\n\n  ' Show Front View\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n\nEnd Sub\n")),Object(r.b)("hr",null),Object(r.b)("h2",{id:"understanding-the-code"},"Understanding the Code"),Object(r.b)("p",null,"Now let us walk through ",Object(r.b)("strong",{parentName:"p"},"each line")," in the above code, and ",Object(r.b)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),Object(r.b)("p",null,"I also give some link so that you can go through them if there are anything I explained in previous posts."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n")),Object(r.b)("p",null,"This line forces us to define every variable we are going to use. "),Object(r.b)("p",null,"For more information please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),Object(r.b)("p",null,"In this line, we create a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),Object(r.b)("p",null,"In this line, we create a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Boolean Variable\nDim BoolStatus As Boolean\n")),Object(r.b)("p",null,"In this line, we create a variable named ",Object(r.b)("inlineCode",{parentName:"p"},"BoolStatus")," as ",Object(r.b)("inlineCode",{parentName:"p"},"Boolean")," object type."),Object(r.b)("p",null,"These all are our global variables."),Object(r.b)("p",null,"As you can see in code sample, they are ",Object(r.b)("strong",{parentName:"p"},"Solidworks API Objects"),"."),Object(r.b)("p",null,"So basically I group all the ",Object(r.b)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),Object(r.b)("p",null,"I have also place ",Object(r.b)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",Object(r.b)("em",{parentName:"p"},"need")," this variable frequently."),Object(r.b)("p",null,"Thus, I have started placing it here."),Object(r.b)("p",null,"Next is our ",Object(r.b)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",Object(r.b)("inlineCode",{parentName:"p"},"main"),". "),Object(r.b)("p",null,"This procedure hold all the ",Object(r.b)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),Object(r.b)("p",null,"In this line, we set the value of our Solidworks variable ",Object(r.b)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Solidworks document to active part document\nSet swDoc = swApp.ActiveDoc\n")),Object(r.b)("p",null,"In this line, we set the value of our Solidworks variable ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," to currently opened part document as shown below in our post."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Select Circle we want to Pattern\nBoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),Object(r.b)("p",null,"In above line of code, we select the Circle i.e. ",Object(r.b)("strong",{parentName:"p"},"Arc 1")," and add it to selection list."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Convert to construction circle\nswDoc.SketchManager.CreateConstructionGeometry\n")),Object(r.b)("p",null,"In above line, we convert the selected Solidworks Sketch Segment i.e. our circle ",Object(r.b)("inlineCode",{parentName:"p"},"CreateConstructionGeometry")," method from ",Object(r.b)("em",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"Here we did not create another variable for Sketch Manger like I have done previously."))),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"CreateConstructionGeometry")," method takes ",Object(r.b)("strong",{parentName:"p"},"NO")," parameter and ",Object(r.b)("strong",{parentName:"p"},"did not")," return any value."),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Before ",Object(r.b)("em",{parentName:"strong"},"Convert")," Circle")),Object(r.b)("p",null,Object(r.b)("img",{alt:"before-construction-sketch-segment",src:n(357).default})),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"After ",Object(r.b)("em",{parentName:"strong"},"Convert")," Circle")),Object(r.b)("p",null,Object(r.b)("img",{alt:"after-construction-sketch-segment",src:n(358).default})),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' De-select the Sketch after creation\nswDoc.ClearSelection2 True\n")),Object(r.b)("p",null,"In the above line of code, we deselect the ",Object(r.b)("strong",{parentName:"p"},"Sketch")," after the ",Object(r.b)("em",{parentName:"p"},"Circular Sketch Pattern")," operation."),Object(r.b)("p",null,"For de-selecting, we use ",Object(r.b)("inlineCode",{parentName:"p"},"ClearSelection2")," method from our Solidworks document name ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Show Front View\nswDoc.ShowNamedView2 "", swStandardViews_e.swFrontView\n')),Object(r.b)("p",null,"In the above line of code, we update the ",Object(r.b)("em",{parentName:"p"},"view orientation")," to ",Object(r.b)("strong",{parentName:"p"},"Front View"),"."),Object(r.b)("p",null,"In my machine, after inserting a sketch view orientation does not changed."),Object(r.b)("p",null,"Because of this I have to update the view to ",Object(r.b)("strong",{parentName:"p"},"Front view"),"."),Object(r.b)("p",null,"For showing ",Object(r.b)("strong",{parentName:"p"},"Front View")," we used ",Object(r.b)("inlineCode",{parentName:"p"},"ShowNamedView2")," method from our Solidworks document name ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(r.b)("p",null,"This method takes 2 parameter described as follows:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"VName")," : Name of the view to display or an empty string to use ViewId instead")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"ViewId")," : ID of the view to display as defined by ",Object(r.b)("inlineCode",{parentName:"p"},"swStandardViews_e")," or -1 to use the ",Object(r.b)("strong",{parentName:"p"},"VName")," argument instead."))),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"If you specify both ",Object(r.b)("strong",{parentName:"p"},"VName")," and ",Object(r.b)("strong",{parentName:"p"},"ViewId"),", then ",Object(r.b)("strong",{parentName:"p"},"ViewId")," takes precedence if the two arguments do not resolve to the same view."))),Object(r.b)("p",null,Object(r.b)("inlineCode",{parentName:"p"},"swStandardViews_e")," has following Standard View Types:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swBackView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swBottomView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swDimetricView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swFrontView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swIsometricView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swLeftView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swRightView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swTopView"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"swExtendetricView")))),Object(r.b)("p",null,"In our code, we did not use ",Object(r.b)("strong",{parentName:"p"},"VName")," instead I used ",Object(r.b)("em",{parentName:"p"},"empty string")," in form of ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},'""'))," symbol."),Object(r.b)("p",null,"I used ",Object(r.b)("strong",{parentName:"p"},"ViewId")," value to specify view and used ",Object(r.b)("inlineCode",{parentName:"p"},"swStandardViews_e.swFrontView")," value to use ",Object(r.b)("em",{parentName:"p"},"Standard Front View"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Zoom to fit screen in Solidworks Window\nswDoc.ViewZoomtofit\n")),Object(r.b)("p",null,"In this last line we use ",Object(r.b)("em",{parentName:"p"},"zoom to fit")," command."),Object(r.b)("p",null,"For Zoom to fit, we use ",Object(r.b)("inlineCode",{parentName:"p"},"ViewZoomtofit")," method from our Solidworks document variable ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc"),"."),Object(r.b)("hr",null),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"This is it !!!")),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"I hope my efforts will helpful to someone!")),Object(r.b)("p",null,"If you found anything to ",Object(r.b)("strong",{parentName:"p"},"add or update"),", please let me know on my ",Object(r.b)("em",{parentName:"p"},"e-mail"),"."),Object(r.b)("p",null,"Hope this post helps you to ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Convert to Construction Sketch"))," with Solidworks VBA Macros."),Object(r.b)("p",null,"For more such tutorials on ",Object(r.b)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"Do let me know by you like this post or not!")),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"Till then, Happy learning!!!")))}s.isMDXComponent=!0},152:function(e,t,n){"use strict";n.d(t,"a",(function(){return p})),n.d(t,"b",(function(){return u}));var a=n(0),o=n.n(a);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function c(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function i(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?c(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):c(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function b(e,t){if(null==e)return{};var n,a,o=function(e,t){if(null==e)return{};var n,a,o={},r=Object.keys(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var l=o.a.createContext({}),s=function(e){var t=o.a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):i(i({},t),e)),n},p=function(e){var t=s(e.components);return o.a.createElement(l.Provider,{value:t},e.children)},m={inlineCode:"code",wrapper:function(e){var t=e.children;return o.a.createElement(o.a.Fragment,{},t)}},d=o.a.forwardRef((function(e,t){var n=e.components,a=e.mdxType,r=e.originalType,c=e.parentName,l=b(e,["components","mdxType","originalType","parentName"]),p=s(n),d=a,u=p["".concat(c,".").concat(d)]||p[d]||m[d]||r;return n?o.a.createElement(u,i(i({ref:t},l),{},{components:n})):o.a.createElement(u,i({ref:t},l))}));function u(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var r=n.length,c=new Array(r);c[0]=d;var i={};for(var b in t)hasOwnProperty.call(t,b)&&(i[b]=t[b]);i.originalType=e,i.mdxType="string"==typeof e?e:a,c[1]=i;for(var l=2;l<r;l++)c[l]=n[l];return o.a.createElement.apply(null,c)}return o.a.createElement.apply(null,n)}d.displayName="MDXCreateElement"},357:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/before-construction-sketch-segment-67918854b753621676e94fc37660e659.png"},358:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/after-construction-sketch-segment-ae59e189ef53404c94bd8e0a6fcb8632.png"}}]);