<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="generator" content="Docusaurus v2.0.0-alpha.66">
<link rel="preconnect" href="https://www.google-analytics.com">
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-117501871-2","auto"),ga("set","anonymizeIp",!0),ga("send","pageview")</script>
<script async src="https://www.google-analytics.com/analytics.js"></script><title data-react-helmet="true">Create 3-Point Arc | The Cad Coder</title><meta data-react-helmet="true" name="twitter:card" content="summary_large_image"><meta data-react-helmet="true" name="docusaurus_language" content="en"><meta data-react-helmet="true" name="docusaurus_version" content="current"><meta data-react-helmet="true" name="docusaurus_tag" content="docs-default-current"><meta data-react-helmet="true" property="og:title" content="Create 3-Point Arc | The Cad Coder"><meta data-react-helmet="true" name="description" content="In this post, I tell you about how to create a 3-Point Arc through Solidworks VBA Macros in a sketch."><meta data-react-helmet="true" property="og:description" content="In this post, I tell you about how to create a 3-Point Arc through Solidworks VBA Macros in a sketch."><meta data-react-helmet="true" property="og:url" content="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-create-3point-arc"><link data-react-helmet="true" rel="shortcut icon" href="/img/logo.png"><link data-react-helmet="true" rel="canonical" href="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-create-3point-arc"><link rel="stylesheet" href="/styles.f7ef45b3.css">
<link rel="preload" href="/styles.e684f388.js" as="script">
<link rel="preload" href="/runtime~main.bcdc0003.js" as="script">
<link rel="preload" href="/main.2d365058.js" as="script">
<link rel="preload" href="/1.1af7f77d.js" as="script">
<link rel="preload" href="/2.4f0019c3.js" as="script">
<link rel="preload" href="/94.4b40930d.js" as="script">
<link rel="preload" href="/95.2f44d2c3.js" as="script">
<link rel="preload" href="/f976f453.e3619938.js" as="script">
<link rel="preload" href="/17896441.361bff39.js" as="script">
<link rel="preload" href="/9d64bfcd.b8928d4d.js" as="script">
</head>
<body>
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><div aria-label="Navigation bar toggle" class="navbar__toggle" role="button" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></div><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a><div class="navbar__item dropdown dropdown--hoverable dropdown--left"><a class="navbar__item navbar__link">VBA</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li><a class="dropdown__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></div><a class="navbar__item navbar__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a><a class="navbar__item navbar__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></div><div class="navbar__items navbar__items--right"><div class="navbar__item dropdown dropdown--hoverable dropdown--right"><a class="navbar__item navbar__link">About</a><ul class="dropdown__menu"><li><a class="dropdown__link" position="right" href="/docs/about">About Me</a></li><li><a class="dropdown__link" position="right" href="/docs/resources">Resources</a></li><li><a class="dropdown__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></div><div class="react-toggle react-toggle--disabled displayOnlyInLargeViewport_2aTZ"><div class="react-toggle-track"><div class="react-toggle-track-check"><span class="toggle_BsTx">ðŸŒœ</span></div><div class="react-toggle-track-x"><span class="toggle_BsTx">ðŸŒž</span></div></div><div class="react-toggle-thumb"></div><input type="checkbox" disabled="" aria-label="Dark mode toggle" class="react-toggle-screenreader-only"></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div><div class="navbar-sidebar"><div class="navbar-sidebar__brand"><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a></div><div class="navbar-sidebar__items"><div class="menu"><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">VBA</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></li><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">About</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/about">About Me</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/resources">Resources</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></li></ul></div></div></div></nav><div class="main-wrapper"><div class="docPage_2gpo"><div class="docSidebarContainer_3_JD" role="complementary"><div class="sidebar_2urC"><div class="menu menu--responsive menu_5FrY"><button aria-label="Open Menu" aria-haspopup="true" class="button button--secondary button--sm menu__button" type="button"><svg aria-label="Menu" class="sidebarMenuIcon_Dm3K" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 32 32" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">General Functions</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba-in-sw">VBA in Solidworks</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-part">Open new Part document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-asm-and-dwg">Open Assembly and Drawing document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-selection-methods">Selection Methods</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-saved-documents">Open Saved Documents</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue">Fix Unit Issue</a></li></ul></li><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!">Sketch</a><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Lines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-line">Create Line</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerline">Create CenterLine</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Rectangles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-corner-rec">Create Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-center-rec">Create Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-corner-rec">Create 3-Point Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-center-rec">Create 3-Point Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-parallelogram">Create A Parallelogram</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Circles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle">Create Circle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle-by-radius">Create Circle By Radius</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-perimeter-circle">Create Perimeter Circle</a></li></ul></li><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!" tabindex="0">Arcs</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc">Create Centerpoint Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-create-tangent-arc">Create Tangent Arc</a></li><li class="menu__list-item"><a aria-current="page" class="menu__link menu__link--active active" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc">Create 3-Point Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-create-polygon">Create Polygon</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Slots</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-straight-slot">Create a Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-straight-slot">Create a Centerpoint Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc-slot">Create a 3-Point Arc Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc-slot">Create a Centerpoint Arc Slot</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Splines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-point">Create a Point</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-spline">Create a Spline</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Fillet &amp; Chamfer</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-fillet">Create a Fillet</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-chamfer">Create a Chamfer</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Trim and Extend</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-trim-entities">Trim Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-extend-entities">Extend Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Offset and Mirror</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-offset-entities">Offset Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-mirror-sketch-entities">Mirror Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Patterns</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-linear-sketch-patterm">Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm">Edit Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm">Circular Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern">Edit Circular Sketch Pattern</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Transformation</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities">Move/Copy Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities">Rotate/Copy Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Relations</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-toggle-sketch-relation">Toggle (Hide/Show) Sketch Relations</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-sketch-relation">Add Sketch Relations (Constraints)</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Others</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-convert-to-construction-sketch">Convert to Construction Sketch</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-split-sketch-entities">Split Open/Closed Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Dimensioning</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-dimension-sketch-entities">Add dimension to Sketch Entities</a></li></ul></li></ul></li></ul></div></div></div><main class="docMainContainer_3EyW"><div class="container padding-vert--lg docItemWrapper_1EkI"><div class="row"><div class="col docItemCol_2ASc"><div class="docItemContainer_3QWW"><article><header><h1 class="docTitle_1Lrw">Create 3-Point Arc</h1></header><div class="markdown"><p>In this post, I tell you about <em>how to create a 3-Point Arc through Solidworks VBA Macros</em> in a sketch.</p><p>The process is almost identical with previous <strong><a href="/docs/solidworks-macros/sw-sketch-macro-create-tangent-arc">Sketch - Create Tangent Arc</a></strong> post.</p><p>In this post, I tell you about <code>Create3PointArc</code> method from <strong>Solidworks</strong> <code>SketchManager</code> object.</p><p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>. </p><p>So <strong><em>use this method</em></strong> if you want to create a new <strong>3-Point Arc</strong>.</p><p>Below is the <code>code</code> sample for creating <em>a 3-Point Arc</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Creating string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swSketchManager = swDoc.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Inserting a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swSketchManager.InsertSketch True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Creating Variable for Solidworks Sketch segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim mySketchSegment As SketchSegment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Creating a 3-Point Arc</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set mySketchSegment = swSketchManager.Create3PointArc(-1, 0, 0, 1, 0, 0, 0, 1, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; De-select the Arc after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ClearSelection2 True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Zoom to fit screen in Solidworks Window</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ViewZoomtofit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="understanding-the-code"></a>Understanding the Code<a aria-hidden="true" tabindex="-1" class="hash-link" href="#understanding-the-code" title="Direct link to heading">#</a></h2><p>Now let us walk through <em>each line</em> in the above code, and <strong>understand</strong> the meaning of every line.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div></div></div></div></div><p>This line forces us to define every variable we are going to use. </p><p>For more information please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div></div></div></div></div><p>In this line, we are creating a variable which we named as <code>swApp</code> and the type of this <code>swApp</code> variable is <code>SldWorks.SldWorks</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div></div></div></div></div><p>In this line, we are creating a variable which we named as <code>swDoc</code> and the type of this <code>swDoc</code> variable is <code>SldWorks.ModelDoc2</code>.</p><p>Next is our <code>Sub</code> procedure named as <code>main</code>. This procedure hold all the <em>statements (instructions)</em> we give to computer.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swApp = Application.SldWorks</span></div></div></div></div></div><p>In this line, we are setting the value of our Solidworks variable <code>swApp</code> which we defined earlier to Solidworks application.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div></div></div></div></div><p>In 1st statement of above example, we are defining a variable of <code>string</code> type and named it as <code>defaultTemplate</code>.</p><p>This variable <code>defaultTemplate</code>, holds the location the location of <strong>Default Part Template</strong>.</p><p>In 2nd line of above example. we assign value to our newly define <code>defaultTemplate</code> variable.</p><p>We assign the value by using a <em>Method</em> named <code>GetUserPreferenceStringValue()</code>. </p><p>This method is a part of our main Solidworks variable <code>swApp</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div></div></div></div></div><p>In this line, we set the value of our <code>swDoc</code> variable to new document.</p><p>For <strong>more detailed information</strong> about above lines please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post. </p><p>I have discussed them <strong>thoroghly</strong> in <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post, so do checkout this post if you don&#x27;t understand above code.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div></div></div></div></div><p>In 1st line, we create a variable named <code>BoolStatus</code> as <code>Boolean</code> object.</p><p>In next line, we select the <em>front plane</em> by using <code>SelectByID2</code> method from <code>Extension</code> object.</p><p>For more information about selection method please visit <strong><a href="/docs/solidworks-macros/sw-macro-selection-methods">Solidworks Macros - Selection Methods</a></strong> post.</p><p>I have discussed about different <em>Selection methods</em> in details in <strong><a href="/docs/solidworks-macros/sw-macro-selection-methods">Soldworks Macros - Selection Methods</a></strong> post, so do visit this post for more <em>Selection methods</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div></div></div></div></div><p>In above line, we create variable <code>swSketchManager</code> for <strong>Solidworks Sketch Manager</strong>.</p><p>As the name suggested, a <strong>Sketch Manager</strong> holds variours methods and properties to manage <em>Sketches</em>.</p><p>To see methods and properties related to SketchManager object, please visit <strong><a href="/docs/solidworks-macros/help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this page</a></strong>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchManager = swDoc.SketchManager</span></div></div></div></div></div><p>In above line, we set the <strong>Sketch manager</strong> variable to current document&#x27;s sketch manager.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Inserting a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swSketchManager.InsertSketch True</span></div></div></div></div></div><p>In above line, we use <code>InsertSketch</code> method of <em>SketchManager</em> and give <code>True</code> value.</p><p>This method allows us to insert a sketch in selected plane.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating Variable for Solidworks Sketch segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim mySketchSegment As SketchSegment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating a 3-Point Arc</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set mySketchSegment = swSketchManager.Create3PointArc(-1, 0, 0, 1, 0, 0, 0, 1, 0)</span></div></div></div></div></div><p>In above sample code, we 1st create a variable named <code>mySketchSegment</code> of type <code>SketchSegment</code>.</p><p>A <code>SketchSegment</code> represent <em>a line, ellipse, parabola or spline.</em></p><p>A <code>SketchSegment</code> provides functions that are <strong>generic</strong> to every type of sketch segment.</p><p>For example, every sketch segment has <strong>an ID</strong> and can be selected programmatically.</p><p>Therefore, the <code>SketchSegment</code> interface provides functions to obtain the ID and to select the item.</p><p>For detailed information about the <code>SketchSegment</code> please visit <strong><a href="http://help.solidworks.com/2017/english/api/sldworksapi/SOLIDWORKS.Interop.sldworks~SOLIDWORKS.Interop.sldworks.ISketchSegment.html" target="_blank" rel="noopener noreferrer">this page of Solidworks API Help</a></strong>.</p><p>In 2nd line, we set the value of sketch segment variable <code>mySketchSegment</code>.</p><p>We get this value from <code>Create3PointArc</code> method which is inside the <code>swSketchManager</code> variable.</p><p><code>swSketchManager</code> variable is a type of <strong>SketchManager</strong>, hence we used <code>Create3PointArc</code> method from <strong>SketchManager</strong>.</p><p>This <code>Create3PointArc</code> method takes following parameters as explained:</p><ul><li><p><em>X1</em> : X coordinate of the start point, of the arc</p></li><li><p><em>Y1</em> : Y coordinate of the start point, of the arc</p></li><li><p><em>Z1</em> : Z coordinate of the start point, of the arc</p></li><li><p><em>X2</em> : X coordinate of the end point, of the arc</p></li><li><p><em>Y2</em> : Y coordinate of the end point, of the arc</p></li><li><p><em>Z2</em> : Z coordinate of the end point, of the arc</p></li><li><p><em>X3</em> : X coordinate of the middle point, of the arc</p></li><li><p><em>Y3</em> : Y coordinate of the middle point, of the arc</p></li><li><p><em>Z3</em> : Z coordinate of the middle point, of the arc</p></li></ul><p>For creating a <em>3-Point arc</em>, I used (-1, 0, 0) as the <em>Start point</em> for <strong>3-Point Arc</strong>, which is -1 point distance in X-direction.</p><p>For <em>End point</em> of <em>3-Point arc</em>, I used (1, 0, 0) which is 1 point distance in X-direction.</p><p>For <em>Middle point</em> of <em>3-Point arc</em>, I used (0, 1, 0) which is 1 point distance in Y-direction.</p><p>Below Image show above parameters in Details.</p><p><img alt="3point-arc-parameter-details" src="/assets/images/3point-arc-parameter-6152f742cc72b9a2d083cd60cf8545fb.png"></p><p>This <code>Create3PointArc</code> method returns <em>sketch segments</em> which represent the sides created for this <em>3-Point arc</em>.</p><p>A <em>Sketch Segment</em> can represent a sketch arc, line, ellipse, parabola or spline.</p><p>Sketch Segment has <code>ISketchSegment</code> Interface, which provides functions that are generic to every type of sketch segment.</p><p>For example, every sketch segment has an ID and can be programmatically selected.</p><p>Therefore, the <code>ISketchSegment</code> interface provides functions to obtain the ID and to select the item.</p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="note"></a>NOTE<a aria-hidden="true" tabindex="-1" class="hash-link" href="#note" title="Direct link to heading">#</a></h3><p>It is <strong><em>very important</em></strong> to remember that, when you give distance or any other numeric value in <strong>Solidworks API</strong>, Solidworks takes that numeric value in <strong><em>Meter only</em></strong>.</p><p><em>Solidworks API</em> does not care about your application&#x27;s Unit systems.</p><p>For example, I works in ANSI system means &quot;inches&quot; for distance. </p><p>But when I used Solidworks API through <em>VBA macros</em> or <em>C#</em>, I have to use <strong>converted</strong> numeric values.</p><p>Because Solidworks API output the distance in <strong>Meter</strong> only; which is not my requirement.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; De-select the Arc after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ClearSelection2 True</span></div></div></div></div></div><p>In the this line of code, we de-select the created 3-Point Arc.</p><p>For de-selecting, we use <code>ClearSelection2</code> method from our Solidworks document variable <code>swDoc</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Zoom to fit screen in Solidworks Window</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ViewZoomtofit</span></div></div></div></div></div><p>In this last line we use <em>zoom to fit</em> command.</p><p>For Zoom to fit, we use <code>ViewZoomtofit</code> method from our Solidworks document variable <code>swDoc</code>. </p><p>Hope this post helps you to <em>create 3-Point Arc</em> in Sketches with Solidworks VB Macros.</p><p>For more such tutorials on <strong>Solidworks VBA Macros</strong>, do come to this blog after sometime.</p><p>Till then, Happy learning!!!</p></div></article><div class="margin-vert--lg"><nav class="pagination-nav" aria-label="Blog list page navigation"><div class="pagination-nav__item"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-create-tangent-arc"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Â« Create Tangent Arc</div></a></div><div class="pagination-nav__item pagination-nav__item--next"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-create-polygon"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Create Polygon Â»</div></a></div></nav></div></div></div><div class="col col--3"><div class="tableOfContents_3SO_"><ul class="table-of-contents table-of-contents__left-border"><li><a href="#understanding-the-code" class="table-of-contents__link">Understanding the Code</a><ul><li><a href="#note" class="table-of-contents__link">NOTE</a></li></ul></li></ul></div></div></div></div></main></div></div><footer class="footer"><div class="container"><div class="row footer__links"><div class="col footer__col"><h4 class="footer__title">Tutorials</h4><ul class="footer__items"><li class="footer__item"><a class="footer__link-item" href="/docs/vba-Intro">VBA Introduction</a></li><li class="footer__item"><a class="footer__link-item" href="/docs/vba-in-sw">VBA in Solidworks</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">Community</h4><ul class="footer__items"><li class="footer__item"><a href="https://www.facebook.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Facebook</a></li><li class="footer__item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" rel="noopener noreferrer" class="footer__link-item">YouTube</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">More</h4><ul class="footer__items"><li class="footer__item"><a href="mailto:thecadcoder@gmail.com" target="_blank" rel="noopener noreferrer" class="footer__link-item">E-Mail</a></li><li class="footer__item"><a href="https://www.buymeacoffee.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Buy Me a Coffee</a></li></ul></div></div><div class="text--center"><div>Copyright Â© 2020 The Cad Coder, Inc. Built with Docusaurus.</div></div></div></footer></div>
<script src="/styles.e684f388.js"></script>
<script src="/runtime~main.bcdc0003.js"></script>
<script src="/main.2d365058.js"></script>
<script src="/1.1af7f77d.js"></script>
<script src="/2.4f0019c3.js"></script>
<script src="/94.4b40930d.js"></script>
<script src="/95.2f44d2c3.js"></script>
<script src="/f976f453.e3619938.js"></script>
<script src="/17896441.361bff39.js"></script>
<script src="/9d64bfcd.b8928d4d.js"></script>
</body>
</html>