<!doctype html>
<!--
  Minimal Mistakes Jekyll Theme 4.21.0 by Michael Rose
  Copyright 2013-2020 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE
-->
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">

<!-- begin _includes/seo.html --><title>Solidworks Macro - Open Saved Documents - The CAD Coder</title>
<meta name="description" content="In this post, I tell you how to open a saved document in Solidworks using VBA Macro.">


  <meta name="author" content="Admin">
  
  <meta property="article:author" content="Admin">
  


<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="Solidworks Macro - Open Saved Documents">
<meta property="og:url" content="http://localhost:4000/solidworks-macros/open-saved-document/">


  <meta property="og:description" content="In this post, I tell you how to open a saved document in Solidworks using VBA Macro.">







  <meta property="article:published_time" content="2021-02-10T14:44:06+00:00">





  

  


<link rel="canonical" href="http://localhost:4000/solidworks-macros/open-saved-document/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": "Admin",
      "url": "http://localhost:4000/"
    
  }
</script>






<!-- end _includes/seo.html -->


<link href="/feed.xml" type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">

<!-- https://t.co/dKP3o1e -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">

<script>
  document.documentElement.className = document.documentElement.className.replace(/\bno-js\b/g, '') + ' js ';
</script>

<!-- For all browsers -->
<link rel="stylesheet" href="/assets/css/main.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">

<!--[if IE]>
  <style>
    /* old IE unsupported flexbox fixes */
    .greedy-nav .site-title {
      padding-right: 3em;
    }
    .greedy-nav button {
      position: absolute;
      top: 0;
      right: 0;
      height: 100%;
    }
  </style>
<![endif]-->



    <!-- start custom head snippets -->

<!-- insert favicons. use https://realfavicongenerator.net/ -->

<!-- end custom head snippets -->

  </head>

  <body class="layout--single">
    <nav class="skip-links">
  <h2 class="screen-reader-text">Skip links</h2>
  <ul>
    <li><a href="#site-nav" class="screen-reader-shortcut">Skip to primary navigation</a></li>
    <li><a href="#main" class="screen-reader-shortcut">Skip to content</a></li>
    <li><a href="#footer" class="screen-reader-shortcut">Skip to footer</a></li>
  </ul>
</nav>

    <!--[if lt IE 9]>
<div class="notice--danger align-center" style="margin: 0;">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</div>
<![endif]-->

    

<div class="masthead">
  <div class="masthead__inner-wrap">
    <div class="masthead__menu">
      <nav id="site-nav" class="greedy-nav">
        
          <a class="site-logo" href="/"><img src="/assets/logo.png" alt=""></a>
        
        <a class="site-title" href="/">
          The CAD Coder
          
        </a>
        <ul class="visible-links"><li class="masthead__menu-item">
              <a href="/vba/vba-Introduction/">VBA</a>
            </li><li class="masthead__menu-item">
              <a href="/solidworks-macros/vba-in-solidworks/">Solidworks VBA Macro</a>
            </li><li class="masthead__menu-item">
              <a href="/Solidworks-csharp-api-tutorials/">Solidworks C# API</a>
            </li><li class="masthead__menu-item">
              <a href="/Solidworks-cpp-api-tutorials/">Solidworks C++ API</a>
            </li><li class="masthead__menu-item">
              <a href="/resources/">Resources</a>
            </li><li class="masthead__menu-item">
              <a href="/aboutMe/">About</a>
            </li></ul>
        
        <button class="search__toggle" type="button">
          <span class="visually-hidden">Toggle search</span>
          <svg class="icon" width="16" height="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15.99 16">
            <path d="M15.5,13.12L13.19,10.8a1.69,1.69,0,0,0-1.28-.55l-0.06-.06A6.5,6.5,0,0,0,5.77,0,6.5,6.5,0,0,0,2.46,11.59a6.47,6.47,0,0,0,7.74.26l0.05,0.05a1.65,1.65,0,0,0,.5,1.24l2.38,2.38A1.68,1.68,0,0,0,15.5,13.12ZM6.4,2A4.41,4.41,0,1,1,2,6.4,4.43,4.43,0,0,1,6.4,2Z" transform="translate(-.01)"></path>
          </svg>
        </button>
        
        <button class="greedy-nav__toggle hidden" type="button">
          <span class="visually-hidden">Toggle menu</span>
          <div class="navicon"></div>
        </button>
        <ul class="hidden-links hidden"></ul>
      </nav>
    </div>
  </div>
</div>


    <div class="initial-content">
      



<div id="main" role="main">
  
  <div class="sidebar sticky">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">General - Solidworks Functions</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/vba-in-solidworks/">Introduction</a></li>
          
            <li><a href="/solidworks-macros/open-new-document/">Open new Part document</a></li>
          
            <li><a href="/solidworks-macros/open-assembly-and-drawing/">Open Assembly and Drawing document</a></li>
          
            <li><a href="/solidworks-macros/select-plane-from-tree/">Selection Methods</a></li>
          
            <li><a href="/solidworks-macros/open-saved-document/" class="active">Open Saved Documents</a></li>
          
            <li><a href="/solidworks-macros/unit-correction/">Fix Unit Issue</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Lines</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/sketch-create-line/">Create Line</a></li>
          
            <li><a href="/solidworks-macros/sketch-create-centerline/">Create CenterLine</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Rectangles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-corner-rectangle/">Create Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-center-rectangle/">Create Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-corner-rectangle/">Create 3-Point Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-center-rectangle/">Create 3-Point Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-parallelogram/">Create A Parallelogram</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Circles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-circle/">Create Circle</a></li>
          
            <li><a href="/solidworks-macros/create-circle-by-radius/">Create Circle By Radius</a></li>
          
            <li><a href="/solidworks-macros/create-perimeter-circle/">Create Perimeter Circle</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Arcs</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc/">Create Centerpoint Arc</a></li>
          
            <li><a href="/solidworks-macros/create-tangent-arc/">Create Tangent Arc</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc/">Create 3-Point Arc</a></li>
          
            <li><a href="/solidworks-macros/polygon/">Create Polygon</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Slots</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-straight-slot/">Create a Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-straight-slot/">Create a Centerpoint Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc-slot/">Create a 3-Point Arc Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc-slot/">Create a Centerpoint Arc Slot</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Point and Spline</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-point/">Create a Point</a></li>
          
            <li><a href="/solidworks-macros/create-spline/">Create a Spline</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Fillet and Chamfer</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-fillet/">Create a Fillet</a></li>
          
            <li><a href="/solidworks-macros/create-chamfer/">Create a Chamfer</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Trim and Extend</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/trim-entities/">Trim Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/extend-entities/">Extend Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Patterns</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/linear-skech-pattern/">Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-linear-skech-pattern/">Edit Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/circular-skech-pattern/">Circular Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-circular-skech-pattern/">Edit Circular Sketch Pattern</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Move and Rotate</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/move-copy-sketch-entities/">Move/Copy Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/rotate-copy-sketch-entities/">Rotate/Copy Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Relations</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/toggle-display-sketch-relation/">Toggle (Hide/Show) Sketch Relations</a></li>
          
            <li><a href="/solidworks-macros/add-sketch-relations/">Add Sketch Relations (Constraints)</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Dimensions</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/add-dimension-methods/">Add dimension to Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-extrude-feature/">Extrude Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Others</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/convert-to-construction-sketch-segment/">Convert to Construction Sketch</a></li>
          
            <li><a href="/solidworks-macros/split-sketch-segments/">Split Open/Closed Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>



  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    <meta itemprop="headline" content="Solidworks Macro - Open Saved Documents">
    <meta itemprop="description" content="In this post, I tell you how to open a saved document in Solidworks using VBA Macro.">
    
    

    <div class="page__inner-wrap">
      
        <header>
          <h1 id="page-title" class="page__title" itemprop="headline">Solidworks Macro - Open Saved Documents
</h1>
          

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          4 minute read
        
      </span>
    
  </p>


        </header>
      

      <section class="page__content" itemprop="text">
        
          <aside class="sidebar__right sticky">
            <nav class="toc">
              <header><h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4></header>
              <ul class="toc__menu"><li><a href="#video-of-code-on-youtube">Video of Code on YouTube</a></li><li><a href="#by-opendoc-method">By OpenDoc method</a></li><li><a href="#by-opendoc6-method">By OpenDoc6 method</a></li></ul>

            </nav>
          </aside>
        
        <p>In this post, I tell you how to <em>open a saved document</em> in Solidworks using <em>VBA Macro</em>.</p>

<p>We open document with 2 different methods.</p>

<ol>
  <li>
    <p>By <code class="language-plaintext highlighter-rouge">OpenDoc</code> method</p>
  </li>
  <li>
    <p>By <code class="language-plaintext highlighter-rouge">OpenDoc6</code> method</p>
  </li>
</ol>

<h2 id="video-of-code-on-youtube">Video of Code on YouTube</h2>

<p>Please see below video on <strong>how to Open Saved Documents</strong> from Visual Studio.</p>

<iframe src="https://www.youtube.com/embed/DeltLKXAIjY" frameborder="0" allowfullscreen=""></iframe>
<p><br /></p>

<p>Please note that there are <strong>no explaination</strong> in the video.</p>

<p><strong>Explaination</strong> of each line and why we write code this way is given in this post.</p>

<h2 id="by-opendoc-method">By OpenDoc method</h2>

<p>This is <strong>the simplest</strong> method to open a saved part from your computer.</p>

<p>In this method we just need two information.</p>

<ul>
  <li>
    <p>Location of document to open</p>
  </li>
  <li>
    <p>Type of document which we want to open</p>
  </li>
</ul>

<p>Below is the example code for opening a saved document using <code class="language-plaintext highlighter-rouge">OpenDoc</code> method.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>


<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Setting Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
      
  <span class="c1">' Open a saved document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">OpenDoc</span><span class="p">(</span><span class="s">"H:\Solidworks studies\API Studies\Chapter 1 - The Basics\1st example part.SLDPRT"</span><span class="p">,</span> <span class="n">swDocumentTypes_e</span><span class="p">.</span><span class="n">swDocPART</span><span class="p">)</span>
      
  <span class="c1">' Selecting Front Plane</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SelectByID</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>I have already explained every line except <em>middle line</em> in above code sample in previous posts.</p>

<p>To open a saved document we used following lline.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Open a saved document</span>
<span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">OpenDoc</span><span class="p">(</span><span class="s">"H:\Solidworks studies\API Studies\Chapter 1 - The Basics\1st example part.SLDPRT"</span><span class="p">,</span> <span class="n">swDocumentTypes_e</span><span class="p">.</span><span class="n">swDocPART</span><span class="p">)</span>
</code></pre></div></div>

<p>Here, we set the <code class="language-plaintext highlighter-rouge">ModelDoc2</code> variable <code class="language-plaintext highlighter-rouge">swDoc</code> to a value.</p>

<p>This value is <em>return</em> or <em>provided</em> by <code class="language-plaintext highlighter-rouge">OpenDoc</code> method.</p>

<p>This method is part of <em>Solidworks document</em>.</p>

<p>Since we define <code class="language-plaintext highlighter-rouge">swApp</code> variable as Solidworks document hence we 1st call <code class="language-plaintext highlighter-rouge">swApp</code> and then using <code class="language-plaintext highlighter-rouge">Dot operator</code> we access the <code class="language-plaintext highlighter-rouge">OpenDoc</code> method.</p>

<p><code class="language-plaintext highlighter-rouge">OpenDoc</code> method takes 2 <em>arguments</em> or <em>parameter</em>.</p>

<p><em>FileName</em> : Document name or full path if not in current directory, including extension.</p>

<p><em>Type</em> : Document type as define in <code class="language-plaintext highlighter-rouge">swDocumentTypes_e</code> as follows.</p>

<ul>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocASSEMBLY</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocDRAWING</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocLAYOUT</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocNONE</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocPART</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocSDM</code></p>
  </li>
</ul>

<blockquote>
  <p>If you want to open a Library feature part then we use <code class="language-plaintext highlighter-rouge">swDocPART</code> as document type.</p>
</blockquote>

<p><strong>Return Value</strong> - If the document opens then this method returns <code class="language-plaintext highlighter-rouge">True</code> and otherwise <code class="language-plaintext highlighter-rouge">False</code>.</p>

<p>If you just want to open a saved document then this method is what you are looking for.</p>

<p>For most of the part, <code class="language-plaintext highlighter-rouge">OpenDoc</code> method works well.</p>

<p>If you want more option while opening a document, then next method is for you.</p>

<hr />

<h2 id="by-opendoc6-method">By OpenDoc6 method</h2>

<p><code class="language-plaintext highlighter-rouge">OpenDoc6</code> method is extension to <code class="language-plaintext highlighter-rouge">OpenDoc</code> with some additional parameters.</p>

<p>How <code class="language-plaintext highlighter-rouge">OpenDoc6</code> works is shown in below code sample:</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>


<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

    <span class="c1">' Setting Solidworks variable to Solidworks application</span>
    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
        
    <span class="c1">' Open an saved document</span>
    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">OpenDoc6</span><span class="p">(</span><span class="s">"H:\Solidworks studies\API Studies\Chapter 1 - The Basics\1st example part.SLDPRT"</span><span class="p">,</span> <span class="n">swDocumentTypes_e</span><span class="p">.</span><span class="n">swDocPART</span><span class="p">,</span> <span class="n">swOpenDocOptions_e</span><span class="p">.</span><span class="n">swOpenDocOptions_Silent</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
        
    <span class="c1">' Selecting Front Plane</span>
    <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SelectByID</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>This code sample is similar is to previous example code except for <code class="language-plaintext highlighter-rouge">OpenDoc6</code> method takes extra 4 parameters.</p>

<p><code class="language-plaintext highlighter-rouge">OpenDoc6</code> method takes 6 <em>arguments</em> or <em>parameter</em>.</p>

<p><em>FileName</em> : Document name or full path if not in current directory, including extension.</p>

<p><em>Type</em> : Document type as define in <code class="language-plaintext highlighter-rouge">swDocumentTypes_e</code> as follows.</p>

<ul>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocASSEMBLY</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocDRAWING</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocLAYOUT</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocNONE</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocPART</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocSDM</code></p>
  </li>
</ul>

<blockquote>
  <p>If you want to open a Library feature part then we use <code class="language-plaintext highlighter-rouge">swDocPART</code> as document type.</p>
</blockquote>

<p><em>Options</em> : Mode in which to open the document as defined in <code class="language-plaintext highlighter-rouge">swOpenDocOptions_e</code>.</p>

<p>For more details about <em>Options</em> parameters, please visit <strong><a href="https://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swOpenDocOptions_e.html">this page of Solidworks API Help</a></strong>.</p>

<p><em>Configuration</em> : Configuration in which you want to open this document.</p>

<ul>
  <li>
    <p>Applies to <em>Part</em> and <em>Assemblies</em>, not <em>drawings</em>.</p>
  </li>
  <li>
    <p>If this argument is <em>empty</em> or the specified configuration is <em>not present</em> in the model, the model is opened in the last-used configuration.</p>
  </li>
</ul>

<p>I used an <code class="language-plaintext highlighter-rouge">""</code> in the above code sample, because I want to open part file in last saved configuration.</p>

<p>If you don’t know about <code class="language-plaintext highlighter-rouge">""</code>, then this symbol represent an <strong>empty string</strong>.</p>

<p>When we don’t want to pass any value as <code class="language-plaintext highlighter-rouge">string</code>, at that time I use <code class="language-plaintext highlighter-rouge">""</code>.</p>

<p>You can also use <code class="language-plaintext highlighter-rouge">""</code> when you want to pass an empty string in VBA.</p>

<p><em>Errors</em> : Load errors as defined in <code class="language-plaintext highlighter-rouge">swFileLoadError_e</code>.</p>

<p>For more details about <em>Errors</em> parameters, please visit <strong><a href="http://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swFileLoadError_e.html">this page of Solidworks API Help</a></strong>.</p>

<p>Since this parameter is <code class="language-plaintext highlighter-rouge">long</code> type, and I don’t want to enter any value from the provided list; I used <strong>0</strong> as value.</p>

<p>If you want to use options from option link then you can use values from there.</p>

<p>It is just I don’t want to load any error information about the part.</p>

<p><em>Warnings</em> : Warnings or extra information generated during the open operation as defined in <code class="language-plaintext highlighter-rouge">swFileLoadWarning_e</code>.</p>

<p>For more details about <em>Warnings</em> parameters, please visit <strong><a href="http://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swFileLoadWarning_e.html">this page of Solidworks API Help</a>.</strong></p>

<p>As in the previous parameter, I use <strong>0</strong> as value.</p>

<p><strong>Return Value</strong> - If the document opens then this method returns <code class="language-plaintext highlighter-rouge">True</code> and otherwise <code class="language-plaintext highlighter-rouge">False</code>.</p>

<p>As you can see, in <code class="language-plaintext highlighter-rouge">OpenDoc6</code> method, we need to defined the extra parameters compared to <code class="language-plaintext highlighter-rouge">OpenDoc</code> method.</p>

<p>It is worth noted that, <code class="language-plaintext highlighter-rouge">OpenDoc6</code> method is the most updated method for opening a saved document.</p>

<p>Hence if did not use any of the above method, I would recommend you to use <code class="language-plaintext highlighter-rouge">OpenDoc6</code> method.</p>

<p>Hope this post helps you to understand opening methods with Solidworks VB Macros.</p>

<p>For more such tutorials on Solidworks VBA Macros, do come to this blog after sometime.</p>

<p>Till then, Happy learning!!!</p>


        
      </section>

      <footer class="page__meta">
        
        
  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-tags" aria-hidden="true"></i> Tags: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/tags/#solidworks-macro" class="page__taxonomy-item" rel="tag">Solidworks Macro</a>
    
    </span>
  </p>




  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-folder-open" aria-hidden="true"></i> Categories: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/categories/#solidworks-macro" class="page__taxonomy-item" rel="tag">Solidworks-macro</a>
    
    </span>
  </p>


        

      </footer>

      <section class="page__share">
  

  <a href="https://twitter.com/intent/tweet?text=Solidworks+Macro+-+Open+Saved+Documents%20http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fopen-saved-document%2F" class="btn btn--twitter" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Twitter"><i class="fab fa-fw fa-twitter" aria-hidden="true"></i><span> Twitter</span></a>

  <a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fopen-saved-document%2F" class="btn btn--facebook" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Facebook"><i class="fab fa-fw fa-facebook" aria-hidden="true"></i><span> Facebook</span></a>

  <a href="https://www.linkedin.com/shareArticle?mini=true&url=http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fopen-saved-document%2F" class="btn btn--linkedin" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on LinkedIn"><i class="fab fa-fw fa-linkedin" aria-hidden="true"></i><span> LinkedIn</span></a>
</section>



      
  <nav class="pagination">
    
      <a href="/solidworks-macros/select-plane-from-tree/" class="pagination--pager" title="Solidworks Macro - Selection Methods
">Previous</a>
    
    
      <a href="/solidworks-macros/unit-correction/" class="pagination--pager" title="Solidworks Macro - Fix Unit Issue
">Next</a>
    
  </nav>

    </div>

    
  </article>

  
  
    <div class="page__related">
      <h4 class="page__related-title">You May Also Enjoy</h4>
      <div class="grid__wrapper">
        
      </div>
    </div>
  
  
</div>

    </div>

    
      <div class="search-content">
        <div class="search-content__inner-wrap"><form onsubmit="return googleCustomSearchExecute();" id="cse-search-box-form-id">
    <label class="sr-only" for="cse-search-input-box-id">
      Enter your search term...
    </label>
    <input type="search" id="cse-search-input-box-id" class="search-input" tabindex="-1" placeholder="Enter your search term..." />
  </form>
  <div id="results" class="results">
    <gcse:searchresults-only></gcse:searchresults-only>
  </div></div>

      </div>
    

    <div id="footer" class="page__footer">
      <footer>
        <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
        <div class="page__footer-follow">
  <ul class="social-icons">
    

    
      
        
      
        
          <li><a href="https://facebook.com/thecadcoder" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-facebook-square" aria-hidden="true"></i> Facebook</a></li>
        
      
        
      
        
      
        
      
        
      
        
          <li><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" rel="nofollow noopener noreferrer"><i class="fab fa-youtube" aria-hidden="true"></i> YouTube</a></li>
        
      
        
          <li><a href="mailto:thecadcoder@gmail.com" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-envelope-square" aria-hidden="true"></i> Email</a></li>
        
      
    

    <li><a href="/feed.xml"><i class="fas fa-fw fa-rss-square" aria-hidden="true"></i> Feed</a></li>
  </ul>
</div>

<div class="page__footer-copyright">&copy; 2021 Admin. Powered by <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a> &amp; <a href="https://mademistakes.com/work/minimal-mistakes-jekyll-theme/" rel="nofollow">Minimal Mistakes</a>. | <strong><a href="http://localhost:4000/Disclaimer/" rel="nofollow"><i class="fas fa-lock" aria-hidden="true"></i> Privacy Policy</a></strong></div>

      </footer>
    </div>

    
  <script src="/assets/js/main.min.js"></script>


<script>
  (function () {
    var cx = '4b2b9cb8c831ee0fb';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();

  function googleCustomSearchExecute() {
    var input = document.getElementById('cse-search-input-box-id');
    var element = google.search.cse.element.getElement('searchresults-only0');
    if (input.value == '') {
      element.clearAllResults();
    } else {
      element.execute(input.value);
    }
    return false;
  }

  
    $(document).ready(function () {
      $('input#cse-search-input-box-id').on('keyup', function () {
        googleCustomSearchExecute();
      });
    });
  
</script>







    <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>


  </body>
</html>
