<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="generator" content="Docusaurus v2.0.0-alpha.66">
<link rel="preconnect" href="https://www.google-analytics.com">
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-117501871-2","auto"),ga("set","anonymizeIp",!0),ga("send","pageview")</script>
<script async src="https://www.google-analytics.com/analytics.js"></script><title data-react-helmet="true">Edit Circular Sketch Pattern | The Cad Coder</title><meta data-react-helmet="true" name="twitter:card" content="summary_large_image"><meta data-react-helmet="true" name="docusaurus_language" content="en"><meta data-react-helmet="true" name="docusaurus_version" content="current"><meta data-react-helmet="true" name="docusaurus_tag" content="docs-default-current"><meta data-react-helmet="true" property="og:title" content="Edit Circular Sketch Pattern | The Cad Coder"><meta data-react-helmet="true" name="description" content="In this post, I tell you about how to Edit Circular Sketch Pattern using Solidworks VBA Macros in a Sketch."><meta data-react-helmet="true" property="og:description" content="In this post, I tell you about how to Edit Circular Sketch Pattern using Solidworks VBA Macros in a Sketch."><meta data-react-helmet="true" property="og:url" content="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern"><link data-react-helmet="true" rel="shortcut icon" href="/img/logo.png"><link data-react-helmet="true" rel="canonical" href="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern"><link rel="stylesheet" href="/styles.f7ef45b3.css">
<link rel="preload" href="/styles.49bb2333.js" as="script">
<link rel="preload" href="/runtime~main.44b41c7a.js" as="script">
<link rel="preload" href="/main.5021cc11.js" as="script">
<link rel="preload" href="/1.86ce1451.js" as="script">
<link rel="preload" href="/2.4a46354d.js" as="script">
<link rel="preload" href="/94.aaa5e340.js" as="script">
<link rel="preload" href="/95.e3f7e856.js" as="script">
<link rel="preload" href="/f976f453.85830ae4.js" as="script">
<link rel="preload" href="/17896441.686270c8.js" as="script">
<link rel="preload" href="/af8b4145.0e72ec36.js" as="script">
</head>
<body>
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><div aria-label="Navigation bar toggle" class="navbar__toggle" role="button" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></div><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a><div class="navbar__item dropdown dropdown--hoverable dropdown--left"><a class="navbar__item navbar__link">VBA</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li><a class="dropdown__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></div><a class="navbar__item navbar__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a><a class="navbar__item navbar__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></div><div class="navbar__items navbar__items--right"><div class="navbar__item dropdown dropdown--hoverable dropdown--right"><a class="navbar__item navbar__link">About</a><ul class="dropdown__menu"><li><a class="dropdown__link" position="right" href="/docs/about">About Me</a></li><li><a class="dropdown__link" position="right" href="/docs/resources">Resources</a></li><li><a class="dropdown__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></div><div class="react-toggle react-toggle--disabled displayOnlyInLargeViewport_2aTZ"><div class="react-toggle-track"><div class="react-toggle-track-check"><span class="toggle_BsTx">ðŸŒœ</span></div><div class="react-toggle-track-x"><span class="toggle_BsTx">ðŸŒž</span></div></div><div class="react-toggle-thumb"></div><input type="checkbox" disabled="" aria-label="Dark mode toggle" class="react-toggle-screenreader-only"></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div><div class="navbar-sidebar"><div class="navbar-sidebar__brand"><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a></div><div class="navbar-sidebar__items"><div class="menu"><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">VBA</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></li><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">About</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/about">About Me</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/resources">Resources</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></li></ul></div></div></div></nav><div class="main-wrapper"><div class="docPage_2gpo"><div class="docSidebarContainer_3_JD" role="complementary"><div class="sidebar_2urC"><div class="menu menu--responsive menu_5FrY"><button aria-label="Open Menu" aria-haspopup="true" class="button button--secondary button--sm menu__button" type="button"><svg aria-label="Menu" class="sidebarMenuIcon_Dm3K" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 32 32" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">General Functions</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba-in-sw">VBA in Solidworks</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-part">Open new Part document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-asm-and-dwg">Open Assembly and Drawing document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-selection-methods">Selection Methods</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-saved-documents">Open Saved Documents</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue">Fix Unit Issue</a></li></ul></li><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!">Sketch</a><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Lines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-line">Create Line</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerline">Create CenterLine</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Rectangles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-corner-rec">Create Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-center-rec">Create Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-corner-rec">Create 3-Point Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-center-rec">Create 3-Point Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-parallelogram">Create A Parallelogram</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Circles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle">Create Circle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle-by-radius">Create Circle By Radius</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-perimeter-circle">Create Perimeter Circle</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Arcs</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc">Create Centerpoint Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-tangent-arc">Create Tangent Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc">Create 3-Point Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-polygon">Create Polygon</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Slots</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-straight-slot">Create a Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-straight-slot">Create a Centerpoint Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc-slot">Create a 3-Point Arc Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc-slot">Create a Centerpoint Arc Slot</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Splines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-point">Create a Point</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-spline">Create a Spline</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Fillet &amp; Chamfer</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-fillet">Create a Fillet</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-chamfer">Create a Chamfer</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Trim and Extend</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-trim-entities">Trim Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-extend-entities">Extend Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Offset and Mirror</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-offset-entities">Offset Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-mirror-sketch-entities">Mirror Sketch Entities</a></li></ul></li><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!" tabindex="0">Sketch Patterns</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-linear-sketch-patterm">Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm">Edit Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm">Circular Sketch Pattern</a></li><li class="menu__list-item"><a aria-current="page" class="menu__link menu__link--active active" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern">Edit Circular Sketch Pattern</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Transformation</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities">Move/Copy Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities">Rotate/Copy Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Relations</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-toggle-sketch-relation">Toggle (Hide/Show) Sketch Relations</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-sketch-relation">Add Sketch Relations (Constraints)</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Others</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-convert-to-construction-sketch">Convert to Construction Sketch</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-split-sketch-entities">Split Open/Closed Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Dimensioning</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-dimension-sketch-entities">Add dimension to Sketch Entities</a></li></ul></li></ul></li></ul></div></div></div><main class="docMainContainer_3EyW"><div class="container padding-vert--lg docItemWrapper_1EkI"><div class="row"><div class="col docItemCol_2ASc"><div class="docItemContainer_3QWW"><article><header><h1 class="docTitle_1Lrw">Edit Circular Sketch Pattern</h1></header><div class="markdown"><p>In this post, I tell you about <strong>how to Edit Circular Sketch Pattern using Solidworks VBA Macros</strong> in a Sketch.</p><p>In this post, I explain about <code>EditCircularSketchStepAndRepeat</code> method from <strong>Solidworks</strong> <code>SketchManager</code> object.</p><p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>. </p><p>So <strong><em>use this method</em></strong> if you want to <em>edit existing Circular Sketch Pattern</em>.</p><p>This post is a little different of previous <strong><a href="/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm">Solidworks Macro - Circular Sketch Pattern From VBA Macro</a></strong> post.</p><p>There are 2 changes I have made, which I am going to use on future posts also.</p><p>These change are explain below:</p><ul><li><p>In this post I used <code>code sample</code> from <strong><a href="/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue">Fix Unit Issue</a></strong> post to fix unit conversion issue and show how to use it.</p></li><li><p>In input parameter of <code>EditCircularSketchStepAndRepeat</code> method, I passed variables not direct values. This helps us to maintain the code and modification of existing code is simple.</p></li></ul><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="code-sample"></a>Code Sample<a aria-hidden="true" tabindex="-1" class="hash-link" href="#code-sample" title="Direct link to heading">#</a></h2><p>Below is the <code>code</code> sample to <em>edit Circular Sketch Pattern</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create Variable for Solidworks Sketch Segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchSegment As SldWorks.SketchSegment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Create string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27;-----------------------UNIT CONVERSION----------------------------------------</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Local variables used as Conversion Factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim LengthConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim AngleConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Use a Select Case, to get the length of active Unit and set the different factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Select Case swDoc.GetUnits(0)       &#x27; GetUnits function gives us, active unit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swMETER    &#x27; If length is in Meter</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swMM       &#x27; If length is in MM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 1000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swCM       &#x27; If length is in CM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 100</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swINCHES   &#x27; If length is in INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 * 0.0254</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swFEET     &#x27; If length is in FEET</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 * (0.0254 * 12)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swFEETINCHES     &#x27; If length is in FEET &amp; INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 * 0.0254  &#x27; For length we use sama as Inch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swANGSTROM        &#x27; If length is in ANGSTROM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 10000000000#</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swNANOMETER       &#x27; If length is in NANOMETER</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 1000000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swMICRON       &#x27; If length is in MICRON</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 1000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  End Select</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27;----------------------------------------------------------------</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Select Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swSketchManager = swDoc.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Insert a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swSketchManager.InsertSketch True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Circle Radius</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim circleRadius As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  circleRadius = 5 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Sketch Segment value and Create a Circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, circleRadius)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; De-select the lines after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ClearSelection2 True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Select Circle we want to Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  BoolStatus = swDoc.Extension.SelectByID2(&quot;Arc1&quot;, &quot;SKETCHSEGMENT&quot;, 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Arc Radius</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim arcRadius As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  arcRadius = 10 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Arc Angle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim arcAngle As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  arcAngle = 0 * AngleConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Number of Instances</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim numberOfInstance As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  numberOfInstance = 3</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Pattern Spacing</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim patternSpacing As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  patternSpacing = 5 * AngleConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Create a Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  BoolStatus = swSketchManager.CreateCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, True, &quot;&quot;, True, True, True)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; De-select the Sketch Segment after Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ClearSelection2 True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Update Arc Radius</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  arcRadius = 20 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Edit a Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  BoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, True, &quot;&quot;, True, True, True, &quot;Arc1_&quot;)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Show Front View after Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ShowNamedView2 &quot;&quot;, swStandardViews_e.swFrontView</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Zoom to fit screen in Solidworks Window</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ViewZoomtofit2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="understanding-the-code"></a>Understanding the Code<a aria-hidden="true" tabindex="-1" class="hash-link" href="#understanding-the-code" title="Direct link to heading">#</a></h3><p>Now let us walk through <strong>each line</strong> in the above code, and <strong>understand</strong> the meaning and purpose of every line.</p><p>I also give some link so that you can go through them if there are anything I explained in <strong>previous posts</strong>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div></div></div></div></div><p>This line forces us to define every variable we are going to use. </p><p>For more information please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div></div></div></div></div><p>In this line, we create a variable which we named as <code>swApp</code> and the type of this <code>swApp</code> variable is <code>SldWorks.SldWorks</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div></div></div></div></div><p>In this line, we create a variable which we named as <code>swDoc</code> and the type of this <code>swDoc</code> variable is <code>SldWorks.ModelDoc2</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div></div></div></div></div><p>In this line, we create a variable named <code>BoolStatus</code> as <code>Boolean</code> object type.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div></div></div></div></div><p>In above line, we create variable <code>swSketchManager</code> for <strong>Solidworks Sketch Manager</strong>.</p><p>As the name suggested, a <strong>Sketch Manager</strong> holds variours methods and properties to manage <em>Sketches</em>.</p><p>To see methods and properties related to <code>SketchManager</code> object, please visit <strong><a href="/docs/solidworks-macros/help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this page</a></strong>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks Sketch Segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchSegment As SldWorks.SketchSegment</span></div></div></div></div></div><p>In this line, we Create a variable which we named as <code>swSketchSegment</code> and the type of this <code>swSketchSegment</code> variable is <code>SldWorks.SketchSegment</code>.</p><p>We create variable <code>swSketchSegment</code> for <strong>Solidworks Sketch Segments</strong>.</p><p>To see methods and properties related to <code>swSketchSegment</code> object, please visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html" target="_blank" rel="noopener noreferrer">this page</a></strong>.</p><p>These all are our global variables.</p><p>As you can see in code sample, they are <strong>Solidworks API Objects</strong>.</p><p>So basically I group all the <strong>Solidworks API Objects</strong> in one place.</p><p>I have also place <code>boolean</code> type object at top also, because after certain point we will <em>need</em> this variable frequently.</p><p>Thus, I have started placing it here.</p><p>Next is our <code>Sub</code> procedure which has name of <code>main</code>. </p><p>This procedure hold all the <em>statements (instructions)</em> we give to computer.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swApp = Application.SldWorks</span></div></div></div></div></div><p>In this line, we set the value of our Solidworks variable <code>swApp</code>; which we define earlier; to Solidworks application.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div></div></div></div></div><p>In 1st statement of above example, we are defining a variable of <code>string</code> type and named it as <code>defaultTemplate</code>.</p><p>This variable <code>defaultTemplate</code>, hold the location the location of <strong>Default Part Template</strong>.</p><p>In 2nd line of above example. we assign value to our newly define <code>defaultTemplate</code> variable.</p><p>We assign the value by using a <em>Method</em> named <code>GetUserPreferenceStringValue()</code>. </p><p>This <code>GetUserPreferenceStringValue()</code> method is a part of our main Solidworks variable <code>swApp</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div></div></div></div></div><p>In this line, we set the value of our <code>swDoc</code> variable to new document.</p><p>For <strong>detailed information</strong> about these lines please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post.</p><p>I have discussed them <strong>thoroghly</strong> in <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post, so do checkout that post if you want to understand above code in more detail.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27;-----------------------UNIT CONVERSION----------------------------------------</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Local variables used as Conversion Factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim LengthConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim AngleConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Use a Select Case, to get the length of active Unit and set the different factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Select Case swDoc.GetUnits(0)       &#x27; GetUnits function gives us, active unit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swMETER    &#x27; If length is in Meter</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swMM       &#x27; If length is in MM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 1000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swCM       &#x27; If length is in CM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 100</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swINCHES   &#x27; If length is in INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 * 0.0254</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swFEET     &#x27; If length is in FEET</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 * (0.0254 * 12)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swFEETINCHES     &#x27; If length is in FEET &amp; INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 * 0.0254  &#x27; For length we use sama as Inch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swANGSTROM        &#x27; If length is in ANGSTROM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 10000000000#</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swNANOMETER       &#x27; If length is in NANOMETER</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 1000000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swMICRON       &#x27; If length is in MICRON</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 1000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Select</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27;----------------------------------------------------------------</span></div></div></div></div></div><p>Above code sample shows how to <strong>fix Solidworks API Unit issue</strong>. </p><p>We <em>1st</em> get the <em>current unit</em> of the part and apply the <em>switch</em> statements to update our <em>Length and Angle Conversion factors</em>. </p><p>I have already explained in detail about <strong>Fixing Solidworks API Unit Issue</strong> in <strong><a href="/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue">Fix Unit Issue</a></strong> blog post. </p><p>Do checkout above post for Fixing Solidworks API Issue.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Select Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div></div></div></div></div><p>In above line, we select the <em>front plane</em> by using <code>SelectByID2</code> method from <code>Extension</code> object.</p><p>For more information about selection method please visit <strong><a href="/docs/solidworks-macros/sw-macro-selection-methods">Solidworks Macros - Selection Methods</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchManager = swDoc.SketchManager</span></div></div></div></div></div><p>In above line, we set the <em>Sketch manager</em> variable to <em>current document&#x27;s sketch manager</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Insert a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swSketchManager.InsertSketch True</span></div></div></div></div></div><p>In above line, we use <code>InsertSketch</code> method of <em>SketchManager</em> and give <code>True</code> value.</p><p>This method allows us to insert a sketch in selected plane.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Circle Radius</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim circleRadius As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">circleRadius = 5 * LengthConversionFactor</span></div></div></div></div></div><p>In above code sample, we do following:</p><ol><li><p>Create a local variable named <code>circleRadius</code>, which is <code>Double</code> type.</p></li><li><p>In 2nd line, we assign a value of <strong>5</strong> to our <code>circleRadius</code> variable, also we multiple with our <code>LengthConversionFactor</code> variable.</p></li></ol><p>Since I am using <em>IPS unit system</em>, I want to create a circle of Radius <em>5 inch</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Sketch Segment value and Create a Circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, circleRadius)</span></div></div></div></div></div><p>In above line, we set the value of Solidworks Sketch Segment variable <code>swSketchSegment</code> by <code>CreateCircleByRadius</code> method from <em>Solidworks Sketch Manager</em>.</p><p>This <code>CreateCircleByRadius</code> method creates <em>a Circle</em> at given point with radius.</p><p>For more information about <code>CreateCircleByRadius</code> method, you can read my <strong><a href="/docs/solidworks-macros/sw-sketch-macro-create-circle-by-radius">Solidworks Macro - Create Circle By Radius From VBA Macro</a></strong> post.</p><p>That post describe all the parameters we need for this <code>CreateCircleByRadius</code> method in details.</p><p>In above line, we create a Circle with:</p><ul><li><p><strong>Circle Centerpoint</strong> : At origin i.e. <em>(0, 0, 0)</em></p></li><li><p><strong>Circle Radius</strong> : <em><code>circleRadius</code></em></p></li></ul><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; De-select the Sketch after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ClearSelection2 True</span></div></div></div></div></div><p>In the above line of code, we deselect the <strong>Sketch</strong> after the <em>Circular Sketch Pattern</em> operation.</p><p>For de-selecting, we use <code>ClearSelection2</code> method from our Solidworks document name <code>swDoc</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Select Circle we want to Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swDoc.Extension.SelectByID2(&quot;Arc1&quot;, &quot;SKETCHSEGMENT&quot;, 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div></div></div></div></div><p>In above line of code, we select the Circle i.e. <strong>Arc 1</strong> and add it to selection list.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Arc Radius</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim arcRadius As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">arcRadius = 10 * LengthConversionFactor</span></div></div></div></div></div><p>Above code sample creates a variable for <strong>Arc Radius</strong> and assign value.</p><p>While assigning the value we multiple with <code>LengthConversionFactor</code> to get correct length.</p><p>Variable Name: <code>arcRadius</code></p><p>Variable type: <code>Double</code></p><p>Variable Value: 10 inch</p><p><em>We want Arc Radius to 10 inch.</em></p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>By creating the variables we can handle the values more effciently.</p></div></div><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Arc Angle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim arcAngle As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">arcAngle = 0 * AngleConversionFactor</span></div></div></div></div></div><p>Above code sample creates a variable for <strong>Arc Angle</strong> and assign value.</p><p>While assigning the value we multiple with <code>AngleConversionFactor</code> to get correct angle.</p><p>Variable Name: <code>arcAngle</code></p><p>Variable type: <code>Double</code></p><p>Variable Value: 0</p><p><em>We want Arc Angle to 0 degree.</em></p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Number of Instances</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim numberOfInstance As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">numberOfInstance = 3</span></div></div></div></div></div><p>Above code sample creates a variable for <strong>Number of Instances</strong> and assign value.</p><p>Variable Name: <code>numberOfInstance</code></p><p>Variable type: <code>Double</code></p><p>Variable Value: 3</p><p><em>We want 3 copies of the circle including the seed i.e. original circle.</em></p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Pattern Spacing</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim patternSpacing As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">patternSpacing = 5 * AngleConversionFactor</span></div></div></div></div></div><p>Above code sample creates a variable for <strong>Pattern Spacing</strong> and assign value.</p><p>While assigning the value we multiple with <code>AngleConversionFactor</code> to get correct angle.</p><p>Variable Name: <code>patternSpacing</code></p><p>Variable type: <code>Double</code></p><p>Variable Value: 5</p><p><em>We want 5 degree of spacing between each circle.</em></p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create a Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swSketchManager.CreateCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, True, &quot;&quot;, True, True, True)</span></div></div></div></div></div><p>In above code sample we <em>Create a Circular Sketch Pattern</em> of the selected circle by <code>CreateCircularSketchStepAndRepeat</code> method from <em>Solidworks Sketch Manger</em> variable.</p><p>As you can see we pass our <em>previously created variables</em> <code>arcRadius</code>, <code>arcAngle</code>, <code>numberOfInstance</code> and <code>patternSpacing</code> in <code>CreateCircularSketchStepAndRepeat</code> method as parameters.</p><p>I have explained <code>CreateCircularSketchStepAndRepeat</code> method in detail in <strong><a href="/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm">Sketch - Circular Sketch Pattern</a></strong> post.</p><p>Please see above post if you want to learn more about <code>CreateCircularSketchStepAndRepeat</code> method and its parameters.</p><p>Below image shows Circular Sketch Pattern Parameter.</p><p><img alt="before-edit-circular-pattern" src="/assets/images/before-edit-circular-pattern-fe419f8b4250220bfc3613b83491a87d.png"></p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; De-select the Sketch Segment after Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ClearSelection2 True</span></div></div></div></div></div><p>In above line we <em>de-select</em> the <em>Sketch Segment</em> after creating <em>Circular Sketch Pattern</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Update Arc Radius</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">arcRadius = 20 * LengthConversionFactor</span></div></div></div></div></div><p>In above line we <strong>Update Arc Radius</strong> to new value which we will use in <em>Editing previously created Circular Sketch pattern</em>.</p><p>Variable Name: <code>arcRadius</code></p><p>Updated Value: 20 inch</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Edit a Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, True, &quot;&quot;, True, True, True, &quot;Arc1_&quot;)</span></div></div></div></div></div><p>For &quot;<strong>editing</strong>&quot; a Circular Sketch pattern, we need <code>EditCircularSketchStepAndRepeat</code> method from <em>Solidworks Sketch Manager</em> object/variable.</p><p>This <code>CreateCircularSketchStepAndRepeat</code> method takes following parameters as explained:</p><ul><li><p><strong>ArcRadius</strong> : <em>Radius for the circular sketch pattern. This value is in radian.</em></p></li><li><p><strong>ArcAngle</strong> : <em>Angle relative to the sketch entities being patterned. This value is in radian.</em></p></li><li><p><strong>PatternNum</strong> : <em>Total number of instances, including the seed geometry.</em></p></li><li><p><strong>PatternSpacing</strong> : <em>Spacing between pattern instances. This value is in radian.</em></p></li><li><p><strong>PatternRotate</strong> : <em>True to rotate the pattern, false to not.</em></p></li><li><p><strong>DeleteInstances</strong> : <em>Number of instances to delete, passed as a string in the format: &quot;(a) (b) (c)&quot;.</em></p></li><li><p><strong>RadiusDim</strong> : <em>True to display the radius dimension in the graphics area, false to not.</em></p></li><li><p><strong>AngleDim</strong> : <em>True to display the angle dimension between axes in the graphics area, false to not.</em></p></li><li><p><strong>CreateNumOfInstancesDim</strong> : <em>True to display the number of instances dimension in the graphics area, false to not.</em></p></li><li><p><strong>Seed</strong>: <em>List of the names of the entities, separated by the underscore character (<em>), that comprise the seed pattern (e.g., Arc1</em> as a seed pattern).</em></p></li></ul><p><strong>NOTE:</strong> In <em>Seed</em>, adding underscore(_) after selected entity is important, otherwise code will note work.</p><p>After the function complete following are the results:</p><p><strong>Return Value</strong>:</p><ul><li><p><strong>True</strong>: <em>If Edit Circular Sketch Pattern is </em>Success<em>.</em></p></li><li><p><strong>False</strong>: <em>If Edit Circular Sketch Pattern is </em>Fail<em>.</em></p></li></ul><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="cases"></a><strong>Cases</strong><a aria-hidden="true" tabindex="-1" class="hash-link" href="#cases" title="Direct link to heading">#</a></h2><p>In this section, we will go through different cases by </p><ul><li><p><em>Modifying different parameters</em></p></li><li><p><em>See images, before and after parameter modification</em></p></li></ul><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-1--update-arc-radius"></a>CASE 1 : Update Arc Radius<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-1--update-arc-radius" title="Direct link to heading">#</a></h3><p>In our code, if we want to update Arc Radius, then we need to update <code>arcRadius</code> variable only.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Update Arc Radius</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">arcRadius = 20 * LengthConversionFactor</span></div></div></div></div></div><p>In above line we <strong>Update Arc Radius</strong> to new value. of 20 inch.</p><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we update <strong>Arc Radius</strong>.</p><p><strong>Before Update Arc Radius</strong></p><p><img alt="before-edit-circular-pattern" src="/assets/images/before-edit-circular-pattern-fe419f8b4250220bfc3613b83491a87d.png"></p><p><strong>After Update Arc Radius</strong></p><p><img alt="after-update-arc-radius" src="/assets/images/after-update-arc-radius-3677d25642762b746e9ef6dcc6f32241.png"></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-2--update-arc-angle"></a>CASE 2 : Update Arc Angle<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-2--update-arc-angle" title="Direct link to heading">#</a></h3><p>In our code, if we want to update Arc Angle, then we need to update <code>arcAngle</code> variable only.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Update Arc Angle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">arcAngle = 30 * AngleConversionFactor</span></div></div></div></div></div><p>In above line we <strong>Update Arc Angle</strong> to new value of 30 inch.</p><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we update <strong>Arc Angle</strong>.</p><p><strong>Before Update Arc Angle</strong></p><p><img alt="after-update-arc-radius" src="/assets/images/after-update-arc-radius-3677d25642762b746e9ef6dcc6f32241.png"></p><p><strong>After Update Arc Angle</strong></p><p><img alt="after-update-arc-angle" src="/assets/images/after-update-arc-angle-e6e465fb88ffd4a8f6d2cfbe60753bdf.png"></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-3--update-number-of-instances"></a>CASE 3 : Update Number of Instances<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-3--update-number-of-instances" title="Direct link to heading">#</a></h3><p>In our code, if we want to update Number of Instances, then we need to update <code>numberOfInstance</code> variable only.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Update Number of Instances</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">numberOfInstance = 5</span></div></div></div></div></div><p>In above line we <strong>Update Number of Instances</strong> to new value of 5 number of instances.</p><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we update <strong>Number of Instances</strong>.</p><p><strong>Before Update Number of Instances</strong></p><p><img alt="after-update-arc-angle" src="/assets/images/after-update-arc-angle-e6e465fb88ffd4a8f6d2cfbe60753bdf.png"></p><p><strong>After Update Number of Instances</strong></p><p><img alt="after-update-number-of-instances" src="/assets/images/after-update-number-of-instances-e8ad5a826c39937cc230b222c0f53557.png"></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-4--update-pattern-spacing"></a>CASE 4 : Update Pattern Spacing<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-4--update-pattern-spacing" title="Direct link to heading">#</a></h3><p>In our code, if we want to update Number of Instances, then we need to update <code>patternSpacing</code> variable only.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Update Pattern Spacing</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">patternSpacing = 10 * AngleConversionFactor</span></div></div></div></div></div><p>In above line we <strong>Update Pattern Spacing</strong> to new value of 10 degree.</p><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we update <strong>Pattern Spacing</strong>.</p><p><strong>Before Update Pattern Spacing</strong></p><p><img alt="after-update-number-of-instances" src="/assets/images/after-update-number-of-instances-e8ad5a826c39937cc230b222c0f53557.png"></p><p><strong>After Update Pattern Spacing</strong></p><p><img alt="after-update-pattern-spacing" src="/assets/images/after-update-pattern-spacing-5af114e7a240763542004d930cfce8b9.png"></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-5--update-display-rotation-of-pattern"></a>CASE 5 : Update Display Rotation of Pattern<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-5--update-display-rotation-of-pattern" title="Direct link to heading">#</a></h3><p>If we want to update Display Rotation of Pattern, then we need to update value to either <code>True</code> or <code>False</code>.</p><p>In our code, we set this value to <code>True</code> which means we are displaying the rotation of pattern.</p><p>We update our code for not displaying the rotation of pattern as given in below code sample.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Edit a Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, False, &quot;&quot;, True, True, True, &quot;Arc1_&quot;)</span></div></div></div></div></div><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we update <strong>Display Rotation of Pattern</strong>.</p><p><strong>Before Update Display Rotation of Pattern</strong></p><p><img alt="after-update-pattern-spacing" src="/assets/images/after-update-pattern-spacing-5af114e7a240763542004d930cfce8b9.png"></p><p><strong>After Update Display Rotation of Pattern</strong></p><p><img alt="after-update-rotation-of-pattern" src="/assets/images/after-update-rotation-of-pattern-5af114e7a240763542004d930cfce8b9.png"></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-6--update-number-of-instances-to-delete"></a>CASE 6 : Update Number of Instances to Delete<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-6--update-number-of-instances-to-delete" title="Direct link to heading">#</a></h3><p>If we want to update Number of Instances to Delete, then we need to update value of <code>&quot;&quot;</code> as given in below code sample.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Edit a Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, False, &quot;(3)&quot;, True, True, True, &quot;Arc1_&quot;)</span></div></div></div></div></div><p>In above code sample, we want to delete 3rd instance hence we pass the number <strong><code>3</code></strong> inside <strong><code>()</code></strong>.</p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>For delete any instance we need to pass its position in paranthesis (). Otherwise it won&#x27;t work.**</p></div></div><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we update <strong>Number of Instances to Delete</strong>.</p><p><strong>Before Update Number of Instances to Delete</strong></p><p><img alt="after-update-pattern-spacing" src="/assets/images/after-update-pattern-spacing-5af114e7a240763542004d930cfce8b9.png"></p><p><strong>After Update Number of Instances to Delete</strong></p><p><img alt="after-update-number-of-instance-to-delete" src="/assets/images/after-update-number-of-instance-to-delete-82c7f1c197a256a08bd621e106dea366.png"></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-7--update-display-radius-dimension"></a>CASE 7 : Update Display Radius Dimension<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-7--update-display-radius-dimension" title="Direct link to heading">#</a></h3><p>If we want to update Display Radius Dimension, then we need to update value to either <code>True</code> or <code>False</code>.</p><p>In our code, we set this value to <code>True</code> which means we are displaying the Display Radius Dimension.</p><p>We update our code for not displaying the Display Radius Dimension as given in below code sample.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Edit a Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, False, &quot;(3)&quot;, False, True, True, &quot;Arc1_&quot;)</span></div></div></div></div></div><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we update <strong>Display Radius Dimension</strong>.</p><p><strong>Before Update Display Radius Dimension</strong></p><p><img alt="after-update-number-of-instance-to-delete" src="/assets/images/after-update-number-of-instance-to-delete-82c7f1c197a256a08bd621e106dea366.png"></p><p><strong>After Update Display Radius Dimension</strong></p><p><img alt="after-update-display-radius-dimension" src="/assets/images/after-update-display-radius-dimension-0170696abf2326d18f1321de4348564b.png"></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-8--update-display-angle-dimension"></a>CASE 8 : Update Display Angle Dimension<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-8--update-display-angle-dimension" title="Direct link to heading">#</a></h3><p>If we want to update Display Angle Dimension, then we need to update value to either <code>True</code> or <code>False</code>.</p><p>In our code, we set this value to <code>True</code> which means we are displaying the Display Angle Dimension.</p><p>We update our code for not displaying the Display Angle Dimension as given in below code sample.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Edit a Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, False, &quot;(3)&quot;, False, False, True, &quot;Arc1_&quot;)</span></div></div></div></div></div><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we update <strong>Display Angle Dimension</strong>.</p><p><strong>Before Update Display Angle Dimension</strong></p><p><img alt="after-update-number-of-instance-to-delete" src="/assets/images/after-update-number-of-instance-to-delete-82c7f1c197a256a08bd621e106dea366.png"></p><p><strong>After Update Display Angle Dimension</strong></p><p><img alt="after-update-display-angle-dimension" src="/assets/images/after-update-display-angle-dimension-c5549bc4b01f68053a3a486453c020e8.png"></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-9--update-display-number-of-instances"></a>CASE 9 : Update Display Number of Instances<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-9--update-display-number-of-instances" title="Direct link to heading">#</a></h3><p>If we want to update Display Number of Instances, then we need to update value to either <code>True</code> or <code>False</code>.</p><p>In our code, we set this value to <code>True</code> which means we are displaying the Display Number of Instances.</p><p>We update our code for not displaying the Display Number of Instances as given in below code sample.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Edit a Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swSketchManager.EditCircularSketchStepAndRepeat(arcRadius, arcAngle, numberOfInstance, patternSpacing, False, &quot;(3)&quot;, False, False, False, &quot;Arc1_&quot;)</span></div></div></div></div></div><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we update <strong>Display Number of Instances</strong>.</p><p><strong>Before Update Display Number of Instances</strong></p><p><img alt="after-update-number-of-instance-to-delete" src="/assets/images/after-update-number-of-instance-to-delete-82c7f1c197a256a08bd621e106dea366.png"></p><p><strong>After Update Display Number of Instances</strong></p><p><img alt="after-update-display-number-of-instance" src="/assets/images/after-update-display-number-of-instance-530f548b755237d639db2499743c5f7d.png"></p><hr><p><strong>This is it !!!</strong></p><p><em>It is indeed a very LONG post. But I try to update the code and move into the direction where we were able to use these code samples in UserForms.</em></p><p><em>I hope you like my effort!!!</em></p><p>If you found anything to add or update, please let me know on my e-mail.</p><p>Hope this post helps you to <em>Edit a Circular Sketch Pattern</em> with Solidworks VBA Macros.</p><p>For more such tutorials on <strong>Solidworks VBA Macro</strong>, do come to this blog after sometime.</p><p><em>If you like the post then please share it with your friends also.</em></p><p><em>Do let me know by you like this post or not!</em></p><p><em>Till then, Happy learning!!!</em></p></div></article><div class="margin-vert--lg"><nav class="pagination-nav" aria-label="Blog list page navigation"><div class="pagination-nav__item"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Â« Circular Sketch Pattern</div></a></div><div class="pagination-nav__item pagination-nav__item--next"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Move/Copy Sketch Entities Â»</div></a></div></nav></div></div></div><div class="col col--3"><div class="tableOfContents_3SO_"><ul class="table-of-contents table-of-contents__left-border"><li><a href="#code-sample" class="table-of-contents__link">Code Sample</a><ul><li><a href="#understanding-the-code" class="table-of-contents__link">Understanding the Code</a></li></ul></li><li><a href="#cases" class="table-of-contents__link"><strong>Cases</strong></a><ul><li><a href="#case-1--update-arc-radius" class="table-of-contents__link">CASE 1 : Update Arc Radius</a></li><li><a href="#case-2--update-arc-angle" class="table-of-contents__link">CASE 2 : Update Arc Angle</a></li><li><a href="#case-3--update-number-of-instances" class="table-of-contents__link">CASE 3 : Update Number of Instances</a></li><li><a href="#case-4--update-pattern-spacing" class="table-of-contents__link">CASE 4 : Update Pattern Spacing</a></li><li><a href="#case-5--update-display-rotation-of-pattern" class="table-of-contents__link">CASE 5 : Update Display Rotation of Pattern</a></li><li><a href="#case-6--update-number-of-instances-to-delete" class="table-of-contents__link">CASE 6 : Update Number of Instances to Delete</a></li><li><a href="#case-7--update-display-radius-dimension" class="table-of-contents__link">CASE 7 : Update Display Radius Dimension</a></li><li><a href="#case-8--update-display-angle-dimension" class="table-of-contents__link">CASE 8 : Update Display Angle Dimension</a></li><li><a href="#case-9--update-display-number-of-instances" class="table-of-contents__link">CASE 9 : Update Display Number of Instances</a></li></ul></li></ul></div></div></div></div></main></div></div><footer class="footer"><div class="container"><div class="row footer__links"><div class="col footer__col"><h4 class="footer__title">Tutorials</h4><ul class="footer__items"><li class="footer__item"><a class="footer__link-item" href="/docs/vba-Intro">VBA Introduction</a></li><li class="footer__item"><a class="footer__link-item" href="/docs/vba-in-sw">VBA in Solidworks</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">Community</h4><ul class="footer__items"><li class="footer__item"><a href="https://www.facebook.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Facebook</a></li><li class="footer__item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" rel="noopener noreferrer" class="footer__link-item">YouTube</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">More</h4><ul class="footer__items"><li class="footer__item"><a href="mailto:thecadcoder@gmail.com" target="_blank" rel="noopener noreferrer" class="footer__link-item">E-Mail</a></li><li class="footer__item"><a href="https://www.buymeacoffee.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Buy Me a Coffee</a></li></ul></div></div><div class="text--center"><div>Copyright Â© 2020 The Cad Coder, Inc. Built with Docusaurus.</div></div></div></footer></div>
<script src="/styles.49bb2333.js"></script>
<script src="/runtime~main.44b41c7a.js"></script>
<script src="/main.5021cc11.js"></script>
<script src="/1.86ce1451.js"></script>
<script src="/2.4a46354d.js"></script>
<script src="/94.aaa5e340.js"></script>
<script src="/95.e3f7e856.js"></script>
<script src="/f976f453.85830ae4.js"></script>
<script src="/17896441.686270c8.js"></script>
<script src="/af8b4145.0e72ec36.js"></script>
</body>
</html>