<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="generator" content="Docusaurus v2.0.0-alpha.66">
<link rel="preconnect" href="https://www.google-analytics.com">
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-117501871-2","auto"),ga("set","anonymizeIp",!0),ga("send","pageview")</script>
<script async src="https://www.google-analytics.com/analytics.js"></script><title data-react-helmet="true">Move/Copy Sketch Entities | The Cad Coder</title><meta data-react-helmet="true" name="twitter:card" content="summary_large_image"><meta data-react-helmet="true" name="docusaurus_language" content="en"><meta data-react-helmet="true" name="docusaurus_version" content="current"><meta data-react-helmet="true" name="docusaurus_tag" content="docs-default-current"><meta data-react-helmet="true" property="og:title" content="Move/Copy Sketch Entities | The Cad Coder"><meta data-react-helmet="true" name="description" content="In this post, I tell you about how to Move/Copy Sketch Entities using Solidworks VBA Macros in a Sketch."><meta data-react-helmet="true" property="og:description" content="In this post, I tell you about how to Move/Copy Sketch Entities using Solidworks VBA Macros in a Sketch."><meta data-react-helmet="true" property="og:url" content="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities"><link data-react-helmet="true" rel="shortcut icon" href="/img/logo.png"><link data-react-helmet="true" rel="canonical" href="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities"><link rel="stylesheet" href="/styles.f7ef45b3.css">
<link rel="preload" href="/styles.e684f388.js" as="script">
<link rel="preload" href="/runtime~main.bcdc0003.js" as="script">
<link rel="preload" href="/main.2d365058.js" as="script">
<link rel="preload" href="/1.1af7f77d.js" as="script">
<link rel="preload" href="/2.4f0019c3.js" as="script">
<link rel="preload" href="/94.4b40930d.js" as="script">
<link rel="preload" href="/95.2f44d2c3.js" as="script">
<link rel="preload" href="/f976f453.e3619938.js" as="script">
<link rel="preload" href="/17896441.361bff39.js" as="script">
<link rel="preload" href="/853a609d.7bb1c524.js" as="script">
</head>
<body>
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><div aria-label="Navigation bar toggle" class="navbar__toggle" role="button" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></div><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a><div class="navbar__item dropdown dropdown--hoverable dropdown--left"><a class="navbar__item navbar__link">VBA</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li><a class="dropdown__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></div><a class="navbar__item navbar__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a><a class="navbar__item navbar__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></div><div class="navbar__items navbar__items--right"><div class="navbar__item dropdown dropdown--hoverable dropdown--right"><a class="navbar__item navbar__link">About</a><ul class="dropdown__menu"><li><a class="dropdown__link" position="right" href="/docs/about">About Me</a></li><li><a class="dropdown__link" position="right" href="/docs/resources">Resources</a></li><li><a class="dropdown__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></div><div class="react-toggle react-toggle--disabled displayOnlyInLargeViewport_2aTZ"><div class="react-toggle-track"><div class="react-toggle-track-check"><span class="toggle_BsTx">ðŸŒœ</span></div><div class="react-toggle-track-x"><span class="toggle_BsTx">ðŸŒž</span></div></div><div class="react-toggle-thumb"></div><input type="checkbox" disabled="" aria-label="Dark mode toggle" class="react-toggle-screenreader-only"></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div><div class="navbar-sidebar"><div class="navbar-sidebar__brand"><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a></div><div class="navbar-sidebar__items"><div class="menu"><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">VBA</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></li><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">About</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/about">About Me</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/resources">Resources</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></li></ul></div></div></div></nav><div class="main-wrapper"><div class="docPage_2gpo"><div class="docSidebarContainer_3_JD" role="complementary"><div class="sidebar_2urC"><div class="menu menu--responsive menu_5FrY"><button aria-label="Open Menu" aria-haspopup="true" class="button button--secondary button--sm menu__button" type="button"><svg aria-label="Menu" class="sidebarMenuIcon_Dm3K" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 32 32" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">General Functions</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba-in-sw">VBA in Solidworks</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-part">Open new Part document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-asm-and-dwg">Open Assembly and Drawing document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-selection-methods">Selection Methods</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-saved-documents">Open Saved Documents</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue">Fix Unit Issue</a></li></ul></li><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!">Sketch</a><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Lines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-line">Create Line</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerline">Create CenterLine</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Rectangles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-corner-rec">Create Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-center-rec">Create Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-corner-rec">Create 3-Point Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-center-rec">Create 3-Point Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-parallelogram">Create A Parallelogram</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Circles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle">Create Circle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle-by-radius">Create Circle By Radius</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-perimeter-circle">Create Perimeter Circle</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Arcs</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc">Create Centerpoint Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-tangent-arc">Create Tangent Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc">Create 3-Point Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-polygon">Create Polygon</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Slots</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-straight-slot">Create a Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-straight-slot">Create a Centerpoint Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc-slot">Create a 3-Point Arc Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc-slot">Create a Centerpoint Arc Slot</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Splines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-point">Create a Point</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-spline">Create a Spline</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Fillet &amp; Chamfer</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-fillet">Create a Fillet</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-chamfer">Create a Chamfer</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Trim and Extend</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-trim-entities">Trim Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-extend-entities">Extend Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Offset and Mirror</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-offset-entities">Offset Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-mirror-sketch-entities">Mirror Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Patterns</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-linear-sketch-patterm">Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm">Edit Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm">Circular Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern">Edit Circular Sketch Pattern</a></li></ul></li><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!" tabindex="0">Sketch Transformation</a><ul class="menu__list"><li class="menu__list-item"><a aria-current="page" class="menu__link menu__link--active active" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities">Move/Copy Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities">Rotate/Copy Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Relations</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-toggle-sketch-relation">Toggle (Hide/Show) Sketch Relations</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-sketch-relation">Add Sketch Relations (Constraints)</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Others</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-convert-to-construction-sketch">Convert to Construction Sketch</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-split-sketch-entities">Split Open/Closed Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Dimensioning</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-dimension-sketch-entities">Add dimension to Sketch Entities</a></li></ul></li></ul></li></ul></div></div></div><main class="docMainContainer_3EyW"><div class="container padding-vert--lg docItemWrapper_1EkI"><div class="row"><div class="col docItemCol_2ASc"><div class="docItemContainer_3QWW"><article><header><h1 class="docTitle_1Lrw">Move/Copy Sketch Entities</h1></header><div class="markdown"><p>In this post, I tell you about <strong>how to Move/Copy Sketch Entities using Solidworks VBA Macros</strong> in a Sketch.</p><p>In this post, I explain about <code>MoveOrCopy</code> method from <strong>Solidworks</strong> <code>ModelDoc2</code>&#x27;s <code>Extension</code> object.</p><p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>. </p><p>So <strong><em>use this method</em></strong> if you want to <em>MoveOrCopy Sketch Entities</em>.</p><p>This post is similar to previous <strong><a href="/docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern">Solidworks Macro - Edit Circular Sketch Pattern From VBA Macro</a></strong> post.</p><p>If you have not visited my previous <strong><a href="/docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern">Solidworks Macro - Edit Circular Sketch Pattern From VBA Macro</a></strong> post, then please do check-it if you want to learn Editing Circular Sketch Pattern from VBA Macros.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="code-sample"></a>Code Sample<a aria-hidden="true" tabindex="-1" class="hash-link" href="#code-sample" title="Direct link to heading">#</a></h2><p>Below is the <code>code</code> sample to <em>edit Circular Sketch Pattern</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create Variable for Solidworks Sketch Segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchSegment As SldWorks.SketchSegment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Create string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27;-----------------------UNIT CONVERSION----------------------------------------</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Local variables used as Conversion Factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim LengthConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim AngleConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Use a Select Case, to get the length of active Unit and set the different factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Select Case swDoc.GetUnits(0)       &#x27; GetUnits function gives us, active unit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swMETER    &#x27; If length is in Meter</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swMM       &#x27; If length is in MM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 1000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swCM       &#x27; If length is in CM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 100</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swINCHES   &#x27; If length is in INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 * 0.0254</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swFEET     &#x27; If length is in FEET</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 * (0.0254 * 12)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swFEETINCHES     &#x27; If length is in FEET &amp; INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 * 0.0254  &#x27; For length we use sama as Inch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swANGSTROM        &#x27; If length is in ANGSTROM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 10000000000#</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swNANOMETER       &#x27; If length is in NANOMETER</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 1000000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Case swMICRON       &#x27; If length is in MICRON</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      LengthConversionFactor = 1 / 1000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  End Select</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27;----------------------------------------------------------------</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Select Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swSketchManager = swDoc.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Insert a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swSketchManager.InsertSketch True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Circle Radius</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim circleRadius As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  circleRadius = 5 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set Sketch Segment value and Create a Circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, circleRadius)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Defining variables for Destination Co-ordinates</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim destinationCoOrdinateInXDir As Double, destinationCoOrdinateInYDir As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting the values of Destination Co-ordinates in X &amp; Y directions for Move</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  destinationCoOrdinateInXDir = 10 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  destinationCoOrdinateInYDir = 10 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Move circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.Extension.MoveOrCopy False, 1, False, 0, 0, 0, destinationCoOrdinateInXDir, destinationCoOrdinateInYDir, 0</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting the values of Destination Co-ordinates in X &amp; Y directions for Copy</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  destinationCoOrdinateInXDir = 15 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  destinationCoOrdinateInYDir = 15 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Copy circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.Extension.MoveOrCopy True, 3, True, 0, 0, 0, destinationCoOrdinateInXDir, destinationCoOrdinateInYDir, 0</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; De-select the lines after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ClearSelection2 True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Show Front View after Circular Sketch Pattern</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ShowNamedView2 &quot;&quot;, swStandardViews_e.swFrontView</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Zoom to fit screen in Solidworks Window</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ViewZoomtofit2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="understanding-the-code"></a>Understanding the Code<a aria-hidden="true" tabindex="-1" class="hash-link" href="#understanding-the-code" title="Direct link to heading">#</a></h3><p>Now let us walk through <strong>each line</strong> in the above code, and <strong>understand</strong> the meaning and purpose of every line.</p><p>I also give some link so that you can go through them if there are anything I explained in <strong>previous posts</strong>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div></div></div></div></div><p>This line forces us to define every variable we are going to use. </p><p>For more information please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div></div></div></div></div><p>In this line, we create a variable which we named as <code>swApp</code> and the type of this <code>swApp</code> variable is <code>SldWorks.SldWorks</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div></div></div></div></div><p>In this line, we create a variable which we named as <code>swDoc</code> and the type of this <code>swDoc</code> variable is <code>SldWorks.ModelDoc2</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div></div></div></div></div><p>In this line, we create a variable named <code>BoolStatus</code> as <code>Boolean</code> object type.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div></div></div></div></div><p>In above line, we create variable <code>swSketchManager</code> for <strong>Solidworks Sketch Manager</strong>.</p><p>As the name suggested, a <strong>Sketch Manager</strong> holds variours methods and properties to manage <em>Sketches</em>.</p><p>To see methods and properties related to <code>SketchManager</code> object, please visit <strong><a href="/docs/solidworks-macros/help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this page</a></strong>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create variable for Solidworks Sketch Segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchSegment As SldWorks.SketchSegment</span></div></div></div></div></div><p>In this line, we Create a variable which we named as <code>swSketchSegment</code> and the type of this <code>swSketchSegment</code> variable is <code>SldWorks.SketchSegment</code>.</p><p>We create variable <code>swSketchSegment</code> for <strong>Solidworks Sketch Segments</strong>.</p><p>To see methods and properties related to <code>swSketchSegment</code> object, please visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html" target="_blank" rel="noopener noreferrer">this page</a></strong>.</p><p>These all are our global variables.</p><p>As you can see in code sample, they are <strong>Solidworks API Objects</strong>.</p><p>So basically I group all the <strong>Solidworks API Objects</strong> in one place.</p><p>I have also place <code>boolean</code> type object at top also, because after certain point we will <em>need</em> this variable frequently.</p><p>Thus, I have started placing it here.</p><p>Next is our <code>Sub</code> procedure which has name of <code>main</code>. </p><p>This procedure hold all the <em>statements (instructions)</em> we give to computer.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swApp = Application.SldWorks</span></div></div></div></div></div><p>In this line, we set the value of our Solidworks variable <code>swApp</code>; which we define earlier; to Solidworks application.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Create string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div></div></div></div></div><p>In 1st statement of above example, we are defining a variable of <code>string</code> type and named it as <code>defaultTemplate</code>.</p><p>This variable <code>defaultTemplate</code>, hold the location the location of <strong>Default Part Template</strong>.</p><p>In 2nd line of above example. we assign value to our newly define <code>defaultTemplate</code> variable.</p><p>We assign the value by using a <em>Method</em> named <code>GetUserPreferenceStringValue()</code>. </p><p>This <code>GetUserPreferenceStringValue()</code> method is a part of our main Solidworks variable <code>swApp</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div></div></div></div></div><p>In this line, we set the value of our <code>swDoc</code> variable to new document.</p><p>For <strong>detailed information</strong> about these lines please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post.</p><p>I have discussed them <strong>thoroghly</strong> in <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post, so do checkout that post if you want to understand above code in more detail.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27;-----------------------UNIT CONVERSION----------------------------------------</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Local variables used as Conversion Factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim LengthConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim AngleConversionFactor As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Use a Select Case, to get the length of active Unit and set the different factors</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Select Case swDoc.GetUnits(0)       &#x27; GetUnits function gives us, active unit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swMETER    &#x27; If length is in Meter</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swMM       &#x27; If length is in MM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 1000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swCM       &#x27; If length is in CM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 100</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swINCHES   &#x27; If length is in INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 * 0.0254</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swFEET     &#x27; If length is in FEET</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 * (0.0254 * 12)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swFEETINCHES     &#x27; If length is in FEET &amp; INCHES</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 * 0.0254  &#x27; For length we use sama as Inch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swANGSTROM        &#x27; If length is in ANGSTROM</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 10000000000#</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swNANOMETER       &#x27; If length is in NANOMETER</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 1000000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Case swMICRON       &#x27; If length is in MICRON</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    LengthConversionFactor = 1 / 1000000</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    AngleConversionFactor = 1 * 0.01745329</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Select</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27;----------------------------------------------------------------</span></div></div></div></div></div><p>Above code sample shows how to <strong>fix Solidworks API Unit issue</strong>. </p><p>We <em>1st</em> get the <em>current unit</em> of the part and apply the <em>switch</em> statements to update our <em>Length and Angle Conversion factors</em>. </p><p>I have already explained in detail about <strong>Fixing Solidworks API Unit Issue</strong> in <strong><a href="/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue">Fix Unit Issue</a></strong> blog post. </p><p>Do checkout above post for Fixing Solidworks API Issue.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Select Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div></div></div></div></div><p>In above line, we select the <em>front plane</em> by using <code>SelectByID2</code> method from <code>Extension</code> object.</p><p>For more information about selection method please visit <strong><a href="/docs/solidworks-macros/sw-macro-selection-methods">Solidworks Macros - Selection Methods</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchManager = swDoc.SketchManager</span></div></div></div></div></div><p>In above line, we set the <em>Sketch manager</em> variable to <em>current document&#x27;s sketch manager</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Insert a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swSketchManager.InsertSketch True</span></div></div></div></div></div><p>In above line, we use <code>InsertSketch</code> method of <em>SketchManager</em> and give <code>True</code> value.</p><p>This method allows us to insert a sketch in selected plane.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Circle Radius</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim circleRadius As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">circleRadius = 5 * LengthConversionFactor</span></div></div></div></div></div><p>In above code sample, we do following:</p><ol><li><p>Create a local variable named <code>circleRadius</code>, which is <code>Double</code> type.</p></li><li><p>In 2nd line, we assign a value of <strong>5</strong> to our <code>circleRadius</code> variable, also we multiple with our <code>LengthConversionFactor</code> variable.</p></li></ol><p>Since I am using <em>IPS unit system</em>, I want to create a circle of Radius <em>5 inch</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set Sketch Segment value and Create a Circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, circleRadius)</span></div></div></div></div></div><p>In above line, we set the value of Solidworks Sketch Segment variable <code>swSketchSegment</code> by <code>CreateCircleByRadius</code> method from <em>Solidworks Sketch Manager</em>.</p><p>This <code>CreateCircleByRadius</code> method creates <em>a Circle</em> at given point with radius.</p><p>For more information about <code>CreateCircleByRadius</code> method, you can read my <strong><a href="/docs/solidworks-macros/sw-sketch-macro-create-circle-by-radius">Solidworks Macro - Create Circle By Radius From VBA Macro</a></strong> post.</p><p>That post describe all the parameters we need for this <code>CreateCircleByRadius</code> method in details.</p><p>In above line, we create a Circle with:</p><ul><li><p><strong>Circle Centerpoint</strong> : At origin i.e. <em>(0, 0, 0)</em></p></li><li><p><strong>Circle Radius</strong> : <em><code>circleRadius</code></em></p></li></ul><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Defining variables for Destination Co-ordinates</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim destinationCoOrdinateInXDir As Double, destinationCoOrdinateInYDir As Double</span></div></div></div></div></div><p>In above line of code, we create <strong>two</strong> variables of <strong><code>double</code></strong> type in <em>one single line</em>.</p><p>These variables we use for defining <strong>Destination Co-ordinates</strong>.</p><p>Variables Name:</p><ul><li><p><code>destinationCoOrdinateInXDir</code></p></li><li><p><code>destinationCoOrdinateInYDir</code></p></li></ul><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting the values of Destination Co-ordinates in X &amp; Y directions for Move</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">destinationCoOrdinateInXDir = 10 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">destinationCoOrdinateInYDir = 10 * LengthConversionFactor</span></div></div></div></div></div><p>In above line of code, we set the values of <em>Destination Co-ordinates</em> in <strong>X &amp; Y directions</strong> for <strong><em>Move</em></strong> selected circle.</p><p>Variables Values:</p><ul><li><p><code>destinationCoOrdinateInXDir = 10 * LengthConversionFactor</code></p><p><em>10&quot; in X direction.</em></p></li><li><p><code>destinationCoOrdinateInYDir = 10 * LengthConversionFactor</code></p><p><em>10&quot; in Y direction.</em></p></li></ul><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Move circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.Extension.MoveOrCopy False, 1, False, 0, 0, 0, destinationCoOrdinateInXDir, destinationCoOrdinateInYDir, 0</span></div></div></div></div></div><p>For &quot;<strong>Moving</strong>&quot; a sketch entity, we need <code>MoveOrCopy</code> method from <strong>Solidworks</strong> <code>ModelDoc2</code>&#x27;s <code>Extension</code> object.</p><p>This <code>MoveOrCopy</code> method takes following parameters as explained:</p><ul><li><p><strong>Copy</strong> : <em><code>True</code> to copy the sketch entities, <code>False</code> to not.</em></p></li><li><p><strong>NumCopies</strong> : <em>Number of copies you want to create.</em></p></li><li><p><strong>KeepRelations</strong> : <em><code>True</code> to keep sketch relations after Move or Copy operation, <code>False</code> to not.</em></p></li><li><p><strong>BaseX</strong> : <em>X coordinate of the base point from which to move the sketch entities.</em></p></li><li><p><strong>BaseY</strong> : <em>Y coordinate of the base point from which to move the sketch entities.</em></p></li><li><p><strong>BaseZ</strong> : <em>Z coordinate of the base point from which to move the sketch entities.</em></p></li><li><p><strong>DestX</strong> : <em>X coordinate of the destination point from which to move the sketch entities.</em></p></li><li><p><strong>DestY</strong> : <em>Y coordinate of the destination point from which to move the sketch entities.</em></p></li><li><p><strong>DestZ</strong> : <em>Z coordinate of the destination point from which to move the sketch entities.</em></p></li></ul><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>There are no return value after this function.</p></div></div><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="cases"></a><strong>Cases</strong><a aria-hidden="true" tabindex="-1" class="hash-link" href="#cases" title="Direct link to heading">#</a></h2><p>In this section, we will go through different cases by </p><ul><li><p><em>Modifying different parameters</em></p></li><li><p><em>See images, before and after parameter modification</em></p></li></ul><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-1--move-sketch-entities"></a>CASE 1 : Move Sketch Entities<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-1--move-sketch-entities" title="Direct link to heading">#</a></h3><p>In our code, if we want to <em>Move Sketch Entities</em>, then we need to use code sample as given below:</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Defining variables for Destination Co-ordinates</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim destinationCoOrdinateInXDir As Double, destinationCoOrdinateInYDir As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting the values of Destination Co-ordinates in X &amp; Y directions for Move</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">destinationCoOrdinateInXDir = 10 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">destinationCoOrdinateInYDir = 10 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Move circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.Extension.MoveOrCopy False, 1, False, 0, 0, 0, destinationCoOrdinateInXDir, destinationCoOrdinateInYDir, 0</span></div></div></div></div></div><p>In above line we <strong>Move Sketch Entities</strong> to new position i.e. <em>10&quot; in X-Direction</em> and <em>10&quot; in Y-Direction</em>.</p><p>In above code we need to set following parameters:</p><ul><li><p><strong>Copy</strong> : <code>False</code> to not create a copy.</p></li><li><p><strong>NumCopies</strong> : <em>Number of copies you want to create to 1 which is itself.</em></p></li><li><p><strong>KeepRelations</strong> : <em><code>True</code> to keep sketch relations after Move or Copy operation.</em></p></li><li><p><strong>BaseX</strong> : <em>X coordinate of the base point  = 0</em></p></li><li><p><strong>BaseY</strong> : <em>Y coordinate of the base point  = 0</em></p></li><li><p><strong>BaseZ</strong> : <em>Z coordinate of the base point  = 0</em></p></li><li><p><strong>DestX</strong> : <em>X coordinate of the destination  = 10&quot;</em></p></li><li><p><strong>DestY</strong> : <em>Y coordinate of the destination point  = 10&quot;</em></p></li><li><p><strong>DestZ</strong> : <em>Z coordinate of the destination point  = 0</em>  </p></li></ul><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we <strong>Move Sketch Entitny</strong>.</p><p><strong>Before Move Sketch Entitny</strong></p><p><img alt="before-move-copy" src="/assets/images/before-move-copy-fa58f30c9f52032cb6c96598e57f3d18.png"></p><p><strong>After Move Sketch Entitny</strong></p><p><img alt="after-move" src="/assets/images/after-move-27e66d1e2bad407f7fe9ba7a152aa6d0.png"></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="case-2--copy-sketch-entities"></a>CASE 2 : Copy Sketch Entities<a aria-hidden="true" tabindex="-1" class="hash-link" href="#case-2--copy-sketch-entities" title="Direct link to heading">#</a></h3><p>In our code, if we want to <em>Copy Sketch Entities</em>, then we need to use code sample as given below:</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Defining variables for Destination Co-ordinates</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim destinationCoOrdinateInXDir As Double, destinationCoOrdinateInYDir As Double</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting the values of Destination Co-ordinates in X &amp; Y directions for Move</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">destinationCoOrdinateInXDir = 15 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">destinationCoOrdinateInYDir = 15 * LengthConversionFactor</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Copy circle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.Extension.MoveOrCopy True, 3, True, 0, 0, 0, destinationCoOrdinateInXDir, destinationCoOrdinateInYDir, 0</span></div></div></div></div></div><p>In above line we <strong>Copy Sketch Entities</strong> to new position i.e. <em>15&quot; in X-Direction</em> and <em>15&quot; in Y-Direction</em> for every copy of sketch.</p><p>This will more clear in below images when you scroll down.</p><p>In above code we need to set following parameters:</p><ul><li><p><strong>Copy</strong> : <code>True</code> to create a copy.</p></li><li><p><strong>NumCopies</strong> : <em>Number of copies we want to create: 3</em></p></li><li><p><strong>KeepRelations</strong> : <em><code>True</code> to keep sketch relations after Move or Copy operation.</em></p></li><li><p><strong>BaseX</strong> : <em>X coordinate of the base point  = 0</em></p></li><li><p><strong>BaseY</strong> : <em>Y coordinate of the base point  = 0</em></p></li><li><p><strong>BaseZ</strong> : <em>Z coordinate of the base point  = 0</em></p></li><li><p><strong>DestX</strong> : <em>X coordinate of the destination  = 15&quot;</em></p></li><li><p><strong>DestY</strong> : <em>Y coordinate of the destination point  = 15&quot;</em></p></li><li><p><strong>DestZ</strong> : <em>Z coordinate of the destination point  = 0</em>  </p></li></ul><p><strong><em>Example Images:</em></strong></p><p>Below image shows before and after we <strong>Copy Sketch Entitny</strong>.</p><p><strong>Before Copy Sketch Entitny</strong></p><p><img alt="before-move-copy" src="/assets/images/before-move-copy-fa58f30c9f52032cb6c96598e57f3d18.png"></p><p><strong>After Copy Sketch Entitny</strong></p><p><img alt="after-copy" src="/assets/images/after-copy-9d61c3d0aa475413ab7efa46be542142.png"></p><hr><p><strong>This is it !!!</strong></p><p><em>I hope my efforts will helpful to someone!</em></p><p>If you found anything to <strong>add or update</strong>, please let me know on my <em>e-mail</em>.</p><p>Hope this post helps you to <em>Move/Copy Sketch Entities</em> with Solidworks VBA Macros.</p><p>For more such tutorials on <strong>Solidworks VBA Macro</strong>, do come to this blog after sometime.</p><p><em>If you like the post then please share it with your friends also.</em></p><p><em>Do let me know by you like this post or not!</em></p><p><em>Till then, Happy learning!!!</em></p></div></article><div class="margin-vert--lg"><nav class="pagination-nav" aria-label="Blog list page navigation"><div class="pagination-nav__item"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Â« Edit Circular Sketch Pattern</div></a></div><div class="pagination-nav__item pagination-nav__item--next"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Rotate/Copy Sketch Entities Â»</div></a></div></nav></div></div></div><div class="col col--3"><div class="tableOfContents_3SO_"><ul class="table-of-contents table-of-contents__left-border"><li><a href="#code-sample" class="table-of-contents__link">Code Sample</a><ul><li><a href="#understanding-the-code" class="table-of-contents__link">Understanding the Code</a></li></ul></li><li><a href="#cases" class="table-of-contents__link"><strong>Cases</strong></a><ul><li><a href="#case-1--move-sketch-entities" class="table-of-contents__link">CASE 1 : Move Sketch Entities</a></li><li><a href="#case-2--copy-sketch-entities" class="table-of-contents__link">CASE 2 : Copy Sketch Entities</a></li></ul></li></ul></div></div></div></div></main></div></div><footer class="footer"><div class="container"><div class="row footer__links"><div class="col footer__col"><h4 class="footer__title">Tutorials</h4><ul class="footer__items"><li class="footer__item"><a class="footer__link-item" href="/docs/vba-Intro">VBA Introduction</a></li><li class="footer__item"><a class="footer__link-item" href="/docs/vba-in-sw">VBA in Solidworks</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">Community</h4><ul class="footer__items"><li class="footer__item"><a href="https://www.facebook.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Facebook</a></li><li class="footer__item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" rel="noopener noreferrer" class="footer__link-item">YouTube</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">More</h4><ul class="footer__items"><li class="footer__item"><a href="mailto:thecadcoder@gmail.com" target="_blank" rel="noopener noreferrer" class="footer__link-item">E-Mail</a></li><li class="footer__item"><a href="https://www.buymeacoffee.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Buy Me a Coffee</a></li></ul></div></div><div class="text--center"><div>Copyright Â© 2020 The Cad Coder, Inc. Built with Docusaurus.</div></div></div></footer></div>
<script src="/styles.e684f388.js"></script>
<script src="/runtime~main.bcdc0003.js"></script>
<script src="/main.2d365058.js"></script>
<script src="/1.1af7f77d.js"></script>
<script src="/2.4f0019c3.js"></script>
<script src="/94.4b40930d.js"></script>
<script src="/95.2f44d2c3.js"></script>
<script src="/f976f453.e3619938.js"></script>
<script src="/17896441.361bff39.js"></script>
<script src="/853a609d.7bb1c524.js"></script>
</body>
</html>