<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- begin _includes/seo.html -->
  <title>SOLIDWORKS C# API - Create Line Code Refactor - The CAD Coder</title>
  <meta name="description" content="Objective">



  <meta property="og:type" content="article">
  <meta property="og:locale" content="en_US">
  <meta property="og:site_name" content="The CAD Coder">
  <meta property="og:title" content="SOLIDWORKS C# API - Create Line Code Refactor">
  <meta property="og:url" content="https://thecadcoder.com/solidworks-csharp/create-line-code-refactor/">


  <meta property="og:description" content="Objective">







  <meta property="article:published_time" content="2025-03-01T08:06:43-05:00">






  <link rel="canonical" href="https://thecadcoder.com/solidworks-csharp/create-line-code-refactor/">




  <script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": null,
      "url": "https://thecadcoder.com/"
    
  }
</script>







  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117501871-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'UA-117501871-2', { 'anonymize_ip': true });
  </script>

  <!-- end _includes/seo.html -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">
  <link href="/feed.xml" type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/main.css">

  <meta name="google-site-verification" content="OeSBbUv_kXDkDxaeoLixjE1BYxlbQRINt58H1UGbSMY" />


</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
      <img src="/assets/logo.png" width="30" height="30" class="img-fluid" alt="">
      <span>The CAD Coder</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="/vba/vba-Introduction/"><span>VBA</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/Solidworks-macro-guide/"><span>Solidworks VBA Macro</span></a>
        </li>


        <li class="nav-item">
          <a class="active nav-link" style="border-bottom: 1px solid #fff;"
            href="/Solidworks-csharp-api-tutorials/"><span>Solidworks C# API</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/Solidworks-cpp-api-tutorials/"><span>Solidworks C++ API</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/wpf-tutorials/syncfusion-account-signup/"><span>WPF Tutorials</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/knowledge-base/introduction/"><span>My Knowledge Base</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/resources/"><span>Resources</span></a>
        </li>


        <li class="nav-item">
          <a class="nav-link" href="/aboutMe/"><span>About</span></a>
        </li>

        <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li> -->
      </ul>
      <!-- <a class="btn btn-outline-success my-2 my-sm-0" href="/seach-document/" role="button">
            <i class="fas fa-search"></i>
        </a> -->
    </div>
  </nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-lg-2 col-sm-4">
        <div class="sidebar sticky" style="width: 100%;">











          <nav class="nav__list">

            <input id="ac-toc" name="accordion-toc" type="checkbox" />
            <label for="ac-toc">Toggle Menu</label>
            <ul class="nav__items">

              <li>

                <span class="nav__sub-title">Getting Started</span>



                <ul>

                  <li><a href="/Solidworks-csharp-api-tutorials/">Introduction</a></li>

                  <li><a href="/solidworks-csharp/Prerequisite/">Prerequisite</a></li>

                  <li><a href="/solidworks-csharp/open-solidworks/">Open Solidworks</a></li>

                  <li><a href="/solidworks-csharp/open-solidworks-document/">Open Solidworks Document</a></li>

                  <li><a href="/solidworks-csharp/browse-and-open-solidworks-file/">Browse/Open SOLIDWORKS Document</a>
                  </li>

                  <li><a href="/solidworks-csharp/unit-correction/">Fix Unit Issue</a></li>

                </ul>

              </li>

              <li>

                <span class="nav__sub-title">Sketch Segment</span>



                <ul>

                  <li><a href="/solidworks-csharp/insert-sketch/">Insert Solidworks Sketch</a></li>

                  <li><a href="/solidworks-csharp/edit-sketch/">Edit Solidworks Sketch</a></li>

                  <li><a href="/solidworks-csharp/edit-solidworks-feature-sketch/">Edit Solidworks Feature Sketch</a>
                  </li>

                  <li><a href="/solidworks-csharp/change-sketch-name/">Change Sketch Name</a></li>

                  <li><a href="/solidworks-csharp/delete-selected-sketch/">Delete Selected Sketch</a></li>

                </ul>

              </li>

              <li>

                <span class="nav__sub-title">Sketch Lines</span>



                <ul>

                  <li><a href="/solidworks-csharp/create-line/">Create Line</a></li>

                  <li><a href="/solidworks-csharp/create-line-code-refactor/" class="active">Create Line Code
                      Refactor</a></li>

                  <li><a href="/solidworks-csharp/setup-test-project/">Setup Test Project</a></li>

                  <li><a href="/solidworks-csharp/test-createLine-method/">Test Create Line Method</a></li>

                  <li><a href="/solidworks-csharp/test-applyunitconversion-method/">Test ApplyUnitConversion Method</a>
                  </li>

                  <li><a href="/solidworks-csharp/test-SelectSketchPlane-method/">Test SelectSketchPlane Method</a></li>

                </ul>

              </li>

              <li>

                <span class="nav__sub-title">Others</span>



                <ul>

                  <li><a href="/solidworks-csharp/update-dimension-state/">Update Dimension State</a></li>

                </ul>

              </li>

            </ul>
          </nav>



        </div>

      </div>
      <div class="col-md-9 col-lg-10 col-sm-8">
        <div>
          <div id="main" role="main">

            <article class="page" itemscope itemtype="https://schema.org/CreativeWork">

              <meta itemprop="headline" content="SOLIDWORKS C# API - Create Line Code Refactor">

              <meta itemprop="description" content="Objective">


              <meta itemprop="datePublished" content="2025-03-01T08:06:43-05:00">


              <div class="page__inner-wrap">

                <header>
                  <h1 id="page-title" class="page__title" itemprop="headline">SOLIDWORKS C# API - Create Line Code
                    Refactor
                  </h1>


                  <p class="page__meta">








                    <span class="page__meta-readtime">
                      <i class="far fa-clock" aria-hidden="true"></i>

                      7 minute read

                    </span>

                  </p>


                </header>


                <section class="page__content" itemprop="text">

                  <aside class="sidebar__right sticky">
                    <nav class="toc">
                      <header>
                        <h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4>
                      </header>
                      <ul class="toc__menu">
                        <li><a href="#objective">Objective</a></li>
                        <li><a href="#demo-video">Demo Video</a></li>
                        <li><a href="#code-overview-and-summary">Code Overview and Summary</a></li>
                        <li><a href="#create-interface">Create Interface</a></li>
                        <li><a href="#register-interface">Register Interface</a></li>
                        <li><a href="#update-mainwindowviewmodel">Update MainWindowViewModel</a>
                          <ul>
                            <li><a href="#properties-update">Properties Update</a></li>
                            <li><a href="#constructor-parameters-update">Constructor Parameters Update</a></li>
                            <li><a href="#private-fields-update">Private Fields Update</a></li>
                          </ul>
                        </li>
                        <li><a href="#update-method---createlinemethod">Update Method - CreateLineMethod</a>
                          <ul>
                            <li><a href="#purpose">Purpose</a></li>
                            <li><a href="#return-type">Return Type</a></li>
                            <li><a href="#flowsummary">Flow/Summary</a></li>
                          </ul>
                        </li>
                        <li><a href="#create-method---createsolidworksinstance">Create Method -
                            CreateSolidworksInstance</a>
                          <ul>
                            <li><a href="#purpose-1">Purpose</a></li>
                            <li><a href="#return-type-1">Return Type</a></li>
                            <li><a href="#flowsummary-1">Flow/Summary</a></li>
                          </ul>
                        </li>
                        <li><a href="#create-method---createpartdocument">Create Method - CreatePartDocument</a>
                          <ul>
                            <li><a href="#purpose-2">Purpose</a></li>
                            <li><a href="#return-type-2">Return Type</a></li>
                            <li><a href="#flowsummary-2">Flow/Summary</a></li>
                          </ul>
                        </li>
                        <li><a href="#create-method---selectsketchplane">Create Method - SelectSketchPlane</a>
                          <ul>
                            <li><a href="#purpose-3">Purpose</a></li>
                            <li><a href="#return-type-3">Return Type</a></li>
                            <li><a href="#flowsummary-3">Flow/Summary</a></li>
                          </ul>
                        </li>
                        <li><a href="#create-method---applyunitconversion">Create Method - ApplyUnitConversion</a>
                          <ul>
                            <li><a href="#purpose-4">Purpose</a></li>
                            <li><a href="#return-type-4">Return Type</a></li>
                            <li><a href="#flowsummary-4">Flow/Summary</a></li>
                          </ul>
                        </li>
                        <li><a href="#create-method---createline">Create Method - CreateLine</a>
                          <ul>
                            <li><a href="#purpose-5">Purpose</a></li>
                            <li><a href="#return-type-5">Return Type</a></li>
                            <li><a href="#flowsummary-5">Flow/Summary</a></li>
                          </ul>
                        </li>
                      </ul>

                      <br />
                      <script async
                        src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
                        crossorigin="anonymous"></script>
                      <!-- Vertical Ads -->
                      <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002"
                        data-ad-slot="4311368222" data-ad-format="auto" data-full-width-responsive="true"></ins>
                      <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                      </script>
                    </nav>
                  </aside>

                  <div>
                    <script async
                      src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
                      crossorigin="anonymous"></script>
                    <!-- Horizontal Ads -->
                    <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002"
                      data-ad-slot="6007593278" data-ad-format="auto" data-full-width-responsive="true"></ins>
                    <script>
                      (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                    <h2 id="objective">Objective</h2>

                    <p>I want to:</p>

                    <ul>
                      <li><em>Refactor <strong><code
                              class="language-plaintext highlighter-rouge">CreateLineMethod</code></strong> function for
                          unit testing compatible.</em></li>
                      <li><em>Add unit test cases into our solution to make our code testable.</em></li>
                      <li><em>We will continue from previous article üöÄ <strong><a
                              href="/solidworks-csharp/create-line/" target="_blank">Create Line</a></strong></em>.</li>
                      <li><em>I will not explain each line, since they are already explained in previous articles.</em>
                      </li>
                    </ul>

                    <hr />

                    <h2 id="demo-video">Demo Video</h2>

                    <p>Watch the video below to learn how to refactor the <strong><code
                          class="language-plaintext highlighter-rouge">CreateLineMethod</code></strong> function.</p>

                    <iframe src="https://www.youtube.com/embed/S3L8ngOyEMc" frameborder="0" allowfullscreen=""></iframe>
                    <p><br /></p>

                    <p class="notice--info">Please note that there are <strong>no explanation</strong> in the
                      video.<br />
                      <strong>Explanation</strong> of each step and why we write code this way is given in this post.
                    </p>

                    <hr />

                    <h2 id="code-overview-and-summary">Code Overview and Summary</h2>

                    <p>The code comprises several functions working together to create a sketch line.
                      Each function has a specific responsibility:</p>

                    <ul>
                      <li>Create <strong><code class="language-plaintext highlighter-rouge">Interface</code></strong>
                        and register them.</li>
                      <li><strong><code class="language-plaintext highlighter-rouge">CreateLineMethod</code></strong>
                        acts as the entry point, coordinating other functions.</li>
                      <li><strong><code
                            class="language-plaintext highlighter-rouge">CreateSolidworksInstance</code></strong>
                        ensures SolidWorks is running and prepares the application.</li>
                      <li><strong><code class="language-plaintext highlighter-rouge">CreatePartDocument</code></strong>
                        creates a new part document in SolidWorks.</li>
                      <li><strong><code class="language-plaintext highlighter-rouge">SelectSketchPlane</code></strong>
                        selects a plane for sketching.</li>
                      <li><strong><code class="language-plaintext highlighter-rouge">ApplyUnitConversion</code></strong>
                        converts points using the correct length units.</li>
                      <li><strong><code class="language-plaintext highlighter-rouge">CreateLine</code></strong> draws
                        the line based on the converted points.</li>
                    </ul>

                    <p>Below is a detailed breakdown of each function.</p>

                    <hr />

                    <h2 id="create-interface">Create <code class="language-plaintext highlighter-rouge">Interface</code>
                    </h2>

                    <ul>
                      <li>First we need to create a folder in our solution.</li>
                      <li>Name of folder: <code class="language-plaintext highlighter-rouge">Interface</code></li>
                    </ul>

                    <p><a href="/assets/solidworks-csharp-images/create-line-code-refactor/create-folder.png"><img
                          src="/assets/solidworks-csharp-images/create-line-code-refactor/create-folder.png"
                          alt="create-folder" /></a></p>

                    <ul>
                      <li>Inside this folder create 2 <code
                          class="language-plaintext highlighter-rouge">Interface</code>
                        <ul>
                          <li><strong><code class="language-plaintext highlighter-rouge">IPointViewModel</code></strong>
                          </li>
                          <li><strong><code
                                class="language-plaintext highlighter-rouge">IUnitConversionHelper</code></strong></li>
                        </ul>
                      </li>
                      <li><strong><code class="language-plaintext highlighter-rouge">IPointViewModel</code></strong>
                        code as shown below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">namespace</span> <span class="nn">SolidworksTest.Interfaces</span><span class="p">;</span>

<span class="k">public</span> <span class="k">interface</span> <span class="nc">IPointViewModel</span>
<span class="p">{</span>
  <span class="kt">string</span> <span class="n">Header</span> <span class="p">{</span> <span class="k">get</span><span class="p">;</span> <span class="k">set</span><span class="p">;</span> <span class="p">}</span>
  <span class="kt">double</span> <span class="n">XPoint</span> <span class="p">{</span> <span class="k">get</span><span class="p">;</span> <span class="k">set</span><span class="p">;</span> <span class="p">}</span>
  <span class="kt">double</span> <span class="n">YPoint</span> <span class="p">{</span> <span class="k">get</span><span class="p">;</span> <span class="k">set</span><span class="p">;</span> <span class="p">}</span>
  <span class="kt">double</span> <span class="n">ZPoint</span> <span class="p">{</span> <span class="k">get</span><span class="p">;</span> <span class="k">set</span><span class="p">;</span> <span class="p">}</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <ul>
                      <li><strong><code
                            class="language-plaintext highlighter-rouge">IUnitConversionHelper</code></strong> code as
                        shown below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">using</span> <span class="nn">SwConst</span><span class="p">;</span>

<span class="k">namespace</span> <span class="nn">SolidworksTest.Interfaces</span><span class="p">;</span>

<span class="k">public</span> <span class="k">interface</span> <span class="nc">IUnitConversionHelper</span>
<span class="p">{</span>
  <span class="kt">double</span> <span class="n">AngleConversionFactor</span> <span class="p">{</span> <span class="k">get</span><span class="p">;</span> <span class="k">set</span><span class="p">;</span> <span class="p">}</span>
  <span class="kt">double</span> <span class="n">LengthConversionFactor</span> <span class="p">{</span> <span class="k">get</span><span class="p">;</span> <span class="k">set</span><span class="p">;</span> <span class="p">}</span>

  <span class="k">void</span> <span class="nf">UnitConversion</span><span class="p">(</span><span class="n">swLengthUnit_e</span> <span class="n">swUnit</span><span class="p">);</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <hr />

                    <h2 id="register-interface">Register <code
                        class="language-plaintext highlighter-rouge">Interface</code></h2>

                    <ul>
                      <li>Open <strong><code class="language-plaintext highlighter-rouge">App.xaml.cs</code></strong> as
                        shown below:</li>
                    </ul>

                    <p><a href="/assets/solidworks-csharp-images/create-line-code-refactor/open-app-cs-file.png"><img
                          src="/assets/solidworks-csharp-images/create-line-code-refactor/open-app-cs-file.png"
                          alt="open-app-cs-file" /></a></p>

                    <ul>
                      <li>Update <strong><code
                            class="language-plaintext highlighter-rouge">RegisterTypes</code></strong> function as shown
                        below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">protected</span> <span class="k">override</span> <span class="k">void</span> <span class="nf">RegisterTypes</span><span class="p">(</span><span class="n">IContainerRegistry</span> <span class="n">containerRegistry</span><span class="p">)</span>
<span class="p">{</span>
  <span class="n">containerRegistry</span><span class="p">.</span><span class="n">Register</span><span class="p">&lt;</span><span class="n">IPointViewModel</span><span class="p">,</span><span class="n">PointViewModel</span><span class="p">&gt;();</span>
  <span class="n">containerRegistry</span><span class="p">.</span><span class="n">Register</span><span class="p">&lt;</span><span class="n">IUnitConversionHelper</span><span class="p">,</span> <span class="n">UnitConversionHelper</span><span class="p">&gt;();</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <ul>
                      <li>In above code, we register <strong><code
                            class="language-plaintext highlighter-rouge">IPointViewModel</code></strong> into <strong>DI
                          container</strong>.</li>
                      <li>When we asked to create object for <strong><code
                            class="language-plaintext highlighter-rouge">IPointViewModel</code></strong> interface, it
                        will create <strong><code
                            class="language-plaintext highlighter-rouge">PointViewModel</code></strong> type object.
                      </li>
                      <li>Same goes for <strong><code
                            class="language-plaintext highlighter-rouge">IUnitConversionHelper</code></strong>
                        interface.</li>
                      <li>If we asked to create object for <strong><code
                            class="language-plaintext highlighter-rouge">IUnitConversionHelper</code></strong>
                        interface, it will create <strong><code
                            class="language-plaintext highlighter-rouge">UnitConversionHelper</code></strong> type
                        object.</li>
                    </ul>

                    <hr />

                    <h2 id="update-mainwindowviewmodel">Update <code
                        class="language-plaintext highlighter-rouge">MainWindowViewModel</code></h2>

                    <p>In MainWindowViewModel, we need to update 2 things:</p>

                    <ol>
                      <li>Properties</li>
                      <li>Constructor Parameters</li>
                      <li>Private Fields</li>
                    </ol>

                    <h3 id="properties-update">Properties Update</h3>

                    <ul>
                      <li>Now we need to update <strong><code
                            class="language-plaintext highlighter-rouge">MainWindowViewModel</code></strong>.</li>
                      <li>Update <em>type</em> of <strong><code
                            class="language-plaintext highlighter-rouge">StartPointViewModel</code></strong> and
                        <strong><code class="language-plaintext highlighter-rouge">EndPointViewModel</code></strong>
                        properties.
                        <ul>
                          <li><strong>Old Type</strong>: <strong><code
                                class="language-plaintext highlighter-rouge">PointViewModel</code></strong></li>
                          <li><strong>New Type</strong>: <strong><code
                                class="language-plaintext highlighter-rouge">IPointViewModel</code></strong></li>
                        </ul>
                      </li>
                      <li>Update the code as shown below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">private</span> <span class="n">IPointViewModel</span> <span class="n">_startPointViewModel</span><span class="p">;</span>
<span class="k">public</span> <span class="n">IPointViewModel</span> <span class="n">StartPointViewModel</span>
<span class="p">{</span>
  <span class="k">get</span> <span class="p">{</span> <span class="k">return</span> <span class="n">_startPointViewModel</span><span class="p">;</span> <span class="p">}</span>
  <span class="k">set</span> <span class="p">{</span> <span class="nf">SetProperty</span><span class="p">(</span><span class="k">ref</span> <span class="n">_startPointViewModel</span><span class="p">,</span> <span class="k">value</span><span class="p">);</span> <span class="p">}</span>
<span class="p">}</span>

<span class="k">private</span> <span class="n">IPointViewModel</span> <span class="n">_endpointViewModel</span><span class="p">;</span>
<span class="k">public</span> <span class="n">IPointViewModel</span> <span class="n">EndPointViewModel</span>
<span class="p">{</span>
  <span class="k">get</span> <span class="p">{</span> <span class="k">return</span> <span class="n">_endpointViewModel</span><span class="p">;</span> <span class="p">}</span>
  <span class="k">set</span> <span class="p">{</span> <span class="nf">SetProperty</span><span class="p">(</span><span class="k">ref</span> <span class="n">_endpointViewModel</span><span class="p">,</span> <span class="k">value</span><span class="p">);</span> <span class="p">}</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <ul>
                      <li>
                        <p>Now in <strong><code
                              class="language-plaintext highlighter-rouge">MainWindowViewModel</code></strong>
                          constructor, we need to create <strong>object</strong> for these properties using
                          <strong>DI</strong>.</p>
                      </li>
                      <li>
                        <p>Please see below code for reference.</p>
                      </li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">public</span> <span class="nf">MainWindowViewModel</span><span class="p">(</span><span class="n">IEventAggregator</span> <span class="n">eventAggregator</span><span class="p">,</span> <span class="n">IContainerProvider</span> <span class="n">container</span><span class="p">)</span>
<span class="p">{</span>
  <span class="k">this</span><span class="p">.</span><span class="n">eventAggregator</span> <span class="p">=</span> <span class="n">eventAggregator</span><span class="p">;</span>
  <span class="k">this</span><span class="p">.</span><span class="n">container</span> <span class="p">=</span> <span class="n">container</span><span class="p">;</span>

  <span class="n">StartPointViewModel</span> <span class="p">=</span> <span class="k">this</span><span class="p">.</span><span class="n">container</span><span class="p">.</span><span class="n">Resolve</span><span class="p">&lt;</span><span class="n">IPointViewModel</span><span class="p">&gt;();</span>
  <span class="n">EndPointViewModel</span> <span class="p">=</span> <span class="k">this</span><span class="p">.</span><span class="n">container</span><span class="p">.</span><span class="n">Resolve</span><span class="p">&lt;</span><span class="n">IPointViewModel</span><span class="p">&gt;();</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <p>In above code, below lines are responsibile for create objects for <strong><code
                          class="language-plaintext highlighter-rouge">StartPointViewModel</code></strong> and
                      <strong><code class="language-plaintext highlighter-rouge">EndPointViewModel</code></strong>
                      properties.</p>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="n">StartPointViewModel</span> <span class="p">=</span> <span class="k">this</span><span class="p">.</span><span class="n">container</span><span class="p">.</span><span class="n">Resolve</span><span class="p">&lt;</span><span class="n">IPointViewModel</span><span class="p">&gt;();</span>
<span class="n">EndPointViewModel</span> <span class="p">=</span> <span class="k">this</span><span class="p">.</span><span class="n">container</span><span class="p">.</span><span class="n">Resolve</span><span class="p">&lt;</span><span class="n">IPointViewModel</span><span class="p">&gt;();</span>
</code></pre>
                      </div>
                    </div>

                    <hr />

                    <h3 id="constructor-parameters-update">Constructor Parameters Update</h3>

                    <ul>
                      <li>We need additional parameter in our MainWindowViewModel Constructor and assign it to a private
                        field.</li>
                      <li>Additiona Parameter: IUnitConversionHelper</li>
                      <li>Please see below code for reference.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">public</span> <span class="n">IUnitConversionHelper</span> <span class="n">conversionHelper</span><span class="p">;</span>

<span class="k">public</span> <span class="nf">MainWindowViewModel</span><span class="p">(</span><span class="n">IEventAggregator</span> <span class="n">eventAggregator</span><span class="p">,</span> <span class="n">IContainerProvider</span> <span class="n">container</span><span class="p">,</span> <span class="n">IUnitConversionHelper</span> <span class="n">conversionHelper</span><span class="p">)</span>
<span class="p">{</span>
  <span class="k">this</span><span class="p">.</span><span class="n">eventAggregator</span> <span class="p">=</span> <span class="n">eventAggregator</span><span class="p">;</span>
  <span class="k">this</span><span class="p">.</span><span class="n">container</span> <span class="p">=</span> <span class="n">container</span><span class="p">;</span>

  <span class="n">StartPointViewModel</span> <span class="p">=</span> <span class="k">this</span><span class="p">.</span><span class="n">container</span><span class="p">.</span><span class="n">Resolve</span><span class="p">&lt;</span><span class="n">IPointViewModel</span><span class="p">&gt;();</span>
  <span class="n">EndPointViewModel</span> <span class="p">=</span> <span class="k">this</span><span class="p">.</span><span class="n">container</span><span class="p">.</span><span class="n">Resolve</span><span class="p">&lt;</span><span class="n">IPointViewModel</span><span class="p">&gt;();</span>
  <span class="k">this</span><span class="p">.</span><span class="n">conversionHelper</span> <span class="p">=</span> <span class="n">conversionHelper</span><span class="p">;</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <p>In above code, please note following.</p>

                    <ul>
                      <li><strong>Input Parameter</strong>: <strong><code
                            class="language-plaintext highlighter-rouge">IUnitConversionHelper conversionHelper</code></strong>
                      </li>
                      <li><strong>Private Field</strong>: <strong><code
                            class="language-plaintext highlighter-rouge">this.conversionHelper</code></strong></li>
                    </ul>

                    <hr />

                    <h3 id="private-fields-update">Private Fields Update</h3>

                    <ul>
                      <li>Now we need to remove some <strong>private fields</strong>.</li>
                      <li>Those fields are listed below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">private</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span> <span class="n">swApp</span><span class="p">;</span>
<span class="k">private</span> <span class="n">ModelDoc2</span> <span class="n">swDoc</span><span class="p">;</span>
</code></pre>
                      </div>
                    </div>

                    <ul>
                      <li>These variables we will use create directly in our functions.</li>
                    </ul>

                    <hr />

                    <h2 id="update-method---createlinemethod">Update Method - CreateLineMethod</h2>

                    <ul>
                      <li>Now we need to update <strong><code
                            class="language-plaintext highlighter-rouge">CreateLineMethod()</code></strong> method as
                        shown below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">public</span> <span class="kt">bool</span> <span class="nf">CreateLineMethod</span><span class="p">()</span>
<span class="p">{</span>
  <span class="n">ModelDoc2</span> <span class="n">swDoc</span><span class="p">;</span>
  <span class="k">if</span> <span class="p">(</span><span class="nf">CreateSolidworksInstance</span><span class="p">(</span><span class="k">out</span> <span class="n">swDoc</span><span class="p">)</span> <span class="p">==</span> <span class="k">false</span><span class="p">)</span>
    <span class="k">return</span> <span class="k">false</span><span class="p">;</span>
  
  <span class="n">swDoc</span><span class="p">.</span><span class="nf">ClearSelection2</span><span class="p">(</span><span class="k">true</span><span class="p">);</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="nf">ViewZoomtofit2</span><span class="p">();</span>
  <span class="n">messageToShow</span> <span class="p">=</span> <span class="s">"Sketch line successfully created."</span><span class="p">;</span>
  <span class="k">return</span> <span class="k">true</span><span class="p">;</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <h3 id="purpose">Purpose</h3>

                    <ul>
                      <li><strong><code class="language-plaintext highlighter-rouge">CreateLineMethod()</code></strong>
                        method‚Äôs purpose is to <em>create a line in a SolidWorks document</em>.</li>
                      <li>While the code for drawing the line isn‚Äôt shown.</li>
                      <li>It prepares <em>a SolidWorks instance, clears any selections, and adjusts the view.</em></li>
                    </ul>

                    <h3 id="return-type">Return Type</h3>

                    <ul>
                      <li>The <strong><code
                            class="language-plaintext highlighter-rouge">CreateLineMethod()</code></strong> method
                        returns a <strong><code class="language-plaintext highlighter-rouge">bool</code></strong>
                        (Boolean value) ‚Äî <strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong> or <strong><code
                            class="language-plaintext highlighter-rouge">false</code></strong>.</li>
                      <li>This return type usually indicates <em>success</em> (<strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong>) or <em>failure</em>
                        (<strong><code class="language-plaintext highlighter-rouge">false</code></strong>) of the
                        method.</li>
                    </ul>

                    <h3 id="flowsummary">Flow/Summary</h3>

                    <ul>
                      <li>Calls <strong><code
                            class="language-plaintext highlighter-rouge">CreateSolidworksInstance</code></strong> to
                        start SolidWorks and prepare a document.</li>
                      <li>Clears any current selections in the document.</li>
                      <li>Zooms the view to fit the entire sketch.</li>
                      <li>Sets a success message if no errors occur and returns <strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong>.</li>
                      <li>Please see below üëáüèª flow digram to understand the functions.</li>
                    </ul>

                    <p><a
                        href="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-1.png"><img
                          src="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-1.png"
                          alt="CreateLineRefactorMethods-1" /></a></p>

                    <hr />

                    <h2 id="create-method---createsolidworksinstance">Create Method - CreateSolidworksInstance</h2>

                    <ul>
                      <li>Now we need to create <strong><code
                            class="language-plaintext highlighter-rouge">CreateSolidworksInstance()</code></strong>
                        method as shown below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">public</span> <span class="k">virtual</span> <span class="kt">bool</span> <span class="nf">CreateSolidworksInstance</span><span class="p">(</span><span class="k">out</span> <span class="n">ModelDoc2</span> <span class="n">swDoc</span><span class="p">)</span>
<span class="p">{</span>
  <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span> <span class="n">swApp</span> <span class="p">=</span> <span class="k">new</span> <span class="n">SldWorks</span><span class="p">.</span><span class="nf">SldWorks</span><span class="p">();</span>

  <span class="k">if</span> <span class="p">(</span><span class="n">swApp</span> <span class="p">==</span> <span class="k">null</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="n">messageToShow</span> <span class="p">=</span> <span class="s">"Failed to find Solidworks application."</span><span class="p">;</span>
    <span class="n">swDoc</span> <span class="p">=</span> <span class="k">null</span><span class="p">;</span>
    <span class="k">return</span> <span class="k">false</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="n">swApp</span><span class="p">.</span><span class="n">Visible</span> <span class="p">=</span> <span class="k">true</span><span class="p">;</span>

  <span class="k">return</span> <span class="nf">CreatePartDocument</span><span class="p">(</span><span class="n">swApp</span><span class="p">,</span><span class="k">out</span> <span class="n">swDoc</span><span class="p">);</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <h3 id="purpose-1">Purpose</h3>

                    <ul>
                      <li><strong><code
                            class="language-plaintext highlighter-rouge">CreateSolidworksInstance()</code></strong>
                        method‚Äôs purpose is to:
                        <ul>
                          <li><em>create an instance of SolidWorks</em>.</li>
                          <li><em>make it visible</em></li>
                          <li><em>then attempt to create a part document in SolidWorks</em></li>
                        </ul>
                      </li>
                    </ul>

                    <h3 id="return-type-1">Return Type</h3>

                    <ul>
                      <li>The <strong><code
                            class="language-plaintext highlighter-rouge">CreateSolidworksInstance()</code></strong>
                        method returns a <strong><code class="language-plaintext highlighter-rouge">bool</code></strong>
                        (Boolean value) ‚Äî <strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong> or <strong><code
                            class="language-plaintext highlighter-rouge">false</code></strong>.</li>
                      <li>This return type usually indicates <em>success</em> (<strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong>) or <em>failure</em>
                        (<strong><code class="language-plaintext highlighter-rouge">false</code></strong>) of the
                        method.</li>
                    </ul>

                    <h3 id="flowsummary-1">Flow/Summary</h3>

                    <ul>
                      <li>Tries to <strong>create an instance of SolidWorks</strong>.</li>
                      <li>If <em>SolidWorks cannot be found</em>, <strong>sets an error message</strong> and returns
                        <strong><code class="language-plaintext highlighter-rouge">false</code></strong>.</li>
                      <li>Makes the SolidWorks application <strong>visible</strong> to the user.</li>
                      <li>Calls <strong><code
                            class="language-plaintext highlighter-rouge">CreatePartDocument</code></strong> to
                        <strong>create a new part document</strong> and <em>returns its result</em>.</li>
                      <li>Please see below üëáüèª flow digram to understand the functions.</li>
                    </ul>

                    <p><a
                        href="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-2.png"><img
                          src="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-2.png"
                          alt="CreateLineRefactorMethods-2" /></a></p>

                    <hr />

                    <h2 id="create-method---createpartdocument">Create Method - CreatePartDocument</h2>

                    <ul>
                      <li>Now we need to create <strong><code
                            class="language-plaintext highlighter-rouge">CreatePartDocument()</code></strong> method as
                        shown below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">public</span> <span class="kt">bool</span> <span class="nf">CreatePartDocument</span><span class="p">(</span><span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span> <span class="n">swApp</span><span class="p">,</span><span class="k">out</span> <span class="n">ModelDoc2</span> <span class="n">swDoc</span><span class="p">)</span>
<span class="p">{</span>
  <span class="kt">string</span> <span class="n">defaultTemplate</span> <span class="p">=</span> <span class="n">swApp</span><span class="p">.</span><span class="nf">GetUserPreferenceStringValue</span><span class="p">((</span><span class="kt">int</span><span class="p">)</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">);</span>

  <span class="k">if</span> <span class="p">(</span><span class="kt">string</span><span class="p">.</span><span class="nf">IsNullOrEmpty</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">))</span>
  <span class="p">{</span>
    <span class="n">messageToShow</span> <span class="p">=</span> <span class="s">"Default part template is empty."</span><span class="p">;</span>
    <span class="n">swDoc</span> <span class="p">=</span> <span class="k">null</span><span class="p">;</span>
    <span class="k">return</span> <span class="k">false</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="n">swDoc</span> <span class="p">=</span> <span class="n">swApp</span><span class="p">.</span><span class="nf">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="m">0</span><span class="p">);</span>

  <span class="k">if</span> <span class="p">(</span><span class="n">swDoc</span> <span class="p">==</span> <span class="k">null</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="n">messageToShow</span> <span class="p">=</span> <span class="s">"Failed to create new Part document."</span><span class="p">;</span>
    <span class="k">return</span> <span class="k">false</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="k">return</span> <span class="nf">SelectSketchPlane</span><span class="p">(</span><span class="n">swApp</span><span class="p">,</span> <span class="n">swDoc</span><span class="p">);</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <h3 id="purpose-2">Purpose</h3>

                    <ul>
                      <li><strong><code
                            class="language-plaintext highlighter-rouge">CreatePartDocument()</code></strong> method‚Äôs
                        purpose is to:
                        <ul>
                          <li><em>create a new part document in SolidWorks using a default template.</em></li>
                          <li><em>sets up a sketch plane for further operations.</em></li>
                        </ul>
                      </li>
                    </ul>

                    <h3 id="return-type-2">Return Type</h3>

                    <ul>
                      <li>The <strong><code
                            class="language-plaintext highlighter-rouge">CreatePartDocument()</code></strong> method
                        returns a <strong><code class="language-plaintext highlighter-rouge">bool</code></strong>
                        (Boolean value) ‚Äî <strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong> or <strong><code
                            class="language-plaintext highlighter-rouge">false</code></strong>.</li>
                      <li>This return type usually indicates <em>success</em> (<strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong>) or <em>failure</em>
                        (<strong><code class="language-plaintext highlighter-rouge">false</code></strong>) of the
                        method.</li>
                    </ul>

                    <h3 id="flowsummary-2">Flow/Summary</h3>

                    <ul>
                      <li>Fetches the <strong>default part template</strong> from <em>SolidWorks user preferences</em>.
                      </li>
                      <li>Checks if the template is valid. If not, <strong>sets an error message and returns <code
                            class="language-plaintext highlighter-rouge">false</code></strong>.</li>
                      <li>Creates a <em>new part document using the template</em>.</li>
                      <li>Calls <strong><code
                            class="language-plaintext highlighter-rouge">SelectSketchPlane</code></strong> to <em>set up
                          a plane for sketching</em> and <em>returns its result</em>.</li>
                      <li>Please see below üëáüèª flow digram to understand the functions.</li>
                    </ul>

                    <p><a
                        href="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-3.png"><img
                          src="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-3.png"
                          alt="CreateLineRefactorMethods-3" /></a></p>

                    <hr />

                    <h2 id="create-method---selectsketchplane">Create Method - SelectSketchPlane</h2>

                    <ul>
                      <li>Now we need to create <strong><code
                            class="language-plaintext highlighter-rouge">SelectSketchPlane()</code></strong> method as
                        shown below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">public</span> <span class="kt">bool</span> <span class="nf">SelectSketchPlane</span><span class="p">(</span><span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span> <span class="n">swApp</span><span class="p">,</span> <span class="n">ModelDoc2</span> <span class="n">swDoc</span><span class="p">)</span>
<span class="p">{</span>
  <span class="kt">bool</span> <span class="n">boolStatus</span> <span class="p">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="nf">SelectByID2</span><span class="p">(</span><span class="s">"Right Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="k">false</span><span class="p">,</span> <span class="m">0</span><span class="p">,</span> <span class="k">null</span><span class="p">,</span> <span class="p">(</span><span class="kt">int</span><span class="p">)</span><span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">);</span>

  <span class="k">if</span> <span class="p">(</span><span class="n">boolStatus</span> <span class="p">==</span> <span class="k">false</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="n">messageToShow</span> <span class="p">=</span> <span class="s">"Failed to select Right Plane"</span><span class="p">;</span>
    <span class="n">swApp</span><span class="p">.</span><span class="nf">CloseAllDocuments</span><span class="p">(</span><span class="k">true</span><span class="p">);</span>
    <span class="n">swApp</span><span class="p">.</span><span class="nf">ExitApp</span><span class="p">();</span>
    <span class="k">return</span> <span class="k">false</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span><span class="p">.</span><span class="nf">InsertSketch</span><span class="p">(</span><span class="k">false</span><span class="p">);</span>

  <span class="kt">double</span> <span class="n">x1</span><span class="p">,</span> <span class="n">y1</span><span class="p">,</span> <span class="n">z1</span><span class="p">,</span> <span class="n">x2</span><span class="p">,</span> <span class="n">y2</span><span class="p">,</span> <span class="n">z2</span><span class="p">;</span>
  <span class="kt">var</span> <span class="n">lengthUnit</span> <span class="p">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">LengthUnit</span><span class="p">;</span>

  <span class="n">conversionHelper</span><span class="p">.</span><span class="nf">UnitConversion</span><span class="p">((</span><span class="n">swLengthUnit_e</span><span class="p">)</span><span class="n">lengthUnit</span><span class="p">);</span>

  <span class="p">(</span><span class="n">x1</span><span class="p">,</span> <span class="n">y1</span><span class="p">,</span> <span class="n">z1</span><span class="p">)</span> <span class="p">=</span> <span class="nf">ApplyUnitConversion</span><span class="p">(</span><span class="n">StartPointViewModel</span><span class="p">,</span> <span class="n">conversionHelper</span><span class="p">.</span><span class="n">LengthConversionFactor</span><span class="p">);</span>
  <span class="p">(</span><span class="n">x2</span><span class="p">,</span> <span class="n">y2</span><span class="p">,</span> <span class="n">z2</span><span class="p">)</span> <span class="p">=</span> <span class="nf">ApplyUnitConversion</span><span class="p">(</span><span class="n">EndPointViewModel</span><span class="p">,</span> <span class="n">conversionHelper</span><span class="p">.</span><span class="n">LengthConversionFactor</span><span class="p">);</span>
  <span class="n">SketchSegment</span> <span class="n">sketchSegment</span> <span class="p">=</span> <span class="k">null</span><span class="p">;</span>
  <span class="k">return</span> <span class="nf">CreateLine</span><span class="p">(</span><span class="n">sketchSegment</span><span class="p">,</span> <span class="n">x1</span><span class="p">,</span> <span class="n">y1</span><span class="p">,</span> <span class="n">z1</span><span class="p">,</span> <span class="n">swApp</span><span class="p">,</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span><span class="p">,</span> <span class="n">x2</span><span class="p">,</span> <span class="n">y2</span><span class="p">,</span> <span class="n">z2</span><span class="p">);</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <h3 id="purpose-3">Purpose</h3>

                    <ul>
                      <li><strong><code class="language-plaintext highlighter-rouge">SelectSketchPlane()</code></strong>
                        method‚Äôs purpose is to:
                        <ul>
                          <li><em>select a specific sketch plane (e.g., the Right Plane) in the SolidWorks part
                              document.</em></li>
                          <li><em>then insert a new sketch.</em></li>
                        </ul>
                      </li>
                    </ul>

                    <h3 id="return-type-3">Return Type</h3>

                    <ul>
                      <li>The <strong><code
                            class="language-plaintext highlighter-rouge">SelectSketchPlane()</code></strong> method
                        returns a <strong><code class="language-plaintext highlighter-rouge">bool</code></strong>
                        (Boolean value) ‚Äî <strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong> or <strong><code
                            class="language-plaintext highlighter-rouge">false</code></strong>.</li>
                      <li>This return type usually indicates <em>success</em> (<strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong>) or <em>failure</em>
                        (<strong><code class="language-plaintext highlighter-rouge">false</code></strong>) of the
                        method.</li>
                    </ul>

                    <h3 id="flowsummary-3">Flow/Summary</h3>

                    <ul>
                      <li>Attempts to select the <em>Right Plane in the part document</em>.</li>
                      <li>If the <strong>selection fails</strong>, <em>closes all documents, exits SolidWorks, and sets
                          an error message</em>.</li>
                      <li>Inserts a new sketch on the selected plane.</li>
                      <li>Converts the provided points using <strong><code
                            class="language-plaintext highlighter-rouge">ApplyUnitConversion</code></strong> and passes
                        them to <strong><code class="language-plaintext highlighter-rouge">CreateLine</code></strong>.
                      </li>
                      <li>Please see below üëáüèª flow digram to understand the functions.</li>
                    </ul>

                    <p><a
                        href="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-4.png"><img
                          src="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-4.png"
                          alt="CreateLineRefactorMethods-4" /></a></p>

                    <hr />

                    <h2 id="create-method---applyunitconversion">Create Method - ApplyUnitConversion</h2>

                    <ul>
                      <li>Now we need to create <strong><code
                            class="language-plaintext highlighter-rouge">ApplyUnitConversion()</code></strong> method as
                        shown below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">public</span> <span class="p">(</span><span class="kt">double</span><span class="p">,</span> <span class="kt">double</span><span class="p">,</span> <span class="kt">double</span><span class="p">)</span> <span class="nf">ApplyUnitConversion</span><span class="p">(</span><span class="n">IPointViewModel</span> <span class="n">inputPoint</span><span class="p">,</span> <span class="kt">double</span> <span class="n">lengthConversionFactor</span><span class="p">)</span>
<span class="p">{</span>
  <span class="kt">double</span> <span class="n">X</span><span class="p">,</span> <span class="n">Y</span><span class="p">,</span> <span class="n">Z</span><span class="p">;</span>

  <span class="n">X</span> <span class="p">=</span> <span class="n">inputPoint</span><span class="p">.</span><span class="n">XPoint</span> <span class="p">*</span> <span class="n">lengthConversionFactor</span><span class="p">;</span>
  <span class="n">Y</span> <span class="p">=</span> <span class="n">inputPoint</span><span class="p">.</span><span class="n">YPoint</span> <span class="p">*</span> <span class="n">lengthConversionFactor</span><span class="p">;</span>
  <span class="n">Z</span> <span class="p">=</span> <span class="n">inputPoint</span><span class="p">.</span><span class="n">ZPoint</span> <span class="p">*</span> <span class="n">lengthConversionFactor</span><span class="p">;</span>

  <span class="k">return</span> <span class="p">(</span><span class="n">X</span><span class="p">,</span> <span class="n">Y</span><span class="p">,</span> <span class="n">Z</span><span class="p">);</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <h3 id="purpose-4">Purpose</h3>

                    <ul>
                      <li><strong><code
                            class="language-plaintext highlighter-rouge">ApplyUnitConversion()</code></strong> method‚Äôs
                        purpose is to:
                        <ul>
                          <li><em>convert a point‚Äôs coordinates (X, Y, Z) based on the length units set in the
                              SolidWorks document.</em></li>
                        </ul>
                      </li>
                    </ul>

                    <h3 id="return-type-4">Return Type</h3>

                    <ul>
                      <li>The <strong><code
                            class="language-plaintext highlighter-rouge">ApplyUnitConversion()</code></strong> method
                        returns <strong><code
                            class="language-plaintext highlighter-rouge">(double, double, double)</code></strong>.</li>
                      <li>This returnS the converted X, Y, and Z coordinates as a <strong><code
                            class="language-plaintext highlighter-rouge">tuple</code></strong>.</li>
                    </ul>

                    <h3 id="flowsummary-4">Flow/Summary</h3>

                    <ul>
                      <li>Takes an input point and the length conversion factor.</li>
                      <li>Multiplies each coordinate <strong><code
                            class="language-plaintext highlighter-rouge">(X, Y, Z)</code></strong> of the input point by
                        the conversion factor.</li>
                      <li>Returns the converted coordinates as a <strong><code
                            class="language-plaintext highlighter-rouge">tuple</code></strong>.</li>
                      <li>Please see below üëáüèª flow digram to understand the functions.</li>
                    </ul>

                    <p><a
                        href="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-5.png"><img
                          src="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-5.png"
                          alt="CreateLineRefactorMethods-5" /></a></p>

                    <hr />

                    <h2 id="create-method---createline">Create Method - CreateLine</h2>

                    <ul>
                      <li>Now we need to create <strong><code
                            class="language-plaintext highlighter-rouge">CreateLine()</code></strong> method as shown
                        below.</li>
                    </ul>

                    <div class="language-cs highlighter-rouge">
                      <div class="highlight">
                        <pre class="highlight"><code><span class="k">public</span> <span class="kt">bool</span> <span class="nf">CreateLine</span><span class="p">(</span><span class="n">SketchSegment</span> <span class="n">sketchSegment</span><span class="p">,</span> <span class="kt">double</span> <span class="n">x1</span><span class="p">,</span> <span class="kt">double</span> <span class="n">y1</span><span class="p">,</span> <span class="kt">double</span> <span class="n">z1</span><span class="p">,</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span> <span class="n">swApp</span><span class="p">,</span> <span class="n">SketchManager</span> <span class="n">swSketchManager</span><span class="p">,</span> <span class="kt">double</span> <span class="n">x2</span><span class="p">,</span> <span class="kt">double</span> <span class="n">y2</span><span class="p">,</span> <span class="kt">double</span> <span class="n">z2</span><span class="p">)</span>
<span class="p">{</span>
  <span class="n">sketchSegment</span> <span class="p">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="nf">CreateLine</span><span class="p">(</span><span class="n">x1</span><span class="p">,</span> <span class="n">y1</span><span class="p">,</span> <span class="n">z1</span><span class="p">,</span> <span class="n">x2</span><span class="p">,</span> <span class="n">y2</span><span class="p">,</span> <span class="n">z2</span><span class="p">);</span>

  <span class="k">if</span> <span class="p">(</span><span class="n">sketchSegment</span> <span class="p">==</span> <span class="k">null</span><span class="p">)</span>
  <span class="p">{</span>
    <span class="n">messageToShow</span> <span class="p">=</span> <span class="s">"Failed to Create Sketch line."</span><span class="p">;</span>
    <span class="n">swApp</span><span class="p">.</span><span class="nf">CloseAllDocuments</span><span class="p">(</span><span class="k">true</span><span class="p">);</span>
    <span class="n">swApp</span><span class="p">.</span><span class="nf">ExitApp</span><span class="p">();</span>
    <span class="k">return</span> <span class="k">false</span><span class="p">;</span>
  <span class="p">}</span>

  <span class="k">return</span> <span class="k">true</span><span class="p">;</span>
<span class="p">}</span>
</code></pre>
                      </div>
                    </div>

                    <h3 id="purpose-5">Purpose</h3>

                    <ul>
                      <li><strong><code class="language-plaintext highlighter-rouge">CreateLine()</code></strong>
                        method‚Äôs purpose is:
                        <ul>
                          <li><em>To draw a sketch line in the SolidWorks part document using the provided start and end
                              points.</em></li>
                        </ul>
                      </li>
                    </ul>

                    <h3 id="return-type-5">Return Type</h3>

                    <ul>
                      <li>The <strong><code class="language-plaintext highlighter-rouge">CreateLine()</code></strong>
                        method returns a <strong><code class="language-plaintext highlighter-rouge">bool</code></strong>
                        (Boolean value) ‚Äî <strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong> or <strong><code
                            class="language-plaintext highlighter-rouge">false</code></strong>.</li>
                      <li>This return type usually indicates <em>success</em> (<strong><code
                            class="language-plaintext highlighter-rouge">true</code></strong>) or <em>failure</em>
                        (<strong><code class="language-plaintext highlighter-rouge">false</code></strong>) of the
                        method.</li>
                    </ul>

                    <h3 id="flowsummary-5">Flow/Summary</h3>

                    <ul>
                      <li>Uses the SolidWorks <strong><code
                            class="language-plaintext highlighter-rouge">SketchManager.CreateLine</code></strong> method
                        to <strong>draw a line</strong> <em>between start and end points</em>.</li>
                      <li>If the line creation <strong><code
                            class="language-plaintext highlighter-rouge">fails</code></strong>, <em>sets an error
                          message, closes all documents, and exits SolidWorks</em>.</li>
                      <li>Returns <strong><code class="language-plaintext highlighter-rouge">true</code></strong> if
                        <em>the line is successfully created</em>.</li>
                      <li>Please see below üëáüèª flow digram to understand the functions.</li>
                    </ul>

                    <p><a
                        href="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-6.png"><img
                          src="/assets/solidworks-csharp-images/create-line-code-refactor/CreateLineRefactorMethods-6.png"
                          alt="CreateLineRefactorMethods-6" /></a></p>

                    <hr />

                    <p><strong>This is it !!!</strong></p>

                    <p><em>I hope my efforts will helpful to someone!</em></p>

                    <p>If you found anything to <strong>add or update</strong>, please let me know on my
                      <em>e-mail</em>.</p>

                    <p>Hope this post helps you to <strong>Understand Refactor Code</strong>.</p>

                    <p><em>If you like the post then please share it with your friends also.</em></p>

                    <p><em>Do let me know by you like this post or not!</em></p>

                    <p><em>Till then, Happy learning!!!</em></p>


                  </div>

                  <div>
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Top and Bottom placed Ad -->
                    <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002"
                      data-ad-slot="6644001766" data-ad-format="auto" data-full-width-responsive="true"></ins>
                    <script>
                      (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
                  </div>

                </section>

                <footer class="page__meta">






                  <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i>
                      Updated:</strong> <time datetime="2025-03-01T08:06:43-05:00">March 1, 2025</time></p>


                </footer>


                <nav aria-label="Page navigation example">
                  <ul class="pagination justify-content-center">

                    <li class="page-item mr-5">
                      <a class="btn btn-primary text-light" href="/solidworks-csharp/create-line/" title="SOLIDWORKS C# API - Create Line
">‚ùÆ Previous</a>
                    </li>


                    <li class="page-item ml-5">
                      <a class="btn btn-primary text-light" href="/solidworks-csharp/setup-test-project/" title="SOLIDWORKS C# API - Setup Test Project
">Next ‚ùØ</a>
                    </li>

                  </ul>
                </nav>

              </div>
            </article>

          </div>
        </div>
      </div>
    </div>
  </div>

  <div id="footer" class="page__footer">
    <footer>
      <!-- start custom footer snippets -->

      <!-- end custom footer snippets -->
      <footer class="bd-footer py-5 bg-light">
        <div class="container">
          <div class="row">
            <div class="col-6">
              <a class="d-inline-flex align-items-center mb-2 link-dark" href="/" aria-label="Bootstrap">
                <img src="/assets/logo.png" width="30" height="30" class="img-fluid mr-2" alt="">
                <span> The CAD Coder</span>
              </a>
              <ul class="list-unstyled small text-muted">
                <li class="mb-2">Programming Tutorials for SOLIDWORKS 3D CAD Software.</li>
                <li class="mb-2">Copyright ¬© 2022 The CAD Coder</li>
                <li class="mb-2">Built with <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a>.</li>






                <li class="list-inline-item"><a href="https://facebook.com/thecadcoder" target="_blank"
                    title="Facebook"><i class="fab fa-2x fa-facebook-f"></i></a></li>











                <li class="list-inline-item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg"
                    target="_blank" title="YouTube"><i class="fab fa-2x fa-youtube"></i></a></li>



                <li class="list-inline-item"><a href="mailto:thecadcoder@gmail.com" target="_blank" title="Email"><i
                      class="fa fa-envelope fa-2x"></i></a></li>



              </ul>
            </div>
            <div class="col-6">
              <h5>Links</h5>
              <ul class="list-unstyled">
                <!-- <li class="mb-2"><a href="/">Home</a></li> -->
                <li class="mb-2"><a href="/aboutMe/">About</a></li>
                <li class="mb-2"><a href="/resources/">Resources</a></li>
                <li class="mb-2"><a href="/Disclaimer/">Privacy Policy</a></li>
              </ul>
            </div>
          </div>
        </div>
      </footer>
    </footer>
  </div>


  <script src="/assets/js/main.min.js"></script>




  <script src="/assets/js/lunr/lunr.min.js"></script>
  <script src="/assets/js/lunr/lunr-store.js"></script>
  <script src="/assets/js/lunr/lunr-en.js"></script>







  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->


  <script src="/assets/js/main.min.js"></script>




  <script src="/assets/js/lunr/lunr.min.js"></script>
  <script src="/assets/js/lunr/lunr-store.js"></script>
  <script src="/assets/js/lunr/lunr-en.js"></script>






</body>

</html>