<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="generator" content="Docusaurus v2.0.0-alpha.66">
<link rel="preconnect" href="https://www.google-analytics.com">
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-117501871-2","auto"),ga("set","anonymizeIp",!0),ga("send","pageview")</script>
<script async src="https://www.google-analytics.com/analytics.js"></script>
<script data-ad-client="ca-pub-8158659264340002" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><title data-react-helmet="true">VBE Windows | The Cad Coder</title><meta data-react-helmet="true" name="twitter:card" content="summary_large_image"><meta data-react-helmet="true" name="docusaurus_language" content="en"><meta data-react-helmet="true" name="docusaurus_version" content="current"><meta data-react-helmet="true" name="docusaurus_tag" content="docs-default-current"><meta data-react-helmet="true" property="og:title" content="VBE Windows | The Cad Coder"><meta data-react-helmet="true" name="description" content="In this post we look following windows in Visual Basic Editor:"><meta data-react-helmet="true" property="og:description" content="In this post we look following windows in Visual Basic Editor:"><meta data-react-helmet="true" property="og:url" content="https://prashantbaher.github.io//docs/vba/vba-vbe-window"><link data-react-helmet="true" rel="shortcut icon" href="/img/logo_icon.ico"><link data-react-helmet="true" rel="canonical" href="https://prashantbaher.github.io//docs/vba/vba-vbe-window"><link rel="stylesheet" href="/styles.1f42e2d6.css">
<link rel="preload" href="/styles.8dac73e6.js" as="script">
<link rel="preload" href="/runtime~main.c20766ae.js" as="script">
<link rel="preload" href="/main.c76857e4.js" as="script">
<link rel="preload" href="/1.edd1b653.js" as="script">
<link rel="preload" href="/2.266b950c.js" as="script">
<link rel="preload" href="/94.4c75db3c.js" as="script">
<link rel="preload" href="/95.3eb551e8.js" as="script">
<link rel="preload" href="/f976f453.ebf1a006.js" as="script">
<link rel="preload" href="/17896441.bf30d83f.js" as="script">
<link rel="preload" href="/ab0be63b.a7018905.js" as="script">
</head>
<body>
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><div aria-label="Navigation bar toggle" class="navbar__toggle" role="button" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></div><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a><div class="navbar__item dropdown dropdown--hoverable dropdown--left"><a class="navbar__item navbar__link">VBA</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li><a class="dropdown__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></div><a class="navbar__item navbar__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a><a class="navbar__item navbar__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></div><div class="navbar__items navbar__items--right"><div class="navbar__item dropdown dropdown--hoverable dropdown--right"><a class="navbar__item navbar__link">About</a><ul class="dropdown__menu"><li><a class="dropdown__link" position="right" href="/docs/about">About Me</a></li><li><a class="dropdown__link" position="right" href="/docs/resources">Resources</a></li><li><a class="dropdown__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></div><div class="react-toggle react-toggle--disabled displayOnlyInLargeViewport_2aTZ"><div class="react-toggle-track"><div class="react-toggle-track-check"><span class="toggle_BsTx">ðŸŒœ</span></div><div class="react-toggle-track-x"><span class="toggle_BsTx">ðŸŒž</span></div></div><div class="react-toggle-thumb"></div><input type="checkbox" disabled="" aria-label="Dark mode toggle" class="react-toggle-screenreader-only"></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div><div class="navbar-sidebar"><div class="navbar-sidebar__brand"><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a></div><div class="navbar-sidebar__items"><div class="menu"><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">VBA</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></li><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">About</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/about">About Me</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/resources">Resources</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></li></ul></div></div></div></nav><div class="main-wrapper"><div class="docPage_2gpo"><div class="docSidebarContainer_3_JD" role="complementary"><div class="sidebar_2urC"><div class="menu menu--responsive menu_5FrY"><button aria-label="Open Menu" aria-haspopup="true" class="button button--secondary button--sm menu__button" type="button"><svg aria-label="Menu" class="sidebarMenuIcon_Dm3K" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 32 32" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><ul class="menu__list"><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!">Introduction</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-Intro">VBA Introduction</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba/vba-vbe">Visual Basic Editor (VBE)</a></li><li class="menu__list-item"><a aria-current="page" class="menu__link menu__link--active active" tabindex="0" href="/docs/vba/vba-vbe-window">VBE Windows</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">Procedures</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-procedures">Sub and Function Procedures</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-procedures-exec">Executing Sub and Function Procedures</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">Programming Concept</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-prog-concept">Programming Concepts, Comments and Data-types</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-variables">VBA Variables</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-variables-decl">Declaring and Scoping of Variables</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-variable-scope">Variable Scope</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-variable-life">Public, Static and Variable&#x27;s Life</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-constants">VBA Constants</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-string-basic">VBA String Basics</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-statement">VBA Assignment Statements And Operators</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-arrays">VBA Arrays</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-functions">VBA Functions</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-functions-adv">VBA Functions that do more</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">Program Flow</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-program-flow">Controlling Program Flow and Making Decisions</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-if-else">If-Then-Else and Select Case structure</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-looping">VBA Looping</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">Bug Finding</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-bug-find">Bug Finding</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-debugger">VBA Debugger</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-bug-tips">VBA Bug Reduction Tips</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">Dialog Boxes</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-dialog-box">VBA Dialog Boxes</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-msgbx-box">VBA MsgBox Function</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-input-box">VBA InputBox Function</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba/vba-open-boxes">VBA GetOpenFilename, GetSaveAsFilename and Getting a Folder Name</a></li></ul></li></ul></div></div></div><main class="docMainContainer_3EyW"><div class="container padding-vert--lg docItemWrapper_1EkI"><div class="row"><div class="col docItemCol_2ASc"><div class="docItemContainer_3QWW"><article><header><h1 class="docTitle_1Lrw">VBE Windows</h1></header><div class="markdown"><p>In this post we look following windows in <code>Visual Basic Editor</code>:</p><ol><li>Project Window</li><li>Code Window</li></ol><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="project-window"></a>Project Window<a aria-hidden="true" tabindex="-1" class="hash-link" href="#project-window" title="Direct link to heading">#</a></h2><p>When you are working in <code>VBE</code>, each file open is called a Project.
You can think of a <code>project</code> as a <code>collection</code> of objects. </p><p>You can <em>expand</em> a project by clicking plus sign (+) at the left of the projectâ€™s name in Project window. </p><p><em>Contract</em> a project by clicking minus sign (-) to the left of the projectâ€™s name in Project window. Or you can simply <em>double</em> click the items to expand or contract them.</p><p>Every project expands to show at least one node. In our previous image we have <code>SOLIDWORKS Objects</code>. This node expands to show an item for Solidworks application. </p><p>If the project has any <code>VBA</code> module, the project listing also shows a <code>Module node</code>. </p><p>A project can also contain a node called <code>Forms</code>, which contains <code>UserForm objects</code> (which holds custom dialog boxes).</p><p>The concept of <code>Object</code> may not be clear to you at this moment. However, things become much clearer in subsequent topics. </p><p>Donâ€™t be too concerned if you donâ€™t understand whatâ€™s going on at this point.</p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="adding-a-new-vba-module"></a>Adding a new VBA module<a aria-hidden="true" tabindex="-1" class="hash-link" href="#adding-a-new-vba-module" title="Direct link to heading">#</a></h3><p>Follow below steps to add a new VBA module to a project:</p><ol><li>Select the projects name in the Project Window.</li><li>Select Insert -&gt; Module.</li></ol><p>or </p><ol><li>Right click the projectâ€™s name.</li><li>Select Insert -&gt; Module from the shortcut menu.</li></ol><p>When you record a macro or create a blank macro, <code>Solidworks</code> automatically adds a module to hold the codes.</p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="removing-a-new-vba-module"></a>Removing a new VBA module<a aria-hidden="true" tabindex="-1" class="hash-link" href="#removing-a-new-vba-module" title="Direct link to heading">#</a></h3><p>If you want to remove a module from Project window then follow below steps for that:</p><ol><li>Select the module&#x27;s name in the Project Window.</li><li>Select Fie -&gt; Remove.</li></ol><p>Or</p><ol><li>Right-click the moduleâ€™s name.</li><li>Select remove from the shortcut menu.</li></ol><p><code>VBE</code> always trying to keep you from doing something that you will regret, hence it will ask if you want to export the code in the module before deleting the code. </p><p>And in most cases, you donâ€™t want to export. If you do want to export the code, please see next section.</p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="exporting-and-importing-of-objects"></a>Exporting and Importing of objects<a aria-hidden="true" tabindex="-1" class="hash-link" href="#exporting-and-importing-of-objects" title="Direct link to heading">#</a></h3><p>Every object in a <code>VBA project</code> can be saved to a separate file. Saving an individual object in a project is known as <code>Exporting</code>. </p><p>Reason for exporting a file is that you can also <code>import</code> objects in a project. </p><p><code>Exporting</code> and <code>Importing</code> objects might be useful if you want to use a particular object (such as a VBA module or a UserForm) in a different project.</p><p>Below steps show how to export an object:</p><ol><li>Select an object in the Project window.</li><li>Select File -&gt; Export file or press Ctrl + E.</li></ol><p>You get a <code>dialog box</code> that asks for a filename. Note that the object remains in the original project only a copy of object is exported.</p><p>Importing an object is also a similar process, which is shown below:</p><ol><li>Select the projectâ€™s name in the Explorer window.</li><li>Select File -&gt; Import file or press Ctrl + M.</li></ol><p>You get a dialog box that asks for a file. Locate the file and click open. </p><p>You should only import a file if was export by using <code>File -&gt; Export</code> file command.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="code-window"></a>Code Window<a aria-hidden="true" tabindex="-1" class="hash-link" href="#code-window" title="Direct link to heading">#</a></h2><p>As you become proficient with <code>VBA</code>, you spend a lot of time with working in the <code>Code window</code>. </p><p>Macros that you record are stored in a module, and you can type a <code>VBA code</code> <em>directly</em> into a VBA module.</p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="minimize-and-maximize-code-windows"></a>Minimize and maximize Code windows<a aria-hidden="true" tabindex="-1" class="hash-link" href="#minimize-and-maximize-code-windows" title="Direct link to heading">#</a></h3><p>If you have several projects open, the <code>VBE</code> may have lots of Code window at any given time. Below figure shows an example of this.</p><p><img alt="Visual-basic-editor" src="/assets/images/2.Example_of_Many_code_window-64eb975418e4b11f08aba5a4c0508bae.PNG"></p><p><code>Code windows</code> are much like your files opened in <code>Solidworks</code>. You can minimize them, maximize them, resize them, and hide them and so on. </p><p>Most people find it much easier to <em>maximize</em> the <code>code window</code> that they are working on. Doing so lets you see more code and keeps you from getting distracted.</p><p>To maximize the <code>Code window</code>, click the maximize button in its <em>title bar</em> or just <em>double-click</em> the title bar of Code window to maximize it. </p><p>To restore a window to its original size, click the restore button. When the Code window is maximized, its title bar is not visible, so you will find the restore below the <code>VBE title bar</code>.</p><p>Sometimes you want to have two or more <code>Code windows</code> visible. </p><p>For example, you want to compare the code in the two modules or copy code from one module to another. </p><p>You can arrange the windows manually, or use the <code>Window -&gt; Tile Horizontally</code> or <code>Window â‡¨ Tile Vertically</code> command to arrange them automatically.</p><p>You can quickly switch among code window by pressing <code>Ctrl + TAB</code>. If you repeat that key combination, you keep cycling through all the open code windows. </p><p>Pressing <code>Ctrl + Shift + TAB</code> cycles through the windows in reverse order.</p><p>Minimizing a window gets it out of the way. You can also click the window close button in a Code windowâ€™s title bar to close the window completely. (Closing a window just hides it; you wonâ€™t lose anything.) </p><p>To open it again, just double-click the appropriate object in the Project window. Working with these Code windows sounds difficult that it really is.</p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="creating-a-module"></a>Creating a Module<a aria-hidden="true" tabindex="-1" class="hash-link" href="#creating-a-module" title="Direct link to heading">#</a></h3><p>In general, a <code>VBA module</code> can hold <strong>three</strong> types of code:</p><ol><li><p><strong>Declaration</strong>: One or more information statement that you provide to <code>VBA</code>. For example, you can declare the data type for variables you plan to use, or set some other module-wide options.</p></li><li><p><strong>Sub procedures:</strong> A set of programming instructions that performs some actions.</p></li><li><p><strong>Function procedures:</strong> A set of programming instructions that returns a single value.</p></li></ol><p>A single <code>VBA module</code> can store any number of <code>Sub procedures</code>, <code>Function procedure</code> and <code>declaration</code>. </p><p>Well, there is a limit â€“ about 64,000 characters per module. It is very rare that if anybody reaches that limit but if someone reaches then the solution is simply insert a new module.</p><p>How you organize a <code>VBA module</code> is totally up to you. Some people prefer to keep all their VBA code in a <em>single module</em> others (like me) likes to split up the code into <code>several different modules or even classes</code>. It is a personal choice like arranging furniture.</p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="inserting-vba-code-into-a-module"></a>Inserting VBA code into a Module<a aria-hidden="true" tabindex="-1" class="hash-link" href="#inserting-vba-code-into-a-module" title="Direct link to heading">#</a></h3><p>An empty <code>VBA module</code> is like a <strong>fake</strong> food you see in the advertisements. It looks good but it does not really do much. </p><p>Before you can do anything meaningful, you must have some <code>VBA code</code> in the <code>VBA module</code>. You can insert VBA code into VBA module in three ways:</p><ol><li><p>Insert code directly into code window.</p></li><li><p>Use the macro recorder to record your actions and convert them into VBA code.</p></li><li><p>Copy the code from one module and paste it into another module.</p></li></ol><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="entering-code-directly-into-a-module"></a>Entering code directly into a module<a aria-hidden="true" tabindex="-1" class="hash-link" href="#entering-code-directly-into-a-module" title="Direct link to heading">#</a></h3><p>Sometimes the best route is the most <code>direct one</code>. Entering the <code>code directly</code> involves, typing the code via your keyboard. </p><p>Entering and editing a text in a VBA module works as you might expect. You can select, copy, cut, paste and do other things as you do in other word processing software.</p><p>Use the <code>TAB</code> key to indent some of the lines to make your code easier to read. This is not necessary, but it is a good habit to acquire. </p><p>As you go through you will understand why indenting code lines is helpful.</p><p>A single line of <code>VBA code</code> can be as long as you like. </p><p>However, you may want to use the <code>line-continuation</code> character to break up the lengthy line of code. </p><p>To continue a single line of code (also known as <code>statement</code>) from one line to next, end the first line with a space followed by an underscore (_). Then continue the <code>statement</code> in the next line. </p><p>Below is given the example of a single statement split into two lines:</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">set swPart = swApp.NewDocument(swApp.GetUserPreferenceStringValue _</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    (swUserPreferenceStringValue_e.swDefaultTemplatePart),0,0,0)</span></div></div></div></div></div><p>This statement would perform the same way if it were entered in a single line (with no continuation characters). </p><p>Notice that I indented the second line of statement. Indenting is optional but it clarifies the fact that these lines are not separate statements.</p><div class="admonition admonition-info alert alert--info"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"></path></svg></span>info</h5></div><div class="admonition-content"><p>If you are wondering what above statement does, then the answer is above statement open a new part with <code>default part template</code> in <em>SolidWorks</em>. This code is <strong><em>not</em></strong> inserted using macro recorder, instead I write it manually to find a default part template and use that template to open a new part.</p></div></div><p>The engineers who designed <code>VBE</code> knew that people like us would be making mistakes. Therefore, the VBE has multiple levels of Undo and Redo. </p><p>If you deleted a statement that you should not have, use the <code>Undo button</code> on the toolbar (or press <code>Ctrl+Z</code>) until the statement shows up. </p><p>After undoing, you can use the <code>Redo button</code> to perform the changes you have undone. This redo/undo stuff is much like you use in other software. Until you use it, you cannot understand.</p><p>Ready to enter some <code>live code</code>, try the following steps:</p><ol><li>Go to your VBE.</li><li>Double-click your module if it is not opened.</li><li>Go to COde Window.</li><li>Type the following code into <code>Code window</code>:</li></ol><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub GuessName()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Msg = &quot;Is this a CAD Software?&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Ans = MsgBox(Msg, vbYesNo)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    If Ans = vbNo Then MsgBox &quot;Oh, thatâ€™s fine.&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    If Ans = vbYes Then MsgBox &quot;You must be joking!&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><ol start="5"><li>Make sure the cursor is located anywhere within the text you typed, and then press <code>F5</code> to execute the procedure.</li></ol><p><code>F5</code> is a shortcut for the <code>Run -&gt; Run Sub/UserForm command</code>. </p><p>If you entered the code correctly, <code>VBE</code> execute the procedure, and you can respond to the simple dialog box as shown in below figure.</p><p><img alt="Visual-basic-editor" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAPEAAACYCAYAAAA1MA+bAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAuJSURBVHhe7Z1Nb9zGHYf5nXSSP0kh9LxA07pIi7aJW7cCWgQIGhhSgebiFI3aQ3pIXN9kw3ZkS5ZfJEvyu2VbtmF/A198nvI3JJcz5OxqV6st9y8/D/CTl8PhkBzNwyEpJcrevn3rXr9+7Q4ODtzLly/dixcv3P7+vnv27Jl7+vSpe/LkiXv8+LF79OiRe/jwoc+DBw8IIVNM5Zq8k3/yUE7KTTn66tUr9+bNGyd/MwmsQlVQRW2kRu7fv+/29vbc7u6u29nZcffu3XPb29s+W1tbhJAppnJN3sk/uSgnJbY8ff78uZ94JXImgX+68BNCiKFodtasLJEzzcAqBAAbyFfNypqRNQlnMhqJAewgX3WLrUdfzcaZ7rGRGMAO8lXPzdVsnOkDEgPYQb7evn3bv3TWnXSmt15IDGAH+bq5uenfXOtOGokBjCFfb9686X8EpR8HZ5qSkRjADvJ1Y2Oj/1ycaUpGYgA7yNcbN264O3fu+OfiTFMyEgPYQb5ev37dv9zSj5oyTclIDDA9JNqHDx/KpTZapzqjIl/X1tbcrVu3/Mut7O7du6NLvNpzWZaV6bnVstgTrcvcqeWDcoVYdb3slIuKPCqv2tHnevtmG6u9zPXiHbbb1DGElQ49pnh/9abNtg/c8qm8TlVhWD8ANJCku7t7SZGHrRuEfL127Vr/5dboEh8su1PhgM2Xl6sFP6jbg76WJiGcR+WhxGGdUrJQnFBQfzyxmAfLp+rlcY/J108fiy4g/e2G9QPAAFKyHkVgEUqsO+lMD8cjSaxBfmo5V6FJIUfolyca7E1BK1Q+pE7Yhj4H+5ewveW8rL9jHUe1/VGOKVyuP2s/rdk92Q8AwwmlParAQr5evXrVv6HWJDy6xH5gN29JcyIxQkKpEoJ6VD5M9FDGpqT63Nw+EH7cY4rkLNctp4TVukQ/AIxAJe9RBRYTSCwKqaLnx8YMWRMK2BCmTyBesk7YRl6j/1yc1y33udort5GEVcWRj6l6rg1u2z31uqi4T6IfAEZgBiQu8TNdOYCnPhMHZZWogbDVc3D0PDzuMbXql+tWVd48poCwHwAOoRJY/4afx+V4JM6pnxXD2S0gEuOIEjfl0nI+w67qebgqVFlvOZb9CMcUXQTCdbpgRILHtJ6ZARKkpD2qyEeXOJ+VmpL0B31roEuCIW+C+6h8kMRFG7EfxX7jt85FvfSPvMY5pnA5XudFrW7Ph/UDQIJhsh5F5Alm4kqWMs3Zx0tTr49XN7bNUwx8lYcSh3VCwWoioUr0rJycDQ89pngfddvtdX4f/XV1m8zCcBg7U/hlj2O5nQaAbkBiAOMgMYBxkBjAOEgMYBwkBjAOEgMYB4kBjIPEAMZBYgDjIDGAcZAYwDgtifUFiQHsIF+j/8cWEgPYAokBjIPEAMZBYgDjIDGAcZAYwDhIDGAcJAYwDhIDGAeJAYyDxADGQWIA4yAxgHGQGMA4SAxgHCQGMA4SAxgHiQGMg8QAxkFiAOMgMYBxkBjAOEgMYJyWxL8/+0ckBjBES+JPf/0bJAYwBBIDGKeSeHNz021vbyMxgDWOUeJV18t6+dejoG3n3dJBuRhysOTmB61rMk7dsThwS/OZy7Iy80t5ScxqLy/vNc9e5xVsl2d+2MGt9oK6I/ZltU3imODjoCOJm9IOkbhr/IUhc5GfedlSY3l+vud6881zSJ1nLlxL9hy/n6D/mvtIUrRXNzfD/QhTA4mHUszAKedCDpbm/Qxb/VuTOK+mrBWaUceeTa30I0yTKUkc337GEqheva6YlcrBt1rMeiqvZQgH5rB2xTh189q6BS7XjzQ7JtF+yn36GTkUMTyeikEXhqJfkrfb/jia51LUr8rml5aiZZ2Pzq/eT+NY1Ga5Mt0PRf1ebz4vL/sgOo5RL9gwbaYjsWaVevQkaAwov5wPjEoA/5xXDZKg7jjtHlo3pHk8JS0pE0R1AqE9qXYHSSzqC0+9vuib/rIXqWqz2X5jOeyD/PN8fmzVRaJ91yDC7Yv9pi+mWszba20PXTAdicsr9uBvcmNADF0OPo/T7qF1czTI8zpFwv2X+DaGzzhNGbTcnM3idpuiJyiP3TeTOIZ6hh3WbznatrzArOYzqr/T8cuNY0j2Q6Ktfp0y/fOELpmOxCV+QOff7Pb3+pDBFy03143T7pC6kRyDxBo2awrtrzGwfap228cT73cw/YvBJBL3zysv78ubtxXIPbgfGm2NeNzw/6cl8e8+O3NsEgsNxvZseNjgC5eb6wpGa7cgWVezTzSQ29t5ylkqEjmv798ch230CcVPndeAi0I+S9b1ijaKY25sE8mUaj8+D3/uuZjV+Wu51wtuhQf2Q/rY230OXdOSeGNjY3KJo9uz9NW7/zLFj85hgzH4fGi749QtRPHrkz8eCvCDu2pL9YtBr3NIDWqJUp9XsF10jk0adUPTo/2HbYT9VBD3a04kZmJ5YD+02271Q3iM0BktifW7l0eTGAC6AIkBjIPEAMZBYgDjIDGAcZAYwDhIDGAcJAYwjnz9/vsfkBjAKvL1k5+fdiv/+jcSA1hEvv7sk9Pu9C9/5S5duozEANYIJT639DckBrBGKPHnZ84iMYA1Qon1nxIjMYAxkBjAOC2J9YoaiQHsgMQAxkFiAOMgMYBxkBjAOEgMYBwkBjAOEgMYB4kBjIPEAMZBYgDjIDGAcZAYwDhIDGCcgRK/f/+eEGIgSEyI8cjXX5z+FIkJsRr5+oezf0JiQqxGvp47t4TEhFiNfP3nt98iMSFWI18vXryIxIRYjXzVH1STwEhMiMHI1x9//NH9+S9fIDEhFlNJ/Pevv0ZiQiymkvi77/6DxIRYTCXxpcuXC4nPn/8GiQkxlEriW7duud9+dsZlMhmJCbET+bq2tuYl/vLLr2ZL4uzzfTKFpPo6lQsXLpApJNXXkySU+Pw3/0DijyGpvk5FA+7du3fkGDNtiX+48N/ZlDjVGWT8IHH3mbbEN27cQOKTHCTuPtOW+N69e0h8koPE3QeJyURB4u6DxGSiIHH3QeKOsrKQubnF9bh8ZcFlCytx2YzHtsQrbiHLEn2u8jm3uB6WzW6QuKusL7q5bMGt9MvW3eKcnYFTxb7Ec25uLnMLK+1yJA4k/utX55A4kWg2NjgLKydB4sWV/II6t+jWm+VIXEusL0iciGZjP3g0CwezgZ+l89s8n2q2LuoUZc2Zo7ucCIlzWePHm4bE0fdjdvq+ChJ3HA2ehcVwJmgMoHyG9oNrRmfqkyLx8M/NC2zw/ZmBIHHXkZytQVJf9X0kb1neehnWcU6OxHn6F8qg3Pd7+O6ivPDO0GyMxJ2nMZASgybM+uLcTN3SnSiJ+481SIzEY6U5kLQ8fMaVyLMyI58sifP074Sq8uL7Ed8pDb7IdhEk7jzDBlJwO13edheZnUF04iTOU9ztBOXR96Ndv+sgMZkotiU+GUFiMlGQuPsgMZkoSNx9kJhMFCTuPkhMJgoSdx8kJhMFibvPRysxOd6k+joVJD7+IDE5lqT6OhUNOHL8SfX1JGlJzJ9xIcRW5Gv1FyBmbiYmhBye1kyMxITYChITYjxITIjxVBLfvn3b7ezsuExfkJgQO5Gv169fR2JCrEa+6m8w3blzx+3u7rpMX5CYEDupJL57967b29tzmb4gMSF2Il83Njbc1taWu3//vsv0BYkJsRP5evPmTadf1Hrw4IHLHj58iMSEGIp81Y+X9D7r8ePHLtMXJCbETuRr9Tz85MkTl+3v7/tCQoidaBbWXfTTp09d9uLFC/9B99Z6U637bL261nS9ubnpH6DX19f9z6X0S9fXrl1zV69eJYQcU65cudJPVSbP5Ju8k3/yUE7KTf2ClnzVLPz8+XOXvX792knkZ8+e+ftrrdQ0LdMltN6AaUP9YFlSK3qoVqOEkOOP/Kpck3fyTx5KXk20lcC6i3758qX7HwA/+/sz2ooeAAAAAElFTkSuQmCC"></p><p>When you enter the code listed in <code>step 4</code>, you might notice that the <code>VBE</code> makes some adjustments to the text you enter. </p><p>For example, after you type the <code>sub statement</code>, the <code>VBE</code> automatically insert the End Sub statement, and if omit the space before or after an equal sign, the <code>VBE</code> insert the space for you. </p><p>Also, the <code>VBE</code> changes the color and capitalization of some text. This is all perfectly normal. It is just VBEâ€™s way of keeping things neat and readable.</p><p>If you followed the previous steps, you just wrote a <code>VBA Sub procedure</code>, also known as a <code>macro</code>. </p><p>When you press <code>F5</code>, VBE executes the code and follows the instructions. </p><p>In other words, VBE evaluates each statement and does what you told it to do.</p><p>This simple macro uses the following concepts:</p><ul><li>Defining a Sub procedure (the first line).</li><li>Assigning values to variables (Msg and Ans).</li><li>Using a built-in VBA function (MsgBox).</li><li>Using built-in VBA constants (vbYesNo, vbNo, and vbYes).</li><li>Using an If-Then construct (twice).</li><li>Ending a Sub procedure (the last line)</li></ul><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="using-the-macro-recorder"></a>Using the Macro recorder<a aria-hidden="true" tabindex="-1" class="hash-link" href="#using-the-macro-recorder" title="Direct link to heading">#</a></h3><p>Another way you can get code into a <code>VBA module</code> is by recording your actions, using the in-built <code>macro recorder</code>.</p><p>By the way, there is absolutely <strong>no way</strong> you can record the <code>GuessName</code> procedure shown in the preceding section. </p><p>You can record only things that you can do directly in <em>Solidworks</em>. </p><p>Displaying a message box is not in application&#x27;s normal repertoire. The macro recorder is useful, but in many cases, youâ€™ll probably need to enter at least some code manually.</p><p>We have already seen how macros are recorded. So there is no need for us to go twice for same thing. If you want to see how it is done go to Open <a href="/docs/vba-in-sw">VBA in Solidworks topic</a></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="copying-vba-code"></a>Copying VBA code<a aria-hidden="true" tabindex="-1" class="hash-link" href="#copying-vba-code" title="Direct link to heading">#</a></h3><p>The final method for getting <code>code</code> into a <code>VBA module</code> is to copy it from another module or from some other place (such as a Web site i.e. Solidworks forum). </p><p>For example, a <code>Sub or Function procedure</code> that you write for one project might also be useful in another project. </p><p>Instead of <em>wasting time</em> in <code>re-entering</code> the code, you can activate the module and use the normal Clipboard <code>copy-and-paste</code> procedures. </p><p>After pasting it into a <code>VBA module</code>, you can modify the code if necessary. </p><p>Youâ€™ll also find lots of VBA code examples on the Web. </p><p>If youâ€™d like to try them, select the code in your browser and press <code>Ctrl+C</code> to <em>copy</em> it. Then, activate a module and press <code>Ctrl+V</code> to <em>paste</em> it.</p><p>Next post will be about <code>Sub and Function Procedures</code>.</p></div></article><div class="margin-vert--lg"><nav class="pagination-nav" aria-label="Blog list page navigation"><div class="pagination-nav__item"><a class="pagination-nav__link" href="/docs/vba/vba-vbe"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Â« Visual Basic Editor (VBE)</div></a></div><div class="pagination-nav__item pagination-nav__item--next"><a class="pagination-nav__link" href="/docs/vba/vba-procedures"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Sub and Function Procedures Â»</div></a></div></nav></div></div></div><div class="col col--3"><div class="tableOfContents_3SO_"><ul class="table-of-contents table-of-contents__left-border"><li><a href="#project-window" class="table-of-contents__link">Project Window</a><ul><li><a href="#adding-a-new-vba-module" class="table-of-contents__link">Adding a new VBA module</a></li><li><a href="#removing-a-new-vba-module" class="table-of-contents__link">Removing a new VBA module</a></li><li><a href="#exporting-and-importing-of-objects" class="table-of-contents__link">Exporting and Importing of objects</a></li></ul></li><li><a href="#code-window" class="table-of-contents__link">Code Window</a><ul><li><a href="#minimize-and-maximize-code-windows" class="table-of-contents__link">Minimize and maximize Code windows</a></li><li><a href="#creating-a-module" class="table-of-contents__link">Creating a Module</a></li><li><a href="#inserting-vba-code-into-a-module" class="table-of-contents__link">Inserting VBA code into a Module</a></li><li><a href="#entering-code-directly-into-a-module" class="table-of-contents__link">Entering code directly into a module</a></li><li><a href="#using-the-macro-recorder" class="table-of-contents__link">Using the Macro recorder</a></li><li><a href="#copying-vba-code" class="table-of-contents__link">Copying VBA code</a></li></ul></li></ul></div></div></div></div></main></div></div><footer class="footer"><div class="container"><div class="row footer__links"><div class="col footer__col"><h4 class="footer__title">Tutorials</h4><ul class="footer__items"><li class="footer__item"><a class="footer__link-item" href="/docs/vba-Intro">VBA Introduction</a></li><li class="footer__item"><a class="footer__link-item" href="/docs/vba-in-sw">VBA in Solidworks</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">Community</h4><ul class="footer__items"><li class="footer__item"><a href="https://www.facebook.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Facebook</a></li><li class="footer__item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" rel="noopener noreferrer" class="footer__link-item">YouTube</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">More</h4><ul class="footer__items"><li class="footer__item"><a href="mailto:thecadcoder@gmail.com" target="_blank" rel="noopener noreferrer" class="footer__link-item">E-Mail</a></li><li class="footer__item"><a href="https://www.buymeacoffee.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Buy Me a Coffee</a></li></ul></div></div><div class="text--center"><div>Copyright Â© 2020 The Cad Coder, Inc. Built with Docusaurus.</div></div></div></footer></div>
<script src="/styles.8dac73e6.js"></script>
<script src="/runtime~main.c20766ae.js"></script>
<script src="/main.c76857e4.js"></script>
<script src="/1.edd1b653.js"></script>
<script src="/2.266b950c.js"></script>
<script src="/94.4c75db3c.js"></script>
<script src="/95.3eb551e8.js"></script>
<script src="/f976f453.ebf1a006.js"></script>
<script src="/17896441.bf30d83f.js"></script>
<script src="/ab0be63b.a7018905.js"></script>
</body>
</html>