<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- begin _includes/seo.html --><title>Solidworks Macro - Edit Linear Sketch Pattern - The CAD Coder</title>
<meta name="description" content="In this post, I tell you about how to Edit Linear Sketch Pattern using Solidworks VBA Macros in a Sketch.">



<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="Solidworks Macro - Edit Linear Sketch Pattern">
<meta property="og:url" content="https://thecadcoder.com/solidworks-macros/edit-linear-skech-pattern/">


  <meta property="og:description" content="In this post, I tell you about how to Edit Linear Sketch Pattern using Solidworks VBA Macros in a Sketch.">







  <meta property="article:published_time" content="2023-01-05T19:57:44-05:00">






<link rel="canonical" href="https://thecadcoder.com/solidworks-macros/edit-linear-skech-pattern/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": null,
      "url": "https://thecadcoder.com/"
    
  }
</script>







<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-117501871-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-117501871-2', { 'anonymize_ip': true});
</script>

<!-- end _includes/seo.html -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">
  <link
    href="/feed.xml"
    type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/main.css">

  <meta name="google-site-verification" content="OeSBbUv_kXDkDxaeoLixjE1BYxlbQRINt58H1UGbSMY" />

  
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        <img src="/assets/logo.png" width="30" height="30" class="img-fluid" alt="">
        <span>The CAD Coder</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a  class="nav-link"   href="/vba/vba-Introduction/"><span>VBA</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="active nav-link" style="border-bottom: 1px solid #fff;"   href="/Solidworks-macro-guide/"><span>Solidworks VBA Macro</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-csharp-api-tutorials/"><span>Solidworks C# API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-cpp-api-tutorials/"><span>Solidworks C++ API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/resources/"><span>Resources</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/aboutMe/"><span>About</span></a>
            </li>
            
            <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li> -->
        </ul>
        <!-- <a class="btn btn-outline-success my-2 my-sm-0" href="/seach-document/" role="button">
            <i class="fas fa-search"></i>
        </a> -->
    </div>
</nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-lg-2 col-sm-4">
  <div class="sidebar sticky" style="width: 100%;">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">General - Solidworks Functions</span>
        

        
        <ul>
          
            <li><a href="/Solidworks-macro-guide/">Introduction</a></li>
          
            <li><a href="/solidworks-macros/open-new-document/">Open new Part document</a></li>
          
            <li><a href="/solidworks-macros/open-assembly-and-drawing/">Open Assembly and Drawing document</a></li>
          
            <li><a href="/solidworks-macros/select-plane-from-tree/">Selection Methods</a></li>
          
            <li><a href="/solidworks-macros/open-saved-document/">Open Saved Documents</a></li>
          
            <li><a href="/solidworks-macros/unit-correction/">Fix Unit Issue</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Lines</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/sketch-create-line/">Create Line</a></li>
          
            <li><a href="/solidworks-macros/sketch-create-centerline/">Create CenterLine</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Rectangles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-corner-rectangle/">Create Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-center-rectangle/">Create Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-corner-rectangle/">Create 3-Point Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-center-rectangle/">Create 3-Point Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-parallelogram/">Create A Parallelogram</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Circles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-circle/">Create Circle</a></li>
          
            <li><a href="/solidworks-macros/create-circle-by-radius/">Create Circle By Radius</a></li>
          
            <li><a href="/solidworks-macros/create-perimeter-circle/">Create Perimeter Circle</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Arcs</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc/">Create Centerpoint Arc</a></li>
          
            <li><a href="/solidworks-macros/create-tangent-arc/">Create Tangent Arc</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc/">Create 3-Point Arc</a></li>
          
            <li><a href="/solidworks-macros/polygon/">Create Polygon</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Slots</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-straight-slot/">Create a Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-straight-slot/">Create a Centerpoint Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc-slot/">Create a 3-Point Arc Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc-slot/">Create a Centerpoint Arc Slot</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Point and Spline</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-point/">Create a Point</a></li>
          
            <li><a href="/solidworks-macros/create-spline/">Create a Spline</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Fillet and Chamfer</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-sketch-fillet/">Create a Fillet</a></li>
          
            <li><a href="/solidworks-macros/create-sketch-chamfer/">Create a Chamfer</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Trim and Extend</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/trim-entities/">Trim Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/extend-entities/">Extend Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Patterns</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/linear-skech-pattern/">Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-linear-skech-pattern/" class="active">Edit Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/circular-skech-pattern/">Circular Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-circular-skech-pattern/">Edit Circular Sketch Pattern</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Move and Rotate</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/move-copy-sketch-entities/">Move/Copy Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/rotate-copy-sketch-entities/">Rotate/Copy Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Relations</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/toggle-display-sketch-relation/">Toggle (Hide/Show) Sketch Relations</a></li>
          
            <li><a href="/solidworks-macros/add-sketch-relations/">Add Sketch Relations (Constraints)</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Dimensions</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/add-dimension-methods/">Add dimension to Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Extrudes</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-extrude-feature/">Extrude Feature</a></li>
          
            <li><a href="/solidworks-macros/create-revolved-feature/">Revolved Boss/Base Feature</a></li>
          
            <li><a href="/solidworks-macros/create-sweep-feature/">Sweep Boss/Base Feature</a></li>
          
            <li><a href="/solidworks-macros/create-lofted-boss-feature/">Lofted Boss/Base Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Cuts</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-extrude-cut-feature/">Extrude Cut Feature</a></li>
          
            <li><a href="/solidworks-macros/create-revolve-cut-feature/">Revolve Cut Feature</a></li>
          
            <li><a href="/solidworks-macros/create-sweep-cut-feature/">Sweep Cut Feature</a></li>
          
            <li><a href="/solidworks-macros/create-loft-cut-feature/">Lofted Cut Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Holes and Threads</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-hole-from-hole-wizard/">Holes from Hole Wizard</a></li>
          
            <li><a href="/solidworks-macros/create-threads/">Threads</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Fillet & Chamfer</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-fillet/">Fillet Feature</a></li>
          
            <li><a href="/solidworks-macros/create-chamfer/">Chamfer Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Mirror & Patterns</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-mirror/">Mirror Feature</a></li>
          
            <li><a href="/solidworks-macros/create-linear-patterns/">Linear Pattern Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-circular-patterns/">Circular Pattern Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-sketch-driven-pattern/">Sketch Driven Pattern Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Transformation</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/create-rib/">Rib Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-draft/">Draft Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-shell/">Shell Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-wrap/">Wrap Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-scale/">Scale Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Reference Geometry</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/create-reference-plane/">Reference Plane</a></li>
          
            <li><a href="/solidworks-vba-macros/create-reference-axis/">Reference Axis</a></li>
          
            <li><a href="/solidworks-vba-macros/create-reference-coordinate/">Reference Co-Ordinate</a></li>
          
            <li><a href="/solidworks-vba-macros/create-reference-point/">Reference Point</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Assembly - General</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/assembly-insert-component/">Insert Component</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-unfix-component/">Unfix Component</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Assembly - Standard Mates</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/assembly-conicident-mate/">Add Coincident Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-parallel-mate/">Add Parallel Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-perpendicular-mate/">Add Perpendicular Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-tangent-mate/">Add Tangent Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-concentric-mate/">Add Concentric Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-distance-mate/">Add Distance Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-angle-mate/">Add Angle Mate</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Assembly - Advanced Mates</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/assembly-width-mate/">Add Width Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-symmetric-mate/">Add Symmetric Mate</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Assembly - Editing Mates</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/assembly-rename-mate/">Rename Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-edit-distance-mate/">Edit Distance Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-toggle-mate-alignment/">Toggle Mate Alignment</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-delete-mate/">Delete Mate</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Assembly - Components</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/assembly-insert-virtual-part/">Insert Virtual Part</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-insert-virtual-assembly/">Insert Virtual Assembly</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-copy-with-mate/">Copy With Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-hide-component/">Hide Selected Component</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-show-component/">Show Selected Component</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-suppress-component/">Suppress Selected Component</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-unsuppress-component/">Unsuppress Selected Component</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Assembly - Misc</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/assembly-insert-folder/">Insert Folder</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-traverse-sequentially/">Traverse Components Sequentially</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Drawing - Insert Views</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/drawing-1stangle-standard3views/">Standard 3 View [1st Angle]</a></li>
          
            <li><a href="/solidworks-vba-macros/drawing-3rdangle-standard3views/">Standard 3 View [3rd Angle]</a></li>
          
            <li><a href="/solidworks-vba-macros/drawing-insert-modelview/">Insert Model View</a></li>
          
            <li><a href="/solidworks-vba-macros/drawing-insert-projectionview/">Insert Projection View</a></li>
          
            <li><a href="/solidworks-vba-macros/drawing-insert-auxilaryview/">Insert Auxilary View</a></li>
          
            <li><a href="/solidworks-vba-macros/drawing-insert-sectionview/">Insert Section View</a></li>
          
            <li><a href="/solidworks-vba-macros/drawing-insert-detailview/">Insert Detail View</a></li>
          
            <li><a href="/solidworks-vba-macros/drawing-brokenout-view/">Insert Broken-out View</a></li>
          
            <li><a href="/solidworks-vba-macros/drawing-crop-view/">Insert Crop View</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Drawing - View Position and Boundary</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/drawing-get-view-position/">Get View Position</a></li>
          
            <li><a href="/solidworks-vba-macros/drawing-get-view-outer-boundary/">Get View Outer Boundary</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Drawing - Get Views and Views Count</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/drawing-first-view-in-current-sheet/">First/Next View In Current Sheet</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Others</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/convert-to-construction-sketch-segment/">Convert to Construction Sketch</a></li>
          
            <li><a href="/solidworks-macros/split-sketch-segments/">Split Open/Closed Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>

</div>
      <div class="col-md-9 col-lg-10 col-sm-8">
        <div>
          <div id="main" role="main">

  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    
    <meta itemprop="headline" content="Solidworks Macro - Edit Linear Sketch Pattern">
    
    <meta itemprop="description" content="In this post, I tell you about how to Edit Linear Sketch Pattern using Solidworks VBA Macros in a Sketch.">
    
    
    <meta itemprop="datePublished" content="2023-01-05T19:57:44-05:00">
    

    <div class="page__inner-wrap">
      
      <header>
        <h1 id="page-title" class="page__title" itemprop="headline">Solidworks Macro - Edit Linear Sketch Pattern
</h1>
        

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          14 minute read
        
      </span>
    
  </p>


      </header>
      

      <section class="page__content" itemprop="text">
        
        <aside class="sidebar__right sticky">
          <nav class="toc">
            <header>
              <h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4>
            </header>
            <ul class="toc__menu"><li><a href="#video-of-code-on-youtube">Video of Code on YouTube</a></li><li><a href="#for-experience-macro-developers">For Experience Macro Developers</a></li><li><a href="#for-beginner-macro-developers">For Beginner Macro Developers</a><ul><li><a href="#cases">Cases</a><ul><li><a href="#case-1--increase-total-number-of-instances-along-the-x-axis">CASE 1 : Increase Total number of instances along the “X” axis</a></li><li><a href="#case-2--increase-total-number-of-instances-along-the-y-axis">CASE 2 : Increase Total number of instances along the “Y” axis</a></li><li><a href="#case-3--update-angle-for-direction-1-along-the-x-axis">CASE 3 : Update Angle for direction 1 along the “X” axis</a></li><li><a href="#case-4--update-angle-for-direction-1-along-the-y-axis">CASE 4 : Update Angle for direction 1 along the “Y” axis</a></li><li><a href="#case-5--number-of-instances-to-delete">CASE 5 : Number of instances to delete</a></li><li><a href="#case-6--display-the-spacing-between-instances-dimension-along-the-y-axis">CASE 6 : Display the spacing between instances dimension along the “Y” axis</a></li><li><a href="#case-7--display-the-angle-dimension-between-axes">CASE 7 : Display the angle dimension between axes</a></li><li><a href="#case-8--display-the-number-of-instances-in-the-x-direction">CASE 8 : Display the number of instances in the “X” direction</a></li><li><a href="#case-9--display-the-number-of-instances-in-the-y-direction">CASE 9 : Display the number of instances in the “Y” direction</a></li><li><a href="#case-10--multiple-entities-as-seed">CASE 10 : Multiple entities as Seed</a></li></ul></li><li><a href="#note">NOTE</a></li></ul></li></ul>

            <br/>
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Vertical Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="4311368222"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          </nav>
        </aside>
        
        <div>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Horizontal Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="6007593278"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          <p>In this post, I tell you about <strong>how to Edit Linear Sketch Pattern using Solidworks VBA Macros</strong> in a Sketch.</p>

<p>This post is extension of previous <strong><a href="/solidworks-macros/linear-skech-pattern">Solidworks Macro - Linear Sketch Pattern</a></strong> post.</p>

<p>I recommend you to read <strong><a href="/solidworks-macros/linear-skech-pattern">Solidworks Macro - Linear Sketch Pattern</a></strong> post because we are using same code sample.</p>

<hr />

<h2 id="video-of-code-on-youtube">Video of Code on YouTube</h2>

<p>Please see below video how we can <em>Edit Linear Sketch Pattern</em> in <strong>Solidworks VBA macro</strong>.</p>

<iframe src="https://www.youtube.com/embed/4pLUprIxXHU" frameborder="0" allowfullscreen=""></iframe>
<p><br /></p>

<p>Please note that there is <strong>no explanation</strong> in the video.</p>

<p>Why we write our code this way is <strong>explained</strong> in this post.</p>

<hr />

<h2 id="for-experience-macro-developers">For Experience Macro Developers</h2>

<p>If you are an experienced <strong>Solidworks Macro developer</strong>, then you are looking for a specific code sample.</p>

<p>Below is the code for <strong>Edit Linear Sketch Pattern</strong> from <strong>Solidworks VBA Macro</strong>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mf">0.785</span><span class="p">,</span> <span class="mf">1.5708</span><span class="p">,</span> <span class="s">"(3,2)(2,1)"</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong>Method Name</strong>: <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code></p>

<p><strong>Description</strong>: Edit <em>Linear Sketch Pattern</em>.</p>

<p><strong>Prerequisites</strong>: To <em>edit</em> a <strong>Linear Sketch Pattern</strong> a Solidworks Sketch entity or entities, first, we need the following things:</p>

<ol>
  <li>Existing Linear Sketch Pattern</li>
</ol>

<p><strong>How it works</strong>:</p>

<ul>
  <li>
    <p>For <strong>Edit a Linear Sketch Pattern</strong>, first, we need to <strong>create</strong> a variable of <code class="language-plaintext highlighter-rouge">Boolean</code> type.</p>
  </li>
  <li>
    <p>After creating variable, we need to set the value of this <code class="language-plaintext highlighter-rouge">Boolean</code> variable.</p>
  </li>
  <li>
    <p>For this, we used <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method from <strong>Solidworks Sketch Manager</strong>.</p>
  </li>
  <li>
    <p>This <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method set the value of <code class="language-plaintext highlighter-rouge">Boolean</code> type variable.</p>
  </li>
  <li>
    <p>If the editing of <em>Linear Sketch Pattern</em> is <strong>successful</strong> then <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method return <strong>True</strong> value otherwise <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> returns <strong>False</strong> value.</p>
  </li>
</ul>

<p>This <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method takes the following parameters as explained:</p>

<ul>
  <li>
    <p><strong>NumX</strong>: <em>Total number of instances along the <strong>x</strong> axis, including the seed i.e. original entity/entities.</em></p>
  </li>
  <li>
    <p><strong>NumY</strong>: <em>Total number of instances along the <strong>y</strong> axis, including the seed i.e. original entity/entities.</em></p>
  </li>
  <li>
    <p><strong>SpacingX</strong>: <em>Spacing between instances along the <strong>x</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>SpacingY</strong>: <em>Spacing between instances along the <strong>y</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>AngleX</strong>: <em>Angle for direction 1 relative to the <strong>x</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>AngleY</strong>: <em>Angle for direction 1 relative to the <strong>y</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>DeleteInstances</strong>: <em>Number of instances to delete, passed as a string in the format: “(a) (b) (c)”.</em></p>
  </li>
  <li>
    <p><strong>XSpacingDim</strong>: <em>True to display the spacing between instances dimension along the <strong>x</strong> axis in the graphics area, false to not</em></p>
  </li>
  <li>
    <p><strong>YSpacingDim</strong>: <em>True to display the spacing between instances dimension along the <strong>y</strong> axis in the graphics area, false to not</em></p>
  </li>
  <li>
    <p><strong>AngleDim</strong>: <em>True to display the angle dimension between axes in the graphics area, false to not.</em></p>
  </li>
  <li>
    <p><strong>CreateNumOfInstancesDimInXDir</strong>: <em>True to display the number of instances in the <strong>x</strong> direction dimension in the graphics area, false to not.</em></p>
  </li>
  <li>
    <p><strong>CreateNumOfInstancesDimInYDir</strong>: <em>True to display the number of instances in the <strong>y</strong> direction dimension in the graphics area, false to not.</em></p>
  </li>
  <li>
    <p><strong>Seed</strong>: <em>List of the names of the entities, separated by the underscore character (_), that comprise the seed pattern (e.g., Line1_Line2_Line3_Line4 for a rectangular-shaped seed pattern).</em></p>
  </li>
</ul>

<p><strong>Return Value</strong>:</p>

<ul>
  <li>
    <p><strong>True</strong>: <em>If Editing of Linear Sketch Pattern is “Success”.</em></p>
  </li>
  <li>
    <p><strong>False</strong>: <em>If Editing of Linear Sketch Pattern is “Fail”.</em></p>
  </li>
</ul>

<p>If you want more detailed explaination then please read further otherwise this will help you to <em>edit</em> a <strong>Linear Sketch Pattern</strong>.</p>

<hr />

<h2 id="for-beginner-macro-developers">For Beginner Macro Developers</h2>

<p>In this post, I tell you about <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method from <strong>Solidworks</strong> <code class="language-plaintext highlighter-rouge">SketchManager</code> object.</p>

<p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>.</p>

<p>So <strong><em>use this method</em></strong> if you want to <em>edit Linear Sketch Pattern</em>.</p>

<p>Below is the <code class="language-plaintext highlighter-rouge">code</code> sample to <em>edit Linear Sketch Pattern</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="c1">' Create variable for Solidworks Sketch Manager</span>
<span class="k">Dim</span> <span class="nv">swSketchManager</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchManager</span>

<span class="c1">' Create Variable for Solidworks Sketch Segment</span>
<span class="k">Dim</span> <span class="nv">swSketchSegment</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchSegment</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Create string type variable for storing default part location</span>
  <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>

  <span class="c1">' Set value of this string type variable to "Default part template"</span>
  <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>

  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

  <span class="c1">' Select Front Plane</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>

  <span class="c1">' Set Sketch manager for our sketch</span>
  <span class="k">Set</span> <span class="n">swSketchManager</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span>

  <span class="c1">' Insert a sketch into selected plane</span>
  <span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
  
  <span class="c1">' Set Sketch Segment value and Create a Circle</span>
  <span class="k">Set</span> <span class="n">swSketchSegment</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateCircleByRadius</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mf">0.2</span><span class="p">)</span>
  
  <span class="c1">' De-select the lines after creation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

  <span class="c1">' Select Circle we want to Pattern</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Arc1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Create a Linear Sketch Pattern</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">)</span>
  
  <span class="c1">' De-select the Sketch Segment after Linear Sketch Pattern</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
  
  <span class="c1">' Show Front View after Linear Sketch Pattern</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ShowNamedView2</span> <span class="s">""</span><span class="p">,</span> <span class="n">swStandardViews_e</span><span class="p">.</span><span class="n">swFrontView</span>
  
  <span class="c1">' Zoom to fit screen in Solidworks Window</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ViewZoomtofit2</span>

  <span class="c1">' Edit a Linear Sketch Pattern &lt;--- FROM HERE IS THE LAST LINE I EXPLAIN</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>Since this post is <em>an extension</em> of previous <strong><a href="/solidworks-macros/linear-skech-pattern">Solidworks Macro - Linear Sketch Pattern</a></strong> post, then I will start explaining from <strong>Last line</strong> only.</p>

<p>If you want to understand every line of code, then please visit <strong><a href="/solidworks-macros/linear-skech-pattern">Solidworks Macro - Linear Sketch Pattern</a></strong> post “first”, then read this post.</p>

<p>By doing this, <em>you learn 2 thing</em>:</p>

<ol>
  <li>
    <p><em>How to create a Linear Sketch Pattern</em></p>
  </li>
  <li>
    <p><em>How to edit/modify an existing Linear Sketch Pattern</em></p>
  </li>
</ol>

<p>I also give some <em>links</em> so that you can go through them if there are anything I <em>explained</em> in previous posts.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p>For “<strong>editing</strong>” a Linear Sketch pattern, we need <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method from <em>Solidworks Sketch Manager</em> object/variable.</p>

<p>This <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method takes the following parameters as explained:</p>

<ul>
  <li>
    <p><strong>NumX</strong>: <em>Total number of instances along the <strong>x</strong> axis, including the seed i.e. original entity/entities.</em></p>
  </li>
  <li>
    <p><strong>NumY</strong>: <em>Total number of instances along the <strong>y</strong> axis, including the seed i.e. original entity/entities.</em></p>
  </li>
  <li>
    <p><strong>SpacingX</strong>: <em>Spacing between instances along the <strong>x</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>SpacingY</strong>: <em>Spacing between instances along the <strong>y</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>AngleX</strong>: <em>Angle for direction 1 relative to the <strong>x</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>AngleY</strong>: <em>Angle for direction 1 relative to the <strong>y</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>DeleteInstances</strong>: <em>Number of instances to delete, passed as a string in the format: “(a) (b) (c)”.</em></p>
  </li>
  <li>
    <p><strong>XSpacingDim</strong>: <em>True to display the spacing between instances dimension along the <strong>x</strong> axis in the graphics area, false to not</em></p>
  </li>
  <li>
    <p><strong>YSpacingDim</strong>: <em>True to display the spacing between instances dimension along the <strong>y</strong> axis in the graphics area, false to not</em></p>
  </li>
  <li>
    <p><strong>AngleDim</strong>: <em>True to display the angle dimension between axes in the graphics area, false to not.</em></p>
  </li>
  <li>
    <p><strong>CreateNumOfInstancesDimInXDir</strong>: <em>True to display the number of instances in the <strong>x</strong> direction dimension in the graphics area, false to not.</em></p>
  </li>
  <li>
    <p><strong>CreateNumOfInstancesDimInYDir</strong>: <em>True to display the number of instances in the <strong>y</strong> direction dimension in the graphics area, false to not.</em></p>
  </li>
  <li>
    <p><strong>Seed</strong>: <em>List of the names of the entities, separated by the underscore character (_), that comprise the seed pattern (e.g., Line1_Line2_Line3_Line4 for a rectangular-shaped seed pattern).</em></p>
  </li>
</ul>

<p><strong>NOTE:</strong> In <em>Seed</em>, adding underscore(_) after selected entity is important, otherwise code will note work.</p>

<p>After the function complete, we get following results:</p>

<p><strong>Return Value</strong>:</p>

<ul>
  <li>
    <p><strong>True</strong>: <em>If Editing of Linear Sketch Pattern is “Success”.</em></p>
  </li>
  <li>
    <p><strong>False</strong>: <em>If Editing of Linear Sketch Pattern is “Fail”.</em></p>
  </li>
</ul>

<p>In our code, I have used following values:</p>

<ul>
  <li>
    <p><strong>NumX</strong> : <em>I have used <strong>5</strong> as Total number of instances along the <strong>x</strong> axis including original circle.</em></p>
  </li>
  <li>
    <p><strong>NumY</strong> : <em>I have used <strong>1</strong> as Total number of instances along the <strong>y</strong> axis which includes original circle only.</em></p>
  </li>
</ul>

<blockquote>
  <p><em>Even uf you don’t want to pattern in <strong>Y</strong> direction, you have to give atleast 1 as a value. Same goes for <strong>X</strong> direction.</em></p>
</blockquote>

<ul>
  <li>
    <p><strong>SpacingX</strong> : <em>I use <strong>1</strong> as Spacing between instances along the <strong>x</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>SpacingY</strong> : <em>I use <strong>0</strong> Spacing between instances along the <strong>y</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>AngleX</strong> : <em>I use <strong>0</strong> Angle for direction 1 relative to the <strong>x</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>AngleY</strong> : <em>I use <strong>0</strong> Angle for direction 1 relative to the <strong>y</strong> axis.</em></p>
  </li>
  <li>
    <p><strong>DeleteInstances</strong> : <em>I use <strong>”“</strong> as Number of instances to delete, because I don’t want to delete any instances.</em></p>
  </li>
  <li>
    <p><strong>XSpacingDim</strong> : <em>I use <strong>True</strong> to display the spacing between instances dimension along the <strong>x</strong> axis in the graphics area.</em></p>
  </li>
  <li>
    <p><strong>YSpacingDim</strong> : <em>I use <strong>False</strong> to display the spacing between instances dimension along the <strong>y</strong> axis in the graphics area.</em></p>
  </li>
  <li>
    <p><strong>AngleDim</strong> : <em>I use <strong>True</strong> to display the angle dimension between axes in the graphics area.</em></p>
  </li>
  <li>
    <p><strong>CreateNumOfInstancesDimInXDir</strong> : <em>I use <strong>True</strong> to display the number of instances in the <strong>x</strong> direction dimension in the graphics area.</em></p>
  </li>
  <li>
    <p><strong>CreateNumOfInstancesDimInYDir</strong> : <em>I use <strong>False</strong> to display the number of instances in the <strong>y</strong> direction dimension in the graphics area.</em></p>
  </li>
  <li>
    <p><strong>Seed</strong> : <em>I use <strong>Arc1_</strong> as the seed of this Edit Pattern Function. We can select multiple sketch entities into existing Linear Sketch Pattern.</em></p>
  </li>
</ul>

<hr />

<h3 id="cases">Cases</h3>

<p>In this section, we will go through different cases by</p>

<ul>
  <li>
    <p><em>Modifying different parameters</em></p>

    <ol>
      <li>
        <p><em>A basic 1 line description</em></p>
      </li>
      <li>
        <p><em>Sample Code of parameter modification</em></p>
      </li>
    </ol>
  </li>
  <li>
    <p><em>See images, before and after parameter modification</em></p>
  </li>
</ul>

<hr />

<h4 id="case-1--increase-total-number-of-instances-along-the-x-axis">CASE 1 : Increase Total number of instances along the “X” axis</h4>

<p>To increase Total number of instances along the “X” axis, we need to update <strong>NumX</strong> parameter in <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method.</p>

<p>In my previous <strong><a href="/solidworks-macros/linear-skech-pattern">Solidworks Macro - Linear Sketch Pattern</a></strong> post, we created a Linear pattern <em>3 instances</em> in <em>x-direction</em>.</p>

<p><strong><em>Code sample:</em></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p>In above code, we update the number of instances from <em>3 instances</em> to <em>5 instances</em>.</p>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>number of instance in X-direction</strong>.</p>

<p><strong>Before Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-linear-pattern.png" alt="after-linear-pattern" /></p>

<p><strong>After Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-numX.png" alt="edit-linear-pattern-numX" /></p>

<hr />

<h4 id="case-2--increase-total-number-of-instances-along-the-y-axis">CASE 2 : Increase Total number of instances along the “Y” axis</h4>

<p>To increase Total number of instances along the “Y” axis, we need to update <strong>NumY</strong> parameter in <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method.</p>

<p>If we increase the number of instances in <em>Y-direction</em>, then we also need to give value for <strong>SpacingY</strong> parameter.</p>

<p><em>We need following parameters to update:</em></p>

<ul>
  <li>
    <p><strong>NumY</strong></p>
  </li>
  <li>
    <p><strong>SpacingY</strong></p>
  </li>
</ul>

<p><em>We will use following values for these parameters:</em></p>

<ul>
  <li>
    <p><strong>NumY</strong>: <em>4</em></p>
  </li>
  <li>
    <p><strong>SpacingY</strong>: <em>0.75</em></p>
  </li>
</ul>

<p><strong><em>Code sample:</em></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>number of instance in Y-direction</strong>.</p>

<p><strong>Before Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-numX.png" alt="edit-linear-pattern-numX" /></p>

<p><strong>After Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-numY.png" alt="edit-linear-pattern-numY" /></p>

<p><strong><em>NOTE:</em></strong></p>

<p>As you notice in previous image, when you give values for <strong>NumY</strong> and <strong>SpacingY</strong>, number of instances increased in X-direction!</p>

<p><em>Why the instances are increased in X-direction not in Y-direction as I was expecting?</em></p>

<p>This question comes in my mind after seeing the result!</p>

<p>Reason is that we did not give value of <strong>AngleY</strong> parameter.</p>

<p>If you provide the value of <strong>AngleY</strong> parameter then we can have instances in Y-direction.</p>

<p>More detail with example in <strong>CASE 4</strong>.</p>

<hr />

<h4 id="case-3--update-angle-for-direction-1-along-the-x-axis">CASE 3 : Update Angle for direction 1 along the “X” axis</h4>

<p>To update Angle for <em>direction 1</em> along the “X” axis, we need to update <strong>AngleX</strong> parameter in <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method.</p>

<p><em>We will use following value for <strong>AngleX</strong> parameter:</em></p>

<ul>
  <li><strong>AngleX</strong>: <em>0.785</em>.</li>
</ul>

<p><strong><em>Code sample:</em></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mf">0.785</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Angle for direction 1 along the “X” axis</strong>.</p>

<p><strong>Before Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-numY.png" alt="edit-linear-pattern-numY" /></p>

<p><strong>After Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-angleX.png" alt="edit-linear-pattern-angleX" /></p>

<p><strong><em>NOTE:</em></strong></p>

<p>In this case, we use <strong>AngleX</strong> = <em>0.785</em>.</p>

<p>This value is in <strong><em>Radian</em></strong>.</p>

<p>Hence, <em>0.785</em> Radian = <em>44.999 Degree</em></p>

<p>So we have update Angle for direction 1 in <strong>~45 degree</strong>.</p>

<hr />

<h4 id="case-4--update-angle-for-direction-1-along-the-y-axis">CASE 4 : Update Angle for direction 1 along the “Y” axis</h4>

<p>To update Angle for <em>direction 2</em> along the “Y” axis, we need to update <strong>AngleY</strong> parameter in <code class="language-plaintext highlighter-rouge">EditLinearSketchStepAndRepeat</code> method.</p>

<p><em>We will use following value for <strong>AngleY</strong> parameter:</em></p>

<ul>
  <li><strong>AngleX</strong>: <em>1.5708</em>.</li>
</ul>

<p><strong><em>Code sample:</em></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mf">0.785</span><span class="p">,</span> <span class="mf">1.5708</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Angle for direction 2 along the “Y” axis</strong>.</p>

<p><strong>Before Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-angleX.png" alt="edit-linear-pattern-angleX" /></p>

<p><strong>After Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-angleY.png" alt="edit-linear-pattern-angleX" /></p>

<p><strong><em>NOTE:</em></strong></p>

<p>In this case, we use <strong>AngleY</strong> = <em>1.5708</em>.</p>

<p>This value is in <strong><em>Radian</em></strong>.</p>

<p>Hence, <em>1.5708</em> Radian = <em>90 Degree</em></p>

<p>So we have update Angle for direction 1 in <strong>90 degree</strong>.</p>

<hr />

<h4 id="case-5--number-of-instances-to-delete">CASE 5 : Number of instances to delete</h4>

<p>Ok, this one is a little “<strong>tricky</strong>”!!!</p>

<p>We want to delete some instance now.</p>

<p>For deleting instances, we need following:</p>

<ul>
  <li>
    <p>Deleting instance’s position with respect to <strong>X and Y directions</strong>.</p>
  </li>
  <li>
    <p>Those position in a particular format.</p>
  </li>
</ul>

<p><strong><em>Grid Position Image:</em></strong></p>

<p>I tried my best to describe you this position system in Grid format using image.</p>

<p>Please see below image for this Grid position.</p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-deleteInstances.png" alt="edit-linear-pattern-deleteInstances" /></p>

<p>We are going to delete 2 instances.</p>

<p><strong>1st Instance</strong>: First we will get the position of this instance.</p>

<ul>
  <li>
    <p><strong>In X-Direction</strong>: As you can see in above image, position of this instance is 3 in Grid position system for X-Direction.</p>
  </li>
  <li>
    <p><strong>In Y-Direction</strong>: As you can see in above image, position of this instance is 2 in Grid position system for Y-Direction.</p>
  </li>
</ul>

<p><strong>2nd Instance</strong>: First we will get the position of this instance.</p>

<ul>
  <li>
    <p><strong>In X-Direction</strong>: As you can see in above image, position of this instance is 2 in Grid position system for X-Direction.</p>
  </li>
  <li>
    <p><strong>In Y-Direction</strong>: As you can see in above image, position of this instance is 1 in Grid position system for Y-Direction.</p>
  </li>
</ul>

<p><strong>Position in special format</strong>: After we get the position, we need to put “Grid position” of each instance inside <em>a bracket (or paranthesis)</em>.</p>

<p>One thing to note here is that, there should be no “<strong>comma</strong>” between <strong>bracket (or paranthesis)</strong>.</p>

<p>Please see below code sample for detail.</p>

<p><strong><em>Code sample:</em></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mf">0.785</span><span class="p">,</span> <span class="mf">1.5708</span><span class="p">,</span> <span class="s">"(3,2)(2,1)"</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<hr />

<h4 id="case-6--display-the-spacing-between-instances-dimension-along-the-y-axis">CASE 6 : Display the spacing between instances dimension along the “Y” axis</h4>

<p>In our code sample, we display the spacing between instances dimension along the <strong>X</strong> axis.</p>

<p>We do this by <strong><code class="language-plaintext highlighter-rouge">XSpacingDim = True</code></strong>.</p>

<p>If we want to display the spacing between instances dimension along the <strong>Y</strong> axis.</p>

<p>For that we need to set <strong><code class="language-plaintext highlighter-rouge">YSpacingDim = True</code></strong>.</p>

<p><strong><em>Code sample:</em></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mf">0.785</span><span class="p">,</span> <span class="mf">1.5708</span><span class="p">,</span> <span class="s">"(3,2)(2,1)"</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows after we update value for <strong>display dimension along the **Y</strong> axis**.</p>

<p><strong>Before Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-YSpacingDim.png" alt="edit-linear-pattern-YSpacingDim" /></p>

<hr />

<h4 id="case-7--display-the-angle-dimension-between-axes">CASE 7 : Display the angle dimension between axes</h4>

<p>In our code sample, we display the angle dimension between axes.</p>

<p>We do this by <strong><code class="language-plaintext highlighter-rouge">AngleDim = True</code></strong>.</p>

<p>If we don’t want to display the angle dimension between axes then we need to set <strong><code class="language-plaintext highlighter-rouge">AngleDim = False</code></strong>.</p>

<p><strong><em>Code sample:</em></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mf">0.785</span><span class="p">,</span> <span class="mf">1.5708</span><span class="p">,</span> <span class="s">"(3,2)(2,1)"</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows after we update value to <code class="language-plaintext highlighter-rouge">False</code> for <strong>the angle dimension between axes</strong>.</p>

<p><strong>Before Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-AngleDim.png" alt="edit-linear-pattern-AngleDim" /></p>

<hr />

<h4 id="case-8--display-the-number-of-instances-in-the-x-direction">CASE 8 : Display the number of instances in the “X” direction</h4>

<p>In our code sample, we display the number of instances along the <strong>X</strong> axis.</p>

<p>We do this by <strong><code class="language-plaintext highlighter-rouge">CreateNumOfInstancesDimInXDir = True</code></strong>.</p>

<p>If we don’t want to display the number of instances along the <strong>X</strong> axis then we need to set <strong><code class="language-plaintext highlighter-rouge">CreateNumOfInstancesDimInXDir = False</code></strong>.</p>

<p><strong><em>Code sample:</em></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mf">0.785</span><span class="p">,</span> <span class="mf">1.5708</span><span class="p">,</span> <span class="s">"(3,2)(2,1)"</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows after we update value to <code class="language-plaintext highlighter-rouge">False</code> for <strong>not display the number of instances in the X direction</strong>.</p>

<p><strong>Before Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-CreateNumOfInstancesDimInXDir.png" alt="edit-linear-pattern-CreateNumOfInstancesDimInXDir" /></p>

<hr />

<h4 id="case-9--display-the-number-of-instances-in-the-y-direction">CASE 9 : Display the number of instances in the “Y” direction</h4>

<p>In our code sample, we don’t display the number of instances along the <strong>Y</strong> axis.</p>

<p>We do this by <strong><code class="language-plaintext highlighter-rouge">CreateNumOfInstancesDimInYDir = False</code></strong>.</p>

<p>If we want to display the number of instances along the <strong>Y</strong> axis then we need to set <strong><code class="language-plaintext highlighter-rouge">CreateNumOfInstancesDimInYDir = True</code></strong>.</p>

<p><strong><em>Code sample:</em></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Linear Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditLinearSketchStepAndRepeat</span><span class="p">(</span><span class="mi">5</span><span class="p">,</span> <span class="mi">4</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mf">0.75</span><span class="p">,</span> <span class="mf">0.785</span><span class="p">,</span> <span class="mf">1.5708</span><span class="p">,</span> <span class="s">"(3,2)(2,1)"</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows after we update value to <code class="language-plaintext highlighter-rouge">True</code> for <strong>display the number of instances in the Y direction</strong>.</p>

<p><strong>Before Edit Linear Sketch Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/edit-linear-pattern-CreateNumOfInstancesDimInYDir.png" alt="edit-linear-pattern-CreateNumOfInstancesDimInXDir" /></p>

<hr />

<h4 id="case-10--multiple-entities-as-seed">CASE 10 : Multiple entities as Seed</h4>

<p>In our code sample, we use only <strong>1 circle</strong> for <em>Linear Sketch pattern</em>.</p>

<p>But in many cases we need to select <strong>many sketch entities</strong>.</p>

<p>In this condition, add the entities name with <strong>an underscore (_)</strong> one by one.</p>

<p>For example, we want to pattern a Ractangle, in this case, value of seed should be following:</p>

<ul>
  <li><strong>Seed</strong> : <strong><code class="language-plaintext highlighter-rouge">Line1_Line2_Line3_Line4_</code></strong></li>
</ul>

<hr />

<h3 id="note">NOTE</h3>

<p>It is <strong><em>very important</em></strong> to remember that, when you give distance or any other numeric value in <strong>Solidworks API</strong>, Solidworks takes that numeric value in <strong><em>Meter only</em></strong>.</p>

<p>Please see below for detail:</p>

<ul>
  <li>
    <p>Length: <strong>Meter</strong></p>
  </li>
  <li>
    <p>Angle: <strong>Radian</strong></p>
  </li>
</ul>

<p>Solidworks API does not care about your application’s Unit systems.</p>

<p>For example, I works in <strong>ANSI</strong> system means <em>inches</em> for distance. But when I used <strong>Solidworks API</strong> through <em>VBA macros or C#</em>, I need to converted numeric values.</p>

<p>Because Solidworks API output the distance in <strong>Meter</strong> which is not my requirement.</p>

<hr />

<p><strong>This is it !!!</strong></p>

<p>If you found anything to add or update, please let me know on my e-mail.</p>

<p>Hope this post helps you to <em>Edit a Linear Sketch Pattern</em> with Solidworks VBA Macros.</p>

<p>For more such tutorials on <strong>Solidworks VBA Macro</strong>, do come to this blog after sometime.</p>

<p><em>If you like the post then please share it with your friends also.</em></p>

<p><em>Do let me know by you like this post or not!</em></p>

<p><em>Till then, Happy learning!!!</em></p>

        </div>
        
        <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

      </section>

      <footer class="page__meta">
        
        


        

  <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i> Updated:</strong> <time datetime="2023-01-05T19:57:44-05:00">January 5, 2023</time></p>


      </footer>

      
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    
    <li class="page-item mr-5">
      <a class="btn btn-primary text-light" href="/solidworks-macros/linear-skech-pattern/" title="Solidworks Macro - Linear Sketch Pattern
">❮ Previous</a>
    </li>
    
    
    <li class="page-item ml-5">
      <a class="btn btn-primary text-light" href="/solidworks-macros/circular-skech-pattern/" title="Solidworks Macro - Circular Sketch Pattern
">Next ❯</a>
    </li>
    
  </ul>
</nav>

    </div>
  </article>

</div>
        </div>
      </div>
    </div>
  </div>

  <div id="footer" class="page__footer">
    <footer>
      <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
      <footer class="bd-footer py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <a class="d-inline-flex align-items-center mb-2 link-dark" href="/" aria-label="Bootstrap">
          <img src="/assets/logo.png" width="30" height="30" class="img-fluid mr-2" alt="">
          <span> The CAD Coder</span>
        </a>
        <ul class="list-unstyled small text-muted">
          <li class="mb-2">Programming Tutorials for SOLIDWORKS 3D CAD Software.</li>
          <li class="mb-2">Copyright © 2022 The CAD Coder</li>
          <li class="mb-2">Built with <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a>.</li>

          
            
              
            
              
              <li class="list-inline-item"><a href="https://facebook.com/thecadcoder" target="_blank" title="Facebook"><i
                class="fab fa-2x fa-facebook-f"></i></a></li>
              
            
              
            
              
            
              
            
              
            
              
              <li class="list-inline-item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" title="YouTube"><i
                class="fab fa-2x fa-youtube"></i></a></li>
              
            
              
              <li class="list-inline-item"><a href="mailto:thecadcoder@gmail.com" target="_blank" title="Email"><i
                class="fa fa-envelope fa-2x"></i></a></li>
              
            
          
        </ul>
      </div>
      <div class="col-6">
        <h5>Links</h5>
        <ul class="list-unstyled">
          <!-- <li class="mb-2"><a href="/">Home</a></li> -->
          <li class="mb-2"><a href="/aboutMe/">About</a></li>
          <li class="mb-2"><a href="/resources/">Resources</a></li>
          <li class="mb-2"><a href="/Disclaimer/">Privacy Policy</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
    </footer>
  </div>

  
  <script src="/assets/js/main.min.js"></script>




<script src="/assets/js/lunr/lunr.min.js"></script>
<script src="/assets/js/lunr/lunr-store.js"></script>
<script src="/assets/js/lunr/lunr-en.js"></script>







  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->

  
  <script src="/assets/js/main.min.js"></script>




<script src="/assets/js/lunr/lunr.min.js"></script>
<script src="/assets/js/lunr/lunr-store.js"></script>
<script src="/assets/js/lunr/lunr-en.js"></script>






</body>

</html>