<!doctype html>
<!--
  Minimal Mistakes Jekyll Theme 4.21.0 by Michael Rose
  Copyright 2013-2020 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE
-->
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">

<!-- begin _includes/seo.html --><title>Solidworks Macro - Create a Spline - The CAD Coder</title>
<meta name="description" content="In this post, I tell you about how to create a Spline through Solidworks VBA Macros in a sketch.">


  <meta name="author" content="Admin">
  
  <meta property="article:author" content="Admin">
  


<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="Solidworks Macro - Create a Spline">
<meta property="og:url" content="http://localhost:4000/solidworks-macros/create-spline/">


  <meta property="og:description" content="In this post, I tell you about how to create a Spline through Solidworks VBA Macros in a sketch.">







  <meta property="article:published_time" content="2021-03-18T05:21:32+00:00">





  

  


<link rel="canonical" href="http://localhost:4000/solidworks-macros/create-spline/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": "Admin",
      "url": "http://localhost:4000/"
    
  }
</script>






<!-- end _includes/seo.html -->


<link href="/feed.xml" type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">

<!-- https://t.co/dKP3o1e -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">

<script>
  document.documentElement.className = document.documentElement.className.replace(/\bno-js\b/g, '') + ' js ';
</script>

<!-- For all browsers -->
<link rel="stylesheet" href="/assets/css/main.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">

<!--[if IE]>
  <style>
    /* old IE unsupported flexbox fixes */
    .greedy-nav .site-title {
      padding-right: 3em;
    }
    .greedy-nav button {
      position: absolute;
      top: 0;
      right: 0;
      height: 100%;
    }
  </style>
<![endif]-->



    <!-- start custom head snippets -->

<!-- insert favicons. use https://realfavicongenerator.net/ -->

<!-- end custom head snippets -->

  </head>

  <body class="layout--single">
    <nav class="skip-links">
  <h2 class="screen-reader-text">Skip links</h2>
  <ul>
    <li><a href="#site-nav" class="screen-reader-shortcut">Skip to primary navigation</a></li>
    <li><a href="#main" class="screen-reader-shortcut">Skip to content</a></li>
    <li><a href="#footer" class="screen-reader-shortcut">Skip to footer</a></li>
  </ul>
</nav>

    <!--[if lt IE 9]>
<div class="notice--danger align-center" style="margin: 0;">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</div>
<![endif]-->

    

<div class="masthead">
  <div class="masthead__inner-wrap">
    <div class="masthead__menu">
      <nav id="site-nav" class="greedy-nav">
        
          <a class="site-logo" href="/"><img src="/assets/logo.png" alt=""></a>
        
        <a class="site-title" href="/">
          The CAD Coder
          
        </a>
        <ul class="visible-links"><li class="masthead__menu-item">
              <a href="/vba/vba-Introduction/">VBA</a>
            </li><li class="masthead__menu-item">
              <a href="/solidworks-macros/vba-in-solidworks/">Solidworks VBA Macro</a>
            </li><li class="masthead__menu-item">
              <a href="/Solidworks-csharp-api-tutorials/">Solidworks C# API</a>
            </li><li class="masthead__menu-item">
              <a href="/Solidworks-cpp-api-tutorials/">Solidworks C++ API</a>
            </li><li class="masthead__menu-item">
              <a href="/resources/">Resources</a>
            </li><li class="masthead__menu-item">
              <a href="/aboutMe/">About</a>
            </li></ul>
        
        <button class="search__toggle" type="button">
          <span class="visually-hidden">Toggle search</span>
          <svg class="icon" width="16" height="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15.99 16">
            <path d="M15.5,13.12L13.19,10.8a1.69,1.69,0,0,0-1.28-.55l-0.06-.06A6.5,6.5,0,0,0,5.77,0,6.5,6.5,0,0,0,2.46,11.59a6.47,6.47,0,0,0,7.74.26l0.05,0.05a1.65,1.65,0,0,0,.5,1.24l2.38,2.38A1.68,1.68,0,0,0,15.5,13.12ZM6.4,2A4.41,4.41,0,1,1,2,6.4,4.43,4.43,0,0,1,6.4,2Z" transform="translate(-.01)"></path>
          </svg>
        </button>
        
        <button class="greedy-nav__toggle hidden" type="button">
          <span class="visually-hidden">Toggle menu</span>
          <div class="navicon"></div>
        </button>
        <ul class="hidden-links hidden"></ul>
      </nav>
    </div>
  </div>
</div>


    <div class="initial-content">
      



<div id="main" role="main">
  
  <div class="sidebar sticky">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">General - Solidworks Functions</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/vba-in-solidworks/">Introduction</a></li>
          
            <li><a href="/solidworks-macros/open-new-document/">Open new Part document</a></li>
          
            <li><a href="/solidworks-macros/open-assembly-and-drawing/">Open Assembly and Drawing document</a></li>
          
            <li><a href="/solidworks-macros/select-plane-from-tree/">Selection Methods</a></li>
          
            <li><a href="/solidworks-macros/open-saved-document/">Open Saved Documents</a></li>
          
            <li><a href="/solidworks-macros/unit-correction/">Fix Unit Issue</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Lines</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/sketch-create-line/">Create Line</a></li>
          
            <li><a href="/solidworks-macros/sketch-create-centerline/">Create CenterLine</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Rectangles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-corner-rectangle/">Create Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-center-rectangle/">Create Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-corner-rectangle/">Create 3-Point Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-center-rectangle/">Create 3-Point Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-parallelogram/">Create A Parallelogram</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Circles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-circle/">Create Circle</a></li>
          
            <li><a href="/solidworks-macros/create-circle-by-radius/">Create Circle By Radius</a></li>
          
            <li><a href="/solidworks-macros/create-perimeter-circle/">Create Perimeter Circle</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Arcs</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc/">Create Centerpoint Arc</a></li>
          
            <li><a href="/solidworks-macros/create-tangent-arc/">Create Tangent Arc</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc/">Create 3-Point Arc</a></li>
          
            <li><a href="/solidworks-macros/polygon/">Create Polygon</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Slots</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-straight-slot/">Create a Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-straight-slot/">Create a Centerpoint Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc-slot/">Create a 3-Point Arc Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc-slot/">Create a Centerpoint Arc Slot</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Point and Spline</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-point/">Create a Point</a></li>
          
            <li><a href="/solidworks-macros/create-spline/" class="active">Create a Spline</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Fillet and Chamfer</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-fillet/">Create a Fillet</a></li>
          
            <li><a href="/solidworks-macros/create-chamfer/">Create a Chamfer</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Trim and Extend</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/trim-entities/">Trim Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/extend-entities/">Extend Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Patterns</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/linear-skech-pattern/">Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-linear-skech-pattern/">Edit Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/circular-skech-pattern/">Circular Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-circular-skech-pattern/">Edit Circular Sketch Pattern</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Move and Rotate</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/move-copy-sketch-entities/">Move/Copy Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/rotate-copy-sketch-entities/">Rotate/Copy Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Relations</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/toggle-display-sketch-relation/">Toggle (Hide/Show) Sketch Relations</a></li>
          
            <li><a href="/solidworks-macros/add-sketch-relations/">Add Sketch Relations (Constraints)</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Dimensions</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/add-dimension-methods/">Add dimension to Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-extrude-feature/">Extrude Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Others</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/convert-to-construction-sketch-segment/">Convert to Construction Sketch</a></li>
          
            <li><a href="/solidworks-macros/split-sketch-segments/">Split Open/Closed Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>



  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    <meta itemprop="headline" content="Solidworks Macro - Create a Spline">
    <meta itemprop="description" content="In this post, I tell you about how to create a Spline through Solidworks VBA Macros in a sketch.">
    
    

    <div class="page__inner-wrap">
      
        <header>
          <h1 id="page-title" class="page__title" itemprop="headline">Solidworks Macro - Create a Spline
</h1>
          

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          22 minute read
        
      </span>
    
  </p>


        </header>
      

      <section class="page__content" itemprop="text">
        
          <aside class="sidebar__right sticky">
            <nav class="toc">
              <header><h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4></header>
              <ul class="toc__menu"><li><a href="#video-of-code-on-youtube">Video of Code on YouTube</a></li><li><a href="#for-experience-macro-developer">For Experience Macro Developer</a></li><li><a href="#for-beginners-macro-developers">For Beginners Macro Developers</a><ul><li><a href="#understanding-the-code">Understanding the Code</a><ul><li><a href="#creating-sequence-of-points">Creating sequence of Points</a></li><li><a href="#create-a-collection-of-points-co-ordinates">Create a Collection of Points Co-ordinates</a></li><li><a href="#preparing-co-ordinates-of-points">Preparing Co-ordinates of Points</a></li><li><a href="#create-spline">Create Spline</a></li></ul></li><li><a href="#note">NOTE</a></li></ul></li><li><a href="#vba-language-feature-used-in-this-post">VBA Language feature used in this post</a></li><li><a href="#solidworks-api-objects">Solidworks API Objects</a></li></ul>

            </nav>
          </aside>
        
        <p>In this post, I tell you about <em>how to create a Spline through Solidworks VBA Macros</em> in a sketch.</p>

<p>This post take some functionality from previous <strong><a href="/solidworks-macros/create-point">Sketch - Create Create a Point</a></strong> post.</p>

<p>Hence if you have not read <strong><a href="/solidworks-macros/create-point">Sketch - Create Create a Point</a></strong> post, then it is <strong>recommended</strong> that please read it 1st.</p>

<hr />

<h2 id="video-of-code-on-youtube">Video of Code on YouTube</h2>

<p>Please see below video how visually we can create <em>a Spline</em> from <strong>Solidworks VBA macro</strong>.</p>

<iframe src="https://www.youtube.com/embed/B_W-f3cqUPM" frameborder="0" allowfullscreen=""></iframe>

<p>Please note that there are no explaination given in the video.</p>

<p>Explaination of each line and why we write code this way is explained here.</p>

<hr />

<h2 id="for-experience-macro-developer">For Experience Macro Developer</h2>

<p>If you are an experience <strong>Solidworks Macro developer</strong>, then you are looking for a specific code sample.</p>

<p>Below is the code for creating <strong>A Spline</strong> from <strong>Solidworks VBA Macro</strong>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks Sketch Segment</span>
<span class="k">Dim</span> <span class="nv">swSketchSegment</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchSegment</span>
      
<span class="c1">' Set the value of Solidworks Sketch segment by "CreateSpline2" method from Solidworks sketch manager</span>
<span class="k">Set</span> <span class="n">swSketchSegment</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateSpline2</span><span class="p">((</span><span class="n">pointArray</span><span class="p">),</span> <span class="k">True</span><span class="p">)</span>
</code></pre></div></div>

<p>For creating a <strong>Spline</strong> first you need to <strong>Create</strong> a variable of <code class="language-plaintext highlighter-rouge">SketchSegment</code> type.</p>

<p>After creating variable, you need to set the value of this variable.</p>

<p>For this you used <code class="language-plaintext highlighter-rouge">CreateSpline2</code> method from <strong>Solidworks Sketch Manager</strong>.</p>

<p>This <code class="language-plaintext highlighter-rouge">CreateSpline2</code> method set the value of <code class="language-plaintext highlighter-rouge">SketchSegment</code> type variable.</p>

<p>This <code class="language-plaintext highlighter-rouge">CreateSpline2</code> method takes following parameters as explained:</p>

<ul>
  <li>
    <p><strong>PointData</strong> : <em>Array of X,Y,Z point coordinates to use in creating the spline</em>.</p>
  </li>
  <li>
    <p><strong>SimulateNaturalEnds</strong> : <em>True to simulate natural ends, false to not simulate natural ends</em>.</p>
  </li>
</ul>

<p>If you want a more detail explaination then please read further otherwise this will help you to <strong>Create a Spline From VBA Macro</strong>.</p>

<hr />

<h2 id="for-beginners-macro-developers">For Beginners Macro Developers</h2>

<p>In this post, I tell you about <code class="language-plaintext highlighter-rouge">CreateSpline2</code> method from <strong>Solidworks</strong> <code class="language-plaintext highlighter-rouge">SketchManager</code> object.</p>

<p>By this method we create <em>a simple Spline from a sequence of points</em>.</p>

<p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>.</p>

<p>So <strong><em>use this method</em></strong> if you want to create <strong>a new Spline</strong>.</p>

<p>Below is the <code class="language-plaintext highlighter-rouge">code</code> sample for creating <em>a Spline</em>.</p>

<blockquote>
  <p>Please don’t get distracted by length of code, I  just want to do everything programatically. So that you have some sort of experience in developing logic.</p>
</blockquote>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="c1">' Creating variable for Solidworks Sketch Manager</span>
<span class="k">Dim</span> <span class="nv">swSketchManager</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchManager</span>

<span class="c1">' Creating variable for Solidworks Sketch</span>
<span class="k">Dim</span> <span class="nv">swSketch</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">Sketch</span>

<span class="c1">' Creating variable for Solidworks Sketch Point</span>
<span class="k">Dim</span> <span class="nv">swSketchPoint</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchPoint</span>

<span class="c1">' Creating variable for Solidworks Sketch Segment</span>
<span class="k">Dim</span> <span class="nv">swSketchSegment</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchSegment</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks application variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Creating string type variable for storing default part location</span>
  <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
  
  <span class="c1">' Set value of this string type variable to "Default part template"</span>
  <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>

  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

  <span class="c1">' Select Front Plane</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Set Sketch manager for our sketch</span>
  <span class="k">Set</span> <span class="n">swSketchManager</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span>
  
  <span class="c1">' Insert a sketch into selected plane</span>
  <span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
  
  <span class="c1">' Create integer type local variable</span>
  <span class="k">Dim</span> <span class="nv">i</span> <span class="ow">As</span> <span class="kt">Integer</span>
  
  <span class="c1">' Loop through 0 to 10</span>
  <span class="k">For</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span> <span class="k">To</span> <span class="mi">10</span>
    
    <span class="c1">' Create integer type variables</span>
    <span class="k">Dim</span> <span class="nv">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="n">incrementFactor</span> <span class="ow">As</span> <span class="kt">Integer</span>
    
    <span class="c1">' Set value of incrementFactor</span>
    <span class="n">incrementFactor</span> <span class="o">=</span> <span class="n">i</span> <span class="o">*</span> <span class="mf">0.5</span>
    
    <span class="c1">' Set value of x co-ordinate</span>
    <span class="n">x</span> <span class="o">=</span> <span class="n">i</span>
    <span class="c1">' Set value of y co-ordinate</span>
    <span class="n">y</span> <span class="o">=</span> <span class="n">x</span> <span class="o">+</span> <span class="n">incrementFactor</span>
    <span class="c1">' Set value of z co-ordinate</span>
    <span class="n">z</span> <span class="o">=</span> <span class="mi">0</span>

    <span class="c1">' Create a Sketch Point using x, y &amp; z variables</span>
    <span class="k">Set</span> <span class="n">swSketchPoint</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreatePoint</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">z</span><span class="p">)</span>

  <span class="k">Next</span> <span class="n">i</span>
  
  <span class="c1">' De-select the points after creation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
  
  <span class="c1">' Set Solidworks Sketch variable to active sketch</span>
  <span class="k">Set</span> <span class="n">swSketch</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">ActiveSketch</span>
  
  <span class="c1">' Create variant type variable named "sketchPointArray"</span>
  <span class="k">Dim</span> <span class="nv">sketchPointArray</span> <span class="ow">As</span> <span class="kt">Variant</span>
  
  <span class="c1">' Get all the points in this active sketch and store them into our variant type variable</span>
  <span class="n">sketchPointArray</span> <span class="o">=</span> <span class="n">swSketch</span><span class="p">.</span><span class="n">GetSketchPoints2</span><span class="p">()</span>
  
  <span class="c1">' Creating a new Collection,</span>
  <span class="c1">' we use this collecction to store x,y,z co-ordinates of all sketch points</span>
  <span class="k">Dim</span> <span class="nv">pointCollection</span> <span class="ow">As</span> <span class="k">New</span> <span class="n">Collection</span>
  
  <span class="c1">' Loop through all points in "sketchPointArray"</span>
  <span class="k">For</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span> <span class="k">To</span> <span class="n">UBound</span><span class="p">(</span><span class="n">sketchPointArray</span><span class="p">)</span>
    <span class="c1">' Set Solidworks sketch point variable to current point</span>
    <span class="k">Set</span> <span class="n">swSketchPoint</span> <span class="o">=</span> <span class="n">sketchPointArray</span><span class="p">(</span><span class="n">i</span><span class="p">)</span>
    
    <span class="c1">' Add X co-ordinate of current point into collection</span>
    <span class="n">pointCollection</span><span class="p">.</span><span class="n">Add</span> <span class="p">(</span><span class="n">swSketchPoint</span><span class="p">.</span><span class="n">x</span><span class="p">)</span>
    
    <span class="c1">' Add Y co-ordinate of current point into collection</span>
    <span class="n">pointCollection</span><span class="p">.</span><span class="n">Add</span> <span class="p">(</span><span class="n">swSketchPoint</span><span class="p">.</span><span class="n">y</span><span class="p">)</span>
    
    <span class="c1">' Add Z co-ordinate of current point into collection</span>
    <span class="n">pointCollection</span><span class="p">.</span><span class="n">Add</span> <span class="p">(</span><span class="n">swSketchPoint</span><span class="p">.</span><span class="n">z</span><span class="p">)</span>
  <span class="k">Next</span> <span class="n">i</span>
  
  <span class="c1">' Create an array variable, this is Double type variable</span>
  <span class="k">Dim</span> <span class="nv">point</span><span class="p">()</span> <span class="ow">As</span> <span class="kt">Double</span>
  
  <span class="c1">' Define the size of array Dynamically</span>
  <span class="k">ReDim</span> <span class="n">point</span><span class="p">(</span><span class="mi">0</span> <span class="k">To</span> <span class="n">pointCollection</span><span class="p">.</span><span class="n">Count</span><span class="p">)</span> <span class="ow">As</span> <span class="kt">Double</span>
  
  <span class="c1">' Loop through the collection we have</span>
  <span class="k">For</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span> <span class="k">To</span> <span class="p">(</span><span class="n">pointCollection</span><span class="p">.</span><span class="n">Count</span> <span class="o">-</span> <span class="mi">1</span><span class="p">)</span>
    <span class="c1">' Add each item of collection into our array variable</span>
    <span class="n">point</span><span class="p">(</span><span class="n">i</span><span class="p">)</span> <span class="o">=</span> <span class="n">pointCollection</span><span class="p">(</span><span class="n">i</span> <span class="o">+</span> <span class="mi">1</span><span class="p">)</span>
  <span class="k">Next</span> <span class="n">i</span>
  
  <span class="c1">' Create a local variable name "pointArray" of variant type</span>
  <span class="k">Dim</span> <span class="nv">pointArray</span> <span class="ow">As</span> <span class="kt">Variant</span>
  
  <span class="c1">' Set the new created variable equal to point array variable</span>
  <span class="n">pointArray</span> <span class="o">=</span> <span class="n">point</span>
  
  <span class="c1">' Exit the sketch</span>
  <span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
  
  <span class="c1">' De-select the sketch</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
  
  <span class="c1">' Select Front Plane</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Insert a sketch into "Front Plane"</span>
  <span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
  
  <span class="c1">' Set the value of Solidworks Sketch segment by "CreateSpline2" method from Solidworks sketch manager</span>
  <span class="k">Set</span> <span class="n">swSketchSegment</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateSpline2</span><span class="p">((</span><span class="n">pointArray</span><span class="p">),</span> <span class="k">True</span><span class="p">)</span>

  <span class="c1">' De-select the Spline after creation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
  
  <span class="c1">' Zoom to fit screen in Solidworks Window</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ViewZoomtofit2</span>

  <span class="c1">' Exit the sketch</span>
  <span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>

  <span class="c1">' Force Re-build the model</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">Rebuild</span> <span class="p">(</span><span class="n">swRebuildOptions_e</span><span class="p">.</span><span class="n">swForceRebuildAll</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<hr />

<h3 id="understanding-the-code">Understanding the Code</h3>

<p>Now let us walk through <em>each line</em> in the above code, and <strong>understand</strong> the meaning of every line.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>
</code></pre></div></div>

<p>This line forces us to define every variable we are going to use.</p>

<p>For more information please visit <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
</code></pre></div></div>

<p>In this line, we are creating a variable which we named as <code class="language-plaintext highlighter-rouge">swApp</code> and the type of this <code class="language-plaintext highlighter-rouge">swApp</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.SldWorks</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
</code></pre></div></div>

<p>In this line, we are creating a variable which we named as <code class="language-plaintext highlighter-rouge">swDoc</code> and the type of this <code class="language-plaintext highlighter-rouge">swDoc</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.ModelDoc2</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>
</code></pre></div></div>

<p>In this line, we create a variable named <code class="language-plaintext highlighter-rouge">BoolStatus</code> as <code class="language-plaintext highlighter-rouge">Boolean</code> object type.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks Sketch Manager</span>
<span class="k">Dim</span> <span class="nv">swSketchManager</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchManager</span>
</code></pre></div></div>

<p>In above line, we create variable <code class="language-plaintext highlighter-rouge">swSketchManager</code> for <strong>Solidworks Sketch Manager</strong>.</p>

<p>As the name suggested, a <strong>Sketch Manager</strong> holds variours methods and properties to manage <em>Sketches</em>.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">SketchManager</code> object, please visit <strong><a href="https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this page of Solidworks API Help</a></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks Sketch</span>
<span class="k">Dim</span> <span class="nv">swSketch</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">Sketch</span>
</code></pre></div></div>

<p>In this line, we are creating a variable which we named as <code class="language-plaintext highlighter-rouge">swSketch</code> and the type of this <code class="language-plaintext highlighter-rouge">swSketch</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.Sketch</code>.</p>

<p>We create variable <code class="language-plaintext highlighter-rouge">swSketch</code> for <strong>Solidworks Sketches</strong>.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">Sketch</code> object, please visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketch_members.html?verRedirect=1">this page of Solidworks API Help</a></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks Sketch Point</span>
<span class="k">Dim</span> <span class="nv">swSketchPoint</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchPoint</span>
</code></pre></div></div>

<p>In this line, we are creating a variable which we named as <code class="language-plaintext highlighter-rouge">swSketchPoint</code> and the type of this <code class="language-plaintext highlighter-rouge">swSketchPoint</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.SketchPoint</code>.</p>

<p>We create variable <code class="language-plaintext highlighter-rouge">swSketchPoint</code> for <strong>Solidworks Sketch Points</strong>.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">SketchPoint</code> object, please visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchPoint_members.html">this page of Solidworks API Help</a></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks Sketch Segment</span>
<span class="k">Dim</span> <span class="nv">swSketchSegment</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchSegment</span>
</code></pre></div></div>

<p>In this line, we are creating a variable which we named as <code class="language-plaintext highlighter-rouge">swSketchSegment</code> and the type of this <code class="language-plaintext highlighter-rouge">swSketchSegment</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.SketchSegment</code>.</p>

<p>We create variable <code class="language-plaintext highlighter-rouge">swSketchSegment</code> for <strong>Solidworks Sketch Segments</strong>.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">swSketchSegment</code> object, please visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html">this page of Solidworks API Help</a></strong></p>

<p>These all are our global variables.</p>

<p>As you can see in code sample, they are <strong>Solidworks API Objects</strong>.</p>

<p>So basically I group all the <strong>Solidworks API Objects</strong> in one place.</p>

<p>I have also place <code class="language-plaintext highlighter-rouge">boolean</code> type object at top also, because after certain point we will <em>need</em> this variable frequently.</p>

<p>Thus, I have started placing it here.</p>

<p>Next is our <code class="language-plaintext highlighter-rouge">Sub</code> procedure named as <code class="language-plaintext highlighter-rouge">main</code>. This procedure hold all the <em>statements (instructions)</em> we give to computer.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Setting Solidworks variable to Solidworks application</span>
<span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
</code></pre></div></div>

<p>In this line, we are setting the value of our Solidworks variable <code class="language-plaintext highlighter-rouge">swApp</code> which we defined earlier to Solidworks application.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating string type variable for storing default part location</span>
<span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>

<span class="c1">' Setting value of this string type variable to "Default part template"</span>
<span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>
</code></pre></div></div>

<p>In 1st statement of above example, we are defining a variable of <code class="language-plaintext highlighter-rouge">string</code> type and named it as <code class="language-plaintext highlighter-rouge">defaultTemplate</code>.</p>

<p>This variable <code class="language-plaintext highlighter-rouge">defaultTemplate</code>, holds the location the location of <strong>Default Part Template</strong>.</p>

<p>In 2nd line of above example. we assign value to our newly define <code class="language-plaintext highlighter-rouge">defaultTemplate</code> variable.</p>

<p>We assign the value by using a <em>Method</em> named <code class="language-plaintext highlighter-rouge">GetUserPreferenceStringValue()</code>.</p>

<p>This method is a part of our main Solidworks variable <code class="language-plaintext highlighter-rouge">swApp</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Setting Solidworks document to new part document</span>
<span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
</code></pre></div></div>

<p>In this line, we set the value of our <code class="language-plaintext highlighter-rouge">swDoc</code> variable to new document.</p>

<p>For <strong>more detailed information</strong> about above lines please visit <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post.</p>

<p>I have discussed them <strong>thoroghly</strong> in <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post, so do checkout this post if you don’t understand above code.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Selecting Front Plane</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line, we select the <em>front plane</em> by using <code class="language-plaintext highlighter-rouge">SelectByID2</code> method from <code class="language-plaintext highlighter-rouge">Extension</code> object.</p>

<p>For more information about selection method please visit <strong><a href="/solidworks-macros/select-plane-from-tree">Solidworks Macros - Selection Methods</a></strong> post.</p>

<p>I have discussed about different <em>Selection methods</em> in details in <strong><a href="/solidworks-macros/select-plane-from-tree">Soldworks Macros - Selection Methods</a></strong> post, so do visit this post for more <em>Selection methods</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Setting Sketch manager for our sketch</span>
<span class="k">Set</span> <span class="n">swSketchManager</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span>
</code></pre></div></div>

<p>In above line, we set the <strong>Solidworks Sketch manager</strong> variable to current document’s sketch manager.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Inserting a sketch into selected plane</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
</code></pre></div></div>

<p>In above line, we use <code class="language-plaintext highlighter-rouge">InsertSketch</code> method of <em>SketchManager</em> and give <code class="language-plaintext highlighter-rouge">True</code> value.</p>

<p>This method allows us to insert/exit <strong>a sketch</strong> in selected plane.</p>

<p><strong>Now I have created a sequence of Points for our Spline.</strong></p>

<p>Because if you already have co-ordinates of points in your machine somewhere you can use the approach I shown here to create a Spline.</p>

<blockquote>
  <p>TIP: I like to save co-ordinates in MS Excel file and then use it.</p>
</blockquote>

<hr />

<h4 id="creating-sequence-of-points">Creating sequence of Points</h4>

<p><em>Below code shows how to create Sequence of Points.</em></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create integer type local variable</span>
<span class="k">Dim</span> <span class="nv">i</span> <span class="ow">As</span> <span class="kt">Integer</span>

<span class="c1">' Loop through 0 to 10</span>
<span class="k">For</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span> <span class="k">To</span> <span class="mi">10</span>
  
  <span class="c1">' Create integer type variables</span>
  <span class="k">Dim</span> <span class="nv">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="n">incrementFactor</span> <span class="ow">As</span> <span class="kt">Integer</span>
  
  <span class="c1">' Set value of incrementFactor</span>
  <span class="n">incrementFactor</span> <span class="o">=</span> <span class="n">i</span> <span class="o">*</span> <span class="mf">0.5</span>
  
  <span class="c1">' Set value of x co-ordinate</span>
  <span class="n">x</span> <span class="o">=</span> <span class="n">i</span>
  <span class="c1">' Set value of y co-ordinate</span>
  <span class="n">y</span> <span class="o">=</span> <span class="n">x</span> <span class="o">+</span> <span class="n">incrementFactor</span>
  <span class="c1">' Set value of z co-ordinate</span>
  <span class="n">z</span> <span class="o">=</span> <span class="mi">0</span>

  <span class="c1">' Create a Sketch Point using x, y &amp; z variables</span>
  <span class="k">Set</span> <span class="n">swSketchPoint</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreatePoint</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">z</span><span class="p">)</span>

<span class="k">Next</span> <span class="n">i</span>

<span class="c1">' De-select the points after creation</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
</code></pre></div></div>

<p><em>Let us understand each line of code and how above Lines of code creates a number of points.</em></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create integer type local variable</span>
<span class="k">Dim</span> <span class="nv">i</span> <span class="ow">As</span> <span class="kt">Integer</span>
</code></pre></div></div>

<p>In above line, we create a local variable named <code class="language-plaintext highlighter-rouge">i</code> of <strong>integer</strong> type.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Looping through 1 to 10</span>
<span class="k">For</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span> <span class="k">To</span> <span class="mi">10</span>
  
<span class="k">Next</span>
</code></pre></div></div>

<p>In above lines, we create a <code class="language-plaintext highlighter-rouge">For</code> loop.</p>

<p>This loop iterate the value of <code class="language-plaintext highlighter-rouge">i</code> variable from <strong>0 -&gt; 10</strong>.</p>

<p>I use max value of <strong>10</strong>, because I want to create 10 points.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create integer type variables</span>
<span class="k">Dim</span> <span class="nv">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">z</span><span class="p">,</span> <span class="n">incrementFactor</span> <span class="ow">As</span> <span class="kt">Integer</span>

<span class="c1">' Set value of incrementFactor</span>
<span class="n">incrementFactor</span> <span class="o">=</span> <span class="n">i</span> <span class="o">*</span> <span class="mf">0.5</span>

<span class="c1">' Setting values of x, y and z</span>
<span class="n">x</span> <span class="o">=</span> <span class="n">i</span>
<span class="n">y</span> <span class="o">=</span> <span class="n">x</span> <span class="o">+</span> <span class="n">incrementFactor</span>
<span class="n">z</span> <span class="o">=</span> <span class="mi">0</span>
</code></pre></div></div>

<p>In above lines, we 1st declare 4 variable <em>x, y, z and incrementFactor</em> of <strong>integer</strong> type.</p>

<p><em>x, y and z</em> are co-ordinates of a single point in <em>X, Y</em> and <em>Z</em> direction.</p>

<p><em>incrementFactor</em> is the factor by which I want to increase the value of <em>Y co-ordinate</em> of a single point.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set value of incrementFactor</span>
<span class="n">incrementFactor</span> <span class="o">=</span> <span class="n">i</span> <span class="o">*</span> <span class="mf">0.5</span>
</code></pre></div></div>

<p>In above line, I set the value of <em>incrementFactor</em>.</p>

<p>This value is <strong>0.5</strong> times of value of <code class="language-plaintext highlighter-rouge">i</code> variable.</p>

<p>Example: <code class="language-plaintext highlighter-rouge">i = 3</code> then <em>incrementFactor = 3 * 0.5 =&gt; incrementFactor = 1.5</em></p>

<p>In next 3 lines, we set the values of <em>x, y and z</em>.</p>

<p>For all points, we set the value of <em>z</em> to <strong>0</strong> because we want to place our points in <strong>X-Y plane</strong>.</p>

<p>If the value of <code class="language-plaintext highlighter-rouge">i = 0</code>, then we set the value of <em>x</em> equal to <em>i</em>.</p>

<p>This makes <code class="language-plaintext highlighter-rouge">x = 0</code> also.</p>

<p>Now, we set the value of <em>y</em> which is equal to <strong>SUM</strong> of <em>x</em> and <em>incrementFactor</em>.</p>

<p>Hence for <em>i = 0</em>, <em>x = 0</em>, <em>y = 0</em> and <em>incrementFactor = 0</em>.</p>

<p>For <em>i = 1</em>, <em>x = 1</em>, <em>y = 1.5</em> and <em>incrementFactor = 0.5</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create a Sketch Point using x, y &amp; z variables</span>
<span class="k">Set</span> <span class="n">swSketchPoint</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreatePoint</span><span class="p">(</span><span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">,</span> <span class="n">z</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line, we create a Point using <code class="language-plaintext highlighter-rouge">CreatePoint</code> function of <code class="language-plaintext highlighter-rouge">swSketchManager</code> variable with the values of <em>x, y and z</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' De-select the Points after creation</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
</code></pre></div></div>

<p>In the this line of code, we de-select the created <em>Points</em>.</p>

<p>For de-selecting, we use <code class="language-plaintext highlighter-rouge">ClearSelection2</code> method from our Solidworks document variable <code class="language-plaintext highlighter-rouge">swDoc</code>.</p>

<hr />

<h4 id="create-a-collection-of-points-co-ordinates">Create a Collection of Points Co-ordinates</h4>

<p>After creating points, I want to do following things:</p>

<ol>
  <li>
    <p>Get all points in this sketch</p>
  </li>
  <li>
    <p>Add co-ordinates of each point into a collection</p>
  </li>
</ol>

<p><strong><em>Why I want to do this when I already know co-ordinates of all points in previous section?</em></strong></p>

<p>It is because I create points from this macro hence I know their co-ordinates.</p>

<p>I can add them to collection there BUT I want to take this opportunity to show following things:</p>

<ul>
  <li>
    <p>How you get points of an Sketch.</p>
  </li>
  <li>
    <p>How to create a Collection and Add values in it.</p>
  </li>
</ul>

<p><em>Below code shows how to do all those things.</em></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Solidworks Sketch variable to active sketch</span>
<span class="k">Set</span> <span class="n">swSketch</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">ActiveSketch</span>

<span class="c1">' Create variant type variable named "sketchPointArray"</span>
<span class="k">Dim</span> <span class="nv">sketchPointArray</span> <span class="ow">As</span> <span class="kt">Variant</span>

<span class="c1">' Get all the points in this active sketch and store them into our variant type variable</span>
<span class="n">sketchPointArray</span> <span class="o">=</span> <span class="n">swSketch</span><span class="p">.</span><span class="n">GetSketchPoints2</span><span class="p">()</span>

<span class="c1">' Creating a new Collection,</span>
<span class="c1">' we use this collecction to store x,y,z co-ordinates of all sketch points</span>
<span class="k">Dim</span> <span class="nv">pointCollection</span> <span class="ow">As</span> <span class="k">New</span> <span class="n">Collection</span>

<span class="c1">' Loop through all points in "sketchPointArray"</span>
<span class="k">For</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span> <span class="k">To</span> <span class="n">UBound</span><span class="p">(</span><span class="n">sketchPointArray</span><span class="p">)</span>
  <span class="c1">' Set Solidworks sketch point variable to current point</span>
  <span class="k">Set</span> <span class="n">swSketchPoint</span> <span class="o">=</span> <span class="n">sketchPointArray</span><span class="p">(</span><span class="n">i</span><span class="p">)</span>
  
  <span class="c1">' Add X co-ordinate of current point into collection</span>
  <span class="n">pointCollection</span><span class="p">.</span><span class="n">Add</span> <span class="p">(</span><span class="n">swSketchPoint</span><span class="p">.</span><span class="n">x</span><span class="p">)</span>
  
  <span class="c1">' Add Y co-ordinate of current point into collection</span>
  <span class="n">pointCollection</span><span class="p">.</span><span class="n">Add</span> <span class="p">(</span><span class="n">swSketchPoint</span><span class="p">.</span><span class="n">y</span><span class="p">)</span>
  
  <span class="c1">' Add Z co-ordinate of current point into collection</span>
  <span class="n">pointCollection</span><span class="p">.</span><span class="n">Add</span> <span class="p">(</span><span class="n">swSketchPoint</span><span class="p">.</span><span class="n">z</span><span class="p">)</span>
<span class="k">Next</span> <span class="n">i</span>
</code></pre></div></div>

<p><em>Let us understand each line of code.</em></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Solidworks Sketch variable to active sketch</span>
<span class="k">Set</span> <span class="n">swSketch</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">ActiveSketch</span>
</code></pre></div></div>

<p>In the above line, I set the value of <em>Solidworks Sketch</em> variable <code class="language-plaintext highlighter-rouge">swSketch</code> to active sketch.</p>

<p>For this we use <code class="language-plaintext highlighter-rouge">ActiveSketch</code> method of <em>Solidworks Sketch Manager</em> variable <code class="language-plaintext highlighter-rouge">swSketchManager</code>.</p>

<p>This method give us a <code class="language-plaintext highlighter-rouge">SldWorks.Sketch</code> type return value which we store into <code class="language-plaintext highlighter-rouge">swSketch</code> variable.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create variant type variable named "sketchPointArray"</span>
<span class="k">Dim</span> <span class="nv">sketchPointArray</span> <span class="ow">As</span> <span class="kt">Variant</span>

<span class="c1">' Get all the points in this active sketch and store them into our variant type variable</span>
<span class="n">sketchPointArray</span> <span class="o">=</span> <span class="n">swSketch</span><span class="p">.</span><span class="n">GetSketchPoints2</span><span class="p">()</span>
</code></pre></div></div>

<p>In 1st line of above code, I create a variable <code class="language-plaintext highlighter-rouge">sketchPointArray</code>.</p>

<p>This variable is <code class="language-plaintext highlighter-rouge">Variant</code> type variable.</p>

<p>In 2nd line of above code, I set the value of variable <code class="language-plaintext highlighter-rouge">sketchPointArray</code> using <code class="language-plaintext highlighter-rouge">GetSketchPoints2()</code> method.</p>

<p>We use <code class="language-plaintext highlighter-rouge">GetSketchPoints2()</code> method from our <em>Solidworks Sketch</em> type variable <code class="language-plaintext highlighter-rouge">swSketch</code>.</p>

<p><code class="language-plaintext highlighter-rouge">GetSketchPoints2()</code> method gives us all points in this sketch and we store those points into <code class="language-plaintext highlighter-rouge">sketchPointArray</code> variable.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating a new Collection,</span>
<span class="c1">' we use this collecction to store x,y,z co-ordinates of all sketch points</span>
<span class="k">Dim</span> <span class="nv">pointCollection</span> <span class="ow">As</span> <span class="k">New</span> <span class="n">Collection</span>
</code></pre></div></div>

<p>In the above line, I create variable <code class="language-plaintext highlighter-rouge">pointCollection</code> of <strong>Collection</strong> type.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Loop through all points in "sketchPointArray"</span>
<span class="k">For</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span> <span class="k">To</span> <span class="n">UBound</span><span class="p">(</span><span class="n">sketchPointArray</span><span class="p">)</span>

<span class="k">Next</span> <span class="n">i</span>
</code></pre></div></div>

<p>In above lines, we create a <code class="language-plaintext highlighter-rouge">For</code> loop.</p>

<p>This loop iterate the value of <code class="language-plaintext highlighter-rouge">i</code> variable from <strong>0 -&gt; UBound(sketchPointArray)</strong>.</p>

<p>I use max value of <strong>UBound(sketchPointArray)</strong>, because I want to iterate through Maximum number of points we get from the <code class="language-plaintext highlighter-rouge">GetSketchPoints2()</code> method.</p>

<p>If number of points are other than <em>10</em>, then <code class="language-plaintext highlighter-rouge">UBound(sketchPointArray)</code> method return only that number of points.</p>

<p>Hence it is <strong>useful</strong> to know for future use.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Solidworks sketch point variable to current point</span>
<span class="k">Set</span> <span class="n">swSketchPoint</span> <span class="o">=</span> <span class="n">sketchPointArray</span><span class="p">(</span><span class="n">i</span><span class="p">)</span>
</code></pre></div></div>

<p>Now inside, this loop in 1st line we set <em>Solidworks sketch point</em> variable to <strong>current</strong> point of <code class="language-plaintext highlighter-rouge">sketchPointArray</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Add X co-ordinate of current point into collection</span>
<span class="n">pointCollection</span><span class="p">.</span><span class="n">Add</span> <span class="p">(</span><span class="n">swSketchPoint</span><span class="p">.</span><span class="n">x</span><span class="p">)</span>

<span class="c1">' Add Y co-ordinate of current point into collection</span>
<span class="n">pointCollection</span><span class="p">.</span><span class="n">Add</span> <span class="p">(</span><span class="n">swSketchPoint</span><span class="p">.</span><span class="n">y</span><span class="p">)</span>

<span class="c1">' Add Z co-ordinate of current point into collection</span>
<span class="n">pointCollection</span><span class="p">.</span><span class="n">Add</span> <span class="p">(</span><span class="n">swSketchPoint</span><span class="p">.</span><span class="n">z</span><span class="p">)</span>
</code></pre></div></div>

<p>In above 3 lines, we add <em>X, Y and Z</em> co-ordinates of current point into our collection.</p>

<h4 id="preparing-co-ordinates-of-points">Preparing Co-ordinates of Points</h4>

<p>You know from <strong><a href="#for-experience-macro-developer">For Experience Macro Developers</a></strong> section, we need an <em>Array</em> of <strong>PointData</strong>.</p>

<p>This array contains <em>X, Y and Z</em> co-ordinates for Spline Points.</p>

<p>Now I tried to add <em>X, Y and Z</em> co-ordinates directly into an Array and then use this array to create Spline.</p>

<p>But it did not work, hence I had to store all <em>X, Y and Z</em> co-ordinates 1st into <strong>Collection</strong>.</p>

<p>Now I have all co-ordinates in my <strong>Collection</strong> and I have to create an <code class="language-plaintext highlighter-rouge">Array</code> for Spline from this <strong>Collection</strong>.</p>

<p><em>Below code sample show how to prepare Co-ordinate points for Spline</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create an array variable, this is Double type variable</span>
<span class="k">Dim</span> <span class="nv">point</span><span class="p">()</span> <span class="ow">As</span> <span class="kt">Double</span>

<span class="c1">' Define the size of array Dynamically</span>
<span class="k">ReDim</span> <span class="n">point</span><span class="p">(</span><span class="mi">0</span> <span class="k">To</span> <span class="n">pointCollection</span><span class="p">.</span><span class="n">Count</span><span class="p">)</span> <span class="ow">As</span> <span class="kt">Double</span>

<span class="c1">' Loop through the collection we have</span>
<span class="k">For</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span> <span class="k">To</span> <span class="p">(</span><span class="n">pointCollection</span><span class="p">.</span><span class="n">Count</span> <span class="o">-</span> <span class="mi">1</span><span class="p">)</span>
  <span class="c1">' Add each item of collection into our array variable</span>
  <span class="n">point</span><span class="p">(</span><span class="n">i</span><span class="p">)</span> <span class="o">=</span> <span class="n">pointCollection</span><span class="p">(</span><span class="n">i</span> <span class="o">+</span> <span class="mi">1</span><span class="p">)</span>
<span class="k">Next</span> <span class="n">i</span>

<span class="c1">' Create a local variable name "pointArray" of variant type</span>
<span class="k">Dim</span> <span class="nv">pointArray</span> <span class="ow">As</span> <span class="kt">Variant</span>

<span class="c1">' Set the new created variable equal to point array variable</span>
<span class="n">pointArray</span> <span class="o">=</span> <span class="n">point</span>

<span class="c1">' Exit the sketch</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>

<span class="c1">' De-select the sketch</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
</code></pre></div></div>

<p><em>Let us understand each line of above code sample.</em></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create an array variable, this is Double type variable</span>
<span class="k">Dim</span> <span class="nv">point</span><span class="p">()</span> <span class="ow">As</span> <span class="kt">Double</span>

<span class="c1">' Define the size of array Dynamically</span>
<span class="k">ReDim</span> <span class="n">point</span><span class="p">(</span><span class="mi">0</span> <span class="k">To</span> <span class="n">pointCollection</span><span class="p">.</span><span class="n">Count</span><span class="p">)</span> <span class="ow">As</span> <span class="kt">Double</span>
</code></pre></div></div>

<p>In above code, 1st line creates an <code class="language-plaintext highlighter-rouge">Array</code> variable. This is <code class="language-plaintext highlighter-rouge">double</code> type variable.</p>

<p>If you don’t know what an array is, then please visit <strong><a href="/vba/arrays">VBA Arrays</a></strong> post.</p>

<p>In 2nd line, we define the size of array. This size is <em>dynamic</em> means it <strong>automatic</strong> in nature.</p>

<p>We don’t have to give exact value every time, this code adjust the values if there is any change in our <em>Collection</em>.</p>

<p>This size of this array is <em>from</em> 0 to Number of Co-ordinates in the collection.</p>

<p>In our case size of array is <strong>0 -&gt; 30</strong>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Loop through the collection we have</span>
<span class="k">For</span> <span class="n">i</span> <span class="o">=</span> <span class="mi">0</span> <span class="k">To</span> <span class="p">(</span><span class="n">pointCollection</span><span class="p">.</span><span class="n">Count</span> <span class="o">-</span> <span class="mi">1</span><span class="p">)</span>
  <span class="c1">' Add each item of collection into our array variable</span>
  <span class="n">point</span><span class="p">(</span><span class="n">i</span><span class="p">)</span> <span class="o">=</span> <span class="n">pointCollection</span><span class="p">(</span><span class="n">i</span> <span class="o">+</span> <span class="mi">1</span><span class="p">)</span>
<span class="k">Next</span> <span class="n">i</span>
</code></pre></div></div>

<p>In above code we 1st create a <em>Loop</em>.</p>

<p>This <em>Loop</em> iterate <em>from 0</em> to <em>pointCollection.Count - 1</em>.</p>

<p>Why <em>pointCollection.Count - 1</em> ? It is because <em>pointCollection.Count</em> starts from <em>1</em> and our loop start with <em>0</em>.</p>

<p>Because of additional 1 count in <em>pointCollection</em>, we need to remove 1 from the count.</p>

<p>Inside this loop, we add every item of <em>pointCollection</em> into our <strong>point() array</strong>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create a local variable name "pointArray" of variant type</span>
<span class="k">Dim</span> <span class="nv">pointArray</span> <span class="ow">As</span> <span class="kt">Variant</span>

<span class="c1">' Set the new created variable equal to point array variable</span>
<span class="n">pointArray</span> <span class="o">=</span> <span class="n">point</span>
</code></pre></div></div>

<p>In 1st line of above code, we create local variable “pointArray”. This variable is <code class="language-plaintext highlighter-rouge">Variant</code> type.</p>

<p>In 2nd line of above code, we set the value of variable “pointArray” to value of variable “point”.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Exit the sketch</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>

<span class="c1">' De-select the sketch</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
</code></pre></div></div>

<p>In 1st line of above code, we Exit the sketch.</p>

<p>In 2nd line of above code, we De-select the sketch.</p>

<h4 id="create-spline">Create Spline</h4>

<p>Now we have all information available for creating <strong>a Spline</strong>.</p>

<p><em>Below code sample shows how to create a Spline.</em></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Select Front Plane</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>

<span class="c1">' Insert a sketch into "Front Plane"</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>

<span class="c1">' Set the value of Solidworks Sketch segment by "CreateSpline2" method from Solidworks sketch manager</span>
<span class="k">Set</span> <span class="n">swSketchSegment</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateSpline2</span><span class="p">((</span><span class="n">pointArray</span><span class="p">),</span> <span class="k">True</span><span class="p">)</span>

<span class="c1">' De-select the Spline after creation</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

<span class="c1">' Zoom to fit screen in Solidworks Window</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ViewZoomtofit2</span>

<span class="c1">' Exit the sketch</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>

<span class="c1">' Force Re-build the model</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">Rebuild</span> <span class="p">(</span><span class="n">swRebuildOptions_e</span><span class="p">.</span><span class="n">swForceRebuildAll</span><span class="p">)</span>
</code></pre></div></div>

<p><em>Let us understand each line of above code sample.</em></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Selecting Front Plane</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line, we select the <em>front plane</em> by using <code class="language-plaintext highlighter-rouge">SelectByID2</code> method from <code class="language-plaintext highlighter-rouge">Extension</code> object.</p>

<p>For more information about selection method please visit <strong><a href="/solidworks-macros/select-plane-from-tree">Solidworks Macros - Selection Methods</a></strong> post.</p>

<p>I have discussed about different <em>Selection methods</em> in details in <strong><a href="/solidworks-macros/select-plane-from-tree">Soldworks Macros - Selection Methods</a></strong> post, so do visit this post for more <em>Selection methods</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Inserting a sketch into selected plane</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
</code></pre></div></div>

<p>In above line, we use <code class="language-plaintext highlighter-rouge">InsertSketch</code> method of <em>SketchManager</em> and give <code class="language-plaintext highlighter-rouge">True</code> value.</p>

<p>This method allows us to insert/exit <strong>a sketch</strong> in selected plane.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set the value of Solidworks Sketch segment by "CreateSpline2" method from Solidworks sketch manager</span>
<span class="k">Set</span> <span class="n">swSketchSegment</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateSpline2</span><span class="p">((</span><span class="n">pointArray</span><span class="p">),</span> <span class="k">True</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line we set the value of <em>Solidworks Sketch segment variable</em> <code class="language-plaintext highlighter-rouge">swSketchSegment</code>.</p>

<p>For this we use, <code class="language-plaintext highlighter-rouge">CreateSpline2</code> method from <em>Solidworks sketch manager variable</em> <code class="language-plaintext highlighter-rouge">swSketchManager</code>.</p>

<p>This <code class="language-plaintext highlighter-rouge">CreateSpline2</code> method takes following parameters as explained:</p>

<p><strong>PointData</strong> : <em>Array of X,Y,Z point coordinates to use in creating the spline</em>.</p>

<p><strong>SimulateNaturalEnds</strong> : <em>True to simulate natural ends, false to not simulate natural ends</em>.</p>

<p>Below Image described <strong>the Parameters for a Spline</strong>.</p>

<p><img src="/assets/Solidworks_Images/splines/spline_parameters.png" alt="spline_parameters" /></p>

<p>In this <code class="language-plaintext highlighter-rouge">CreateSpline2</code> method, we pass our <code class="language-plaintext highlighter-rouge">pointArray</code> variable as <strong>PointData</strong>.</p>

<p>We want our spline to simulate natural ends. Hence we <code class="language-plaintext highlighter-rouge">True</code> as second parameter.</p>

<hr />

<h3 id="note">NOTE</h3>

<p>It is <strong><em>very important</em></strong> to remember that, when you give distance or any other numeric value in <strong>Solidworks API</strong>, Solidworks takes that numeric value in <strong><em>Meter only</em></strong>.</p>

<p><em>Solidworks API</em> does not care about your application’s Unit systems.</p>

<p>For example, I works in <strong>ANSI</strong> system means “inches” for distance.</p>

<p>But when I used Solidworks API through <em>VBA macros</em> or <em>C#</em>, I have to use <strong>converted</strong> numeric values.</p>

<p>Because Solidworks API output the distance in <strong>Meter</strong> only; which is not my requirement.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' De-select the Spline after creation</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
</code></pre></div></div>

<p>In above line, we de-select the created <em>Spline</em>.</p>

<p>For de-selecting, we use <code class="language-plaintext highlighter-rouge">ClearSelection2</code> method from our Solidworks document variable <code class="language-plaintext highlighter-rouge">swDoc</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Zoom to fit screen in Solidworks Window</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ViewZoomtofit</span>
</code></pre></div></div>

<p>In above line we use <em>zoom to fit</em> command.</p>

<p>For Zoom to fit, we use <code class="language-plaintext highlighter-rouge">ViewZoomtofit</code> method from our Solidworks document variable <code class="language-plaintext highlighter-rouge">swDoc</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Exit the sketch</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
</code></pre></div></div>

<p>In above line, we exit the sketch.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Force Re-build the model</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">Rebuild</span> <span class="p">(</span><span class="n">swRebuildOptions_e</span><span class="p">.</span><span class="n">swForceRebuildAll</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line, we Force Re-build the model the model.</p>

<p>For “Force Re-build” we use <strong>Rebuild</strong> method from <em>Solidworks Document variable</em> <code class="language-plaintext highlighter-rouge">swDoc</code>.</p>

<p>In this <strong>Rebuild</strong> method, we use <code class="language-plaintext highlighter-rouge">swRebuildOptions_e.swForceRebuildAll</code> option for re-build all.</p>

<p>This is it !!!</p>

<p>It is a BIG post but I tried to explain all.</p>

<p>If you found anything to add or update, please let me know on my e-mail.</p>

<hr />

<h2 id="vba-language-feature-used-in-this-post">VBA Language feature used in this post</h2>

<p>In this post used some features of <strong>VBA programming language</strong>.</p>

<p>This section of post, has some brief information about the VBA programming language specific features.</p>

<ol>
  <li>
    <p>We use <strong>Option Explicit</strong> for capturing un-declared variables. If you want to read more about <strong>Option Explicit</strong> then please visit <strong><a href="/vba/declaring-and-scoping-of-variables">Declaring and Scoping of Variables</a></strong>.</p>
  </li>
  <li>
    <p>Then we create <strong>variable</strong> for different data types. If you don’t know about them, then please visit <strong><a href="/vba/variables">Variables</a></strong> and <strong><a href="/vba/programming-concepts/#data-types-in-vba">Data-types</a></strong> posts of this blog. These posts will help you to understand what <strong>Variables</strong> are and how to use them.</p>
  </li>
  <li>
    <p>Then we create <strong>main Sub procedure</strong> for our macro. If you don’t know about the <strong>Sub procedure</strong>, then I suggest you to visit <strong><a href="/vba/sub-and-function-procedure">VBA Sub and Function Procedures</a></strong> and <strong><a href="/vba/executing-procedures">Executing Sub and Function Procedures</a></strong> posts of this blog. These posts will help you to understand what <strong>Procedures</strong> are and how to use them.</p>
  </li>
  <li>
    <p>In most part we create some variables and set their values. We set those values by using some <strong>functions</strong> provided from objects. If you don’t know about the <strong>functions</strong>, then you should visit <strong><a href="/vba/functions">VBA Functions</a></strong> and <strong><a href="/vba/more-functions">VBA Functions that do more</a></strong> posts of this blog. These posts will help you to understand what <strong>functions</strong> are and how to use them.</p>
  </li>
  <li>
    <p>For creating a sequence of points and data for Spline, we use a <strong>For-Next loop</strong>. We use a loop to set values of x, y and z co-ordinates of each points. If you don’t know about the <strong>For-Next loop</strong>, then you should visit <strong><a href="/vba/looping">VBA Looping</a></strong> post of this blog. This posts will help you to understand what <strong>For-Next loop</strong> are and how to use them.</p>
  </li>
  <li>
    <p>For storing co-ordinates of points we use <strong>Collection</strong>. In an <strong>Collection</strong>, we store objects or data. This is very helpful and important language feature. If you don’t know about the <strong>Collection</strong>, then you should visit <strong><a href="https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/collections">Collections (Visual Basic)</a></strong> from <strong>Microsoft Official Document Website</strong>. This will help you to understand what <strong>Collection</strong> are and how to use them.</p>
  </li>
  <li>
    <p>For creating Spline we use an <strong>Array</strong>. An <strong>Array</strong> is similar to <strong>Collection</strong>, in which we store objects or data. But Array is more basic version actually Array is a basic programming feature and used frequently <em>C and C++ programming languages</em>. This is also very helpful and important language feature. If you don’t know about the <strong>Array</strong>, then you should visit <strong><a href="https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/language-features/arrays/index">Arrays in Visual Basic</a></strong> from <strong>Microsoft Official Document Website</strong>. This will help you to understand what <strong>Array</strong> are and how to use them.</p>
  </li>
</ol>

<hr />

<h2 id="solidworks-api-objects">Solidworks API Objects</h2>

<p>In this post, for creating a <strong>Point</strong>, we use <em>Solidworks API objects and their methods</em>.</p>

<p>This section contains the list of all <strong>Solidworks Objects</strong> used in this post.</p>

<p>I have also attached links of these <strong>Solidworks API Objects</strong> in <strong>API Help website</strong>.</p>

<p>If you want to explore those objects, you can use these links.</p>

<p>These Solidworks API Objects are listed below:</p>

<ul>
  <li><strong>Solidworks Application Object</strong></li>
</ul>

<p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Application Object</strong> object you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html">this link</a></strong>.</p>

<ul>
  <li><strong>Solidworks Document Object</strong></li>
</ul>

<p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Document Object</strong> object you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html">this link</a></strong>.</p>

<ul>
  <li><strong>Solidworks Sketch Manager Object</strong></li>
</ul>

<p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Sketch Manager Object</strong> you can visit <strong><a href="http://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this link</a></strong>.</p>

<ul>
  <li><strong>Solidworks Sketches Object</strong></li>
</ul>

<p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Sketches Object</strong> you can visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketch_members.html?verRedirect=1">this link</a></strong>.</p>

<ul>
  <li><strong>Solidworks Sketch Point Object</strong></li>
</ul>

<p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Sketch Point Object</strong> you can visit <strong><a href="http://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchPoint_members.html">this link</a></strong>.</p>

<ul>
  <li><strong>Solidworks Sketch Segment Object</strong></li>
</ul>

<p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Sketch Segment Object</strong> you can visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html">this link</a></strong>.</p>

<hr />

<p>Hope this post helps you to <em>create a Spline</em> in Sketches with Solidworks VB Macros.</p>

<p>For more such tutorials on <strong>Solidworks VBA Macros</strong>, do come to this blog after sometime.</p>

<p>Till then, Happy learning!!!</p>

        
      </section>

      <footer class="page__meta">
        
        
  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-tags" aria-hidden="true"></i> Tags: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/tags/#solidworks-macro" class="page__taxonomy-item" rel="tag">Solidworks Macro</a>
    
    </span>
  </p>




  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-folder-open" aria-hidden="true"></i> Categories: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/categories/#solidworks-macro" class="page__taxonomy-item" rel="tag">Solidworks-macro</a>
    
    </span>
  </p>


        

      </footer>

      <section class="page__share">
  

  <a href="https://twitter.com/intent/tweet?text=Solidworks+Macro+-+Create+a+Spline%20http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fcreate-spline%2F" class="btn btn--twitter" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Twitter"><i class="fab fa-fw fa-twitter" aria-hidden="true"></i><span> Twitter</span></a>

  <a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fcreate-spline%2F" class="btn btn--facebook" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Facebook"><i class="fab fa-fw fa-facebook" aria-hidden="true"></i><span> Facebook</span></a>

  <a href="https://www.linkedin.com/shareArticle?mini=true&url=http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fcreate-spline%2F" class="btn btn--linkedin" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on LinkedIn"><i class="fab fa-fw fa-linkedin" aria-hidden="true"></i><span> LinkedIn</span></a>
</section>



      
  <nav class="pagination">
    
      <a href="/solidworks-macros/create-point/" class="pagination--pager" title="Solidworks Macro - Create a Point
">Previous</a>
    
    
      <a href="/solidworks-macros/create-fillet/" class="pagination--pager" title="Solidworks Macro - Create a Fillet
">Next</a>
    
  </nav>

    </div>

    
  </article>

  
  
    <div class="page__related">
      <h4 class="page__related-title">You May Also Enjoy</h4>
      <div class="grid__wrapper">
        
      </div>
    </div>
  
  
</div>

    </div>

    
      <div class="search-content">
        <div class="search-content__inner-wrap"><form onsubmit="return googleCustomSearchExecute();" id="cse-search-box-form-id">
    <label class="sr-only" for="cse-search-input-box-id">
      Enter your search term...
    </label>
    <input type="search" id="cse-search-input-box-id" class="search-input" tabindex="-1" placeholder="Enter your search term..." />
  </form>
  <div id="results" class="results">
    <gcse:searchresults-only></gcse:searchresults-only>
  </div></div>

      </div>
    

    <div id="footer" class="page__footer">
      <footer>
        <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
        <div class="page__footer-follow">
  <ul class="social-icons">
    

    
      
        
      
        
          <li><a href="https://facebook.com/thecadcoder" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-facebook-square" aria-hidden="true"></i> Facebook</a></li>
        
      
        
      
        
      
        
      
        
      
        
          <li><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" rel="nofollow noopener noreferrer"><i class="fab fa-youtube" aria-hidden="true"></i> YouTube</a></li>
        
      
        
          <li><a href="mailto:thecadcoder@gmail.com" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-envelope-square" aria-hidden="true"></i> Email</a></li>
        
      
    

    <li><a href="/feed.xml"><i class="fas fa-fw fa-rss-square" aria-hidden="true"></i> Feed</a></li>
  </ul>
</div>

<div class="page__footer-copyright">&copy; 2021 Admin. Powered by <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a> &amp; <a href="https://mademistakes.com/work/minimal-mistakes-jekyll-theme/" rel="nofollow">Minimal Mistakes</a>. | <strong><a href="http://localhost:4000/Disclaimer/" rel="nofollow"><i class="fas fa-lock" aria-hidden="true"></i> Privacy Policy</a></strong></div>

      </footer>
    </div>

    
  <script src="/assets/js/main.min.js"></script>


<script>
  (function () {
    var cx = '4b2b9cb8c831ee0fb';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();

  function googleCustomSearchExecute() {
    var input = document.getElementById('cse-search-input-box-id');
    var element = google.search.cse.element.getElement('searchresults-only0');
    if (input.value == '') {
      element.clearAllResults();
    } else {
      element.execute(input.value);
    }
    return false;
  }

  
    $(document).ready(function () {
      $('input#cse-search-input-box-id').on('keyup', function () {
        googleCustomSearchExecute();
      });
    });
  
</script>







    <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>


  </body>
</html>
