<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="generator" content="Docusaurus v2.0.0-alpha.66">
<link rel="preconnect" href="https://www.google-analytics.com">
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-117501871-2","auto"),ga("set","anonymizeIp",!0),ga("send","pageview")</script>
<script async src="https://www.google-analytics.com/analytics.js"></script><title data-react-helmet="true">Create a Chamfer | The Cad Coder</title><meta data-react-helmet="true" name="twitter:card" content="summary_large_image"><meta data-react-helmet="true" name="docusaurus_language" content="en"><meta data-react-helmet="true" name="docusaurus_version" content="current"><meta data-react-helmet="true" name="docusaurus_tag" content="docs-default-current"><meta data-react-helmet="true" property="og:title" content="Create a Chamfer | The Cad Coder"><meta data-react-helmet="true" name="description" content="In this post, I tell you about how to create a Chamfer through Solidworks VBA Macros in a sketch."><meta data-react-helmet="true" property="og:description" content="In this post, I tell you about how to create a Chamfer through Solidworks VBA Macros in a sketch."><meta data-react-helmet="true" property="og:url" content="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-create-chamfer"><link data-react-helmet="true" rel="shortcut icon" href="/img/logo.png"><link data-react-helmet="true" rel="canonical" href="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-create-chamfer"><link rel="stylesheet" href="/styles.f7ef45b3.css">
<link rel="preload" href="/styles.e684f388.js" as="script">
<link rel="preload" href="/runtime~main.10187eec.js" as="script">
<link rel="preload" href="/main.d90b1f90.js" as="script">
<link rel="preload" href="/1.1af7f77d.js" as="script">
<link rel="preload" href="/2.4f0019c3.js" as="script">
<link rel="preload" href="/94.4b40930d.js" as="script">
<link rel="preload" href="/95.2f44d2c3.js" as="script">
<link rel="preload" href="/f976f453.e3619938.js" as="script">
<link rel="preload" href="/17896441.361bff39.js" as="script">
<link rel="preload" href="/1f161840.e3b9e0d9.js" as="script">
</head>
<body>
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><div aria-label="Navigation bar toggle" class="navbar__toggle" role="button" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></div><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a><div class="navbar__item dropdown dropdown--hoverable dropdown--left"><a class="navbar__item navbar__link">VBA</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li><a class="dropdown__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></div><a class="navbar__item navbar__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a><a class="navbar__item navbar__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></div><div class="navbar__items navbar__items--right"><div class="navbar__item dropdown dropdown--hoverable dropdown--right"><a class="navbar__item navbar__link">About</a><ul class="dropdown__menu"><li><a class="dropdown__link" position="right" href="/docs/about">About Me</a></li><li><a class="dropdown__link" position="right" href="/docs/resources">Resources</a></li><li><a class="dropdown__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></div><div class="react-toggle react-toggle--disabled displayOnlyInLargeViewport_2aTZ"><div class="react-toggle-track"><div class="react-toggle-track-check"><span class="toggle_BsTx">ðŸŒœ</span></div><div class="react-toggle-track-x"><span class="toggle_BsTx">ðŸŒž</span></div></div><div class="react-toggle-thumb"></div><input type="checkbox" disabled="" aria-label="Dark mode toggle" class="react-toggle-screenreader-only"></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div><div class="navbar-sidebar"><div class="navbar-sidebar__brand"><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a></div><div class="navbar-sidebar__items"><div class="menu"><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">VBA</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></li><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">About</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/about">About Me</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/resources">Resources</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></li></ul></div></div></div></nav><div class="main-wrapper"><div class="docPage_2gpo"><div class="docSidebarContainer_3_JD" role="complementary"><div class="sidebar_2urC"><div class="menu menu--responsive menu_5FrY"><button aria-label="Open Menu" aria-haspopup="true" class="button button--secondary button--sm menu__button" type="button"><svg aria-label="Menu" class="sidebarMenuIcon_Dm3K" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 32 32" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">General Functions</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba-in-sw">VBA in Solidworks</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-part">Open new Part document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-asm-and-dwg">Open Assembly and Drawing document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-selection-methods">Selection Methods</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-saved-documents">Open Saved Documents</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue">Fix Unit Issue</a></li></ul></li><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!">Sketch</a><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Lines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-line">Create Line</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerline">Create CenterLine</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Rectangles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-corner-rec">Create Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-center-rec">Create Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-corner-rec">Create 3-Point Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-center-rec">Create 3-Point Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-parallelogram">Create A Parallelogram</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Circles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle">Create Circle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle-by-radius">Create Circle By Radius</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-perimeter-circle">Create Perimeter Circle</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Arcs</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc">Create Centerpoint Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-tangent-arc">Create Tangent Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc">Create 3-Point Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-polygon">Create Polygon</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Slots</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-straight-slot">Create a Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-straight-slot">Create a Centerpoint Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc-slot">Create a 3-Point Arc Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc-slot">Create a Centerpoint Arc Slot</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Splines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-point">Create a Point</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-spline">Create a Spline</a></li></ul></li><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!" tabindex="0">Fillet &amp; Chamfer</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-create-fillet">Create a Fillet</a></li><li class="menu__list-item"><a aria-current="page" class="menu__link menu__link--active active" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-create-chamfer">Create a Chamfer</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Trim and Extend</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-trim-entities">Trim Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-extend-entities">Extend Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Offset and Mirror</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-offset-entities">Offset Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-mirror-sketch-entities">Mirror Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Patterns</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-linear-sketch-patterm">Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm">Edit Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm">Circular Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern">Edit Circular Sketch Pattern</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Transformation</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities">Move/Copy Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities">Rotate/Copy Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Relations</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-toggle-sketch-relation">Toggle (Hide/Show) Sketch Relations</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-sketch-relation">Add Sketch Relations (Constraints)</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Others</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-convert-to-construction-sketch">Convert to Construction Sketch</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-split-sketch-entities">Split Open/Closed Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Dimensioning</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-dimension-sketch-entities">Add dimension to Sketch Entities</a></li></ul></li></ul></li></ul></div></div></div><main class="docMainContainer_3EyW"><div class="container padding-vert--lg docItemWrapper_1EkI"><div class="row"><div class="col docItemCol_2ASc"><div class="docItemContainer_3QWW"><article><header><h1 class="docTitle_1Lrw">Create a Chamfer</h1></header><div class="markdown"><p>In this post, I tell you about <em>how to create a Chamfer through Solidworks VBA Macros</em> in a sketch.</p><p>This post is an extension of <strong><a href="/docs/solidworks-macros/sw-sketch-macro-create-corner-rec">Sketch - Create Corner Rectangle</a></strong> post.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="video-of-code-on-youtube"></a>Video of Code on YouTube<a aria-hidden="true" tabindex="-1" class="hash-link" href="#video-of-code-on-youtube" title="Direct link to heading">#</a></h2><p>Please see below video how visually we can create <em>a Chamfer</em> from <strong>Solidworks VBA macro</strong>.</p><div class="youtube-responsive-container"><iframe src="https://www.youtube.com/embed/HobbXAv9zMI" frameborder="0"></iframe></div><p>Please note that there are <strong>no explaination</strong> given in the video. </p><p><strong>Explaination</strong> of each line and why we write code this way is given in this post.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="for-experience-macro-developer"></a>For Experience Macro Developer<a aria-hidden="true" tabindex="-1" class="hash-link" href="#for-experience-macro-developer" title="Direct link to heading">#</a></h2><p>If you are an experience <strong>Solidworks Macro developer</strong>, then you are looking for a specific code sample.</p><p>Below is the code for creating <strong>A Chamfer</strong> from <strong>Solidworks VBA Macro</strong>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks Sketch Segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchSegment As SldWorks.SketchSegment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set the value of Solidworks Sketch segment by &quot;CreateChamfer&quot; method from Solidworks sketch manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchSegment = swSketchManager.CreateChamfer(swSketchChamferType_e.swSketchChamfer_DistanceEqual, 0.1, 0.2)</span></div></div></div></div></div><p>For creating a <strong>Chamfer</strong> first you need to <strong>Create</strong> a variable of <code>SketchSegment</code> type.</p><p>After creating variable, you need to set the value of this variable.</p><p>For this you used <code>CreateChamfer</code> method from <strong>Solidworks Sketch Manager</strong>.</p><p>This <code>CreateChamfer</code> method set the value of <code>SketchSegment</code> type variable.</p><p>This <code>CreateChamfer</code> method takes following parameters as explained:</p><p><strong>Type</strong> : <em>Type of chamfer as defined in <code>swSketchChamferType_e</code></em></p><p><strong>Distance</strong> : <em>Distance of the chamfer</em></p><p><strong>AngleORdist</strong> : <em>These are as follows</em></p><ul><li><p>If Type = <code>swSketchChamfer_DistanceDistance</code>, then the second chamfer distance </p></li><li><p>If Type = <code>swSketchChamfer_DistanceAngle</code>, then the second chamfer angle </p></li><li><p>If Type = <code>swSketchChamfer_DistanceEqual</code>, then this argument is ignored because Distance
is used for both edges</p></li></ul><p>If you want a more detail explaination then please read further otherwise this will help you to <strong>Create a Chamfer From VBA Macro</strong>.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="for-beginners-macro-developers"></a>For Beginners Macro Developers<a aria-hidden="true" tabindex="-1" class="hash-link" href="#for-beginners-macro-developers" title="Direct link to heading">#</a></h2><p>In this post, I tell you about <code>CreateChamfer</code> method from <strong>Solidworks</strong> <code>SketchManager</code> object.</p><p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>. </p><p>So <strong><em>use this method</em></strong> if you want to create a Chamfer.</p><p>Below is the <code>code</code> sample for creating a Chamfer.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating Variable for Solidworks Sketch Segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchSegment As SldWorks.SketchSegment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Creating string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swSketchManager = swDoc.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Inserting a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swSketchManager.InsertSketch True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Creating a &quot;Variant&quot; Variable which holds the values return by &quot;CreateCornerRectangle&quot; method</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim vSketchLines As Variant</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Creating a Corner Rectangle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  vSketchLines = swSketchManager.CreateCornerRectangle(0, 1, 0, 1, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; De-select the lines after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ClearSelection2 True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Selecting Point 1</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  BoolStatus = swDoc.Extension.SelectByID2(&quot;Point1&quot;, &quot;SKETCHPOINT&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Set the value of Solidworks Sketch segment by &quot;CreateChamfer&quot; method from Solidworks sketch manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swSketchSegment = swSketchManager.CreateChamfer(swSketchChamferType_e.swSketchChamfer_DistanceEqual, 0.1, 0.2)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; De-select the Chamfer after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ClearSelection2 True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Show Front View after creating Chamfer</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ShowNamedView2 &quot;&quot;, swStandardViews_e.swFrontView</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Zoom to fit screen in Solidworks Window</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ViewZoomtofit2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="understanding-the-code"></a>Understanding the Code<a aria-hidden="true" tabindex="-1" class="hash-link" href="#understanding-the-code" title="Direct link to heading">#</a></h3><p>Now let us walk through <em>each line</em> in the above code, and <strong>understand</strong> the meaning of every line.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div></div></div></div></div><p>This line forces us to define every variable we are going to use. </p><p>For more information please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div></div></div></div></div><p>In this line, we are creating a variable which we named as <code>swApp</code> and the type of this <code>swApp</code> variable is <code>SldWorks.SldWorks</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div></div></div></div></div><p>In this line, we are creating a variable which we named as <code>swDoc</code> and the type of this <code>swDoc</code> variable is <code>SldWorks.ModelDoc2</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div></div></div></div></div><p>In this line, we create a variable named <code>BoolStatus</code> as <code>Boolean</code> object type.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div></div></div></div></div><p>In above line, we create variable <code>swSketchManager</code> for <strong>Solidworks Sketch Manager</strong>.</p><p>As the name suggested, a <strong>Sketch Manager</strong> holds variours methods and properties to manage <em>Sketches</em>.</p><p>To see methods and properties related to <code>SketchManager</code> object, please visit <strong><a href="/docs/solidworks-macros/help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this page</a></strong>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks Sketch Segment</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchSegment As SldWorks.SketchSegment</span></div></div></div></div></div><p>In this line, we are creating a variable which we named as <code>swSketchSegment</code> and the type of this <code>swSketchSegment</code> variable is <code>SldWorks.SketchSegment</code>.</p><p>We create variable <code>swSketchSegment</code> for <strong>Solidworks Sketch Segments</strong>.</p><p>To see methods and properties related to <code>swSketchSegment</code> object, please visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html" target="_blank" rel="noopener noreferrer">this page</a></strong>.</p><p>These all are our global variables.</p><p>As you can see in code sample, they are <strong>Solidworks API Objects</strong>.</p><p>So basically I group all the <strong>Solidworks API Objects</strong> in one place.</p><p>I have also place <code>boolean</code> type object at top also, because after certain point we will <em>need</em> this variable frequently.</p><p>Thus, I have started placing it here.</p><p>Next is our <code>Sub</code> procedure named <code>main</code>. This procedure hold all the <em>statements (instructions)</em> we give to computer.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swApp = Application.SldWorks</span></div></div></div></div></div><p>In this line, we are setting the value of our Solidworks variable which we define earlier to Solidworks application.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div></div></div></div></div><p>In 1st statement of above example, we are defining a variable of <code>string</code> type and named it as <code>defaultTemplate</code>.</p><p>This variable <code>defaultTemplate</code>, hold the location the location of <strong>Default Part Template</strong>.</p><p>In 2nd line of above example. we assign value to our newly define <code>defaultTemplate</code> variable.</p><p>We assign the value by using a <em>Method</em> named <code>GetUserPreferenceStringValue()</code>. This method is a part of our main Solidworks variable <code>swApp</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div></div></div></div></div><p>In this line, we set the value of our <code>swDoc</code> variable to new document.</p><p>For <strong>detailed information</strong> about these lines please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post.</p><p>I have discussed them <strong>thoroghly</strong> in <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post, so do checkout this post if you don&#x27;t understand above code.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div></div></div></div></div><p>In above line, we select the <em>front plane</em> by using <code>SelectByID2</code> method from <code>Extension</code> object.</p><p>For more information about selection method please visit <strong><a href="/docs/solidworks-macros/sw-macro-selection-methods">Solidworks Macros - Selection Methods</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchManager = swDoc.SketchManager</span></div></div></div></div></div><p>In above line, we set the sketch manager variable to current document&#x27;s sketch manager.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Inserting a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swSketchManager.InsertSketch True</span></div></div></div></div></div><p>In above line, we use <code>InsertSketch</code> method of <em>SketchManager</em> and give <code>True</code> value.</p><p>This method allows us to insert a sketch in selected plane.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating a &quot;Variant&quot; Variable which holds the values return by &quot;CreateCornerRectangle&quot; method</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim vSketchLines As Variant</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating a Corner Rectangle</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">vSketchLines = swSketchManager.CreateCornerRectangle(0, 1, 0, 1, 0, 0)</span></div></div></div></div></div><p>In above sample code, we 1st create a variable named <code>vSketchLines</code> of type <code>Variant</code>.</p><p>A <code>Variant</code> type variable can hold <strong>any</strong> type of value depends upon the use of variable.</p><p>In 2nd line, we set the value of variable <code>vSketchLines</code>.</p><p>Value of <code>vSketchLinesis</code> an array of lines. This array is send as return value when we use <code>CreateCornerRectangle</code> method.</p><p>This <code>CreateCornerRectangle</code> method is part of <code>swSketchManager</code> and it is the latest method to create a corner rectangle.</p><p>For detail explaination on <code>CreateCornerRectangle</code> method, please see <strong><a href="/docs/solidworks-macros/sw-sketch-macro-create-corner-rec">Sketch - Create Corner Rectangle</a></strong> post.</p><p>In the above code sample I have used (0, 1, 0) Upper-left point in <em>Y-direction</em>.</p><p>For Lower-right point I used (1, 0, 0) which is 1 point distance in <em>X-direction</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; De-select the Rectangle after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ClearSelection2 True</span></div></div></div></div></div><p>In above line, we de-select the ractangle we just create.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div></div></div></div></div><p>In above line, we select the <em>front plane</em> by using <code>SelectByID2</code> method from <code>Extension</code> object.</p><p>For more information about selection method please visit <strong><a href="/docs/solidworks-macros/sw-macro-selection-methods">Solidworks Macros - Selection Methods</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Set the value of Solidworks Sketch segment by &quot;CreateChamfer&quot; method from Solidworks sketch manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchSegment = swSketchManager.CreateChamfer(swSketchChamferType_e.swSketchChamfer_DistanceEqual, 0.1, 0.2)</span></div></div></div></div></div><p>In above line, we set the value of Solidworks Sketch Segment variable <code>swSketchSegment</code> by <code>CreateChamfer</code> method from <em>Solidworks Sketch Manager</em>.</p><p>This <code>CreateChamfer</code> method takes following parameters:</p><p><strong>Type</strong> : <em>Type of chamfer as defined in <code>swSketchChamferType_e</code></em>.</p><p>The <code>swSketchChamferType_e</code> has 3 values for type of chamfers:</p><ul><li><p><code>swSketchChamfer_DistanceAngle</code></p></li><li><p><code>swSketchChamfer_DistanceDistance</code></p></li><li><p><code>swSketchChamfer_DistanceEqual</code></p></li></ul><p><strong>Distance</strong> : <em>Distance of the chamfer</em></p><p><strong>AngleORdist</strong> : <em>Angle or Distance for chamfer. These are as follows</em></p><ul><li><p>If Type = <code>swSketchChamfer_DistanceDistance</code>, then the second chamfer distance </p></li><li><p>If Type = <code>swSketchChamfer_DistanceAngle</code>, then the second chamfer angle </p></li><li><p>If Type = <code>swSketchChamfer_DistanceEqual</code>, then this argument is ignored because Distance is used for both edges.</p></li></ul><p>Below Image described <strong>the Parameters for a Chamfer</strong>.</p><p><img alt="fillet_parameters" src="/assets/images/fillet_parameters-c914080196123507c1e3e6449604a6b8.png"></p><p>In our code, I have used following values:</p><ul><li><p><strong>Type</strong> : I have used <code>swSketchChamferType_e.swSketchChamfer_DistanceEqual</code> enumerator as value for type of Chamfer.</p></li><li><p><strong>Distance</strong> : I have used 0.1 (This value is in meter) as the distance of Chamfer.</p></li><li><p><strong>AngleORdist</strong> : I have used 0.2 (This value is in meter). But in our code <strong>Type = <code>swSketchChamfer_DistanceEqual</code></strong>, then this argument is ignored because Distance
is used for both edges.</p></li></ul><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="note"></a>NOTE<a aria-hidden="true" tabindex="-1" class="hash-link" href="#note" title="Direct link to heading">#</a></h3><p>It is <strong><em>very important</em></strong> to remember that, when you give distance or any other numeric value in <strong>Solidworks API</strong>, Solidworks takes that numeric value in <strong><em>Meter only</em></strong>.</p><p>Solidworks API does not care about your application&#x27;s Unit systems.</p><p>For example, I works in <strong>ANSI</strong> system means inches for distance. But when I used <strong>Solidworks API</strong> through <em>VBA macros or C#</em>, I need to use converted numeric values.</p><p>Because Solidworks API output the distance in <strong>Meter</strong> which is not my requirement.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; De-select the Fillet after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ClearSelection2 True</span></div></div></div></div></div><p>In the above line of code, we deselect the <strong>Chamfer</strong> we have created.</p><p>For de-selecting, we use <code>ClearSelection2</code> method from our Solidworks document name <code>swDoc</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Show Front View after creating Chamfer</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ShowNamedView2 &quot;&quot;, swStandardViews_e.swFrontView</span></div></div></div></div></div><p>In the above line of code, we update the <em>view orientation</em> to <strong>Front View</strong>.</p><p>In my machine, after inserting a sketch view orientation does not changed.</p><p>Because of this I have to update the view to <strong>Front view</strong>.</p><p>For showing <strong>Front View</strong> we used <code>ShowNamedView2</code> method from our Solidworks document name <code>swDoc</code>.</p><p>This method takes 2 parameter described as follows:</p><ul><li><p><strong>VName</strong> : Name of the view to display or an empty string to use ViewId instead</p></li><li><p><strong>ViewId</strong> : ID of the view to display as defined by <code>swStandardViews_e</code> or -1 to use the <strong>VName</strong> argument instead.</p></li></ul><p><em>NOTE:</em> If you specify both <strong>VName</strong> and <strong>ViewId</strong>, then <strong>ViewId</strong> takes precedence if the two arguments do not resolve to the same view.</p><p><code>swStandardViews_e</code> has following Standard View Types:</p><ul><li><p><em>swBackView</em></p></li><li><p><em>swBottomView</em></p></li><li><p><em>swDimetricView</em></p></li><li><p><em>swFrontView</em></p></li><li><p><em>swIsometricView</em></p></li><li><p><em>swLeftView</em></p></li><li><p><em>swRightView</em></p></li><li><p><em>swTopView</em></p></li><li><p><em>swTrimetricView</em></p></li></ul><p>In our code, we did not use <strong>VName</strong> instead I used <em>empty string</em> in form of <strong><em>&quot;&quot;</em></strong> symbol.</p><p>I used <strong>ViewId</strong> value to specify view and used <code>swStandardViews_e.swFrontView</code> value to use <em>Standard Front View</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Zoom to fit screen in Solidworks Window</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ViewZoomtofit</span></div></div></div></div></div><p>In this last line we use <em>zoom to fit</em> command.</p><p>For Zoom to fit, we use <code>ViewZoomtofit</code> method from our Solidworks document variable <code>swDoc</code>.</p><p>This is it !!!</p><p>If you found anything to add or update, please let me know on my e-mail.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="vba-language-feature-used-in-this-post"></a>VBA Language feature used in this post<a aria-hidden="true" tabindex="-1" class="hash-link" href="#vba-language-feature-used-in-this-post" title="Direct link to heading">#</a></h2><p>In this post used some features of <strong>VBA programming language</strong>.</p><p>This section of post, has some brief information about the VBA programming language specific features.</p><ol><li>We use <strong>Option Explicit</strong> for capturing un-declared variables.</li></ol><p>If you want to read more about <strong>Option Explicit</strong> then please visit <strong><a href="/docs/vba/vba-variables-decl">Declaring and Scoping of Variables</a></strong>.</p><ol start="2"><li>Then we create <strong>variable</strong> for different data types.</li></ol><p>If you don&#x27;t know about them, then please visit <strong><a href="/docs/vba/vba-variables">Variables</a></strong> and <strong><a href="/docs/vba/vba-prog-concept#data-types-in-vba">Data-types</a></strong> posts of this blog.</p><p>These posts will help you to understand what <strong>Variables</strong> are and how to use them.</p><ol start="3"><li>Then we create <strong>main Sub procedure</strong> for our macro.</li></ol><p>If you don&#x27;t know about the <strong>Sub procedure</strong>, then I suggest you to visit <strong><a href="/docs/vba/vba-procedures">VBA Sub and Function Procedures</a></strong> and <strong><a href="/docs/vba/vba-procedures-exec">Executing Sub and Function Procedures</a></strong> posts of this blog.</p><p>These posts will help you to understand what <strong>Procedures</strong> are and how to use them.</p><ol start="4"><li>In most part we create some variables and set their values. We set those values by using some <strong>functions</strong> provided from objects.</li></ol><p>If you don&#x27;t know about the <strong>functions</strong>, then you should visit <strong><a href="/docs/vba/vba-functions">VBA Functions</a></strong> and <strong><a href="/docs/vba/vba-functions-adv">VBA Functions that do more</a></strong> posts of this blog.</p><p>These posts will help you to understand what <strong>functions</strong> are and how to use them.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="solidworks-api-objects"></a>Solidworks API Objects<a aria-hidden="true" tabindex="-1" class="hash-link" href="#solidworks-api-objects" title="Direct link to heading">#</a></h2><p>In this post, for creating a <strong>Fillet</strong>, we use <em>Solidworks API objects and their methods</em>.</p><p>This section contains the list of all <strong>Solidworks Objects</strong> used in this post.</p><p>I have also attached links of these <strong>Solidworks API Objects</strong> in <strong>API Help website</strong>.</p><p>If you want to explore those objects, you can use these links.</p><p>These Solidworks API Objects are listed below:</p><ul><li><strong>Solidworks Application Object</strong></li></ul><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Application Object</strong> object you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html" target="_blank" rel="noopener noreferrer">this link</a></strong>.</p><ul><li><strong>Solidworks Document Object</strong></li></ul><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Document Object</strong> object you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html" target="_blank" rel="noopener noreferrer">this link</a></strong>.</p><ul><li><strong>Solidworks Sketch Manager Object</strong></li></ul><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Sketch Manager Object</strong> you can visit <strong><a href="/docs/solidworks-macros/help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this link</a></strong>.</p><ul><li><strong>Solidworks Sketch Segment Object</strong></li></ul><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Sketch Segment Object</strong> you can visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html" target="_blank" rel="noopener noreferrer">this link</a></strong>.</p><hr><p>Hope this post helps you to <em>create a Chamfer</em> in Sketches with Solidworks VB Macros.</p><p>For more such tutorials on <strong>Solidworks VBA Macros</strong>, do come to this blog after sometime.</p><p>Till then, Happy learning!!!</p></div></article><div class="margin-vert--lg"><nav class="pagination-nav" aria-label="Blog list page navigation"><div class="pagination-nav__item"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-create-fillet"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Â« Create a Fillet</div></a></div><div class="pagination-nav__item pagination-nav__item--next"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-trim-entities"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Trim Sketch Entities Â»</div></a></div></nav></div></div></div><div class="col col--3"><div class="tableOfContents_3SO_"><ul class="table-of-contents table-of-contents__left-border"><li><a href="#video-of-code-on-youtube" class="table-of-contents__link">Video of Code on YouTube</a></li><li><a href="#for-experience-macro-developer" class="table-of-contents__link">For Experience Macro Developer</a></li><li><a href="#for-beginners-macro-developers" class="table-of-contents__link">For Beginners Macro Developers</a><ul><li><a href="#understanding-the-code" class="table-of-contents__link">Understanding the Code</a></li><li><a href="#note" class="table-of-contents__link">NOTE</a></li></ul></li><li><a href="#vba-language-feature-used-in-this-post" class="table-of-contents__link">VBA Language feature used in this post</a></li><li><a href="#solidworks-api-objects" class="table-of-contents__link">Solidworks API Objects</a></li></ul></div></div></div></div></main></div></div><footer class="footer"><div class="container"><div class="row footer__links"><div class="col footer__col"><h4 class="footer__title">Tutorials</h4><ul class="footer__items"><li class="footer__item"><a class="footer__link-item" href="/docs/vba-Intro">VBA Introduction</a></li><li class="footer__item"><a class="footer__link-item" href="/docs/vba-in-sw">VBA in Solidworks</a></li><li class="footer__item">
                <div>
                  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                  
                  <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002" data-ad-slot="6644001766" data-ad-format="auto" data-full-width-responsive="true"></ins>
                  <script>(adsbygoogle=window.adsbygoogle||[]).push({})</script>
                </div>            
                </li></ul></div><div class="col footer__col"><h4 class="footer__title">Community</h4><ul class="footer__items"><li class="footer__item"><a href="https://www.facebook.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Facebook</a></li><li class="footer__item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" rel="noopener noreferrer" class="footer__link-item">YouTube</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">More</h4><ul class="footer__items"><li class="footer__item"><a href="mailto:thecadcoder@gmail.com" target="_blank" rel="noopener noreferrer" class="footer__link-item">E-Mail</a></li><li class="footer__item"><a href="https://www.buymeacoffee.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Buy Me a Coffee</a></li></ul></div></div><div class="text--center"><div>Copyright Â© 2020 The Cad Coder, Inc. Built with Docusaurus.</div></div></div></footer></div>
<script src="/styles.e684f388.js"></script>
<script src="/runtime~main.10187eec.js"></script>
<script src="/main.d90b1f90.js"></script>
<script src="/1.1af7f77d.js"></script>
<script src="/2.4f0019c3.js"></script>
<script src="/94.4b40930d.js"></script>
<script src="/95.2f44d2c3.js"></script>
<script src="/f976f453.e3619938.js"></script>
<script src="/17896441.361bff39.js"></script>
<script src="/1f161840.e3b9e0d9.js"></script>
</body>
</html>