<!doctype html>
<html lang="en" dir="ltr" class="docs-wrapper docs-doc-page docs-version-current plugin-docs plugin-id-solidworks-macros docs-doc-id-open-saved-document">
<head>
<meta charset="UTF-8">
<meta name="generator" content="Docusaurus v2.1.0">
<title data-rh="true">Solidworks Macro - Open Saved Documents | The CAD Coder</title><meta data-rh="true" name="viewport" content="width=device-width,initial-scale=1"><meta data-rh="true" name="twitter:card" content="summary_large_image"><meta data-rh="true" property="og:url" content="https://thecadcoder.com//solidworks-macros/open-saved-document"><meta data-rh="true" name="docusaurus_locale" content="en"><meta data-rh="true" name="docsearch:language" content="en"><meta data-rh="true" name="docusaurus_version" content="current"><meta data-rh="true" name="docusaurus_tag" content="docs-solidworks-macros-current"><meta data-rh="true" name="docsearch:version" content="current"><meta data-rh="true" name="docsearch:docusaurus_tag" content="docs-solidworks-macros-current"><meta data-rh="true" property="og:title" content="Solidworks Macro - Open Saved Documents | The CAD Coder"><link data-rh="true" rel="icon" href="/assets/logo.png"><link data-rh="true" rel="canonical" href="https://thecadcoder.com//solidworks-macros/open-saved-document"><link data-rh="true" rel="alternate" href="https://thecadcoder.com//solidworks-macros/open-saved-document" hreflang="en"><link data-rh="true" rel="alternate" href="https://thecadcoder.com//solidworks-macros/open-saved-document" hreflang="x-default"><link rel="stylesheet" href="/assets/css/styles.fa9eade3.css">
<link rel="preload" href="/assets/js/runtime~main.87a6ab9f.js" as="script">
<link rel="preload" href="/assets/js/main.6107f5d7.js" as="script">
</head>
<body class="navigation-with-keyboard">
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<div role="region" aria-label="theme.common.skipToMainContent"><a href="#" class="skipToContent_fXgn">Skip to main content</a></div><nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><button aria-label="Navigation bar toggle" class="navbar__toggle clean-btn" type="button" tabindex="0"><svg width="30" height="30" viewBox="0 0 30 30" aria-hidden="true"><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><a class="navbar__brand" href="/"><div class="navbar__logo"><img src="/assets/logo.png" alt="My Site Logo" class="themedImage_ToTc themedImage--light_HNdA"><img src="/assets/logo.png" alt="My Site Logo" class="themedImage_ToTc themedImage--dark_i4oU"></div><b class="navbar__title text--truncate">The CAD Coder</b></a><a class="navbar__item navbar__link" href="/vba/vba-introduction">VBA</a><div class="navbar__item dropdown dropdown--hoverable"><a href="#" aria-haspopup="true" aria-expanded="false" role="button" class="navbar__link">Solidworks API Tutorials</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/solidworks-macros/vba-in-solidworks">Solidworks API + VBA</a></li><li><a class="dropdown__link" href="/solidworks-csharp/solidworks-CSharp-Api">Solidworks API + C#</a></li><li><a class="dropdown__link" href="/solidworks-cpp/solidworks-Cpp-Api">Solidworks API + C++</a></li></ul></div></div><div class="navbar__items navbar__items--right"><a class="navbar__item navbar__link" href="/resources">Resources</a><a class="navbar__item navbar__link" href="/aboutme">About Me</a><div class="toggle_vylO colorModeToggle_DEke"><button class="clean-btn toggleButton_gllP toggleButtonDisabled_aARS" type="button" disabled="" title="Switch between dark and light mode (currently light mode)" aria-label="Switch between dark and light mode (currently light mode)"><svg viewBox="0 0 24 24" width="24" height="24" class="lightToggleIcon_pyhR"><path fill="currentColor" d="M12,9c1.65,0,3,1.35,3,3s-1.35,3-3,3s-3-1.35-3-3S10.35,9,12,9 M12,7c-2.76,0-5,2.24-5,5s2.24,5,5,5s5-2.24,5-5 S14.76,7,12,7L12,7z M2,13l2,0c0.55,0,1-0.45,1-1s-0.45-1-1-1l-2,0c-0.55,0-1,0.45-1,1S1.45,13,2,13z M20,13l2,0c0.55,0,1-0.45,1-1 s-0.45-1-1-1l-2,0c-0.55,0-1,0.45-1,1S19.45,13,20,13z M11,2v2c0,0.55,0.45,1,1,1s1-0.45,1-1V2c0-0.55-0.45-1-1-1S11,1.45,11,2z M11,20v2c0,0.55,0.45,1,1,1s1-0.45,1-1v-2c0-0.55-0.45-1-1-1C11.45,19,11,19.45,11,20z M5.99,4.58c-0.39-0.39-1.03-0.39-1.41,0 c-0.39,0.39-0.39,1.03,0,1.41l1.06,1.06c0.39,0.39,1.03,0.39,1.41,0s0.39-1.03,0-1.41L5.99,4.58z M18.36,16.95 c-0.39-0.39-1.03-0.39-1.41,0c-0.39,0.39-0.39,1.03,0,1.41l1.06,1.06c0.39,0.39,1.03,0.39,1.41,0c0.39-0.39,0.39-1.03,0-1.41 L18.36,16.95z M19.42,5.99c0.39-0.39,0.39-1.03,0-1.41c-0.39-0.39-1.03-0.39-1.41,0l-1.06,1.06c-0.39,0.39-0.39,1.03,0,1.41 s1.03,0.39,1.41,0L19.42,5.99z M7.05,18.36c0.39-0.39,0.39-1.03,0-1.41c-0.39-0.39-1.03-0.39-1.41,0l-1.06,1.06 c-0.39,0.39-0.39,1.03,0,1.41s1.03,0.39,1.41,0L7.05,18.36z"></path></svg><svg viewBox="0 0 24 24" width="24" height="24" class="darkToggleIcon_wfgR"><path fill="currentColor" d="M9.37,5.51C9.19,6.15,9.1,6.82,9.1,7.5c0,4.08,3.32,7.4,7.4,7.4c0.68,0,1.35-0.09,1.99-0.27C17.45,17.19,14.93,19,12,19 c-3.86,0-7-3.14-7-7C5,9.07,6.81,6.55,9.37,5.51z M12,3c-4.97,0-9,4.03-9,9s4.03,9,9,9s9-4.03,9-9c0-0.46-0.04-0.92-0.1-1.36 c-0.98,1.37-2.58,2.26-4.4,2.26c-2.98,0-5.4-2.42-5.4-5.4c0-1.81,0.89-3.42,2.26-4.4C12.92,3.04,12.46,3,12,3L12,3z"></path></svg></button></div><div class="searchBox_ZlJk"><div class="navbar__search searchBarContainer_NW3z"><input placeholder="Search" aria-label="Search" class="navbar__search-input"><div class="loadingRing_RJI3 searchBarLoadingRing_YnHq"><div></div><div></div><div></div><div></div></div><div class="searchHintContainer_Pkmr"><kbd class="searchHint_iIMx">ctrl</kbd><kbd class="searchHint_iIMx">K</kbd></div></div></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div></nav><div class="main-wrapper mainWrapper_z2l0 docsWrapper_BCFX"><button aria-label="Scroll back to top" class="clean-btn theme-back-to-top-button backToTopButton_sjWU" type="button"></button><div class="docPage__5DB"><aside class="theme-doc-sidebar-container docSidebarContainer_b6E3"><div class="sidebar_njMd"><nav class="menu thin-scrollbar menu_SIkG"><ul class="theme-doc-sidebar-menu menu__list"><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret menu__link--active" aria-expanded="true" href="/solidworks-macros/vba-in-solidworks">GENERAL - SOLIDWORKS FUNCTIONS</a></div><ul style="display:block;overflow:visible;height:auto" class="menu__list"><li class="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-2 menu__list-item"><a class="menu__link" tabindex="0" href="/solidworks-macros/vba-in-solidworks">Introduction</a></li><li class="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-2 menu__list-item"><a class="menu__link" tabindex="0" href="/solidworks-macros/open-new-document">Open new Part document</a></li><li class="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-2 menu__list-item"><a class="menu__link" tabindex="0" href="/solidworks-macros/open-assembly-and-drawing">Open Assembly and Drawing document</a></li><li class="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-2 menu__list-item"><a class="menu__link" tabindex="0" href="/solidworks-macros/select-plane-from-tree">Selection Methods</a></li><li class="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-2 menu__list-item"><a class="menu__link menu__link--active" aria-current="page" tabindex="0" href="/solidworks-macros/open-saved-document">Open Saved Documents</a></li><li class="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-2 menu__list-item"><a class="menu__link" tabindex="0" href="/solidworks-macros/unit-correction">Fix Unit Issue</a></li></ul></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/sketch-create-line">SKETCH - LINES</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/create-corner-rectangle">SKETCH - RECTANGLES</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/create-circle">SKETCH - CIRCLES</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/create-centerpoint-arc">SKETCH - ARCS</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/create-straight-slot">SKETCH - SLOTS</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/create-point">SKETCH - POINT AND SPLINE</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/create-sketch-fillet">SKETCH - FILLET AND CHAMFER</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/trim-entities">SKETCH - TRIM AND EXTEND</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/offset-entities">SKETCH - OFFSET AND MIRROR</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/linear-skech-pattern">SKETCH - PATTERNS</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/move-copy-sketch-entities">SKETCH - MOVE AND ROTATE</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/toggle-display-sketch-relation">SKETCH - RELATIONS</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/add-dimension-methods">SKETCH - DIMENSIONS</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/feature-create-extrude-boss">FEATURES - EXTRUDES</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/feature-create-extrude-cut">FEATURES - CUTS</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/feature-create-hole-wizard">FEATURES - HOLES AND THREADS</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/feature-create-fillet">FEATURES - FILLET &amp; CHAMFER</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/feature-create-mirror">FEATURES - MIRROR &amp; PATTERNS</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/feature-create-rib">FEATURES - TRANSFORMATION</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/feature-reference-plane">REFERENCE GEOMETRY</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/assembly-insert-component">ASSEMBLY - GENERAL</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/assembly-conicident-mate">ASSEMBLY - STANDARD MATES</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/assembly-width-mate">ASSEMBLY - ADVANCED MATES</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/assembly-rename-mate">ASSEMBLY - EDITING MATES</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/assembly-insert-virtual-part">ASSEMBLY - COMPONENTS</a></div></li><li class="theme-doc-sidebar-item-category theme-doc-sidebar-item-category-level-1 menu__list-item menu__list-item--collapsed"><div class="menu__list-item-collapsible"><a class="menu__link menu__link--sublist menu__link--sublist-caret" aria-expanded="false" href="/solidworks-macros/convert-to-construction-sketch-segment">SKETCH - OTHERS</a></div></li></ul></nav><button type="button" title="Collapse sidebar" aria-label="Collapse sidebar" class="button button--secondary button--outline collapseSidebarButton_PEFL"><svg width="20" height="20" aria-hidden="true" class="collapseSidebarButtonIcon_kv0_"><g fill="#7a7a7a"><path d="M9.992 10.023c0 .2-.062.399-.172.547l-4.996 7.492a.982.982 0 01-.828.454H1c-.55 0-1-.453-1-1 0-.2.059-.403.168-.551l4.629-6.942L.168 3.078A.939.939 0 010 2.528c0-.548.45-.997 1-.997h2.996c.352 0 .649.18.828.45L9.82 9.472c.11.148.172.347.172.55zm0 0"></path><path d="M19.98 10.023c0 .2-.058.399-.168.547l-4.996 7.492a.987.987 0 01-.828.454h-3c-.547 0-.996-.453-.996-1 0-.2.059-.403.168-.551l4.625-6.942-4.625-6.945a.939.939 0 01-.168-.55 1 1 0 01.996-.997h3c.348 0 .649.18.828.45l4.996 7.492c.11.148.168.347.168.55zm0 0"></path></g></svg></button></div></aside><main class="docMainContainer_gTbr"><div class="container padding-top--md padding-bottom--lg"><div class="row"><div class="col docItemCol_VOVn"><div class="docItemContainer_Djhp"><article><nav class="theme-doc-breadcrumbs breadcrumbsContainer_Z_bl" aria-label="Breadcrumbs"><ul class="breadcrumbs" itemscope="" itemtype="https://schema.org/BreadcrumbList"><li class="breadcrumbs__item"><a aria-label="Home page" class="breadcrumbs__link" href="/"><svg viewBox="0 0 24 24" class="breadcrumbHomeIcon_OVgt"><path d="M10 19v-5h4v5c0 .55.45 1 1 1h3c.55 0 1-.45 1-1v-7h1.7c.46 0 .68-.57.33-.87L12.67 3.6c-.38-.34-.96-.34-1.34 0l-8.36 7.53c-.34.3-.13.87.33.87H5v7c0 .55.45 1 1 1h3c.55 0 1-.45 1-1z" fill="currentColor"></path></svg></a></li><li class="breadcrumbs__item"><span class="breadcrumbs__link">GENERAL - SOLIDWORKS FUNCTIONS</span><meta itemprop="position" content="1"></li><li itemscope="" itemprop="itemListElement" itemtype="https://schema.org/ListItem" class="breadcrumbs__item breadcrumbs__item--active"><span class="breadcrumbs__link" itemprop="name">Open Saved Documents</span><meta itemprop="position" content="2"></li></ul></nav><div class="tocCollapsible_ETCw theme-doc-toc-mobile tocMobile_ITEo"><button type="button" class="clean-btn tocCollapsibleButton_TO0P">On this page</button></div><div class="theme-doc-markdown markdown"><header><h1>Solidworks Macro - Open Saved Documents</h1></header><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002" data-ad-slot="6644001766" data-ad-format="auto" data-full-width-responsive="true"></ins><p>In this post, I tell you how to <em>open a saved document</em> in Solidworks using <em>VBA Macro</em>.</p><p>We open document with 2 different methods.</p><ol><li><p>By <code>OpenDoc</code> method</p></li><li><p>By <code>OpenDoc6</code> method</p></li></ol><h2 class="anchor anchorWithStickyNavbar_LWe7" id="video-of-code-on-youtube">Video of Code on YouTube<a class="hash-link" href="#video-of-code-on-youtube" title="Direct link to heading">​</a></h2><p>Please see below video 🎬 on <strong>how to Open Saved Documents</strong> from Visual Studio.</p><iframe src="https://www.youtube.com/embed/DeltLKXAIjY" frameborder="0" width="100%" height="500"></iframe><p>Please note that there are <strong>no explaination</strong> in the video. </p><p><strong>Explaination</strong> of each line and why we write code this way is given in this post.</p><h2 class="anchor anchorWithStickyNavbar_LWe7" id="by-opendoc-method">By OpenDoc method<a class="hash-link" href="#by-opendoc-method" title="Direct link to heading">​</a></h2><p>This is <strong>the simplest</strong> method to open a saved part from your computer.</p><p>In this method we just need two information.</p><ul><li><p>Location of document to open</p></li><li><p>Type of document which we want to open</p></li></ul><p>Below is the example code for opening a saved document using <code>OpenDoc</code> method.</p><div class="language-vb codeBlockContainer_Ckt0 theme-code-block" style="--prism-color:#000000;--prism-background-color:#ffffff"><div class="codeBlockContent_biex"><pre tabindex="0" class="prism-code language-vb codeBlock_bY9V thin-scrollbar"><code class="codeBlockLines_e6Vv codeBlockLinesWithNumbering_o6Pm"><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token keyword" style="color:rgb(0, 0, 255)">Option</span><span class="token plain"> Explicit</span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain" style="display:inline-block"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Creating variable for Solidworks application</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">Dim</span><span class="token plain"> swApp </span><span class="token keyword" style="color:rgb(0, 0, 255)">As</span><span class="token plain"> SldWorks</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">SldWorks</span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Creating variable for Solidworks document</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">Dim</span><span class="token plain"> swDoc </span><span class="token keyword" style="color:rgb(0, 0, 255)">As</span><span class="token plain"> SldWorks</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">ModelDoc2</span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Boolean Variable</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">Dim</span><span class="token plain"> BoolStatus </span><span class="token keyword" style="color:rgb(0, 0, 255)">As</span><span class="token plain"> </span><span class="token keyword" style="color:rgb(0, 0, 255)">Boolean</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain" style="display:inline-block"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain" style="display:inline-block"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Main function of our VBA program</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">Sub</span><span class="token plain"> main</span><span class="token punctuation" style="color:rgb(4, 81, 165)">(</span><span class="token punctuation" style="color:rgb(4, 81, 165)">)</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain" style="display:inline-block"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  </span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Setting Solidworks variable to Solidworks application</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  </span><span class="token keyword" style="color:rgb(0, 0, 255)">Set</span><span class="token plain"> swApp </span><span class="token operator" style="color:rgb(0, 0, 0)">=</span><span class="token plain"> Application</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">SldWorks</span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">      </span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  </span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Open a saved document</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  </span><span class="token keyword" style="color:rgb(0, 0, 255)">Set</span><span class="token plain"> swDoc </span><span class="token operator" style="color:rgb(0, 0, 0)">=</span><span class="token plain"> swApp</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">OpenDoc</span><span class="token punctuation" style="color:rgb(4, 81, 165)">(</span><span class="token string" style="color:rgb(163, 21, 21)">&quot;H:\Solidworks studies\API Studies\Chapter 1 - The Basics\1st example part.SLDPRT&quot;</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> swDocumentTypes_e</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">swDocPART</span><span class="token punctuation" style="color:rgb(4, 81, 165)">)</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">      </span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  </span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Selecting Front Plane</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  BoolStatus </span><span class="token operator" style="color:rgb(0, 0, 0)">=</span><span class="token plain"> swDoc</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">SelectByID</span><span class="token punctuation" style="color:rgb(4, 81, 165)">(</span><span class="token string" style="color:rgb(163, 21, 21)">&quot;Front Plane&quot;</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token string" style="color:rgb(163, 21, 21)">&quot;PLANE&quot;</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token number" style="color:rgb(9, 134, 88)">0</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token number" style="color:rgb(9, 134, 88)">0</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token number" style="color:rgb(9, 134, 88)">0</span><span class="token punctuation" style="color:rgb(4, 81, 165)">)</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain" style="display:inline-block"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">End</span><span class="token plain"> </span><span class="token keyword" style="color:rgb(0, 0, 255)">Sub</span></span></span></code></pre><div class="buttonGroup__atx"><button type="button" aria-label="Copy code to clipboard" title="Copy" class="clean-btn"><span class="copyButtonIcons_eSgA" aria-hidden="true"><svg class="copyButtonIcon_y97N" viewBox="0 0 24 24"><path d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z"></path></svg><svg class="copyButtonSuccessIcon_LjdS" viewBox="0 0 24 24"><path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg></span></button></div></div></div><p>I have already explained every line except <em>middle line</em> in above code sample in previous posts.</p><p>To open a saved document we used following lline.</p><div class="language-vb codeBlockContainer_Ckt0 theme-code-block" style="--prism-color:#000000;--prism-background-color:#ffffff"><div class="codeBlockContent_biex"><pre tabindex="0" class="prism-code language-vb codeBlock_bY9V thin-scrollbar"><code class="codeBlockLines_e6Vv codeBlockLinesWithNumbering_o6Pm"><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Open a saved document</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">Set</span><span class="token plain"> swDoc </span><span class="token operator" style="color:rgb(0, 0, 0)">=</span><span class="token plain"> swApp</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">OpenDoc</span><span class="token punctuation" style="color:rgb(4, 81, 165)">(</span><span class="token string" style="color:rgb(163, 21, 21)">&quot;H:\Solidworks studies\API Studies\Chapter 1 - The Basics\1st example part.SLDPRT&quot;</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> swDocumentTypes_e</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">swDocPART</span><span class="token punctuation" style="color:rgb(4, 81, 165)">)</span></span></span></code></pre><div class="buttonGroup__atx"><button type="button" aria-label="Copy code to clipboard" title="Copy" class="clean-btn"><span class="copyButtonIcons_eSgA" aria-hidden="true"><svg class="copyButtonIcon_y97N" viewBox="0 0 24 24"><path d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z"></path></svg><svg class="copyButtonSuccessIcon_LjdS" viewBox="0 0 24 24"><path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg></span></button></div></div></div><p>Here, we set the <code>ModelDoc2</code> variable <code>swDoc</code> to a value.</p><p>This value is <em>return</em> or <em>provided</em> by <code>OpenDoc</code> method.</p><p>This method is part of <em>Solidworks document</em>. </p><p>Since we define <code>swApp</code> variable as Solidworks document hence we 1st call <code>swApp</code> and then using <code>Dot operator</code> we access the <code>OpenDoc</code> method.</p><p><code>OpenDoc</code> method takes 2 <em>arguments</em> or <em>parameter</em>.</p><p><em>FileName</em> : Document name or full path if not in current directory, including extension.</p><p><em>Type</em> : Document type as define in <code>swDocumentTypes_e</code> as follows.</p><ul><li><p><code>swDocASSEMBLY</code></p></li><li><p><code>swDocDRAWING</code></p></li><li><p><code>swDocLAYOUT</code></p></li><li><p><code>swDocNONE</code></p></li><li><p><code>swDocPART</code></p></li><li><p><code>swDocSDM</code></p></li></ul><div class="theme-admonition theme-admonition-info alert alert--info admonition_LlT9"><div class="admonitionHeading_tbUL"><span class="admonitionIcon_kALy"><svg viewBox="0 0 14 16"><path fill-rule="evenodd" d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"></path></svg></span>info</div><div class="admonitionContent_S0QG"><p>If you want to open a Library feature part then we use <code>swDocPART</code> as document type.</p></div></div><p><strong>Return Value</strong> - If the document opens then this method returns <code>True</code> and otherwise <code>False</code>.</p><p>If you just want to open a saved document then this method is what you are looking for.</p><p>For most of the part, <code>OpenDoc</code> method works well.</p><p>If you want more option while opening a document, then next method is for you.</p><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002" data-ad-slot="6644001766" data-ad-format="auto" data-full-width-responsive="true"></ins><hr><h2 class="anchor anchorWithStickyNavbar_LWe7" id="by-opendoc6-method">By OpenDoc6 method<a class="hash-link" href="#by-opendoc6-method" title="Direct link to heading">​</a></h2><p><code>OpenDoc6</code> method is extension to <code>OpenDoc</code> with some additional parameters.</p><p>How <code>OpenDoc6</code> works is shown in below code sample:</p><div class="language-vb codeBlockContainer_Ckt0 theme-code-block" style="--prism-color:#000000;--prism-background-color:#ffffff"><div class="codeBlockContent_biex"><pre tabindex="0" class="prism-code language-vb codeBlock_bY9V thin-scrollbar"><code class="codeBlockLines_e6Vv codeBlockLinesWithNumbering_o6Pm"><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token keyword" style="color:rgb(0, 0, 255)">Option</span><span class="token plain"> Explicit</span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain" style="display:inline-block"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Creating variable for Solidworks application</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">Dim</span><span class="token plain"> swApp </span><span class="token keyword" style="color:rgb(0, 0, 255)">As</span><span class="token plain"> SldWorks</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">SldWorks</span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Creating variable for Solidworks document</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">Dim</span><span class="token plain"> swDoc </span><span class="token keyword" style="color:rgb(0, 0, 255)">As</span><span class="token plain"> SldWorks</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">ModelDoc2</span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Boolean Variable</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">Dim</span><span class="token plain"> BoolStatus </span><span class="token keyword" style="color:rgb(0, 0, 255)">As</span><span class="token plain"> </span><span class="token keyword" style="color:rgb(0, 0, 255)">Boolean</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain" style="display:inline-block"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain" style="display:inline-block"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Main function of our VBA program</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">Sub</span><span class="token plain"> main</span><span class="token punctuation" style="color:rgb(4, 81, 165)">(</span><span class="token punctuation" style="color:rgb(4, 81, 165)">)</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain" style="display:inline-block"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  </span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Setting Solidworks variable to Solidworks application</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  </span><span class="token keyword" style="color:rgb(0, 0, 255)">Set</span><span class="token plain"> swApp </span><span class="token operator" style="color:rgb(0, 0, 0)">=</span><span class="token plain"> Application</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">SldWorks</span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">      </span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  </span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Open an saved document</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  </span><span class="token keyword" style="color:rgb(0, 0, 255)">Set</span><span class="token plain"> swDoc </span><span class="token operator" style="color:rgb(0, 0, 0)">=</span><span class="token plain"> swApp</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">OpenDoc6</span><span class="token punctuation" style="color:rgb(4, 81, 165)">(</span><span class="token string" style="color:rgb(163, 21, 21)">&quot;H:\Solidworks studies\API Studies\Chapter 1 - The Basics\1st example part.SLDPRT&quot;</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> swDocumentTypes_e</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">swDocPART</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> swOpenDocOptions_e</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">swOpenDocOptions_Silent</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token string" style="color:rgb(163, 21, 21)">&quot;&quot;</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token number" style="color:rgb(9, 134, 88)">0</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token number" style="color:rgb(9, 134, 88)">0</span><span class="token punctuation" style="color:rgb(4, 81, 165)">)</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">      </span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  </span><span class="token comment" style="color:rgb(0, 128, 0)">&#x27; Selecting Front Plane</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain">  BoolStatus </span><span class="token operator" style="color:rgb(0, 0, 0)">=</span><span class="token plain"> swDoc</span><span class="token punctuation" style="color:rgb(4, 81, 165)">.</span><span class="token plain">SelectByID</span><span class="token punctuation" style="color:rgb(4, 81, 165)">(</span><span class="token string" style="color:rgb(163, 21, 21)">&quot;Front Plane&quot;</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token string" style="color:rgb(163, 21, 21)">&quot;PLANE&quot;</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token number" style="color:rgb(9, 134, 88)">0</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token number" style="color:rgb(9, 134, 88)">0</span><span class="token punctuation" style="color:rgb(4, 81, 165)">,</span><span class="token plain"> </span><span class="token number" style="color:rgb(9, 134, 88)">0</span><span class="token punctuation" style="color:rgb(4, 81, 165)">)</span><span class="token plain"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain" style="display:inline-block"></span></span></span><span class="token-line codeLine_lJS_" style="color:#000000"><span class="codeLineNumber_Tfdd"></span><span class="codeLineContent_feaV"><span class="token plain"></span><span class="token keyword" style="color:rgb(0, 0, 255)">End</span><span class="token plain"> </span><span class="token keyword" style="color:rgb(0, 0, 255)">Sub</span></span></span></code></pre><div class="buttonGroup__atx"><button type="button" aria-label="Copy code to clipboard" title="Copy" class="clean-btn"><span class="copyButtonIcons_eSgA" aria-hidden="true"><svg class="copyButtonIcon_y97N" viewBox="0 0 24 24"><path d="M19,21H8V7H19M19,5H8A2,2 0 0,0 6,7V21A2,2 0 0,0 8,23H19A2,2 0 0,0 21,21V7A2,2 0 0,0 19,5M16,1H4A2,2 0 0,0 2,3V17H4V3H16V1Z"></path></svg><svg class="copyButtonSuccessIcon_LjdS" viewBox="0 0 24 24"><path d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z"></path></svg></span></button></div></div></div><p>This code sample is similar is to previous example code except for <code>OpenDoc6</code> method takes extra 4 parameters.</p><p><code>OpenDoc6</code> method takes 6 <em>arguments</em> or <em>parameter</em>.</p><p><em>FileName</em> : Document name or full path if not in current directory, including extension.</p><p><em>Type</em> : Document type as define in <code>swDocumentTypes_e</code> as follows.</p><ul><li><p><code>swDocASSEMBLY</code></p></li><li><p><code>swDocDRAWING</code></p></li><li><p><code>swDocLAYOUT</code></p></li><li><p><code>swDocNONE</code></p></li><li><p><code>swDocPART</code></p></li><li><p><code>swDocSDM</code></p></li></ul><div class="theme-admonition theme-admonition-info alert alert--info admonition_LlT9"><div class="admonitionHeading_tbUL"><span class="admonitionIcon_kALy"><svg viewBox="0 0 14 16"><path fill-rule="evenodd" d="M7 2.3c3.14 0 5.7 2.56 5.7 5.7s-2.56 5.7-5.7 5.7A5.71 5.71 0 0 1 1.3 8c0-3.14 2.56-5.7 5.7-5.7zM7 1C3.14 1 0 4.14 0 8s3.14 7 7 7 7-3.14 7-7-3.14-7-7-7zm1 3H6v5h2V4zm0 6H6v2h2v-2z"></path></svg></span>info</div><div class="admonitionContent_S0QG"><p>f you want to open a Library feature part then we use <code>swDocPART</code> as document type.</p></div></div><p><em>Options</em> : Mode in which to open the document as defined in <code>swOpenDocOptions_e</code>.</p><p>For more details about <em>Options</em> parameters, please visit 🚀 <strong><a href="https://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swOpenDocOptions_e.html" target="_blank" rel="noopener noreferrer">this page of Solidworks API Help</a></strong>.</p><p><em>Configuration</em> : Configuration in which you want to open this document.</p><ul><li><p>Applies to <em>Part</em> and <em>Assemblies</em>, not <em>drawings</em>.</p></li><li><p>If this argument is <em>empty</em> or the specified configuration is <em>not present</em> in the model, the model is opened in the last-used configuration.</p></li></ul><p>I used an <code>&quot;&quot;</code> in the above code sample, because I want to open part file in last saved configuration.</p><p>If you don&#x27;t know about <code>&quot;&quot;</code>, then this symbol represent an <strong>empty string</strong>.</p><p>When we don&#x27;t want to pass any value as <code>string</code>, at that time I use <code>&quot;&quot;</code>.</p><p>You can also use <code>&quot;&quot;</code> when you want to pass an empty string in VBA.</p><p><em>Errors</em> : Load errors as defined in <code>swFileLoadError_e</code>.</p><p>For more details about <em>Errors</em> parameters, please visit 🚀 <strong><a href="http://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swFileLoadError_e.html" target="_blank" rel="noopener noreferrer">this page of Solidworks API Help</a></strong>.</p><p>Since this parameter is <code>long</code> type, and I don&#x27;t want to enter any value from the provided list; I used <strong>0</strong> as value.</p><p>If you want to use options from option link then you can use values from there.</p><p>It is just I don&#x27;t want to load any error information about the part.</p><p><em>Warnings</em> : Warnings or extra information generated during the open operation as defined in <code>swFileLoadWarning_e</code>.</p><p>For more details about <em>Warnings</em> parameters, please visit 🚀 <strong><a href="http://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swFileLoadWarning_e.html" target="_blank" rel="noopener noreferrer">this page of Solidworks API Help</a>.</strong></p><p>As in the previous parameter, I use <strong>0</strong> as value.</p><p><strong>Return Value</strong> - If the document opens then this method returns <code>True</code> and otherwise <code>False</code>.</p><p>As you can see, in <code>OpenDoc6</code> method, we need to defined the extra parameters compared to <code>OpenDoc</code> method.</p><p>It is worth noted that, <code>OpenDoc6</code> method is the most updated method for opening a saved document.</p><p>Hence if did not use any of the above method, I would recommend you to use <code>OpenDoc6</code> method.</p><p>Hope this post helps you to understand opening methods with Solidworks VB Macros.</p><p>For more such tutorials on Solidworks VBA Macros, do come to this blog after sometime.</p><p>Till then, Happy learning!!!</p></div><br><script>window.location.reload(!0)</script><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002" data-ad-slot="6644001766" data-ad-format="auto" data-full-width-responsive="true"></ins><footer class="theme-doc-footer docusaurus-mt-lg"><div class="theme-doc-footer-tags-row row margin-bottom--sm"><div class="col"><b>Tags:</b><ul class="tags_jXut padding--none margin-left--sm"><li class="tag_QGVx"><a class="tag_zVej tagRegular_sFm0" href="/solidworks-macros/tags/solidworks-macro">Solidworks Macro</a></li></ul></div></div></footer></article><nav class="pagination-nav docusaurus-mt-lg" aria-label="Docs pages navigation"><a class="pagination-nav__link pagination-nav__link--prev" href="/solidworks-macros/select-plane-from-tree"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Solidworks Macro - Selection Methods</div></a><a class="pagination-nav__link pagination-nav__link--next" href="/solidworks-macros/unit-correction"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Solidworks Macro - Fix Unit Issue</div></a></nav></div></div><div class="col col--3"><div class="tableOfContents_bqdL thin-scrollbar theme-doc-toc-desktop"><div><ul class="table-of-contents table-of-contents__left-border"><li><a href="#video-of-code-on-youtube" class="table-of-contents__link toc-highlight">Video of Code on YouTube</a></li><li><a href="#by-opendoc-method" class="table-of-contents__link toc-highlight">By OpenDoc method</a></li><li><a href="#by-opendoc6-method" class="table-of-contents__link toc-highlight">By OpenDoc6 method</a></li></ul><ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002" data-ad-slot="4311368222" data-ad-format="auto" data-full-width-responsive="true"></ins></div></div></div></div></div></main></div></div><footer class="footer"><div class="container container-fluid"><div class="row footer__links"><div class="col footer__col"><div class="footer__title">Docs</div><ul class="footer__items clean-list"><li class="footer__item"><a class="footer__link-item" href="/vba/vba-introduction">VBA Tutorials</a></li><li class="footer__item"><a class="footer__link-item" href="/solidworks-macros/vba-in-solidworks">Solidworks VBA Tutorials</a></li></ul></div><div class="col footer__col"><div class="footer__title">Links</div><ul class="footer__items clean-list"><li class="footer__item"><a class="footer__link-item" href="/aboutme">About</a></li><li class="footer__item"><a class="footer__link-item" href="/resources">Resources</a></li><li class="footer__item"><a class="footer__link-item" href="/privacy">Privacy Policy</a></li></ul></div></div><div class="footer__bottom text--center"><div class="footer__copyright">Copyright © 2022 The CAD Coder.</div></div></div></footer></div>
<script src="/assets/js/runtime~main.87a6ab9f.js"></script>
<script src="/assets/js/main.6107f5d7.js"></script>
</body>
</html>