<!doctype html>
<!--
  Minimal Mistakes Jekyll Theme 4.21.0 by Michael Rose
  Copyright 2013-2020 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE
-->
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">

<!-- begin _includes/seo.html --><title>Solidworks Macro - Create Extrude/Boss - The CAD Coder</title>
<meta name="description" content="In this post, I tell you about how to create Extrude/Boss through Solidworks VBA Macros in a sketch.">


  <meta name="author" content="Admin">
  
  <meta property="article:author" content="Admin">
  


<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="Solidworks Macro - Create Extrude/Boss">
<meta property="og:url" content="http://localhost:4000/solidworks-macros/create-extrude-feature/">


  <meta property="og:description" content="In this post, I tell you about how to create Extrude/Boss through Solidworks VBA Macros in a sketch.">







  <meta property="article:published_time" content="2021-02-08T14:03:29+00:00">





  

  


<link rel="canonical" href="http://localhost:4000/solidworks-macros/create-extrude-feature/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": "Admin",
      "url": "http://localhost:4000/"
    
  }
</script>






<!-- end _includes/seo.html -->


<link href="/feed.xml" type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">

<!-- https://t.co/dKP3o1e -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">

<script>
  document.documentElement.className = document.documentElement.className.replace(/\bno-js\b/g, '') + ' js ';
</script>

<!-- For all browsers -->
<link rel="stylesheet" href="/assets/css/main.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">

<!--[if IE]>
  <style>
    /* old IE unsupported flexbox fixes */
    .greedy-nav .site-title {
      padding-right: 3em;
    }
    .greedy-nav button {
      position: absolute;
      top: 0;
      right: 0;
      height: 100%;
    }
  </style>
<![endif]-->



    <!-- start custom head snippets -->

<!-- insert favicons. use https://realfavicongenerator.net/ -->

<!-- end custom head snippets -->

  </head>

  <body class="layout--single">
    <nav class="skip-links">
  <h2 class="screen-reader-text">Skip links</h2>
  <ul>
    <li><a href="#site-nav" class="screen-reader-shortcut">Skip to primary navigation</a></li>
    <li><a href="#main" class="screen-reader-shortcut">Skip to content</a></li>
    <li><a href="#footer" class="screen-reader-shortcut">Skip to footer</a></li>
  </ul>
</nav>

    <!--[if lt IE 9]>
<div class="notice--danger align-center" style="margin: 0;">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</div>
<![endif]-->

    

<div class="masthead">
  <div class="masthead__inner-wrap">
    <div class="masthead__menu">
      <nav id="site-nav" class="greedy-nav">
        
          <a class="site-logo" href="/"><img src="/assets/logo.png" alt=""></a>
        
        <a class="site-title" href="/">
          The CAD Coder
          
        </a>
        <ul class="visible-links"><li class="masthead__menu-item">
              <a href="/vba/vba-Introduction/">VBA</a>
            </li><li class="masthead__menu-item">
              <a href="/solidworks-macros/vba-in-solidworks/">Solidworks VBA Macro</a>
            </li><li class="masthead__menu-item">
              <a href="/Solidworks-csharp-api-tutorials/">Solidworks C# API</a>
            </li><li class="masthead__menu-item">
              <a href="/Solidworks-cpp-api-tutorials/">Solidworks C++ API</a>
            </li><li class="masthead__menu-item">
              <a href="/resources/">Resources</a>
            </li><li class="masthead__menu-item">
              <a href="/aboutMe/">About</a>
            </li></ul>
        
        <button class="search__toggle" type="button">
          <span class="visually-hidden">Toggle search</span>
          <svg class="icon" width="16" height="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15.99 16">
            <path d="M15.5,13.12L13.19,10.8a1.69,1.69,0,0,0-1.28-.55l-0.06-.06A6.5,6.5,0,0,0,5.77,0,6.5,6.5,0,0,0,2.46,11.59a6.47,6.47,0,0,0,7.74.26l0.05,0.05a1.65,1.65,0,0,0,.5,1.24l2.38,2.38A1.68,1.68,0,0,0,15.5,13.12ZM6.4,2A4.41,4.41,0,1,1,2,6.4,4.43,4.43,0,0,1,6.4,2Z" transform="translate(-.01)"></path>
          </svg>
        </button>
        
        <button class="greedy-nav__toggle hidden" type="button">
          <span class="visually-hidden">Toggle menu</span>
          <div class="navicon"></div>
        </button>
        <ul class="hidden-links hidden"></ul>
      </nav>
    </div>
  </div>
</div>


    <div class="initial-content">
      



<div id="main" role="main">
  
  <div class="sidebar sticky">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">General - Solidworks Functions</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/vba-in-solidworks/">Introduction</a></li>
          
            <li><a href="/solidworks-macros/open-new-document/">Open new Part document</a></li>
          
            <li><a href="/solidworks-macros/open-assembly-and-drawing/">Open Assembly and Drawing document</a></li>
          
            <li><a href="/solidworks-macros/select-plane-from-tree/">Selection Methods</a></li>
          
            <li><a href="/solidworks-macros/open-saved-document/">Open Saved Documents</a></li>
          
            <li><a href="/solidworks-macros/unit-correction/">Fix Unit Issue</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Lines</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/sketch-create-line/">Create Line</a></li>
          
            <li><a href="/solidworks-macros/sketch-create-centerline/">Create CenterLine</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Rectangles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-corner-rectangle/">Create Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-center-rectangle/">Create Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-corner-rectangle/">Create 3-Point Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-center-rectangle/">Create 3-Point Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-parallelogram/">Create A Parallelogram</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Circles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-circle/">Create Circle</a></li>
          
            <li><a href="/solidworks-macros/create-circle-by-radius/">Create Circle By Radius</a></li>
          
            <li><a href="/solidworks-macros/create-perimeter-circle/">Create Perimeter Circle</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Arcs</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc/">Create Centerpoint Arc</a></li>
          
            <li><a href="/solidworks-macros/create-tangent-arc/">Create Tangent Arc</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc/">Create 3-Point Arc</a></li>
          
            <li><a href="/solidworks-macros/polygon/">Create Polygon</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Slots</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-straight-slot/">Create a Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-straight-slot/">Create a Centerpoint Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc-slot/">Create a 3-Point Arc Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc-slot/">Create a Centerpoint Arc Slot</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Point and Spline</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-point/">Create a Point</a></li>
          
            <li><a href="/solidworks-macros/create-spline/">Create a Spline</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Fillet and Chamfer</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-fillet/">Create a Fillet</a></li>
          
            <li><a href="/solidworks-macros/create-chamfer/">Create a Chamfer</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Trim and Extend</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/trim-entities/">Trim Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/extend-entities/">Extend Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Patterns</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/linear-skech-pattern/">Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-linear-skech-pattern/">Edit Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/circular-skech-pattern/">Circular Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-circular-skech-pattern/">Edit Circular Sketch Pattern</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Move and Rotate</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/move-copy-sketch-entities/">Move/Copy Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/rotate-copy-sketch-entities/">Rotate/Copy Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Relations</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/toggle-display-sketch-relation/">Toggle (Hide/Show) Sketch Relations</a></li>
          
            <li><a href="/solidworks-macros/add-sketch-relations/">Add Sketch Relations (Constraints)</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Dimensions</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/add-dimension-methods/">Add dimension to Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-extrude-feature/" class="active">Extrude Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Others</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/convert-to-construction-sketch-segment/">Convert to Construction Sketch</a></li>
          
            <li><a href="/solidworks-macros/split-sketch-segments/">Split Open/Closed Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>



  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    <meta itemprop="headline" content="Solidworks Macro - Create Extrude/Boss">
    <meta itemprop="description" content="In this post, I tell you about how to create Extrude/Boss through Solidworks VBA Macros in a sketch.">
    
    

    <div class="page__inner-wrap">
      
        <header>
          <h1 id="page-title" class="page__title" itemprop="headline">Solidworks Macro - Create Extrude/Boss
</h1>
          

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          11 minute read
        
      </span>
    
  </p>


        </header>
      

      <section class="page__content" itemprop="text">
        
          <aside class="sidebar__right sticky">
            <nav class="toc">
              <header><h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4></header>
              <ul class="toc__menu"><li><a href="#code-sample">Code Sample</a></li><li><a href="#understanding-the-code">Understanding the Code</a></li><li><a href="#method-parameters-details">Method Parameters Details</a></li></ul>

            </nav>
          </aside>
        
        <p>In this post, I tell you about <em>how to create Extrude/Boss through Solidworks VBA Macros</em> in a sketch.</p>

<p>In this post, I tell you about <code class="language-plaintext highlighter-rouge">FeatureExtrusion3</code> method from <strong>Solidworks</strong> <code class="language-plaintext highlighter-rouge">FeatureManager</code> object.</p>

<p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>.</p>

<p>So <strong><em>use this method</em></strong> if you want to create a new <strong>Corner Extrude/Boss</strong>.</p>

<hr />

<!--
## Video of Code on YouTube

Please see below video on **how to create Corner Rectangle** from Solidworks VBA Macros.

<iframe src="https://www.youtube.com/embed/03s3pWNIC08" frameborder="0" allowfullscreen></iframe>
<br>

Please note that there are **no explaination** in the video. 

**Explaination** of each line and why we write code this way is given in this post.
---
-->
<h2 id="code-sample">Code Sample</h2>

<p>Below is the <code class="language-plaintext highlighter-rouge">code</code> sample for creating Corner Rectangle.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>
<span class="c1">' Creating variable for Solidworks Sketch Manager</span>
<span class="k">Dim</span> <span class="nv">swSketchManager</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchManager</span>
<span class="c1">' Creating variable for Solidworks Feature</span>
<span class="k">Dim</span> <span class="nv">swFeature</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">Feature</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Setting Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Creating string type variable for storing default part location</span>
  <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
  <span class="c1">' Setting value of this string type variable to "Default part template"</span>
  <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>

  <span class="c1">' Setting Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

  <span class="c1">' Selecting Front Plane</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Setting Sketch manager for our sketch</span>
  <span class="k">Set</span> <span class="n">swSketchManager</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span>
  
  <span class="c1">' Inserting a sketch into selected plane</span>
  <span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
  
  <span class="c1">' Creating a "Variant" Variable which holds the values return by "CreateCornerRectangle" method</span>
  <span class="k">Dim</span> <span class="nv">vSketchLines</span> <span class="ow">As</span> <span class="kt">Variant</span>
  
  <span class="c1">' Creating a Corner Rectangle</span>
  <span class="n">vSketchLines</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateCornerRectangle</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
  
  <span class="c1">' De-select the lines after creation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
  
  <span class="c1">' Zoom to fit screen in Solidworks Window</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ViewZoomtofit2</span>
  
  <span class="c1">' Exit the Sketch</span>
  <span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>

  <span class="c1">' Create Extrude Feature</span>
  <span class="k">Set</span> <span class="n">swFeature</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">FeatureManager</span><span class="p">.</span><span class="n">FeatureExtrusion3</span><span class="p">(</span><span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="n">swEndConditions_e</span><span class="p">.</span><span class="n">swEndCondBlind</span><span class="p">,</span> <span class="n">swEndConditions_e</span><span class="p">.</span><span class="n">swEndCondBlind</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="n">swEndConditions_e</span><span class="p">.</span><span class="n">swEndCondBlind</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<hr />

<h2 id="understanding-the-code">Understanding the Code</h2>

<p>Now let us walk through <strong>each line</strong> in the above code, and <strong>understand</strong> the meaning and purpose of every line.</p>

<p>I also give some link so that you can go through them if there are anything I explained in previous posts.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>
</code></pre></div></div>

<p>This line forces us to define every variable we are going to use.</p>

<p>For more information please visit <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
</code></pre></div></div>

<p>In this line, we create a variable which we named as <code class="language-plaintext highlighter-rouge">swApp</code> and the type of this <code class="language-plaintext highlighter-rouge">swApp</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.SldWorks</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
</code></pre></div></div>

<p>In this line, we create a variable which we named as <code class="language-plaintext highlighter-rouge">swDoc</code> and the type of this <code class="language-plaintext highlighter-rouge">swDoc</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.ModelDoc2</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>
</code></pre></div></div>

<p>In this line, we create a variable named <code class="language-plaintext highlighter-rouge">BoolStatus</code> as <code class="language-plaintext highlighter-rouge">Boolean</code> object type.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create variable for Solidworks Sketch Manager</span>
<span class="k">Dim</span> <span class="nv">swSketchManager</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchManager</span>
</code></pre></div></div>

<p>In above line, we create variable <code class="language-plaintext highlighter-rouge">swSketchManager</code> for <strong>Solidworks Sketch Manager</strong>.</p>

<p>As the name suggested, a <strong>Sketch Manager</strong> holds variours methods and properties to manage <em>Sketches</em>.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">SketchManager</code> object, please visit <strong><a href="https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this page of Solidworks API Help</a></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks Feature</span>
<span class="k">Dim</span> <span class="nv">swFeature</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">Feature</span>
</code></pre></div></div>

<p>In this line, we Create a variable which we named as <code class="language-plaintext highlighter-rouge">swFeature</code> and the type of this <code class="language-plaintext highlighter-rouge">swFeature</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.Feature</code>.</p>

<p>We create variable <code class="language-plaintext highlighter-rouge">swFeature</code> for <strong>Solidworks Feature</strong>.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">Feature</code> object, please visit <strong><a href="https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeature_members.html">this page of Solidworks API Help</a></strong></p>

<p>These all are our global variables.</p>

<p>As you can see in code sample, they are <strong>Solidworks API Objects</strong>.</p>

<p>So basically I group all the <strong>Solidworks API Objects</strong> in one place.</p>

<p>I have also place <code class="language-plaintext highlighter-rouge">boolean</code> type object at top also, because after certain point we will <em>need</em> this variable frequently.</p>

<p>Thus, I have started placing it here.</p>

<p>Next is our <code class="language-plaintext highlighter-rouge">Sub</code> procedure which has name of <code class="language-plaintext highlighter-rouge">main</code>.</p>

<p>This procedure hold all the <em>statements (instructions)</em> we give to computer.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Solidworks variable to Solidworks application</span>
<span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
</code></pre></div></div>

<p>In this line, we set the value of our Solidworks variable <code class="language-plaintext highlighter-rouge">swApp</code>; which we define earlier; to Solidworks application.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create string type variable for storing default part location</span>
<span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
<span class="c1">' Set value of this string type variable to "Default part template"</span>
<span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>
</code></pre></div></div>

<p>In 1st statement of above example, we are defining a variable of <code class="language-plaintext highlighter-rouge">string</code> type and named it as <code class="language-plaintext highlighter-rouge">defaultTemplate</code>.</p>

<p>This variable <code class="language-plaintext highlighter-rouge">defaultTemplate</code>, hold the location the location of <strong>Default Part Template</strong>.</p>

<p>In 2nd line of above example. we assign value to our newly define <code class="language-plaintext highlighter-rouge">defaultTemplate</code> variable.</p>

<p>We assign the value by using a <em>Method</em> named <code class="language-plaintext highlighter-rouge">GetUserPreferenceStringValue()</code>.</p>

<p>This <code class="language-plaintext highlighter-rouge">GetUserPreferenceStringValue()</code> method is a part of our main Solidworks variable <code class="language-plaintext highlighter-rouge">swApp</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Solidworks document to new part document</span>
<span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
</code></pre></div></div>

<p>In this line, we set the value of our <code class="language-plaintext highlighter-rouge">swDoc</code> variable to new document.</p>

<p>For <strong>detailed information</strong> about these lines please visit <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post.</p>

<p>I have discussed them <strong>thoroghly</strong> in <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post, so do checkout that post if you want to understand above code in more detail.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Select Front Plane</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line, we select the <em>front plane</em> by using <code class="language-plaintext highlighter-rouge">SelectByID2</code> method from <code class="language-plaintext highlighter-rouge">Extension</code> object.</p>

<p>For more information about selection method please visit <strong><a href="/solidworks-macros/select-plane-from-tree">Solidworks Macros - Selection Methods</a></strong> post.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Sketch manager for our sketch</span>
<span class="k">Set</span> <span class="n">swSketchManager</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span>
</code></pre></div></div>

<p>In above line, we set the <em>Sketch manager</em> variable to <em>current document’s sketch manager</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Insert a sketch into selected plane</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
</code></pre></div></div>

<p>In above line, we use <code class="language-plaintext highlighter-rouge">InsertSketch</code> method of <em>SketchManager</em> and give <code class="language-plaintext highlighter-rouge">True</code> value.</p>

<p>This method allows us to <strong>insert</strong> a sketch in selected plane.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating a "Variant" Variable which holds the values return by "CreateCornerRectangle" method</span>
<span class="k">Dim</span> <span class="nv">vSketchLines</span> <span class="ow">As</span> <span class="kt">Variant</span>
    
<span class="c1">' Creating a Corner Rectangle</span>
<span class="n">vSketchLines</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateCornerRectangle</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
</code></pre></div></div>

<p>In above sample code, we 1st create a variable named <code class="language-plaintext highlighter-rouge">vSketchLines</code> of type <code class="language-plaintext highlighter-rouge">Variant</code>.</p>

<p>A <code class="language-plaintext highlighter-rouge">Variant</code> type variable can hold <strong>any</strong> type of value depends upon the use of variable.</p>

<p>In 2nd line, we set the value of variable <code class="language-plaintext highlighter-rouge">vSketchLines</code>.</p>

<p>In the above code sample I have used (0, 1, 0) Upper-left point in <em>Y-direction</em>.</p>

<p>For Lower-right point I used (1, 0, 0) which is 1 point distance in <em>X-direction</em>.</p>

<p>This <code class="language-plaintext highlighter-rouge">CreateCornerRectangle</code> method returns <strong>an array</strong> of <em>sketch segments</em> that represent the edges created for this corner rectangle.</p>

<p>For more information about <strong>Create Corner Rectangle</strong> please visit <strong><a href="/solidworks-macros/create-corner-rectangle">Solidworks Macros - Selection Methods</a></strong> post.</p>

<p class="notice--warning">It is <strong><em>very important</em></strong> to remember that, when you give distance or any other numeric value in <strong>Solidworks API</strong>, Solidworks takes that numeric value in <strong><em>Meter only</em></strong>.<br />
Solidworks API does not care about your application’s Unit systems.<br />
For example, I works in ANSI system means inches for distance.<br /> But when I used Solidworks API through VBA macros or C#, I need to use converted numeric values.<br />
Because Solidworks API output the distance in <strong>Meter</strong> which is not my requirement.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' De-select the lines after creation</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
</code></pre></div></div>

<p>In the this line of code, we deselect the Corner rectangle we have created.</p>

<p>For de-selecting, we use <code class="language-plaintext highlighter-rouge">ClearSelection2</code> method from our Solidworks document name <code class="language-plaintext highlighter-rouge">swDoc</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Zoom to fit screen in Solidworks Window</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ViewZoomtofit2</span>
</code></pre></div></div>

<p>In this last line we use <em>zoom to fit</em> command.</p>

<p>For Zoom to fit, we use <code class="language-plaintext highlighter-rouge">ViewZoomtofit</code> method from our Solidworks document variable <code class="language-plaintext highlighter-rouge">swDoc</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Exit the Sketch</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
</code></pre></div></div>

<p>In above line, we use <code class="language-plaintext highlighter-rouge">InsertSketch</code> method of <em>SketchManager</em> and give <code class="language-plaintext highlighter-rouge">True</code> value.</p>

<p>This method allows us to <strong>exit</strong> a sketch in selected plane.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create Extrude Feature</span>
<span class="k">Set</span> <span class="n">swFeature</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">FeatureManager</span><span class="p">.</span><span class="n">FeatureExtrusion3</span><span class="p">(</span><span class="k">True</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="n">swEndConditions_e</span><span class="p">.</span><span class="n">swEndCondBlind</span><span class="p">,</span> <span class="n">swEndConditions_e</span><span class="p">.</span><span class="n">swEndCondBlind</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="n">swEndConditions_e</span><span class="p">.</span><span class="n">swEndCondBlind</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line of code we set the value of variable <code class="language-plaintext highlighter-rouge">swFeature</code> by <code class="language-plaintext highlighter-rouge">FeatureExtrusion3</code> method.</p>

<p><code class="language-plaintext highlighter-rouge">FeatureExtrusion3</code> method is part of <code class="language-plaintext highlighter-rouge">FeatureManager</code> object.</p>

<p>This <code class="language-plaintext highlighter-rouge">FeatureManager</code> is again part of <code class="language-plaintext highlighter-rouge">swDoc</code> variable i.e. <code class="language-plaintext highlighter-rouge">ModelDoc2</code> object.</p>

<h2 id="method-parameters-details">Method Parameters Details</h2>

<p>This <code class="language-plaintext highlighter-rouge">FeatureExtrusion3</code> method takes following parameters as explained:</p>

<ul>
  <li>
    <p><strong>Sd</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> for single ended, <code class="language-plaintext highlighter-rouge">False</code> for double ended.</em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-1.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-1.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>Flip</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> to flip the side to cut</em></p>

    <p class="notice--warning">This option activate when we select feature “<strong>Extruded Cut</strong>”.</p>
  </li>
  <li>
    <p><strong>Dir</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> to flip the direction of extrusion.</em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-2.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-2.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>T1</strong> - <em>Termination type for first end of the extrusion as defined in <code class="language-plaintext highlighter-rouge">swEndConditions_e</code>.</em></p>

    <p>End Conditions has following enumeration values:</p>

    <ul>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondBlind</code> or <strong>0</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondMidPlane</code> or <strong>6</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondOffsetFromSurface</code> or <strong>5</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondThroughAll</code> or <strong>1</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondThroughAllBoth</code> or <strong>9</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondThroughNext</code> or <strong>2</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondUpToBody</code> or <strong>7</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondUpToNext</code> or <strong>11</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondUpToSelection</code> or <strong>10</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondUpToSurface</code> or <strong>4</strong> = Do not use; superseded by <code class="language-plaintext highlighter-rouge">swEndCondUpToSelection</code></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swEndCondUpToVertex</code> or <strong>3</strong> = Do not use; superseded by <code class="language-plaintext highlighter-rouge">swEndCondUpToSelection</code></p>
      </li>
    </ul>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-3.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-3.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>T2</strong> - <em>Termination type for second end of the extrusion as defined in <code class="language-plaintext highlighter-rouge">swEndConditions_e</code>.</em></p>

    <p>End Conditions has enumeration values as described in <strong>T1</strong>.</p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-4.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-4.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>D1</strong> - <em>Depth of extrusion for first end in meters; offset, if <strong>T1</strong> is set to <code class="language-plaintext highlighter-rouge">swEndConditions_e.swEndCondOffsetFromSurface</code></em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-5.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-5.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>D2</strong> - <em>Depth of extrusion for second end in meters; offset, if <strong>T2</strong> is set to <code class="language-plaintext highlighter-rouge">swEndConditions_e.swEndCondOffsetFromSurface</code></em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-6.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-6.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>Dchk1</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> to allow drafting in the first direction, <code class="language-plaintext highlighter-rouge">False</code> to not</em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-7.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-7.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>Dchk2</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> to allow drafting in the second direction, <code class="language-plaintext highlighter-rouge">False</code> to not</em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-8.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-8.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>Ddir1</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> for first draft angle to be inward, <code class="language-plaintext highlighter-rouge">False</code> to be outward; valid only if <strong>Dchk1</strong> is true</em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-9.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-9.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>Ddir2</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> for second draft angle to be inward, <code class="language-plaintext highlighter-rouge">False</code> to be outward; valid only if <strong>Dchk2</strong> is true</em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-10.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-10.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>Dang1</strong> - <em>Draft angle for first end; valid only if <strong>Dchk1</strong> is true</em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-11.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-11.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>Dang2</strong> - <em>Draft angle for second end; valid only if <strong>Dchk2</strong> is true</em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-12.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-12.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>OffsetReverse1</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> to offset the first end from another face or plane in a direction away from the sketch, <code class="language-plaintext highlighter-rouge">False</code> to offset in a direction toward the sketch; valid only if <strong>T1</strong> is set to <code class="language-plaintext highlighter-rouge">swEndConditions_e.swEndCondOffsetFromSurface</code></em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-13.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-13.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>OffsetReverse2</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> to offset the second end from another face or plane in a direction away from the sketch, <code class="language-plaintext highlighter-rouge">False</code> to offset in a direction toward the sketch; valid only if <strong>T2</strong> is set to <code class="language-plaintext highlighter-rouge">swEndConditions_e.swEndCondOffsetFromSurface</code></em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-14.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-14.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>TranslateSurface1</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> if the first end of the extrusion is a translation of the reference surface, <code class="language-plaintext highlighter-rouge">False</code> if it has a true offset; valid only if <strong>T1</strong> is set to <code class="language-plaintext highlighter-rouge">swEndConditions_e.swEndCondOffsetFromSurface</code></em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-15.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-15.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>TranslateSurface2</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> if the second end of the extrusion is a translation of the reference surface, <code class="language-plaintext highlighter-rouge">False</code> if it has a true offset; valid only if <strong>T2</strong> is set to <code class="language-plaintext highlighter-rouge">swEndConditions_e.swEndCondOffsetFromSurface</code></em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-16.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-16.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>Merge</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> to merge the results in a multibody part, <code class="language-plaintext highlighter-rouge">False</code> to not</em></p>

    <p class="notice--warning">This option visible when we <strong>Extrude</strong> from existing <strong>feature/body</strong>.</p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-17.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-17.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>UseFeatScope</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> if the feature only affects selected bodies, <code class="language-plaintext highlighter-rouge">False</code> if the feature affects all bodies.</em></p>
  </li>
  <li>
    <p><strong>UseAutoSelect</strong> - <em>True to automatically select all bodies and have the feature affect those bodies, <code class="language-plaintext highlighter-rouge">False</code> to select the bodies that the feature affects.</em></p>
  </li>
  <li>
    <p><strong>T0</strong> - <em>Start condition as defined in <code class="language-plaintext highlighter-rouge">swStartConditions_e</code></em></p>

    <p>Start Conditions has following enumeration values:</p>

    <ul>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swStartOffset</code> or <strong>3</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swStartSketchPlane</code> or <strong>0</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swStartSurface</code> or <strong>1</strong></p>
      </li>
      <li>
        <p><code class="language-plaintext highlighter-rouge">swStartVertex</code> or <strong>2</strong></p>
      </li>
    </ul>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-18.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-18.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>StartOffset</strong> - <em>Distance from the sketch plane to start the extrude; valid only if <strong>T0</strong> is set to <code class="language-plaintext highlighter-rouge">swStartConditions_e.swStartOffset</code></em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-19.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-19.svg" alt="feature-extrude-final" /></a></p>
  </li>
  <li>
    <p><strong>FlipStartOffset</strong> - <em><code class="language-plaintext highlighter-rouge">True</code> to flip the direction of the start offset, <code class="language-plaintext highlighter-rouge">False</code> to not; valid only if <strong>T0</strong> is set to <code class="language-plaintext highlighter-rouge">swStartConditions_e.swStartOffset</code></em></p>

    <p><a href="/assets/Solidworks_Images/features-extrude/Extrude-parameter-20.svg"><img src="/assets/Solidworks_Images/features-extrude/Extrude-parameter-20.svg" alt="feature-extrude-final" /></a></p>
  </li>
</ul>

<p><strong>Return Value</strong> : This <code class="language-plaintext highlighter-rouge">FeatureExtrusion3</code> method retun <code class="language-plaintext highlighter-rouge">Feature</code> object.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">Feature</code> object, please visit <strong><a href="https://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IFeature_members.html">this page of Solidworks API Help</a></strong>.</p>

<p>In our code, I have used following values:</p>

<ul>
  <li>
    <p><strong>Sd</strong> -  <em>I use <code class="language-plaintext highlighter-rouge">True</code> for single ended.</em></p>
  </li>
  <li>
    <p><strong>Flip</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> to flip the side to cut</em></p>
  </li>
  <li>
    <p><strong>Dir</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> to flip the direction of extrusion</em></p>
  </li>
  <li>
    <p><strong>T1</strong> - *I use <code class="language-plaintext highlighter-rouge">swEndConditions_e.swEndCondBlind</code> of Termination type for first end of the extrusion *</p>
  </li>
  <li>
    <p><strong>T2</strong> - *I use <code class="language-plaintext highlighter-rouge">swEndConditions_e.swEndCondBlind</code> of Termination type for second end of the extrusion *</p>
  </li>
  <li>
    <p><strong>D1</strong> - <em>I use <code class="language-plaintext highlighter-rouge">2</code> as *Depth of extrusion</em> for first end in meters*</p>
  </li>
  <li>
    <p><strong>D2</strong> - <em>I use <code class="language-plaintext highlighter-rouge">0</code> as *Depth of extrusion</em> for second end in meters*</p>
  </li>
  <li>
    <p><strong>Dchk1</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> to allow drafting in the first direction</em></p>
  </li>
  <li>
    <p><strong>Dchk2</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> to allow drafting in the second direction</em></p>
  </li>
  <li>
    <p><strong>Ddir1</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> for first draft angle to be inward</em></p>
  </li>
  <li>
    <p><strong>Ddir2</strong> - <em>I use <code class="language-plaintext highlighter-rouge">True</code> for second draft angle to be inward</em></p>

    <p class="notice--warning">Since <strong>Dchk2</strong> is <code class="language-plaintext highlighter-rouge">False</code>, setting the value to <code class="language-plaintext highlighter-rouge">True</code> is invalid.</p>
  </li>
  <li>
    <p><strong>Dang1</strong> - <em>I use <code class="language-plaintext highlighter-rouge">0</code> for first end’s draft angle</em></p>
  </li>
  <li>
    <p><strong>Dang2</strong> - <em>I use <code class="language-plaintext highlighter-rouge">0</code> for second end’s draft angle</em></p>
  </li>
  <li>
    <p><strong>OffsetReverse1</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> to offset the first end from another face or plane in a direction away from the sketch</em></p>
  </li>
  <li>
    <p><strong>OffsetReverse2</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> to offset the second end from another face or plane in a direction away from the sketch</em></p>
  </li>
  <li>
    <p><strong>TranslateSurface1</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> to the first end of the extrusion is a translation of the reference surface</em></p>
  </li>
  <li>
    <p><strong>TranslateSurface2</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> to the second end of the extrusion is a translation of the reference surface</em></p>
  </li>
  <li>
    <p><strong>Merge</strong> - <em>I use <code class="language-plaintext highlighter-rouge">True</code> to merge the results in a multibody part</em></p>
  </li>
  <li>
    <p><strong>UseFeatScope</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> so that this feature affects to all bodies</em></p>
  </li>
  <li>
    <p><strong>UseAutoSelect</strong> - <em>I use <code class="language-plaintext highlighter-rouge">True</code> to automatically select all bodies and have the feature affect those bodies</em></p>
  </li>
  <li>
    <p><strong>T0</strong> - <em>I use <code class="language-plaintext highlighter-rouge">swEndConditions_e.swEndCondBlind</code> as Start condition</em></p>
  </li>
  <li>
    <p><strong>StartOffset</strong> - <em>I use <code class="language-plaintext highlighter-rouge">0</code> for distance from the sketch plane to start the extrude</em></p>
  </li>
  <li>
    <p><strong>FlipStartOffset</strong> - <em>I use <code class="language-plaintext highlighter-rouge">False</code> to flip the direction of the start offset</em></p>
  </li>
</ul>

<p>After running macro we get extrude as shown in below image.</p>

<p><a href="/assets/Solidworks_Images/features-extrude/extrude-part.svg"><img src="/assets/Solidworks_Images/features-extrude/extrude-part.svg" alt="feature-extrude-final" /></a></p>

<hr />

<p><strong>This is it !!!</strong></p>

<p><em>I hope my efforts will helpful to someone!</em></p>

<p>If you found anything to <strong>add or update</strong>, please let me know on my <em>e-mail</em>.</p>

<p>Hope this post helps you to <strong>create Extrude/Boss</strong> with Solidworks VBA Macros.</p>

<p>For more such tutorials on <strong>Solidworks VBA Macro</strong>, do come to this blog after sometime.</p>

<p><em>If you like the post then please share it with your friends also.</em></p>

<p><em>Do let me know by you like this post or not!</em></p>

<p><em>Till then, Happy learning!!!</em></p>

        
      </section>

      <footer class="page__meta">
        
        
  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-tags" aria-hidden="true"></i> Tags: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/tags/#solidworks-macro" class="page__taxonomy-item" rel="tag">Solidworks Macro</a>
    
    </span>
  </p>




  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-folder-open" aria-hidden="true"></i> Categories: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/categories/#solidworks-macro" class="page__taxonomy-item" rel="tag">Solidworks-macro</a>
    
    </span>
  </p>


        

      </footer>

      <section class="page__share">
  

  <a href="https://twitter.com/intent/tweet?text=Solidworks+Macro+-+Create+Extrude%2FBoss%20http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fcreate-extrude-feature%2F" class="btn btn--twitter" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Twitter"><i class="fab fa-fw fa-twitter" aria-hidden="true"></i><span> Twitter</span></a>

  <a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fcreate-extrude-feature%2F" class="btn btn--facebook" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Facebook"><i class="fab fa-fw fa-facebook" aria-hidden="true"></i><span> Facebook</span></a>

  <a href="https://www.linkedin.com/shareArticle?mini=true&url=http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fcreate-extrude-feature%2F" class="btn btn--linkedin" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on LinkedIn"><i class="fab fa-fw fa-linkedin" aria-hidden="true"></i><span> LinkedIn</span></a>
</section>



      
  <nav class="pagination">
    
      <a href="/solidworks-macros/add-dimension-methods/" class="pagination--pager" title="Solidworks Macro - Add dimension to Sketch Entities
">Previous</a>
    
    
      <a href="/solidworks-macros/convert-to-construction-sketch-segment/" class="pagination--pager" title="Solidworks Macro - Convert to Construction Sketch
">Next</a>
    
  </nav>

    </div>

    
  </article>

  
  
    <div class="page__related">
      <h4 class="page__related-title">You May Also Enjoy</h4>
      <div class="grid__wrapper">
        
      </div>
    </div>
  
  
</div>

    </div>

    
      <div class="search-content">
        <div class="search-content__inner-wrap"><form onsubmit="return googleCustomSearchExecute();" id="cse-search-box-form-id">
    <label class="sr-only" for="cse-search-input-box-id">
      Enter your search term...
    </label>
    <input type="search" id="cse-search-input-box-id" class="search-input" tabindex="-1" placeholder="Enter your search term..." />
  </form>
  <div id="results" class="results">
    <gcse:searchresults-only></gcse:searchresults-only>
  </div></div>

      </div>
    

    <div id="footer" class="page__footer">
      <footer>
        <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
        <div class="page__footer-follow">
  <ul class="social-icons">
    

    
      
        
      
        
          <li><a href="https://facebook.com/thecadcoder" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-facebook-square" aria-hidden="true"></i> Facebook</a></li>
        
      
        
      
        
      
        
      
        
      
        
          <li><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" rel="nofollow noopener noreferrer"><i class="fab fa-youtube" aria-hidden="true"></i> YouTube</a></li>
        
      
        
          <li><a href="mailto:thecadcoder@gmail.com" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-envelope-square" aria-hidden="true"></i> Email</a></li>
        
      
    

    <li><a href="/feed.xml"><i class="fas fa-fw fa-rss-square" aria-hidden="true"></i> Feed</a></li>
  </ul>
</div>

<div class="page__footer-copyright">&copy; 2021 Admin. Powered by <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a> &amp; <a href="https://mademistakes.com/work/minimal-mistakes-jekyll-theme/" rel="nofollow">Minimal Mistakes</a>. | <strong><a href="http://localhost:4000/Disclaimer/" rel="nofollow"><i class="fas fa-lock" aria-hidden="true"></i> Privacy Policy</a></strong></div>

      </footer>
    </div>

    
  <script src="/assets/js/main.min.js"></script>


<script>
  (function () {
    var cx = '4b2b9cb8c831ee0fb';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();

  function googleCustomSearchExecute() {
    var input = document.getElementById('cse-search-input-box-id');
    var element = google.search.cse.element.getElement('searchresults-only0');
    if (input.value == '') {
      element.clearAllResults();
    } else {
      element.execute(input.value);
    }
    return false;
  }

  
    $(document).ready(function () {
      $('input#cse-search-input-box-id').on('keyup', function () {
        googleCustomSearchExecute();
      });
    });
  
</script>







    <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>


  </body>
</html>
