<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- begin _includes/seo.html --><title>SOLIDWORKS C# API - Setup Test Project - The CAD Coder</title>
<meta name="description" content="Objective">



<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="SOLIDWORKS C# API - Setup Test Project">
<meta property="og:url" content="http://localhost:4000/solidworks-csharp/setup-test-project/">


  <meta property="og:description" content="Objective">







  <meta property="article:published_time" content="2025-07-29T07:06:23-04:00">






<link rel="canonical" href="http://localhost:4000/solidworks-csharp/setup-test-project/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": null,
      "url": "http://localhost:4000/"
    
  }
</script>







<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-117501871-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-117501871-2', { 'anonymize_ip': true});
</script>

<!-- end _includes/seo.html -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">
  <link
    href="/feed.xml"
    type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/main.css">

  <meta name="google-site-verification" content="OeSBbUv_kXDkDxaeoLixjE1BYxlbQRINt58H1UGbSMY" />

  

  <!-- MailerLite Universal -->
  <script>
    (function (w, d, e, u, f, l, n) {
      w[f] = w[f] || function () {
        (w[f].q = w[f].q || [])
          .push(arguments);
      }, l = d.createElement(e), l.async = 1, l.src = u,
        n = d.getElementsByTagName(e)[0], n.parentNode.insertBefore(l, n);
    })
      (window, document, 'script', 'https://assets.mailerlite.com/js/universal.js', 'ml');
    ml('account', '1644816');
  </script>
  <!-- End MailerLite Universal -->
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        <img src="/assets/logo.png" width="30" height="30" class="img-fluid" alt="">
        <span>The CAD Coder</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a  class="nav-link"   href="/knowledge-base/introduction/"><span>Knowledge Base</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/vba/vba-Introduction/"><span>VBA</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-macro-guide/"><span>Solidworks VBA Macro</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="active nav-link" style="border-bottom: 1px solid #fff;"   href="/Solidworks-csharp-api-tutorials/"><span>Solidworks C# API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-cpp-api-tutorials/"><span>Solidworks C++ API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/wpf-tutorials/syncfusion-account-signup/"><span>WPF Tutorials</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/knowledge-base/wix4-introduction/"><span>Wix4 Tutorials</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/resources/"><span>Resources</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/aboutMe/"><span>About</span></a>
            </li>
            
            <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li> -->
        </ul>
        <!-- <a class="btn btn-outline-success my-2 my-sm-0" href="/seach-document/" role="button">
            <i class="fas fa-search"></i>
        </a> -->
    </div>
</nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-lg-2 col-sm-4">
  <div class="sidebar sticky" style="width: 100%;">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">Getting Started</span>
        

        
        <ul>
          
            <li><a href="/Solidworks-csharp-api-tutorials/">Introduction</a></li>
          
            <li><a href="/solidworks-csharp/Prerequisite/">Prerequisite</a></li>
          
            <li><a href="/solidworks-csharp/open-solidworks/">Open Solidworks</a></li>
          
            <li><a href="/solidworks-csharp/open-solidworks-document/">Open Solidworks Document</a></li>
          
            <li><a href="/solidworks-csharp/browse-and-open-solidworks-file/">Browse/Open SOLIDWORKS Document</a></li>
          
            <li><a href="/solidworks-csharp/unit-correction/">Fix Unit Issue</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch Segment</span>
        

        
        <ul>
          
            <li><a href="/solidworks-csharp/insert-sketch/">Insert Solidworks Sketch</a></li>
          
            <li><a href="/solidworks-csharp/edit-sketch/">Edit Solidworks Sketch</a></li>
          
            <li><a href="/solidworks-csharp/edit-solidworks-feature-sketch/">Edit Solidworks Feature Sketch</a></li>
          
            <li><a href="/solidworks-csharp/change-sketch-name/">Change Sketch Name</a></li>
          
            <li><a href="/solidworks-csharp/delete-selected-sketch/">Delete Selected Sketch</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch Lines</span>
        

        
        <ul>
          
            <li><a href="/solidworks-csharp/create-line/">Create Line</a></li>
          
            <li><a href="/solidworks-csharp/create-line-code-refactor/">Create Line Code Refactor</a></li>
          
            <li><a href="/solidworks-csharp/setup-test-project/" class="active">Setup Test Project</a></li>
          
            <li><a href="/solidworks-csharp/test-createLine-method/">Test Create Line Method</a></li>
          
            <li><a href="/solidworks-csharp/test-applyunitconversion-method/">Test ApplyUnitConversion Method</a></li>
          
            <li><a href="/solidworks-csharp/test-SelectSketchPlane-method/">Test SelectSketchPlane Method</a></li>
          
            <li><a href="/solidworks-csharp/test-CreatePartDocument-method/">Test CreatePartDocument Method</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Others</span>
        

        
        <ul>
          
            <li><a href="/solidworks-csharp/update-dimension-state/">Update Dimension State</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>

</div>
      <div class="col-md-9 col-lg-10 col-sm-8">
        <div>
          <div id="main" role="main">

  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    
    <meta itemprop="headline" content="SOLIDWORKS C# API - Setup Test Project">
    
    <meta itemprop="description" content="Objective">
    
    
    <meta itemprop="datePublished" content="2025-07-29T07:06:23-04:00">
    

    <div class="page__inner-wrap">
      
      <header>
        <h1 id="page-title" class="page__title" itemprop="headline">SOLIDWORKS C# API - Setup Test Project
</h1>
        

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          2 minute read
        
      </span>
    
  </p>


      </header>
      

      <section class="page__content" itemprop="text">
        
        <aside class="sidebar__right sticky">
          <nav class="toc">
            <header>
              <h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4>
            </header>
            <ul class="toc__menu"><li><a href="#objective">Objective</a></li><li><a href="#demo-video">Demo Video</a></li><li><a href="#add-xunit-project">Add [xUnit] Project</a></li><li><a href="#add-mainwindowviewmodeltests">Add [MainWindowViewModelTests]</a></li><li><a href="#add-solidworks-references">Add [Solidworks References]</a></li><li><a href="#add-moq">Add [Moq]</a></li><li><a href="#add-project">Add [Project]</a></li><li><a href="#change-framework">Change Framework</a></li></ul>

            <br/>
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Vertical Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="4311368222"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          </nav>
        </aside>
        
        <div>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Horizontal Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="6007593278"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          <h2 id="objective">Objective</h2>

<p>I want to:</p>

<ul>
  <li><em>Setup Test Project for our Unit test cases.</em></li>
  <li><em>We will use <strong>xUnit</strong> as test runner and <strong>Moq</strong> for mocking the objects.</em></li>
  <li><em>I will not explain each line, since they are already explained in previous articles.</em></li>
</ul>

<hr />

<h2 id="demo-video">Demo Video</h2>

<p>Watch the video below to learn how to <strong>Setup Test Project</strong>.</p>

<iframe src="https://www.youtube.com/embed/mAkyV1Ef11o" frameborder="0" allowfullscreen=""></iframe>
<p><br /></p>

<p class="notice--info">Please note that there are <strong>no explanation</strong> in the video.<br />
<strong>Explanation</strong> of each step and why we write code this way is given in this post.</p>

<hr />

<h2 id="add-xunit-project">Add [xUnit] Project</h2>

<p>First, we need to add <strong>xUnit</strong> project to our solution.</p>

<p>Look at the picture below 👇🏻 for help.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/1-add-new-project.png"><img src="/assets/solidworks-csharp-images/setup-test-project/1-add-new-project.png" alt="1-add-new-project" /></a></p>

<p>When you do this, a new window will open.</p>

<p>Next, choose “<strong>xUnit Test Template</strong>” and then click the “<strong>Next</strong>” button. See the picture below 👇🏻.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/2-select-xunit-project.png"><img src="/assets/solidworks-csharp-images/setup-test-project/2-select-xunit-project.png" alt="2-select-xunit-project" /></a></p>

<p>When you click the “<strong>Next</strong>” button, another new window will open.</p>

<p>This window will help us set up our project.</p>

<p>Please see below 👇🏻 image for reference.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/3-configure-project-window.png"><img src="/assets/solidworks-csharp-images/setup-test-project/3-configure-project-window.png" alt="3-configure-project-window" /></a></p>

<p>In this window, fill in the Project Name as “<strong>SolidworksDemo.Test</strong>” then click the “<strong>Next</strong>” button.</p>

<p>This will open a new screen called the <strong>Additional information page</strong>.</p>

<p>On this page, <strong>do nothing</strong> and click the “<strong>Create</strong>” button.</p>

<p>This will <strong>add a new project</strong> in our solution.</p>

<p>Please see the image below of the new unit test project.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/4-new-xunit-project.png"><img src="/assets/solidworks-csharp-images/setup-test-project/4-new-xunit-project.png" alt="4-new-xunit-project" /></a></p>

<hr />

<h2 id="add-mainwindowviewmodeltests">Add [<code class="language-plaintext highlighter-rouge">MainWindowViewModelTests</code>]</h2>

<p>Now we need to <strong>delete</strong> this auto-generated “<strong><code class="language-plaintext highlighter-rouge">UnitTest1</code></strong>” file.</p>

<p>For this operation, select the <strong><code class="language-plaintext highlighter-rouge">UnitTest1</code></strong> file and open the <strong>context menu</strong> by <em>right-clicking</em> on this <strong><code class="language-plaintext highlighter-rouge">UnitTest1</code></strong> file.</p>

<p>See the image below of the <strong>Context Menu</strong>.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/5-delete-file.png"><img src="/assets/solidworks-csharp-images/setup-test-project/5-delete-file.png" alt="5-delete-file" /></a></p>

<p>Now add a new folder in our test project.</p>

<p><strong>Name of the folder</strong> = “<strong><code class="language-plaintext highlighter-rouge">ViewModel.Tests</code></strong>”</p>

<p>See the image below for reference.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/6-add-new-folder.png"><img src="/assets/solidworks-csharp-images/setup-test-project/6-add-new-folder.png" alt="6-add-new-folder" /></a></p>

<p>After this we need to add a class.</p>

<p><strong>Name of class</strong>: “<strong><code class="language-plaintext highlighter-rouge">MainWindowViewModelTests</code></strong>”</p>

<p>See the image below for reference.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/7-add-new-class-file.png"><img src="/assets/solidworks-csharp-images/setup-test-project/7-add-new-class-file.png" alt="7-add-new-class-file" /></a></p>

<hr />

<h2 id="add-solidworks-references">Add [Solidworks References]</h2>

<p>Now, we need to <strong>“Add [Solidworks References]”</strong> into our application.</p>

<p>We already <strong>have an article</strong> where we <strong>“Add [Solidworks References]”</strong> into our application.</p>

<p>Please see 🚀 <strong><em><a href="/solidworks-csharp/edit-sketch/#add-solidworks-references" target="_blank">Add [Solidworks References]</a></em></strong> section of 🚀 <strong><em><a href="/solidworks-csharp/edit-sketch/" target="_blank">SOLIDWORKS C# API - Edit Solidworks Sketch</a></em></strong> article for <strong>Adding [Solidworks References]</strong>.</p>

<hr />

<h2 id="add-moq">Add [Moq]</h2>

<p>Now we need to add <strong><code class="language-plaintext highlighter-rouge">Moq</code></strong>.</p>

<p>For this select “<strong><code class="language-plaintext highlighter-rouge">Dependencies</code></strong>” and open <strong><code class="language-plaintext highlighter-rouge">Context Menu</code></strong>.</p>

<p>After this select “<strong><code class="language-plaintext highlighter-rouge">Manage NuGet Packages</code></strong>”.</p>

<p>See below for reference.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/8-open-nuget-packages.png"><img src="/assets/solidworks-csharp-images/setup-test-project/8-open-nuget-packages.png" alt="8-open-nuget-packages" /></a></p>

<p>Now a new tab open.</p>

<p>In this tab, select <strong><code class="language-plaintext highlighter-rouge">Moq</code></strong> <em>NuGet package and install</em> it.</p>

<p>See below for reference.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/9-install-nuget-package.png"><img src="/assets/solidworks-csharp-images/setup-test-project/9-install-nuget-package.png" alt="9-install-nuget-package" /></a></p>

<hr />

<h2 id="add-project">Add [Project]</h2>

<p>Now we need to <strong>add reference</strong> of <em>Project</em> we want to test.</p>

<p>In our case, project we want to test is <strong>[<code class="language-plaintext highlighter-rouge">SolidworksTest</code>]</strong></p>

<p>Select “<strong>Add Project Reference</strong>” as shown below.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/10-add-project-reference.gif"><img src="/assets/solidworks-csharp-images/setup-test-project/10-add-project-reference.gif" alt="10-add-project-reference" /></a></p>

<hr />

<h2 id="change-framework">Change Framework</h2>

<p>After adding the project, if you see any <strong>warnings</strong> ⚠️, you need to <strong>match</strong> the <em>framework of the test project with the project it is referencing</em>.</p>

<p>In our case, our <em>main project</em> is on the “<strong><code class="language-plaintext highlighter-rouge">net8.0</code></strong>” framework and the <em>test project</em> is on the “<strong><code class="language-plaintext highlighter-rouge">net6.0-windows</code></strong>” framework.</p>

<p>To fix this, <em>copy the framework</em> from the main project and paste it into the test project framework.</p>

<p>This should solve the issue.</p>

<p>For reference, see below.</p>

<p><a href="/assets/solidworks-csharp-images/setup-test-project/11-fix-project-warning-issue.gif"><img src="/assets/solidworks-csharp-images/setup-test-project/11-fix-project-warning-issue.gif" alt="11-fix-project-warning-issue" /></a></p>

<hr />

<p><strong>This is it !!!</strong></p>

<p><em>I hope my efforts will helpful to someone!</em></p>

<p>If you found anything to <strong>add or update</strong>, please let me know on my <em>e-mail</em>.</p>

<p>Hope this post helps you to <strong>Setup Unit Test Project</strong>.</p>

<p><em>If you like the post then please share it with your friends also.</em></p>

<p><em>Do let me know by you like this post or not!</em></p>

<p><em>Till then, Happy learning!!!</em></p>

<ul>
  <li><a href="/download-solidworks-macros/">🎁 Download 5 Free SolidWorks Macros →</a></li>
</ul>

        </div>
        
        <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

      </section>

      <footer class="page__meta">
        
        


        

  <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i> Updated:</strong> <time datetime="2025-07-29T07:06:23-04:00">July 29, 2025</time></p>


      </footer>

      
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    
    <li class="page-item mr-5">
      <a class="btn btn-primary text-light" href="/solidworks-csharp/create-line-code-refactor/" title="SOLIDWORKS C# API - Create Line Code Refactor
">❮ Previous</a>
    </li>
    
    
    <li class="page-item ml-5">
      <a class="btn btn-primary text-light" href="/solidworks-csharp/test-createLine-method/" title="SOLIDWORKS C# API - Test Create Line Method
">Next ❯</a>
    </li>
    
  </ul>
</nav>

    </div>
  </article>

</div>

          
        </div>
      </div>
    </div>
  </div>

  <div id="footer" class="page__footer">
    <footer>
      <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
      <footer class="bd-footer py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <a class="d-inline-flex align-items-center mb-2 link-dark" href="/" aria-label="Bootstrap">
          <img src="/assets/logo.png" width="30" height="30" class="img-fluid mr-2" alt="">
          <span> The CAD Coder</span>
        </a>
        <ul class="list-unstyled small text-muted">
          <li class="mb-2">Programming Tutorials for SOLIDWORKS 3D CAD Software.</li>
          <li class="mb-2">Copyright © 2022 The CAD Coder</li>
          <li class="mb-2">Built with <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a>.</li>

          
          
          
          
          
          <li class="list-inline-item"><a href="https://facebook.com/thecadcoder" target="_blank" title="Facebook"><i
                class="fab fa-2x fa-facebook-f"></i></a></li>
          
          
          
          
          
          
          
          
          
          
          
          <li class="list-inline-item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" title="YouTube"><i
                class="fab fa-2x fa-youtube"></i></a></li>
          
          
          
          <li class="list-inline-item"><a href="mailto:thecadcoder@gmail.com" target="_blank" title="Email"><i
                class="fa fa-envelope fa-2x"></i></a></li>
          
          
          
        </ul>
      </div>
      <div class="col-6">
        <h5>Links</h5>
        <ul class="list-unstyled">
          <!-- <li class="mb-2"><a href="/">Home</a></li> -->
          <li class="mb-2"><a href="/aboutMe/">About</a></li>
          <li class="mb-2"><a href="/resources/">Resources</a></li>
          <li class="mb-2"><a href="/privacy-policy/">Privacy Policy</a></li>
          <li class="mb-2"><a href="/Disclaimer/">Disclaimer</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
    </footer>
  </div>

  
  <script src="/assets/js/main.min.js"></script>




<script src="/assets/js/lunr/lunr.min.js"></script>
<script src="/assets/js/lunr/lunr-store.js"></script>
<script src="/assets/js/lunr/lunr-en.js"></script>







  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->

  
  <script src="/assets/js/main.min.js"></script>




<script src="/assets/js/lunr/lunr.min.js"></script>
<script src="/assets/js/lunr/lunr-store.js"></script>
<script src="/assets/js/lunr/lunr-en.js"></script>






</body>

</html>