I"Åò<p>In this post, I tell you about <em>how to create a Chamfer through Solidworks VBA Macros</em> in a sketch.</p>

<p>This post is an extension of <strong><a href="/solidworks-macros/create-corner-rectangle">Sketch - Create Corner Rectangle</a></strong> post.</p>

<hr />

<h2 id="video-of-code-on-youtube">Video of Code on YouTube</h2>

<p>Please see below video how visually we can create <em>a Chamfer</em> from <strong>Solidworks VBA macro</strong>.</p>

<iframe src="https://www.youtube.com/embed/HobbXAv9zMI" frameborder="0" allowfullscreen=""></iframe>

<p>Please note that there are <strong>no explaination</strong> given in the video.</p>

<p><strong>Explaination</strong> of each line and why we write code this way is given in this post.</p>

<hr />

<h2 id="for-experience-macro-developer">For Experience Macro Developer</h2>

<p>If you are an experience <strong>Solidworks Macro developer</strong>, then you are looking for a specific code sample.</p>

<p>Below is the code for creating <strong>A Chamfer</strong> from <strong>Solidworks VBA Macro</strong>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks Sketch Segment</span>
<span class="k">Dim</span> <span class="nv">swSketchSegment</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchSegment</span>
      
<span class="c1">' Set the value of Solidworks Sketch segment by "CreateChamfer" method from Solidworks sketch manager</span>
<span class="k">Set</span> <span class="n">swSketchSegment</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateChamfer</span><span class="p">(</span><span class="n">swSketchChamferType_e</span><span class="p">.</span><span class="n">swSketchChamfer_DistanceEqual</span><span class="p">,</span> <span class="mf">0.1</span><span class="p">,</span> <span class="mf">0.2</span><span class="p">)</span>
</code></pre></div></div>

<p>For creating a <strong>Chamfer</strong> first you need to <strong>Create</strong> a variable of <code class="language-plaintext highlighter-rouge">SketchSegment</code> type.</p>

<p>After creating variable, you need to set the value of this variable.</p>

<p>For this you used <code class="language-plaintext highlighter-rouge">CreateChamfer</code> method from <strong>Solidworks Sketch Manager</strong>.</p>

<p>This <code class="language-plaintext highlighter-rouge">CreateChamfer</code> method set the value of <code class="language-plaintext highlighter-rouge">SketchSegment</code> type variable.</p>

<p>This <code class="language-plaintext highlighter-rouge">CreateChamfer</code> method takes following parameters as explained:</p>

<ul>
  <li>
    <p><strong>Type</strong> : <em>Type of chamfer as defined in <code class="language-plaintext highlighter-rouge">swSketchChamferType_e</code></em></p>
  </li>
  <li>
    <p><strong>Distance</strong> : <em>Distance of the chamfer</em></p>
  </li>
  <li>
    <p><strong>AngleORdist</strong> : <em>These are as follows</em></p>

    <ul>
      <li>
        <p>If Type = <code class="language-plaintext highlighter-rouge">swSketchChamfer_DistanceDistance</code>, then the second chamfer distance</p>
      </li>
      <li>
        <p>If Type = <code class="language-plaintext highlighter-rouge">swSketchChamfer_DistanceAngle</code>, then the second chamfer angle</p>
      </li>
      <li>
        <p>If Type = <code class="language-plaintext highlighter-rouge">swSketchChamfer_DistanceEqual</code>, then this argument is ignored because Distance is used for both edges</p>
      </li>
    </ul>
  </li>
</ul>

<p>If you want a more detail explaination then please read further otherwise this will help you to <strong>Create a Chamfer From VBA Macro</strong>.</p>

<hr />

<h2 id="for-beginners-macro-developers">For Beginners Macro Developers</h2>

<p>In this post, I tell you about <code class="language-plaintext highlighter-rouge">CreateChamfer</code> method from <strong>Solidworks</strong> <code class="language-plaintext highlighter-rouge">SketchManager</code> object.</p>

<p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>.</p>

<p>So <strong><em>use this method</em></strong> if you want to create a Chamfer.</p>

<p>Below is the <code class="language-plaintext highlighter-rouge">code</code> sample for creating a Chamfer.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="c1">' Creating variable for Solidworks Sketch Manager</span>
<span class="k">Dim</span> <span class="nv">swSketchManager</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchManager</span>

<span class="c1">' Creating Variable for Solidworks Sketch Segment</span>
<span class="k">Dim</span> <span class="nv">swSketchSegment</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchSegment</span>


<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Setting Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Creating string type variable for storing default part location</span>
  <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
  <span class="c1">' Setting value of this string type variable to "Default part template"</span>
  <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>

  <span class="c1">' Setting Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

  <span class="c1">' Selecting Front Plane</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>

  <span class="c1">' Setting Sketch manager for our sketch</span>
  <span class="k">Set</span> <span class="n">swSketchManager</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span>

  <span class="c1">' Inserting a sketch into selected plane</span>
  <span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
  
  <span class="c1">' Creating a "Variant" Variable which holds the values return by "CreateCornerRectangle" method</span>
  <span class="k">Dim</span> <span class="nv">vSketchLines</span> <span class="ow">As</span> <span class="kt">Variant</span>
  
  <span class="c1">' Creating a Corner Rectangle</span>
  <span class="n">vSketchLines</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateCornerRectangle</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
  
  <span class="c1">' De-select the lines after creation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
  
  <span class="c1">' Selecting Point 1</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Point1"</span><span class="p">,</span> <span class="s">"SKETCHPOINT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>

  <span class="c1">' Set the value of Solidworks Sketch segment by "CreateChamfer" method from Solidworks sketch manager</span>
  <span class="k">Set</span> <span class="n">swSketchSegment</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateChamfer</span><span class="p">(</span><span class="n">swSketchChamferType_e</span><span class="p">.</span><span class="n">swSketchChamfer_DistanceEqual</span><span class="p">,</span> <span class="mf">0.1</span><span class="p">,</span> <span class="mf">0.2</span><span class="p">)</span>

  <span class="c1">' De-select the Chamfer after creation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
  
  <span class="c1">' Show Front View after creating Chamfer</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ShowNamedView2</span> <span class="s">""</span><span class="p">,</span> <span class="n">swStandardViews_e</span><span class="p">.</span><span class="n">swFrontView</span>
  
  <span class="c1">' Zoom to fit screen in Solidworks Window</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ViewZoomtofit2</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<hr />

<h3 id="understanding-the-code">Understanding the Code</h3>

<p>Now let us walk through <em>each line</em> in the above code, and <strong>understand</strong> the meaning of every line.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>
</code></pre></div></div>

<p>This line forces us to define every variable we are going to use.</p>

<p>For more information please visit <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
</code></pre></div></div>

<p>In this line, we are creating a variable which we named as <code class="language-plaintext highlighter-rouge">swApp</code> and the type of this <code class="language-plaintext highlighter-rouge">swApp</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.SldWorks</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
</code></pre></div></div>

<p>In this line, we are creating a variable which we named as <code class="language-plaintext highlighter-rouge">swDoc</code> and the type of this <code class="language-plaintext highlighter-rouge">swDoc</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.ModelDoc2</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>
</code></pre></div></div>

<p>In this line, we create a variable named <code class="language-plaintext highlighter-rouge">BoolStatus</code> as <code class="language-plaintext highlighter-rouge">Boolean</code> object type.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks Sketch Manager</span>
<span class="k">Dim</span> <span class="nv">swSketchManager</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchManager</span>
</code></pre></div></div>

<p>In above line, we create variable <code class="language-plaintext highlighter-rouge">swSketchManager</code> for <strong>Solidworks Sketch Manager</strong>.</p>

<p>As the name suggested, a <strong>Sketch Manager</strong> holds variours methods and properties to manage <em>Sketches</em>.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">SketchManager</code> object, please visit <strong><a href="http://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this page of Solidworks API Help</a></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating variable for Solidworks Sketch Segment</span>
<span class="k">Dim</span> <span class="nv">swSketchSegment</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchSegment</span>
</code></pre></div></div>

<p>In this line, we are creating a variable which we named as <code class="language-plaintext highlighter-rouge">swSketchSegment</code> and the type of this <code class="language-plaintext highlighter-rouge">swSketchSegment</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.SketchSegment</code>.</p>

<p>We create variable <code class="language-plaintext highlighter-rouge">swSketchSegment</code> for <strong>Solidworks Sketch Segments</strong>.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">swSketchSegment</code> object, please visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html">this page of Solidworks API Help</a></strong></p>

<p>These all are our global variables.</p>

<p>As you can see in code sample, they are <strong>Solidworks API Objects</strong>.</p>

<p>So basically I group all the <strong>Solidworks API Objects</strong> in one place.</p>

<p>I have also place <code class="language-plaintext highlighter-rouge">boolean</code> type object at top also, because after certain point we will <em>need</em> this variable frequently.</p>

<p>Thus, I have started placing it here.</p>

<p>Next is our <code class="language-plaintext highlighter-rouge">Sub</code> procedure named <code class="language-plaintext highlighter-rouge">main</code>. This procedure hold all the <em>statements (instructions)</em> we give to computer.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Setting Solidworks variable to Solidworks application</span>
<span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
</code></pre></div></div>

<p>In this line, we are setting the value of our Solidworks variable which we define earlier to Solidworks application.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating string type variable for storing default part location</span>
<span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
<span class="c1">' Setting value of this string type variable to "Default part template"</span>
<span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>
</code></pre></div></div>

<p>In 1st statement of above example, we are defining a variable of <code class="language-plaintext highlighter-rouge">string</code> type and named it as <code class="language-plaintext highlighter-rouge">defaultTemplate</code>.</p>

<p>This variable <code class="language-plaintext highlighter-rouge">defaultTemplate</code>, hold the location the location of <strong>Default Part Template</strong>.</p>

<p>In 2nd line of above example. we assign value to our newly define <code class="language-plaintext highlighter-rouge">defaultTemplate</code> variable.</p>

<p>We assign the value by using a <em>Method</em> named <code class="language-plaintext highlighter-rouge">GetUserPreferenceStringValue()</code>. This method is a part of our main Solidworks variable <code class="language-plaintext highlighter-rouge">swApp</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Setting Solidworks document to new part document</span>
<span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
</code></pre></div></div>

<p>In this line, we set the value of our <code class="language-plaintext highlighter-rouge">swDoc</code> variable to new document.</p>

<p>For <strong>detailed information</strong> about these lines please visit <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post.</p>

<p>I have discussed them <strong>thoroghly</strong> in <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post, so do checkout this post if you don‚Äôt understand above code.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Selecting Front Plane</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line, we select the <em>front plane</em> by using <code class="language-plaintext highlighter-rouge">SelectByID2</code> method from <code class="language-plaintext highlighter-rouge">Extension</code> object.</p>

<p>For more information about selection method please visit <strong><a href="/solidworks-macros/select-plane-from-tree">Solidworks Macros - Selection Methods</a></strong> post.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Setting Sketch manager for our sketch</span>
<span class="k">Set</span> <span class="n">swSketchManager</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span>
</code></pre></div></div>

<p>In above line, we set the sketch manager variable to current document‚Äôs sketch manager.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Inserting a sketch into selected plane</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
</code></pre></div></div>

<p>In above line, we use <code class="language-plaintext highlighter-rouge">InsertSketch</code> method of <em>SketchManager</em> and give <code class="language-plaintext highlighter-rouge">True</code> value.</p>

<p>This method allows us to insert a sketch in selected plane.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Creating a "Variant" Variable which holds the values return by "CreateCornerRectangle" method</span>
<span class="k">Dim</span> <span class="nv">vSketchLines</span> <span class="ow">As</span> <span class="kt">Variant</span>
    
<span class="c1">' Creating a Corner Rectangle</span>
<span class="n">vSketchLines</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateCornerRectangle</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
</code></pre></div></div>

<p>In above sample code, we 1st create a variable named <code class="language-plaintext highlighter-rouge">vSketchLines</code> of type <code class="language-plaintext highlighter-rouge">Variant</code>.</p>

<p>A <code class="language-plaintext highlighter-rouge">Variant</code> type variable can hold <strong>any</strong> type of value depends upon the use of variable.</p>

<p>In 2nd line, we set the value of variable <code class="language-plaintext highlighter-rouge">vSketchLines</code>.</p>

<p>Value of <code class="language-plaintext highlighter-rouge">vSketchLinesis</code> an array of lines. This array is send as return value when we use <code class="language-plaintext highlighter-rouge">CreateCornerRectangle</code> method.</p>

<p>This <code class="language-plaintext highlighter-rouge">CreateCornerRectangle</code> method is part of <code class="language-plaintext highlighter-rouge">swSketchManager</code> and it is the latest method to create a corner rectangle.</p>

<p>For detail explaination on <code class="language-plaintext highlighter-rouge">CreateCornerRectangle</code> method, please see <strong><a href="/solidworks-macros/create-corner-rectangle">Sketch - Create Corner Rectangle</a></strong> post.</p>

<p>In the above code sample I have used (0, 1, 0) Upper-left point in <em>Y-direction</em>.</p>

<p>For Lower-right point I used (1, 0, 0) which is 1 point distance in <em>X-direction</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' De-select the Rectangle after creation</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
</code></pre></div></div>

<p>In above line, we de-select the ractangle we just create.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Selecting Front Plane</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line, we select the <em>front plane</em> by using <code class="language-plaintext highlighter-rouge">SelectByID2</code> method from <code class="language-plaintext highlighter-rouge">Extension</code> object.</p>

<p>For more information about selection method please visit <strong><a href="/solidworks-macros/select-plane-from-tree">Solidworks Macros - Selection Methods</a></strong> post.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set the value of Solidworks Sketch segment by "CreateChamfer" method from Solidworks sketch manager</span>
<span class="k">Set</span> <span class="n">swSketchSegment</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateChamfer</span><span class="p">(</span><span class="n">swSketchChamferType_e</span><span class="p">.</span><span class="n">swSketchChamfer_DistanceEqual</span><span class="p">,</span> <span class="mf">0.1</span><span class="p">,</span> <span class="mf">0.2</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line, we set the value of Solidworks Sketch Segment variable <code class="language-plaintext highlighter-rouge">swSketchSegment</code> by <code class="language-plaintext highlighter-rouge">CreateChamfer</code> method from <em>Solidworks Sketch Manager</em>.</p>

<p>This <code class="language-plaintext highlighter-rouge">CreateChamfer</code> method takes following parameters:</p>

<p><strong>Type</strong> : <em>Type of chamfer as defined in <code class="language-plaintext highlighter-rouge">swSketchChamferType_e</code></em>.</p>

<p>The <code class="language-plaintext highlighter-rouge">swSketchChamferType_e</code> has 3 values for type of chamfers:</p>

<ul>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swSketchChamfer_DistanceAngle</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swSketchChamfer_DistanceDistance</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swSketchChamfer_DistanceEqual</code></p>
  </li>
</ul>

<p><strong>Distance</strong> : <em>Distance of the chamfer</em></p>

<p><strong>AngleORdist</strong> : <em>Angle or Distance for chamfer. These are as follows</em></p>

<ul>
  <li>
    <p>If Type = <code class="language-plaintext highlighter-rouge">swSketchChamfer_DistanceDistance</code>, then the second chamfer distance</p>
  </li>
  <li>
    <p>If Type = <code class="language-plaintext highlighter-rouge">swSketchChamfer_DistanceAngle</code>, then the second chamfer angle</p>
  </li>
  <li>
    <p>If Type = <code class="language-plaintext highlighter-rouge">swSketchChamfer_DistanceEqual</code>, then this argument is ignored because Distance is used for both edges.</p>
  </li>
</ul>

<p>Below Image described <strong>the Parameters for a Chamfer</strong>.</p>

<p><img src="/assets/Solidworks_Images/fillet_and_chamfer/fillet_parameters.png" alt="fillet_parameters" /></p>

<p>In our code, I have used following values:</p>

<ul>
  <li>
    <p><strong>Type</strong> : I have used <code class="language-plaintext highlighter-rouge">swSketchChamferType_e.swSketchChamfer_DistanceEqual</code> enumerator as value for type of Chamfer.</p>
  </li>
  <li>
    <p><strong>Distance</strong> : I have used 0.1 (This value is in meter) as the distance of Chamfer.</p>
  </li>
  <li>
    <p><strong>AngleORdist</strong> : I have used 0.2 (This value is in meter). But in our code <strong>Type = <code class="language-plaintext highlighter-rouge">swSketchChamfer_DistanceEqual</code></strong>, then this argument is ignored because Distance
  is used for both edges.</p>
  </li>
</ul>

<hr />

<h3 id="note">NOTE</h3>

<p>It is <strong><em>very important</em></strong> to remember that, when you give distance or any other numeric value in <strong>Solidworks API</strong>, Solidworks takes that numeric value in <strong><em>Meter only</em></strong>.</p>

<p>Solidworks API does not care about your application‚Äôs Unit systems.</p>

<p>For example, I works in <strong>ANSI</strong> system means inches for distance. But when I used <strong>Solidworks API</strong> through <em>VBA macros or C#</em>, I need to use converted numeric values.</p>

<p>Because Solidworks API output the distance in <strong>Meter</strong> which is not my requirement.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' De-select the Fillet after creation</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
</code></pre></div></div>

<p>In the above line of code, we deselect the <strong>Chamfer</strong> we have created.</p>

<p>For de-selecting, we use <code class="language-plaintext highlighter-rouge">ClearSelection2</code> method from our Solidworks document name <code class="language-plaintext highlighter-rouge">swDoc</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Show Front View after creating Chamfer</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ShowNamedView2</span> <span class="s">""</span><span class="p">,</span> <span class="n">swStandardViews_e</span><span class="p">.</span><span class="n">swFrontView</span>
</code></pre></div></div>

<p>In the above line of code, we update the <em>view orientation</em> to <strong>Front View</strong>.</p>

<p>In my machine, after inserting a sketch view orientation does not changed.</p>

<p>Because of this I have to update the view to <strong>Front view</strong>.</p>

<p>For showing <strong>Front View</strong> we used <code class="language-plaintext highlighter-rouge">ShowNamedView2</code> method from our Solidworks document name <code class="language-plaintext highlighter-rouge">swDoc</code>.</p>

<p>This method takes 2 parameter described as follows:</p>

<p><strong>VName</strong> : Name of the view to display or an empty string to use ViewId instead</p>

<p><strong>ViewId</strong> : ID of the view to display as defined by <code class="language-plaintext highlighter-rouge">swStandardViews_e</code> or -1 to use the <strong>VName</strong> argument instead.</p>

<p><em>NOTE:</em> If you specify both <strong>VName</strong> and <strong>ViewId</strong>, then <strong>ViewId</strong> takes precedence if the two arguments do not resolve to the same view.</p>

<p><code class="language-plaintext highlighter-rouge">swStandardViews_e</code> has following Standard View Types:</p>

<ul>
  <li>
    <p><em>swBackView</em></p>
  </li>
  <li>
    <p><em>swBottomView</em></p>
  </li>
  <li>
    <p><em>swDimetricView</em></p>
  </li>
  <li>
    <p><em>swFrontView</em></p>
  </li>
  <li>
    <p><em>swIsometricView</em></p>
  </li>
  <li>
    <p><em>swLeftView</em></p>
  </li>
  <li>
    <p><em>swRightView</em></p>
  </li>
  <li>
    <p><em>swTopView</em></p>
  </li>
  <li>
    <p><em>swTrimetricView</em></p>
  </li>
</ul>

<p>In our code, we did not use <strong>VName</strong> instead I used <em>empty string</em> in form of <strong><em>‚Äù‚Äú</em></strong> symbol.</p>

<p>I used <strong>ViewId</strong> value to specify view and used <code class="language-plaintext highlighter-rouge">swStandardViews_e.swFrontView</code> value to use <em>Standard Front View</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Zoom to fit screen in Solidworks Window</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ViewZoomtofit</span>
</code></pre></div></div>

<p>In this last line we use <em>zoom to fit</em> command.</p>

<p>For Zoom to fit, we use <code class="language-plaintext highlighter-rouge">ViewZoomtofit</code> method from our Solidworks document variable <code class="language-plaintext highlighter-rouge">swDoc</code>.</p>

<p>This is it !!!</p>

<p>If you found anything to add or update, please let me know on my e-mail.</p>

<hr />

<h2 id="vba-language-feature-used-in-this-post">VBA Language feature used in this post</h2>

<p>In this post used some features of <strong>VBA programming language</strong>.</p>

<p>This section of post, has some brief information about the VBA programming language specific features.</p>

<ol>
  <li>
    <p>We use <strong>Option Explicit</strong> for capturing un-declared variables. If you want to read more about <strong>Option Explicit</strong> then please visit <strong><a href="/vba/declaring-and-scoping-of-variables">Declaring and Scoping of Variables</a></strong>.</p>
  </li>
  <li>
    <p>Then we create <strong>variable</strong> for different data types. If you don‚Äôt know about them, then please visit <strong><a href="/vba/variables">Variables</a></strong> and <strong><a href="/vba/programming-concepts/#data-types-in-vba">Data-types</a></strong> posts of this blog. These posts will help you to understand what <strong>Variables</strong> are and how to use them.</p>
  </li>
  <li>
    <p>Then we create <strong>main Sub procedure</strong> for our macro. If you don‚Äôt know about the <strong>Sub procedure</strong>, then I suggest you to visit <strong><a href="/vba/sub-and-function-procedure">VBA Sub and Function Procedures</a></strong> and <strong><a href="/vba/executing-procedures">Executing Sub and Function Procedures</a></strong> posts of this blog. These posts will help you to understand what <strong>Procedures</strong> are and how to use them.</p>
  </li>
  <li>
    <p>In most part we create some variables and set their values. We set those values by using some <strong>functions</strong> provided from objects. If you don‚Äôt know about the <strong>functions</strong>, then you should visit <strong><a href="/vba/functions">VBA Functions</a></strong> and <strong><a href="/vba/more-functions">VBA Functions that do more</a></strong> posts of this blog. These posts will help you to understand what <strong>functions</strong> are and how to use them.</p>
  </li>
</ol>

<hr />

<h2 id="solidworks-api-objects">Solidworks API Objects</h2>

<p>In this post, for creating a <strong>Fillet</strong>, we use <em>Solidworks API objects and their methods</em>.</p>

<p>This section contains the list of all <strong>Solidworks Objects</strong> used in this post.</p>

<p>I have also attached links of these <strong>Solidworks API Objects</strong> in <strong>API Help website</strong>.</p>

<p>If you want to explore those objects, you can use these links.</p>

<p>These Solidworks API Objects are listed below:</p>

<ul>
  <li><strong>Solidworks Application Object</strong></li>
</ul>

<p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Application Object</strong> object you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html">this link</a></strong>.</p>

<ul>
  <li><strong>Solidworks Document Object</strong></li>
</ul>

<p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Document Object</strong> object you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html">this link</a></strong>.</p>

<ul>
  <li><strong>Solidworks Sketch Manager Object</strong></li>
</ul>

<p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Sketch Manager Object</strong> you can visit <strong><a href="http://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this link</a></strong>.</p>

<ul>
  <li><strong>Solidworks Sketch Segment Object</strong></li>
</ul>

<p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Sketch Segment Object</strong> you can visit <strong><a href="http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html">this link</a></strong>.</p>

<hr />

<p>Hope this post helps you to <em>create a Chamfer</em> in Sketches with Solidworks VB Macros.</p>

<p>For more such tutorials on <strong>Solidworks VBA Macros</strong>, do come to this blog after sometime.</p>

<p>Till then, Happy learning!!!</p>
:ET