I"Ð3<p>In this post, we see how to open following documents with <em>Solidworks VBA macro</em>:</p>

<ol>
  <li>
    <p><em>Solidworks Assembly document</em></p>
  </li>
  <li>
    <p><em>Solidworks Drawing document</em></p>

    <ul>
      <li>
        <p><strong>Without</strong> Pre-defined Sheet size</p>
      </li>
      <li>
        <p><strong>With</strong> Pre-defined Sheet size</p>
      </li>
      <li>
        <p><em>With Custom Sheet size</em></p>
      </li>
    </ul>
  </li>
</ol>

<h2 id="solidworks-assembly-document">Solidworks Assembly Document</h2>

<p>The code for opening <em>default Assembly document</em> is identical to the <em>default Part template</em> with only one change.</p>

<p>First, let us see the code to open default Assembly document.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

    <span class="c1">' Setting Solidworks variable to Solidworks application</span>
    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
    
    <span class="c1">' Creating string type variable for storing default Assembly location</span>
    <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
    <span class="c1">' Setting value of this string type variable to "Default Assembly template"</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplateAssembly</span><span class="p">)</span>

    <span class="c1">' Setting Solidworks document to new Assembly document</span>
    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>As you can see in the above code and the code is given in the <a href="/solidworks-macros/open-new-document">previous post</a> is almost identically.</p>

<p>In case you have not read my previous post (<a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a>), I recommend you to read that post first.</p>

<p>I have already explained each and every line in this code there. So I will not explain them in this post.</p>

<p>To open default assembly template, you just need to change <code class="language-plaintext highlighter-rouge">defaultTemplate</code> variable and use <code class="language-plaintext highlighter-rouge">swDefaultTemplateAssembly</code> in place of <code class="language-plaintext highlighter-rouge">swDefaultTemplatePart</code>.</p>

<p>With this you can open a new assembly document.</p>

<hr />

<h2 id="solidworks-drawing-document-without-defining-paper-size">Solidworks Drawing Document without Defining Paper size</h2>

<p>To open new <em>Default drawing document</em> we use same code as used above but with slight modification.</p>

<p>If we make similar change as we have done for <em>Assembly document</em> then we open <em>Default drawing document</em> <strong>without</strong> specifying sheet size.</p>

<p>The code sample shows how to do it.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

    <span class="c1">' Setting Solidworks variable to Solidworks application</span>
    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
    
    <span class="c1">' Creating string type variable for storing default drawing location</span>
    <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
    <span class="c1">' Setting value of this string type variable to "Default drawing template" without define paper size</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplateDrawing</span><span class="p">)</span>

    <span class="c1">' Setting Solidworks document to new drawing document</span>
    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<hr />

<h3 id="solidworks-drawing-document-with-default-paper-size">Solidworks Drawing Document with Default Paper size</h3>

<p>To open a <em>new Drawing</em> with <strong>pre-define</strong> sheet size we use following code sample:</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

    <span class="c1">' Setting Solidworks variable to Solidworks application</span>
    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
    
    <span class="c1">' Creating string type variable for storing default drawing location</span>
    <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
    <span class="c1">' Setting value of this string type variable to "Default drawing template" with pre-define paper size</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplateDrawing</span><span class="p">)</span>

    <span class="c1">' Setting Solidworks document to new drawing document</span>
    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="n">swDwgPaperSizes_e</span><span class="p">.</span><span class="n">swDwgPaperA4sizeVertical</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>This code is <em>similar</em> to what we have used in the <em>previous section</em> but has a <em>one modification</em>.</p>

<p>That is while setting the document (at <code class="language-plaintext highlighter-rouge">Set Doc</code>) we <em>define Paper size or Sheet size</em>.</p>

<p>I used A4 Sheet with vertical orientation by using <code class="language-plaintext highlighter-rouge">swDwgPaperSizes_e.swDwgPaperA4sizeVertical</code> enumarator.</p>

<p>You can use other values from <a href="http://help.solidworks.com/2013/English/api/swconst/SolidWorks.Interop.swconst~SolidWorks.Interop.swconst.swDwgPaperSizes_e.html">this list</a>.</p>

<hr />

<h3 id="solidworks-drawing-document-with-custom-paper-size">Solidworks Drawing Document with Custom Paper size</h3>

<p>To open a new Drawing with <em>Custom sheet size</em> we use following code sample:</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

    <span class="c1">' Setting Solidworks variable to Solidworks application</span>
    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
    
    <span class="c1">' Creating string type variable for storing default drawing location</span>
    <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
    <span class="c1">' Setting value of this string type variable to "Default drawing template" with custom paper size</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplateDrawing</span><span class="p">)</span>

    <span class="c1">' Setting Solidworks document to new drawing document</span>
    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="n">swDwgPaperSizes_e</span><span class="p">.</span><span class="n">swDwgPapersUserDefined</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">3</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>For <em>custom paper size</em>, we need to use <code class="language-plaintext highlighter-rouge">swDwgPaperSizes_e.swDwgPapersUserDefined</code> value of paper size.</p>

<p>Since we are using custom value, we need to define <strong>paper width</strong> and <strong>paper height</strong> also.</p>

<blockquote>
  <p>It important to remember that API use <strong>Metric system</strong> only. So you need to use the converted value in defining paper width and paper height.</p>
</blockquote>

<p>This is all for now. In the next post I will tell you how select a plane in a part document and if possible how to create a skecth segment.</p>

:ET