<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="generator" content="Docusaurus v2.0.0-alpha.66">
<link rel="preconnect" href="https://www.google-analytics.com">
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-117501871-2","auto"),ga("set","anonymizeIp",!0),ga("send","pageview")</script>
<script async src="https://www.google-analytics.com/analytics.js"></script><title data-react-helmet="true">Create a Centerpoint Arc Slot | The Cad Coder</title><meta data-react-helmet="true" name="twitter:card" content="summary_large_image"><meta data-react-helmet="true" name="docusaurus_language" content="en"><meta data-react-helmet="true" name="docusaurus_version" content="current"><meta data-react-helmet="true" name="docusaurus_tag" content="docs-default-current"><meta data-react-helmet="true" property="og:title" content="Create a Centerpoint Arc Slot | The Cad Coder"><meta data-react-helmet="true" name="description" content="In this post, I tell you about how to create a Centerpoint Arc Slot through Solidworks VBA Macros in a sketch."><meta data-react-helmet="true" property="og:description" content="In this post, I tell you about how to create a Centerpoint Arc Slot through Solidworks VBA Macros in a sketch."><meta data-react-helmet="true" property="og:url" content="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc-slot"><link data-react-helmet="true" rel="shortcut icon" href="/img/logo.png"><link data-react-helmet="true" rel="canonical" href="https://prashantbaher.github.io//docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc-slot"><link rel="stylesheet" href="/styles.f7ef45b3.css">
<link rel="preload" href="/styles.e684f388.js" as="script">
<link rel="preload" href="/runtime~main.9d8e6dec.js" as="script">
<link rel="preload" href="/main.d90b1f90.js" as="script">
<link rel="preload" href="/1.1af7f77d.js" as="script">
<link rel="preload" href="/2.4f0019c3.js" as="script">
<link rel="preload" href="/94.4b40930d.js" as="script">
<link rel="preload" href="/95.2f44d2c3.js" as="script">
<link rel="preload" href="/f976f453.e3619938.js" as="script">
<link rel="preload" href="/17896441.361bff39.js" as="script">
<link rel="preload" href="/e6fafb66.392b095e.js" as="script">
</head>
<body>
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><div aria-label="Navigation bar toggle" class="navbar__toggle" role="button" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></div><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a><div class="navbar__item dropdown dropdown--hoverable dropdown--left"><a class="navbar__item navbar__link">VBA</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li><a class="dropdown__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></div><a class="navbar__item navbar__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a><a class="navbar__item navbar__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></div><div class="navbar__items navbar__items--right"><div class="navbar__item dropdown dropdown--hoverable dropdown--right"><a class="navbar__item navbar__link">About</a><ul class="dropdown__menu"><li><a class="dropdown__link" position="right" href="/docs/about">About Me</a></li><li><a class="dropdown__link" position="right" href="/docs/resources">Resources</a></li><li><a class="dropdown__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></div><div class="react-toggle react-toggle--disabled displayOnlyInLargeViewport_2aTZ"><div class="react-toggle-track"><div class="react-toggle-track-check"><span class="toggle_BsTx">ðŸŒœ</span></div><div class="react-toggle-track-x"><span class="toggle_BsTx">ðŸŒž</span></div></div><div class="react-toggle-thumb"></div><input type="checkbox" disabled="" aria-label="Dark mode toggle" class="react-toggle-screenreader-only"></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div><div class="navbar-sidebar"><div class="navbar-sidebar__brand"><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a></div><div class="navbar-sidebar__items"><div class="menu"><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">VBA</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></li><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">About</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/about">About Me</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/resources">Resources</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></li></ul></div></div></div></nav><div class="main-wrapper"><div class="docPage_2gpo"><div class="docSidebarContainer_3_JD" role="complementary"><div class="sidebar_2urC"><div class="menu menu--responsive menu_5FrY"><button aria-label="Open Menu" aria-haspopup="true" class="button button--secondary button--sm menu__button" type="button"><svg aria-label="Menu" class="sidebarMenuIcon_Dm3K" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 32 32" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">General Functions</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/vba-in-sw">VBA in Solidworks</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-part">Open new Part document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-asm-and-dwg">Open Assembly and Drawing document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-selection-methods">Selection Methods</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-macro-open-saved-documents">Open Saved Documents</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue">Fix Unit Issue</a></li></ul></li><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!">Sketch</a><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Lines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-line">Create Line</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerline">Create CenterLine</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Rectangles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-corner-rec">Create Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-center-rec">Create Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-corner-rec">Create 3-Point Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-center-rec">Create 3-Point Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-parallelogram">Create A Parallelogram</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Circles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle">Create Circle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle-by-radius">Create Circle By Radius</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-perimeter-circle">Create Perimeter Circle</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Arcs</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc">Create Centerpoint Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-tangent-arc">Create Tangent Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc">Create 3-Point Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-polygon">Create Polygon</a></li></ul></li><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!" tabindex="0">Slots</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-create-straight-slot">Create a Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-straight-slot">Create a Centerpoint Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc-slot">Create a 3-Point Arc Slot</a></li><li class="menu__list-item"><a aria-current="page" class="menu__link menu__link--active active" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc-slot">Create a Centerpoint Arc Slot</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Splines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-point">Create a Point</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-spline">Create a Spline</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Fillet &amp; Chamfer</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-fillet">Create a Fillet</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-chamfer">Create a Chamfer</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Trim and Extend</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-trim-entities">Trim Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-extend-entities">Extend Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Offset and Mirror</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-offset-entities">Offset Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-mirror-sketch-entities">Mirror Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Patterns</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-linear-sketch-patterm">Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm">Edit Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm">Circular Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern">Edit Circular Sketch Pattern</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Transformation</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities">Move/Copy Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities">Rotate/Copy Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Relations</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-toggle-sketch-relation">Toggle (Hide/Show) Sketch Relations</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-sketch-relation">Add Sketch Relations (Constraints)</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Others</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-convert-to-construction-sketch">Convert to Construction Sketch</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-split-sketch-entities">Split Open/Closed Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="0">Sketch Dimensioning</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-dimension-sketch-entities">Add dimension to Sketch Entities</a></li></ul></li></ul></li></ul></div></div></div><main class="docMainContainer_3EyW"><div class="container padding-vert--lg docItemWrapper_1EkI"><div class="row"><div class="col docItemCol_2ASc"><div class="docItemContainer_3QWW"><article><header><h1 class="docTitle_1Lrw">Create a Centerpoint Arc Slot</h1></header><div class="markdown"><p>In this post, I tell you about <em>how to create a Centerpoint Arc Slot through Solidworks VBA Macros</em> in a sketch.</p><p>The process is almost identical with previous <strong><a href="/docs/solidworks-macros/sw-sketch-macro-create-straight-slot">Sketch - Create Straight Slot</a></strong> post. </p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="demo-video-of-code-on-youtube"></a>Demo Video of Code on YouTube<a aria-hidden="true" tabindex="-1" class="hash-link" href="#demo-video-of-code-on-youtube" title="Direct link to heading">#</a></h2><p>I have not created the video for this post now. </p><p>I will upload the video soon for this post and update the post after that.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="for-experience-macro-developer"></a>For Experience Macro Developer<a aria-hidden="true" tabindex="-1" class="hash-link" href="#for-experience-macro-developer" title="Direct link to heading">#</a></h2><p>If you are an experience <strong>Solidworks Macro developer</strong>, then you are looking for a specific code sample.</p><p>Below is the code for creating <strong>A Centerpoint Arc Slot</strong> from <strong>Solidworks VBA Macro</strong>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating Variable for Solidworks Slot</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim mySketchSlot As SketchSlot</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting the value of a Centerpoint Arc slot</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set mySketchSlot = swSketchManager.CreateSketchSlot(swSketchSlotCreationType_e.swSketchSlotCreationType_arc, swSketchSlotLengthType_e.swSketchSlotLengthType_CenterCenter, 0.5, 0, 0, 0, -1, 0, 0, 1, 0, 0, -1, False)</span></div></div></div></div></div><p>First you need to <strong>Create</strong> a variable of <code>SketchSlot</code> type.</p><p>After creating variable, you need to set the value of this variable.</p><p>For this you used <code>CreateSketchSlot</code> method from <strong>Solidworks Sketch Manager</strong>.</p><p>This <code>CreateSketchSlot</code> method set the value of <code>SketchSlot</code> type variable.</p><p>The <code>CreateSketchSlot</code> method takes following parameters:</p><ul><li><p><em>SlotCreationType</em> : <em>Type of sketch slot</em>.</p></li><li><p><em>SlotLengthType</em> : <em>Type of length of sketch slot</em>.</p></li><li><p><em>Width</em> : Width of Slot</p></li><li><p><em>X1</em> : X coordinate of the point 1, of the Slot</p></li><li><p><em>Y1</em> : Y coordinate of the point 1, of the Slot</p></li><li><p><em>Z1</em> : Z coordinate of the point 1, of the Slot</p></li><li><p><em>X2</em> : X coordinate of the point 2, of the Slot</p></li><li><p><em>Y2</em> : Y coordinate of the point 2, of the Slot</p></li><li><p><em>Z2</em> : Z coordinate of the point 2, of the Slot</p></li><li><p><em>X3</em> : X coordinate of the point 3, of the Slot</p></li><li><p><em>Y3</em> : Y coordinate of the point 3, of the Slot</p></li><li><p><em>Z3</em> : Z coordinate of the point 3, of the Slot</p></li><li><p><em>CenterArcDirection</em> : We need to set the direction eiter Clockwise or Anti-Clockwise/Counterclockwise </p></li><li><p><em>AddDimension</em> : <code>True</code> to automatically add dimensions, <code>False</code> to not.</p></li></ul><p>If you want a more detail explaination then please read further otherwise this will help you to <strong>Create a Centerpoint Arc Slot From VBA Macro</strong>.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="for-beginners-macro-developers"></a>For Beginners Macro Developers<a aria-hidden="true" tabindex="-1" class="hash-link" href="#for-beginners-macro-developers" title="Direct link to heading">#</a></h2><p>In this post, I tell you about <code>CreateSketchSlot</code> method from <strong>Solidworks</strong> <code>SketchManager</code> object.</p><p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>. </p><p>So <strong><em>use this method</em></strong> if you want to create a new <strong>Centerpoint Arc Slot</strong>.</p><p>Below is the <code>code</code> sample for creating <em>a Centerpoint Arc Slot</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Creating string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Setting Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set swSketchManager = swDoc.SketchManager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Inserting a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swSketchManager.InsertSketch True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Creating Variable for Solidworks Slot</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Dim mySketchSlot As SketchSlot</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Creating a Centerpoint Arc slot</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  Set mySketchSlot = swSketchManager.CreateSketchSlot(swSketchSlotCreationType_e.swSketchSlotCreationType_arc, swSketchSlotLengthType_e.swSketchSlotLengthType_CenterCenter, 0.5, 0, 0, 0, -1, 0, 0, 1, 0, 0, -1, False)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; De-select the Slot after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ClearSelection2 True</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  &#x27; Zoom to fit screen in Solidworks Window</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">  swDoc.ViewZoomtofit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="understanding-the-code"></a>Understanding the Code<a aria-hidden="true" tabindex="-1" class="hash-link" href="#understanding-the-code" title="Direct link to heading">#</a></h3><p>Now let us walk through <em>each line</em> in the above code, and <strong>understand</strong> the meaning of every line.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div></div></div></div></div><p>This line forces us to define every variable we are going to use. </p><p>For more information please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div></div></div></div></div><p>In this line, we are creating a variable which we named as <code>swApp</code> and the type of this <code>swApp</code> variable is <code>SldWorks.SldWorks</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div></div></div></div></div><p>In this line, we are creating a variable which we named as <code>swDoc</code> and the type of this <code>swDoc</code> variable is <code>SldWorks.ModelDoc2</code>.</p><p>Next is our <code>Sub</code> procedure named as <code>main</code>. This procedure hold all the <em>statements (instructions)</em> we give to computer.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swApp = Application.SldWorks</span></div></div></div></div></div><p>In this line, we are setting the value of our Solidworks variable <code>swApp</code> which we defined earlier to Solidworks application.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div></div></div></div></div><p>In 1st statement of above example, we are defining a variable of <code>string</code> type and named it as <code>defaultTemplate</code>.</p><p>This variable <code>defaultTemplate</code>, holds the location the location of <strong>Default Part Template</strong>.</p><p>In 2nd line of above example. we assign value to our newly define <code>defaultTemplate</code> variable.</p><p>We assign the value by using a <em>Method</em> named <code>GetUserPreferenceStringValue()</code>. </p><p>This method is a part of our main Solidworks variable <code>swApp</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div></div></div></div></div><p>In this line, we set the value of our <code>swDoc</code> variable to new document.</p><p>For <strong>more detailed information</strong> about above lines please visit <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post. </p><p>I have discussed them <strong>thoroghly</strong> in <strong><a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a></strong> post, so do checkout this post if you don&#x27;t understand above code.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div></div></div></div></div><p>In 1st line, we create a variable named <code>BoolStatus</code> as <code>Boolean</code> object.</p><p>In next line, we select the <em>front plane</em> by using <code>SelectByID2</code> method from <code>Extension</code> object.</p><p>For more information about selection method please visit <strong>[Solidworks Macros - Selection Methods](sw-macro-selection-methods</strong>) post.</p><p>I have discussed about different <em>Selection methods</em> in details in <strong><a href="/docs/solidworks-macros/sw-macro-selection-methods">Soldworks Macros - Selection Methods</a></strong> post, so do visit this post for more <em>Selection methods</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks Sketch Manager</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swSketchManager As SldWorks.SketchManager</span></div></div></div></div></div><p>In above line, we create variable <code>swSketchManager</code> for <strong>Solidworks Sketch Manager</strong>.</p><p>As the name suggested, a <strong>Sketch Manager</strong> holds variours methods and properties to manage <em>Sketches</em>.</p><p>To see methods and properties related to SketchManager object, please visit <strong><a href="/docs/solidworks-macros/help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this page</a></strong>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Setting Sketch manager for our sketch</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swSketchManager = swDoc.SketchManager</span></div></div></div></div></div><p>In above line, we set the <strong>Sketch manager</strong> variable to current document&#x27;s sketch manager.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Inserting a sketch into selected plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swSketchManager.InsertSketch True</span></div></div></div></div></div><p>In above line, we use <code>InsertSketch</code> method of <em>SketchManager</em> and give <code>True</code> value.</p><p>This method allows us to insert a sketch in selected plane.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating Variable for Solidworks Slot</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim mySketchSlot As SketchSlot</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">      </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating a Centerpoint Arc slot</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set mySketchSlot = swSketchManager.CreateSketchSlot(swSketchSlotCreationType_e.swSketchSlotCreationType_arc, swSketchSlotLengthType_e.swSketchSlotLengthType_CenterCenter, 0.5, 0, 0, 0, -1, 0, 0, 1, 0, 0, -1, False</span></div></div></div></div></div><p>In above sample code, we 1st create a variable named <code>mySketchSlot</code> of type <code>SketchSlot</code>.</p><p>In 2nd line, we <strong>set</strong> the value of <em>SketchSlot</em> variable <code>mySketchSlot</code>.</p><p>We get this value from <code>CreateSketchSlot</code> method which is inside the <code>swSketchManager</code> variable.</p><p><code>swSketchManager</code> variable is a type of <strong>SketchManager</strong>, hence we used <code>CreateSketchSlot</code> method from <strong>SketchManager</strong>.</p><p>This <code>CreateSketchSlot</code> method takes following parameters as explained:</p><p><em>SlotCreationType</em> : <em>Type of sketch slot</em> as defined in <code>swSketchSlotCreationType_e</code>.</p><p>  There are 4 Different types of Slots we can create.</p><ul><li><p><strong><em>Straight Slot</em></strong> : <code>swSketchSlotCreationType_e.swSketchSlotCreationType_line</code> or <strong>0</strong></p></li><li><p><strong><em>Centerpoint straight Slot</em></strong> : <code>swSketchSlotCreationType_e.swSketchSlotCreationType_center_line</code> or <strong>1</strong></p></li><li><p><strong><em>Centerpoint arc Slot</em></strong> : <code>swSketchSlotCreationType_e.swSketchSlotCreationType_arc</code> or <strong>2</strong></p></li><li><p><strong><em>3-point arc Slot</em></strong> : <code>swSketchSlotCreationType_e.swSketchSlotCreationType_3pointarc</code> or <strong>4</strong></p></li></ul><p><em>SlotLengthType</em> : <em>Type of length of sketch slot</em> as defined in <code>swSketchSlotLengthType_e</code>.</p><p>  There are 2 different types of Sketch slot length we can create.</p><ul><li><p><strong><em>Center to Center</em></strong> : <code>swSketchSlotLengthType_e.swSketchSlotLengthType_CenterCenter</code> or <strong>0</strong></p></li><li><p><strong><em>Full Length</em></strong> : <code>swSketchSlotLengthType_e.swSketchSlotLengthType_FullLength</code> or <strong>1</strong></p></li></ul><p><em>Width</em> : Width of Slot</p><p><em>X1</em> : X coordinate of the point 1, of the Slot</p><p><em>Y1</em> : Y coordinate of the point 1, of the Slot</p><p><em>Z1</em> : Z coordinate of the point 1, of the Slot</p><p><em>X2</em> : X coordinate of the point 2, of the Slot</p><p><em>Y2</em> : Y coordinate of the point 2, of the Slot</p><p><em>Z2</em> : Z coordinate of the point 2, of the Slot</p><p><em>X3</em> : X coordinate of the point 3, of the Slot</p><p><em>Y3</em> : Y coordinate of the point 3, of the Slot</p><p><em>Z3</em> : Z coordinate of the point 3, of the Slot</p><p><em>CenterArcDirection</em> : We need to set the direction eiter Clockwise or Anti-Clockwise/Counterclockwise as follows:</p><ul><li><p><strong><em>Clockwise (CW)</em></strong> : -1</p></li><li><p><strong><em>Anti-Clockwise/Counterclockwise (CCW)</em></strong> : 1</p></li></ul><p><em>AddDimension</em> : <code>True</code> to automatically add dimensions, <code>False</code> to not.</p><p>For <strong>more details</strong> about <em>Slot Parameter</em> you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/solidworks.interop.sldworks~solidworks.interop.sldworks.isketchmanager~createsketchslot.html" target="_blank" rel="noopener noreferrer">this page</a></strong>.</p><p>For creating a <em>Centerpoint Arc Slot</em>, I used following parameter Values:</p><ul><li><p><em>SlotCreationType</em> : <code>swSketchSlotCreationType_e.swSketchSlotCreationType_arc</code></p><p>Since we want to create a <em>Centerpoint Arc Slot</em> hence I select above value.</p></li><li><p><em>SlotLengthType</em> : <code>swSketchSlotLengthType_e.swSketchSlotLengthType_CenterCenter</code></p><p>I want length of this Slot from <em>Center to Center</em> hence I select above value.</p></li><li><p><em>Width</em> : <strong>0.5</strong></p></li><li><p><em>X1, Y1, Z1</em> : <code>0, 0, 0</code></p><p>For Point 1, I use (0, 0, 0) values, which is <em>origin</em> of Sketch.</p></li><li><p><em>X2, Y2, Z2</em> : <code>-1, 0, 0</code></p><p>For Point 2, I use (-1, 0, 0) values, which is which is -1 point distance in X-direction.</p></li><li><p><em>X3, Y3, Z3</em> : <code>1, 0, 0</code></p><p>For Point 2, I use (1, 0, 0) values, which is which is 1 point distance in X-direction.</p></li><li><p><em>CenterArcDirection</em> : <strong>-1</strong></p><p>I want to create Clockwise Slot.</p></li><li><p><em>AddDimension</em> : <code>False</code></p></li></ul><p>Below Image described <strong>the Parameters for Centerpoint Arc Slot</strong> in more detail.</p><p><img alt="centerpoint-arc-slot-parameters" src="/assets/images/centerpoint-arc-slot-parameters-a9ea02a21e1dc4b34c24f9037e1dc30e.png"></p><p>This <code>CreateSketchSlot</code> method returns <em>Sketch Slot</em> interface i.e. <code>ISketchSlot</code> interface. </p><p>This <code>ISketchSlot</code> interface has various <strong>methods and properties</strong> for <em>a Slot</em>.</p><p>For more detail about <strong>methods and properties</strong> of <code>ISketchSlot</code> interface you can visit <a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSlot_members.html" target="_blank" rel="noopener noreferrer">this page</a></p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="note"></a>NOTE<a aria-hidden="true" tabindex="-1" class="hash-link" href="#note" title="Direct link to heading">#</a></h3><p>It is <strong><em>very important</em></strong> to remember that, when you give distance or any other numeric value in <strong>Solidworks API</strong>, Solidworks takes that numeric value in <strong><em>Meter only</em></strong>.</p><p><em>Solidworks API</em> does not care about your application&#x27;s Unit systems.</p><p>For example, I works in ANSI system means &quot;inches&quot; for distance. </p><p>But when I used Solidworks API through <em>VBA macros</em> or <em>C#</em>, I have to use <strong>converted</strong> numeric values.</p><p>Because Solidworks API output the distance in <strong>Meter</strong> only; which is not my requirement.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; De-select the Slot after creation</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ClearSelection2 True</span></div></div></div></div></div><p>In the this line of code, we de-select the created Centerpointrc Slot.</p><p>For de-selecting, we use <code>ClearSelection2</code> method from our Solidworks document variable <code>swDoc</code>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Zoom to fit screen in Solidworks Window</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">swDoc.ViewZoomtofit</span></div></div></div></div></div><p>In this last line we use <em>zoom to fit</em> command.</p><p>For Zoom to fit, we use <code>ViewZoomtofit</code> method from our Solidworks document variable <code>swDoc</code>. </p><p>After this our Solidworks VBA Macro ends the <strong>Sub procedure</strong> and we create <strong>a Centerpoint Arc Slot</strong>.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="vba-language-feature-used-in-this-post"></a>VBA Language feature used in this post<a aria-hidden="true" tabindex="-1" class="hash-link" href="#vba-language-feature-used-in-this-post" title="Direct link to heading">#</a></h2><p>In this post used some features of <strong>VBA programming language</strong>.</p><p>This section of post, has some brief information about the VBA programming language specific features.</p><ol><li>We use <strong>Option Explicit</strong> for capturing un-declared variables.</li></ol><p>If you want to read more about <strong>Option Explicit</strong> then please visit <strong><a href="/docs/vba/vba-variables-decl">Declaring and Scoping of Variables</a></strong>.</p><ol start="2"><li>Then we create <strong>variable</strong> for different data types.</li></ol><p>If you don&#x27;t know about them, then please visit <strong><a href="/docs/vba/vba-variables">Variables</a></strong> and <strong><a href="/docs/vba/vba-prog-concept#data-types-in-vba">Data-types</a></strong> posts of this blog.</p><p>These posts will help you to understand what <strong>Variables</strong> are and how to use them.</p><ol start="3"><li>Then we create <strong>main Sub procedure</strong> for our macro.</li></ol><p>If you don&#x27;t know about the <strong>Sub procedure</strong>, then I suggest you to visit <strong><a href="/docs/vba/vba-procedures">VBA Sub and Function Procedures</a></strong> and <strong><a href="/docs/vba/vba-procedures-exec">Executing Sub and Function Procedures</a></strong> posts of this blog.</p><p>These posts will help you to understand what <strong>Procedures</strong> are and how to use them.</p><ol start="4"><li>In most part we create some variables and set their values. We set those values by using some <strong>functions</strong> provided from objects.</li></ol><p>If you don&#x27;t know about the <strong>functions</strong>, then you should visit <strong><a href="/docs/vba/vba-functions">VBA Functions</a></strong> and <strong><a href="/docs/vba/vba-functions-adv">VBA Functions that do more</a></strong> posts of this blog.</p><p>These posts will help you to understand what <strong>functions</strong> are and how to use them.</p><ol start="5"><li>For creating <strong>Centerpoint Arc Slot</strong>, we use <code>CreateSketchSlot</code> function. This function take some input values in form of <strong>VBA Constants</strong>.</li></ol><p>If you don&#x27;t know about the <strong>VBA Constants</strong>, then you should visit <strong><a href="/docs/vba/vba-constants">VBA Constants</a></strong> post of this blog.</p><p>This posts will help you to understand what <strong>VBA Constants</strong> are and how to use them.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="solidworks-api-objects"></a>Solidworks API Objects<a aria-hidden="true" tabindex="-1" class="hash-link" href="#solidworks-api-objects" title="Direct link to heading">#</a></h2><p>In this post, for creating <strong>Centerpoint Arc Slot</strong>, we use <em>Solidworks API objects and their methods</em>.</p><p>This section contains the list of all <strong>Solidworks Objects</strong> used in this post.</p><p>I have also attached links of these <strong>Solidworks API Objects</strong> in <strong>API Help website</strong>.</p><p>If you want to explore those objects, you can use these links.</p><p>These Solidworks API Objects are listed below:</p><ul><li><strong>Solidworks Application Object</strong></li></ul><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Application Object</strong> object you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISldWorks_members.html" target="_blank" rel="noopener noreferrer">this link</a></strong>.</p><ul><li><strong>Solidworks Document Object</strong></li></ul><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of <strong>Solidworks Document Object</strong> object you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2_members.html" target="_blank" rel="noopener noreferrer">this link</a></strong>.</p><ul><li><strong>Solidworks Sketch Manager Object</strong></li></ul><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of this <strong>Solidworks Sketch Manager Object</strong> you can visit <strong><a href="/docs/solidworks-macros/help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this link</a></strong>.</p><ul><li><strong>Solidworks Sketch Slot Object</strong></li></ul><p>If you want explore <strong><em>Properties and Methods/Functions</em></strong> of this <strong>Solidworks Sketch Slot Object</strong> you can visit <strong><a href="http://help.solidworks.com/2019/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSlot_members.html" target="_blank" rel="noopener noreferrer">this link</a></strong>.</p><hr><p>Hope this post helps you to <em>create a Centerpoint Arc Slot</em> in Sketches with <strong>Solidworks VBA Macros</strong>.</p><p>For more such tutorials on <strong>Solidworks VBA Macros</strong>, do come to this blog.</p><p>Till then, Happy learning!!!</p></div></article><div class="margin-vert--lg"><nav class="pagination-nav" aria-label="Blog list page navigation"><div class="pagination-nav__item"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc-slot"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Â« Create a 3-Point Arc Slot</div></a></div><div class="pagination-nav__item pagination-nav__item--next"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-sketch-macro-create-point"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Create a Point Â»</div></a></div></nav></div></div></div><div class="col col--3"><div class="tableOfContents_3SO_"><ul class="table-of-contents table-of-contents__left-border"><li><a href="#demo-video-of-code-on-youtube" class="table-of-contents__link">Demo Video of Code on YouTube</a></li><li><a href="#for-experience-macro-developer" class="table-of-contents__link">For Experience Macro Developer</a></li><li><a href="#for-beginners-macro-developers" class="table-of-contents__link">For Beginners Macro Developers</a><ul><li><a href="#understanding-the-code" class="table-of-contents__link">Understanding the Code</a></li><li><a href="#note" class="table-of-contents__link">NOTE</a></li></ul></li><li><a href="#vba-language-feature-used-in-this-post" class="table-of-contents__link">VBA Language feature used in this post</a></li><li><a href="#solidworks-api-objects" class="table-of-contents__link">Solidworks API Objects</a></li></ul></div></div></div></div></main></div></div><footer class="footer"><div class="container"><div class="row footer__links"><div class="col footer__col"><h4 class="footer__title">Tutorials</h4><ul class="footer__items"><li class="footer__item"><a class="footer__link-item" href="/docs/vba-Intro">VBA Introduction</a></li><li class="footer__item"><a class="footer__link-item" href="/docs/vba-in-sw">VBA in Solidworks</a></li><li class="footer__item">
                <div>
                  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                  
                  <ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-8158659264340002" data-ad-slot="6644001766" data-ad-format="auto" data-full-width-responsive="true"></ins>
                  <script>(adsbygoogle=window.adsbygoogle||[]).push({})</script>
                </div>            
                </li></ul></div><div class="col footer__col"><h4 class="footer__title">Community</h4><ul class="footer__items"><li class="footer__item"><a href="https://www.facebook.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Facebook</a></li><li class="footer__item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" rel="noopener noreferrer" class="footer__link-item">YouTube</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">More</h4><ul class="footer__items"><li class="footer__item"><a href="mailto:thecadcoder@gmail.com" target="_blank" rel="noopener noreferrer" class="footer__link-item">E-Mail</a></li><li class="footer__item"><a href="https://www.buymeacoffee.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Buy Me a Coffee</a></li></ul></div></div><div class="text--center"><div>Copyright Â© 2020 The Cad Coder, Inc. Built with Docusaurus.</div></div></div></footer></div>
<script src="/styles.e684f388.js"></script>
<script src="/runtime~main.9d8e6dec.js"></script>
<script src="/main.d90b1f90.js"></script>
<script src="/1.1af7f77d.js"></script>
<script src="/2.4f0019c3.js"></script>
<script src="/94.4b40930d.js"></script>
<script src="/95.2f44d2c3.js"></script>
<script src="/f976f453.e3619938.js"></script>
<script src="/17896441.361bff39.js"></script>
<script src="/e6fafb66.392b095e.js"></script>
</body>
</html>