(window.webpackJsonp=window.webpackJsonp||[]).push([[50],{107:function(e,t,a){"use strict";a.r(t),a.d(t,"frontMatter",(function(){return i})),a.d(t,"metadata",(function(){return c})),a.d(t,"rightToc",(function(){return p})),a.d(t,"default",(function(){return s}));var n=a(2),r=a(6),b=(a(0),a(152)),i={id:"sw-sketch-macro-edit-linear-sketch-patterm",title:"Edit Linear Sketch Pattern"},c={unversionedId:"solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm",id:"solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm",isDocsHomePage:!1,title:"Edit Linear Sketch Pattern",description:"In this post, I tell you about how to Edit Linear Sketch Pattern using Solidworks VBA Macros in a Sketch.",source:"@site/docs\\solidworks-macros\\2020-01-29-edit-linear-skech-pattern.md",slug:"/solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm",permalink:"/docs/solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm",version:"current",sidebar:"swvba",previous:{title:"Linear Sketch Pattern",permalink:"/docs/solidworks-macros/sw-sketch-macro-linear-sketch-patterm"},next:{title:"Circular Sketch Pattern",permalink:"/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm"}},p=[{value:"Video of Code on YouTube",id:"video-of-code-on-youtube",children:[]},{value:"For Experience Macro Developer",id:"for-experience-macro-developer",children:[]},{value:"For Beginners Macro Developers",id:"for-beginners-macro-developers",children:[{value:"Cases",id:"cases",children:[]},{value:"CASE 1 : Increase Total number of instances along the &quot;X&quot; axis",id:"case-1--increase-total-number-of-instances-along-the-x-axis",children:[]},{value:"CASE 2 : Increase Total number of instances along the &quot;Y&quot; axis",id:"case-2--increase-total-number-of-instances-along-the-y-axis",children:[]},{value:"CASE 3 : Update Angle for direction 1 along the &quot;X&quot; axis",id:"case-3--update-angle-for-direction-1-along-the-x-axis",children:[]},{value:"CASE 4 : Update Angle for direction 1 along the &quot;Y&quot; axis",id:"case-4--update-angle-for-direction-1-along-the-y-axis",children:[]},{value:"CASE 5 : Number of instances to delete",id:"case-5--number-of-instances-to-delete",children:[]},{value:"CASE 6 : Display the spacing between instances dimension along the &quot;Y&quot; axis",id:"case-6--display-the-spacing-between-instances-dimension-along-the-y-axis",children:[]},{value:"CASE 7 : Display the angle dimension between axes",id:"case-7--display-the-angle-dimension-between-axes",children:[]},{value:"CASE 8 : Display the number of instances in the &quot;X&quot; direction",id:"case-8--display-the-number-of-instances-in-the-x-direction",children:[]},{value:"CASE 9 : Display the number of instances in the &quot;Y&quot; direction",id:"case-9--display-the-number-of-instances-in-the-y-direction",children:[]},{value:"CASE 10 : Multiple entities as Seed",id:"case-10--multiple-entities-as-seed",children:[]},{value:"NOTE",id:"note",children:[]}]}],o={rightToc:p};function s(e){var t=e.components,i=Object(r.a)(e,["components"]);return Object(b.b)("wrapper",Object(n.a)({},o,i,{components:t,mdxType:"MDXLayout"}),Object(b.b)("p",null,"In this post, I tell you about ",Object(b.b)("strong",{parentName:"p"},"how to Edit Linear Sketch Pattern using Solidworks VBA Macros")," in a Sketch."),Object(b.b)("p",null,"This post is extension of previous ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"sw-sketch-macro-linear-sketch-patterm"}),"Solidworks Macro - Linear Sketch Pattern From VBA Macro"))," post."),Object(b.b)("p",null,"I recommend you to read ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"sw-sketch-macro-linear-sketch-patterm"}),"Solidworks Macro - Linear Sketch Pattern From VBA Macro"))," post because we are using same code sample."),Object(b.b)("hr",null),Object(b.b)("h2",{id:"video-of-code-on-youtube"},"Video of Code on YouTube"),Object(b.b)("p",null,"Please see below video how we can ",Object(b.b)("em",{parentName:"p"},"Edit Linear Sketch Pattern")," in ",Object(b.b)("strong",{parentName:"p"},"Solidworks VBA macro"),"."),Object(b.b)("div",{class:"youtube-responsive-container"},Object(b.b)("iframe",{src:"https://www.youtube.com/embed/4pLUprIxXHU",frameborder:"0",allowfullscreen:!0})),Object(b.b)("p",null,"Please note that there is ",Object(b.b)("strong",{parentName:"p"},"no explanation")," in the video. "),Object(b.b)("p",null,"Why we write our code this way is ",Object(b.b)("strong",{parentName:"p"},"explained")," in this post."),Object(b.b)("hr",null),Object(b.b)("h2",{id:"for-experience-macro-developer"},"For Experience Macro Developer"),Object(b.b)("p",null,"If you are an experienced ",Object(b.b)("strong",{parentName:"p"},"Solidworks Macro developer"),", then you are looking for a specific code sample."),Object(b.b)("p",null,"Below is the code for ",Object(b.b)("strong",{parentName:"p"},"Edit Linear Sketch Pattern")," from ",Object(b.b)("strong",{parentName:"p"},"Solidworks VBA Macro"),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Boolean Variable\nDim BoolStatus As Boolean\n\n\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 4, 1, 0.75, 0.785, 1.5708, "(3,2)(2,1)", True, True, False, False, True, "Arc1_")\n')),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Method Name"),": ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Description"),": Edit ",Object(b.b)("em",{parentName:"p"},"Linear Sketch Pattern"),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Prerequisites"),": To ",Object(b.b)("em",{parentName:"p"},"edit")," a ",Object(b.b)("strong",{parentName:"p"},"Linear Sketch Pattern")," a Solidworks Sketch entity or entities, first, we need the following things:"),Object(b.b)("ol",null,Object(b.b)("li",{parentName:"ol"},"Existing Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"How it works"),":"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"For ",Object(b.b)("strong",{parentName:"p"},"Edit a Linear Sketch Pattern"),", first, we need to ",Object(b.b)("strong",{parentName:"p"},"create")," a variable of ",Object(b.b)("inlineCode",{parentName:"p"},"Boolean")," type.")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"After creating variable, we need to set the value of this ",Object(b.b)("inlineCode",{parentName:"p"},"Boolean")," variable.")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"For this, we used ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method from ",Object(b.b)("strong",{parentName:"p"},"Solidworks Sketch Manager"),".")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"This ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method set the value of ",Object(b.b)("inlineCode",{parentName:"p"},"Boolean")," type variable.")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"If the editing of ",Object(b.b)("em",{parentName:"p"},"Linear Sketch Pattern")," is ",Object(b.b)("strong",{parentName:"p"},"successful")," then ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method return ",Object(b.b)("strong",{parentName:"p"},"True")," value otherwise ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," returns ",Object(b.b)("strong",{parentName:"p"},"False")," value."))),Object(b.b)("p",null,"This ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method takes the following parameters as explained:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumX"),": ",Object(b.b)("em",{parentName:"p"},"Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis, including the seed i.e. original entity/entities."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumY"),": ",Object(b.b)("em",{parentName:"p"},"Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis, including the seed i.e. original entity/entities."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingX"),": ",Object(b.b)("em",{parentName:"p"},"Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingY"),": ",Object(b.b)("em",{parentName:"p"},"Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleX"),": ",Object(b.b)("em",{parentName:"p"},"Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleY"),": ",Object(b.b)("em",{parentName:"p"},"Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"DeleteInstances"),": ",Object(b.b)("em",{parentName:"p"},'Number of instances to delete, passed as a string in the format: "(a) (b) (c)".'))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"XSpacingDim"),": ",Object(b.b)("em",{parentName:"p"},"True to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis in the graphics area, false to not"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"YSpacingDim"),": ",Object(b.b)("em",{parentName:"p"},"True to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis in the graphics area, false to not"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleDim"),": ",Object(b.b)("em",{parentName:"p"},"True to display the angle dimension between axes in the graphics area, false to not."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInXDir"),": ",Object(b.b)("em",{parentName:"p"},"True to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"x")," direction dimension in the graphics area, false to not."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInYDir"),": ",Object(b.b)("em",{parentName:"p"},"True to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"y")," direction dimension in the graphics area, false to not."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"Seed"),": ",Object(b.b)("em",{parentName:"p"},"List of the names of the entities, separated by the underscore character (_), that comprise the seed pattern (e.g., Line1_Line2_Line3_Line4 for a rectangular-shaped seed pattern).")))),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Return Value"),":"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"True"),": ",Object(b.b)("em",{parentName:"p"},'If Editing of Linear Sketch Pattern is "Success".'))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"False"),": ",Object(b.b)("em",{parentName:"p"},'If Editing of Linear Sketch Pattern is "Fail".')))),Object(b.b)("p",null,"If you want more detailed explaination then please read further otherwise this will help you to ",Object(b.b)("em",{parentName:"p"},"edit")," a ",Object(b.b)("strong",{parentName:"p"},"Linear Sketch Pattern From VBA Macro"),"."),Object(b.b)("hr",null),Object(b.b)("h2",{id:"for-beginners-macro-developers"},"For Beginners Macro Developers"),Object(b.b)("p",null,"In this post, I tell you about ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method from ",Object(b.b)("strong",{parentName:"p"},"Solidworks")," ",Object(b.b)("inlineCode",{parentName:"p"},"SketchManager")," object."),Object(b.b)("p",null,"This method is ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"most updated"))," method, I found in ",Object(b.b)("em",{parentName:"p"},"Solidworks API Help"),". "),Object(b.b)("p",null,"So ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"use this method"))," if you want to ",Object(b.b)("em",{parentName:"p"},"edit Linear Sketch Pattern"),"."),Object(b.b)("p",null,"Below is the ",Object(b.b)("inlineCode",{parentName:"p"},"code")," sample to ",Object(b.b)("em",{parentName:"p"},"edit Linear Sketch Pattern"),"."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Set Sketch Segment value and Create a Circle\n  Set swSketchSegment = swSketchManager.CreateCircleByRadius(0, 0, 0, 0.2)\n  \n  ' De-select the lines after creation\n  swDoc.ClearSelection2 True\n\n  ' Select Circle we want to Pattern\n  BoolStatus = swDoc.Extension.SelectByID2(\"Arc1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 1, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Create a Linear Sketch Pattern\n  BoolStatus = swSketchManager.CreateLinearSketchStepAndRepeat(3, 1, 1, 0, 0, 0, \"\", True, False, True, True, False)\n  \n  ' De-select the Sketch Segment after Linear Sketch Pattern\n  swDoc.ClearSelection2 True\n  \n  ' Show Front View after Linear Sketch Pattern\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n\n  ' Edit a Linear Sketch Pattern <--- FROM HERE IS THE LAST LINE I EXPLAIN\n  BoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 1, 1, 0, 0, 0, \"\", True, False, True, True, False, \"Arc1_\")\n\nEnd Sub\n")),Object(b.b)("p",null,"Since this post is ",Object(b.b)("em",{parentName:"p"},"an extension")," of previous ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"sw-sketch-macro-linear-sketch-patterm"}),"Solidworks Macro - Linear Sketch Pattern From VBA Macro"))," post, then I will start explaining from ",Object(b.b)("strong",{parentName:"p"},"Last line")," only."),Object(b.b)("p",null,"If you want to understand every line of code, then please visit ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"sw-sketch-macro-linear-sketch-patterm"}),"Solidworks Macro - Linear Sketch Pattern From VBA Macro")),' post "first", then read this post.'),Object(b.b)("p",null,"By doing this, ",Object(b.b)("em",{parentName:"p"},"you learn 2 thing"),":"),Object(b.b)("ol",null,Object(b.b)("li",{parentName:"ol"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"How to create a Linear Sketch Pattern"))),Object(b.b)("li",{parentName:"ol"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"How to edit/modify an existing Linear Sketch Pattern")))),Object(b.b)("p",null,"I also give some ",Object(b.b)("em",{parentName:"p"},"links")," so that you can go through them if there are anything I ",Object(b.b)("em",{parentName:"p"},"explained")," in previous posts."),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 1, 1, 0, 0, 0, "", True, False, True, True, False, "Arc1_")\n')),Object(b.b)("p",null,'For "',Object(b.b)("strong",{parentName:"p"},"editing"),'" a Linear Sketch pattern, we need ',Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method from ",Object(b.b)("em",{parentName:"p"},"Solidworks Sketch Manager")," object/variable."),Object(b.b)("p",null,"This ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method takes the following parameters as explained:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumX"),": ",Object(b.b)("em",{parentName:"p"},"Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis, including the seed i.e. original entity/entities."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumY"),": ",Object(b.b)("em",{parentName:"p"},"Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis, including the seed i.e. original entity/entities."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingX"),": ",Object(b.b)("em",{parentName:"p"},"Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingY"),": ",Object(b.b)("em",{parentName:"p"},"Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleX"),": ",Object(b.b)("em",{parentName:"p"},"Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleY"),": ",Object(b.b)("em",{parentName:"p"},"Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"DeleteInstances"),": ",Object(b.b)("em",{parentName:"p"},'Number of instances to delete, passed as a string in the format: "(a) (b) (c)".'))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"XSpacingDim"),": ",Object(b.b)("em",{parentName:"p"},"True to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis in the graphics area, false to not"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"YSpacingDim"),": ",Object(b.b)("em",{parentName:"p"},"True to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis in the graphics area, false to not"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleDim"),": ",Object(b.b)("em",{parentName:"p"},"True to display the angle dimension between axes in the graphics area, false to not."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInXDir"),": ",Object(b.b)("em",{parentName:"p"},"True to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"x")," direction dimension in the graphics area, false to not."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInYDir"),": ",Object(b.b)("em",{parentName:"p"},"True to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"y")," direction dimension in the graphics area, false to not."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"Seed"),": ",Object(b.b)("em",{parentName:"p"},"List of the names of the entities, separated by the underscore character (_), that comprise the seed pattern (e.g., Line1_Line2_Line3_Line4 for a rectangular-shaped seed pattern).")))),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"NOTE:")," In ",Object(b.b)("em",{parentName:"p"},"Seed"),", adding underscore(_) after selected entity is important, otherwise code will note work."),Object(b.b)("p",null,"After the function complete, we get following results:"),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Return Value"),":"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"True"),": ",Object(b.b)("em",{parentName:"p"},'If Editing of Linear Sketch Pattern is "Success".'))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"False"),": ",Object(b.b)("em",{parentName:"p"},'If Editing of Linear Sketch Pattern is "Fail".')))),Object(b.b)("p",null,"In our code, I have used following values:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumX")," : ",Object(b.b)("em",{parentName:"p"},"I have used ",Object(b.b)("strong",{parentName:"em"},"5")," as Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis including original circle."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumY")," : ",Object(b.b)("em",{parentName:"p"},"I have used ",Object(b.b)("strong",{parentName:"em"},"1")," as Total number of instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis which includes original circle only.")),Object(b.b)("div",Object(n.a)({parentName:"li"},{className:"admonition admonition-note alert alert--secondary"}),Object(b.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-heading"}),Object(b.b)("h5",{parentName:"div"},Object(b.b)("span",Object(n.a)({parentName:"h5"},{className:"admonition-icon"}),Object(b.b)("svg",Object(n.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(b.b)("path",Object(n.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(b.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-content"}),Object(b.b)("p",{parentName:"div"},Object(b.b)("em",{parentName:"p"},"Even uf you don't want to pattern in ",Object(b.b)("strong",{parentName:"em"},"Y")," direction, you have to give atleast 1 as a value. Same goes for ",Object(b.b)("strong",{parentName:"em"},"X")," direction."))))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingX")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"1")," as Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingY")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"0")," Spacing between instances along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleX")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"0")," Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"x")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleY")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"0")," Angle for direction 1 relative to the ",Object(b.b)("strong",{parentName:"em"},"y")," axis."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"DeleteInstances")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},'""')," as Number of instances to delete, because I don't want to delete any instances."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"XSpacingDim")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"True")," to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"x")," axis in the graphics area."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"YSpacingDim")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"False")," to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"em"},"y")," axis in the graphics area."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"AngleDim")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"True")," to display the angle dimension between axes in the graphics area."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInXDir")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"True")," to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"x")," direction dimension in the graphics area."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"CreateNumOfInstancesDimInYDir")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"False")," to display the number of instances in the ",Object(b.b)("strong",{parentName:"em"},"y")," direction dimension in the graphics area."))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"Seed")," : ",Object(b.b)("em",{parentName:"p"},"I use ",Object(b.b)("strong",{parentName:"em"},"Arc1_")," as the seed of this Edit Pattern Function. We can select multiple sketch entities into existing Linear Sketch Pattern.")))),Object(b.b)("hr",null),Object(b.b)("h3",{id:"cases"},"Cases"),Object(b.b)("p",null,"In this section, we will go through different cases by "),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"Modifying different parameters")),Object(b.b)("ol",{parentName:"li"},Object(b.b)("li",{parentName:"ol"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"A basic 1 line description"))),Object(b.b)("li",{parentName:"ol"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"Sample Code of parameter modification"))))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("em",{parentName:"p"},"See images, before and after parameter modification")))),Object(b.b)("hr",null),Object(b.b)("h3",{id:"case-1--increase-total-number-of-instances-along-the-x-axis"},'CASE 1 : Increase Total number of instances along the "X" axis'),Object(b.b)("p",null,'To increase Total number of instances along the "X" axis, we need to update ',Object(b.b)("strong",{parentName:"p"},"NumX")," parameter in ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method."),Object(b.b)("p",null,"In my previous ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("a",Object(n.a)({parentName:"strong"},{href:"sw-sketch-macro-linear-sketch-patterm"}),"Solidworks Macro - Linear Sketch Pattern From VBA Macro"))," post, we created a Linear pattern ",Object(b.b)("em",{parentName:"p"},"3 instances")," in ",Object(b.b)("em",{parentName:"p"},"x-direction"),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Code sample:"))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 1, 1, 0, 0, 0, "", True, False, True, True, False, "Arc1_")\n')),Object(b.b)("p",null,"In above code, we update the number of instances from ",Object(b.b)("em",{parentName:"p"},"3 instances")," to ",Object(b.b)("em",{parentName:"p"},"5 instances"),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Example Images:"))),Object(b.b)("p",null,"Below image shows before and after we update ",Object(b.b)("strong",{parentName:"p"},"number of instance in X-direction"),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Before Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"after-linear-pattern",src:a(172).default})),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"After Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-numX",src:a(185).default})),Object(b.b)("hr",null),Object(b.b)("h3",{id:"case-2--increase-total-number-of-instances-along-the-y-axis"},'CASE 2 : Increase Total number of instances along the "Y" axis'),Object(b.b)("p",null,'To increase Total number of instances along the "Y" axis, we need to update ',Object(b.b)("strong",{parentName:"p"},"NumY")," parameter in ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method."),Object(b.b)("p",null,"If we increase the number of instances in ",Object(b.b)("em",{parentName:"p"},"Y-direction"),", then we also need to give value for ",Object(b.b)("strong",{parentName:"p"},"SpacingY")," parameter."),Object(b.b)("p",null,Object(b.b)("em",{parentName:"p"},"We need following parameters to update:")),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumY"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingY")))),Object(b.b)("p",null,Object(b.b)("em",{parentName:"p"},"We will use following values for these parameters:")),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"NumY"),": ",Object(b.b)("em",{parentName:"p"},"4"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"SpacingY"),": ",Object(b.b)("em",{parentName:"p"},"0.75")))),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Code sample:"))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 4, 1, 0.75, 0, 0, "", True, False, True, True, False, "Arc1_")\n')),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Example Images:"))),Object(b.b)("p",null,"Below image shows before and after we update ",Object(b.b)("strong",{parentName:"p"},"number of instance in Y-direction"),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Before Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-numX",src:a(185).default})),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"After Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-numY",src:a(186).default})),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"NOTE:"))),Object(b.b)("p",null,"As you notice in previous image, when you give values for ",Object(b.b)("strong",{parentName:"p"},"NumY")," and ",Object(b.b)("strong",{parentName:"p"},"SpacingY"),", number of instances increased in X-direction!"),Object(b.b)("p",null,Object(b.b)("em",{parentName:"p"},"Why the instances are increased in X-direction not in Y-direction as I was expecting?")),Object(b.b)("p",null,"This question comes in my mind after seeing the result!"),Object(b.b)("p",null,"Reason is that we did not give value of ",Object(b.b)("strong",{parentName:"p"},"AngleY")," parameter."),Object(b.b)("p",null,"If you provide the value of ",Object(b.b)("strong",{parentName:"p"},"AngleY")," parameter then we can have instances in Y-direction."),Object(b.b)("p",null,"More detail with example in ",Object(b.b)("strong",{parentName:"p"},"CASE 4"),"."),Object(b.b)("hr",null),Object(b.b)("h3",{id:"case-3--update-angle-for-direction-1-along-the-x-axis"},'CASE 3 : Update Angle for direction 1 along the "X" axis'),Object(b.b)("p",null,"To update Angle for ",Object(b.b)("em",{parentName:"p"},"direction 1"),' along the "X" axis, we need to update ',Object(b.b)("strong",{parentName:"p"},"AngleX")," parameter in ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method."),Object(b.b)("p",null,Object(b.b)("em",{parentName:"p"},"We will use following value for ",Object(b.b)("strong",{parentName:"em"},"AngleX")," parameter:")),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("strong",{parentName:"li"},"AngleX"),": ",Object(b.b)("em",{parentName:"li"},"0.785"),".")),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Code sample:"))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 4, 1, 0.75, 0.785, 0, "", True, False, True, True, False, "Arc1_")\n')),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Example Images:"))),Object(b.b)("p",null,"Below image shows before and after we update ",Object(b.b)("strong",{parentName:"p"},'Angle for direction 1 along the "X" axis'),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Before Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-numY",src:a(186).default})),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"After Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-angleX",src:a(187).default})),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"NOTE:"))),Object(b.b)("p",null,"In this case, we use ",Object(b.b)("strong",{parentName:"p"},"AngleX")," = ",Object(b.b)("em",{parentName:"p"},"0.785"),"."),Object(b.b)("p",null,"This value is in ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Radian")),"."),Object(b.b)("p",null,"Hence, ",Object(b.b)("em",{parentName:"p"},"0.785")," Radian = ",Object(b.b)("em",{parentName:"p"},"44.999 Degree")),Object(b.b)("p",null,"So we have update Angle for direction 1 in ",Object(b.b)("strong",{parentName:"p"},"~45 degree"),"."),Object(b.b)("hr",null),Object(b.b)("h3",{id:"case-4--update-angle-for-direction-1-along-the-y-axis"},'CASE 4 : Update Angle for direction 1 along the "Y" axis'),Object(b.b)("p",null,"To update Angle for ",Object(b.b)("em",{parentName:"p"},"direction 2"),' along the "Y" axis, we need to update ',Object(b.b)("strong",{parentName:"p"},"AngleY")," parameter in ",Object(b.b)("inlineCode",{parentName:"p"},"EditLinearSketchStepAndRepeat")," method."),Object(b.b)("p",null,Object(b.b)("em",{parentName:"p"},"We will use following value for ",Object(b.b)("strong",{parentName:"em"},"AngleY")," parameter:")),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("strong",{parentName:"li"},"AngleX"),": ",Object(b.b)("em",{parentName:"li"},"1.5708"),".")),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Code sample:"))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 4, 1, 0.75, 0.785, 1.5708, "", True, False, True, True, False, "Arc1_")\n')),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Example Images:"))),Object(b.b)("p",null,"Below image shows before and after we update ",Object(b.b)("strong",{parentName:"p"},'Angle for direction 2 along the "Y" axis'),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Before Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-angleX",src:a(187).default})),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"After Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-angleX",src:a(258).default})),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"NOTE:"))),Object(b.b)("p",null,"In this case, we use ",Object(b.b)("strong",{parentName:"p"},"AngleY")," = ",Object(b.b)("em",{parentName:"p"},"1.5708"),"."),Object(b.b)("p",null,"This value is in ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Radian")),"."),Object(b.b)("p",null,"Hence, ",Object(b.b)("em",{parentName:"p"},"1.5708")," Radian = ",Object(b.b)("em",{parentName:"p"},"90 Degree")),Object(b.b)("p",null,"So we have update Angle for direction 1 in ",Object(b.b)("strong",{parentName:"p"},"90 degree"),"."),Object(b.b)("hr",null),Object(b.b)("h3",{id:"case-5--number-of-instances-to-delete"},"CASE 5 : Number of instances to delete"),Object(b.b)("p",null,'Ok, this one is a little "',Object(b.b)("strong",{parentName:"p"},"tricky"),'"!!! '),Object(b.b)("p",null,"We want to delete some instance now."),Object(b.b)("p",null,"For deleting instances, we need following:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"Deleting instance's position with respect to ",Object(b.b)("strong",{parentName:"p"},"X and Y directions"),".")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"Those position in a particular format."))),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Grid Position Image:"))),Object(b.b)("p",null,"I tried my best to describe you this position system in Grid format using image."),Object(b.b)("p",null,"Please see below image for this Grid position."),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-deleteInstances",src:a(259).default})),Object(b.b)("p",null,"We are going to delete 2 instances."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"1st Instance"),": First we will get the position of this instance."),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"In X-Direction"),": As you can see in above image, position of this instance is 3 in Grid position system for X-Direction.")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"In Y-Direction"),": As you can see in above image, position of this instance is 2 in Grid position system for Y-Direction."))),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"2nd Instance"),": First we will get the position of this instance."),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"In X-Direction"),": As you can see in above image, position of this instance is 2 in Grid position system for X-Direction.")),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},Object(b.b)("strong",{parentName:"p"},"In Y-Direction"),": As you can see in above image, position of this instance is 1 in Grid position system for Y-Direction."))),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Position in special format"),': After we get the position, we need to put "Grid position" of each instance inside ',Object(b.b)("em",{parentName:"p"},"a bracket (or paranthesis)"),"."),Object(b.b)("p",null,'One thing to note here is that, there should be no "',Object(b.b)("strong",{parentName:"p"},"comma"),'" between ',Object(b.b)("strong",{parentName:"p"},"bracket (or paranthesis)"),"."),Object(b.b)("p",null,"Please see below code sample for detail."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Code sample:"))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 4, 1, 0.75, 0.785, 1.5708, "(3,2)(2,1)", True, False, True, True, False, "Arc1_")\n')),Object(b.b)("hr",null),Object(b.b)("h3",{id:"case-6--display-the-spacing-between-instances-dimension-along-the-y-axis"},'CASE 6 : Display the spacing between instances dimension along the "Y" axis'),Object(b.b)("p",null,"In our code sample, we display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"p"},"X")," axis."),Object(b.b)("p",null,"We do this by ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("inlineCode",{parentName:"strong"},"XSpacingDim = True")),"."),Object(b.b)("p",null,"If we want to display the spacing between instances dimension along the ",Object(b.b)("strong",{parentName:"p"},"Y")," axis."),Object(b.b)("p",null,"For that we need to set ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("inlineCode",{parentName:"strong"},"YSpacingDim = True")),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Code sample:"))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 4, 1, 0.75, 0.785, 1.5708, "(3,2)(2,1)", True, True, True, True, False, "Arc1_")\n')),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Example Images:"))),Object(b.b)("p",null,"Below image shows after we update value for ",Object(b.b)("strong",{parentName:"p"},"display dimension along the "),"Y",Object(b.b)("strong",{parentName:"p"}," axis"),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Before Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-YSpacingDim",src:a(260).default})),Object(b.b)("hr",null),Object(b.b)("h3",{id:"case-7--display-the-angle-dimension-between-axes"},"CASE 7 : Display the angle dimension between axes"),Object(b.b)("p",null,"In our code sample, we display the angle dimension between axes."),Object(b.b)("p",null,"We do this by ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("inlineCode",{parentName:"strong"},"AngleDim = True")),"."),Object(b.b)("p",null,"If we don't want to display the angle dimension between axes then we need to set ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("inlineCode",{parentName:"strong"},"AngleDim = False")),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Code sample:"))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 4, 1, 0.75, 0.785, 1.5708, "(3,2)(2,1)", True, True, False, True, False, "Arc1_")\n')),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Example Images:"))),Object(b.b)("p",null,"Below image shows after we update value to ",Object(b.b)("inlineCode",{parentName:"p"},"False")," for ",Object(b.b)("strong",{parentName:"p"},"the angle dimension between axes"),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Before Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-AngleDim",src:a(261).default})),Object(b.b)("hr",null),Object(b.b)("h3",{id:"case-8--display-the-number-of-instances-in-the-x-direction"},'CASE 8 : Display the number of instances in the "X" direction'),Object(b.b)("p",null,"In our code sample, we display the number of instances along the ",Object(b.b)("strong",{parentName:"p"},"X")," axis."),Object(b.b)("p",null,"We do this by ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("inlineCode",{parentName:"strong"},"CreateNumOfInstancesDimInXDir = True")),"."),Object(b.b)("p",null,"If we don't want to display the number of instances along the ",Object(b.b)("strong",{parentName:"p"},"X")," axis then we need to set ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("inlineCode",{parentName:"strong"},"CreateNumOfInstancesDimInXDir = False")),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Code sample:"))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 4, 1, 0.75, 0.785, 1.5708, "(3,2)(2,1)", True, True, False, False, False, "Arc1_")\n')),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Example Images:"))),Object(b.b)("p",null,"Below image shows after we update value to ",Object(b.b)("inlineCode",{parentName:"p"},"False")," for ",Object(b.b)("strong",{parentName:"p"},"not display the number of instances in the X direction"),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Before Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-CreateNumOfInstancesDimInXDir",src:a(262).default})),Object(b.b)("hr",null),Object(b.b)("h3",{id:"case-9--display-the-number-of-instances-in-the-y-direction"},'CASE 9 : Display the number of instances in the "Y" direction'),Object(b.b)("p",null,"In our code sample, we don't display the number of instances along the ",Object(b.b)("strong",{parentName:"p"},"Y")," axis."),Object(b.b)("p",null,"We do this by ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("inlineCode",{parentName:"strong"},"CreateNumOfInstancesDimInYDir = False")),"."),Object(b.b)("p",null,"If we want to display the number of instances along the ",Object(b.b)("strong",{parentName:"p"},"Y")," axis then we need to set ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("inlineCode",{parentName:"strong"},"CreateNumOfInstancesDimInYDir = True")),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Code sample:"))),Object(b.b)("pre",null,Object(b.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),'\' Edit a Linear Sketch Pattern\nBoolStatus = swSketchManager.EditLinearSketchStepAndRepeat(5, 4, 1, 0.75, 0.785, 1.5708, "(3,2)(2,1)", True, True, False, False, True, "Arc1_")\n')),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Example Images:"))),Object(b.b)("p",null,"Below image shows after we update value to ",Object(b.b)("inlineCode",{parentName:"p"},"True")," for ",Object(b.b)("strong",{parentName:"p"},"display the number of instances in the Y direction"),"."),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"Before Edit Linear Sketch Pattern")),Object(b.b)("p",null,Object(b.b)("img",{alt:"edit-linear-pattern-CreateNumOfInstancesDimInXDir",src:a(263).default})),Object(b.b)("hr",null),Object(b.b)("h3",{id:"case-10--multiple-entities-as-seed"},"CASE 10 : Multiple entities as Seed"),Object(b.b)("p",null,"In our code sample, we use only ",Object(b.b)("strong",{parentName:"p"},"1 circle")," for ",Object(b.b)("em",{parentName:"p"},"Linear Sketch pattern"),"."),Object(b.b)("p",null,"But in many cases we need to select ",Object(b.b)("strong",{parentName:"p"},"many sketch entities"),"."),Object(b.b)("p",null,"In this condition, add the entities name with ",Object(b.b)("strong",{parentName:"p"},"an underscore (_)")," one by one."),Object(b.b)("p",null,"For example, we want to pattern a Ractangle, in this case, value of seed should be following:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("strong",{parentName:"li"},"Seed")," : ",Object(b.b)("strong",{parentName:"li"},"Line1",Object(b.b)("em",{parentName:"strong"},"Line2_Line3_Line4")))),Object(b.b)("hr",null),Object(b.b)("h3",{id:"note"},"NOTE"),Object(b.b)("p",null,"It is ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"very important"))," to remember that, when you give distance or any other numeric value in ",Object(b.b)("strong",{parentName:"p"},"Solidworks API"),", Solidworks takes that numeric value in ",Object(b.b)("strong",{parentName:"p"},Object(b.b)("em",{parentName:"strong"},"Meter only")),"."),Object(b.b)("p",null,"Please see below for detail:"),Object(b.b)("ul",null,Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"Length: ",Object(b.b)("strong",{parentName:"p"},"Meter"))),Object(b.b)("li",{parentName:"ul"},Object(b.b)("p",{parentName:"li"},"Angle: ",Object(b.b)("strong",{parentName:"p"},"Radian")))),Object(b.b)("p",null,"Solidworks API does not care about your application's Unit systems."),Object(b.b)("p",null,"For example, I works in ",Object(b.b)("strong",{parentName:"p"},"ANSI")," system means ",Object(b.b)("em",{parentName:"p"},"inches")," for distance. But when I used ",Object(b.b)("strong",{parentName:"p"},"Solidworks API")," through ",Object(b.b)("em",{parentName:"p"},"VBA macros or C#"),", I need to converted numeric values."),Object(b.b)("p",null,"Because Solidworks API output the distance in ",Object(b.b)("strong",{parentName:"p"},"Meter")," which is not my requirement."),Object(b.b)("hr",null),Object(b.b)("p",null,Object(b.b)("strong",{parentName:"p"},"This is it !!!")),Object(b.b)("p",null,"If you found anything to add or update, please let me know on my e-mail."),Object(b.b)("p",null,"Hope this post helps you to ",Object(b.b)("em",{parentName:"p"},"Edit a Linear Sketch Pattern")," with Solidworks VBA Macros."),Object(b.b)("p",null,"For more such tutorials on ",Object(b.b)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),Object(b.b)("p",null,Object(b.b)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),Object(b.b)("p",null,Object(b.b)("em",{parentName:"p"},"Do let me know by you like this post or not!")),Object(b.b)("p",null,Object(b.b)("em",{parentName:"p"},"Till then, Happy learning!!!")))}s.isMDXComponent=!0},152:function(e,t,a){"use strict";a.d(t,"a",(function(){return l})),a.d(t,"b",(function(){return j}));var n=a(0),r=a.n(n);function b(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}function i(e,t){var a=Object.keys(e);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);t&&(n=n.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),a.push.apply(a,n)}return a}function c(e){for(var t=1;t<arguments.length;t++){var a=null!=arguments[t]?arguments[t]:{};t%2?i(Object(a),!0).forEach((function(t){b(e,t,a[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(a)):i(Object(a)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(a,t))}))}return e}function p(e,t){if(null==e)return{};var a,n,r=function(e,t){if(null==e)return{};var a,n,r={},b=Object.keys(e);for(n=0;n<b.length;n++)a=b[n],t.indexOf(a)>=0||(r[a]=e[a]);return r}(e,t);if(Object.getOwnPropertySymbols){var b=Object.getOwnPropertySymbols(e);for(n=0;n<b.length;n++)a=b[n],t.indexOf(a)>=0||Object.prototype.propertyIsEnumerable.call(e,a)&&(r[a]=e[a])}return r}var o=r.a.createContext({}),s=function(e){var t=r.a.useContext(o),a=t;return e&&(a="function"==typeof e?e(t):c(c({},t),e)),a},l=function(e){var t=s(e.components);return r.a.createElement(o.Provider,{value:t},e.children)},m={inlineCode:"code",wrapper:function(e){var t=e.children;return r.a.createElement(r.a.Fragment,{},t)}},O=r.a.forwardRef((function(e,t){var a=e.components,n=e.mdxType,b=e.originalType,i=e.parentName,o=p(e,["components","mdxType","originalType","parentName"]),l=s(a),O=n,j=l["".concat(i,".").concat(O)]||l[O]||m[O]||b;return a?r.a.createElement(j,c(c({ref:t},o),{},{components:a})):r.a.createElement(j,c({ref:t},o))}));function j(e,t){var a=arguments,n=t&&t.mdxType;if("string"==typeof e||n){var b=a.length,i=new Array(b);i[0]=O;var c={};for(var p in t)hasOwnProperty.call(t,p)&&(c[p]=t[p]);c.originalType=e,c.mdxType="string"==typeof e?e:n,i[1]=c;for(var o=2;o<b;o++)i[o]=a[o];return r.a.createElement.apply(null,i)}return r.a.createElement.apply(null,a)}O.displayName="MDXCreateElement"},172:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/after-linear-pattern-b545e8f2dbb930bd1376406b6e2ad911.png"},185:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/edit-linear-pattern-numX-fbb44fc8a66824381a523edcd76aaa5d.png"},186:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/edit-linear-pattern-numY-15c0209171cd9d5aa0a627f28e57da0d.png"},187:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/edit-linear-pattern-angleX-daf7d26125e4d157c8d63c8f319042cd.png"},258:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/edit-linear-pattern-angleY-52de22a441cb36b3448938b034014fc3.png"},259:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/edit-linear-pattern-deleteInstances-ae7e3e63bb528a0f323730ae3d22e13d.png"},260:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/edit-linear-pattern-YSpacingDim-85a14330b67a8136d36e79524fcf900c.png"},261:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/edit-linear-pattern-AngleDim-ea72e00c75257890ab4ff6c68a11110d.png"},262:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/edit-linear-pattern-CreateNumOfInstancesDimInXDir-b8aa2be17454691de084d2bfaa280fa9.png"},263:function(e,t,a){"use strict";a.r(t),t.default=a.p+"assets/images/edit-linear-pattern-CreateNumOfInstancesDimInYDir-79858d9203d05acb39099e2cdde51b25.png"}}]);