(window.webpackJsonp=window.webpackJsonp||[]).push([[77],{134:function(e,t,n){"use strict";n.r(t),n.d(t,"frontMatter",(function(){return i})),n.d(t,"metadata",(function(){return c})),n.d(t,"rightToc",(function(){return r})),n.d(t,"default",(function(){return d}));var a=n(2),o=n(6),l=(n(0),n(152)),i={id:"sw-sketch-macro-add-sketch-relation",title:"Add Sketch Relations (Constraints)"},c={unversionedId:"solidworks-macros/sw-sketch-macro-add-sketch-relation",id:"solidworks-macros/sw-sketch-macro-add-sketch-relation",isDocsHomePage:!1,title:"Add Sketch Relations (Constraints)",description:"In this post, I tell you about how to Add Sketch Relations (Constraints) using Solidworks VBA Macros in a Sketch.",source:"@site/docs\\solidworks-macros\\2020-08-27-add-sketch-relations.md",slug:"/solidworks-macros/sw-sketch-macro-add-sketch-relation",permalink:"/docs/solidworks-macros/sw-sketch-macro-add-sketch-relation",version:"current",sidebar:"swvba",previous:{title:"Toggle (Hide/Show) Sketch Relations",permalink:"/docs/solidworks-macros/sw-sketch-macro-toggle-sketch-relation"},next:{title:"Convert to Construction Sketch",permalink:"/docs/solidworks-macros/sw-sketch-macro-convert-to-construction-sketch"}},r=[{value:"Add Sketch Relations (Constraints) method",id:"add-sketch-relations-constraints-method",children:[]},{value:"Add &#39;Fix&#39; Sketch Relation to a sketch segment",id:"add-fix-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Coincident&#39; Sketch Relation to a sketch segment",id:"add-coincident-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Horizontal&#39; Sketch Relation to a sketch segment",id:"add-horizontal-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Vertical&#39; Sketch Relation to a sketch segment",id:"add-vertical-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Midpoint&#39; Sketch Relation to a sketch segment",id:"add-midpoint-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Co-Linear&#39; Sketch Relation to a sketch segment",id:"add-co-linear-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Perpendicular&#39; Sketch Relation to a sketch segment",id:"add-perpendicular-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Parallel&#39; Sketch Relation to a sketch segment",id:"add-parallel-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Equal Length&#39; Sketch Relation to a sketch segment",id:"add-equal-length-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Tangent&#39; Sketch Relation to a sketch segment",id:"add-tangent-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Same Curve Length&#39; Sketch Relation to a sketch segment",id:"add-same-curve-length-sketch-relation-to-a-sketch-segment",children:[]},{value:"Add &#39;Coincident&#39; Sketch Relation to a sketch segment",id:"add-coincident-sketch-relation-to-a-sketch-segment-1",children:[]},{value:"Add &#39;Coradial&#39; Sketch Relation to a sketch segment",id:"add-coradial-sketch-relation-to-a-sketch-segment",children:[]}],s={rightToc:r};function d(e){var t=e.components,i=Object(o.a)(e,["components"]);return Object(l.b)("wrapper",Object(a.a)({},s,i,{components:t,mdxType:"MDXLayout"}),Object(l.b)("p",null,"In this post, I tell you about ",Object(l.b)("strong",{parentName:"p"},"how to Add Sketch Relations (Constraints) using Solidworks VBA Macros")," in a Sketch."),Object(l.b)("p",null,"In this post, I explain about ",Object(l.b)("inlineCode",{parentName:"p"},"SketchAddConstraints")," method from ",Object(l.b)("strong",{parentName:"p"},"Solidworks"),"'s ",Object(l.b)("inlineCode",{parentName:"p"},"ModelDoc2")," object."),Object(l.b)("p",null,"This method is ",Object(l.b)("strong",{parentName:"p"},Object(l.b)("em",{parentName:"strong"},"most updated"))," method, I found in ",Object(l.b)("em",{parentName:"p"},"Solidworks API Help"),"."),Object(l.b)("p",null,"This post will utilize the methods explained in earlier posts, hence knowledge to those is required but it is not mandatory."),Object(l.b)("p",null,"An absolute beginner can follow what is written here."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-sketch-relations-constraints-method"},"Add Sketch Relations (Constraints) method"),Object(l.b)("p",null,"For adding relations to a sketch segment, we use ",Object(l.b)("inlineCode",{parentName:"p"},"SketchAddConstraints")," method from ",Object(l.b)("strong",{parentName:"p"},"Solidworks"),"'s ",Object(l.b)("inlineCode",{parentName:"p"},"ModelDoc2")," object."),Object(l.b)("p",null,"This ",Object(l.b)("inlineCode",{parentName:"p"},"SketchAddConstraints")," method takes following parameters as explained:"),Object(l.b)("ul",null,Object(l.b)("li",{parentName:"ul"},Object(l.b)("strong",{parentName:"li"},"Constraint")," : ",Object(l.b)("em",{parentName:"li"},"ID of constraint as given on ",Object(l.b)("strong",{parentName:"em"},Object(l.b)("a",Object(a.a)({parentName:"strong"},{href:"http://help.solidworks.com/2020/english/api/sldworksapi/SOLIDWORKS.Interop.sldworks~SOLIDWORKS.Interop.sldworks.IModelDoc2~SketchAddConstraints.html?verRedirect=1"}),"this page")),"."))),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Return Value"),": There are no return value for this method."),Object(l.b)("p",null,"In following sections we add different sketch constraints to sketch segments."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-fix-sketch-relation-to-a-sketch-segment"},"Add 'Fix' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Fixed")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use a ",Object(l.b)("inlineCode",{parentName:"p"},"circle")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Fix")," Sketch Relation to Circle")),Object(l.b)("p",null,Object(l.b)("img",{alt:"circle-before-fixed-relation",src:n(316).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Fix")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Set Solidworks document to active part document\n  Set swDoc = swApp.ActiveDoc\n  \n  ' Select Circle\n  BoolStatus = swDoc.Extension.SelectByID2(\"Arc1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Add Fix sketch relation\n  swDoc.SketchAddConstraints (\"sgFIXED\")\n  \n  ' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n")),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Fix")," Sketch Relation to Circle")),Object(l.b)("p",null,Object(l.b)("img",{alt:"circle-after-fixed-relation",src:n(317).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-coincident-sketch-relation-to-a-sketch-segment"},"Add 'Coincident' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Coincident")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use a ",Object(l.b)("inlineCode",{parentName:"p"},"circle")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Coincident")," Sketch Relation to Circle")),Object(l.b)("p",null,Object(l.b)("img",{alt:"circle-before-coincident-relation",src:n(318).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Coincident")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n\' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  \' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  \' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Select Circle center point\n  BoolStatus = swDoc.Extension.SelectByID2("Point2", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Select Origin\n  BoolStatus = swDoc.Extension.SelectByID2("Point1@Origin", "EXTSKETCHPOINT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Add Coincident sketch relation\n  swDoc.SketchAddConstraints ("sgCOINCIDENT")\n  \n  \' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n')),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Coincident")," Sketch Relation to Circle")),Object(l.b)("p",null,Object(l.b)("img",{alt:"circle-after-coincident-relation",src:n(319).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-horizontal-sketch-relation-to-a-sketch-segment"},"Add 'Horizontal' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Horizontal")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use a ",Object(l.b)("inlineCode",{parentName:"p"},"Line")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Horizontal")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"line-before-horizontal-or-vertical-relation",src:n(174).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Horizontal")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  ' Select Line\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Add Horizontal sketch relation\n  swDoc.SketchAddConstraints (\"sgHORIZONTAL2D\")\n  \n  ' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n")),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Horizontal")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"line-after-horizontal-relation",src:n(320).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-vertical-sketch-relation-to-a-sketch-segment"},"Add 'Vertical' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Vertical")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use a ",Object(l.b)("inlineCode",{parentName:"p"},"Line")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Vertical")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"line-before-horizontal-or-vertical-relation",src:n(174).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Vertical")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  ' Select Line\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Add Vertical sketch relation\n  swDoc.SketchAddConstraints (\"sgVERTICAL2D\")\n  \n  ' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n")),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Vertical")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"line-after-vertical-relation",src:n(321).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-midpoint-sketch-relation-to-a-sketch-segment"},"Add 'Midpoint' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Midpoint")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use a ",Object(l.b)("inlineCode",{parentName:"p"},"Line")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Midpoint")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"line-before-horizontal-or-vertical-relation",src:n(174).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Midpoint")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n\' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  \' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  \' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Select Line\n  BoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Select Origin\n  BoolStatus = swDoc.Extension.SelectByID2("Point1@Origin", "EXTSKETCHPOINT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Add Midpoint sketch relation\n  swDoc.SketchAddConstraints ("sgATMIDDLE")\n  \n  \' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n')),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Midpoint")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"line-after-midpoint-relation",src:n(322).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-co-linear-sketch-relation-to-a-sketch-segment"},"Add 'Co-Linear' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Co-Linear")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use two ",Object(l.b)("inlineCode",{parentName:"p"},"Lines")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Co-Linear")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"lines-before-addng-colinear-relation",src:n(323).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Co-Linear")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n\' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  \' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  \' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Select Line 1\n  BoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Select Line 2\n  BoolStatus = swDoc.Extension.SelectByID2("Line2", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Add Co-Linear sketch relation\n  swDoc.SketchAddConstraints ("sgCOLINEAR")\n  \n  \' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n')),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Co-Linear")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"lines-after-colinear-relation",src:n(324).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-perpendicular-sketch-relation-to-a-sketch-segment"},"Add 'Perpendicular' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Perpendicular")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use two ",Object(l.b)("inlineCode",{parentName:"p"},"Lines")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Perpendicular")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"lines-before-addng-perpendicular-relation",src:n(325).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Perpendicular")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n\' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  \' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  \' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Select Line 1\n  BoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Select Line 2\n  BoolStatus = swDoc.Extension.SelectByID2("Line2", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Add Perpendicular sketch relation\n  swDoc.SketchAddConstraints ("sgPERPENDICULAR")\n  \n  \' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n')),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Perpendicular")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"lines-after-adding-perpendicular-relation",src:n(326).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-parallel-sketch-relation-to-a-sketch-segment"},"Add 'Parallel' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Parallel")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use two ",Object(l.b)("inlineCode",{parentName:"p"},"Lines")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Parallel")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"lines-before-addng-parallel-relation",src:n(327).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Parallel")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n\' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  \' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  \' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Select Line 1\n  BoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Select Line 2\n  BoolStatus = swDoc.Extension.SelectByID2("Line2", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Add Parallel sketch relation\n  swDoc.SketchAddConstraints ("sgPARALLEL")\n  \n  \' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n')),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Parallel")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"lines-after-adding-parallel-relation",src:n(328).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-equal-length-sketch-relation-to-a-sketch-segment"},"Add 'Equal Length' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Equal Length")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use two ",Object(l.b)("inlineCode",{parentName:"p"},"Lines")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Equal Length")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"lines-before-addng-equal-relation",src:n(329).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Equal Length")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n\' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  \' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  \' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Select Line 1\n  BoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Select Line 2\n  BoolStatus = swDoc.Extension.SelectByID2("Line2", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Add Equal Length sketch relation\n  swDoc.SketchAddConstraints ("sgSAMELENGTH")\n  \n  \' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n')),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Equal Length")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"lines-after-adding-equal-relation",src:n(330).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-tangent-sketch-relation-to-a-sketch-segment"},"Add 'Tangent' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Tangent")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use a ",Object(l.b)("inlineCode",{parentName:"p"},"Line")," and a ",Object(l.b)("inlineCode",{parentName:"p"},"Circle")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Tangent")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"line-circle-before-adding-tangent-relation",src:n(331).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Tangent")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n\' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  \' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  \' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Select Line 1\n  BoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Select Line 2\n  BoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Add Tangent sketch relation\n  swDoc.SketchAddConstraints ("sgTANGENT")\n  \n  \' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n')),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Tangent")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"line-circle-after-adding-tangent-relation",src:n(332).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-same-curve-length-sketch-relation-to-a-sketch-segment"},"Add 'Same Curve Length' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Same Curve Length")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use a ",Object(l.b)("inlineCode",{parentName:"p"},"Line")," and a ",Object(l.b)("inlineCode",{parentName:"p"},"Circle")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Same Curve Length")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"line-circle-before-adding-equal-curve-length-relation",src:n(333).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Same Curve Length")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n\' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  \' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  \' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Select Line 1\n  BoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Select Line 2\n  BoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Add Same Curve Length sketch relation\n  swDoc.SketchAddConstraints ("sgSAMECURVELENGTH")\n  \n  \' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n')),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Same Curve Length")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"line-circle-after-adding-equal-curve-length-relation",src:n(334).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-coincident-sketch-relation-to-a-sketch-segment-1"},"Add 'Coincident' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Coincident")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use ",Object(l.b)("strong",{parentName:"p"},"two")," ",Object(l.b)("inlineCode",{parentName:"p"},"Circles")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Coincident")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"circles-before-adding-concentric-relation",src:n(335).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Coincident")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n\' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  \' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  \' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Select Line 1\n  BoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Select Line 2\n  BoolStatus = swDoc.Extension.SelectByID2("Arc2", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Add Coincident sketch relation\n  swDoc.SketchAddConstraints ("sgCONCENTRIC")\n  \n  \' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n')),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Coincident")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"circles-after-adding-concentric-relation",src:n(336).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("h2",{id:"add-coradial-sketch-relation-to-a-sketch-segment"},"Add 'Coradial' Sketch Relation to a sketch segment"),Object(l.b)("p",null,"Here we learn how to add ",Object(l.b)("inlineCode",{parentName:"p"},"Coradial")," ",Object(l.b)("em",{parentName:"p"},"sketch relation")," to a sketch segment through ",Object(l.b)("strong",{parentName:"p"},"VBA"),"."),Object(l.b)("p",null,"We need ",Object(l.b)("em",{parentName:"p"},"an unconstraint sketch segment"),"."),Object(l.b)("p",null,"In this post, I use ",Object(l.b)("strong",{parentName:"p"},"two")," ",Object(l.b)("inlineCode",{parentName:"p"},"Circles")," as shown in below image:"),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Before Add ",Object(l.b)("em",{parentName:"strong"},"Coradial")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"circles-before-adding-coradial-relation",src:n(337).default})),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"Code to add ",Object(l.b)("inlineCode",{parentName:"strong"},"Coradial")," sketch relation")),Object(l.b)("pre",null,Object(l.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'Option Explicit\n\n\' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n\' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n\' Boolean Variable\nDim BoolStatus As Boolean\n\nSub main()\n\n  \' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  \' Set Solidworks document to new part document\n  Set swDoc = swApp.ActiveDoc\n  \n  \' Select Line 1\n  BoolStatus = swDoc.Extension.SelectByID2("Arc1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Select Line 2\n  BoolStatus = swDoc.Extension.SelectByID2("Arc2", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  \' Add Coradial sketch relation\n  swDoc.SketchAddConstraints ("sgCORADIAL")\n  \n  \' Clear selection after adding relation\n  swDoc.ClearSelection2 True\n\nEnd Sub\n')),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"After Add ",Object(l.b)("em",{parentName:"strong"},"Coradial")," Sketch Relation to Line")),Object(l.b)("p",null,Object(l.b)("img",{alt:"circles-after-adding-coradial-relation",src:n(338).default})),Object(l.b)("p",null,"I have added comments to each line ",Object(l.b)("inlineCode",{parentName:"p"},"code sample"),", hence it is easy to understand."),Object(l.b)("hr",null),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},"This is it !!!")),Object(l.b)("p",null,Object(l.b)("em",{parentName:"p"},"I hope my efforts will helpful to someone!")),Object(l.b)("p",null,"If you found anything to ",Object(l.b)("strong",{parentName:"p"},"add or update"),", please let me know on my ",Object(l.b)("em",{parentName:"p"},"e-mail"),"."),Object(l.b)("p",null,"Hope this post helps you to ",Object(l.b)("strong",{parentName:"p"},Object(l.b)("em",{parentName:"strong"},"Add Sketch Relations (Constraints)"))," with Solidworks VBA Macros."),Object(l.b)("p",null,"For more such tutorials on ",Object(l.b)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},Object(l.b)("em",{parentName:"strong"},"If you like the post then please share it with your friends also."))),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},Object(l.b)("em",{parentName:"strong"},"Do let me know by you like this post or not!"))),Object(l.b)("p",null,Object(l.b)("strong",{parentName:"p"},Object(l.b)("em",{parentName:"strong"},"Till then, Happy learning!!!"))))}d.isMDXComponent=!0},152:function(e,t,n){"use strict";n.d(t,"a",(function(){return b})),n.d(t,"b",(function(){return u}));var a=n(0),o=n.n(a);function l(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function i(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function c(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?i(Object(n),!0).forEach((function(t){l(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):i(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function r(e,t){if(null==e)return{};var n,a,o=function(e,t){if(null==e)return{};var n,a,o={},l=Object.keys(e);for(a=0;a<l.length;a++)n=l[a],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var l=Object.getOwnPropertySymbols(e);for(a=0;a<l.length;a++)n=l[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var s=o.a.createContext({}),d=function(e){var t=o.a.useContext(s),n=t;return e&&(n="function"==typeof e?e(t):c(c({},t),e)),n},b=function(e){var t=d(e.components);return o.a.createElement(s.Provider,{value:t},e.children)},p={inlineCode:"code",wrapper:function(e){var t=e.children;return o.a.createElement(o.a.Fragment,{},t)}},m=o.a.forwardRef((function(e,t){var n=e.components,a=e.mdxType,l=e.originalType,i=e.parentName,s=r(e,["components","mdxType","originalType","parentName"]),b=d(n),m=a,u=b["".concat(i,".").concat(m)]||b[m]||p[m]||l;return n?o.a.createElement(u,c(c({ref:t},s),{},{components:n})):o.a.createElement(u,c({ref:t},s))}));function u(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var l=n.length,i=new Array(l);i[0]=m;var c={};for(var r in t)hasOwnProperty.call(t,r)&&(c[r]=t[r]);c.originalType=e,c.mdxType="string"==typeof e?e:a,i[1]=c;for(var s=2;s<l;s++)i[s]=n[s];return o.a.createElement.apply(null,i)}return o.a.createElement.apply(null,n)}m.displayName="MDXCreateElement"},174:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/line-before-horizontal-or-vertical-relation-08ae3dfc4ace10dc123cd1fd1c11723b.png"},316:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/circle-before-fixed-relation-d62a926fde8166bdf7898025f3d6f569.png"},317:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/circle-after-fixed-relation-7afd0a3ae15a36b59c0936e068dfce94.png"},318:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/circle-before-coincident-relation-a0f2766de60f089de97cb4883f4b24c0.png"},319:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/circle-after-coincident-relation-c1fef741c7ffc33d1ec85394e70060c5.png"},320:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/line-after-horizontal-relation-0f02d0a6cc81e1beb0075e7271d5517e.png"},321:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/line-after-vertical-relation-8b98fb4d657aad4b086e409d851a1b0a.png"},322:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/line-after-midpoint-relation-0f3046d27d2255b5578628881e4399db.png"},323:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/lines-before-addng-colinear-relation-a85ea9f6573f3f9111889729b9a36b4d.png"},324:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/lines-after-colinear-relation-b708dbd8d24521b329078eb1362ae98e.png"},325:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/lines-before-addng-perpendicular-relation-6934a8b5e84d81ed0e1a501b9dc698dd.png"},326:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/lines-after-adding-perpendicular-relation-f47d14bfc47b9576d06a04d4f7b1945c.png"},327:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/lines-before-addng-parallel-relation-8309e73860ab1220bddf293f748e9f06.png"},328:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/lines-after-adding-parallel-relation-5055afc161716e184f708ea802ba69e4.png"},329:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/lines-before-addng-equal-relation-802502c63abde1312502e73b2b5a6d9f.png"},330:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/lines-after-adding-equal-relation-e90055c9565f844a0857a9a06e2416da.png"},331:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/line-circle-before-adding-tangent-relation-24bd26aff144680bc0eb825d028094f7.png"},332:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/line-circle-after-adding-tangent-relation-55c3f3abd56232112947201112738eb9.png"},333:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/line-circle-before-adding-equal-curve-length-relation-24bd26aff144680bc0eb825d028094f7.png"},334:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/line-circle-after-adding-equal-curve-length-relation-40f1be15e15bb80241c1a1a18786daab.png"},335:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/circles-before-adding-concentric-relation-4b414309e0f0ee2165a29b9cadb98cf9.png"},336:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/circles-after-adding-concentric-relation-4d1f5f86033b04dd4b1d6b0e31ba8df7.png"},337:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/circles-before-adding-coradial-relation-7d83a0d9a9e38a3229712f4c6edc5f92.png"},338:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/circles-after-adding-coradial-relation-dc69d65de5fbd628ca6f97bdd1ac3852.png"}}]);