(window.webpackJsonp=window.webpackJsonp||[]).push([[79],{136:function(e,t,a){"use strict";a.r(t),a.d(t,"frontMatter",(function(){return i})),a.d(t,"metadata",(function(){return c})),a.d(t,"rightToc",(function(){return s})),a.d(t,"default",(function(){return l}));var n=a(2),o=a(6),r=(a(0),a(152)),i={id:"sw-macro-open-part",title:"Open new Part document"},c={unversionedId:"solidworks-macros/sw-macro-open-part",id:"solidworks-macros/sw-macro-open-part",isDocsHomePage:!1,title:"Open new Part document",description:"As the title suggested, in this post, we open new document from Solidworks VBA macros.",source:"@site/docs\\solidworks-macros\\2019-02-3-open-new-document.md",slug:"/solidworks-macros/sw-macro-open-part",permalink:"/docs/solidworks-macros/sw-macro-open-part",version:"current",sidebar:"swvba",previous:{title:"VBA in Solidworks",permalink:"/docs/vba-in-sw"},next:{title:"Open Assembly and Drawing document",permalink:"/docs/solidworks-macros/sw-macro-open-asm-and-dwg"}},s=[],p={rightToc:s};function l(e){var t=e.components,a=Object(o.a)(e,["components"]);return Object(r.b)("wrapper",Object(n.a)({},p,a,{components:t,mdxType:"MDXLayout"}),Object(r.b)("p",null,"As the title suggested, in this post, we open new document ",Object(r.b)("strong",{parentName:"p"},"from")," ",Object(r.b)("em",{parentName:"p"},"Solidworks VBA macros"),"."),Object(r.b)("p",null,"Also we ",Object(r.b)("em",{parentName:"p"},"understand")," each and every line of written code. So that you can understand why we written those lines and get some knowledge about how to write macro properly."),Object(r.b)("p",null,"Please see below video for visual details."),Object(r.b)("div",{class:"youtube-responsive-container"},Object(r.b)("iframe",{src:"https://www.youtube.com/embed/SXrdQ0vrTyI",frameborder:"0",allowfullscreen:!0})),Object(r.b)("p",null,"To do this, we first need to create a new empty macro. If you don't know how to create an empty macro; then please go to this ",Object(r.b)("a",Object(n.a)({parentName:"p"},{href:"/docs/vba-in-sw"}),"VBA in Solidworks")," post."),Object(r.b)("p",null,"After creating an empty macro, you need to copy paste below code into this empty macro."),Object(r.b)("pre",null,Object(r.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Main function of our VBA program\nSub main()\n\n    ' Setting Solidworks variable to Solidworks application\n    Set swApp = Application.SldWorks\n    \n    ' Creating string type variable for storing default part location\n    Dim defaultTemplate As String\n    ' Setting value of this string type variable to \"Default part template\"\n    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n    ' Setting Solidworks document to new part document\n    Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n\nEnd Sub\n")),Object(r.b)("p",null,"This code opens ",Object(r.b)("strong",{parentName:"p"},"a new default part")," template in Solidworks."),Object(r.b)("p",null,"Now let us walk through ",Object(r.b)("em",{parentName:"p"},"each line")," in the above code, and ",Object(r.b)("strong",{parentName:"p"},"understand")," the meaning of every line."),Object(r.b)("pre",null,Object(r.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n")),Object(r.b)("p",null,"This line forces us to define every variable we are going to use. "),Object(r.b)("p",null,"This is ",Object(r.b)("strong",{parentName:"p"},"very important")," because if you don't declare above line, it is very difficult to caught ",Object(r.b)("em",{parentName:"p"},"typo errors")," in variable names."),Object(r.b)("p",null,"This type of error comes, when you mistakenly type wrong spelling of your defined variable."),Object(r.b)("p",null,"In this case, VBE thinks that you have defined a new variable and use this variable. "),Object(r.b)("p",null,"This causes issues because your program runs perfectly but you didn't get the desired result."),Object(r.b)("p",null,"This most of the time discourage people and ultimately they left the programming."),Object(r.b)("p",null,"So be on safe side and use this ",Object(r.b)("strong",{parentName:"p"},"Option Explicit")," line in your every module."),Object(r.b)("pre",null,Object(r.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),Object(r.b)("p",null,"As the comments in above code sample shows, in these 2 lines we are creating variables of different type."),Object(r.b)("pre",null,Object(r.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Creating variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),Object(r.b)("p",null,"In this line, we are creating a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),Object(r.b)("p",null,"If we ",Object(r.b)("strong",{parentName:"p"},"omit")," 1 ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks"),", then our ",Object(r.b)("em",{parentName:"p"},"VBE")," show error if we try to run this macro."),Object(r.b)("pre",null,Object(r.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Creating variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),Object(r.b)("p",null,"In this line, we are creating a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),Object(r.b)("p",null,"Here, if we omit ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks"),", the compiler won't give error. I used it to know who is the parent object."),Object(r.b)("p",null,Object(r.b)("inlineCode",{parentName:"p"},"ModelDoc2")," is the a ",Object(r.b)("strong",{parentName:"p"},"object"),", which holds properties and methods related to this a document."),Object(r.b)("p",null,"These methods and properties are common to ",Object(r.b)("em",{parentName:"p"},"part"),", ",Object(r.b)("em",{parentName:"p"},"assembly")," and ",Object(r.b)("em",{parentName:"p"},"drawing")," documents."),Object(r.b)("p",null,"You can see more about ",Object(r.b)("inlineCode",{parentName:"p"},"ModelDoc2")," in this help ",Object(r.b)("a",Object(n.a)({parentName:"p"},{href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.IModelDoc2.html?verRedirect=1"}),"link"),"."),Object(r.b)("p",null,"Next is our ",Object(r.b)("inlineCode",{parentName:"p"},"Sub")," procedure named ",Object(r.b)("inlineCode",{parentName:"p"},"main"),". This procedure hold all the ",Object(r.b)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),Object(r.b)("pre",null,Object(r.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Setting Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),Object(r.b)("p",null,"In this line, we are setting the value of our Solidworks variable which we define earlier to Solidworks application."),Object(r.b)("div",{className:"admonition admonition-caution alert alert--warning"},Object(r.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(n.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(n.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"16",height:"16",viewBox:"0 0 16 16"}),Object(r.b)("path",Object(n.a)({parentName:"svg"},{fillRule:"evenodd",d:"M8.893 1.5c-.183-.31-.52-.5-.887-.5s-.703.19-.886.5L.138 13.499a.98.98 0 0 0 0 1.001c.193.31.53.501.886.501h13.964c.367 0 .704-.19.877-.5a1.03 1.03 0 0 0 .01-1.002L8.893 1.5zm.133 11.497H6.987v-2.003h2.039v2.003zm0-3.004H6.987V5.987h2.039v4.006z"})))),"caution")),Object(r.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"Now it important to know that when you defined a variable of different type, which is not a common type, then you need to set the variable also."))),Object(r.b)("p",null,"This is a standard way to set Solidworks application. This way is given in many Solidworks API VBA example."),Object(r.b)("pre",null,Object(r.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Creating string type variable for storing default part location\nDim defaultTemplate As String\n' Setting value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),Object(r.b)("p",null,"In 1st statement of above example, we are defining a variable of ",Object(r.b)("inlineCode",{parentName:"p"},"string")," type and named it as ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),Object(r.b)("p",null,"This variable ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",Object(r.b)("strong",{parentName:"p"},"Default Part Template"),"."),Object(r.b)("p",null,"In 2nd line of above example. we assign value to our newly define ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),Object(r.b)("p",null,"We assign the value by using a ",Object(r.b)("em",{parentName:"p"},"Method")," named ",Object(r.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". This method is a part of our main Solidworks variable ",Object(r.b)("inlineCode",{parentName:"p"},"swApp"),"."),Object(r.b)("p",null,"To access this method, we need to write ",Object(r.b)("inlineCode",{parentName:"p"},"swApp"),' variable and then use a "." to access the ',Object(r.b)("em",{parentName:"p"},"Public properties")," and ",Object(r.b)("em",{parentName:"p"},"Methods")," inside this variable."),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(n.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(n.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(n.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},'This "." is called ',Object(r.b)("strong",{parentName:"p"},"Dot operator"),". This operator provides us the access to the ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Public properties"))," and ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Methods"))," inside an object."))),Object(r.b)("p",null,'When you type after a "." you will notice that ',Object(r.b)("em",{parentName:"p"},"Visual Basic Editor")," automatically provides a list of properties and methods inside this ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," object. This helps us to write correct name for these methods and properties."),Object(r.b)("p",null,"Now we get the function ",Object(r.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". But this function needs some input to work with. This inputs are generally called ",Object(r.b)("strong",{parentName:"p"},"Parameters"),"."),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(n.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(n.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(n.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"In programming voculabury, we need to pass the parameter to this function so that this function can worked."))),Object(r.b)("p",null,"This input parameter is a single value from a list of other values. This list is stored in ",Object(r.b)("inlineCode",{parentName:"p"},"swUserPreferenceStringValue_e")," object."),Object(r.b)("p",null,"In Solidworks API, if anything has ",Object(r.b)("inlineCode",{parentName:"p"},"_e")," after it, it means that this object contains some type of lists. It is important to know because we frequently use these type of lists. They are called ",Object(r.b)("strong",{parentName:"p"},"enum"),". The value they hold is called ",Object(r.b)("strong",{parentName:"p"},"Constant"),"."),Object(r.b)("p",null,"So our function ",Object(r.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," needs some constant value from ",Object(r.b)("inlineCode",{parentName:"p"},"swUserPreferenceStringValue_e")," enum list to work."),Object(r.b)("p",null,"Since we want ",Object(r.b)("em",{parentName:"p"},"Default part template"),", we use ",Object(r.b)("inlineCode",{parentName:"p"},"swDefaultTemplatePart")," constant value from the ",Object(r.b)("inlineCode",{parentName:"p"},"swUserPreferenceStringValue_e")," enum list."),Object(r.b)("div",{className:"admonition admonition-tip alert alert--success"},Object(r.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(n.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(n.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"}),Object(r.b)("path",Object(n.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"})))),"tip")),Object(r.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"Please note that there are lots of values inside this enum list. You can see these values from this ",Object(r.b)("a",Object(n.a)({parentName:"p"},{href:"http://help.solidworks.com/2019/English/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swUserPreferenceStringValue_e.html"}),"link"),"."))),Object(r.b)("p",null,"Now we just need to set the value of our ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," variable to new document. We set the value as shown in below code snippet."),Object(r.b)("pre",null,Object(r.b)("code",Object(n.a)({parentName:"pre"},{className:"language-vb"}),"' Setting Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),Object(r.b)("p",null,"To set the value of ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc"),", we use ",Object(r.b)("inlineCode",{parentName:"p"},"NewDocument()")," method. This method is inside ",Object(r.b)("inlineCode",{parentName:"p"},"swApp"),", hence we first need to invoke ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," and then by using ",Object(r.b)("em",{parentName:"p"},"Dot operator")," we access the ",Object(r.b)("inlineCode",{parentName:"p"},"NewDocument()")," method."),Object(r.b)("p",null,"Now this method needs 4 parameters (or input values) to work. If we don't provide any of these required value we get errors."),Object(r.b)("p",null,"These 4 parameters are as follows:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"TemplateName")),Object(r.b)("p",{parentName:"li"},"  This can be a full path of the template, which we use to create New document.")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"PaperSize")),Object(r.b)("p",{parentName:"li"},"  Size of paper")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"Width")),Object(r.b)("p",{parentName:"li"},"  Width of paper")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"Height")),Object(r.b)("p",{parentName:"li"},"  Height of paper"))),Object(r.b)("p",null,"When successfully implemented, this method creates a new document. "),Object(r.b)("p",null,"If this method failes to create a new document in that case this return ",Object(r.b)("inlineCode",{parentName:"p"},"NULL")," value. We can use this ",Object(r.b)("inlineCode",{parentName:"p"},"NULL")," value to check if the operation is successfull or not."),Object(r.b)("p",null,"In our example, we use ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate")," variable as ",Object(r.b)("em",{parentName:"p"},"TemplateName")," parameter and use ",Object(r.b)("strong",{parentName:"p"},"0")," in all other 3 parameter."),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(n.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(n.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(n.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(n.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"Please note that ",Object(r.b)("em",{parentName:"p"},"PaperSize"),", ",Object(r.b)("em",{parentName:"p"},"Width")," and ",Object(r.b)("em",{parentName:"p"},"Height")," is used only if we want to create a new ",Object(r.b)("strong",{parentName:"p"},"Drawing document"),"."))),Object(r.b)("p",null,"This is all for now. This post is getting too long. "),Object(r.b)("p",null,"In next post I will tell you how to create a new ",Object(r.b)("em",{parentName:"p"},"Assembly")," document and new ",Object(r.b)("em",{parentName:"p"},"Drawing")," document."))}l.isMDXComponent=!0},152:function(e,t,a){"use strict";a.d(t,"a",(function(){return b})),a.d(t,"b",(function(){return u}));var n=a(0),o=a.n(n);function r(e,t,a){return t in e?Object.defineProperty(e,t,{value:a,enumerable:!0,configurable:!0,writable:!0}):e[t]=a,e}function i(e,t){var a=Object.keys(e);if(Object.getOwnPropertySymbols){var n=Object.getOwnPropertySymbols(e);t&&(n=n.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),a.push.apply(a,n)}return a}function c(e){for(var t=1;t<arguments.length;t++){var a=null!=arguments[t]?arguments[t]:{};t%2?i(Object(a),!0).forEach((function(t){r(e,t,a[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(a)):i(Object(a)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(a,t))}))}return e}function s(e,t){if(null==e)return{};var a,n,o=function(e,t){if(null==e)return{};var a,n,o={},r=Object.keys(e);for(n=0;n<r.length;n++)a=r[n],t.indexOf(a)>=0||(o[a]=e[a]);return o}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(n=0;n<r.length;n++)a=r[n],t.indexOf(a)>=0||Object.prototype.propertyIsEnumerable.call(e,a)&&(o[a]=e[a])}return o}var p=o.a.createContext({}),l=function(e){var t=o.a.useContext(p),a=t;return e&&(a="function"==typeof e?e(t):c(c({},t),e)),a},b=function(e){var t=l(e.components);return o.a.createElement(p.Provider,{value:t},e.children)},m={inlineCode:"code",wrapper:function(e){var t=e.children;return o.a.createElement(o.a.Fragment,{},t)}},d=o.a.forwardRef((function(e,t){var a=e.components,n=e.mdxType,r=e.originalType,i=e.parentName,p=s(e,["components","mdxType","originalType","parentName"]),b=l(a),d=n,u=b["".concat(i,".").concat(d)]||b[d]||m[d]||r;return a?o.a.createElement(u,c(c({ref:t},p),{},{components:a})):o.a.createElement(u,c({ref:t},p))}));function u(e,t){var a=arguments,n=t&&t.mdxType;if("string"==typeof e||n){var r=a.length,i=new Array(r);i[0]=d;var c={};for(var s in t)hasOwnProperty.call(t,s)&&(c[s]=t[s]);c.originalType=e,c.mdxType="string"==typeof e?e:n,i[1]=c;for(var p=2;p<r;p++)i[p]=a[p];return o.a.createElement.apply(null,i)}return o.a.createElement.apply(null,a)}d.displayName="MDXCreateElement"}}]);