(window.webpackJsonp=window.webpackJsonp||[]).push([[82],{139:function(e,t,n){"use strict";n.r(t),n.d(t,"frontMatter",(function(){return c})),n.d(t,"metadata",(function(){return b})),n.d(t,"rightToc",(function(){return i})),n.d(t,"default",(function(){return s}));var a=n(2),o=n(6),r=(n(0),n(152)),c={id:"sw-sketch-macro-rotate-or-copy-sketch-entities",title:"Rotate/Copy Sketch Entities"},b={unversionedId:"solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities",id:"solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities",isDocsHomePage:!1,title:"Rotate/Copy Sketch Entities",description:"In this post, I tell you about how to Rotate/Copy Sketch Entities using Solidworks VBA Macros in a Sketch.",source:"@site/docs\\solidworks-macros\\2020-05-08-rotate-copy-sketch-entities.md",slug:"/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities",permalink:"/docs/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities",version:"current",sidebar:"swvba",previous:{title:"Move/Copy Sketch Entities",permalink:"/docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities"},next:{title:"Toggle (Hide/Show) Sketch Relations",permalink:"/docs/solidworks-macros/sw-sketch-macro-toggle-sketch-relation"}},i=[{value:"Code Sample",id:"code-sample",children:[{value:"Understanding the Code",id:"understanding-the-code",children:[]}]},{value:"Destination Point Values",id:"destination-point-values",children:[{value:"On X-Y Plane",id:"on-x-y-plane",children:[]},{value:"On Y-Z Plane",id:"on-y-z-plane",children:[]},{value:"On X-Z Plane",id:"on-x-z-plane",children:[]}]},{value:"Cases",id:"cases",children:[{value:"CASE 1 : Rotate Sketch Entities",id:"case-1--rotate-sketch-entities",children:[]},{value:"CASE 2 : Copy and Rotate Sketch Entities",id:"case-2--copy-and-rotate-sketch-entities",children:[]}]}],l={rightToc:i};function s(e){var t=e.components,c=Object(o.a)(e,["components"]);return Object(r.b)("wrapper",Object(a.a)({},l,c,{components:t,mdxType:"MDXLayout"}),Object(r.b)("p",null,"In this post, I tell you about ",Object(r.b)("strong",{parentName:"p"},"how to Rotate/Copy Sketch Entities using Solidworks VBA Macros")," in a Sketch."),Object(r.b)("p",null,"In this post, I explain about ",Object(r.b)("inlineCode",{parentName:"p"},"RotateOrCopy")," method from ",Object(r.b)("strong",{parentName:"p"},"Solidworks")," ",Object(r.b)("inlineCode",{parentName:"p"},"ModelDoc2"),"'s ",Object(r.b)("inlineCode",{parentName:"p"},"Extension")," object."),Object(r.b)("p",null,"This method is ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"most updated"))," method, I found in ",Object(r.b)("em",{parentName:"p"},"Solidworks API Help"),". "),Object(r.b)("p",null,"So ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"use this method"))," if you want to ",Object(r.b)("em",{parentName:"p"},"RotateOrCopy Sketch Entities"),"."),Object(r.b)("p",null,"This post is similar to previous ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-sketch-macro-move-or-copy-sketch-entities"}),"Sketch Transformation - Move/Copy Sketch Entities"))," post."),Object(r.b)("p",null,"If you have not visited my previous ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-sketch-macro-move-or-copy-sketch-entities"}),"Sketch Transformation - Move/Copy Sketch Entities"))," post, then please do check-it if you want to learn Move/Copy Sketch Entities from VBA Macros."),Object(r.b)("hr",null),Object(r.b)("h2",{id:"code-sample"},"Code Sample"),Object(r.b)("p",null,"Below is the ",Object(r.b)("inlineCode",{parentName:"p"},"code")," sample to ",Object(r.b)("em",{parentName:"p"},"edit Circular Sketch Pattern"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n\n' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n\n' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n\n' Boolean Variable\nDim BoolStatus As Boolean\n\n' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n\n' Create Variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n\n' Main function of our VBA program\nSub main()\n\n  ' Set Solidworks variable to Solidworks application\n  Set swApp = Application.SldWorks\n  \n  ' Create string type variable for storing default part location\n  Dim defaultTemplate As String\n\n  ' Set value of this string type variable to \"Default part template\"\n  defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n\n  ' Set Solidworks document to new part document\n  Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n  \n  '-----------------------UNIT CONVERSION----------------------------------------\n\n  ' Local variables used as Conversion Factors\n  Dim LengthConversionFactor As Double\n  Dim AngleConversionFactor As Double\n  \n  ' Use a Select Case, to get the length of active Unit and set the different factors\n  Select Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n    \n    Case swMETER    ' If length is in Meter\n      LengthConversionFactor = 1\n      AngleConversionFactor = 1\n    \n    Case swMM       ' If length is in MM\n      LengthConversionFactor = 1 / 1000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swCM       ' If length is in CM\n      LengthConversionFactor = 1 / 100\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swINCHES   ' If length is in INCHES\n      LengthConversionFactor = 1 * 0.0254\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEET     ' If length is in FEET\n      LengthConversionFactor = 1 * (0.0254 * 12)\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swFEETINCHES     ' If length is in FEET & INCHES\n      LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swANGSTROM        ' If length is in ANGSTROM\n      LengthConversionFactor = 1 / 10000000000#\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swNANOMETER       ' If length is in NANOMETER\n      LengthConversionFactor = 1 / 1000000000\n      AngleConversionFactor = 1 * 0.01745329\n    \n    Case swMICRON       ' If length is in MICRON\n      LengthConversionFactor = 1 / 1000000\n      AngleConversionFactor = 1 * 0.01745329\n  End Select\n\n  '----------------------------------------------------------------\n\n  ' Select Front Plane\n  BoolStatus = swDoc.Extension.SelectByID2(\"Front Plane\", \"PLANE\", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n\n  ' Set Sketch manager for our sketch\n  Set swSketchManager = swDoc.SketchManager\n\n  ' Insert a sketch into selected plane\n  swSketchManager.InsertSketch True\n  \n  ' Create a local variable for CenterPoint ractangle\n  Dim vSketch As Variant\n  \n  ' Create CenterPoint ractangle\n  vSketch = swSketchManager.CreateCenterRectangle(0, 0, 0, 1 * LengthConversionFactor, 1 * LengthConversionFactor, 0)\n    \n  ' De-select the lines after creation\n  swDoc.ClearSelection2 True\n  \n  ' Select all lines of CenterPoint Ractangle\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line1\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line2\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line3\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  BoolStatus = swDoc.Extension.SelectByID2(\"Line4\", \"SKETCHSEGMENT\", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n  \n  ' Rotate CenterPoint Ractangle by 45 degree only\n  swDoc.Extension.RotateOrCopy False, 1, True, 0, 0, 0, 0, 0, 1, 45 * AngleConversionFactor\n  \n  ' De-select all after creation\n  swDoc.ClearSelection2 True\n  \n  ' Show Front View after Circular Sketch Pattern\n  swDoc.ShowNamedView2 \"\", swStandardViews_e.swFrontView\n  \n  ' Zoom to fit screen in Solidworks Window\n  swDoc.ViewZoomtofit2\n  \nEnd Sub\n")),Object(r.b)("hr",null),Object(r.b)("h3",{id:"understanding-the-code"},"Understanding the Code"),Object(r.b)("p",null,"Now let us walk through ",Object(r.b)("strong",{parentName:"p"},"each line")," in the above code, and ",Object(r.b)("strong",{parentName:"p"},"understand")," the meaning and purpose of every line."),Object(r.b)("p",null,"I also give some link so that you can go through them if there are anything I explained in ",Object(r.b)("strong",{parentName:"p"},"previous posts"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"Option Explicit\n")),Object(r.b)("p",null,"This line forces us to define every variable we are going to use. "),Object(r.b)("p",null,"For more information please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks application\nDim swApp As SldWorks.SldWorks\n")),Object(r.b)("p",null,"In this line, we create a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swApp")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.SldWorks"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks document\nDim swDoc As SldWorks.ModelDoc2\n")),Object(r.b)("p",null,"In this line, we create a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.ModelDoc2"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Boolean Variable\nDim BoolStatus As Boolean\n")),Object(r.b)("p",null,"In this line, we create a variable named ",Object(r.b)("inlineCode",{parentName:"p"},"BoolStatus")," as ",Object(r.b)("inlineCode",{parentName:"p"},"Boolean")," object type."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks Sketch Manager\nDim swSketchManager As SldWorks.SketchManager\n")),Object(r.b)("p",null,"In above line, we create variable ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchManager")," for ",Object(r.b)("strong",{parentName:"p"},"Solidworks Sketch Manager"),"."),Object(r.b)("p",null,"As the name suggested, a ",Object(r.b)("strong",{parentName:"p"},"Sketch Manager")," holds variours methods and properties to manage ",Object(r.b)("em",{parentName:"p"},"Sketches"),"."),Object(r.b)("p",null,"To see methods and properties related to ",Object(r.b)("inlineCode",{parentName:"p"},"SketchManager")," object, please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html"}),"this page")),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create variable for Solidworks Sketch Segment\nDim swSketchSegment As SldWorks.SketchSegment\n")),Object(r.b)("p",null,"In this line, we Create a variable which we named as ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchSegment")," and the type of this ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchSegment")," variable is ",Object(r.b)("inlineCode",{parentName:"p"},"SldWorks.SketchSegment"),"."),Object(r.b)("p",null,"We create variable ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchSegment")," for ",Object(r.b)("strong",{parentName:"p"},"Solidworks Sketch Segments"),"."),Object(r.b)("p",null,"To see methods and properties related to ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchSegment")," object, please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"http://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html"}),"this page")),"."),Object(r.b)("p",null,"These all are our global variables."),Object(r.b)("p",null,"As you can see in code sample, they are ",Object(r.b)("strong",{parentName:"p"},"Solidworks API Objects"),"."),Object(r.b)("p",null,"So basically I group all the ",Object(r.b)("strong",{parentName:"p"},"Solidworks API Objects")," in one place."),Object(r.b)("p",null,"I have also place ",Object(r.b)("inlineCode",{parentName:"p"},"boolean")," type object at top also, because after certain point we will ",Object(r.b)("em",{parentName:"p"},"need")," this variable frequently."),Object(r.b)("p",null,"Thus, I have started placing it here."),Object(r.b)("p",null,"Next is our ",Object(r.b)("inlineCode",{parentName:"p"},"Sub")," procedure which has name of ",Object(r.b)("inlineCode",{parentName:"p"},"main"),". "),Object(r.b)("p",null,"This procedure hold all the ",Object(r.b)("em",{parentName:"p"},"statements (instructions)")," we give to computer."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Solidworks variable to Solidworks application\nSet swApp = Application.SldWorks\n")),Object(r.b)("p",null,"In this line, we set the value of our Solidworks variable ",Object(r.b)("inlineCode",{parentName:"p"},"swApp"),"; which we define earlier; to Solidworks application."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create string type variable for storing default part location\nDim defaultTemplate As String\n' Set value of this string type variable to \"Default part template\"\ndefaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)\n")),Object(r.b)("p",null,"In 1st statement of above example, we are defining a variable of ",Object(r.b)("inlineCode",{parentName:"p"},"string")," type and named it as ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate"),"."),Object(r.b)("p",null,"This variable ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate"),", hold the location the location of ",Object(r.b)("strong",{parentName:"p"},"Default Part Template"),"."),Object(r.b)("p",null,"In 2nd line of above example. we assign value to our newly define ",Object(r.b)("inlineCode",{parentName:"p"},"defaultTemplate")," variable."),Object(r.b)("p",null,"We assign the value by using a ",Object(r.b)("em",{parentName:"p"},"Method")," named ",Object(r.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()"),". "),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"GetUserPreferenceStringValue()")," method is a part of our main Solidworks variable ",Object(r.b)("inlineCode",{parentName:"p"},"swApp"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Solidworks document to new part document\nSet swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)\n")),Object(r.b)("p",null,"In this line, we set the value of our ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc")," variable to new document."),Object(r.b)("p",null,"For ",Object(r.b)("strong",{parentName:"p"},"detailed information")," about these lines please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post."),Object(r.b)("p",null,"I have discussed them ",Object(r.b)("strong",{parentName:"p"},"thoroghly")," in ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-open-part"}),"Solidworks Macros - Open new Part document"))," post, so do checkout that post if you want to understand above code in more detail."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"'-----------------------UNIT CONVERSION----------------------------------------\n\n' Local variables used as Conversion Factors\nDim LengthConversionFactor As Double\nDim AngleConversionFactor As Double\n\n' Use a Select Case, to get the length of active Unit and set the different factors\nSelect Case swDoc.GetUnits(0)       ' GetUnits function gives us, active unit\n  \n  Case swMETER    ' If length is in Meter\n    LengthConversionFactor = 1\n    AngleConversionFactor = 1\n  \n  Case swMM       ' If length is in MM\n    LengthConversionFactor = 1 / 1000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swCM       ' If length is in CM\n    LengthConversionFactor = 1 / 100\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swINCHES   ' If length is in INCHES\n    LengthConversionFactor = 1 * 0.0254\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEET     ' If length is in FEET\n    LengthConversionFactor = 1 * (0.0254 * 12)\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swFEETINCHES     ' If length is in FEET & INCHES\n    LengthConversionFactor = 1 * 0.0254  ' For length we use sama as Inch\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swANGSTROM        ' If length is in ANGSTROM\n    LengthConversionFactor = 1 / 10000000000#\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swNANOMETER       ' If length is in NANOMETER\n    LengthConversionFactor = 1 / 1000000000\n    AngleConversionFactor = 1 * 0.01745329\n  \n  Case swMICRON       ' If length is in MICRON\n    LengthConversionFactor = 1 / 1000000\n    AngleConversionFactor = 1 * 0.01745329\nEnd Select\n\n'----------------------------------------------------------------\n")),Object(r.b)("p",null,"Above code sample shows how to ",Object(r.b)("strong",{parentName:"p"},"fix Solidworks API Unit issue"),". "),Object(r.b)("p",null,"We ",Object(r.b)("em",{parentName:"p"},"1st")," get the ",Object(r.b)("em",{parentName:"p"},"current unit")," of the part and apply the ",Object(r.b)("em",{parentName:"p"},"switch")," statements to update our ",Object(r.b)("em",{parentName:"p"},"Length and Angle Conversion factors"),". "),Object(r.b)("p",null,"I have already explained in detail about ",Object(r.b)("strong",{parentName:"p"},"Fixing Solidworks API Unit Issue")," in ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-sketch-macro-fix-unit-issue"}),"Fix Unit Issue"))," blog post. "),Object(r.b)("p",null,"Do checkout above post for Fixing Solidworks API Issue."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Select Front Plane\nBoolStatus = swDoc.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),Object(r.b)("p",null,"In above line, we select the ",Object(r.b)("em",{parentName:"p"},"front plane")," by using ",Object(r.b)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",Object(r.b)("inlineCode",{parentName:"p"},"Extension")," object."),Object(r.b)("p",null,"For more information about selection method please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-macro-selection-methods"}),"Solidworks Macros - Selection Methods"))," post."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Set Sketch manager for our sketch\nSet swSketchManager = swDoc.SketchManager\n")),Object(r.b)("p",null,"In above line, we set the ",Object(r.b)("em",{parentName:"p"},"Sketch manager")," variable to ",Object(r.b)("em",{parentName:"p"},"current document's sketch manager"),"."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Insert a sketch into selected plane\nswSketchManager.InsertSketch True\n")),Object(r.b)("p",null,"In above line, we use ",Object(r.b)("inlineCode",{parentName:"p"},"InsertSketch")," method of ",Object(r.b)("em",{parentName:"p"},"SketchManager")," and give ",Object(r.b)("inlineCode",{parentName:"p"},"True")," value."),Object(r.b)("p",null,"This method allows us to insert a sketch in selected plane."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Create a local variable for CenterPoint ractangle\nDim vSketch As Variant\n\n' Create CenterPoint ractangle\nvSketch = swSketchManager.CreateCenterRectangle(0, 0, 0, 1 * LengthConversionFactor, 1 * LengthConversionFactor, 0)\n")),Object(r.b)("p",null,"In above code sample, we do following:"),Object(r.b)("ol",null,Object(r.b)("li",{parentName:"ol"},Object(r.b)("p",{parentName:"li"},"Create a local variable named ",Object(r.b)("inlineCode",{parentName:"p"},"vSketch"),", which is ",Object(r.b)("inlineCode",{parentName:"p"},"Variant")," type.")),Object(r.b)("li",{parentName:"ol"},Object(r.b)("p",{parentName:"li"},"In 2nd line, we Create CenterPoint ractangle by using ",Object(r.b)("inlineCode",{parentName:"p"},"CreateCenterRectangle")," method."),Object(r.b)("p",{parentName:"li"},"This ",Object(r.b)("inlineCode",{parentName:"p"},"CreateCenterRectangle")," method is available in ",Object(r.b)("inlineCode",{parentName:"p"},"swSketchManager")," variable.")),Object(r.b)("li",{parentName:"ol"},Object(r.b)("p",{parentName:"li"},"This ",Object(r.b)("inlineCode",{parentName:"p"},"CreateCenterRectangle")," method return a value. We store that value in previously defined variable  ",Object(r.b)("inlineCode",{parentName:"p"},"vSketch"),"."))),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Side of CenterPoint ractangle:")," ",Object(r.b)("em",{parentName:"p"},'1" or 1 inch')),Object(r.b)("p",null,"If you want to know more about ",Object(r.b)("inlineCode",{parentName:"p"},"CreateCenterRectangle")," method, then please visit ",Object(r.b)("strong",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"strong"},{href:"sw-sketch-macro-create-center-rec"}),"Sketch - Create Center Rectangle"))," post."),Object(r.b)("p",null,"I have given a detail explaination about ",Object(r.b)("inlineCode",{parentName:"p"},"CreateCenterRectangle")," method there."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' De-select the lines after creation\nswDoc.ClearSelection2 True\n")),Object(r.b)("p",null,"After creating a Square, we de-select all entities."),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),'\' Select all lines of Center Ractangle\nBoolStatus = swDoc.Extension.SelectByID2("Line1", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\nBoolStatus = swDoc.Extension.SelectByID2("Line2", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\nBoolStatus = swDoc.Extension.SelectByID2("Line3", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\nBoolStatus = swDoc.Extension.SelectByID2("Line4", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, swSelectOption_e.swSelectOptionDefault)\n')),Object(r.b)("p",null,"In above line of code, we select all lines of Center Ractangle by using ",Object(r.b)("inlineCode",{parentName:"p"},"SelectByID2")," method from ",Object(r.b)("inlineCode",{parentName:"p"},"swDoc.Extension")," object."),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"I have not create separate variable ",Object(r.b)("inlineCode",{parentName:"p"},"Extension"),", because I like to avoid creating extra objects."))),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Please not that we have selected only Sides, not the diagonals.")),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Rotate Center Ractangle\nswDoc.Extension.RotateOrCopy False, 1, True, 0, 0, 0, 0, 0, 1, 45 * AngleConversionFactor\n")),Object(r.b)("p",null,'For "',Object(r.b)("strong",{parentName:"p"},"Rotating"),'" a sketch entity, we need ',Object(r.b)("inlineCode",{parentName:"p"},"RotateOrCopy")," method from ",Object(r.b)("strong",{parentName:"p"},"Solidworks")," ",Object(r.b)("inlineCode",{parentName:"p"},"ModelDoc2"),"'s ",Object(r.b)("inlineCode",{parentName:"p"},"Extension")," object."),Object(r.b)("p",null,"This ",Object(r.b)("inlineCode",{parentName:"p"},"RotateOrCopy")," method takes following parameters as explained:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Copy")," : ",Object(r.b)("em",{parentName:"p"},Object(r.b)("inlineCode",{parentName:"em"},"True")," to copy the sketch entities, ",Object(r.b)("inlineCode",{parentName:"em"},"False")," to not."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"NumCopies")," : ",Object(r.b)("em",{parentName:"p"},"Number of copies you want to create."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"KeepRelations")," : ",Object(r.b)("em",{parentName:"p"},Object(r.b)("inlineCode",{parentName:"em"},"True")," to keep sketch relations after Rotate or Copy operation, ",Object(r.b)("inlineCode",{parentName:"em"},"False")," to not."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"BaseX")," : ",Object(r.b)("em",{parentName:"p"},"X coordinate of the base point from which to Rotate the sketch entities."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"BaseY")," : ",Object(r.b)("em",{parentName:"p"},"Y coordinate of the base point from which to Rotate the sketch entities."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"BaseZ")," : ",Object(r.b)("em",{parentName:"p"},"Z coordinate of the base point from which to Rotate the sketch entities."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestX")," : ",Object(r.b)("em",{parentName:"p"},"X coordinate of the destination point from which to Rotate the sketch entities."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestY")," : ",Object(r.b)("em",{parentName:"p"},"Y coordinate of the destination point from which to Rotate the sketch entities."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestZ")," : ",Object(r.b)("em",{parentName:"p"},"Z coordinate of the destination point from which to Rotate the sketch entities."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Angle")," : ",Object(r.b)("em",{parentName:"p"},"Angle of Rotation by which we rotate the selected sketch entities.")))),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"There are no return value after this function."))),Object(r.b)("hr",null),Object(r.b)("h2",{id:"destination-point-values"},"Destination Point Values"),Object(r.b)("p",null,"Destination Point is defined by following parameters:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestX"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestY"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestZ")))),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"The values of these parameters are mainly dependent on the plane, you have selected.")),Object(r.b)("p",null,"There values as per ",Object(r.b)("strong",{parentName:"p"},"Default Planes")," is given below."),Object(r.b)("h3",{id:"on-x-y-plane"},"On X-Y Plane"),Object(r.b)("p",null,"When ",Object(r.b)("strong",{parentName:"p"},"X-Y")," plane is selected, then values are:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestX")," = 0")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestY")," = 0")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestZ")," = 1"))),Object(r.b)("hr",null),Object(r.b)("h3",{id:"on-y-z-plane"},"On Y-Z Plane"),Object(r.b)("p",null,"When ",Object(r.b)("strong",{parentName:"p"},"Y-Z")," plane is selected, then values are:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestX")," = 1")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestY")," = 0")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestZ")," = 0"))),Object(r.b)("hr",null),Object(r.b)("h3",{id:"on-x-z-plane"},"On X-Z Plane"),Object(r.b)("p",null,"When ",Object(r.b)("strong",{parentName:"p"},"X-Z")," plane is selected, then values are:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestX")," = 0")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestY")," = 1")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestZ")," = 0"))),Object(r.b)("p",null,"Since we are creating our Sketch in ",Object(r.b)("strong",{parentName:"p"},"X-Y")," plane, hence I used the values accordingly."),Object(r.b)("hr",null),Object(r.b)("h2",{id:"cases"},"Cases"),Object(r.b)("p",null,"In this section, we will go through different cases by "),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"Modifying different parameters"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("em",{parentName:"p"},"See images, before and after parameter modification")))),Object(r.b)("hr",null),Object(r.b)("h3",{id:"case-1--rotate-sketch-entities"},"CASE 1 : Rotate Sketch Entities"),Object(r.b)("p",null,"In our code, if we want to ",Object(r.b)("em",{parentName:"p"},"Rotate Sketch Entities"),", then we need to use code sample as given below:"),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Rotate circle\nswDoc.Extension.RotateOrCopy False, 1, True, 0, 0, 0, 0, 0, 1, 45 * AngleConversionFactor\n")),Object(r.b)("p",null,"In above code we ",Object(r.b)("strong",{parentName:"p"},"Rotate Sketch Entities")," with:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Base Point")," : ",Object(r.b)("inlineCode",{parentName:"p"},"0, 0, 0"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Rotation Angle")," : ",Object(r.b)("em",{parentName:"p"},Object(r.b)("inlineCode",{parentName:"em"},"45 Degree")," Anti-clock wise"),"."))),Object(r.b)("div",{className:"admonition admonition-note alert alert--secondary"},Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"14",height:"16",viewBox:"0 0 14 16"}),Object(r.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"})))),"note")),Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"If you want to rotate Clock-wise, then then use ",Object(r.b)("strong",{parentName:"p"},"Negeative (-ve)")," value."))),Object(r.b)("p",null,"In above code we need to set following parameters:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Copy")," : ",Object(r.b)("inlineCode",{parentName:"p"},"False")," to not create a copy.")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"NumCopies")," : ",Object(r.b)("em",{parentName:"p"},"Number of copies you want to create to 1 which is itself."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"KeepRelations")," : ",Object(r.b)("em",{parentName:"p"},Object(r.b)("inlineCode",{parentName:"em"},"True")," to keep sketch relations after Rotate or Copy operation."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"BaseX")," : ",Object(r.b)("em",{parentName:"p"},"X coordinate of the base point  = 0"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"BaseY")," : ",Object(r.b)("em",{parentName:"p"},"Y coordinate of the base point  = 0"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"BaseZ")," : ",Object(r.b)("em",{parentName:"p"},"Z coordinate of the base point  = 0")))),Object(r.b)("p",null,"Since we are creating sketch in ",Object(r.b)("strong",{parentName:"p"},"X-Y plane"),", hence I used values mentioned in ",Object(r.b)("em",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"em"},{href:"sw-sketch-macro-rotate-or-copy-sketch-entities#destination-point-values"}),"Destination Point Values"))," section of this post."),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestX")," : ",Object(r.b)("em",{parentName:"p"},"X coordinate of the destination  = 0"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestY")," : ",Object(r.b)("em",{parentName:"p"},"Y coordinate of the destination point  = 0"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestZ")," : ",Object(r.b)("em",{parentName:"p"},"Z coordinate of the destination point  = 1"),"  ")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Rotation Angle")," : ",Object(r.b)("em",{parentName:"p"},"Angle of Rotation by which we rotate the selected sketch entities = ",Object(r.b)("inlineCode",{parentName:"em"},"45 Degree")," Anti-clock wise"),"."))),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Example Images:"))),Object(r.b)("p",null,"Below image shows before and after we ",Object(r.b)("strong",{parentName:"p"},"Rotate Sketch Entitny"),"."),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Before Rotate Sketch Entitny")),Object(r.b)("p",null,Object(r.b)("img",{alt:"before-rotate",src:n(199).default})),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"After Rotate Sketch Entitny")),Object(r.b)("p",null,Object(r.b)("img",{alt:"after-Rotate",src:n(341).default})),Object(r.b)("hr",null),Object(r.b)("h3",{id:"case-2--copy-and-rotate-sketch-entities"},"CASE 2 : Copy and Rotate Sketch Entities"),Object(r.b)("p",null,"In our code, if we want to ",Object(r.b)("em",{parentName:"p"},"Copy and Rotate Sketch Entities"),", then we need to use code sample as given below:"),Object(r.b)("pre",null,Object(r.b)("code",Object(a.a)({parentName:"pre"},{className:"language-vb"}),"' Copy circle\nswDoc.Extension.RotateOrCopy True, 2, True, 0, 0, 0, destinationCoOrdinateInXDir, destinationCoOrdinateInYDir, 0\n")),Object(r.b)("p",null,"In above code we ",Object(r.b)("strong",{parentName:"p"},"Rotate Sketch Entities")," with:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Create Copy")," : ",Object(r.b)("inlineCode",{parentName:"p"},"True"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Base Point")," : ",Object(r.b)("inlineCode",{parentName:"p"},"0, 0, 0"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Rotation Angle of Copied Entity")," : ",Object(r.b)("em",{parentName:"p"},Object(r.b)("inlineCode",{parentName:"em"},"45 Degree")," Anti-clock wise"),"."))),Object(r.b)("div",{className:"admonition admonition-tip alert alert--success"},Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-heading"}),Object(r.b)("h5",{parentName:"div"},Object(r.b)("span",Object(a.a)({parentName:"h5"},{className:"admonition-icon"}),Object(r.b)("svg",Object(a.a)({parentName:"span"},{xmlns:"http://www.w3.org/2000/svg",width:"12",height:"16",viewBox:"0 0 12 16"}),Object(r.b)("path",Object(a.a)({parentName:"svg"},{fillRule:"evenodd",d:"M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"})))),"tip")),Object(r.b)("div",Object(a.a)({parentName:"div"},{className:"admonition-content"}),Object(r.b)("p",{parentName:"div"},"If you want to rotate Clock-wise, then then use ",Object(r.b)("strong",{parentName:"p"},"Negeative (-ve)")," value."))),Object(r.b)("p",null,"In above code we need to set following parameters:"),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Copy")," : ",Object(r.b)("inlineCode",{parentName:"p"},"True")," to not create a copy.")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"NumCopies")," : ",Object(r.b)("em",{parentName:"p"},"Number of copies you want to create to 2 which is itself."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"KeepRelations")," : ",Object(r.b)("em",{parentName:"p"},Object(r.b)("inlineCode",{parentName:"em"},"True")," to keep sketch relations after Rotate or Copy operation."))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"BaseX")," : ",Object(r.b)("em",{parentName:"p"},"X coordinate of the base point  = 0"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"BaseY")," : ",Object(r.b)("em",{parentName:"p"},"Y coordinate of the base point  = 0"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"BaseZ")," : ",Object(r.b)("em",{parentName:"p"},"Z coordinate of the base point  = 0")))),Object(r.b)("p",null,"Since we are creating sketch in ",Object(r.b)("strong",{parentName:"p"},"X-Y plane"),", hence I used values mentioned in ",Object(r.b)("em",{parentName:"p"},Object(r.b)("a",Object(a.a)({parentName:"em"},{href:"sw-sketch-macro-rotate-or-copy-sketch-entities#destination-point-values"}),"Destination Point Values"))," sections of this post."),Object(r.b)("ul",null,Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestX")," : ",Object(r.b)("em",{parentName:"p"},"X coordinate of the destination  = 0"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestY")," : ",Object(r.b)("em",{parentName:"p"},"Y coordinate of the destination point  = 0"))),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"DestZ")," : ",Object(r.b)("em",{parentName:"p"},"Z coordinate of the destination point  = 1"),"  ")),Object(r.b)("li",{parentName:"ul"},Object(r.b)("p",{parentName:"li"},Object(r.b)("strong",{parentName:"p"},"Rotation Angle")," : ",Object(r.b)("em",{parentName:"p"},"Angle of Rotation by which we rotate the selected sketch entities = ",Object(r.b)("inlineCode",{parentName:"em"},"45 Degree")," Anti-clock wise"),"."))),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},Object(r.b)("em",{parentName:"strong"},"Example Images:"))),Object(r.b)("p",null,"Below image shows before and after we ",Object(r.b)("strong",{parentName:"p"},"Rotate Sketch Entitny"),"."),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"Before Rotate Sketch Entitny")),Object(r.b)("p",null,Object(r.b)("img",{alt:"before-rotate",src:n(199).default})),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"After Rotate Sketch Entitny")),Object(r.b)("p",null,Object(r.b)("img",{alt:"after-rotate-copy",src:n(342).default})),Object(r.b)("hr",null),Object(r.b)("p",null,Object(r.b)("strong",{parentName:"p"},"This is it !!!")),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"I hope my efforts will helpful to someone!")),Object(r.b)("p",null,"If you found anything to ",Object(r.b)("strong",{parentName:"p"},"add or update"),", please let me know on my ",Object(r.b)("em",{parentName:"p"},"e-mail"),"."),Object(r.b)("p",null,"Hope this post helps you to ",Object(r.b)("em",{parentName:"p"},"Rotate/Copy Sketch Entities")," with Solidworks VBA Macros."),Object(r.b)("p",null,"For more such tutorials on ",Object(r.b)("strong",{parentName:"p"},"Solidworks VBA Macro"),", do come to this blog after sometime."),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"If you like the post then please share it with your friends also.")),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"Do let me know by you like this post or not!")),Object(r.b)("p",null,Object(r.b)("em",{parentName:"p"},"Till then, Happy learning!!!")))}s.isMDXComponent=!0},152:function(e,t,n){"use strict";n.d(t,"a",(function(){return p})),n.d(t,"b",(function(){return j}));var a=n(0),o=n.n(a);function r(e,t,n){return t in e?Object.defineProperty(e,t,{value:n,enumerable:!0,configurable:!0,writable:!0}):e[t]=n,e}function c(e,t){var n=Object.keys(e);if(Object.getOwnPropertySymbols){var a=Object.getOwnPropertySymbols(e);t&&(a=a.filter((function(t){return Object.getOwnPropertyDescriptor(e,t).enumerable}))),n.push.apply(n,a)}return n}function b(e){for(var t=1;t<arguments.length;t++){var n=null!=arguments[t]?arguments[t]:{};t%2?c(Object(n),!0).forEach((function(t){r(e,t,n[t])})):Object.getOwnPropertyDescriptors?Object.defineProperties(e,Object.getOwnPropertyDescriptors(n)):c(Object(n)).forEach((function(t){Object.defineProperty(e,t,Object.getOwnPropertyDescriptor(n,t))}))}return e}function i(e,t){if(null==e)return{};var n,a,o=function(e,t){if(null==e)return{};var n,a,o={},r=Object.keys(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||(o[n]=e[n]);return o}(e,t);if(Object.getOwnPropertySymbols){var r=Object.getOwnPropertySymbols(e);for(a=0;a<r.length;a++)n=r[a],t.indexOf(n)>=0||Object.prototype.propertyIsEnumerable.call(e,n)&&(o[n]=e[n])}return o}var l=o.a.createContext({}),s=function(e){var t=o.a.useContext(l),n=t;return e&&(n="function"==typeof e?e(t):b(b({},t),e)),n},p=function(e){var t=s(e.components);return o.a.createElement(l.Provider,{value:t},e.children)},m={inlineCode:"code",wrapper:function(e){var t=e.children;return o.a.createElement(o.a.Fragment,{},t)}},O=o.a.forwardRef((function(e,t){var n=e.components,a=e.mdxType,r=e.originalType,c=e.parentName,l=i(e,["components","mdxType","originalType","parentName"]),p=s(n),O=a,j=p["".concat(c,".").concat(O)]||p[O]||m[O]||r;return n?o.a.createElement(j,b(b({ref:t},l),{},{components:n})):o.a.createElement(j,b({ref:t},l))}));function j(e,t){var n=arguments,a=t&&t.mdxType;if("string"==typeof e||a){var r=n.length,c=new Array(r);c[0]=O;var b={};for(var i in t)hasOwnProperty.call(t,i)&&(b[i]=t[i]);b.originalType=e,b.mdxType="string"==typeof e?e:a,c[1]=b;for(var l=2;l<r;l++)c[l]=n[l];return o.a.createElement.apply(null,c)}return o.a.createElement.apply(null,n)}O.displayName="MDXCreateElement"},199:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/before-rotate-95ba4720f9d992c772ccb39bbcda7176.png"},341:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/after-Rotate-c3f376c62b8fe7637a9607114fcc7e47.png"},342:function(e,t,n){"use strict";n.r(t),t.default=n.p+"assets/images/after-rotate-copy-a5a65287c46f18bb65fa555cc9da0bbd.png"}}]);