<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="generator" content="Docusaurus v2.0.0-alpha.66">
<link rel="preconnect" href="https://www.google-analytics.com">
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-117501871-2","auto"),ga("set","anonymizeIp",!0),ga("send","pageview")</script>
<script async src="https://www.google-analytics.com/analytics.js"></script>
<script data-ad-client="ca-pub-8158659264340002" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script><title data-react-helmet="true">Selection Methods | The Cad Coder</title><meta data-react-helmet="true" name="twitter:card" content="summary_large_image"><meta data-react-helmet="true" name="docusaurus_language" content="en"><meta data-react-helmet="true" name="docusaurus_version" content="current"><meta data-react-helmet="true" name="docusaurus_tag" content="docs-default-current"><meta data-react-helmet="true" property="og:title" content="Selection Methods | The Cad Coder"><meta data-react-helmet="true" name="description" content="In this post, we select Default planes with following methods:"><meta data-react-helmet="true" property="og:description" content="In this post, we select Default planes with following methods:"><meta data-react-helmet="true" property="og:url" content="https://prashantbaher.github.io//docs/solidworks-macros/sw-macro-selection-methods"><link data-react-helmet="true" rel="shortcut icon" href="/img/logo.png"><link data-react-helmet="true" rel="canonical" href="https://prashantbaher.github.io//docs/solidworks-macros/sw-macro-selection-methods"><link rel="stylesheet" href="/styles.f7ef45b3.css">
<link rel="preload" href="/styles.c3633769.js" as="script">
<link rel="preload" href="/runtime~main.4d18c882.js" as="script">
<link rel="preload" href="/main.08717c6b.js" as="script">
<link rel="preload" href="/1.4d0f5633.js" as="script">
<link rel="preload" href="/2.9b374bfd.js" as="script">
<link rel="preload" href="/94.e6f15855.js" as="script">
<link rel="preload" href="/95.291d156d.js" as="script">
<link rel="preload" href="/f976f453.2a96abdd.js" as="script">
<link rel="preload" href="/17896441.b813b81e.js" as="script">
<link rel="preload" href="/9047f1f2.513f72a7.js" as="script">
</head>
<body>
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><div aria-label="Navigation bar toggle" class="navbar__toggle" role="button" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></div><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a><div class="navbar__item dropdown dropdown--hoverable dropdown--left"><a class="navbar__item navbar__link">VBA</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li><a class="dropdown__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></div><a class="navbar__item navbar__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a><a class="navbar__item navbar__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></div><div class="navbar__items navbar__items--right"><div class="navbar__item dropdown dropdown--hoverable dropdown--right"><a class="navbar__item navbar__link">About</a><ul class="dropdown__menu"><li><a class="dropdown__link" position="right" href="/docs/about">About Me</a></li><li><a class="dropdown__link" position="right" href="/docs/resources">Resources</a></li><li><a class="dropdown__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></div><div class="react-toggle react-toggle--disabled displayOnlyInLargeViewport_2aTZ"><div class="react-toggle-track"><div class="react-toggle-track-check"><span class="toggle_BsTx">ðŸŒœ</span></div><div class="react-toggle-track-x"><span class="toggle_BsTx">ðŸŒž</span></div></div><div class="react-toggle-thumb"></div><input type="checkbox" disabled="" aria-label="Dark mode toggle" class="react-toggle-screenreader-only"></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div><div class="navbar-sidebar"><div class="navbar-sidebar__brand"><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a></div><div class="navbar-sidebar__items"><div class="menu"><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">VBA</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></li><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">About</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/about">About Me</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/resources">Resources</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></li></ul></div></div></div></nav><div class="main-wrapper"><div class="docPage_2gpo"><div class="docSidebarContainer_3_JD" role="complementary"><div class="sidebar_2urC"><div class="menu menu--responsive menu_5FrY"><button aria-label="Open Menu" aria-haspopup="true" class="button button--secondary button--sm menu__button" type="button"><svg aria-label="Menu" class="sidebarMenuIcon_Dm3K" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 32 32" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><ul class="menu__list"><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!">General Functions</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-in-sw">VBA in Solidworks</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-macro-open-part">Open new Part document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-macro-open-asm-and-dwg">Open Assembly and Drawing document</a></li><li class="menu__list-item"><a aria-current="page" class="menu__link menu__link--active active" tabindex="0" href="/docs/solidworks-macros/sw-macro-selection-methods">Selection Methods</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-macro-open-saved-documents">Open Saved Documents</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/solidworks-macros/sw-sketch-macro-fix-unit-issue">Fix Unit Issue</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!">Sketch</a><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Lines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-line">Create Line</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerline">Create CenterLine</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Rectangles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-corner-rec">Create Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-center-rec">Create Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-corner-rec">Create 3-Point Corner Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-center-rec">Create 3-Point Center Rectangle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-parallelogram">Create A Parallelogram</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Circles</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle">Create Circle</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-circle-by-radius">Create Circle By Radius</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-perimeter-circle">Create Perimeter Circle</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Arcs</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc">Create Centerpoint Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-tangent-arc">Create Tangent Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc">Create 3-Point Arc</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-polygon">Create Polygon</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Slots</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-straight-slot">Create a Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-straight-slot">Create a Centerpoint Straight Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-3point-arc-slot">Create a 3-Point Arc Slot</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-centerpoint-arc-slot">Create a Centerpoint Arc Slot</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Splines</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-point">Create a Point</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-spline">Create a Spline</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Fillet &amp; Chamfer</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-fillet">Create a Fillet</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-create-chamfer">Create a Chamfer</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Trim and Extend</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-trim-entities">Trim Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-extend-entities">Extend Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Offset and Mirror</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-offset-entities">Offset Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-mirror-sketch-entities">Mirror Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Sketch Patterns</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-linear-sketch-patterm">Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-linear-sketch-patterm">Edit Linear Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-circular-sketch-patterm">Circular Sketch Pattern</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-edit-circular-sketch-pattern">Edit Circular Sketch Pattern</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Sketch Transformation</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-move-or-copy-sketch-entities">Move/Copy Sketch Entities</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-rotate-or-copy-sketch-entities">Rotate/Copy Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Sketch Relations</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-toggle-sketch-relation">Toggle (Hide/Show) Sketch Relations</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-sketch-relation">Add Sketch Relations (Constraints)</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Others</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-convert-to-construction-sketch">Convert to Construction Sketch</a></li><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-split-sketch-entities">Split Open/Closed Sketch Entities</a></li></ul></li><li class="menu__list-item menu__list-item--collapsed"><a class="menu__link menu__link--sublist" href="#!" tabindex="-1">Sketch Dimensioning</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="-1" href="/docs/solidworks-macros/sw-sketch-macro-add-dimension-sketch-entities">Add dimension to Sketch Entities</a></li></ul></li></ul></li></ul></div></div></div><main class="docMainContainer_3EyW"><div class="container padding-vert--lg docItemWrapper_1EkI"><div class="row"><div class="col docItemCol_2ASc"><div class="docItemContainer_3QWW"><article><header><h1 class="docTitle_1Lrw">Selection Methods</h1></header><div class="markdown"><p>In this post, we select <strong>Default planes</strong> with following methods:</p><ol><li><p>By <code>SelectByID</code> method From <code>ModelDoc2</code> Interface</p></li><li><p>By <code>SelectByID2</code> method From <code>IModelDocExtension</code> Interface</p></li></ol><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="by-selectbyid-method-from-modeldoc2-interface"></a>By <strong>SelectByID</strong> method From <strong>ModelDoc2</strong> Interface<a aria-hidden="true" tabindex="-1" class="hash-link" href="#by-selectbyid-method-from-modeldoc2-interface" title="Direct link to heading">#</a></h2><p><code>SelectByID</code> method From <code>ModelDoc2</code> Interface is the easiest method for selecting Default plane.</p><p>I will explain the use of this method in 2 different scenerio as follows:</p><ol><li><p>Using this method in the previous example of creating a new document and then select a Plane.</p></li><li><p>Using this method in an open document.</p></li></ol><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="using-selectbyid-method-in-previous-example"></a>Using SelectByID method in previous example<a aria-hidden="true" tabindex="-1" class="hash-link" href="#using-selectbyid-method-in-previous-example" title="Direct link to heading">#</a></h3><p>In the previous 2 posts, we learned how to create <em>a new part document, an assembly document, and a drawing document</em>.</p><p>Now we use the same code and <em>extended</em> it for using selecting planes.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Creating string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    BoolStatus = swDoc.SelectByID(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>Above code, 1st create a new part document and then select &quot;<strong>Front Plane</strong>&quot; in VBA macro.</p><p>To select the plane, I have to add 2 lines. 1st I create a boolean varible above main function as shown in below code:</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div></div></div></div></div><p>Then I use this <code>BoolStatus</code> variable to selecting <em>Front Plane</em> as shown in below code:</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swDoc.SelectByID(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0)</span></div></div></div></div></div><p><code>SelectByID</code> takes following parameters:</p><p><em>Name</em> : Name of the object or an empty string</p><p><em>Type</em> : Type of object in uppercase or an empty string</p><p><em>X</em> : X selection location</p><p><em>Y</em> : Y selection location</p><p><em>Z</em> : Z selection location</p><p><strong>Return Value</strong> - If the item is select then this method returns <code>True</code> and otherwise <code>False</code>.</p><p>Since this method returns <code>True</code> or <code>False</code>, hence we use a <code>boolean</code> variable to perfom this method.</p><p>If we want to select <strong>Right Plane</strong> then we just need to replace <code>&quot;Front Plane&quot;</code> -&gt; <code>&quot;Right Plane&quot;</code> in previous code sample.</p><p>Similar for selecting <strong>Top Plane</strong>, we need to replace <code>&quot;Front Plane&quot;</code> -&gt; <code>&quot;Top Plane&quot;</code> in previous code sample.</p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="using-selectbyid-method-in-an-open-document"></a>Using SelectByID method in an Open document<a aria-hidden="true" tabindex="-1" class="hash-link" href="#using-selectbyid-method-in-an-open-document" title="Direct link to heading">#</a></h3><p>For using <code>SelectByID</code> method in an open document we use differnet code sample.</p><p>The code sample is given below:</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">        </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting Solidworks document to active open document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Set swDoc = swApp.ActiveDoc</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">        </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    BoolStatus = swDoc.SelectByID(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>Most of the things in this code sample is already explained in <strong>(<a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a>)</strong> post and in previous section of this very post.</p><p>In this code I have set the <em>Solidworks document variable</em> <code>swDoc</code> to active open document.</p><p>And then we use similar method to select <strong>&quot;Front Plane&quot;</strong>.</p><p>As explained in previous section we can select <strong>Right Plane</strong> and <strong>Top Plane</strong>.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="by-selectbyid2-method-from-imodeldocextension-interface"></a>By <strong>SelectByID2</strong> method From <strong>IModelDocExtension</strong> Interface<a aria-hidden="true" tabindex="-1" class="hash-link" href="#by-selectbyid2-method-from-imodeldocextension-interface" title="Direct link to heading">#</a></h2><p>This method is similar to <code>SelectByID</code> from previous section infact it is the <em>updated version</em> of previous method.</p><p>Since it is <em>updated</em> and has <em>additional functionality</em>, I will explain it I <strong><em>frequently</em></strong> use this method. Previous method is easiest method, by far, for selecting objects.</p><p>Since <code>SelectByID2</code> is updated version of <code>SelectByID</code> it has similar syntax and usage.</p><p>I will explain the use of <code>SelectByID2</code> method in 2 different scenerio as done in previous method:</p><ol><li><p>Using this method in the previous example of creating a new document and then select a Plane.</p></li><li><p>Using this method in an open document.</p></li></ol><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="using-selectbyid2-method-in-previous-example"></a>Using SelectByID2 method in previous example<a aria-hidden="true" tabindex="-1" class="hash-link" href="#using-selectbyid2-method-in-previous-example" title="Direct link to heading">#</a></h3><p>Now we use the same code and <em>extended</em> it for using selecting planes by <code>SelectByID2</code> method.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Creating string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>This method is doing the <em>same thing</em> which I already explained in the previous method. </p><p>The difference is in the <em>syntax</em> and <em>input parameters</em>.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div></div></div></div></div><p>As you can see from the above code sample, this method is a method of <code>Extension</code> interface/object.</p><p>This <code>Extension</code> interface/object is part of <code>swDoc</code> variable. This variable is the type of <code>ModelDoc2</code> interface/object.</p><p>Apart from that, we need to give additional input parameters also.</p><p>Below I have explained about the input parameters of <code>SelectByID2</code> method:</p><p><em>Name</em> : Name of the object or an empty string</p><p><em>Type</em> : Type of object in uppercase or an empty string</p><p><em>X</em> : X selection location</p><p><em>Y</em> : Y selection location</p><p><em>Z</em> : Z selection location</p><p><em>Append</em> : <code>True</code> or <code>False</code>. It is used the adding the selection into selection list.</p><p><em>Mark</em> : Value you want to use as a Mark; this value is used by other functions that require ordered selection.</p><p><em>Callout </em> : Pointer to the <code>Callout</code> interface/object. (Default value most of the time is <code>nothing</code>.)</p><p><em>SelectOption</em> : Selection option. You can use either <code>swSelectOptionDefault</code> or <code>swSelectOptionExtensive</code> value.</p><p><strong>Return Value</strong> - If the item is select then this method returns <code>True</code> and otherwise <code>False</code>.</p><p>There is <strong>a lot more</strong> about this method in the <strong><em>Remark</em></strong> section. For more information visit <a href="http://help.solidworks.com/2017/english/api/sldworksapi/solidworks.interop.sldworks~solidworks.interop.sldworks.imodeldocextension~selectbyid2.html" target="_blank" rel="noopener noreferrer">here</a>.</p><p>Since this method returns <code>True</code> or <code>False</code>, here also we use a <code>boolean</code> variable to perfom this method.</p><p>If we want to select <strong>Right Plane</strong> then we just need to replace <code>&quot;Front Plane&quot;</code> -&gt; <code>&quot;Right Plane&quot;</code> in previous code sample.</p><p>Similar for selecting <strong>Top Plane</strong>, we need to replace <code>&quot;Front Plane&quot;</code> -&gt; <code>&quot;Top Plane&quot;</code> in previous code sample.</p><hr><h3><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="using-selectbyid2-method-in-an-open-document"></a>Using SelectByID2 method in an Open document<a aria-hidden="true" tabindex="-1" class="hash-link" href="#using-selectbyid2-method-in-an-open-document" title="Direct link to heading">#</a></h3><p>For using <code>SelectByID2</code> method in an open document we use same code sample as used in previous method.</p><p>The code sample is given below:</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Boolean Variable</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim BoolStatus As Boolean</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">        </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting Solidworks document to active open document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Set swDoc = swApp.ActiveDoc</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">        </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Selecting Front Plane</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    BoolStatus = swDoc.Extension.SelectByID2(&quot;Front Plane&quot;, &quot;PLANE&quot;, 0, 0, 0, False, 0, Nothing, swSelectOption_e.swSelectOptionDefault)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>Most of the things in this code sample is already explained in <strong>(<a href="/docs/solidworks-macros/sw-macro-open-part">Solidworks Macros - Open new Part document</a>)</strong> post and in previous section of this very post.</p><p>In this code I have set the <em>Solidworks document variable</em> <code>swDoc</code> to active open document.</p><p>And then we use similar method to select <strong>&quot;Front Plane&quot;</strong>.</p><p>As explained in previous section we can select <strong>Right Plane</strong> and <strong>Top Plane</strong>.</p><p>This is all for now. This post is getting too long.</p><p>In next post we learn about <strong><em>Open Saved Documents</em></strong>.</p></div></article><div class="margin-vert--lg"><nav class="pagination-nav" aria-label="Blog list page navigation"><div class="pagination-nav__item"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-macro-open-asm-and-dwg"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Â« Open Assembly and Drawing document</div></a></div><div class="pagination-nav__item pagination-nav__item--next"><a class="pagination-nav__link" href="/docs/solidworks-macros/sw-macro-open-saved-documents"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Open Saved Documents Â»</div></a></div></nav></div></div></div><div class="col col--3"><div class="tableOfContents_3SO_"><ul class="table-of-contents table-of-contents__left-border"><li><a href="#by-selectbyid-method-from-modeldoc2-interface" class="table-of-contents__link">By <strong>SelectByID</strong> method From <strong>ModelDoc2</strong> Interface</a><ul><li><a href="#using-selectbyid-method-in-previous-example" class="table-of-contents__link">Using SelectByID method in previous example</a></li><li><a href="#using-selectbyid-method-in-an-open-document" class="table-of-contents__link">Using SelectByID method in an Open document</a></li></ul></li><li><a href="#by-selectbyid2-method-from-imodeldocextension-interface" class="table-of-contents__link">By <strong>SelectByID2</strong> method From <strong>IModelDocExtension</strong> Interface</a><ul><li><a href="#using-selectbyid2-method-in-previous-example" class="table-of-contents__link">Using SelectByID2 method in previous example</a></li><li><a href="#using-selectbyid2-method-in-an-open-document" class="table-of-contents__link">Using SelectByID2 method in an Open document</a></li></ul></li></ul></div></div></div></div></main></div></div><footer class="footer"><div class="container"><div class="row footer__links"><div class="col footer__col"><h4 class="footer__title">Tutorials</h4><ul class="footer__items"><li class="footer__item"><a class="footer__link-item" href="/docs/vba-Intro">VBA Introduction</a></li><li class="footer__item"><a class="footer__link-item" href="/docs/vba-in-sw">VBA in Solidworks</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">Community</h4><ul class="footer__items"><li class="footer__item"><a href="https://www.facebook.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Facebook</a></li><li class="footer__item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" rel="noopener noreferrer" class="footer__link-item">YouTube</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">More</h4><ul class="footer__items"><li class="footer__item"><a href="mailto:thecadcoder@gmail.com" target="_blank" rel="noopener noreferrer" class="footer__link-item">E-Mail</a></li><li class="footer__item"><a href="https://www.buymeacoffee.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Buy Me a Coffee</a></li></ul></div></div><div class="text--center"><div>Copyright Â© 2020 The Cad Coder, Inc. Built with Docusaurus.</div></div></div></footer></div>
<script src="/styles.c3633769.js"></script>
<script src="/runtime~main.4d18c882.js"></script>
<script src="/main.08717c6b.js"></script>
<script src="/1.4d0f5633.js"></script>
<script src="/2.9b374bfd.js"></script>
<script src="/94.e6f15855.js"></script>
<script src="/95.291d156d.js"></script>
<script src="/f976f453.2a96abdd.js"></script>
<script src="/17896441.b813b81e.js"></script>
<script src="/9047f1f2.513f72a7.js"></script>
</body>
</html>