<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- begin _includes/seo.html --><title>VBA Userforms - Open new Assembly and Drawing document - The CAD Coder</title>
<meta name="description" content="In this post, we learn how can we Open new Assembly and Drawing document from a Visual Basic for Application’s Userform.">



<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="VBA Userforms - Open new Assembly and Drawing document">
<meta property="og:url" content="https://thecadcoder.com//vba/open-assembly-and-drawing-from-userform/">


  <meta property="og:description" content="In this post, we learn how can we Open new Assembly and Drawing document from a Visual Basic for Application’s Userform.">







  <meta property="article:published_time" content="2022-04-21T07:33:08-04:00">






<link rel="canonical" href="https://thecadcoder.com//vba/open-assembly-and-drawing-from-userform/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": null,
      "url": "https://thecadcoder.com//"
    
  }
</script>







<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-117501871-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-117501871-2', { 'anonymize_ip': true});
</script>

<!-- end _includes/seo.html -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">
  <link
    href="/feed.xml"
    type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/main.css">

  <meta name="google-site-verification" content="OeSBbUv_kXDkDxaeoLixjE1BYxlbQRINt58H1UGbSMY" />

  
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        <img src="/assets/logo.png" width="30" height="30" class="img-fluid" alt="">
        <span>The CAD Coder</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a  class="active nav-link" style="border-bottom: 1px solid #fff;"   href="/vba/vba-Introduction/"><span>VBA</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-macro-guide/"><span>Solidworks VBA Macro</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-csharp-api-tutorials/"><span>Solidworks C# API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-cpp-api-tutorials/"><span>Solidworks C++ API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/resources/"><span>Resources</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/aboutMe/"><span>About</span></a>
            </li>
            
            <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li> -->
        </ul>
        <!-- <a class="btn btn-outline-success my-2 my-sm-0" href="/seach-document/" role="button">
            <i class="fas fa-search"></i>
        </a> -->
    </div>
</nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-sm-4">
  <div class="sidebar sticky">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">Getting Started</span>
        

        
        <ul>
          
            <li><a href="/vba/vba-Introduction/">VBA Introduction</a></li>
          
            <li><a href="/vba/vba-vbe-editor/">VBA Visual Basic Editor</a></li>
          
            <li><a href="/vba/vba-windows/">VBE Windows</a></li>
          
            <li><a href="/vba/sub-and-function-procedure/">VBA Sub and Function Procedures</a></li>
          
            <li><a href="/vba/executing-procedures/">VBA Executing Sub and Function Procedures</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Programming Concepts</span>
        

        
        <ul>
          
            <li><a href="/vba/programming-concepts/">VBA Programming Concepts, Comments and Data-types</a></li>
          
            <li><a href="/vba/variables/">VBA Variables</a></li>
          
            <li><a href="/vba/declaring-and-scoping-of-variables/">VBA Declaring and Scoping of Variables</a></li>
          
            <li><a href="/vba/variable-scope/">VBA Variable Scope</a></li>
          
            <li><a href="/vba/publc-static-variable-life/">VBA Public, Static and Variable's Life</a></li>
          
            <li><a href="/vba/constant/">VBA Constants</a></li>
          
            <li><a href="/vba/string-basic/">VBA String Basics</a></li>
          
            <li><a href="/vba/assignment-statement-and-operator/">VBA Assignment Statements And Operators</a></li>
          
            <li><a href="/vba/arrays/">VBA Arrays</a></li>
          
            <li><a href="/vba/functions/">VBA Functions</a></li>
          
            <li><a href="/vba/more-functions/">VBA Functions that do more</a></li>
          
            <li><a href="/vba/controlling-flow-making-desicions/">VBA Controlling Program Flow and Making Decisions</a></li>
          
            <li><a href="/vba/if-then-structure-select-case/">VBA If-Then-Else and Select Case structure</a></li>
          
            <li><a href="/vba/looping/">VBA Looping</a></li>
          
            <li><a href="/vba/bug-finding/">VBA Bug Finding</a></li>
          
            <li><a href="/vba/debugger/">VBA Debugger</a></li>
          
            <li><a href="/vba/bug-reduction-tips/">VBA Bug Reduction Tips</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Dialog Boxes</span>
        

        
        <ul>
          
            <li><a href="/vba/dialog-boxes/">VBA Dialog Boxes</a></li>
          
            <li><a href="/vba/msgBox-function/">VBA MsgBox Function</a></li>
          
            <li><a href="/vba/inputbox-function/">VBA InputBox Function</a></li>
          
            <li><a href="/vba/other-dialogs/">VBA GetOpenFilename, GetSaveAsFilename and Getting a Folder Name</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">UserForms</span>
        

        
        <ul>
          
            <li><a href="/vba/userform/">VBA UserForms</a></li>
          
            <li><a href="/vba/open-part-from-userform/">VBA Userforms - Open new Part document</a></li>
          
            <li><a href="/vba/open-assembly-and-drawing-from-userform/" class="active">VBA Userforms - Open new Assembly and Drawing document</a></li>
          
            <li><a href="/vba/testing-open-assembly-and-drawing-document-macro/">VBA Userforms - Testing Open new Assembly and Drawing document</a></li>
          
            <li><a href="/vba/browse-solidworks-file/">VBA Userforms - Browse SOLIDWORKS file(s)</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>

</div>
      <div class="col-md-9 col-sm-8">
        <div id="main" role="main">

  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    
    <meta itemprop="headline" content="VBA Userforms - Open new Assembly and Drawing document">
    
    <meta itemprop="description" content="In this post, we learn how can we Open new Assembly and Drawing document from a Visual Basic for Application’s Userform.">
    
    
    <meta itemprop="datePublished" content="2022-04-21T07:33:08-04:00">
    

    <div class="page__inner-wrap">
      
      <header>
        <h1 id="page-title" class="page__title" itemprop="headline">VBA Userforms - Open new Assembly and Drawing document
</h1>
        

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          7 minute read
        
      </span>
    
  </p>


      </header>
      

      <section class="page__content" itemprop="text">
        
        <aside class="sidebar__right sticky">
          <nav class="toc">
            <header>
              <h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4>
            </header>
            <ul class="toc__menu"><li><a href="#video-of-code-on-youtube">Video of Code on YouTube</a></li><li><a href="#create-a-new-macro">Create a new macro</a></li><li><a href="#insert-userform-in-the-macro">Insert userform in the macro</a></li><li><a href="#adding-controls-into-userform">Adding Controls into Userform</a><ul><li><a href="#adding-combobox">Adding ComboBox</a></li><li><a href="#adding-commandbutton">Adding CommandButton</a></li></ul></li><li><a href="#updating-properties">Updating Properties</a><ul><li><a href="#updating-properties-of-the-userform">Updating Properties of the UserForm</a></li><li><a href="#updating-properties-of-the-combobox">Updating Properties of the ComboBox</a></li><li><a href="#updating-properties-of-the-command-button">Updating Properties of the Command Button</a></li></ul></li><li><a href="#calling-userform-in-main-module">Calling UserForm in Main Module</a></li><li><a href="#adding-document-list">Adding Document list</a></li><li><a href="#first-test-of-macro">First Test of Macro</a></li><li><a href="#add-functionality-to-open-newpart-button">Add Functionality to Open NewPart Button</a></li><li><a href="#exercise-to-do">Exercise to do</a></li></ul>

            <br/>
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Vertical Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="4311368222"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          </nav>
        </aside>
        
        <div>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Horizontal Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="6007593278"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          <p>In this post, we learn how can we <strong>Open new Assembly and Drawing document</strong> from a Visual Basic for Application’s <strong>Userform</strong>.</p>

<p>For this please we need to do following steps as described below.</p>

<h2 id="video-of-code-on-youtube">Video of Code on YouTube</h2>

<p>Please see below video how visually we <em>Open new Assembly and Drawing document</em> in <strong>Solidworks VBA macro Userform</strong>.</p>

<iframe src="https://www.youtube.com/embed/AQ3Fyw78ExI" frameborder="0" allowfullscreen=""></iframe>
<p><br /></p>

<p>Please note that there are <strong>no explanation</strong> in the video.</p>

<p><strong>Explanation</strong> of each line and why we write code this way is given in this post.</p>

<h2 id="create-a-new-macro">Create a new macro</h2>

<p>1st we need to create a <strong>new macro</strong> in <em>Solidworks 3D CAD Software</em>.</p>

<p>If you don’t know how to create a new macro in Solidworks, please go to <a href="/solidworks-macros/vba-in-solidworks/">VBA in Solidworks</a> post for this.</p>

<p>This will open a new macro in Visual Basic Editor with some code as shown in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/open-new-macro.png" alt="open-new-macro" /></p>

<h2 id="insert-userform-in-the-macro">Insert userform in the macro</h2>

<p>After this we need to insert <em>a userform</em> in our macro.</p>

<p>For this, select the button shown in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/insert-userform-into-macro.png" alt="insert-userform-into-macro" /></p>

<p>This button is called <strong><em>insert userform</em></strong>.</p>

<p>As the name suggest, function of this button is <em>inserting a userform</em>.</p>

<blockquote>
  <p>Please note that in a macro we can insert any number of userform as we like. But for this example we insert only 1 userform.</p>
</blockquote>

<p>After clicking the <strong><em>insert userform</em></strong> button we get the userform window.</p>

<h2 id="adding-controls-into-userform">Adding Controls into Userform</h2>

<p>Now in our userform window, we add following controls:</p>

<ol>
  <li>
    <p><strong>A ComboBox</strong></p>
  </li>
  <li>
    <p><strong>A CommandButton</strong></p>
  </li>
</ol>

<h3 id="adding-combobox">Adding ComboBox</h3>

<p>You can find <code class="language-plaintext highlighter-rouge">ComboBox</code> option, as highlighted in <em>Red Square</em> in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/insert-combox-into-userform.png" alt="insert-combox-into-userform" /></p>

<p>After adding ComboBox, we get window as shown in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/combobox-into-userform.png" alt="combobox-into-userform" /></p>

<h3 id="adding-commandbutton">Adding CommandButton</h3>

<p>You can find <code class="language-plaintext highlighter-rouge">CommandButton</code> option, as highlighted in <em>Red Square</em> in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/insert-command-button-into-userform.png" alt="insert-command-button-into-userform" /></p>

<p>After adding CommandButton, we get window as shown in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/command-button-into-userform.png" alt="command-button-into-userform" /></p>

<h2 id="updating-properties">Updating Properties</h2>

<p>Now we update some properties of following:</p>

<ol>
  <li>
    <p><strong>UserForm</strong></p>
  </li>
  <li>
    <p><strong>ComboBox</strong></p>
  </li>
  <li>
    <p><strong>CommandButton</strong></p>
  </li>
</ol>

<h3 id="updating-properties-of-the-userform">Updating Properties of the UserForm</h3>

<p>We update following properties of the Userform:</p>

<ol>
  <li>
    <p>Name of Userform</p>
  </li>
  <li>
    <p>Caption of Userform</p>
  </li>
</ol>

<p>In below image, I have shown the properties of <code class="language-plaintext highlighter-rouge">Userform1</code> and update the properties:</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/update-userform-properties.png" alt="update-userform-properties" /></p>

<p>Update the value of <em>Name</em> property from <code class="language-plaintext highlighter-rouge">UserForm1</code> to <code class="language-plaintext highlighter-rouge">OpenDocumentWindow</code>.</p>

<ul>
  <li>From <em>Name</em> property, we access the Userform.</li>
</ul>

<p>Update the value of <em>Caption</em> property from <code class="language-plaintext highlighter-rouge">UserForm1</code> to <code class="language-plaintext highlighter-rouge">Open Document</code>.</p>

<ul>
  <li>From <em>Caption</em> property, we update the text appears in the window of our Userform.</li>
</ul>

<blockquote>
  <p>Please note that it is <strong>not necessary</strong> to update properties but it is a good habit to update them for our purpose.</p>
</blockquote>

<h3 id="updating-properties-of-the-combobox">Updating Properties of the ComboBox</h3>

<p>Now, we update following property of the ComboBox:</p>

<ol>
  <li>Name of ComboBox</li>
</ol>

<p>In below image, I have shown the properties of <code class="language-plaintext highlighter-rouge">ComboBox1</code> and update the properties:</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/update-combobox-properties.png" alt="update-combobox-properties" /></p>

<p>Update the value of <em>Name</em> property from <code class="language-plaintext highlighter-rouge">ComboBox1</code> to <code class="language-plaintext highlighter-rouge">DocumentTypeComboBox</code>.</p>

<ul>
  <li>From <em>Name</em> property, we access the ComboBox.</li>
</ul>

<h3 id="updating-properties-of-the-command-button">Updating Properties of the Command Button</h3>

<p>Now, we update following property of the Command Button:</p>

<ol>
  <li>
    <p>Name of Command Button</p>
  </li>
  <li>
    <p>Caption of Command Button</p>
  </li>
</ol>

<p>In below image, I have shown the properties of <code class="language-plaintext highlighter-rouge">CommandButton1</code> and update the properties:</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/update-command-button-properties.png" alt="update-command-button-properties" /></p>

<p>Update the value of <em>Name</em> property from <code class="language-plaintext highlighter-rouge">CommandButton1</code> to <code class="language-plaintext highlighter-rouge">OpenDocumentButton</code>.</p>

<blockquote>
  <p>From <em>Name</em> property, we access the Command Button.</p>
</blockquote>

<p>Update the value of <em>Caption</em> property from <code class="language-plaintext highlighter-rouge">CommandButton1</code> to <code class="language-plaintext highlighter-rouge">Open Selected Document</code>.</p>

<blockquote>
  <p>From <em>Caption</em> property, we update the text appears in the Command Button of our Userform.</p>
</blockquote>

<h2 id="calling-userform-in-main-module">Calling UserForm in Main Module</h2>

<p>Now, we need to call the our <em>Userform</em> inside main <strong><em>module</em></strong>.</p>

<p>For this goto main <code class="language-plaintext highlighter-rouge">Sub procedure</code> inside the <strong>main Module</strong>.</p>

<p>Code inside the main Module is as given below.</p>

<figure class="highlight"><pre><code class="language-vb" data-lang="vb"><span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="kt">Object</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

<span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="k">End</span> <span class="k">Sub</span></code></pre></figure>

<p>To call our <code class="language-plaintext highlighter-rouge">Userform</code>, replace above code with below code:</p>

<figure class="highlight"><pre><code class="language-vb" data-lang="vb"><span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>
  <span class="c1">' Calling our window to show</span>
  <span class="n">OpenDocumentWindow</span><span class="p">.</span><span class="n">Show</span>
<span class="k">End</span> <span class="k">Sub</span></code></pre></figure>

<p>Above function call our window to appears on screen.</p>

<p>When the window appears on screen, we <em>1st</em> select the document we want to <em>open</em> and <em>then</em> hit the button to open selected document.</p>

<h2 id="adding-document-list">Adding Document list</h2>

<p>Before anything we need to <em>add</em> a <em>list</em> of documents inside our combobox.</p>

<p>From this list, we select the document which we want to open.</p>

<p>In this post, we are listing only “<strong>Assembly</strong>” and “<strong>Drawing</strong>” documents.</p>

<p>For “<strong>Part</strong>” document, I will give you a simple exercise.</p>

<p>To add documents list inside our combobox, we 1st need to go in <strong>Code Window</strong> of userform.</p>

<p>For this, we need to <strong>right click</strong> on userform and select “<strong>View Code</strong>” option.</p>

<p>Please see below image for “<em>how to open code window of userform</em>”.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/select-view-code-option.png" alt="select-view-code-option" /></p>

<p>After selecting “<strong>View Code</strong>” a <em>Code window</em> appears, which is shown in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/behind-userform-code-window.png" alt="behind-userform-code-window" /></p>

<p>Now <em>before</em> adding document list we need to understand <strong>one important thing</strong>!!!</p>

<p>We want to add document list, when we <strong>load</strong> our <code class="language-plaintext highlighter-rouge">Userform</code>.</p>

<p>For this we need to create an <code class="language-plaintext highlighter-rouge">Initialize Function</code>.</p>

<p>Below <code class="language-plaintext highlighter-rouge">Code</code> is that <code class="language-plaintext highlighter-rouge">Initialize Function</code> which load document lists in our combobox.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Call when user load</span>
<span class="k">Private</span> <span class="k">Sub</span> <span class="nf">UserForm_Initialize</span><span class="p">()</span>
  <span class="c1">' Adding items in Combo Box and also set index to '0'</span>
  <span class="c1">' '0' index means by default we can see "Assembly Document" as already filled</span>
  <span class="k">With</span> <span class="n">DocumentTypeComboBox</span>
    <span class="p">.</span><span class="n">AddItem</span> <span class="s">"Assembly Document"</span>    <span class="c1">' Adding Assembly Document in Combo Box</span>
    <span class="p">.</span><span class="n">AddItem</span> <span class="s">"Drawing Document"</span>     <span class="c1">' Adding Drawing Document in Combo Box</span>
    <span class="p">.</span><span class="n">ListIndex</span> <span class="o">=</span> <span class="mi">0</span>                  <span class="c1">' Select list index for default value to show in combobox</span>
  <span class="k">End</span> <span class="k">With</span>
<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>Now, above code is <strong><em>fully commented</em></strong> and <strong><em>self explanatory</em></strong> hence I will not explain it.</p>

<h2 id="first-test-of-macro">First Test of Macro</h2>

<p>After writing code sample in previous section, we will test if every thing is working correct?</p>

<p>By working correct means:</p>

<ol>
  <li>
    <p>When we <code class="language-plaintext highlighter-rouge">Run</code> macro, is <strong>Open Document</strong> window appears or not?</p>
  </li>
  <li>
    <p>If window appears, then combobox has documents listed in it?</p>
  </li>
  <li>
    <p>If both item listed, then “<strong>Assembly document</strong>” is showing as pre-filled value or not?</p>
  </li>
  <li>
    <p>Since we have not given any functionality to “<strong>Open Document</strong>” button, hence it should not any done anything when clicking!!!</p>
  </li>
</ol>

<p>For testing all the above points we need to <code class="language-plaintext highlighter-rouge">Run</code> the macro as shown in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/first-test-of-macro.png" alt="first-test-of-macro" /></p>

<p>After running the window we got a window as shown in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/sample-userform-window.png" alt="sample-userform-window" /></p>

<p>Please <strong><em>do check</em></strong> if your macro is running perfectly till now or not!</p>

<p>If not, then I suggest you to read this article again.</p>

<h2 id="add-functionality-to-open-newpart-button">Add Functionality to Open NewPart Button</h2>

<p>To add functionality in our <code class="language-plaintext highlighter-rouge">Open Selected Button</code>, just double click the <code class="language-plaintext highlighter-rouge">Open NewPart Button</code>.</p>

<p>This will add give some code behind the designer and opens the <strong>code window</strong> of Userform designer.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Private</span> <span class="k">Sub</span> <span class="nf">OpenDocumentButton_Click</span><span class="p">()</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>We need to update this code for opening new part after clicking the button.</p>

<p>For this replace all above code with below code.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Private function of Open New Part Button </span>
<span class="k">Private</span> <span class="k">Sub</span> <span class="nf">OpenDocumentButton_Click</span><span class="p">()</span>

  <span class="c1">' Setting Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Creating string type variable for storing default Assembly location</span>
  <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
  
  <span class="k">If</span> <span class="n">DocumentTypeComboBox</span><span class="p">.</span><span class="n">Value</span> <span class="o">=</span> <span class="s">"Assembly Document"</span> <span class="k">Then</span>
    <span class="c1">' Setting value of this string type variable to "Default Assembly template"</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplateAssembly</span><span class="p">)</span>
  <span class="k">Else</span>
    <span class="c1">' Setting value of this string type variable to "Default drawing template" without define paper size</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplateDrawing</span><span class="p">)</span>
  <span class="k">End</span> <span class="k">If</span>

  <span class="c1">' Setting Solidworks document to new Assembly document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
  
  <span class="c1">' Hiding the Window after opening the selected document</span>
  <span class="n">OpenDocumentWindow</span><span class="p">.</span><span class="n">Hide</span>
  
  <span class="c1">' Reset the Index of Combo Box to "0" again</span>
  <span class="n">DocumentTypeComboBox</span><span class="p">.</span><span class="n">ListIndex</span> <span class="o">=</span> <span class="mi">0</span>
    
<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>Now I have added codes in <strong>2 parts</strong>.</p>

<p>In <strong>1st part</strong> I added below code lines <em>at top</em> of the code window.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
</code></pre></div></div>

<p>Please see below image for more reference.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/add-code-at-top-of-userform-codewindow.png" alt="add-code-at-top-of-userform-codewindow" /></p>

<p>In <strong>2nd part</strong> I added <code class="language-plaintext highlighter-rouge">OpenDocumentButton_Click</code> function in the code window as shown in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/code-when-button-clicked.png" alt="code-when-button-clicked" /></p>

<p>I have already explained code inside <code class="language-plaintext highlighter-rouge">OpenDocumentButton_Click</code> function in <a href="/solidworks-macros/open-assembly-and-drawing">Open Assembly and Drawing document</a>.</p>

<p>But here, I have added a condition which is shown in Red colored box in below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/condition-that-control-opening-document.png" alt="condition-that-control-opening-document" /></p>

<p>Basically, this condition stated that, if we select “<em>Assembly Document</em>” in combobox, then by clicking “<em>Open Select Document</em>” button our macro open “<strong>Assembly</strong>” document in <em>Solidworks</em>.</p>

<p>Otherwise, it will always open “<strong>Drawing</strong>” document in <em>Solidworks</em>.</p>

<p>The above code will <em>open New part document</em> when we click the button.</p>

<p><code class="language-plaintext highlighter-rouge">Run</code> the macro, and check wheather our macro is working correct document or not!!</p>

<p>If not, send your macro and I will guide you in doing it correctly!</p>

<h2 id="exercise-to-do">Exercise to do</h2>

<p>For those who wants to do more I have an exercise!!</p>

<ol>
  <li>
    <p>Add “<strong>Part Document</strong>” in ComboBox list.</p>
  </li>
  <li>
    <p>Make “<strong>Part Document</strong>” as <em>pre-filled</em> value in ComboBox.</p>
  </li>
  <li>
    <p>Change the <strong>conditional statement</strong>, so that it can handle <strong>all 3 conditions</strong>!!</p>
  </li>
</ol>

<p>Send me the Code of macro in my below <strong>e-mail</strong> and I will <strong><em>verify</em></strong> it.</p>

<p>That’s it for now.</p>

<p>Hope you learn some use of Userforms and by this post you can get the idea how they works.</p>

<p>I will provide more tutorials on using of Userform time to time.</p>

<p><strong><em>Till then do come to visit this blog and Happy learning!!!</em></strong></p>


        </div>
        
        <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

      </section>

      <footer class="page__meta">
        
        


        

  <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i> Updated:</strong> <time datetime="2022-04-21T07:33:08-04:00">April 21, 2022</time></p>


      </footer>

      
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    
    <li class="page-item mr-5">
      <a class="btn btn-primary text-light" href="/vba/open-part-from-userform/" title="VBA Userforms - Open new Part document
">❮ Previous</a>
    </li>
    
    
    <li class="page-item ml-5">
      <a class="btn btn-primary text-light" href="/vba/testing-open-assembly-and-drawing-document-macro/" title="VBA Userforms - Testing Open new Assembly and Drawing document
">Next ❯</a>
    </li>
    
  </ul>
</nav>

    </div>
  </article>

</div>
      </div>
    </div>
  </div>

  <div id="footer" class="page__footer">
    <footer>
      <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
      <footer class="bd-footer py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <a class="d-inline-flex align-items-center mb-2 link-dark" href="/" aria-label="Bootstrap">
          <img src="/assets/logo.png" width="30" height="30" class="img-fluid mr-2" alt="">
          <span> The CAD Coder</span>
        </a>
        <ul class="list-unstyled small text-muted">
          <li class="mb-2">Programming Tutorials for SOLIDWORKS 3D CAD Software.</li>
          <li class="mb-2">Copyright © 2022 The CAD Coder</li>
          <li class="mb-2">Built with <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a>.</li>

          
            
              
            
              
              <li class="list-inline-item"><a href="https://facebook.com/thecadcoder" target="_blank" title="Facebook"><i
                class="fab fa-2x fa-facebook-f"></i></a></li>
              
            
              
            
              
            
              
            
              
            
              
              <li class="list-inline-item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" title="YouTube"><i
                class="fab fa-2x fa-youtube"></i></a></li>
              
            
              
              <li class="list-inline-item"><a href="mailto:thecadcoder@gmail.com" target="_blank" title="Email"><i
                class="fa fa-envelope fa-2x"></i></a></li>
              
            
          
        </ul>
      </div>
      <div class="col-6">
        <h5>Links</h5>
        <ul class="list-unstyled">
          <!-- <li class="mb-2"><a href="/">Home</a></li> -->
          <li class="mb-2"><a href="/aboutMe/">About</a></li>
          <li class="mb-2"><a href="/resources/">Resources</a></li>
          <li class="mb-2"><a href="/Disclaimer/">Privacy Policy</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
    </footer>
  </div>

  
  <script src="/assets/js/main.min.js"></script>


<script>
  (function () {
    var cx = '4b2b9cb8c831ee0fb';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();

  function googleCustomSearchExecute() {
    var input = document.getElementById('cse-search-input-box-id');
    var element = google.search.cse.element.getElement('searchresults-only0');
    if (input.value == '') {
      element.clearAllResults();
    } else {
      element.execute(input.value);
    }
    return false;
  }

  
    $(document).ready(function () {
      $('input#cse-search-input-box-id').on('keyup', function () {
        googleCustomSearchExecute();
      });
    });
  
</script>







  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->

  
  <script src="/assets/js/main.min.js"></script>


<script>
  (function () {
    var cx = '4b2b9cb8c831ee0fb';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();

  function googleCustomSearchExecute() {
    var input = document.getElementById('cse-search-input-box-id');
    var element = google.search.cse.element.getElement('searchresults-only0');
    if (input.value == '') {
      element.clearAllResults();
    } else {
      element.execute(input.value);
    }
    return false;
  }

  
    $(document).ready(function () {
      $('input#cse-search-input-box-id').on('keyup', function () {
        googleCustomSearchExecute();
      });
    });
  
</script>






</body>

</html>