I"ƒ0<p>In this post, I tell you about <strong>how to Open Solidworks Part Document using Solidworks C++ API</strong> from Visual Studio.</p>

<p>I hope you have setup Visual Studio community version.</p>

<p>If not then please go to <strong><a href="/solidworks-cpp/Prerequisite/">Solidworks C++ API - Prerequisite</a></strong> post and watch the suggested videos before proceeding further.</p>

<hr />

<h2 id="video-of-code-on-youtube">Video of Code on YouTube</h2>

<p>Please see below video on <strong>how to Open Solidworks Part Document using Solidworks C++ API</strong> from Visual Studio.</p>

<iframe src="https://www.youtube.com/embed/DBESb0ZGnGc" frameborder="0" allowfullscreen=""></iframe>
<p><br /></p>

<p>Please note that there are <strong>no explaination</strong> in the video.</p>

<p><strong>Explaination</strong> of each line and why we write code this way is given in this post.</p>

<hr />

<h2 id="create-a-new-project">Create a New project</h2>

<p>Fist, we will create a new project in Visual Studio.</p>

<p>As shown in below image I have created a new project named <code class="language-plaintext highlighter-rouge">OpenPartDocument</code> in Visual Studio.</p>

<p><img src="/assets/solidworks-cpp-images/open-part-document/new-project-window.png" alt="new-project-window" /></p>

<p>If you want to know more detail for Creating a New Project in Visual Studio, please visit <strong><a href="/solidworks-cpp/open-solidworks#create-a-new-project">Create a New project</a></strong> section of <strong><a href="/solidworks-cpp/open-solidworks">Solidworks C++ API - Open Solidworks &amp; Hello World</a></strong> post.</p>

<hr />

<h2 id="add-source-file">Add Source file</h2>

<p>After creating a new project, we need to Add Source file to our project.</p>

<p>I have already explain each steps taken to create/add a ‚Äú<strong>Source.cpp</strong>‚Äù into our project in <strong><a href="/solidworks-cpp/open-solidworks#add-source-file">Add Source file</a></strong> section of <strong><a href="/solidworks-cpp/open-solidworks">Solidworks C++ API - Open Solidworks &amp; Hello World</a></strong> post.</p>

<p>This will add ‚Äú<strong>Source.cpp</strong>‚Äù file into our project.</p>

<hr />

<h2 id="add-references-to-solidworks-type-library-files">Add References to Solidworks Type Library files</h2>

<blockquote>
  <p>This section is copy/paste from <strong><a href="/solidworks-cpp/open-solidworks">Solidworks C++ API - Open Solidworks &amp; Hello World</a></strong> post.</p>
</blockquote>

<p>Now we need to <em>add References to Solidworks Type Library files.</em></p>

<p>For this please follow below steps.</p>

<ol>
  <li>
    <p>Select the <strong>OpenSolidworkTest</strong> project and and <em>Click Right Mouse Button (RMB)</em>.</p>
  </li>
  <li>
    <p>By doing this <em>a context menu</em> is appear as shown in below image.</p>
  </li>
  <li>
    <p>From this <em>context menu</em>, select <strong>‚ÄúProperties‚Äù</strong> option, which is the last one, as shown in below image.</p>
  </li>
</ol>

<p><img src="/assets/solidworks-cpp-images/open-solidworks/open-property-window.png" alt="open-property-window" /></p>

<p>This will open a new window as shown in below image.</p>

<p><img src="/assets/solidworks-cpp-images/open-solidworks/project-property-window.png" alt="project-property-window" /></p>

<p>Now following below steps:</p>

<ol>
  <li>
    <p>Select C/C++ option</p>
  </li>
  <li>
    <p>Add SOLIDWORKS folders path to 2nd Red colored box as shown in below image. Usually this path is ‚Äú<code class="language-plaintext highlighter-rouge">C:\Program Files\ Solidworks Corp\SOLIDWORKS</code>‚Äù if installed in default location.</p>
  </li>
</ol>

<p><img src="/assets/solidworks-cpp-images/open-solidworks/add-solidowrks-reference.png" alt="add-solidowrks-reference" /></p>

<p>After adding the folder path, select ‚Äú<strong>Apply</strong>‚Äù button.</p>

<p>This complete the process of <em>adding References to Solidworks Type Library files.</em></p>

<hr />

<h2 id="add-code-to-source-file">Add Code to Source file</h2>

<p>Now we need to add to <em>Source.cpp</em> file.</p>

<p>Please copy the below code sample to your <em>Source.cpp</em> file.</p>

<div class="language-c++ highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="cp">#include</span> <span class="cpf">&lt;atlbase.h&gt;</span><span class="cp">
</span>
<span class="cp">#import "sldworks.tlb" raw_interfaces_only, raw_native_types, no_namespace, named_guids  // SOLIDWORKS type library
</span>
<span class="cp">#import "swconst.tlb" raw_interfaces_only, raw_native_types, no_namespace, named_guids   // SOLIDWORKS constants type library
</span>
<span class="kt">int</span> <span class="nf">main</span><span class="p">()</span>
<span class="p">{</span>
	<span class="c1">// Initialize COM</span>
	<span class="c1">// Do this before using ATL smart pointers so COM is available.</span>
	<span class="n">CoInitialize</span><span class="p">(</span><span class="nb">NULL</span><span class="p">);</span>

	<span class="c1">// Use a block, so the smart pointers are destructed when the scope of this block is left</span>
	<span class="p">{</span>
		<span class="c1">// COM Pointer of Soldiworks object</span>
		<span class="n">CComPtr</span><span class="o">&lt;</span><span class="n">ISldWorks</span><span class="o">&gt;</span> <span class="n">swApp</span><span class="p">;</span>

		<span class="c1">// COM Pointer of Soldiworks Model Document</span>
		<span class="n">CComPtr</span><span class="o">&lt;</span><span class="n">IModelDoc2</span><span class="o">&gt;</span> <span class="n">swDoc</span><span class="p">;</span>

		<span class="c1">// Variable to check if function is </span>
		<span class="n">HRESULT</span> <span class="n">result</span> <span class="o">=</span> <span class="n">NOERROR</span><span class="p">;</span>

		<span class="c1">// COM Style String for message to user</span>
		<span class="n">CComBSTR</span> <span class="n">_messageToUser</span><span class="p">;</span>

		<span class="c1">// long type variable to store the result value by user</span>
		<span class="kt">long</span> <span class="n">_lMessageResult</span><span class="p">;</span>

		<span class="c1">// Create an instance of Solidworks application</span>
		<span class="c1">// If it fails then return 0 and close program</span>
		<span class="k">if</span> <span class="p">(</span><span class="n">swApp</span><span class="p">.</span><span class="n">CoCreateInstance</span><span class="p">(</span><span class="kr">__uuidof</span><span class="p">(</span><span class="n">SldWorks</span><span class="p">),</span> <span class="nb">NULL</span><span class="p">,</span> <span class="n">CLSCTX_LOCAL_SERVER</span><span class="p">)</span> <span class="o">!=</span> <span class="n">S_OK</span><span class="p">)</span> 
		<span class="p">{</span>
			<span class="c1">// Stop COM </span>
			<span class="n">CoUninitialize</span><span class="p">();</span>
			<span class="k">return</span><span class="p">(</span><span class="mi">0</span><span class="p">);</span>
		<span class="p">}</span>

		<span class="c1">// COM Style String to store document type</span>
		<span class="n">CComBSTR</span> <span class="n">_documentType</span><span class="p">;</span>

		<span class="c1">// Get the Default Part document</span>
		<span class="n">swApp</span><span class="o">-&gt;</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="o">::</span><span class="n">swDefaultTemplatePart</span><span class="p">,</span> <span class="o">&amp;</span><span class="n">_documentType</span><span class="p">);</span>

		<span class="c1">// Create a new Part Document </span>
		<span class="n">result</span> <span class="o">=</span> <span class="n">swApp</span><span class="o">-&gt;</span><span class="n">INewDocument2</span><span class="p">(</span><span class="n">_documentType</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="o">&amp;</span><span class="n">swDoc</span><span class="p">);</span>

		<span class="c1">// If there are no Default Part document assign then show a message to user</span>
		<span class="c1">// and Stop COM, Visible the Solidworks and return the function</span>
		<span class="k">if</span> <span class="p">(</span><span class="n">result</span> <span class="o">!=</span> <span class="n">S_OK</span><span class="p">)</span>
		<span class="p">{</span>
			<span class="c1">// COM Style String for message to user</span>
			<span class="n">_messageToUser</span> <span class="o">=</span> <span class="p">(</span><span class="s">L"Failed to open document.</span><span class="se">\n</span><span class="s">Please try again."</span><span class="p">);</span>

			<span class="c1">// Send a message to user and store the return value in _lMessageResult by referencing it</span>
			<span class="n">swApp</span><span class="o">-&gt;</span><span class="n">SendMsgToUser2</span><span class="p">(</span><span class="n">_messageToUser</span><span class="p">,</span> <span class="n">swMessageBoxIcon_e</span><span class="o">::</span><span class="n">swMbInformation</span><span class="p">,</span> <span class="n">swMessageBoxBtn_e</span><span class="o">::</span><span class="n">swMbOk</span><span class="p">,</span> <span class="o">&amp;</span><span class="n">_lMessageResult</span><span class="p">);</span>

			<span class="c1">// Visible the Solidworks</span>
			<span class="n">swApp</span><span class="o">-&gt;</span><span class="n">put_Visible</span><span class="p">(</span><span class="n">VARIANT_TRUE</span><span class="p">);</span>

			<span class="c1">// Stop COM </span>
			<span class="n">CoUninitialize</span><span class="p">();</span>
			<span class="k">return</span><span class="p">(</span><span class="mi">0</span><span class="p">);</span>
		<span class="p">}</span>

		<span class="c1">// If created successfully, then visible the Solidworks</span>
		<span class="n">swApp</span><span class="o">-&gt;</span><span class="n">put_Visible</span><span class="p">(</span><span class="n">VARIANT_TRUE</span><span class="p">);</span>
	<span class="p">}</span>

	<span class="c1">// Stop COM </span>
	<span class="n">CoUninitialize</span><span class="p">();</span>
<span class="p">}</span>
</code></pre></div></div>

<p>Now Build the Solution as shown in below image.</p>

<p><img src="/assets/solidworks-cpp-images/open-solidworks/build-solution.png" alt="build-solution" /></p>

<p>After Building Solution run the program by pressing <strong>F5</strong>.</p>

<hr />

<h2 id="final-result">Final Result</h2>

<p>After running the program wait for few minute.</p>

<p>You will get result as shown in below image!!!</p>

<p><img src="/assets/solidworks-cpp-images/open-part-document/open-part-window.png" alt="open-part-window" /></p>

<hr />

<h2 id="issues-and-solutions">Issues and Solutions</h2>

<p>There are some issues I can think of which might be come to some people.</p>

<p>Those are as follows:</p>

<p><strong>Issue 1:</strong></p>

<p>Program closed without open Solidworks!</p>

<p><strong>Solution:</strong></p>

<p>I you face this issue, then open Solidworks Manually one time, close it and then run the program.</p>

<p>It will solve this issue.</p>

<hr />

<p><strong>Issue 2:</strong></p>

<p>Program unable to create Part Document.</p>

<p><strong>Solution:</strong></p>

<p>This is a tricky one!!!</p>

<p>If you face this issue, then you need to confirm in Solidworks that you have assigned the ‚Äúdefault Part template‚Äù.</p>

<p>Please refer to below image for proper setting to fix this issue.</p>

<p><img src="/assets/solidworks-cpp-images/open-part-document/default-template-locations.png" alt="default-template-locations" /></p>

<p><strong><em>I hope this will helpful!!!</em></strong></p>

<hr />

<p><strong><em>This is it !!!</em></strong></p>

<p>We have completed our <em>Open Part Document</em> program in <em>Solidworks</em> using <strong>Solidworks C++ APIs</strong>.</p>

<p>Hope this post helps you to start with <em>Solidworks C++ API</em>.</p>

<p><em>If you like the post then please share it with your friends also.</em></p>

<p><em>Do let me know by you like this post or not! I will continue creating Solidworks C++ posts.</em></p>

<p><em>Till then, Happy learning!!!</em></p>
:ET