<!doctype html>
<!--
  Minimal Mistakes Jekyll Theme 4.21.0 by Michael Rose
  Copyright 2013-2020 Michael Rose - mademistakes.com | @mmistakes
  Free for personal and commercial use under the MIT license
  https://github.com/mmistakes/minimal-mistakes/blob/master/LICENSE
-->
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">

<!-- begin _includes/seo.html --><title>Solidworks Macro - Edit Circular Sketch Pattern - The CAD Coder</title>
<meta name="description" content="Introduction">


  <meta name="author" content="Admin">
  
  <meta property="article:author" content="Admin">
  


<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="Solidworks Macro - Edit Circular Sketch Pattern">
<meta property="og:url" content="http://localhost:4000/solidworks-macros/edit-circular-skech-pattern/">


  <meta property="og:description" content="Introduction">







  <meta property="article:published_time" content="2021-01-28T08:32:15+00:00">





  

  


<link rel="canonical" href="http://localhost:4000/solidworks-macros/edit-circular-skech-pattern/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": "Admin",
      "url": "http://localhost:4000/"
    
  }
</script>






<!-- end _includes/seo.html -->


<link href="/feed.xml" type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">

<!-- https://t.co/dKP3o1e -->
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">

<script>
  document.documentElement.className = document.documentElement.className.replace(/\bno-js\b/g, '') + ' js ';
</script>

<!-- For all browsers -->
<link rel="stylesheet" href="/assets/css/main.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">

<!--[if IE]>
  <style>
    /* old IE unsupported flexbox fixes */
    .greedy-nav .site-title {
      padding-right: 3em;
    }
    .greedy-nav button {
      position: absolute;
      top: 0;
      right: 0;
      height: 100%;
    }
  </style>
<![endif]-->



    <!-- start custom head snippets -->

<!-- insert favicons. use https://realfavicongenerator.net/ -->

<!-- end custom head snippets -->

  </head>

  <body class="layout--single">
    <nav class="skip-links">
  <h2 class="screen-reader-text">Skip links</h2>
  <ul>
    <li><a href="#site-nav" class="screen-reader-shortcut">Skip to primary navigation</a></li>
    <li><a href="#main" class="screen-reader-shortcut">Skip to content</a></li>
    <li><a href="#footer" class="screen-reader-shortcut">Skip to footer</a></li>
  </ul>
</nav>

    <!--[if lt IE 9]>
<div class="notice--danger align-center" style="margin: 0;">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience.</div>
<![endif]-->

    

<div class="masthead">
  <div class="masthead__inner-wrap">
    <div class="masthead__menu">
      <nav id="site-nav" class="greedy-nav">
        
          <a class="site-logo" href="/"><img src="/assets/logo.png" alt=""></a>
        
        <a class="site-title" href="/">
          The CAD Coder
          
        </a>
        <ul class="visible-links"><li class="masthead__menu-item">
              <a href="/vba/vba-Introduction/">VBA</a>
            </li><li class="masthead__menu-item">
              <a href="/solidworks-macros/vba-in-solidworks/">Solidworks VBA Macro</a>
            </li><li class="masthead__menu-item">
              <a href="/Solidworks-cpp-api-tutorials/">Solidworks C++ API</a>
            </li><li class="masthead__menu-item">
              <a href="/resources/">Resources</a>
            </li><li class="masthead__menu-item">
              <a href="/aboutMe/">About</a>
            </li></ul>
        
        <button class="search__toggle" type="button">
          <span class="visually-hidden">Toggle search</span>
          <svg class="icon" width="16" height="16" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15.99 16">
            <path d="M15.5,13.12L13.19,10.8a1.69,1.69,0,0,0-1.28-.55l-0.06-.06A6.5,6.5,0,0,0,5.77,0,6.5,6.5,0,0,0,2.46,11.59a6.47,6.47,0,0,0,7.74.26l0.05,0.05a1.65,1.65,0,0,0,.5,1.24l2.38,2.38A1.68,1.68,0,0,0,15.5,13.12ZM6.4,2A4.41,4.41,0,1,1,2,6.4,4.43,4.43,0,0,1,6.4,2Z" transform="translate(-.01)"></path>
          </svg>
        </button>
        
        <button class="greedy-nav__toggle hidden" type="button">
          <span class="visually-hidden">Toggle menu</span>
          <div class="navicon"></div>
        </button>
        <ul class="hidden-links hidden"></ul>
      </nav>
    </div>
  </div>
</div>


    <div class="initial-content">
      



<div id="main" role="main">
  
  <div class="sidebar sticky">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">General - Solidworks Functions</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/vba-in-solidworks/">Introduction</a></li>
          
            <li><a href="/solidworks-macros/open-new-document/">Open new Part document</a></li>
          
            <li><a href="/solidworks-macros/open-assembly-and-drawing/">Open Assembly and Drawing document</a></li>
          
            <li><a href="/solidworks-macros/select-plane-from-tree/">Selection Methods</a></li>
          
            <li><a href="/solidworks-macros/open-saved-document/">Open Saved Documents</a></li>
          
            <li><a href="/solidworks-macros/unit-correction/">Fix Unit Issue</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Lines</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/sketch-create-line/">Create Line</a></li>
          
            <li><a href="/solidworks-macros/sketch-create-centerline/">Create CenterLine</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Rectangles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-corner-rectangle/">Create Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-center-rectangle/">Create Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-corner-rectangle/">Create 3-Point Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-center-rectangle/">Create 3-Point Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-parallelogram/">Create A Parallelogram</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Circles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-circle/">Create Circle</a></li>
          
            <li><a href="/solidworks-macros/create-circle-by-radius/">Create Circle By Radius</a></li>
          
            <li><a href="/solidworks-macros/create-perimeter-circle/">Create Perimeter Circle</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Arcs</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc/">Create Centerpoint Arc</a></li>
          
            <li><a href="/solidworks-macros/create-tangent-arc/">Create Tangent Arc</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc/">Create 3-Point Arc</a></li>
          
            <li><a href="/solidworks-macros/polygon/">Create Polygon</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Slots</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-straight-slot/">Create a Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-straight-slot/">Create a Centerpoint Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc-slot/">Create a 3-Point Arc Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc-slot/">Create a Centerpoint Arc Slot</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Point and Spline</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-point/">Create a Point</a></li>
          
            <li><a href="/solidworks-macros/create-spline/">Create a Spline</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Fillet and Chamfer</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-fillet/">Create a Fillet</a></li>
          
            <li><a href="/solidworks-macros/create-chamfer/">Create a Chamfer</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Trim and Extend</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/trim-entities/">Trim Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/extend-entities/">Extend Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Patterns</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/linear-skech-pattern/">Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-linear-skech-pattern/">Edit Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/circular-skech-pattern/">Circular Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-circular-skech-pattern/" class="active">Edit Circular Sketch Pattern</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Move and Rotate</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/move-copy-sketch-entities/">Move/Copy Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/rotate-copy-sketch-entities/">Rotate/Copy Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Relations</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/toggle-display-sketch-relation/">Toggle (Hide/Show) Sketch Relations</a></li>
          
            <li><a href="/solidworks-macros/add-sketch-relations/">Add Sketch Relations (Constraints)</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Dimensions</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/add-dimension-methods/">Add dimension to Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-extrude-feature/">Extrude Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Others</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/convert-to-construction-sketch-segment/">Convert to Construction Sketch</a></li>
          
            <li><a href="/solidworks-macros/split-sketch-segments/">Split Open/Closed Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>



  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    <meta itemprop="headline" content="Solidworks Macro - Edit Circular Sketch Pattern">
    <meta itemprop="description" content="Introduction">
    
    

    <div class="page__inner-wrap">
      
        <header>
          <h1 id="page-title" class="page__title" itemprop="headline">Solidworks Macro - Edit Circular Sketch Pattern
</h1>
          

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          17 minute read
        
      </span>
    
  </p>


        </header>
      

      <section class="page__content" itemprop="text">
        
          <aside class="sidebar__right sticky">
            <nav class="toc">
              <header><h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4></header>
              <ul class="toc__menu"><li><a href="#introduction">Introduction</a></li><li><a href="#code-sample">Code Sample</a><ul><li><a href="#understanding-the-code">Understanding the Code</a></li><li><a href="#cases">Cases</a><ul><li><a href="#case-1--update-arc-radius">CASE 1 : Update Arc Radius</a></li><li><a href="#case-2--update-arc-angle">CASE 2 : Update Arc Angle</a></li><li><a href="#case-3--update-number-of-instances">CASE 3 : Update Number of Instances</a></li><li><a href="#case-4--update-pattern-spacing">CASE 4 : Update Pattern Spacing</a></li><li><a href="#case-5--update-display-rotation-of-pattern">CASE 5 : Update Display Rotation of Pattern</a></li><li><a href="#case-6--update-number-of-instances-to-delete">CASE 6 : Update Number of Instances to Delete</a></li><li><a href="#case-7--update-display-radius-dimension">CASE 7 : Update Display Radius Dimension</a></li><li><a href="#case-8--update-display-angle-dimension">CASE 8 : Update Display Angle Dimension</a></li><li><a href="#case-9--update-display-number-of-instances">CASE 9 : Update Display Number of Instances</a></li></ul></li></ul></li></ul>

            </nav>
          </aside>
        
        <h2 id="introduction">Introduction</h2>

<p>In this post, I tell you about <strong>how to Edit Circular Sketch Pattern using Solidworks VBA Macros</strong> in a Sketch.</p>

<p>In this post, I explain about <code class="language-plaintext highlighter-rouge">EditCircularSketchStepAndRepeat</code> method from <strong>Solidworks</strong> <code class="language-plaintext highlighter-rouge">SketchManager</code> object.</p>

<p>This method is <strong><em>most updated</em></strong> method, I found in <em>Solidworks API Help</em>.</p>

<p>So <strong><em>use this method</em></strong> if you want to <em>edit existing Circular Sketch Pattern</em>.</p>

<p>This post is a little different of previous <strong><a href="/solidworks-macros/Circular-skech-pattern">Solidworks Macro - Circular Sketch Pattern</a></strong> post.</p>

<p>There are 2 changes I have made, which I am going to use on future posts also.</p>

<p>These change are explain below:</p>

<ul>
  <li>
    <p>In this post I used <code class="language-plaintext highlighter-rouge">code sample</code> from <strong><a href="/solidworks-macros/unit-correction">General - Fix Unit Issue</a></strong> post to fix unit conversion issue and show how to use it.</p>
  </li>
  <li>
    <p>In input parameter of <code class="language-plaintext highlighter-rouge">EditCircularSketchStepAndRepeat</code> method, I passed variables not direct values. This helps us to maintain the code and modification of existing code is simple.</p>
  </li>
</ul>

<hr />

<h2 id="code-sample">Code Sample</h2>

<p>Below is the <code class="language-plaintext highlighter-rouge">code</code> sample to <em>edit Circular Sketch Pattern</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="c1">' Create variable for Solidworks Sketch Manager</span>
<span class="k">Dim</span> <span class="nv">swSketchManager</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchManager</span>

<span class="c1">' Create Variable for Solidworks Sketch Segment</span>
<span class="k">Dim</span> <span class="nv">swSketchSegment</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchSegment</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Create string type variable for storing default part location</span>
  <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>

  <span class="c1">' Set value of this string type variable to "Default part template"</span>
  <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>

  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
  
  <span class="c1">'-----------------------UNIT CONVERSION----------------------------------------</span>

  <span class="c1">' Local variables used as Conversion Factors</span>
  <span class="k">Dim</span> <span class="nv">LengthConversionFactor</span> <span class="ow">As</span> <span class="kt">Double</span>
  <span class="k">Dim</span> <span class="nv">AngleConversionFactor</span> <span class="ow">As</span> <span class="kt">Double</span>
  
  <span class="c1">' Use a Select Case, to get the length of active Unit and set the different factors</span>
  <span class="k">Select</span> <span class="k">Case</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">GetUnits</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>       <span class="c1">' GetUnits function gives us, active unit</span>
    
    <span class="k">Case</span> <span class="n">swMETER</span>    <span class="c1">' If length is in Meter</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span>
    
    <span class="k">Case</span> <span class="n">swMM</span>       <span class="c1">' If length is in MM</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1000</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swCM</span>       <span class="c1">' If length is in CM</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">100</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swINCHES</span>   <span class="c1">' If length is in INCHES</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.0254</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swFEET</span>     <span class="c1">' If length is in FEET</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="p">(</span><span class="mf">0.0254</span> <span class="o">*</span> <span class="mi">12</span><span class="p">)</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swFEETINCHES</span>     <span class="c1">' If length is in FEET &amp; INCHES</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.0254</span>  <span class="c1">' For length we use sama as Inch</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swANGSTROM</span>        <span class="c1">' If length is in ANGSTROM</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">10000000000</span><span class="p">#</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swNANOMETER</span>       <span class="c1">' If length is in NANOMETER</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1000000000</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swMICRON</span>       <span class="c1">' If length is in MICRON</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1000000</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
  <span class="k">End</span> <span class="k">Select</span>

  <span class="c1">'----------------------------------------------------------------</span>

  <span class="c1">' Select Front Plane</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>

  <span class="c1">' Set Sketch manager for our sketch</span>
  <span class="k">Set</span> <span class="n">swSketchManager</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span>

  <span class="c1">' Insert a sketch into selected plane</span>
  <span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
  
  <span class="c1">' Circle Radius</span>
  <span class="k">Dim</span> <span class="nv">circleRadius</span> <span class="ow">As</span> <span class="kt">Double</span>
  <span class="n">circleRadius</span> <span class="o">=</span> <span class="mi">5</span> <span class="o">*</span> <span class="n">LengthConversionFactor</span>
  
  <span class="c1">' Set Sketch Segment value and Create a Circle</span>
  <span class="k">Set</span> <span class="n">swSketchSegment</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateCircleByRadius</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">circleRadius</span><span class="p">)</span>
  
  <span class="c1">' De-select the lines after creation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>

  <span class="c1">' Select Circle we want to Pattern</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Arc1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Arc Radius</span>
  <span class="k">Dim</span> <span class="nv">arcRadius</span> <span class="ow">As</span> <span class="kt">Double</span>
  <span class="n">arcRadius</span> <span class="o">=</span> <span class="mi">10</span> <span class="o">*</span> <span class="n">LengthConversionFactor</span>
  
  <span class="c1">' Arc Angle</span>
  <span class="k">Dim</span> <span class="nv">arcAngle</span> <span class="ow">As</span> <span class="kt">Double</span>
  <span class="n">arcAngle</span> <span class="o">=</span> <span class="mi">0</span> <span class="o">*</span> <span class="n">AngleConversionFactor</span>
  
  <span class="c1">' Number of Instances</span>
  <span class="k">Dim</span> <span class="nv">numberOfInstance</span> <span class="ow">As</span> <span class="kt">Double</span>
  <span class="n">numberOfInstance</span> <span class="o">=</span> <span class="mi">3</span>
  
  <span class="c1">' Pattern Spacing</span>
  <span class="k">Dim</span> <span class="nv">patternSpacing</span> <span class="ow">As</span> <span class="kt">Double</span>
  <span class="n">patternSpacing</span> <span class="o">=</span> <span class="mi">5</span> <span class="o">*</span> <span class="n">AngleConversionFactor</span>
  
  <span class="c1">' Create a Circular Sketch Pattern</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateCircularSketchStepAndRepeat</span><span class="p">(</span><span class="n">arcRadius</span><span class="p">,</span> <span class="n">arcAngle</span><span class="p">,</span> <span class="n">numberOfInstance</span><span class="p">,</span> <span class="n">patternSpacing</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">)</span>
  
  <span class="c1">' De-select the Sketch Segment after Circular Sketch Pattern</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
  
  <span class="c1">' Update Arc Radius</span>
  <span class="n">arcRadius</span> <span class="o">=</span> <span class="mi">20</span> <span class="o">*</span> <span class="n">LengthConversionFactor</span>

  <span class="c1">' Edit a Circular Sketch Pattern</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditCircularSketchStepAndRepeat</span><span class="p">(</span><span class="n">arcRadius</span><span class="p">,</span> <span class="n">arcAngle</span><span class="p">,</span> <span class="n">numberOfInstance</span><span class="p">,</span> <span class="n">patternSpacing</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>

  <span class="c1">' Show Front View after Circular Sketch Pattern</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ShowNamedView2</span> <span class="s">""</span><span class="p">,</span> <span class="n">swStandardViews_e</span><span class="p">.</span><span class="n">swFrontView</span>
  
  <span class="c1">' Zoom to fit screen in Solidworks Window</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ViewZoomtofit2</span>
  
<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<hr />

<h3 id="understanding-the-code">Understanding the Code</h3>

<p>Now let us walk through <strong>each line</strong> in the above code, and <strong>understand</strong> the meaning and purpose of every line.</p>

<p>I also give some link so that you can go through them if there are anything I explained in <strong>previous posts</strong>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>
</code></pre></div></div>

<p>This line forces us to define every variable we are going to use.</p>

<p>For more information please visit <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
</code></pre></div></div>

<p>In this line, we create a variable which we named as <code class="language-plaintext highlighter-rouge">swApp</code> and the type of this <code class="language-plaintext highlighter-rouge">swApp</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.SldWorks</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
</code></pre></div></div>

<p>In this line, we create a variable which we named as <code class="language-plaintext highlighter-rouge">swDoc</code> and the type of this <code class="language-plaintext highlighter-rouge">swDoc</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.ModelDoc2</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>
</code></pre></div></div>

<p>In this line, we create a variable named <code class="language-plaintext highlighter-rouge">BoolStatus</code> as <code class="language-plaintext highlighter-rouge">Boolean</code> object type.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create variable for Solidworks Sketch Manager</span>
<span class="k">Dim</span> <span class="nv">swSketchManager</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchManager</span>
</code></pre></div></div>

<p>In above line, we create variable <code class="language-plaintext highlighter-rouge">swSketchManager</code> for <strong>Solidworks Sketch Manager</strong>.</p>

<p>As the name suggested, a <strong>Sketch Manager</strong> holds variours methods and properties to manage <em>Sketches</em>.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">SketchManager</code> object, please visit <strong><a href="https://help.solidworks.com/2017/english/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchManager_members.html">this page of Solidworks API Help</a></strong></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create variable for Solidworks Sketch Segment</span>
<span class="k">Dim</span> <span class="nv">swSketchSegment</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchSegment</span>
</code></pre></div></div>

<p>In this line, we Create a variable which we named as <code class="language-plaintext highlighter-rouge">swSketchSegment</code> and the type of this <code class="language-plaintext highlighter-rouge">swSketchSegment</code> variable is <code class="language-plaintext highlighter-rouge">SldWorks.SketchSegment</code>.</p>

<p>We create variable <code class="language-plaintext highlighter-rouge">swSketchSegment</code> for <strong>Solidworks Sketch Segments</strong>.</p>

<p>To see methods and properties related to <code class="language-plaintext highlighter-rouge">swSketchSegment</code> object, please visit <strong><a href="https://help.solidworks.com/2019/English/api/sldworksapi/SolidWorks.Interop.sldworks~SolidWorks.Interop.sldworks.ISketchSegment_members.html">this page of Solidworks API Help</a></strong></p>

<p>These all are our global variables.</p>

<p>As you can see in code sample, they are <strong>Solidworks API Objects</strong>.</p>

<p>So basically I group all the <strong>Solidworks API Objects</strong> in one place.</p>

<p>I have also place <code class="language-plaintext highlighter-rouge">boolean</code> type object at top also, because after certain point we will <em>need</em> this variable frequently.</p>

<p>Thus, I have started placing it here.</p>

<p>Next is our <code class="language-plaintext highlighter-rouge">Sub</code> procedure which has name of <code class="language-plaintext highlighter-rouge">main</code>.</p>

<p>This procedure hold all the <em>statements (instructions)</em> we give to computer.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Solidworks variable to Solidworks application</span>
<span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
</code></pre></div></div>

<p>In this line, we set the value of our Solidworks variable <code class="language-plaintext highlighter-rouge">swApp</code>; which we define earlier; to Solidworks application.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create string type variable for storing default part location</span>
<span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
<span class="c1">' Set value of this string type variable to "Default part template"</span>
<span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>
</code></pre></div></div>

<p>In 1st statement of above example, we are defining a variable of <code class="language-plaintext highlighter-rouge">string</code> type and named it as <code class="language-plaintext highlighter-rouge">defaultTemplate</code>.</p>

<p>This variable <code class="language-plaintext highlighter-rouge">defaultTemplate</code>, hold the location the location of <strong>Default Part Template</strong>.</p>

<p>In 2nd line of above example. we assign value to our newly define <code class="language-plaintext highlighter-rouge">defaultTemplate</code> variable.</p>

<p>We assign the value by using a <em>Method</em> named <code class="language-plaintext highlighter-rouge">GetUserPreferenceStringValue()</code>.</p>

<p>This <code class="language-plaintext highlighter-rouge">GetUserPreferenceStringValue()</code> method is a part of our main Solidworks variable <code class="language-plaintext highlighter-rouge">swApp</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Solidworks document to new part document</span>
<span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
</code></pre></div></div>

<p>In this line, we set the value of our <code class="language-plaintext highlighter-rouge">swDoc</code> variable to new document.</p>

<p>For <strong>detailed information</strong> about these lines please visit <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post.</p>

<p>I have discussed them <strong>thoroghly</strong> in <strong><a href="/solidworks-macros/open-new-document">Solidworks Macros - Open new Part document</a></strong> post, so do checkout that post if you want to understand above code in more detail.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">'-----------------------UNIT CONVERSION----------------------------------------</span>

<span class="c1">' Local variables used as Conversion Factors</span>
<span class="k">Dim</span> <span class="nv">LengthConversionFactor</span> <span class="ow">As</span> <span class="kt">Double</span>
<span class="k">Dim</span> <span class="nv">AngleConversionFactor</span> <span class="ow">As</span> <span class="kt">Double</span>

<span class="c1">' Use a Select Case, to get the length of active Unit and set the different factors</span>
<span class="k">Select</span> <span class="k">Case</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">GetUnits</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>       <span class="c1">' GetUnits function gives us, active unit</span>
  
  <span class="k">Case</span> <span class="n">swMETER</span>    <span class="c1">' If length is in Meter</span>
    <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span>
    <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span>
  
  <span class="k">Case</span> <span class="n">swMM</span>       <span class="c1">' If length is in MM</span>
    <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1000</span>
    <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
  
  <span class="k">Case</span> <span class="n">swCM</span>       <span class="c1">' If length is in CM</span>
    <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">100</span>
    <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
  
  <span class="k">Case</span> <span class="n">swINCHES</span>   <span class="c1">' If length is in INCHES</span>
    <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.0254</span>
    <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
  
  <span class="k">Case</span> <span class="n">swFEET</span>     <span class="c1">' If length is in FEET</span>
    <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="p">(</span><span class="mf">0.0254</span> <span class="o">*</span> <span class="mi">12</span><span class="p">)</span>
    <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
  
  <span class="k">Case</span> <span class="n">swFEETINCHES</span>     <span class="c1">' If length is in FEET &amp; INCHES</span>
    <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.0254</span>  <span class="c1">' For length we use sama as Inch</span>
    <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
  
  <span class="k">Case</span> <span class="n">swANGSTROM</span>        <span class="c1">' If length is in ANGSTROM</span>
    <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">10000000000</span><span class="p">#</span>
    <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
  
  <span class="k">Case</span> <span class="n">swNANOMETER</span>       <span class="c1">' If length is in NANOMETER</span>
    <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1000000000</span>
    <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
  
  <span class="k">Case</span> <span class="n">swMICRON</span>       <span class="c1">' If length is in MICRON</span>
    <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1000000</span>
    <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
<span class="k">End</span> <span class="k">Select</span>

<span class="c1">'----------------------------------------------------------------</span>
</code></pre></div></div>

<p>Above code sample shows how to <strong>fix Solidworks API Unit issue</strong>.</p>

<p>We <em>1st</em> get the <em>current unit</em> of the part and apply the <em>switch</em> statements to update our <em>Length and Angle Conversion factors</em>.</p>

<p>I have already explained in detail about <strong>Fixing Solidworks API Unit Issue</strong> in <strong><a href="/solidworks-macros/unit-correction">General - Fix Unit Issue</a></strong> blog post.</p>

<p>Do checkout above post for Fixing Solidworks API Issue.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Select Front Plane</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line, we select the <em>front plane</em> by using <code class="language-plaintext highlighter-rouge">SelectByID2</code> method from <code class="language-plaintext highlighter-rouge">Extension</code> object.</p>

<p>For more information about selection method please visit <strong><a href="/solidworks-macros/select-plane-from-tree">Solidworks Macros - Selection Methods</a></strong> post.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Sketch manager for our sketch</span>
<span class="k">Set</span> <span class="n">swSketchManager</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span>
</code></pre></div></div>

<p>In above line, we set the <em>Sketch manager</em> variable to <em>current documentâ€™s sketch manager</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Insert a sketch into selected plane</span>
<span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
</code></pre></div></div>

<p>In above line, we use <code class="language-plaintext highlighter-rouge">InsertSketch</code> method of <em>SketchManager</em> and give <code class="language-plaintext highlighter-rouge">True</code> value.</p>

<p>This method allows us to insert a sketch in selected plane.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Circle Radius</span>
<span class="k">Dim</span> <span class="nv">circleRadius</span> <span class="ow">As</span> <span class="kt">Double</span>
<span class="n">circleRadius</span> <span class="o">=</span> <span class="mi">5</span> <span class="o">*</span> <span class="n">LengthConversionFactor</span>
</code></pre></div></div>

<p>In above code sample, we do following:</p>

<ol>
  <li>
    <p>Create a local variable named <code class="language-plaintext highlighter-rouge">circleRadius</code>, which is <code class="language-plaintext highlighter-rouge">Double</code> type.</p>
  </li>
  <li>
    <p>In 2nd line, we assign a value of <strong>5</strong> to our <code class="language-plaintext highlighter-rouge">circleRadius</code> variable, also we multiple with our <code class="language-plaintext highlighter-rouge">LengthConversionFactor</code> variable.</p>
  </li>
</ol>

<p>Since I am using <em>IPS unit system</em>, I want to create a circle of Radius <em>5 inch</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Set Sketch Segment value and Create a Circle</span>
<span class="k">Set</span> <span class="n">swSketchSegment</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateCircleByRadius</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">circleRadius</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line, we set the value of Solidworks Sketch Segment variable <code class="language-plaintext highlighter-rouge">swSketchSegment</code> by <code class="language-plaintext highlighter-rouge">CreateCircleByRadius</code> method from <em>Solidworks Sketch Manager</em>.</p>

<p>This <code class="language-plaintext highlighter-rouge">CreateCircleByRadius</code> method creates <em>a Circle</em> at given point with radius.</p>

<p>For more information about <code class="language-plaintext highlighter-rouge">CreateCircleByRadius</code> method, you can read my <strong><a href="/solidworks-macros/create-circle-by-radius">Solidworks Macro - Create Circle By Radius</a></strong> post.</p>

<p>That post describe all the parameters we need for this <code class="language-plaintext highlighter-rouge">CreateCircleByRadius</code> method in details.</p>

<p>In above line, we create a Circle with:</p>

<ul>
  <li>
    <p><strong>Circle Centerpoint</strong> : At origin i.e. <em>(0, 0, 0)</em></p>
  </li>
  <li>
    <p><strong>Circle Radius</strong> : <em><code class="language-plaintext highlighter-rouge">circleRadius</code></em></p>
  </li>
</ul>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' De-select the Sketch after creation</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
</code></pre></div></div>

<p>In the above line of code, we deselect the <strong>Sketch</strong> after the <em>Circular Sketch Pattern</em> operation.</p>

<p>For de-selecting, we use <code class="language-plaintext highlighter-rouge">ClearSelection2</code> method from our Solidworks document name <code class="language-plaintext highlighter-rouge">swDoc</code>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Select Circle we want to Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Arc1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
</code></pre></div></div>

<p>In above line of code, we select the Circle i.e. <strong>Arc 1</strong> and add it to selection list.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Arc Radius</span>
<span class="k">Dim</span> <span class="nv">arcRadius</span> <span class="ow">As</span> <span class="kt">Double</span>
<span class="n">arcRadius</span> <span class="o">=</span> <span class="mi">10</span> <span class="o">*</span> <span class="n">LengthConversionFactor</span>
</code></pre></div></div>

<p>Above code sample creates a variable for <strong>Arc Radius</strong> and assign value.</p>

<p>While assigning the value we multiple with <code class="language-plaintext highlighter-rouge">LengthConversionFactor</code> to get correct length.</p>

<p>Variable Name: <code class="language-plaintext highlighter-rouge">arcRadius</code></p>

<p>Variable type: <code class="language-plaintext highlighter-rouge">Double</code></p>

<p>Variable Value: 10 inch</p>

<p><em>We want Arc Radius to 10 inch.</em></p>

<blockquote>
  <p><strong>By creating the variables we can handle the values more effciently.</strong></p>
</blockquote>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Arc Angle</span>
<span class="k">Dim</span> <span class="nv">arcAngle</span> <span class="ow">As</span> <span class="kt">Double</span>
<span class="n">arcAngle</span> <span class="o">=</span> <span class="mi">0</span> <span class="o">*</span> <span class="n">AngleConversionFactor</span>
</code></pre></div></div>

<p>Above code sample creates a variable for <strong>Arc Angle</strong> and assign value.</p>

<p>While assigning the value we multiple with <code class="language-plaintext highlighter-rouge">AngleConversionFactor</code> to get correct angle.</p>

<p>Variable Name: <code class="language-plaintext highlighter-rouge">arcAngle</code></p>

<p>Variable type: <code class="language-plaintext highlighter-rouge">Double</code></p>

<p>Variable Value: 0</p>

<p><em>We want Arc Angle to 0 degree.</em></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Number of Instances</span>
<span class="k">Dim</span> <span class="nv">numberOfInstance</span> <span class="ow">As</span> <span class="kt">Double</span>
<span class="n">numberOfInstance</span> <span class="o">=</span> <span class="mi">3</span>
</code></pre></div></div>

<p>Above code sample creates a variable for <strong>Number of Instances</strong> and assign value.</p>

<p>Variable Name: <code class="language-plaintext highlighter-rouge">numberOfInstance</code></p>

<p>Variable type: <code class="language-plaintext highlighter-rouge">Double</code></p>

<p>Variable Value: 3</p>

<p><em>We want 3 copies of the circle including the seed i.e. original circle.</em></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Pattern Spacing</span>
<span class="k">Dim</span> <span class="nv">patternSpacing</span> <span class="ow">As</span> <span class="kt">Double</span>
<span class="n">patternSpacing</span> <span class="o">=</span> <span class="mi">5</span> <span class="o">*</span> <span class="n">AngleConversionFactor</span>
</code></pre></div></div>

<p>Above code sample creates a variable for <strong>Pattern Spacing</strong> and assign value.</p>

<p>While assigning the value we multiple with <code class="language-plaintext highlighter-rouge">AngleConversionFactor</code> to get correct angle.</p>

<p>Variable Name: <code class="language-plaintext highlighter-rouge">patternSpacing</code></p>

<p>Variable type: <code class="language-plaintext highlighter-rouge">Double</code></p>

<p>Variable Value: 5</p>

<p><em>We want 5 degree of spacing between each circle.</em></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Create a Circular Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateCircularSketchStepAndRepeat</span><span class="p">(</span><span class="n">arcRadius</span><span class="p">,</span> <span class="n">arcAngle</span><span class="p">,</span> <span class="n">numberOfInstance</span><span class="p">,</span> <span class="n">patternSpacing</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">)</span>
</code></pre></div></div>

<p>In above code sample we <em>Create a Circular Sketch Pattern</em> of the selected circle by <code class="language-plaintext highlighter-rouge">CreateCircularSketchStepAndRepeat</code> method from <em>Solidworks Sketch Manger</em> variable.</p>

<p>As you can see we pass our <em>previously created variables</em> <code class="language-plaintext highlighter-rouge">arcRadius</code>, <code class="language-plaintext highlighter-rouge">arcAngle</code>, <code class="language-plaintext highlighter-rouge">numberOfInstance</code> and <code class="language-plaintext highlighter-rouge">patternSpacing</code> in <code class="language-plaintext highlighter-rouge">CreateCircularSketchStepAndRepeat</code> method as parameters.</p>

<p>I have explained <code class="language-plaintext highlighter-rouge">CreateCircularSketchStepAndRepeat</code> method in detail in <strong><a href="/solidworks-macros/circular-skech-pattern">Sketch - Circular Sketch Pattern</a></strong> post.</p>

<p>Please see above post if you want to learn more about <code class="language-plaintext highlighter-rouge">CreateCircularSketchStepAndRepeat</code> method and its parameters.</p>

<p>Below image shows Circular Sketch Pattern Parameter.</p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/before-edit-circular-pattern.png" alt="before-edit-circular-pattern" /></p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' De-select the Sketch Segment after Circular Sketch Pattern</span>
<span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
</code></pre></div></div>

<p>In above line we <em>de-select</em> the <em>Sketch Segment</em> after creating <em>Circular Sketch Pattern</em>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Update Arc Radius</span>
<span class="n">arcRadius</span> <span class="o">=</span> <span class="mi">20</span> <span class="o">*</span> <span class="n">LengthConversionFactor</span>
</code></pre></div></div>

<p>In above line we <strong>Update Arc Radius</strong> to new value which we will use in <em>Editing previously created Circular Sketch pattern</em>.</p>

<p>Variable Name: <code class="language-plaintext highlighter-rouge">arcRadius</code></p>

<p>Updated Value: 20 inch</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Circular Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditCircularSketchStepAndRepeat</span><span class="p">(</span><span class="n">arcRadius</span><span class="p">,</span> <span class="n">arcAngle</span><span class="p">,</span> <span class="n">numberOfInstance</span><span class="p">,</span> <span class="n">patternSpacing</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p>For â€œ<strong>editing</strong>â€ a Circular Sketch pattern, we need <code class="language-plaintext highlighter-rouge">EditCircularSketchStepAndRepeat</code> method from <em>Solidworks Sketch Manager</em> object/variable.</p>

<p>This <code class="language-plaintext highlighter-rouge">CreateCircularSketchStepAndRepeat</code> method takes following parameters as explained:</p>

<ul>
  <li>
    <p><strong>ArcRadius</strong> : <em>Radius for the circular sketch pattern. This value is in radian.</em></p>
  </li>
  <li>
    <p><strong>ArcAngle</strong> : <em>Angle relative to the sketch entities being patterned. This value is in radian.</em></p>
  </li>
  <li>
    <p><strong>PatternNum</strong> : <em>Total number of instances, including the seed geometry.</em></p>
  </li>
  <li>
    <p><strong>PatternSpacing</strong> : <em>Spacing between pattern instances. This value is in radian.</em></p>
  </li>
  <li>
    <p><strong>PatternRotate</strong> : <em>True to rotate the pattern, false to not.</em></p>
  </li>
  <li>
    <p><strong>DeleteInstances</strong> : <em>Number of instances to delete, passed as a string in the format: â€œ(a) (b) (c)â€.</em></p>
  </li>
  <li>
    <p><strong>RadiusDim</strong> : <em>True to display the radius dimension in the graphics area, false to not.</em></p>
  </li>
  <li>
    <p><strong>AngleDim</strong> : <em>True to display the angle dimension between axes in the graphics area, false to not.</em></p>
  </li>
  <li>
    <p><strong>CreateNumOfInstancesDim</strong> : <em>True to display the number of instances dimension in the graphics area, false to not.</em></p>
  </li>
  <li>
    <p><strong>Seed</strong>: <em>List of the names of the entities, separated by the underscore character (_), that comprise the seed pattern (e.g., Arc1_ as a seed pattern).</em></p>
  </li>
</ul>

<p><strong>NOTE:</strong> In <em>Seed</em>, adding underscore(_) after selected entity is important, otherwise code will note work.</p>

<p>After the function complete following are the results:</p>

<p><strong>Return Value</strong>:</p>

<ul>
  <li>
    <p><strong>True</strong>: <em>If Edit Circular Sketch Pattern is *Success</em>.*</p>
  </li>
  <li>
    <p><strong>False</strong>: <em>If Edit Circular Sketch Pattern is *Fail</em>.*</p>
  </li>
</ul>

<hr />

<h3 id="cases"><strong>Cases</strong></h3>

<p>In this section, we will go through different cases by</p>

<ul>
  <li>
    <p><em>Modifying different parameters</em></p>
  </li>
  <li>
    <p><em>See images, before and after parameter modification</em></p>
  </li>
</ul>

<hr />

<h4 id="case-1--update-arc-radius">CASE 1 : Update Arc Radius</h4>

<p>In our code, if we want to update Arc Radius, then we need to update <code class="language-plaintext highlighter-rouge">arcRadius</code> variable only.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Update Arc Radius</span>
<span class="n">arcRadius</span> <span class="o">=</span> <span class="mi">20</span> <span class="o">*</span> <span class="n">LengthConversionFactor</span>
</code></pre></div></div>

<p>In above line we <strong>Update Arc Radius</strong> to new value. of 20 inch.</p>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Arc Radius</strong>.</p>

<p><strong>Before Update Arc Radius</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/before-edit-circular-pattern.png" alt="before-edit-circular-pattern" /></p>

<p><strong>After Update Arc Radius</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-arc-radius.png" alt="after-update-arc-radius" /></p>

<h4 id="case-2--update-arc-angle">CASE 2 : Update Arc Angle</h4>

<p>In our code, if we want to update Arc Angle, then we need to update <code class="language-plaintext highlighter-rouge">arcAngle</code> variable only.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Update Arc Angle</span>
<span class="n">arcAngle</span> <span class="o">=</span> <span class="mi">30</span> <span class="o">*</span> <span class="n">AngleConversionFactor</span>
</code></pre></div></div>

<p>In above line we <strong>Update Arc Angle</strong> to new value of 30 inch.</p>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Arc Angle</strong>.</p>

<p><strong>Before Update Arc Angle</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-arc-radius.png" alt="after-update-arc-radius" /></p>

<p><strong>After Update Arc Angle</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-arc-angle.png" alt="after-update-arc-angle" /></p>

<h4 id="case-3--update-number-of-instances">CASE 3 : Update Number of Instances</h4>

<p>In our code, if we want to update Number of Instances, then we need to update <code class="language-plaintext highlighter-rouge">numberOfInstance</code> variable only.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Update Number of Instances</span>
<span class="n">numberOfInstance</span> <span class="o">=</span> <span class="mi">5</span>
</code></pre></div></div>

<p>In above line we <strong>Update Number of Instances</strong> to new value of 5 number of instances.</p>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Number of Instances</strong>.</p>

<p><strong>Before Update Number of Instances</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-arc-angle.png" alt="after-update-arc-angle" /></p>

<p><strong>After Update Number of Instances</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-number-of-instances.png" alt="after-update-number-of-instances" /></p>

<h4 id="case-4--update-pattern-spacing">CASE 4 : Update Pattern Spacing</h4>

<p>In our code, if we want to update Number of Instances, then we need to update <code class="language-plaintext highlighter-rouge">patternSpacing</code> variable only.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Update Pattern Spacing</span>
<span class="n">patternSpacing</span> <span class="o">=</span> <span class="mi">10</span> <span class="o">*</span> <span class="n">AngleConversionFactor</span>
</code></pre></div></div>

<p>In above line we <strong>Update Pattern Spacing</strong> to new value of 10 degree.</p>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Pattern Spacing</strong>.</p>

<p><strong>Before Update Pattern Spacing</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-number-of-instances.png" alt="after-update-number-of-instances" /></p>

<p><strong>After Update Pattern Spacing</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-pattern-spacing.png" alt="after-update-pattern-spacing" /></p>

<h4 id="case-5--update-display-rotation-of-pattern">CASE 5 : Update Display Rotation of Pattern</h4>

<p>If we want to update Display Rotation of Pattern, then we need to update value to either <code class="language-plaintext highlighter-rouge">True</code> or <code class="language-plaintext highlighter-rouge">False</code>.</p>

<p>In our code, we set this value to <code class="language-plaintext highlighter-rouge">True</code> which means we are displaying the rotation of pattern.</p>

<p>We update our code for not displaying the rotation of pattern as given in below code sample.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Circular Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditCircularSketchStepAndRepeat</span><span class="p">(</span><span class="n">arcRadius</span><span class="p">,</span> <span class="n">arcAngle</span><span class="p">,</span> <span class="n">numberOfInstance</span><span class="p">,</span> <span class="n">patternSpacing</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Display Rotation of Pattern</strong>.</p>

<p><strong>Before Update Display Rotation of Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-pattern-spacing.png" alt="after-update-pattern-spacing" /></p>

<p><strong>After Update Display Rotation of Pattern</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-rotation-of-pattern.png" alt="after-update-rotation-of-pattern" /></p>

<h4 id="case-6--update-number-of-instances-to-delete">CASE 6 : Update Number of Instances to Delete</h4>

<p>If we want to update Number of Instances to Delete, then we need to update value of <code class="language-plaintext highlighter-rouge">""</code> as given in below code sample.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Circular Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditCircularSketchStepAndRepeat</span><span class="p">(</span><span class="n">arcRadius</span><span class="p">,</span> <span class="n">arcAngle</span><span class="p">,</span> <span class="n">numberOfInstance</span><span class="p">,</span> <span class="n">patternSpacing</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"(3)"</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p>In above code sample, we want to delete 3rd instance hence we pass the number <strong><code class="language-plaintext highlighter-rouge">3</code></strong> inside <strong><code class="language-plaintext highlighter-rouge">()</code></strong>.</p>

<blockquote>
  <p><strong>Note: For delete any instance we need to pass its position in paranthesis (). Otherwise it wonâ€™t work.</strong></p>
</blockquote>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Number of Instances to Delete</strong>.</p>

<p><strong>Before Update Number of Instances to Delete</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-pattern-spacing.png" alt="after-update-pattern-spacing" /></p>

<p><strong>After Update Number of Instances to Delete</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-number-of-instance-to-delete.png" alt="after-update-number-of-instance-to-delete" /></p>

<h4 id="case-7--update-display-radius-dimension">CASE 7 : Update Display Radius Dimension</h4>

<p>If we want to update Display Radius Dimension, then we need to update value to either <code class="language-plaintext highlighter-rouge">True</code> or <code class="language-plaintext highlighter-rouge">False</code>.</p>

<p>In our code, we set this value to <code class="language-plaintext highlighter-rouge">True</code> which means we are displaying the Display Radius Dimension.</p>

<p>We update our code for not displaying the Display Radius Dimension as given in below code sample.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Circular Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditCircularSketchStepAndRepeat</span><span class="p">(</span><span class="n">arcRadius</span><span class="p">,</span> <span class="n">arcAngle</span><span class="p">,</span> <span class="n">numberOfInstance</span><span class="p">,</span> <span class="n">patternSpacing</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"(3)"</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Display Radius Dimension</strong>.</p>

<p><strong>Before Update Display Radius Dimension</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-number-of-instance-to-delete.png" alt="after-update-number-of-instance-to-delete" /></p>

<p><strong>After Update Display Radius Dimension</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-display-radius-dimension.png" alt="after-update-display-radius-dimension" /></p>

<h4 id="case-8--update-display-angle-dimension">CASE 8 : Update Display Angle Dimension</h4>

<p>If we want to update Display Angle Dimension, then we need to update value to either <code class="language-plaintext highlighter-rouge">True</code> or <code class="language-plaintext highlighter-rouge">False</code>.</p>

<p>In our code, we set this value to <code class="language-plaintext highlighter-rouge">True</code> which means we are displaying the Display Angle Dimension.</p>

<p>We update our code for not displaying the Display Angle Dimension as given in below code sample.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Circular Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditCircularSketchStepAndRepeat</span><span class="p">(</span><span class="n">arcRadius</span><span class="p">,</span> <span class="n">arcAngle</span><span class="p">,</span> <span class="n">numberOfInstance</span><span class="p">,</span> <span class="n">patternSpacing</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"(3)"</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Display Angle Dimension</strong>.</p>

<p><strong>Before Update Display Angle Dimension</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-number-of-instance-to-delete.png" alt="after-update-number-of-instance-to-delete" /></p>

<p><strong>After Update Display Angle Dimension</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-display-angle-dimension.png" alt="after-update-display-angle-dimension" /></p>

<h4 id="case-9--update-display-number-of-instances">CASE 9 : Update Display Number of Instances</h4>

<p>If we want to update Display Number of Instances, then we need to update value to either <code class="language-plaintext highlighter-rouge">True</code> or <code class="language-plaintext highlighter-rouge">False</code>.</p>

<p>In our code, we set this value to <code class="language-plaintext highlighter-rouge">True</code> which means we are displaying the Display Number of Instances.</p>

<p>We update our code for not displaying the Display Number of Instances as given in below code sample.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Edit a Circular Sketch Pattern</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">EditCircularSketchStepAndRepeat</span><span class="p">(</span><span class="n">arcRadius</span><span class="p">,</span> <span class="n">arcAngle</span><span class="p">,</span> <span class="n">numberOfInstance</span><span class="p">,</span> <span class="n">patternSpacing</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"(3)"</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="s">"Arc1_"</span><span class="p">)</span>
</code></pre></div></div>

<p><strong><em>Example Images:</em></strong></p>

<p>Below image shows before and after we update <strong>Display Number of Instances</strong>.</p>

<p><strong>Before Update Display Number of Instances</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-number-of-instance-to-delete.png" alt="after-update-number-of-instance-to-delete" /></p>

<p><strong>After Update Display Number of Instances</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-patterns/after-update-display-number-of-instance.png" alt="after-update-display-number-of-instance" /></p>

<hr />

<p><strong>This is it !!!</strong></p>

<p><em>It is indeed a very LONG post. But I try to update the code and move into the direction where we were able to use these code samples in UserForms.</em></p>

<p><em>I hope you like my effort!!!</em></p>

<p>If you found anything to add or update, please let me know on my e-mail.</p>

<p>Hope this post helps you to <em>Edit a Circular Sketch Pattern</em> with Solidworks VBA Macros.</p>

<p>For more such tutorials on <strong>Solidworks VBA Macro</strong>, do come to this blog after sometime.</p>

<p><em>If you like the post then please share it with your friends also.</em></p>

<p><em>Do let me know by you like this post or not!</em></p>

<p><em>Till then, Happy learning!!!</em></p>

        
      </section>

      <footer class="page__meta">
        
        
  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-tags" aria-hidden="true"></i> Tags: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/tags/#solidworks-macro" class="page__taxonomy-item" rel="tag">Solidworks Macro</a>
    
    </span>
  </p>




  


  
  
  

  <p class="page__taxonomy">
    <strong><i class="fas fa-fw fa-folder-open" aria-hidden="true"></i> Categories: </strong>
    <span itemprop="keywords">
    
      
      
      <a href="/categories/#solidworks-macro" class="page__taxonomy-item" rel="tag">Solidworks-macro</a>
    
    </span>
  </p>


        

      </footer>

      <section class="page__share">
  

  <a href="https://twitter.com/intent/tweet?text=Solidworks+Macro+-+Edit+Circular+Sketch+Pattern%20http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fedit-circular-skech-pattern%2F" class="btn btn--twitter" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Twitter"><i class="fab fa-fw fa-twitter" aria-hidden="true"></i><span> Twitter</span></a>

  <a href="https://www.facebook.com/sharer/sharer.php?u=http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fedit-circular-skech-pattern%2F" class="btn btn--facebook" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on Facebook"><i class="fab fa-fw fa-facebook" aria-hidden="true"></i><span> Facebook</span></a>

  <a href="https://www.linkedin.com/shareArticle?mini=true&url=http%3A%2F%2Flocalhost%3A4000%2Fsolidworks-macros%2Fedit-circular-skech-pattern%2F" class="btn btn--linkedin" onclick="window.open(this.href, 'window', 'left=20,top=20,width=500,height=500,toolbar=1,resizable=0'); return false;" title="Share on LinkedIn"><i class="fab fa-fw fa-linkedin" aria-hidden="true"></i><span> LinkedIn</span></a>
</section>



      
  <nav class="pagination">
    
      <a href="/solidworks-macros/circular-skech-pattern/" class="pagination--pager" title="Solidworks Macro - Circular Sketch Pattern
">Previous</a>
    
    
      <a href="/solidworks-macros/move-copy-sketch-entities/" class="pagination--pager" title="Solidworks Macro - Move/Copy Sketch Entities
">Next</a>
    
  </nav>

    </div>

    
  </article>

  
  
    <div class="page__related">
      <h4 class="page__related-title">You May Also Enjoy</h4>
      <div class="grid__wrapper">
        
      </div>
    </div>
  
  
</div>

    </div>

    
      <div class="search-content">
        <div class="search-content__inner-wrap"><form onsubmit="return googleCustomSearchExecute();" id="cse-search-box-form-id">
    <label class="sr-only" for="cse-search-input-box-id">
      Enter your search term...
    </label>
    <input type="search" id="cse-search-input-box-id" class="search-input" tabindex="-1" placeholder="Enter your search term..." />
  </form>
  <div id="results" class="results">
    <gcse:searchresults-only></gcse:searchresults-only>
  </div></div>

      </div>
    

    <div id="footer" class="page__footer">
      <footer>
        <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
        <div class="page__footer-follow">
  <ul class="social-icons">
    

    
      
        
      
        
          <li><a href="https://facebook.com/thecadcoder" rel="nofollow noopener noreferrer"><i class="fab fa-fw fa-facebook-square" aria-hidden="true"></i> Facebook</a></li>
        
      
        
      
        
      
        
      
        
      
        
          <li><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" rel="nofollow noopener noreferrer"><i class="fab fa-youtube" aria-hidden="true"></i> YouTube</a></li>
        
      
        
          <li><a href="mailto:thecadcoder@gmail.com" rel="nofollow noopener noreferrer"><i class="fas fa-fw fa-envelope-square" aria-hidden="true"></i> Email</a></li>
        
      
    

    <li><a href="/feed.xml"><i class="fas fa-fw fa-rss-square" aria-hidden="true"></i> Feed</a></li>
  </ul>
</div>

<div class="page__footer-copyright">&copy; 2021 Admin. Powered by <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a> &amp; <a href="https://mademistakes.com/work/minimal-mistakes-jekyll-theme/" rel="nofollow">Minimal Mistakes</a>. | <strong><a href="http://localhost:4000/Disclaimer/" rel="nofollow"><i class="fas fa-lock" aria-hidden="true"></i> Privacy Policy</a></strong></div>

      </footer>
    </div>

    
  <script src="/assets/js/main.min.js"></script>


<script>
  (function () {
    var cx = '4b2b9cb8c831ee0fb';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();

  function googleCustomSearchExecute() {
    var input = document.getElementById('cse-search-input-box-id');
    var element = google.search.cse.element.getElement('searchresults-only0');
    if (input.value == '') {
      element.clearAllResults();
    } else {
      element.execute(input.value);
    }
    return false;
  }

  
    $(document).ready(function () {
      $('input#cse-search-input-box-id').on('keyup', function () {
        googleCustomSearchExecute();
      });
    });
  
</script>







    <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>


  </body>
</html>
