I"Ð9<p>In this post, I tell you how to <em>open a saved document</em> in Solidworks using <em>VBA Macro</em>.</p>

<p>We open document with 2 different methods.</p>

<ol>
  <li>
    <p>By <code class="language-plaintext highlighter-rouge">OpenDoc</code> method</p>
  </li>
  <li>
    <p>By <code class="language-plaintext highlighter-rouge">OpenDoc6</code> method</p>
  </li>
</ol>

<h2 id="video-of-code-on-youtube">Video of Code on YouTube</h2>

<p>Please see below video on <strong>how to Open Saved Documents</strong> from Visual Studio.</p>

<iframe src="https://www.youtube.com/embed/DeltLKXAIjY" frameborder="0" allowfullscreen=""></iframe>
<p><br /></p>

<p>Please note that there are <strong>no explaination</strong> in the video.</p>

<p><strong>Explaination</strong> of each line and why we write code this way is given in this post.</p>

<h2 id="by-opendoc-method">By OpenDoc method</h2>

<p>This is <strong>the simplest</strong> method to open a saved part from your computer.</p>

<p>In this method we just need two information.</p>

<ul>
  <li>
    <p>Location of document to open</p>
  </li>
  <li>
    <p>Type of document which we want to open</p>
  </li>
</ul>

<p>Below is the example code for opening a saved document using <code class="language-plaintext highlighter-rouge">OpenDoc</code> method.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>


<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Setting Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
      
  <span class="c1">' Open a saved document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">OpenDoc</span><span class="p">(</span><span class="s">"H:\Solidworks studies\API Studies\Chapter 1 - The Basics\1st example part.SLDPRT"</span><span class="p">,</span> <span class="n">swDocumentTypes_e</span><span class="p">.</span><span class="n">swDocPART</span><span class="p">)</span>
      
  <span class="c1">' Selecting Front Plane</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SelectByID</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>I have already explained every line except <em>middle line</em> in above code sample in previous posts.</p>

<p>To open a saved document we used following lline.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Open a saved document</span>
<span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">OpenDoc</span><span class="p">(</span><span class="s">"H:\Solidworks studies\API Studies\Chapter 1 - The Basics\1st example part.SLDPRT"</span><span class="p">,</span> <span class="n">swDocumentTypes_e</span><span class="p">.</span><span class="n">swDocPART</span><span class="p">)</span>
</code></pre></div></div>

<p>Here, we set the <code class="language-plaintext highlighter-rouge">ModelDoc2</code> variable <code class="language-plaintext highlighter-rouge">swDoc</code> to a value.</p>

<p>This value is <em>return</em> or <em>provided</em> by <code class="language-plaintext highlighter-rouge">OpenDoc</code> method.</p>

<p>This method is part of <em>Solidworks document</em>.</p>

<p>Since we define <code class="language-plaintext highlighter-rouge">swApp</code> variable as Solidworks document hence we 1st call <code class="language-plaintext highlighter-rouge">swApp</code> and then using <code class="language-plaintext highlighter-rouge">Dot operator</code> we access the <code class="language-plaintext highlighter-rouge">OpenDoc</code> method.</p>

<p><code class="language-plaintext highlighter-rouge">OpenDoc</code> method takes 2 <em>arguments</em> or <em>parameter</em>.</p>

<p><em>FileName</em> : Document name or full path if not in current directory, including extension.</p>

<p><em>Type</em> : Document type as define in <code class="language-plaintext highlighter-rouge">swDocumentTypes_e</code> as follows.</p>

<ul>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocASSEMBLY</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocDRAWING</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocLAYOUT</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocNONE</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocPART</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocSDM</code></p>
  </li>
</ul>

<blockquote>
  <p>If you want to open a Library feature part then we use <code class="language-plaintext highlighter-rouge">swDocPART</code> as document type.</p>
</blockquote>

<p><strong>Return Value</strong> - If the document opens then this method returns <code class="language-plaintext highlighter-rouge">True</code> and otherwise <code class="language-plaintext highlighter-rouge">False</code>.</p>

<p>If you just want to open a saved document then this method is what you are looking for.</p>

<p>For most of the part, <code class="language-plaintext highlighter-rouge">OpenDoc</code> method works well.</p>

<p>If you want more option while opening a document, then next method is for you.</p>

<hr />

<h2 id="by-opendoc6-method">By OpenDoc6 method</h2>

<p><code class="language-plaintext highlighter-rouge">OpenDoc6</code> method is extension to <code class="language-plaintext highlighter-rouge">OpenDoc</code> with some additional parameters.</p>

<p>How <code class="language-plaintext highlighter-rouge">OpenDoc6</code> works is shown in below code sample:</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>
<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>


<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

    <span class="c1">' Setting Solidworks variable to Solidworks application</span>
    <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
        
    <span class="c1">' Open an saved document</span>
    <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">OpenDoc6</span><span class="p">(</span><span class="s">"H:\Solidworks studies\API Studies\Chapter 1 - The Basics\1st example part.SLDPRT"</span><span class="p">,</span> <span class="n">swDocumentTypes_e</span><span class="p">.</span><span class="n">swDocPART</span><span class="p">,</span> <span class="n">swOpenDocOptions_e</span><span class="p">.</span><span class="n">swOpenDocOptions_Silent</span><span class="p">,</span> <span class="s">""</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
        
    <span class="c1">' Selecting Front Plane</span>
    <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SelectByID</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>

<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<p>This code sample is similar is to previous example code except for <code class="language-plaintext highlighter-rouge">OpenDoc6</code> method takes extra 4 parameters.</p>

<p><code class="language-plaintext highlighter-rouge">OpenDoc6</code> method takes 6 <em>arguments</em> or <em>parameter</em>.</p>

<p><em>FileName</em> : Document name or full path if not in current directory, including extension.</p>

<p><em>Type</em> : Document type as define in <code class="language-plaintext highlighter-rouge">swDocumentTypes_e</code> as follows.</p>

<ul>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocASSEMBLY</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocDRAWING</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocLAYOUT</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocNONE</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocPART</code></p>
  </li>
  <li>
    <p><code class="language-plaintext highlighter-rouge">swDocSDM</code></p>
  </li>
</ul>

<blockquote>
  <p>If you want to open a Library feature part then we use <code class="language-plaintext highlighter-rouge">swDocPART</code> as document type.</p>
</blockquote>

<p><em>Options</em> : Mode in which to open the document as defined in <code class="language-plaintext highlighter-rouge">swOpenDocOptions_e</code>.</p>

<p>For more details about <em>Options</em> parameters, please visit <strong><a href="https://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swOpenDocOptions_e.html">this page of Solidworks API Help</a></strong>.</p>

<p><em>Configuration</em> : Configuration in which you want to open this document.</p>

<ul>
  <li>
    <p>Applies to <em>Part</em> and <em>Assemblies</em>, not <em>drawings</em>.</p>
  </li>
  <li>
    <p>If this argument is <em>empty</em> or the specified configuration is <em>not present</em> in the model, the model is opened in the last-used configuration.</p>
  </li>
</ul>

<p>I used an <code class="language-plaintext highlighter-rouge">""</code> in the above code sample, because I want to open part file in last saved configuration.</p>

<p>If you donât know about <code class="language-plaintext highlighter-rouge">""</code>, then this symbol represent an <strong>empty string</strong>.</p>

<p>When we donât want to pass any value as <code class="language-plaintext highlighter-rouge">string</code>, at that time I use <code class="language-plaintext highlighter-rouge">""</code>.</p>

<p>You can also use <code class="language-plaintext highlighter-rouge">""</code> when you want to pass an empty string in VBA.</p>

<p><em>Errors</em> : Load errors as defined in <code class="language-plaintext highlighter-rouge">swFileLoadError_e</code>.</p>

<p>For more details about <em>Errors</em> parameters, please visit <strong><a href="http://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swFileLoadError_e.html">this page of Solidworks API Help</a></strong>.</p>

<p>Since this parameter is <code class="language-plaintext highlighter-rouge">long</code> type, and I donât want to enter any value from the provided list; I used <strong>0</strong> as value.</p>

<p>If you want to use options from option link then you can use values from there.</p>

<p>It is just I donât want to load any error information about the part.</p>

<p><em>Warnings</em> : Warnings or extra information generated during the open operation as defined in <code class="language-plaintext highlighter-rouge">swFileLoadWarning_e</code>.</p>

<p>For more details about <em>Warnings</em> parameters, please visit <strong><a href="http://help.solidworks.com/2017/english/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swFileLoadWarning_e.html">this page of Solidworks API Help</a>.</strong></p>

<p>As in the previous parameter, I use <strong>0</strong> as value.</p>

<p><strong>Return Value</strong> - If the document opens then this method returns <code class="language-plaintext highlighter-rouge">True</code> and otherwise <code class="language-plaintext highlighter-rouge">False</code>.</p>

<p>As you can see, in <code class="language-plaintext highlighter-rouge">OpenDoc6</code> method, we need to defined the extra parameters compared to <code class="language-plaintext highlighter-rouge">OpenDoc</code> method.</p>

<p>It is worth noted that, <code class="language-plaintext highlighter-rouge">OpenDoc6</code> method is the most updated method for opening a saved document.</p>

<p>Hence if did not use any of the above method, I would recommend you to use <code class="language-plaintext highlighter-rouge">OpenDoc6</code> method.</p>

<p>Hope this post helps you to understand opening methods with Solidworks VB Macros.</p>

<p>For more such tutorials on Solidworks VBA Macros, do come to this blog after sometime.</p>

<p>Till then, Happy learning!!!</p>

:ET