<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- begin _includes/seo.html --><title>Solidworks Macro - Toggle (Hide/Show) Sketch Relations - The CAD Coder</title>
<meta name="description" content="In this post, I tell you about how to Toggle (Hide/Show) Sketch Relations using Solidworks VBA Macros in a Sketch.">



<meta property="og:type" content="article">
<meta property="og:locale" content="en_US">
<meta property="og:site_name" content="The CAD Coder">
<meta property="og:title" content="Solidworks Macro - Toggle (Hide/Show) Sketch Relations">
<meta property="og:url" content="https://thecadcoder.com//solidworks-macros/toggle-display-sketch-relation/">


  <meta property="og:description" content="In this post, I tell you about how to Toggle (Hide/Show) Sketch Relations using Solidworks VBA Macros in a Sketch.">







  <meta property="article:published_time" content="2022-05-25T01:28:57-04:00">






<link rel="canonical" href="https://thecadcoder.com//solidworks-macros/toggle-display-sketch-relation/">




<script type="application/ld+json">
  {
    "@context": "https://schema.org",
    
      "@type": "Person",
      "name": null,
      "url": "https://thecadcoder.com//"
    
  }
</script>







<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-117501871-2"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-117501871-2', { 'anonymize_ip': true});
</script>

<!-- end _includes/seo.html -->

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
    integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/logo.png">
  <link
    href="/feed.xml"
    type="application/atom+xml" rel="alternate" title="The CAD Coder Feed">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5/css/all.min.css">
  <link rel="stylesheet" href="/assets/css/main.css">

  <meta name="google-site-verification" content="OeSBbUv_kXDkDxaeoLixjE1BYxlbQRINt58H1UGbSMY" />

  
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/">
        <img src="/assets/logo.png" width="30" height="30" class="img-fluid" alt="">
        <span>The CAD Coder</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a  class="nav-link"   href="/vba/vba-Introduction/"><span>VBA</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="active nav-link" style="border-bottom: 1px solid #fff;"   href="/Solidworks-macro-guide/"><span>Solidworks VBA Macro</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-csharp-api-tutorials/"><span>Solidworks C# API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/Solidworks-cpp-api-tutorials/"><span>Solidworks C++ API</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/resources/"><span>Resources</span></a>
            </li>
            
            
            <li class="nav-item">
                <a  class="nav-link"   href="/aboutMe/"><span>About</span></a>
            </li>
            
            <!-- <li class="nav-item">
                <a class="nav-link disabled">Disabled</a>
            </li> -->
        </ul>
        <!-- <a class="btn btn-outline-success my-2 my-sm-0" href="/seach-document/" role="button">
            <i class="fas fa-search"></i>
        </a> -->
    </div>
</nav>

  <div class="container-fluid">
    <div class="row">
      <div class="col-md-3 col-sm-4">
  <div class="sidebar sticky">
  
  
    
      
      
      
      
    
    
      

<nav class="nav__list">
  
  <input id="ac-toc" name="accordion-toc" type="checkbox" />
  <label for="ac-toc">Toggle Menu</label>
  <ul class="nav__items">
    
      <li>
        
          <span class="nav__sub-title">General - Solidworks Functions</span>
        

        
        <ul>
          
            <li><a href="/Solidworks-macro-guide/">Introduction</a></li>
          
            <li><a href="/solidworks-macros/open-new-document/">Open new Part document</a></li>
          
            <li><a href="/solidworks-macros/open-assembly-and-drawing/">Open Assembly and Drawing document</a></li>
          
            <li><a href="/solidworks-macros/select-plane-from-tree/">Selection Methods</a></li>
          
            <li><a href="/solidworks-macros/open-saved-document/">Open Saved Documents</a></li>
          
            <li><a href="/solidworks-macros/unit-correction/">Fix Unit Issue</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Lines</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/sketch-create-line/">Create Line</a></li>
          
            <li><a href="/solidworks-macros/sketch-create-centerline/">Create CenterLine</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Rectangles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-corner-rectangle/">Create Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-center-rectangle/">Create Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-corner-rectangle/">Create 3-Point Corner Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-3point-center-rectangle/">Create 3-Point Center Rectangle</a></li>
          
            <li><a href="/solidworks-macros/create-parallelogram/">Create A Parallelogram</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Circles</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-circle/">Create Circle</a></li>
          
            <li><a href="/solidworks-macros/create-circle-by-radius/">Create Circle By Radius</a></li>
          
            <li><a href="/solidworks-macros/create-perimeter-circle/">Create Perimeter Circle</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Arcs</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc/">Create Centerpoint Arc</a></li>
          
            <li><a href="/solidworks-macros/create-tangent-arc/">Create Tangent Arc</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc/">Create 3-Point Arc</a></li>
          
            <li><a href="/solidworks-macros/polygon/">Create Polygon</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Slots</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-straight-slot/">Create a Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-straight-slot/">Create a Centerpoint Straight Slot</a></li>
          
            <li><a href="/solidworks-macros/create-3point-arc-slot/">Create a 3-Point Arc Slot</a></li>
          
            <li><a href="/solidworks-macros/create-centerpoint-arc-slot/">Create a Centerpoint Arc Slot</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Point and Spline</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-point/">Create a Point</a></li>
          
            <li><a href="/solidworks-macros/create-spline/">Create a Spline</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Fillet and Chamfer</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-sketch-fillet/">Create a Fillet</a></li>
          
            <li><a href="/solidworks-macros/create-sketch-chamfer/">Create a Chamfer</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Trim and Extend</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/trim-entities/">Trim Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/extend-entities/">Extend Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Offset and Mirror</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/offset-entities/">Offset Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/mirror-entities/">Mirror Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Patterns</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/linear-skech-pattern/">Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-linear-skech-pattern/">Edit Linear Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/circular-skech-pattern/">Circular Sketch Pattern</a></li>
          
            <li><a href="/solidworks-macros/edit-circular-skech-pattern/">Edit Circular Sketch Pattern</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Move and Rotate</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/move-copy-sketch-entities/">Move/Copy Sketch Entities</a></li>
          
            <li><a href="/solidworks-macros/rotate-copy-sketch-entities/">Rotate/Copy Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Relations</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/toggle-display-sketch-relation/" class="active">Toggle (Hide/Show) Sketch Relations</a></li>
          
            <li><a href="/solidworks-macros/add-sketch-relations/">Add Sketch Relations (Constraints)</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Dimensions</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/add-dimension-methods/">Add dimension to Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Extrudes</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-extrude-feature/">Extrude Feature</a></li>
          
            <li><a href="/solidworks-macros/create-revolved-feature/">Revolved Boss/Base Feature</a></li>
          
            <li><a href="/solidworks-macros/create-sweep-feature/">Sweep Boss/Base Feature</a></li>
          
            <li><a href="/solidworks-macros/create-lofted-boss-feature/">Lofted Boss/Base Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Cuts</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-extrude-cut-feature/">Extrude Cut Feature</a></li>
          
            <li><a href="/solidworks-macros/create-revolve-cut-feature/">Revolve Cut Feature</a></li>
          
            <li><a href="/solidworks-macros/create-sweep-cut-feature/">Sweep Cut Feature</a></li>
          
            <li><a href="/solidworks-macros/create-loft-cut-feature/">Lofted Cut Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Holes and Threads</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-hole-from-hole-wizard/">Holes from Hole Wizard</a></li>
          
            <li><a href="/solidworks-macros/create-threads/">Threads</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Fillet & Chamfer</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-fillet/">Fillet Feature</a></li>
          
            <li><a href="/solidworks-macros/create-chamfer/">Chamfer Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Mirror & Patterns</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/create-mirror/">Mirror Feature</a></li>
          
            <li><a href="/solidworks-macros/create-linear-patterns/">Linear Pattern Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-circular-patterns/">Circular Pattern Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-sketch-driven-pattern/">Sketch Driven Pattern Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Features - Transformation</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/create-rib/">Rib Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-draft/">Draft Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-shell/">Shell Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-wrap/">Wrap Feature</a></li>
          
            <li><a href="/solidworks-vba-macros/create-scale/">Scale Feature</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Reference Geometry</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/create-reference-plane/">Reference Plane</a></li>
          
            <li><a href="/solidworks-vba-macros/create-reference-axis/">Reference Axis</a></li>
          
            <li><a href="/solidworks-vba-macros/create-reference-coordinate/">Reference Co-Ordinate</a></li>
          
            <li><a href="/solidworks-vba-macros/create-reference-point/">Reference Point</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Assembly - General</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/assembly-insert-component/">Insert Component</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-unfix-component/">Unfix Component</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Assembly - Standard Mates</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/assembly-conicident-mate/">Add Coincident Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-parallel-mate/">Add Parallel Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-perpendicular-mate/">Add Perpendicular Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-tangent-mate/">Add Tangent Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-concentric-mate/">Add Concentric Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-distance-mate/">Add Distance Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-angle-mate/">Add Angle Mate</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Assembly - Advanced Mates</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/assembly-width-mate/">Add Width Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-symmetric-mate/">Add Symmetric Mate</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Assembly - Editing Mates</span>
        

        
        <ul>
          
            <li><a href="/solidworks-vba-macros/assembly-rename-mate/">Rename Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-edit-distance-mate/">Edit Distance Mate</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-toggle-mate-alignment/">Toggle Mate Alignment</a></li>
          
            <li><a href="/solidworks-vba-macros/assembly-delete-mate/">Delete Mate</a></li>
          
        </ul>
        
      </li>
    
      <li>
        
          <span class="nav__sub-title">Sketch - Others</span>
        

        
        <ul>
          
            <li><a href="/solidworks-macros/convert-to-construction-sketch-segment/">Convert to Construction Sketch</a></li>
          
            <li><a href="/solidworks-macros/split-sketch-segments/">Split Open/Closed Sketch Entities</a></li>
          
        </ul>
        
      </li>
    
  </ul>
</nav>

    
  
  </div>

</div>
      <div class="col-md-9 col-sm-8">
        <div id="main" role="main">

  <article class="page" itemscope itemtype="https://schema.org/CreativeWork">
    
    <meta itemprop="headline" content="Solidworks Macro - Toggle (Hide/Show) Sketch Relations">
    
    <meta itemprop="description" content="In this post, I tell you about how to Toggle (Hide/Show) Sketch Relations using Solidworks VBA Macros in a Sketch.">
    
    
    <meta itemprop="datePublished" content="2022-05-25T01:28:57-04:00">
    

    <div class="page__inner-wrap">
      
      <header>
        <h1 id="page-title" class="page__title" itemprop="headline">Solidworks Macro - Toggle (Hide/Show) Sketch Relations
</h1>
        

  <p class="page__meta">
    

    

    
      
      

      <span class="page__meta-readtime">
        <i class="far fa-clock" aria-hidden="true"></i>
        
          4 minute read
        
      </span>
    
  </p>


      </header>
      

      <section class="page__content" itemprop="text">
        
        <aside class="sidebar__right sticky">
          <nav class="toc">
            <header>
              <h4 class="nav__title"><i class="fas fa-file-alt"></i> On this page</h4>
            </header>
            <ul class="toc__menu"><li><a href="#video-of-code-on-youtube">Video of Code on YouTube</a></li><li><a href="#code-sample">Code Sample</a></li><li><a href="#understanding-the-code">Understanding the Code</a></li></ul>

            <br/>
            <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Vertical Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="4311368222"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          </nav>
        </aside>
        
        <div>
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-8158659264340002"
     crossorigin="anonymous"></script>
<!-- Horizontal Ads -->
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-8158659264340002"
     data-ad-slot="6007593278"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
          <p>In this post, I tell you about <strong>how to Toggle (Hide/Show) Sketch Relations using Solidworks VBA Macros</strong> in a Sketch.</p>

<p>This post is extension to <strong><em><a href="/solidworks-macros/rotate-copy-sketch-entities">Sketch Transformation - Rotate/Copy Sketch Entities</a></em></strong> post.</p>

<p>Hence I will explained only <strong><em>Toggle (Hide/Show) Sketch Relations</em></strong> related code.</p>

<p>In this post, I explain about <code class="language-plaintext highlighter-rouge">SetUserPreferenceToggle</code> method from <strong>Solidworks</strong>’s <code class="language-plaintext highlighter-rouge">ModelDoc2</code> object.</p>

<p>This method is <strong><em>NOT updated</em></strong> method, but it is easiest way to <strong><em>Toggle (Hide/Show) Sketch Relations</em></strong>.</p>

<hr />

<h2 id="video-of-code-on-youtube">Video of Code on YouTube</h2>

<p>Please see below video on <strong>how to Toggle (Hide/Show) Sketch Relations</strong> from Solidworks VBA Macros.</p>

<iframe src="https://www.youtube.com/embed/9Ck6iPY_4gs" frameborder="0" allowfullscreen=""></iframe>
<p><br /></p>

<p>Please note that there are <strong>no explaination</strong> in the video.</p>

<p><strong>Explaination</strong> of each line and why we write code this way is given in this post.</p>

<hr />

<h2 id="code-sample">Code Sample</h2>

<p>Below is the <code class="language-plaintext highlighter-rouge">code</code> sample to <strong><em>Toggle (Hide/Show) Sketch Relations</em></strong>.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Create variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>

<span class="c1">' Create variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Boolean Variable</span>
<span class="k">Dim</span> <span class="nv">BoolStatus</span> <span class="ow">As</span> <span class="kt">Boolean</span>

<span class="c1">' Create variable for Solidworks Sketch Manager</span>
<span class="k">Dim</span> <span class="nv">swSketchManager</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchManager</span>

<span class="c1">' Create Variable for Solidworks Sketch Segment</span>
<span class="k">Dim</span> <span class="nv">swSketchSegment</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SketchSegment</span>

<span class="c1">' Main function of our VBA program</span>
<span class="k">Sub</span> <span class="nf">main</span><span class="p">()</span>

  <span class="c1">' Set Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Create string type variable for storing default part location</span>
  <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>

  <span class="c1">' Set value of this string type variable to "Default part template"</span>
  <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplatePart</span><span class="p">)</span>

  <span class="c1">' Set Solidworks document to new part document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
  
  <span class="c1">'-----------------------UNIT CONVERSION----------------------------------------</span>

  <span class="c1">' Local variables used as Conversion Factors</span>
  <span class="k">Dim</span> <span class="nv">LengthConversionFactor</span> <span class="ow">As</span> <span class="kt">Double</span>
  <span class="k">Dim</span> <span class="nv">AngleConversionFactor</span> <span class="ow">As</span> <span class="kt">Double</span>
  
  <span class="c1">' Use a Select Case, to get the length of active Unit and set the different factors</span>
  <span class="k">Select</span> <span class="k">Case</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">GetUnits</span><span class="p">(</span><span class="mi">0</span><span class="p">)</span>       <span class="c1">' GetUnits function gives us, active unit</span>
    
    <span class="k">Case</span> <span class="n">swMETER</span>    <span class="c1">' If length is in Meter</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span>
    
    <span class="k">Case</span> <span class="n">swMM</span>       <span class="c1">' If length is in MM</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1000</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swCM</span>       <span class="c1">' If length is in CM</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">100</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swINCHES</span>   <span class="c1">' If length is in INCHES</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.0254</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swFEET</span>     <span class="c1">' If length is in FEET</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="p">(</span><span class="mf">0.0254</span> <span class="o">*</span> <span class="mi">12</span><span class="p">)</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swFEETINCHES</span>     <span class="c1">' If length is in FEET &amp; INCHES</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.0254</span>  <span class="c1">' For length we use sama as Inch</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swANGSTROM</span>        <span class="c1">' If length is in ANGSTROM</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">10000000000</span><span class="p">#</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swNANOMETER</span>       <span class="c1">' If length is in NANOMETER</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1000000000</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
    
    <span class="k">Case</span> <span class="n">swMICRON</span>       <span class="c1">' If length is in MICRON</span>
      <span class="n">LengthConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">/</span> <span class="mi">1000000</span>
      <span class="n">AngleConversionFactor</span> <span class="o">=</span> <span class="mi">1</span> <span class="o">*</span> <span class="mf">0.01745329</span>
  <span class="k">End</span> <span class="k">Select</span>

  <span class="c1">'----------------------------------------------------------------</span>

  <span class="c1">' Select Front Plane</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Front Plane"</span><span class="p">,</span> <span class="s">"PLANE"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">False</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>

  <span class="c1">' Set Sketch manager for our sketch</span>
  <span class="k">Set</span> <span class="n">swSketchManager</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SketchManager</span>

  <span class="c1">' Insert a sketch into selected plane</span>
  <span class="n">swSketchManager</span><span class="p">.</span><span class="n">InsertSketch</span> <span class="k">True</span>
  
  <span class="c1">' Create a local variable for CenterPoint ractangle</span>
  <span class="k">Dim</span> <span class="nv">vSketch</span> <span class="ow">As</span> <span class="kt">Variant</span>
  
  <span class="c1">' Create CenterPoint ractangle</span>
  <span class="n">vSketch</span> <span class="o">=</span> <span class="n">swSketchManager</span><span class="p">.</span><span class="n">CreateCenterRectangle</span><span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span> <span class="o">*</span> <span class="n">LengthConversionFactor</span><span class="p">,</span> <span class="mi">1</span> <span class="o">*</span> <span class="n">LengthConversionFactor</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
    
  <span class="c1">' De-select the lines after creation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
  
  <span class="c1">' Select all lines of CenterPoint Ractangle</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line1"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line2"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line3"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">SelectByID2</span><span class="p">(</span><span class="s">"Line4"</span><span class="p">,</span> <span class="s">"SKETCHSEGMENT"</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="k">Nothing</span><span class="p">,</span> <span class="n">swSelectOption_e</span><span class="p">.</span><span class="n">swSelectOptionDefault</span><span class="p">)</span>
  
  <span class="c1">' Rotate CenterPoint Ractangle by 45 degree only</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">Extension</span><span class="p">.</span><span class="n">RotateOrCopy</span> <span class="k">True</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="k">True</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">1</span><span class="p">,</span> <span class="mi">45</span> <span class="o">*</span> <span class="n">AngleConversionFactor</span>
  
  <span class="c1">' Toggle (Hide/Show) Sketch Relations</span>
  <span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SetUserPreferenceToggle</span><span class="p">(</span><span class="n">swUserPreferenceToggle_e</span><span class="p">.</span><span class="n">swViewSketchRelations</span><span class="p">,</span> <span class="k">True</span><span class="p">)</span>
  
  <span class="c1">' De-select all after creation</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ClearSelection2</span> <span class="k">True</span>
  
  <span class="c1">' Show Front View after Circular Sketch Pattern</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ShowNamedView2</span> <span class="s">""</span><span class="p">,</span> <span class="n">swStandardViews_e</span><span class="p">.</span><span class="n">swFrontView</span>
  
  <span class="c1">' Zoom to fit screen in Solidworks Window</span>
  <span class="n">swDoc</span><span class="p">.</span><span class="n">ViewZoomtofit2</span>
  
<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<hr />

<h2 id="understanding-the-code">Understanding the Code</h2>

<p>I have already discuss above code in previous <strong><em><a href="/solidworks-macros/rotate-copy-sketch-entities">Sketch Transformation - Rotate/Copy Sketch Entities</a></em></strong> post except below line of code.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Toggle (Hide/Show) Sketch Relations</span>
<span class="n">BoolStatus</span> <span class="o">=</span> <span class="n">swDoc</span><span class="p">.</span><span class="n">SetUserPreferenceToggle</span><span class="p">(</span><span class="n">swUserPreferenceToggle_e</span><span class="p">.</span><span class="n">swViewSketchRelations</span><span class="p">,</span> <span class="k">True</span><span class="p">)</span>
</code></pre></div></div>

<p>For “<strong>Toggle (Hide/Show)</strong>”  Sketch Relations, we need <code class="language-plaintext highlighter-rouge">SetUserPreferenceToggle</code> method from <strong>Solidworks</strong>’s <code class="language-plaintext highlighter-rouge">ModelDoc2</code> object.</p>

<p>This <code class="language-plaintext highlighter-rouge">SetUserPreferenceToggle</code> method takes following parameters as explained:</p>

<ul>
  <li><strong>UserPreferenceValue</strong> : <em>Use Preference Values to toggle as defined in <code class="language-plaintext highlighter-rouge">swUserPreferenceToggle_e</code>.</em></li>
</ul>

<blockquote>
  <p>NOTE: <code class="language-plaintext highlighter-rouge">swUserPreferenceToggle_e</code> has many values!!!  Hence it is not possible to list all of them here. If you want to check full list, please visit <strong><a href="https://help.solidworks.com/2020/English/api/swconst/SOLIDWORKS.Interop.swconst~SOLIDWORKS.Interop.swconst.swUserPreferenceToggle_e.html">this page of Solidworks API Help</a></strong>.</p>
</blockquote>

<ul>
  <li><strong>OnFlag</strong> : <em>True to toggle the value on, false to toggle the value off.</em></li>
</ul>

<p>In our code, we used following values:</p>

<ul>
  <li>
    <p><strong>UserPreferenceValue</strong> : <em><code class="language-plaintext highlighter-rouge">swUserPreferenceToggle_e.swViewSketchRelations</code></em></p>
  </li>
  <li>
    <p><strong>OnFlag</strong> : <em><code class="language-plaintext highlighter-rouge">True</code></em></p>
  </li>
</ul>

<p><strong>Return Value</strong>:</p>

<ul>
  <li>
    <p><strong>True</strong>: <em>If Toggle (Hide/Show) of Sketch Relations is <strong>Success</strong>.</em></p>
  </li>
  <li>
    <p><strong>False</strong>: <em>If Toggle (Hide/Show) of Sketch Relations is <strong>Fail</strong>.</em></p>
  </li>
</ul>

<p><strong>Before Toggle (Hide/Show) of Sketch Relations</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/before-toggle-sketch-relation.png" alt="before-toggle-sketch-relation" /></p>

<p><strong>After Toggle (Hide/Show) of Sketch Relations</strong></p>

<p><img src="/assets/Solidworks_Images/sketch-relations/after-toggle-sketch-relation.png" alt="after-toggle-sketch-relation" /></p>

<hr />

<p><strong>This is it !!!</strong></p>

<p><em>I hope my efforts will helpful to someone!</em></p>

<p>If you found anything to <strong>add or update</strong>, please let me know on my <em>e-mail</em>.</p>

<p>Hope this post helps you to <strong><em>Toggle (Hide/Show) of Sketch Relations</em></strong> with Solidworks VBA Macros.</p>

<p>For more such tutorials on <strong>Solidworks VBA Macro</strong>, do come to this blog after sometime.</p>

<p><em>If you like the post then please share it with your friends also.</em></p>

<p><em>Do let me know by you like this post or not!</em></p>

<p><em>Till then, Happy learning!!!</em></p>

        </div>
        
        <div>
  <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  <!-- Top and Bottom placed Ad -->
  <ins class="adsbygoogle"
       style="display:block"
       data-ad-client="ca-pub-8158659264340002"
       data-ad-slot="6644001766"
       data-ad-format="auto"
       data-full-width-responsive="true"></ins>
  <script>
       (adsbygoogle = window.adsbygoogle || []).push({});
  </script>
</div>

      </section>

      <footer class="page__meta">
        
        


        

  <p class="page__date"><strong><i class="fas fa-fw fa-calendar-alt" aria-hidden="true"></i> Updated:</strong> <time datetime="2022-05-25T01:28:57-04:00">May 25, 2022</time></p>


      </footer>

      
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    
    <li class="page-item mr-5">
      <a class="btn btn-primary text-light" href="/solidworks-macros/rotate-copy-sketch-entities/" title="Solidworks Macro - Rotate/Copy Sketch Entities
">❮ Previous</a>
    </li>
    
    
    <li class="page-item ml-5">
      <a class="btn btn-primary text-light" href="/solidworks-macros/add-sketch-relations/" title="Solidworks Macro - Add Sketch Relations (Constraints)
">Next ❯</a>
    </li>
    
  </ul>
</nav>

    </div>
  </article>

</div>
      </div>
    </div>
  </div>

  <div id="footer" class="page__footer">
    <footer>
      <!-- start custom footer snippets -->

<!-- end custom footer snippets -->
      <footer class="bd-footer py-5 bg-light">
  <div class="container">
    <div class="row">
      <div class="col-6">
        <a class="d-inline-flex align-items-center mb-2 link-dark" href="/" aria-label="Bootstrap">
          <img src="/assets/logo.png" width="30" height="30" class="img-fluid mr-2" alt="">
          <span> The CAD Coder</span>
        </a>
        <ul class="list-unstyled small text-muted">
          <li class="mb-2">Programming Tutorials for SOLIDWORKS 3D CAD Software.</li>
          <li class="mb-2">Copyright © 2022 The CAD Coder</li>
          <li class="mb-2">Built with <a href="https://jekyllrb.com" rel="nofollow">Jekyll</a>.</li>

          
            
              
            
              
              <li class="list-inline-item"><a href="https://facebook.com/thecadcoder" target="_blank" title="Facebook"><i
                class="fab fa-2x fa-facebook-f"></i></a></li>
              
            
              
            
              
            
              
            
              
            
              
              <li class="list-inline-item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" title="YouTube"><i
                class="fab fa-2x fa-youtube"></i></a></li>
              
            
              
              <li class="list-inline-item"><a href="mailto:thecadcoder@gmail.com" target="_blank" title="Email"><i
                class="fa fa-envelope fa-2x"></i></a></li>
              
            
          
        </ul>
      </div>
      <div class="col-6">
        <h5>Links</h5>
        <ul class="list-unstyled">
          <!-- <li class="mb-2"><a href="/">Home</a></li> -->
          <li class="mb-2"><a href="/aboutMe/">About</a></li>
          <li class="mb-2"><a href="/resources/">Resources</a></li>
          <li class="mb-2"><a href="/Disclaimer/">Privacy Policy</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
    </footer>
  </div>

  
  <script src="/assets/js/main.min.js"></script>


<script>
  (function () {
    var cx = '4b2b9cb8c831ee0fb';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();

  function googleCustomSearchExecute() {
    var input = document.getElementById('cse-search-input-box-id');
    var element = google.search.cse.element.getElement('searchresults-only0');
    if (input.value == '') {
      element.clearAllResults();
    } else {
      element.execute(input.value);
    }
    return false;
  }

  
    $(document).ready(function () {
      $('input#cse-search-input-box-id').on('keyup', function () {
        googleCustomSearchExecute();
      });
    });
  
</script>







  <!-- Optional JavaScript; choose one of the two! -->

  <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF"
    crossorigin="anonymous"></script>

  <!-- Option 2: Separate Popper and Bootstrap JS -->
  <!--
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js" integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2" crossorigin="anonymous"></script>
    -->

  
  <script src="/assets/js/main.min.js"></script>


<script>
  (function () {
    var cx = '4b2b9cb8c831ee0fb';
    var gcse = document.createElement('script');
    gcse.type = 'text/javascript';
    gcse.async = true;
    gcse.src = 'https://cse.google.com/cse.js?cx=' + cx;
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(gcse, s);
  })();

  function googleCustomSearchExecute() {
    var input = document.getElementById('cse-search-input-box-id');
    var element = google.search.cse.element.getElement('searchresults-only0');
    if (input.value == '') {
      element.clearAllResults();
    } else {
      element.execute(input.value);
    }
    return false;
  }

  
    $(document).ready(function () {
      $('input#cse-search-input-box-id').on('keyup', function () {
        googleCustomSearchExecute();
      });
    });
  
</script>






</body>

</html>