<!doctype html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="generator" content="Docusaurus v2.0.0-alpha.66">
<link rel="preconnect" href="https://www.google-analytics.com">
<script>window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)},ga.l=+new Date,ga("create","UA-117501871-2","auto"),ga("set","anonymizeIp",!0),ga("send","pageview")</script>
<script async src="https://www.google-analytics.com/analytics.js"></script><title data-react-helmet="true">Open new Part document | The Cad Coder</title><meta data-react-helmet="true" name="twitter:card" content="summary_large_image"><meta data-react-helmet="true" name="docusaurus_language" content="en"><meta data-react-helmet="true" name="docusaurus_version" content="current"><meta data-react-helmet="true" name="docusaurus_tag" content="docs-default-current"><meta data-react-helmet="true" property="og:title" content="Open new Part document | The Cad Coder"><meta data-react-helmet="true" name="description" content="In this post, we learn how can we open a part document from a Visual Basic for Application&#x27;s Userform."><meta data-react-helmet="true" property="og:description" content="In this post, we learn how can we open a part document from a Visual Basic for Application&#x27;s Userform."><meta data-react-helmet="true" property="og:url" content="https://prashantbaher.github.io//docs/vba-userform/vba-userforms-open-part"><link data-react-helmet="true" rel="shortcut icon" href="/img/logo_icon.ico"><link data-react-helmet="true" rel="canonical" href="https://prashantbaher.github.io//docs/vba-userform/vba-userforms-open-part"><link rel="stylesheet" href="/styles.aba4c036.css">
<link rel="preload" href="/styles.49bb2333.js" as="script">
<link rel="preload" href="/runtime~main.ab11de34.js" as="script">
<link rel="preload" href="/main.e8afb781.js" as="script">
<link rel="preload" href="/1.ccf2966d.js" as="script">
<link rel="preload" href="/2.ea84abb6.js" as="script">
<link rel="preload" href="/94.6ee319b8.js" as="script">
<link rel="preload" href="/95.e3f7e856.js" as="script">
<link rel="preload" href="/f976f453.85830ae4.js" as="script">
<link rel="preload" href="/17896441.7cfb19b7.js" as="script">
<link rel="preload" href="/27d0949a.b40297e0.js" as="script">
</head>
<body>
<script>!function(){function t(t){document.documentElement.setAttribute("data-theme",t)}var e=function(){var t=null;try{t=localStorage.getItem("theme")}catch(t){}return t}();t(null!==e?e:"light")}()</script><div id="__docusaurus">
<nav class="navbar navbar--fixed-top"><div class="navbar__inner"><div class="navbar__items"><div aria-label="Navigation bar toggle" class="navbar__toggle" role="button" tabindex="0"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 30 30" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></div><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a><div class="navbar__item dropdown dropdown--hoverable dropdown--left"><a class="navbar__item navbar__link">VBA</a><ul class="dropdown__menu"><li><a class="dropdown__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li><a class="dropdown__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></div><a class="navbar__item navbar__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a><a class="navbar__item navbar__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></div><div class="navbar__items navbar__items--right"><div class="navbar__item dropdown dropdown--hoverable dropdown--right"><a class="navbar__item navbar__link">About</a><ul class="dropdown__menu"><li><a class="dropdown__link" position="right" href="/docs/about">About Me</a></li><li><a class="dropdown__link" position="right" href="/docs/resources">Resources</a></li><li><a class="dropdown__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></div><div class="react-toggle react-toggle--disabled displayOnlyInLargeViewport_2aTZ"><div class="react-toggle-track"><div class="react-toggle-track-check"><span class="toggle_BsTx">ðŸŒœ</span></div><div class="react-toggle-track-x"><span class="toggle_BsTx">ðŸŒž</span></div></div><div class="react-toggle-thumb"></div><input type="checkbox" disabled="" aria-label="Dark mode toggle" class="react-toggle-screenreader-only"></div></div></div><div role="presentation" class="navbar-sidebar__backdrop"></div><div class="navbar-sidebar"><div class="navbar-sidebar__brand"><a class="navbar__brand" href="/"><img class="navbar__logo" src="/img/logo.png" alt="My Site Logo"><strong class="navbar__title">The Cad Coder</strong></a></div><div class="navbar-sidebar__items"><div class="menu"><ul class="menu__list"><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">VBA</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" href="/docs/vba-Intro">VBA Tutorials</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-userforms">VBA UserForms</a></li></ul></li><li class="menu__list-item"><a class="menu__link" href="/docs/vba-in-sw">SOLIDWORKS VBA</a></li><li class="menu__list-item"><a class="menu__link" href="/docs/sw-cpp">SOLIDWORKS C++</a></li><li class="menu__list-item menu__list-item--collapsed"><a role="button" class="menu__link menu__link--sublist">About</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/about">About Me</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/resources">Resources</a></li><li class="menu__list-item"><a class="menu__link" position="right" href="/docs/privacy">Privacy Policy</a></li></ul></li></ul></div></div></div></nav><div class="main-wrapper"><div class="docPage_2gpo"><div class="docSidebarContainer_3_JD" role="complementary"><div class="sidebar_2urC"><div class="menu menu--responsive menu_5FrY"><button aria-label="Open Menu" aria-haspopup="true" class="button button--secondary button--sm menu__button" type="button"><svg aria-label="Menu" class="sidebarMenuIcon_Dm3K" xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 32 32" role="img" focusable="false"><title>Menu</title><path stroke="currentColor" stroke-linecap="round" stroke-miterlimit="10" stroke-width="2" d="M4 7h22M4 15h22M4 23h22"></path></svg></button><ul class="menu__list"><li class="menu__list-item"><a class="menu__link menu__link--sublist menu__link--active" href="#!">Introduction</a><ul class="menu__list"><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-userforms">VBA UserForms</a></li><li class="menu__list-item"><a aria-current="page" class="menu__link menu__link--active active" tabindex="0" href="/docs/vba-userform/vba-userforms-open-part">Open new Part document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-userform/vba-userforms-open--ass-doc">Open new Assembly and Drawing document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-userform/vba-userforms-open-part-test">Testing Open new Assembly and Drawing document</a></li><li class="menu__list-item"><a class="menu__link" tabindex="0" href="/docs/vba-userform/vba-userforms-browse-files">Browse SOLIDWORKS file(s)</a></li></ul></li></ul></div></div></div><main class="docMainContainer_3EyW"><div class="container padding-vert--lg docItemWrapper_1EkI"><div class="row"><div class="col docItemCol_2ASc"><div class="docItemContainer_3QWW"><article><header><h1 class="docTitle_1Lrw">Open new Part document</h1></header><div class="markdown"><p>In this post, we learn how can we <em>open a part document</em> from a Visual Basic for Application&#x27;s <em>Userform</em>.</p><p>For this please we need to do following steps as described below.</p><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="video-of-code-on-youtube"></a>Video of Code on YouTube<a aria-hidden="true" tabindex="-1" class="hash-link" href="#video-of-code-on-youtube" title="Direct link to heading">#</a></h2><p>Please see below video on <strong>Solidworks VBA Macro - Open new Part document</strong> in Solidwoks VBA Userforms.</p><div class="youtube-responsive-container"><iframe src="https://www.youtube.com/embed/pXMMSDeXEwo" frameborder="0"></iframe></div><p>Please note that there are <strong>no explaination</strong> in the video. </p><p><strong>Explaination</strong> of each line and why we write code this way is given in this post.</p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="create-a-new-macro"></a>Create a new macro<a aria-hidden="true" tabindex="-1" class="hash-link" href="#create-a-new-macro" title="Direct link to heading">#</a></h2><p>1st we need to create a <strong>new macro</strong> in <em>Solidworks 3D CAD Software</em>.</p><p>If you don&#x27;t know how to create a new macro in Solidworks, please go to <a href="/docs/vba-in-sw">VBA in Solidworks</a> post for this.</p><p>This will open a new macro in Visual Basic Editor with some code as shown in below image.</p><p><img alt="new_macro_window" src="/assets/images/1.new_macro_window-e509af3a79274952a24b6d2119d99e21.PNG"> </p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="insert-userform-in-the-macro"></a>Insert userform in the macro<a aria-hidden="true" tabindex="-1" class="hash-link" href="#insert-userform-in-the-macro" title="Direct link to heading">#</a></h2><p>After this we need to insert a userform in our macro.</p><p>For this, select the button shown in below image.</p><p><img alt="insert-userform-button" src="/assets/images/2.insert-userform-button-47db25e07f07365b98475369da9afeee.png"></p><p>This button is called <strong><em>insert userform</em></strong>. </p><p>As the name suggest, function of this button is <em>inserting a userform</em>.</p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>Please note that in a macro we can insert any number of userform as we like. But for this example we insert only 1 userform.</p></div></div><p>After clicking the <strong><em>insert userform</em></strong> button we get the userform window as shown in below image.</p><p><img alt="userform-window" src="/assets/images/3.userform-window-03cf1994dcb9990c02e86a0fb1c6060a.PNG"></p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="adding-a-button"></a>Adding a Button<a aria-hidden="true" tabindex="-1" class="hash-link" href="#adding-a-button" title="Direct link to heading">#</a></h2><p>Now in our userform window, we add a <code>Command Button</code> at center of window.</p><p>You can find <code>Command Button</code> highlighted in red in below image.</p><p><img alt="add-command-buton" src="/assets/images/4.add-command-button-576696f3adf8e3ed08b321a1fcbbe484.png"></p><p>You can place command button at your desire. I placed it at center of the userform window as shown in below image.</p><p><img alt="userform-window-after-adding-command-button" src="/assets/images/5.userform-window-after-adding-command-button-dd99e79f6a219247ac8fd27575b230dd.PNG"></p><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="updating-properties-of-command-button-and-userform-windows"></a>Updating Properties of Command Button and Userform Windows<a aria-hidden="true" tabindex="-1" class="hash-link" href="#updating-properties-of-command-button-and-userform-windows" title="Direct link to heading">#</a></h2><p>Now we update some properties of Command Button and Userform Windows for our use.</p><div class="admonition admonition-tip alert alert--success"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="12" height="16" viewBox="0 0 12 16"><path fill-rule="evenodd" d="M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"></path></svg></span>tip</h5></div><div class="admonition-content"><p>It is not necessary to update properties but it is a good habit to update them for our purpose. </p></div></div><p>1st we update the properties of Userform.</p><p>In below image, I have shown the properties of <code>Userform1</code> and update following properties:</p><ol><li><p>Name of Userform</p></li><li><p>Caption of Userform</p></li></ol><p><img alt="properties-to-change-in-userform" src="/assets/images/6.properties-to-change-in-userform-583a8eedc6262af7bffa6388390b782e.png"></p><p>Update the value of <em>Name</em> property from <code>UserForm1</code> to <code>OurWindow</code>.</p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>From <em>Name</em> property, we access the Userform.</p></div></div><p>Update the value of <em>Caption</em> property from <code>UserForm1</code> to <code>Our Window</code>.</p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>From <em>Caption</em> property, we update the text appears in the window of our Userform.</p></div></div><p>Now, we repeat the same process for Command Button.</p><p>1st we need to select the Command Button in the user form after that we update same properties of Command Button.</p><ol><li><p>Name of Command Button</p></li><li><p>Caption of Command Button</p></li></ol><p>Update the value of <em>Name</em> property from <code>CommandButton1</code> to <code>OpenNewPartButton</code>.</p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>From <em>Name</em> property, we access the Command Button.</p></div></div><p>Update the value of <em>Caption</em> property from <code>CommandButton1</code> to <code>Open NewPart Button</code>.</p><div class="admonition admonition-note alert alert--secondary"><div class="admonition-heading"><h5><span class="admonition-icon"><svg xmlns="http://www.w3.org/2000/svg" width="14" height="16" viewBox="0 0 14 16"><path fill-rule="evenodd" d="M6.3 5.69a.942.942 0 0 1-.28-.7c0-.28.09-.52.28-.7.19-.18.42-.28.7-.28.28 0 .52.09.7.28.18.19.28.42.28.7 0 .28-.09.52-.28.7a1 1 0 0 1-.7.3c-.28 0-.52-.11-.7-.3zM8 7.99c-.02-.25-.11-.48-.31-.69-.2-.19-.42-.3-.69-.31H6c-.27.02-.48.13-.69.31-.2.2-.3.44-.31.69h1v3c.02.27.11.5.31.69.2.2.42.31.69.31h1c.27 0 .48-.11.69-.31.2-.19.3-.42.31-.69H8V7.98v.01zM7 2.3c-3.14 0-5.7 2.54-5.7 5.68 0 3.14 2.56 5.7 5.7 5.7s5.7-2.55 5.7-5.7c0-3.15-2.56-5.69-5.7-5.69v.01zM7 .98c3.86 0 7 3.14 7 7s-3.14 7-7 7-7-3.12-7-7 3.14-7 7-7z"></path></svg></span>note</h5></div><div class="admonition-content"><p>From <em>Caption</em> property, we update the text appears in the Command Button of our Userform.</p></div></div><hr><h2><a aria-hidden="true" tabindex="-1" class="anchor enhancedAnchor_2cZh" id="add-functionality-to-open-newpart-button"></a>Add Functionality to Open NewPart Button<a aria-hidden="true" tabindex="-1" class="hash-link" href="#add-functionality-to-open-newpart-button" title="Direct link to heading">#</a></h2><p>To add functionality in our <code>Open NewPart Button</code>, just double click the <code>Open NewPart Button</code>.</p><p>This will add give some code behind the designer and opens the <strong>code window</strong> of Userform designer.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Private Sub OpenNewPartButton_Click()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>We need to update this code for opening new part after clicking the button.</p><p>For this replace all above code with below code.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Option Explicit</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As SldWorks.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Creating variable for Solidworks document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swDoc As SldWorks.ModelDoc2</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Private function of Open New Part Button </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Private Sub OpenNewPartButton_Click()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting Solidworks variable to Solidworks application</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    </span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Creating string type variable for storing default part location</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Dim defaultTemplate As String</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting value of this string type variable to &quot;Default part template&quot;</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    defaultTemplate = swApp.GetUserPreferenceStringValue(swUserPreferenceStringValue_e.swDefaultTemplatePart)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Setting Solidworks document to new part document</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    Set swDoc = swApp.NewDocument(defaultTemplate, 0, 0, 0)</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>The above code will <em>open New part document</em> when we click the button.</p><p>But first, we need to call the our <em>Userform</em> inside main <strong><em>module</em></strong>.</p><p>For this goto main <code>Sub procedure</code> inside the <strong>main Module</strong>.</p><p>Code inside the main Module is as given below.</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">Dim swApp As Object</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain" style="display:inline-block">
</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Set swApp = Application.SldWorks</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>To call our Userform, replace above code with below code:</p><div class="mdxCodeBlock_1XEh"><div class="codeBlockContent_1u-d"><button tabindex="0" type="button" aria-label="Copy code to clipboard" class="copyButton_10dd">Copy</button><div class="prism-code language-vb codeBlock_3iAC"><div class="codeBlockLines_b7E3" style="color:#bfc7d5;background-color:#292d3e"><div class="token-line" style="color:#bfc7d5"><span class="token plain">&#x27; Main function of our VBA program</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">Sub main()</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    &#x27; Calling our window to show</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">    OurWindow.Show</span></div><div class="token-line" style="color:#bfc7d5"><span class="token plain">End Sub</span></div></div></div></div></div><p>Above function call our window to appears on screen.</p><p>When the window appears on screen, we hit the button.</p><p>After hitting the button, the code behind the userform run, which opens a new Part document.</p><p>If you want to know more about how we open new part with macro please see <a href="/docs/solidworks-macros/sw-macro-open-part">Open new Part document</a>.</p><p>That&#x27;s it for now.</p><p>Hope you learn some use of Userforms and by this post you can get the idea how they works.</p><p>I will provide more tutorials on using of Userform time to time.</p><p>Till then do come to visit this blog.</p><p>Till then, Happy learning!!!</p></div></article><div class="margin-vert--lg"><nav class="pagination-nav" aria-label="Blog list page navigation"><div class="pagination-nav__item"><a class="pagination-nav__link" href="/docs/vba-userforms"><div class="pagination-nav__sublabel">Previous</div><div class="pagination-nav__label">Â« VBA UserForms</div></a></div><div class="pagination-nav__item pagination-nav__item--next"><a class="pagination-nav__link" href="/docs/vba-userform/vba-userforms-open--ass-doc"><div class="pagination-nav__sublabel">Next</div><div class="pagination-nav__label">Open new Assembly and Drawing document Â»</div></a></div></nav></div></div></div><div class="col col--3"><div class="tableOfContents_3SO_"><ul class="table-of-contents table-of-contents__left-border"><li><a href="#video-of-code-on-youtube" class="table-of-contents__link">Video of Code on YouTube</a></li><li><a href="#create-a-new-macro" class="table-of-contents__link">Create a new macro</a></li><li><a href="#insert-userform-in-the-macro" class="table-of-contents__link">Insert userform in the macro</a></li><li><a href="#adding-a-button" class="table-of-contents__link">Adding a Button</a></li><li><a href="#updating-properties-of-command-button-and-userform-windows" class="table-of-contents__link">Updating Properties of Command Button and Userform Windows</a></li><li><a href="#add-functionality-to-open-newpart-button" class="table-of-contents__link">Add Functionality to Open NewPart Button</a></li></ul></div></div></div></div></main></div></div><footer class="footer"><div class="container"><div class="row footer__links"><div class="col footer__col"><h4 class="footer__title">Tutorials</h4><ul class="footer__items"><li class="footer__item"><a class="footer__link-item" href="/docs/vba-Intro">VBA Introduction</a></li><li class="footer__item"><a class="footer__link-item" href="/docs/vba-in-sw">VBA in Solidworks</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">Community</h4><ul class="footer__items"><li class="footer__item"><a href="https://www.facebook.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Facebook</a></li><li class="footer__item"><a href="https://www.youtube.com/channel/UCm_VglqA2S4WUXM55vyqAFg" target="_blank" rel="noopener noreferrer" class="footer__link-item">YouTube</a></li></ul></div><div class="col footer__col"><h4 class="footer__title">More</h4><ul class="footer__items"><li class="footer__item"><a href="mailto:thecadcoder@gmail.com" target="_blank" rel="noopener noreferrer" class="footer__link-item">E-Mail</a></li><li class="footer__item"><a href="https://www.buymeacoffee.com/thecadcoder" target="_blank" rel="noopener noreferrer" class="footer__link-item">Buy Me a Coffee</a></li></ul></div></div><div class="text--center"><div>Copyright Â© 2020 The Cad Coder, Inc. Built with Docusaurus.</div></div></div></footer></div>
<script src="/styles.49bb2333.js"></script>
<script src="/runtime~main.ab11de34.js"></script>
<script src="/main.e8afb781.js"></script>
<script src="/1.ccf2966d.js"></script>
<script src="/2.ea84abb6.js"></script>
<script src="/94.6ee319b8.js"></script>
<script src="/95.e3f7e856.js"></script>
<script src="/f976f453.85830ae4.js"></script>
<script src="/17896441.7cfb19b7.js"></script>
<script src="/27d0949a.b40297e0.js"></script>
</body>
</html>