I"Ë,<h2 id="introduction">Introduction</h2>

<p>In this post, we <strong>test</strong> our <strong>Open new Assembly and Drawing document</strong> code sample.</p>

<p>This post is supplement of <strong><a href="/vba/open-assembly-and-drawing-from-userform/">VBA Userforms - Open new Assembly and Drawing document</a></strong> post.</p>

<blockquote>
  <p><em>Please visit above post before this post.</em></p>
</blockquote>

<p>From <strong><a href="/vba/open-assembly-and-drawing-from-userform/">VBA Userforms - Open new Assembly and Drawing document</a></strong> post we expect following results :</p>

<ol>
  <li>
    <p><strong>Open Assembly</strong> document when we select ‚Äú<em>Assembly document</em>‚Äù.</p>
  </li>
  <li>
    <p><strong>Open Drawing</strong> document when we select ‚Äú<em>Drawing document</em>‚Äù.</p>
  </li>
</ol>

<p>When we run our <strong>VBA macro</strong> we get the expected result.</p>

<p><em>Now, as a developer, we want to give a thoroughly tested macro/application to our users.</em></p>

<p>For testing our VBA macro, we apply some checks so that macro perform same at all machine.</p>

<hr />

<h2 id="code-block-to-check">Code block to check</h2>

<p>Below is code block where we want to apply our check.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">Option</span> <span class="n">Explicit</span>

<span class="c1">' Creating variable for Solidworks application</span>
<span class="k">Dim</span> <span class="nv">swApp</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">SldWorks</span>
<span class="c1">' Creating variable for Solidworks document</span>
<span class="k">Dim</span> <span class="nv">swDoc</span> <span class="ow">As</span> <span class="n">SldWorks</span><span class="p">.</span><span class="n">ModelDoc2</span>

<span class="c1">' Private function of Open New Part Button </span>
<span class="k">Private</span> <span class="k">Sub</span> <span class="nf">OpenDocumentButton_Click</span><span class="p">()</span>

  <span class="c1">' Setting Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Creating string type variable for storing default Assembly location</span>
  <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
  
  <span class="k">If</span> <span class="n">DocumentTypeComboBox</span><span class="p">.</span><span class="n">Value</span> <span class="o">=</span> <span class="s">"Assembly Document"</span> <span class="k">Then</span>
    <span class="c1">' Setting value of this string type variable to "Default Assembly template"</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplateAssembly</span><span class="p">)</span>
  <span class="k">Else</span>
    <span class="c1">' Setting value of this string type variable to "Default drawing template" without define paper size</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplateDrawing</span><span class="p">)</span>
  <span class="k">End</span> <span class="k">If</span>

  <span class="c1">' Setting Solidworks document to new Assembly document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
  
  <span class="c1">' Hiding the Window after opening the selected document</span>
  <span class="n">OpenDocumentWindow</span><span class="p">.</span><span class="n">Hide</span>
  
  <span class="c1">' Reset the Index of Combo Box to "0" again</span>
  <span class="n">DocumentTypeComboBox</span><span class="p">.</span><span class="n">ListIndex</span> <span class="o">=</span> <span class="mi">0</span>
    
<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<hr />

<h2 id="apply-check">Apply check</h2>

<p>In above code there is only <strong>one</strong> check we apply.</p>

<p><strong><em>We need to check if get the template value or not.</em></strong></p>

<p>For this, we need to put an <code class="language-plaintext highlighter-rouge">If</code> condition before opening a new document.</p>

<p>Please see below code for condition.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Checking if we got template path</span>
<span class="k">If</span> <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">vbNullString</span> <span class="k">Then</span>
    <span class="c1">' If template path is empty then show message and exit from procedure.</span>
    <span class="n">MsgBox</span> <span class="s">"Failed to open "</span> <span class="o">+</span> <span class="n">DocumentTypeComboBox</span><span class="p">.</span><span class="n">Value</span> <span class="o">+</span> <span class="s">" template."</span>
    <span class="k">Exit</span> <span class="k">Sub</span>
<span class="nf">End</span> <span class="k">If</span>
</code></pre></div></div>

<p>In above code, we check <em>if got the template path or not</em>.</p>

<p>If template path is <strong>empty</strong> then</p>

<ol>
  <li>we <em>show a message</em> to user as show in below image.</li>
  <li>we <strong>end</strong> our <code class="language-plaintext highlighter-rouge">sub</code> procedure from here.</li>
</ol>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/error-message-on-empty-template.png" alt="error-message-on-empty-template" /></p>

<p>After adding our check, procedure has following code.</p>

<div class="language-vb highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="c1">' Private function of Open New Part Button</span>
<span class="k">Private</span> <span class="k">Sub</span> <span class="nf">OpenDocumentButton_Click</span><span class="p">()</span>

  <span class="c1">' Setting Solidworks variable to Solidworks application</span>
  <span class="k">Set</span> <span class="n">swApp</span> <span class="o">=</span> <span class="n">Application</span><span class="p">.</span><span class="n">SldWorks</span>
  
  <span class="c1">' Creating string type variable for storing default Assembly location</span>
  <span class="k">Dim</span> <span class="nv">defaultTemplate</span> <span class="ow">As</span> <span class="kt">String</span>
  
  <span class="k">If</span> <span class="n">DocumentTypeComboBox</span><span class="p">.</span><span class="n">Value</span> <span class="o">=</span> <span class="s">"Assembly Document"</span> <span class="k">Then</span>
    <span class="c1">' Setting value of this string type variable to "Default Assembly template"</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplateAssembly</span><span class="p">)</span>
  <span class="k">Else</span>
    <span class="c1">' Setting value of this string type variable to "Default drawing template" without define paper size</span>
    <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">GetUserPreferenceStringValue</span><span class="p">(</span><span class="n">swUserPreferenceStringValue_e</span><span class="p">.</span><span class="n">swDefaultTemplateDrawing</span><span class="p">)</span>
  <span class="k">End</span> <span class="k">If</span>
  
  <span class="c1">' Checking if we got template path</span>
  <span class="k">If</span> <span class="n">defaultTemplate</span> <span class="o">=</span> <span class="n">vbNullString</span> <span class="k">Then</span>
    <span class="c1">' If template path is empty then show message and exit from procedure.</span>
    <span class="n">MsgBox</span> <span class="s">"Failed to open "</span> <span class="o">+</span> <span class="n">DocumentTypeComboBox</span><span class="p">.</span><span class="n">Value</span> <span class="o">+</span> <span class="s">" template."</span>
    <span class="k">Exit</span> <span class="k">Sub</span>
  <span class="nf">End</span> <span class="k">If</span>

  <span class="c1">' Setting Solidworks document to new Assembly document</span>
  <span class="k">Set</span> <span class="n">swDoc</span> <span class="o">=</span> <span class="n">swApp</span><span class="p">.</span><span class="n">NewDocument</span><span class="p">(</span><span class="n">defaultTemplate</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">)</span>
  
  <span class="c1">' Hiding the Window aft er opening the selected document</span>
  <span class="n">OpenDocumentWindow</span><span class="p">.</span><span class="n">Hide</span>
  
  <span class="c1">' Reset the Index of Combo Box to "0" again</span>
  <span class="n">DocumentTypeComboBox</span><span class="p">.</span><span class="n">ListIndex</span> <span class="o">=</span> <span class="mi">0</span>
    
<span class="k">End</span> <span class="k">Sub</span>
</code></pre></div></div>

<hr />

<h2 id="cause-of-error">Cause of Error</h2>

<p><em>You might wondering how can we have such error?</em></p>

<p>We have this error, if the value of templates path is <strong>not set</strong> in option setting.</p>

<p>For reference please see below image.</p>

<p><img src="/assets/vba-images/Open_assembly_and_drawing_from_Userform/default-template-options.png" alt="default-template-options" /></p>

<p>As you can see, in my machine these value are already set.</p>

<p>But they are empty in case of fresh installation.</p>

<p>Hence if someone runs this macro on fresh SOLIDWORKS copy, they might get error message which we give.</p>

<hr />

<p><strong>This is it !!!</strong></p>

<p><em>I hope this be will helpful to someone!</em></p>

<p>If you found anything to <strong>add or update</strong>, please let me know on my <em>e-mail</em> which is given in bottom.</p>

<p>this post helps us to <strong>test</strong> our <strong>Open new Assembly and Drawing document</strong> macro.</p>

<p><strong>We will see this type of testing of all our macros which we in this website.</strong></p>

<p><em>If you like the post then please share it with your friends also.</em></p>

<p><em>Do let me know by you like this post or not!</em></p>

<p><em>Till then, Happy learning!!!</em></p>
:ET